### DISCUSSION TITLE
Problem to create RDSInstance through compositions

### DISCUSSION THREAD

**Discussion by danielmrosa** [crossplane/crossplane#2208] [Q&A] [answered]
Hi,
I'm trying to deploy one RDS instance using compositions. If I deploy directly using Kind RDSInstance manifest, it works, but the instance is never created if I try using the compositions below :

**Composition**

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositepostgresqlinstances.aws.database.example.org
  labels:
    provider: provider-aws
    guide: quickstart
    vpc: vpc-0d2919fb7668f8ea9
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: CompositePostgreSQLInstance
  resources:
    - name: rdsinstance
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            dbSubnetGroupName: "orange-subnet-group"
            region: sa-east-1
            vpcSecurityGroupIds: ["sg-0a0696c50793457be"]
            allocatedStorage: 20
            autoMinorVersionUpgrade: true
            backupRetentionPeriod: 0
            caCertificateIdentifier: rds-ca-2019
            copyTagsToSnapshot: false
            dbInstanceClass: db.t3.medium
            deletionProtection: false
            enableIAMDatabaseAuthentication: false
            enablePerformanceInsights: false
            engine: postgres
            engineVersion: "13"
            finalDBSnapshotIdentifier: orange-test
            masterUsername: orange
            multiAZ: false
            port: 5432
            preferredBackupWindow: 06:15-06:45
            preferredMaintenanceWindow: sat:09:21-sat:09:51
            publiclyAccessible: false
            storageEncrypted: false
            storageType: gp2
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: default
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
```
**CompositeResourceDefinition**

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.database.example.org
spec:
  group: database.example.org
  names:
    kind: CompositePostgreSQLInstance
    plural: compositepostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                required:
                  - storageGB
            required:
              - parameters
```
***XR***
```
apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: orange-test-composition
  namespace: crossplane-system
spec:
  parameters:
    storageGB: 10
  compositionSelector:
    matchLabels:
      provider: provider-aws
  writeConnectionSecretToRef:
    name: db-orange-test-composition
```

***k get Compositeresourcedefinitions compositepostgresqlinstances.database.example.org***

```
NAME                                                ESTABLISHED   OFFERED   AGE
compositepostgresqlinstances.database.example.org   True          True      53m
```

***k describe CompositeResourceDefinition compositepostgresqlinstances.database.example.org***
```
Events:
  Type     Reason              Age              From                                                             Message
  ----     ------              ----             ----                                                             -------
  Normal   RenderCRD           7s (x8 over 7s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Rendered composite resource CustomResourceDefinition
  Warning  OfferClaim          7s               offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot add composite resource claim finalizer: cannot update object: Operation cannot be fulfilled on compositeresourcedefinitions.apiextensions.crossplane.io "compositepostgresqlinstances.database.example.org": the object has been modified; please apply your changes to the latest version and try again
  Normal   EstablishComposite  7s (x5 over 7s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Applied composite resource CustomResourceDefinition
  Normal   EstablishComposite  7s               defined/compositeresourcedefinition.apiextensions.crossplane.io  waiting for composite resource CustomResourceDefinition to be established
  Warning  EstablishComposite  7s (x3 over 7s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot apply rendered composite resource CustomResourceDefinition: cannot update object: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "compositepostgresqlinstances.database.example.org": the object has been modified; please apply your changes to the latest version and try again
  Normal   OfferClaim          7s               offered/compositeresourcedefinition.apiextensions.crossplane.io  waiting for composite resource claim CustomResourceDefinition to be established
  Warning  OfferClaim          7s               offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot apply rendered composite resource claim CustomResourceDefinition: cannot create object: customresourcedefinitions.apiextensions.k8s.io "postgresqlinstances.database.example.org" already exists
  Normal   EstablishComposite  7s (x4 over 7s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  (Re)started composite resource controller
  Normal   ApplyClusterRoles   7s (x2 over 7s)  rbac/compositeresourcedefinition.apiextensions.crossplane.io     Applied RBAC ClusterRoles
  Normal   RenderCRD           4s (x6 over 7s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Rendered composite resource claim CustomResourceDefinition
  Normal   OfferClaim          4s (x4 over 7s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Applied composite resource claim CustomResourceDefinition
  Normal   OfferClaim          4s (x3 over 7s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  (Re)started composite resource claim controller
```

k get PostgreSQLInstance -n crossplane-system
```
NAME                      READY   CONNECTION-SECRET            AGE
orange-test-composition   False   db-orange-test-composition   30s
```

***k describe PostgreSQLInstance -n crossplane-system orange-test-composition***
```
Events:
  Type     Reason                      Age                From                                                             Message
  ----     ------                      ----               ----                                                             -------
  Warning  ConfigureCompositeResource  81s (x2 over 81s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot patch object: Operation cannot be fulfilled on compositepostgresqlinstances.database.example.org "orange-test-composition-7w426": the object has been modified; please apply your changes to the latest version and try again
  Normal   ConfigureCompositeResource  51s (x4 over 81s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully applied composite resource
  Normal   BindCompositeResource       51s (x4 over 81s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Composite resource is not yet ready
```
