### DISCUSSION TITLE
Example to create RDS Instance using compositions

### DISCUSSION THREAD

**Discussion by danielmrosa** [crossplane/crossplane#2209] [Knowledge base]
Hi All,
Follow below a small example to how deploy one RDS Instance using engine postgreSQL on AWS using crossplane compositions. From this example, you can improve and create one complex composition :-)

***Notes:***
On Composition, you just need to replace the fields : vpc,dbSubnetGroupName,vpcSecurityGroupIds and the properties inside on Kind RDSInstance as well.

Consider that I'm using provider called provider-aws. Remember to change to your provider name if needed.
I assume you already have VPC, DBSubnet group, Security Groups, etc. But, you can create them using crossplane as well.

***Composition***

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositepostgresqlinstances.aws.database.example.org
  labels:
    provider: provider-aws
    guide: quickstart
    vpc: vpc-0d2919fb7668f8ea9
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: CompositePostgreSQLInstance
  resources:
    - name: rdsinstance
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          providerConfigRef:
            name: provider-aws
          forProvider:
            dbSubnetGroupName: "orange-subnet-group"
            region: sa-east-1
            vpcSecurityGroupIds: ["sg-0a0696c50793457be"]
            allocatedStorage: 20
            autoMinorVersionUpgrade: true
            backupRetentionPeriod: 0
            caCertificateIdentifier: rds-ca-2019
            copyTagsToSnapshot: false
            dbInstanceClass: db.t3.medium
            deletionProtection: false
            enableIAMDatabaseAuthentication: false
            enablePerformanceInsights: false
            engine: postgres
            engineVersion: "13"
            finalDBSnapshotIdentifier: orange-test
            masterUsername: orange
            multiAZ: false
            port: 5432
            preferredBackupWindow: 06:15-06:45
            preferredMaintenanceWindow: sat:09:21-sat:09:51
            publiclyAccessible: false
            storageEncrypted: false
            storageType: gp2
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: default
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
```

***CompositeResourceDefinition***

````
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.database.example.org
spec:
  group: database.example.org
  names:
    kind: CompositePostgreSQLInstance
    plural: compositepostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  versions:
  - name: v1alpha1
    served: truea
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                required:
                  - storageGB
            required:
              - parameters
````

***PostgreSQLInstance***

````
apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: orange-test-composition
  namespace: crossplane-system
spec:
  parameters:
    storageGB: 10
  compositionSelector:
    matchLabels:
      provider: provider-aws
  writeConnectionSecretToRef:
    name: db-orange-test-composition
