### DISCUSSION TITLE
Example using gitlab project and deploy gitlab-ci runner

### DISCUSSION THREAD

**Discussion by janwillies** [crossplane/crossplane#2264] [Show and tell]
The following composition will create a gitlab repository, import a spring boot java blueprint and deploy a gitlab-ci runner connected to the repository:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: application
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: cnp.example.corp/v1alpha1
    kind: CompositeApplication
  resources:
  - name: gitlab-project
    base:
      apiVersion: projects.gitlab.crossplane.io/v1alpha1
      kind: Project
      spec:
        forProvider:
          namespaceId: <insert existing group-id from gitlab>
          importUrl: # patched
          description: "an example project"
          sharedRunnersEnabled: false
        providerConfigRef:
          name: gitlab-provider
        writeConnectionSecretToRef:
          name: # patched
          namespace: crossplane-system
    patches:
    - fromFieldPath: "metadata.name"
      toFieldPath: "metadata.name"
    - fromFieldPath: "metadata.name"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
        - type: string
          string:
            fmt: "%s-project"
    - type: ToCompositeFieldPath
      fromFieldPath: "status.atProvider.httpUrlToRepo"
      toFieldPath: "status.httpUrlToRepo"
    - fromFieldPath: "spec.language"
      toFieldPath: "spec.forProvider.importUrl"
      transforms:
      - type: map
        map:
          java: https://gitlab.com/janwillies/application-blueprint.git
    connectionDetails:
    - name: runnerRegistrationToken
      fromConnectionSecretKey: runnersToken
  - name: gitlab-ci
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      spec:
        forProvider:
          chart:
            name: gitlab-runner
            repository: https://charts.gitlab.io
            version: 0.27.0
          namespace: gitlab-ci
          values:
            gitlabUrl: https://gitlab.com/
          set:
            - name: runnerRegistrationToken
              valueFrom:
                secretKeyRef:
                  name: # patched
                  namespace: crossplane-system
                  key: runnerRegistrationToken
        providerConfigRef:
          name: helm-provider
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-gitlab-ci"
    - fromFieldPath: metadata.uid
      toFieldPath: spec.forProvider.set[0].valueFrom.secretKeyRef.name
    readinessChecks:
      - type: None
```
xrd:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeapplications.cnp.example.corp
spec:
  connectionSecretKeys:
    - runnerRegistrationToken
  defaultCompositionRef:
    name: application
  claimNames:
    kind: Application
    plural: applications
  group: cnp.example.corp
  names:
    kind: CompositeApplication
    listKind: CompositeApplicationList
    plural: compositeapplications
    singular: compositeapplication
  versions: 
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              language:
                description: Language of the Application 
                type: string
          status:
            type: object
            properties:
              httpUrlToRepo:
                description: Address of this GitLab Project.
                type: string
```
xrc:
```yaml
apiVersion: cnp.example.corp/v1alpha1
kind: Application
metadata:
  name: example-app
spec:
  language: java
```
