### DISCUSSION TITLE
AWS ECR example - controlling external name, categories and additional printer columns

### DISCUSSION THREAD

**Discussion by chlunde** [crossplane/crossplane#2286] [Show and tell]
Here's an example showing a few different things:

* customizing columns shown with `kubectl get` to improve developer experience (see `additionalPrinterColumns`)
* using categories to allow a developer to find relevant app resources by adding `categories` (`kubectl get platform` will show this resource and all other resources tagged this way).
* controlling the external name with a prefix
* ECR

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeimagerepositories.aws.cloud.example.com
spec:
  claimNames:
    kind: ImageRepository
    plural: imagerepositories
    categories:
    - platform
  group: aws.cloud.example.com
  names:
    kind: CompositeImageRepository
    plural: compositeimagerepositories
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    additionalPrinterColumns:
    - jsonPath: .status.repositoryUri
      name: REPOSITORY-URI
      type: string
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    type: string
                    description: "Name of container image repository (will get prefixed with dev/)"
                required:
                  - name
            required:
              - parameters
          status:
            type: object
            properties:
              repositoryUri:
                description: URI of container image repository
                type: string
```

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositeimagerepositories.aws.cloud.example.com
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: aws.cloud.example.com/v1alpha1
    kind: CompositeImageRepository
  resources:
    - base:
        apiVersion: ecr.aws.crossplane.io/v1alpha1
        kind: Repository
        spec:
          forProvider:
            imageScanningConfiguration:
              scanOnPush: true
            imageTagMutability: MUTABLE
            region: eu-north-1
          deletionPolicy: Delete
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
          transforms:
            - type: string
              string:
                fmt: "dev/%s"
        - fromFieldPath: "status.atProvider.repositoryUri"
          toFieldPath: "status.repositoryUri"
          type: ToCompositeFieldPath
```
