### DISCUSSION TITLE
Example S3 bucket, with IAM user, and templated IAMPolicy

### DISCUSSION THREAD

**Discussion by adamkirk** [crossplane/crossplane#2399] [Show and tell]
The following XRD and composition will create an s3 bucket, with an IAM user and access key that has access to manage the bucket. It uses the patch type 'CombineFromComposite', which was added in 1.3.0 and is not fully released at the time of writing, so that I could use a template for the IAM policy json. The main goal for this, was to hide any complexity from the developers about how this bucket is created or accessed.

This is the XRD:

```
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeobjectstoragebuckets.example.org
spec:
  group: example.org
  names:
    kind: CompositeObjectStorageBucket
    plural: compositeobjectstoragebuckets
  claimNames:
    kind: ObjectStorageBucket
    plural: objectstoragebuckets
  connectionSecretKeys:
    - account_id
    - account_key
    - bucket_name
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  # The full name of the bucket
                  name:
                    type: string
                required:
                  - name
            required:
              - parameters

```

This just has 1 parameter which is bucket name. 

The following composition satisfies the XRD. It contains 5 resources: S3 bucket, iam policy, iam user, iam user policy attachment, and iam access key. The access key credentials and bucket name are exposed by the connection secret. The access key will give access to this bucket and nothing else.

```
# Private S3 Object Storage Bucket
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: privates3objectstoragebucket
  labels:
    provider: aws
    # Could have multiple classes, for different purposes
    class: default
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: CompositeObjectStorageBucket
  resources:
    - base:
        # See s3 bucket API ref: https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/Bucket/v1beta1@v0.19.0
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: default
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            acl: "private"
            locationConstraint: us-east-1
      patches:
        # We'll use the name defined in the claim/composite resource for the bucket name
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
        # Write the bucket information to a secret called: {bucket_name}-connection-details
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-connection-details"
      connectionDetails:
        # The resulting secret contains a bucket_name key
        # This key contains the value that was generated by the bucket resource in the endpoint key
        - name: bucket_name
          fromConnectionSecretKey: endpoint
    - base:
        # See IamPolicy Api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMPolicy/v1alpha1@v0.19.0
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMPolicy
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: default
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            path: "/"
      patches:
        # We'll use the name defined in the claim/composite resource for the bucket name
        # We suffix it with '-bucket-access-policy'
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        # Use the bucket name + the '-bucket-access-policy' suffix
        # This will be the resulting name in aws
        # Each bucket name must be unique, so this in turn will be unique
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.description"
          transforms:
          - type: string
            string:
              fmt: "Policy for access to the %s bucket"
        # CombineForComposite works just like the string transforms above
        # Except we can define multiple placeholders in the fmt
        # We need crossplane >= 1.3.0 for this feature
        - type: CombineFromComposite
          toFieldPath: "spec.forProvider.document"
          policy:
            fromFieldPath: Required
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.name
            strategy: string
            # This policy gives a user full access to the bucket and bucket objects
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Action": ["s3:*"],
                      "Resource": [
                        "arn:aws:s3:::%s"
                      ]
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "s3:*"
                      ],
                      "Resource": [
                        "arn:aws:s3:::%s",
                        "arn:aws:s3:::%s/*"
                      ]
                    }
                  ]
                }
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-policy-details"
    - base:
        # See IamUser api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMUser/v1alpha1@v0.19.0
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMUser
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: default
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            path: "/"
      patches:
        # Use bucket name suffixed with '-user'
        # This will be the username of the iam account in AWS
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-details"
    - base:
        # See IamUserPolicyAttachment api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMUserPolicyAttachment/v1alpha1@v0.19.0
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMUserPolicyAttachment
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: default
          writeConnectionSecretToRef:
            namespace: crossplane-system
          # The contents of this are patched in below
          forProvider: {}
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-bucket-policy"
        # Reference the policy we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.policyArnRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        # Reference the user we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.userNameRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-details"
    - base:
        # See IAMAccessKey api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMAccessKey/v1alpha1@v0.19.0
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMAccessKey
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: default
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider: {}
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-access-key"
        # Reference the user we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.userNameRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-access-key"
      connectionDetails:
        # We take the username key from the access key and set it to the account_id in the resulting secret
        - name: account_id
          fromConnectionSecretKey: username
        # We take the password key from the access key and set it to the account_key in the resulting secret
        - name: account_key
          fromConnectionSecretKey: password
```

This is an example of how to create a claim for this resource:

```
---
apiVersion: example.org/v1alpha1
kind: ObjectStorageBucket
metadata:
  namespace: hello-world
  name: my-bucket
spec:
  parameters:
    # You would need to change this to something unique
    name: "my-bucket"
  compositionSelector:
    matchLabels:
      provider: aws
      class: default
  writeConnectionSecretToRef:
    name: my-bucket-connection
```

**Comment by jbw976** [comment]
i love this all-in-one storage bucket abstraction that is usable in the real world @adamkirk, thank you so much for sharing this with the community! 🎉

**Comment by uluzox** [comment]
For users of crossplane < 1.3.0, you can use `%[1]s` (props to [icza](https://stackoverflow.com/a/37001642)) and do the following (if you always replace the same string):

```
- fromFieldPath: "spec.parameters.name"
  toFieldPath: "spec.forProvider.document"
  transforms:
  - type: string
    # This policy gives a user full access to the bucket and bucket objects
      fmt: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": ["s3:*"],
              "Resource": [
                "arn:aws:s3:::%[1]s"
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:*"
              ],
              "Resource": [
                "arn:aws:s3:::%[1]s",
                "arn:aws:s3:::%[1]s/*"
              ]
            }
          ]
        }
```

**Comment by rezuma** [comment]
This is great, but in my case I have a composition creating 3 buckets and 1 Bucket policy, so I handle that since all buckets created have  - fromFieldPath: spec.parameters.name or in my case I am using status.atProvider.arn

the end policy resource section needs to look something like this
                  "Resource": [
                      "arn:aws:s3:::oss-projectname-use1-users",
                      "arn:aws:s3:::oss-projectname-use1-users/*",
                      "arn:aws:s3:::oss-projectname-use1-shared",
                      "arn:aws:s3:::oss-projectname-use1-shared/*",
                      "arn:aws:s3:::oss-projectname-use1-curated",
                      "arn:aws:s3:::oss-projectname-use1-curated/*"
                  ]

**Comment by martivo** [comment]
Updated this for using xpkg.upbound.io/crossplane-contrib/provider-aws:v0.42.0
Some of the api versions and object Kind fields had changed and also the UserPolicyAttachment required different secret name from User.
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeobjectstoragebuckets.example.com
spec:
  group: example.com
  names:
    kind: CompositeObjectStorageBucket
    plural: compositeobjectstoragebuckets
  claimNames:
    kind: ObjectStorageBucket
    plural: objectstoragebuckets
  connectionSecretKeys:
    - account_id
    - account_key
    - bucket_name
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  # The full name of the bucket
                  name:
                    type: string
                required:
                  - name
            required:
              - parameters
---
# Private S3 Object Storage Bucket
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: privates3objectstoragebucket
  labels:
    provider: aws
    # Could have multiple classes, for different purposes
    class: default
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: CompositeObjectStorageBucket
  resources:
    - base:
        # See s3 bucket API ref: https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/Bucket/v1beta1@v0.19.0
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-crossplane-system
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            acl: "private"
            locationConstraint: eu-north-1
            objectOwnership: BucketOwnerPreferred
            publicAccessBlockConfiguration:
              blockPublicPolicy: true
              blockPublicAcls: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            accelerateConfiguration:
              status: Enabled
            versioningConfiguration:
              status: Suspended
            serverSideEncryptionConfiguration:
              rules:
              - applyServerSideEncryptionByDefault:
                  sseAlgorithm: AES256
      patches:
        # We'll use the name defined in the claim/composite resource for the bucket name
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
        # Write the bucket information to a secret called: {bucket_name}-connection-details
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-connection-details"
      connectionDetails:
        # The resulting secret contains a bucket_name key
        # This key contains the value that was generated by the bucket resource in the endpoint key
        - name: bucket_name
          fromConnectionSecretKey: endpoint
    - base:
        # See IamPolicy Api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMPolicy/v1alpha1@v0.19.0
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-crossplane-system
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            path: "/"
      patches:
        # We'll use the name defined in the claim/composite resource for the bucket name
        # We suffix it with '-bucket-access-policy'
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        # Use the bucket name + the '-bucket-access-policy' suffix
        # This will be the resulting name in aws
        # Each bucket name must be unique, so this in turn will be unique
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.description"
          transforms:
          - type: string
            string:
              fmt: "Policy for access to the %s bucket"
        # CombineForComposite works just like the string transforms above
        # Except we can define multiple placeholders in the fmt
        # We need crossplane >= 1.3.0 for this feature
        - type: CombineFromComposite
          toFieldPath: "spec.forProvider.document"
          policy:
            fromFieldPath: Required
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.name
            strategy: string
            # This policy gives a user full access to the bucket and bucket objects
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Action": ["s3:*"],
                      "Resource": [
                        "arn:aws:s3:::%s"
                      ]
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "s3:*"
                      ],
                      "Resource": [
                        "arn:aws:s3:::%s",
                        "arn:aws:s3:::%s/*"
                      ]
                    }
                  ]
                }
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-policy-details"
    - base:
        # See IamUser api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMUser/v1alpha1@v0.19.0
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: User
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-crossplane-system
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            path: "/"
      patches:
        # Use bucket name suffixed with '-user'
        # This will be the username of the iam account in AWS
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-details"
    - base:
        # See IamUserPolicyAttachment api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMUserPolicyAttachment/v1alpha1@v0.19.0
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: UserPolicyAttachment
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-crossplane-system
          writeConnectionSecretToRef:
            namespace: crossplane-system
          # The contents of this are patched in below
          forProvider: {}
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-bucket-policy"
        # Reference the policy we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.policyArnRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        # Reference the user we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.userNameRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-policy-details"
    - base:
        # See IAMAccessKey api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMAccessKey/v1alpha1@v0.19.0
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: AccessKey
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-crossplane-system
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider: {}
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-access-key"
        # Reference the user we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.userNameRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-access-key"
      connectionDetails:
        # We take the username key from the access key and set it to the account_id in the resulting secret
        - name: account_id
          fromConnectionSecretKey: username
        # We take the password key from the access key and set it to the account_key in the resulting secret
        - name: account_key
          fromConnectionSecretKey: password
---
apiVersion: example.com/v1alpha1
kind: ObjectStorageBucket
metadata:
  namespace: app-u1-dev
  name: entigobucketexampletest
spec:
  parameters:
    # You would need to change this to something unique
    name: "entigobucketexampletest"
  compositionSelector:
    matchLabels:
      provider: aws
      class: default
  writeConnectionSecretToRef:
    name: entigobucketexampletest
```
