### DISCUSSION TITLE
Pushing Provider Package to Registry Other Than Docker Hub

### DISCUSSION THREAD

**Discussion by morningspace** [crossplane/crossplane#2475] [Knowledge base]
A Crossplane provider can be packaged as an OCI image, i.e. a [Crossplane package], and pushed to an OCI-compatible registry, so it can be pulled from there by other people who want to install the provider.

By default, most Crossplane providers use [Docker Hub] as the target registry to push their Provider packages. Crossplane also allows you to push packages to other registries. As a provider developer, in order to push package to other registry such as `quay.io`. You got a couple of things to do.

* You need to modify the provider `crossplane.yaml` file, change the `spec.controller.image` to point to the right registry. Otherwise, when install the provider, it will still go back to check Docker Hub. Below is an example:

```yaml
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-kubernetes
  annotations:
    descriptionShort: |
      The Crossplane Kubernetes provider enables management of Kubernetes Objects.
spec:
  controller:
    image: quay.io/morningspace/provider-kubernetes-controller-amd64:VERSION
```

* Most providers define `DOCKER_REGISTRY` with the default value `crossplane` in their `Makefile` files. This is required by the provider build scripts to push to the target registry. This also needs to be updated to reflect the registry change. For example:

```Makefile
# DOCKER_REGISTRY = crossplane
DOCKER_REGISTRY = quay.io/morningspace
```

After then, you should be able to build, then publish your Provider package to the registry by executing below command:

```console
make build publish
```

Note:
If you push Provider package to a private registry, please make sure you login to the registry at first. Also, when you pull package from there, please make sure you specify the [spec.packagePullSecrets] when define `provider.pkg.crossplane.io` resource.

[Crossplane package]: https://crossplane.io/docs/v1.3/concepts/packages.html
[Docker Hub]: https://hub.docker.com/
[spec.packagePullSecrets]: https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Provider/v1@v1.3.0#spec-packagePullSecrets

**Update (May 2023)**

Please also see the following solution for providers using the latest build machinery: https://github.com/crossplane/crossplane/discussions/3817

**Comment by turkenh** [comment]
@morningspace Thanks a lot for adding this here!

I believe you would need to run `make build` at some point before `make publish` right? 
Should we simply update `make publish` step as `make build publish` ?

**Reply by morningspace** [reply]
@turkenh Sure, thanks for your suggestion! I just updated the above content to reflect this comment.

**Comment by hkassaei** [comment]
Can you also provide an example on how to install a configuration package from a private repository in ECR into an eks cluster? I tried following the schema in [this schema definition](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Configuration/v1@v1.5.1) to add packagePullSecrets and create a secrete that includes ECR credentials, something like this:

```
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-credentials
  annotations:
    provider: aws
    registry: aws-ecr
spec:
  package: postgres-aws-rds
  packagePullPolicy: Always
  packagePullSecrets: 
  - name: aws-ecr-creds

```  
 but then when trying to build the configuration package:
$ kubectl crossplane build configuration 

I get this error:
$kubectl crossplane: error: failed to build package: failed to parse package: {path:/home/user1/crossplane-config/crossplane.yaml position:0}: no kind "Configuration" is registered for version "pkg.crossplane.io/v1" in scheme "/home/runner/work/crossplane/crossplane/internal/xpkg/scheme.go:47"

What am I missing?

**Reply by hasheddan** [reply]
@hkassaei the issue here is conflation of [`Configuration.pkg.crossplane.io`](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Configuration/v1@v1.5.1) and [`Configuration.meta.pkg.crossplane.io`](https://doc.crds.dev/github.com/crossplane/crossplane/meta.pkg.crossplane.io/Configuration/v1@v1.5.1). The former is used to _install_ a `Configuration` while the latter is used to _build_ one. More details here: https://crossplane.io/docs/v1.5/concepts/packages.html#configuration-packages

**Reply by hkassaei** [reply]
@hasheddan Thanks for the prompt reply! I see what I missed now. I also realized I'd misunderstood the nuance completely. I think I'm partly to blame for not having read the configuration chapter more carefully, but isn't the term configuration also a bit overloaded? 

So there is a "configuration package" that one is supposed to create and push to an OCI compliant repo. This package contains a 'meta configuration', a composite resource definition, and a composition, which basically defines the mapping between a composite resource and one or more actual underlying resource(s).

Then there is a configuration package that one is supposed to install in the crossplane namespace in the k8s cluster. This package actually contains configuration needed by crossplane to be able to fetch the above configuration package from the OCI compliant repo, among other things.

Finally, I also see a ProviderConfig which, similar to the above, is installed in the crossplane namespace and configures crossplane provider to be able to access the underlying managed resources.

 Now putting it all together and assuming I got it right this time around, does the first package also need to be called configuration package?
 
 I might've digressed a bit and forgot about my original question :-) How should one provide the packagePullSecrets in the "installed configuration" to enable crossplane to access the configuration package that I've pushed to my private repo? Would something like this work?
 ```
spec:
  package: <aws-account-id>.dkr.ecr.ca-central-1.amazonaws.com/postgres-aws-rds:v0.1.0
  packagePullPolicy: IfNotPresent
  packagePullSecrets: 
  - name: aws-ecr-creds
```
And what does crossplane expect the format and content of the secret to be? I saw this in the documentations "This field allows a user to provide credentials required to pull a package from a private repository on a registry." and assumed what I see in the docker config.json file should be enough, but it didn't work. I see the following error when I 'describe' the created custom object:
```
Events:
  Type     Reason         Age                 From                                      Message
  ----     ------         ----                ----                                      -------
  Warning  UnpackPackage  61s (x63 over 31m)  packages/configuration.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: HEAD https://<_aws-account-id_>.dkr.ecr.ca-central-1.amazonaws.com/v2/postgres-aws-rds/manifests/v0.1.0: unexpected status code 401 Unauthorized (HEAD responses have no body, u
```se GET for details)
