### DISCUSSION TITLE
Route53 subdomain delegation - take data from one object and use them in another one

### DISCUSSION THREAD

**Discussion by ruzickap** [crossplane/crossplane#2548] [Q&A]
Hello guys.

Does anybody know how to do a simple subdomain delegation using Crossplane with Route53?

I created the HostedZone in Route53:

```yaml
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  name: test.example.com
  namespace: crossplane-system
spec:
  forProvider:
    name: test.example.com
    config:
      comment: Zone manged by Crossplane
  providerConfigRef:
    name: aws-provider
```

I can see the nameservers for this domain and the `hostedzones.route53.aws.crossplane.io` looks like:

```yaml
$ kubectl get hostedzones.route53.aws.crossplane.io -A -o yaml
...
  status:
    atProvider:
      delegationSet:
        nameServers:
        - ns-128.awsdns-16.com
        - ns-1190.awsdns-20.org
        - ns-1957.awsdns-52.co.uk
        - ns-684.awsdns-21.net
...
```

Then I would like to take "somehow" these `nameServers` from `HostedZone` and use them in `ResourceRecordSet`:

```yaml
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: example.com
  namespace: crossplane-system
spec:
  forProvider:
    type: NS
    ttl: 60
    resourceRecords:
    # - value: "ns1.example.com"
    # <----------- Insert the nameServers values from HostedZone `test.example.com` somehow...
    zoneId: ZxxxxxxxxxxxxxxxxxxxZ
  providerConfigRef:
    name: aws-provider
```

I do not need to use anything complex - just take specific data `status.atProvider.delegationSet.nameServers` from one object `HostedZone` and use them in different one `ResourceRecordSet`.

I can use `Composition`, but it seems to be too "heavy" for simple case like this.

Thank you for the answer...
