### DISCUSSION TITLE
Prometheus metrics and alerting for crossplane and providers

### DISCUSSION THREAD

**Discussion by chlunde** [crossplane/crossplane#2583] [Knowledge base]
# Core crossplane
## Enable metrics port and labels

Set `metrics.enabled` using the helm chart. Flux example:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
....
  # Default values
  # https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/values.yaml.tmpl
  values:
    metrics:
      enabled: true
```

Note: This will enable `prometheus.io/` labels on the deployment, so if you have enabled service discovery using labels, you should not point to these pods using `PodMonitor`.

# Providers

## Expose metrics port and add labels
Note: `ControllerConfig` is in alpha

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
spec:
  metadata:
    labels:
      app: provider-aws
  ports:
  - name: http-prom
    containerPort: 8080
```
## Scrape using `PodMonitor`
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crossplane-system
  namespace: crossplane-system
  labels:
    app.kubernetes.io/part-of: crossplane
spec:
  namespaceSelector:
    matchNames:
      - crossplane-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - provider-aws
          - provider-sql
 #         - crossplane - via metrics.enabled
  podMetricsEndpoints:
    - port: http-prom
```

# Alert on reconcile failure

This is an example alert:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts
  namespace: crossplane-system
  labels:
    app.kubernetes.io/part-of: crossplane
spec:
  groups:
  - name: Crossplane
    rules:
    - alert: ReconciliationFailure
      expr: sum(rate(controller_runtime_reconcile_errors_total{namespace="crossplane-system"}[5m])) by (container, controller)> 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: '{{ $labels.controller }} {{ $labels.namespace }}/{{ $labels.container }} reconciliation has been failing for more than ten minutes.'
```

Have anyone else written crossplane specific alerts? What do you alert on?

**Comment by negz** [comment]
Far from production ready, but the below repo has some Prometheus monitoring configuration that I'm using to test Crossplane at scale. I've found that https://github.com/caicloud/event_exporter works well to monitor events.

https://github.com/negz/crossplane-scale

**Comment by negz** [comment]
I feel like it should be possible to monitor Crossplane providers without needing a `ControllerConfig`, so I've opened https://github.com/crossplane/crossplane/pull/2648 to address that.

**Comment by haarchri** [comment]
did we have Grafana Dashboard Samples available ?

**Reply by negz** [reply]
https://github.com/negz/crossplane-scale/blob/main/grafana-dashboard.json is probably the closest we have

**Comment by eloo** [comment]
@haarchri 
i'm currently checking out the crossplane metrics and i'm really curious what you would expect to see on grafana dashboards here.

As far as i can see crossplane is not really exporting useful information right now. 
The only two metrics i've found is the reconciliation errors and the workqueue_depth gauge right now. 

But IMHO important metric like amount of MR, Compositions, Claims and definition are missing.
Also i was not able to see any metrics which is providing the current state of my crossplane resources. 
e.q. how many MR are in sync and ready or not. so i can create alerting and so on. 

i guess before it makes sense to great grafana dashboards for crossplane its necessary to export relevant data first

**Reply by haarchri** [reply]
That is also my Feeling that we start discussion ;)

**Comment by eloo** [comment]
We have just updated to recent versions of crossplane and provider-aws and so i had the chance to check the metrics from the provider as well and its really disappointing. 
Couldn't find any useful metric out of the box :( 

I would suggest we should start exporting the following metrics:

```
managed_resource_reconcile_condition{type="Ready",status="True",kind="RDSInstance", name="myRdsInstance"...}           # of course also with status = false
managed_resource_reconcile_condition{type="Synced",status="True",kind="RDSInstance", name="myRdsInstance"...}         # of course also with status = false
claim_reconcile_condition{type="Ready",status="True",kind="RDSInstanceClaim", name="myRdsInstanceClaim"...}           # of course also with status = false
claim_reconcile_condition{type="Synced",status="True",kind="RDSInstance", name="myRdsInstanceClaim"...}         # of course also with status = false
```

and so on to get at least an overview of the current status of the crossplane resources..

Is there currently something planned for new metrics?

**Comment by chlunde** [comment]
I think counters per kind here would be cheap and easy to implement:
https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reconciler/managed/reconciler.go#L268-L292

```
managed_resource_reconcile_create_total{kind="...", apiGroup(?)="..."}
managed_resource_reconcile_observe_total{kind="...", apiGroup(?)="..."}
managed_resource_reconcile_update_total{kind="...", apiGroup(?)="..."}
managed_resource_reconcile_delete_total{kind="...", apiGroup(?)="..."}
```

There should also be another counter for errors, would `_errors_total` be best? or have `success=True|False` on the counter above.

not sure about adding names there, it would significantly increase the number of metrics, but it wouldn't be worse than kube-state-metrics :thinking:

**Reply by eloo** [reply]
and how would you separate between synced=true|false and ready=true|false? 
i guess this information is also pretty important to know on which side (e.g. aws or kubernetes) the issue exists. 

IMHO adding the name would be also important to easily identify broken resources. 
maybe you can also have a look at the metrics which are exported by Flux2.

the flux2 metrics about the reconciler is pretty good in my opinion and we can build easy to understand dashboard.
e.g. https://user-images.githubusercontent.com/11332517/111912371-f3bb2d80-8a71-11eb-996a-be8e1bebb5f0.png

**Reply by chlunde** [reply]
> and how would you separate between synced=true|false and ready=true|false? i guess this information is also pretty important to know on which side (e.g. aws or kubernetes) the issue exists.

We could have both.

I'm not sure if anything other than looking at the events would explain "which side" an issue exists.

> IMHO adding the name would be also important to easily identify broken resources. maybe you can also have a look at the metrics which are exported by Flux2.

Yeah, but then I would like the claim name/namespace too I guess :-)

**Reply by eloo** [reply]
> I'm not sure if anything other than looking at the events would explain "which side" an issue exists.

at least our experience with the provider-aws has shown that in general if synced=false anything with the claim,composition or configuration is not working. So the resources is not processed against aws. 
and if ready=false we normally have seen that an issue from aws is returned.
so a bit of information where the issue could be is existing. 

and yes. the claimname / namespace would also makes sense 👍

**Reply by eloo** [reply]
@chlunde is there already any progress here on the metrics topic?

**Reply by mateusz-lubanski-sinch** [reply]
We do plan also go to production with crossplane in upcoming months so we are also very interested to get such metrics

**Reply by chlunde** [reply]
Here is an alternative approach like "kube-state-metrics". It's just a POC at the moment, we can make everything configurable, or even auto-discover managed resource types etc.

https://github.com/chlunde/xp-state-metrics

**Comment by mateusz-lubanski-sinch** [comment]
We decided to onboard [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) to our cluster which allows produce metrics for any CRD via [Custom Resource State Metrics](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md)

Sample configuration:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-state-metrics-crd-config
  namespace: crossplane-system
data:
  crd-config.yaml: |
    kind: CustomResourceStateMetrics
    spec:
      resources:
        - groupVersionKind:
            group: rds.aws.crossplane.sinch.com
            version: v1alpha1
            kind: MySQLInstance
          metricNamePrefix: crossplane_compositeresources
          metrics:
            - name: "status_ready"
              help: "MySQLInstance Claim ready status"
              each:
                type: StateSet
                stateSet:
                  labelName: ready
                  path: [status, conditions, "[type=Ready]", status]
                  list: [True, False, Unknown]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  namespace: [metadata, namespace]
                  name: [metadata, name]
            - name: "status_synced"
              help: "MySQLInstance Claim synced status"
              each:
                type: StateSet
                stateSet:
                  labelName: synced
                  path: [status, conditions, "[type=Synced]", status]
                  list: [True, False, Unknown]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  namespace: [metadata, namespace]
                  name: [metadata, name]
                  apiVersion: [apiVersion]
        - groupVersionKind:
            group: pkg.crossplane.io
            version: "v1"
            kind: Provider
          metricNamePrefix: crossplane_providers
          metrics:
            - name: "status_installed"
              help: "Provider status installed"
              each:
                type: StateSet
                stateSet:
                  labelName: installed
                  path: [status, conditions, "[type=Installed]", status]
                  list: [True, False, Unknown]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  name: [metadata, name]
                  package: [spec, package]
            - name: "status_healthy"
              help: "Provider status healthy"
              each:
                type: StateSet
                stateSet:
                  labelName: healthy
                  path: [status, conditions, "[type=Healthy]", status]
                  list: [True, False, Unknown]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  name: [metadata, name]
                  package: [spec, package]
        - groupVersionKind:
            group: aws.crossplane.io
            kind: "ProviderConfig"
            version: "v1beta1"
          metricNamePrefix: crossplane_providers_config
          metrics:
            - name: "aws_provider_status_users"
              help: "Number of external resources managed by Provider"
              each:
                type: Gauge
                gauge:
                  path: [status, users]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  name: [metadata, name]
        - groupVersionKind:
            group: pkg.crossplane.io
            version: "v1"
            kind: Configuration
          metricNamePrefix: crossplane_configurations
          metrics:
            - name: "status_installed"
              help: "Configuration status installed"
              each:
                type: StateSet
                stateSet:
                  labelName: installed
                  path: [status, conditions, "[type=Installed]", status]
                  list: [True, False, Unknown]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  name: [metadata, name]
                  package: [spec, package]
            - name: "status_healthy"
              help: "Configuration status healthy"
              each:
                type: StateSet
                stateSet:
                  labelName: healthy
                  path: [status, conditions, "[type=Healthy]", status]
                  list: [True, False, Unknown]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  name: [metadata, name]
                  package: [spec, package]
        - groupVersionKind:
            group: apiextensions.crossplane.io
            version: "v1"
            kind: CompositeResourceDefinition
          metricNamePrefix: crossplane_compositeresourcedefinitions
          metrics:
            - name: "status_established"
              help: "CompositeResourceDefinition status Established"
              each:
                type: StateSet
                stateSet:
                  labelName: established
                  path: [status, conditions, "[type=Established]", status]
                  list: [True, False, Unknown]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  name: [metadata, name]
            - name: "status_offered"
              help: "CompositeResourceDefinition status offered"
              each:
                type: StateSet
                stateSet:
                  labelName: offered
                  path: [status, conditions, "[type=Offered]", status]
                  list: [True, False, Unknown]
              commonLabels:
                custom_metric: "yes"
              labelsFromPath:
                  name: [metadata, name]

```

Based on above we can build Grafana dashboard like that:
![image](https://user-images.githubusercontent.com/115790821/219700986-c11777c0-597f-4dfc-be7e-cebc8e1fe4d2.png)
![image](https://user-images.githubusercontent.com/115790821/219701175-e195c7fc-bd66-465a-a72c-5e272fc9faad.png)

We are using also above metrics for Prometheus alerts

In near future (hopefully) kube-static-metrics will provide CRD object which we can use to provide metric configuration. This will help us replace ConfigMap presented above and instead we will define it via that CRD objects
