### DISCUSSION TITLE
Is there any way to share tags definition between the Compositions?

### DISCUSSION THREAD

**Discussion by ytsarev** [crossplane/crossplane#2617] [General]
Problem statement:

We have a set of mandatory tags to be applied to each cloud resource.

In a Composition it usually looks like this

```
....
  patchSets:
  - name: tags
    patches:
    - fromFieldPath: spec.parameters.Application
      toFieldPath: spec.forProvider.tags[0].value
    - fromFieldPath: spec.parameters.AppId
      toFieldPath: spec.forProvider.tags[1].value
    - fromFieldPath: spec.parameters.BuiltBy
      toFieldPath: spec.forProvider.tags[2].value
    - fromFieldPath: spec.parameters.CostCenter
      toFieldPath: spec.forProvider.tags[3].value
    - fromFieldPath: spec.parameters.Environment
      toFieldPath: spec.forProvider.tags[4].value
    - fromFieldPath: spec.parameters.TeamEmailAddress
      toFieldPath: spec.forProvider.tags[5].value
    - fromFieldPath: spec.parameters.TeamCode
      toFieldPath: spec.forProvider.tags[6].value
    - fromFieldPath: spec.parameters.OriginatingCluster
      toFieldPath: spec.forProvider.tags[7].value
    - fromFieldPath: spec.parameters.TeamCode # same value for map-migrated
      toFieldPath: spec.forProvider.tags[8].value
...
  resources:
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        spec:
          forProvider:
            region: af-south-1
            description: An excellent formation of subnetworks.
            subnetIdSelector:
              matchLabels:
                type: app
                region: af-south-1
                awsAccount: default
            tags: &tags
              - key: Application
                value: to-be-patched
              - key: AppId
                value: to-be-patched
              - key: BuiltBy
                value: to-be-patched
              - key: CostCenter
                value: to-be-patched
              - key: Environment
                value: to-be-patched
              - key: TeamEmailAddress
                value: to-be-patched
              - key: TeamCode
                value: to-be-patched
              - key: OriginatingCluster
                value: to-be-patched
              - key: map-migrated
                value: to-be-patched
...
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            region: af-south-1
            multiAZ: false
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            dbInstanceClass: db.t3.small
            masterUsername: masteruser
            engine: postgres
            engineVersion: "13.3"
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: false
            storageEncrypted: true
            vpcSecurityGroupIDSelector:
              matchLabels:
                region: af-south-1
                type: postgresql
                awsAccount: default
            tags: *tags # reusing tag definition through yaml anchor
```

As you сan see there is quite amount of tag set definition repetition which is partially mitigated by yaml anchor based reuse.

The most brittle and painful part is that we need to repeat the same style definition for every other Composition we manage.
It leads to obvious maintenance challenges with tag set update which should be common for all resources.

Additional complications bring the fact that the tag definition API might deviate and not always consistent between resources, e.g. 
* https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/Bucket/v1beta1@v0.19.1#spec-forProvider-tagging
* https://doc.crds.dev/github.com/crossplane/provider-aws/database.aws.crossplane.io/RDSInstance/v1beta1@v0.19.1#spec-forProvider-tags
* https://doc.crds.dev/github.com/crossplane/provider-aws/eks.aws.crossplane.io/Cluster/v1beta1@v0.19.1

It would be great to have a streamlined way to define and propagate tags to all managed resources in a single place while keeping ability to parameterized and expose some of them in the definitions
