### DISCUSSION TITLE
Cloudfront Stuck in Deploying

### DISCUSSION THREAD

**Discussion by kferrone** [crossplane/crossplane#2702] [Q&A]
I can't seem to get a Cloudfront distribution with a valid ACM certificate to complete deploying. I know it has something to do with the ACM cert because everything will work, ie finish deploying, when I take the certificate info off. basically the `aliases` and `viewerCertificate` sections cause the distribution to say `deploying` indefinitely and Crossplane resource will always have condition ready as false. Anyone see something I don't? What could possible block it from finishing and becoming ready? 

Here is the yaml for the distribution that will never finish:
```yaml
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: coolest-website-ever
spec:
  forProvider:
    region: us-west-2
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution
      defaultRootObject: index.html
      origins:
        items:
        - domainName: foobar.example.com.s3.us-west-2.amazonaws.com
          id: s3Origin
          s3OriginConfig:
            originAccessIDentity: ""
      defaultCacheBehavior:
        targetOriginID: s3Origin
        viewerProtocolPolicy: allow-all
        minTTL: 0
        forwardedValues:
          cookies:
            forward: none
          queryString: false
      # if you comment the rest of this out, it will indeed finish
      aliases:
        quantity: 1
        items:
        - foobar.example.com
      viewerCertificate:
        sslSupportMethod: sni-only
        cloudFrontDefaultCertificate: false
        # this was issued for foobar.example.com
        aCMCertificateARN: arn:aws:acm:us-east-1:123456789:certificate/valid-cert-id
```

FYI I did change the domain in the example from our real test domain to simply example.com

**Comment by jbw976** [comment]
This could be another variation of https://github.com/crossplane/provider-aws/issues/894, which we are hearing continues to persist even after https://github.com/crossplane/provider-aws/pull/922.  We'll keep looking into that for a more complete fix.

**Comment by kferrone** [comment]
Here is the full composition and definition if it helps any:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-cloudfront
  labels:
    crossplane.io/xrd: websites.example.com
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: example.com/v1
    kind: Website
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.name
    - fromFieldPath: metadata.labels
  # writeConnectionSecretsToNamespace: crossplane
  resources:

   # now build a bucket
  - name: bucket
    base:
      apiVersion: s3.aws.crossplane.io/v1beta1
      kind: Bucket
      forProvider:
        locationConstraint: us-west-2
        acl: private
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.parameters.domain
      toFieldPath: metadata.annotations[crossplane.io/external-name]

  # first create the acm cert
  - name: acm-cert
    base:
      apiVersion: acm.aws.crossplane.io/v1alpha1
      kind: Certificate
      spec:
        forProvider:
          region: us-east-1
          validationMethod: DNS
          tags:
          - key: Name
        providerConfigRef:
          name: admin
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.parameters.domain
      toFieldPath: spec.forProvider.domainName
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.tags[0].value
    # put values on composite
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.resourceRecord.name
      toFieldPath: status.resourceRecord.name
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.resourceRecord.value
      toFieldPath: status.resourceRecord.value
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.certificateARN
      toFieldPath: status.certArn

  # now we can dns validate the cert
  - name: dns-validation-record
    base:
      apiVersion: route53.aws.crossplane.io/v1alpha1
      kind: ResourceRecordSet
      spec:
        forProvider:
          type: CNAME
          ttl: 300
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.parameters.zone
      toFieldPath: spec.forProvider.zoneIdRef.name
    - fromFieldPath: status.resourceRecord.name
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - fromFieldPath: status.resourceRecord.value
      toFieldPath: spec.forProvider.resourceRecords[0].value

  # creates the cloudfront dist
  - name: cloudfront
    base:
      apiVersion: cloudfront.aws.crossplane.io/v1alpha1
      kind: Distribution
      spec:
        forProvider:
          region: us-west-2
          distributionConfig:
            enabled: true
            comment: ""
            defaultRootObject: index.html
            aliases:
              quantity: 1
              items:
              - ""
            viewerCertificate:
              sslSupportMethod: sni-only
              cloudFrontDefaultCertificate: false
            origins:
              items:
              - domainName: ""
                id: s3Origin
                s3OriginConfig:
                  originAccessIDentity: ""
            defaultCacheBehavior:
              targetOriginID: s3Origin
              viewerProtocolPolicy: allow-all
              minTTL: 0
              forwardedValues:
                cookies:
                  forward: none
                queryString: false
    patches:
    - type: PatchSet
      patchSetName: metadata

    # enable or disable distribution, set to false before deleting
    - fromFieldPath: spec.parameters.enabled
      toFieldPath: spec.forProvider.distributionConfig.enabled

    # set the domain name alias
    - fromFieldPath: spec.parameters.domain
      toFieldPath: spec.forProvider.distributionConfig.aliases.items[0]
    - fromFieldPath: spec.parameters.defaultRootObject
      toFieldPath: spec.forProvider.distributionConfig.defaultRootObject
    - fromFieldPath: spec.parameters.description
      toFieldPath: spec.forProvider.distributionConfig.comment
    # build and add the buckets url as an origin
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.parameters.domain
        strategy: string
        string:
          fmt: "%s.s3.us-west-2.amazonaws.com"
      toFieldPath: spec.forProvider.distributionConfig.origins.items[0].domainName
    - fromFieldPath: status.certArn
      toFieldPath: spec.forProvider.distributionConfig.viewerCertificate.aCMCertificateARN
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.distribution.domainName
      toFieldPath: status.cloudFront.domain
      
  # add the main sites record to route53
  - name: a-record
    base:
      apiVersion: route53.aws.crossplane.io/v1alpha1
      kind: ResourceRecordSet
      spec:
        forProvider:
          type: A
          aliasTarget:
            dnsName: ""
            evaluateTargetHealth: false
            hostedZoneId: Z2FDTNDATAQYW2 # required zone for cloudfront
    patches:
    - fromFieldPath: metadata.labels
    - fromFieldPath: spec.parameters.domain
      toFieldPath: metadata.name
    - fromFieldPath: spec.parameters.zone
      toFieldPath: spec.forProvider.zoneIdRef.name
    # reference the distributions generated domain name
    - fromFieldPath: status.cloudFront.domain
      toFieldPath: spec.forProvider.aliasTarget.dnsName

  # add a cache policy
  - name: cache-policy
    base:
      apiVersion: cloudfront.aws.crossplane.io/v1alpha1
      kind: CachePolicy
      spec:
        forProvider:
          region: us-west-2
          cachePolicyConfig:
            defaultTTL: 300
            maxTTL: 900
            minTTL: 100
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.cachePolicyConfig.name
    - fromFieldPath: spec.parameters.description
      toFieldPath: spec.forProvider.cachePolicyConfig.comment
    # set the cache config values and ttl
    - fromFieldPath: spec.parameters.cacheTTL.default
      toFieldPath: spec.forProvider.cachePolicyConfig.defaultTTL
    - fromFieldPath: spec.parameters.cacheTTL.max
      toFieldPath: spec.forProvider.cachePolicyConfig.maxTTL
    - fromFieldPath: spec.parameters.cacheTTL.min
      toFieldPath: spec.forProvider.cachePolicyConfig.minTTL
    - fromFieldPath: spec.parameters.cacheConfig
      toFieldPath: spec.forProvider.cachePolicyConfig.parametersInCacheKeyAndForwardedToOrigin
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: websites.example.com
spec:
  group: example.com
  names:
    kind: Website
    plural: websites
  defaultCompositionRef:
    name: aws-cloudfront
  #connectionSecretKeys:
  #- certArn
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  domain:
                    type: string
                    description: The fqdn of the domain for your website
                  zone:
                    type: string
                    description: Name of the hosted zone to place your domain name. 
                  enabled:
                    type: boolean
                    description: True when the distribution is active. Set to false before deleting a dist. 
                  description:
                    type: string
                  defaultRootObject:
                    type: string
                  cacheTTL:
                    type: object
                    properties:
                      max:
                        type: integer
                      min:
                        type: integer
                      default: 
                        type: integer
                  cacheConfig:
                    type: object
                required:
                - domain
                - zone
            required:
            - parameters
          status:
            type: object
            properties:
              certArn:
                type: string
              cloudFront:
                type: object
                properties:
                  domain:
                    type: string
              resourceRecord:
                type: object
                properties:
                  name:
                    type: string
                  value: 
                    type: string
       
```
