### DISCUSSION TITLE
Propagating connectionDetails

### DISCUSSION THREAD

**Discussion by Duologic** [crossplane/crossplane#2787] [Knowledge base]
There are various hoops to jump through to get the connectionDetails propagated through
the system, assuming many others like me struggle with this, here is how it currently
(v1.6 and v1.7) works (from what I understand):

1. ~The XRD needs to expose `connectionSecretKeys`. This field is immutable, to get it
   updated we need to remove the XRD and re-apply. It has a ripple effect as there are
   objects depending on this XRD and underlying CRD. We don't want to do that often so we
   have to think ahead.~ Since Crossplane 1.6 this is [fixed](https://github.com/crossplane/crossplane/issues/2593), if unspecified it will take all keys from
  the composition.
2. The Composition needs to set `writeConnectionSecretsToNamespace` to the crossplane
   system namespace, this collects all connectionSecrets from the underlying managed
   resources in this composition. The name of this secret will be `metadata.uid` of the
   composition.
3. Each managed resource in a composition needs a `writeConnectionSecretToRef`, by
   convention:
   - the name is the composition's `metadata.uid` suffixed with the resource name;
   - the namespace is the same as the crossplane system namespace.
4. Each managed resource in a composition also needs a `connectionDetails` to populate the
   composition's 'connection secret'.
5. A Claim on the XRD needs a `writeConnectionSecretToRef`, without the namespace key as
   the secret will be written to the same namespace the Claim is in. I have observed that
   this secret only gets created once the underlying resources are READY.

**Comment by Duologic** [comment]
Example manifests

XRD:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.com
  namespace: crossplane
spec:
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:                                         # (optional) This will make these keys available in the connectionSecret
  - username
  - password
  - endpoint
  - port
  defaultCompositionRef:
    name: azure-postgresql
  group: database.example.com
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
      ...
```

Composition:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xpostgresqlinstances.database.example.com
  name: azure-postgresql
  namespace: crossplane
spec:
  compositeTypeRef:
    apiVersion: database.example.com/v1alpha1
    kind: XPostgreSQLInstance
  resources:
  - base:
      apiVersion: database.azure.crossplane.io/v1beta1
      kind: PostgreSQLServer
      spec:
        writeConnectionSecretToRef:
          namespace: crossplane-system                          # This will create a secret per resource in namespace `crossplane-system`
        ...
    connectionDetails:                                          # This will make the connectionDetails available to the composition
    - fromConnectionSecretKey: username                         # fromConnectionSecretKey refers to keys in the `metadata.uid`-postgresqlinstance secret
      name: username
    - fromConnectionSecretKey: password
      name: password
    - fromConnectionSecretKey: endpoint
      name: endpoint
    - fromConnectionSecretKey: port
      name: port
    name: postgresqlinstance
    patches:
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-postgresqlinstance'                          # This will create a secret per resource with name `metadata.uid`-postgresqlinstance
        type: string
      type: FromCompositeFieldPath
    ...
  writeConnectionSecretsToNamespace: crossplane-system          # This will create a secret per composition with name `metadata.uid` in namespace `crossplane-system`
```

Claim:

```yaml
apiVersion: database.example.com/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: crossplane-testdb
  namespace: crossplane-test
spec:
  writeConnectionSecretToRef:
    name: crossplane-testdb-credentials                         # This will create a secret with name `crossplane-testdb-credentials` in namespace `crossplane-test`
```
