### DISCUSSION TITLE
Composition just stops creating resources

### DISCUSSION THREAD

**Discussion by kferrone** [crossplane/crossplane#2846] [Q&A]
I have a composition to make an eks cluster. It almost works but right after the ProviderConfig is created, nothing else will be created. I figured something must be wrong with the ProviderConfig as it is the last successful item. IE there is nothing wrong with the ProviderConfig, works perfect, it's just the last thing created. 

I need some help working through this one, I feel I am missing something small and nitpicky or there may be a bug, can't really tell. There are no errors and the XRD ultimately says it is ready and all the resources it did create all say ready and synced. It's just not all the resources get created. 

A little more on the backstory. One of the resources is another custom XRD I wrote for an IRSA role, this is one that is `not` getting created. The OpenIdConnectProvider is getting created just fine, to note there is a MutatingWebhookConfiguration which will inject its thumbprint. Another webhook is for the IRSA resource to set some values. 

Before I make compositions and definitions, I make all the resources in individual files using kustomize. This way I can compare results and use it as a guide to build the composition. Deployed individually all the resources are created exactly as I want and the webhooks work like a charm. 

Small warning, the IRSA resource is kinda complicated to share as it won't work without the MutatingWebhook. However for testing it would be easier to make a static IRSA resource. I originally thought my IRSA was the problem, however when it is commented out and I redeploy, the problems persist. 

Here is my definition file
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  labels:
    app.kubernetes.io/component: cluster
    app.kubernetes.io/managed-by: kustomize-v4.4.1
    app.kubernetes.io/name: eks-cluster
    app.kubernetes.io/version: v1
  name: clusters.cubizoid.com
spec:
  defaultCompositionRef:
    name: aws-eks
  group: cubizoid.com
  names:
    kind: Cluster
    plural: clusters
  versions:
    - name: v1
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                deletionPolicy:
                  type: string
                parameters:
                  properties:
                    region:
                      type: string
                  required:
                    - region
                  type: object
                providerConfigRef:
                  properties:
                    name:
                      type: string
                  type: object
              required:
                - parameters
              type: object
            status:
              properties:
                oidcUrl:
                  type: string
              type: object
          type: object
      served: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    app.kubernetes.io/component: cluster
    app.kubernetes.io/managed-by: kustomize-v4.4.1
    app.kubernetes.io/name: eks-cluster
    app.kubernetes.io/version: v1
    crossplane.io/xrd: clusters.cubizoid.com
  name: aws-eks
spec:
  compositeTypeRef:
    apiVersion: cubizoid.com/v1
    kind: Cluster
  patchSets:
    - name: meta
      patches:
        - fromFieldPath: spec.providerConfigRef
        - fromFieldPath: spec.deletionPolicy
    - name: topology
      patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
    - name: labeling
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.labels[app.kubernetes.io/instance]
        - fromFieldPath: spec.parameters.region
          toFieldPath: metadata.labels[topology.kubernetes.io/region]
        - fromFieldPath: spec.providerConfigRef.name
          toFieldPath: metadata.labels[topology.kubernetes.io/provider]
        - fromFieldPath: metadata.labels[app.kubernetes.io/part-of]
  resources:
    - base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Role
        metadata:
          labels:
            app.kubernetes.io/component: cluster
            app.kubernetes.io/created-by: cubizoid-crosshook
            app.kubernetes.io/managed-by: crossplane
            app.kubernetes.io/name: eks-cluster
            app.kubernetes.io/version: v1
            eks.amazonaws.com/cluster-role: "true"
        spec:
          forProvider:
            assumeRolePolicyDocument: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Effect": "Allow",
                    "Principal": {
                      "Service": "eks.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                  }
                ]
              }
            description: Main role for an EKS cluster.
            tags:
              - key: Name
      name: cluster-role
      patches:
        - fromFieldPath: metadata.name
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.tags[0].value
        - patchSetName: meta
          type: PatchSet
        - patchSetName: labeling
          type: PatchSet
    - base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        metadata:
          labels:
            app.kubernetes.io/component: cluster
            app.kubernetes.io/created-by: cubizoid-crosshook
            app.kubernetes.io/managed-by: crossplane
            app.kubernetes.io/name: eks-cluster
            app.kubernetes.io/version: v1
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      name: cluster-role-policy
      patches:
        - patchSetName: meta
          type: PatchSet
        - patchSetName: labeling
          type: PatchSet
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.roleNameRef.name
        - combine:
            strategy: string
            string:
              fmt: '%s-cluster-role-policy'
            variables:
              - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          type: CombineFromComposite
    - base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        metadata:
          labels:
            app.kubernetes.io/component: cluster
            app.kubernetes.io/created-by: cubizoid-crosshook
            app.kubernetes.io/managed-by: crossplane
            app.kubernetes.io/name: eks-cluster
            app.kubernetes.io/version: v1
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
      name: cluster-role-vpc
      patches:
        - patchSetName: meta
          type: PatchSet
        - patchSetName: labeling
          type: PatchSet
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.roleNameRef.name
        - combine:
            strategy: string
            string:
              fmt: '%s-cluster-role-vpc'
            variables:
              - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          type: CombineFromComposite
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        metadata:
          labels:
            app.kubernetes.io/component: cluster
            app.kubernetes.io/created-by: cubizoid-crosshook
            app.kubernetes.io/managed-by: crossplane
            app.kubernetes.io/name: eks-cluster
            app.kubernetes.io/version: v1
            eks.amazonaws.com/security-group: "true"
        spec:
          forProvider:
            description: The extra sg for the cluster
            tags:
              - key: Name
            vpcIdSelector:
              matchLabels:
                app.kubernetes.io/component: network
                app.kubernetes.io/part-of: control-plane
      name: security-group
      patches:
        - fromFieldPath: metadata.name
        - patchSetName: meta
          type: PatchSet
        - patchSetName: labeling
          type: PatchSet
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.tags[0].value
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.groupName
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.vpcIdSelector.matchLabels[topology.kubernetes.io/region]
    - base:
        apiVersion: eks.aws.crossplane.io/v1beta1
        kind: Cluster
        metadata:
          labels:
            app.kubernetes.io/component: cluster
            app.kubernetes.io/created-by: cubizoid-crosshook
            app.kubernetes.io/managed-by: crossplane
            app.kubernetes.io/name: eks-cluster
            app.kubernetes.io/version: v1
        spec:
          forProvider:
            resourcesVpcConfig:
              endpointPrivateAccess: true
              endpointPublicAccess: true
              securityGroupIdSelector:
                matchLabels:
                  eks.amazonaws.com/security-group: "true"
              subnetIdSelector:
                matchLabels:
                  eks.amazonaws.com/subnet: "true"
            roleArnSelector:
              matchLabels:
                eks.amazonaws.com/cluster-role: "true"
            tags:
              Name: eks
          writeConnectionSecretToRef:
            namespace: clusters
      name: cluster
      patches:
        - fromFieldPath: metadata.name
        - patchSetName: meta
          type: PatchSet
        - patchSetName: labeling
          type: PatchSet
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.tags.Name
        - fromFieldPath: metadata.name
          toFieldPath: spec.writeConnectionSecretToRef.name
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.roleArnSelector.matchLabels[topology.kubernetes.io/region]
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.resourcesVpcConfig.subnetIdSelector.matchLabels[topology.kubernetes.io/region]
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.resourcesVpcConfig.securityGroupIdSelector.matchLabels[topology.kubernetes.io/region]
        - fromFieldPath: status.atProvider.identity.oidc.issuer
          toFieldPath: status.oidcUrl
          type: ToCompositeFieldPath
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        metadata:
          labels:
            app.kubernetes.io/component: cluster
            app.kubernetes.io/created-by: cubizoid-crosshook
            app.kubernetes.io/managed-by: crossplane
            app.kubernetes.io/name: eks-cluster
            app.kubernetes.io/version: v1
        spec:
          credentials:
            secretRef:
              key: kubeconfig
              namespace: clusters
            source: Secret
      name: provider-kubernetes
      patches:
        - fromFieldPath: metadata.name
        - patchSetName: labeling
          type: PatchSet
        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.name
      readinessChecks:
        - type: None
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        metadata:
          labels:
            app.kubernetes.io/component: cluster
            app.kubernetes.io/created-by: cubizoid-crosshook
            app.kubernetes.io/managed-by: crossplane
            app.kubernetes.io/name: eks-cluster
            app.kubernetes.io/version: v1
        spec:
          credentials:
            secretRef:
              key: kubeconfig
              namespace: clusters
            source: Secret
      name: provider-helm
      patches:
        - fromFieldPath: metadata.name
        - patchSetName: labeling
          type: PatchSet
        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.name
      readinessChecks:
        - type: None
    - base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: OpenIDConnectProvider
        metadata:
          labels:
            app.kubernetes.io/component: cluster
            app.kubernetes.io/created-by: cubizoid-crosshook
            app.kubernetes.io/managed-by: crossplane
            app.kubernetes.io/name: eks-cluster
            app.kubernetes.io/version: v1
            eks.amazonaws.com/oidc: "true"
        spec:
          forProvider:
            clientIDList:
              - sts.amazonaws.com
            thumbprintList: []
      name: oidc
      patches:
        - fromFieldPath: metadata.name
        - patchSetName: meta
          type: PatchSet
        - patchSetName: labeling
          type: PatchSet
        - fromFieldPath: status.oidcUrl
          toFieldPath: spec.forProvider.url
```

Lastly an example of the XRD resource:
```yaml
apiVersion: cubizoid.com/v1
kind: Cluster
metadata:
  name: cashew
  labels:
    pizza: sauce
    app.kubernetes.io/part-of: crosshook-examples
spec:
  deletionPolicy: Delete
  parameters:
    region: us-west-2
  providerConfigRef:
    name: aws-staging
```
