### DISCUSSION TITLE
Crossplane - How to debug managed resources

### DISCUSSION THREAD

**Discussion by Veluu** [crossplane/crossplane#3467] [Q&A] [answered]
Hey

I followed this example https://github.com/crossplane-contrib/provider-aws/tree/master/examples/apigateway. Resources were created.

I wanted to add other things on top of that. For example

```YAML
apiVersion: apigateway.aws.crossplane.io/v1alpha1
kind: MethodResponse
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    restApiIdRef:
      name: example
    region: us-east-1
    resourceIdRef:
      name: example
    httpMethod: GET
    statusCode: "200"
```
    
 After I create it with `kuebctl apply -f` I don't get any errors. However in AWS API Gateway I see no changes.
 
Based on https://crossplane.io/docs/v1.9/reference/troubleshoot.html I'm trying to find something in logs/events but I see nothing.

```bash
$ k get methodresponses.apigateway.aws.crossplane.io
NAME      READY   SYNCED   EXTERNAL-NAME
example                    
```
 
 and
 
 ```YAML
 $ k describe methodresponses.apigateway.aws.crossplane.io example
Name:         example
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  apigateway.aws.crossplane.io/v1alpha1
Kind:         MethodResponse
Metadata:
  Creation Timestamp:  2022-11-25T22:05:34Z
  Generation:          1
  Managed Fields:
    API Version:  apigateway.aws.crossplane.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:httpMethod:
          f:region:
          f:resourceIdRef:
            .:
            f:name:
          f:restApiIdRef:
            .:
            f:name:
          f:statusCode:
        f:providerConfigRef:
          .:
          f:name:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-11-25T22:05:34Z
  Resource Version:  754792
  UID:               29aa1b10-d16f-4265-b774-8d2ef400b8bf
Spec:
  Deletion Policy:  Delete
  For Provider:
    Http Method:  GET
    Region:       us-east-1
    Resource Id Ref:
      Name:  example
    Rest API Id Ref:
      Name:       example
    Status Code:  200
  Provider Config Ref:
    Name:  default

 ```
 
 When I do
 ```
 $ kubectl -n crossplane-system logs -lapp=crossplane -f
 ```
 I only see logs related to my composition I did a while ago for studying purposes (S3) but nothing regarding API Gateway.
 
 I was hoping to get some sort of error/warning giving me hint what did I actually miss.
 
 Using:
 ```
 crossplane-1.10.1
 provider-aws:v0.33.0
 ```
