### DISCUSSION TITLE
Experience Report: Swapping a resource between two compositions

### DISCUSSION THREAD

**Discussion by Piotr1215** [crossplane/crossplane#3705] [Show and tell]
# Experience Report: Swapping a resource between two compositions

## Context

As part of the efforts to improve compliance and security posture, a new composition required to enable creation of a secure
`StorageBucket`. This composition enables versioning on a GCP bucket.

## Goal

The goal was to swap the existing claim `acme-bucket-prod-00` from being
satisfied by the _generic_ StorageBucket composition to the _secure_
StorageBucket composition. New composition should be label selected by changing
the `type: generic` label to `type: secure`.

## Implementation

To implement the desired state, the following steps have been taken in an experimental scenario.

1. First ensure that new composite is present and healthy in the cluster by running
`kubectl get crossplane`. Checking the state of the existing claim and ensuring
it currently selects the _generic_ composition.

2. Modify the claim file to select the new _secure_ composition by changing the
`type` label from `generic` to `secure`.

3. Expected result should be that the XR changes to the _secure_ composition and
the cloud resource is not managed by the _generic_ composition.

Here is a claim example satisfied by the _generic_ StorageBucket composite.

```yaml
apiVersion: platform-composites.upbound.io/v1alpha1
kind: StorageBucket
metadata:
  name: sample-storage-12345
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
      type: generic
  parameters:
    owner: squad-platform
    service: platform-composites
    # Passthrough location from cloud provider
    # defaults to us-west1 for GCP
    location: us-west1 #Optional
    # This maps to ProviderConfig that points to a specific
    # project in GCP. Use default for local testing and playground for crossplane-playground
    environment: provider-gcp #Required
    # Possible values: STANDARD, NEARLINE, COLDLINE, ARCHIVE
    # Defaults to standard
    storageClass: STANDARD #Optional
```
After applying the above claim, a new `sample-storage-12345` bucket is created in GCP.

![image](https://user-images.githubusercontent.com/8086638/216275403-009f833d-1199-4abb-9428-d3769fa1d50a.png)

Composition selector points to the right composition:

![image](https://user-images.githubusercontent.com/8086638/216275829-5f231776-18ee-427b-b889-d7bfa1737488.png)

> Notice here the `Composition Ref:` is filled although the XRD does not
> have a _default_ or _enforced_ composition.

Now apply the claim with secure composition label selectors, which will select the _secure_ composition.

```yaml
apiVersion: platform-composites.upbound.io/v1alpha1
kind: StorageBucket
metadata:
  name: sample-storage-12345
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
      type: secure
  parameters:
    owner: squad-platform
    service: platform-composites
    # Passthrough location from cloud provider
    # defaults to us-west1 for GCP
    location: us-west1 #Optional
    # This maps to ProviderConfig that points to a specific
    # project in GCP. Use default for local testing and playground for crossplane-playground
    environment: provider-gcp #Required
    # Possible values: STANDARD, NEARLINE, COLDLINE, ARCHIVE
    # Defaults to standard
    # Value is ingored for the secure bucket
    storageClass: STANDARD #Optional
```

The StorageBucket changes its label selectors, but the named reference stays the
same. Bucket in GCP **does not** change and _versioning_ remains disabled.

![image](https://user-images.githubusercontent.com/8086638/216275472-b7ac1627-542d-4090-8c9b-c583005901fa.png)

Only after manually changing the `Composition Ref:` the claim _swaps_ to the new
composition and the cloud resource _versioning_ is correctly switched on.

Manually editing the live claim YAML and changing composition reference name.

![image](https://user-images.githubusercontent.com/8086638/216275912-c1b6f0b3-9797-4358-b3ae-9e8c16b084d2.png)

Cloud resource with _versioning_ enabled.

![image](https://user-images.githubusercontent.com/8086638/216276101-fee38b13-e793-44d2-bee3-7ddf51f703a4.png)

## Alternative Implementation

Instead of using `compositionRef` label selectors, it is possible to use
`compositionRef.name` which works without the need to manually edit the
`compositionRef`.

This however forces the claim user to select composition by name.

## Conclusion

The workflow with composition label selectors requires manual intervention to set the composition reference to a
new name despite there being no _default_ composition in the XRD.

The change should work after applying the composition label selectors. Manual
changes make this flow incompatible with `gitops` approach.

[platform-composites]: https://github.com/upbound/platform-composites
