### DISCUSSION TITLE
Best Practices for Setting `publishConnectionDetailsTo` on Claims

### DISCUSSION THREAD

**Discussion by jonnylangefeld** [crossplane/crossplane#3826] [General]
Are there any best practices for publishConnectionDetailsTo for claims? We expose custom resources to our users with lots of default values set. Creating a ServiceAccount could be as simple as
```
apiVersion: getcruise.com/v1alpha1
kind: CruiseServiceAccount
metadata:
  name: my-sa
spec: {}
```
as a user. But then I would miss out on the secret. I need to always set the secret on the spec as a user:
```
apiVersion: getcruise.com/v1alpha1
kind: CruiseServiceAccount
metadata:
  name: jonnys-sa
spec:
  publishConnectionDetailsTo:
    name: jonnys-sa
```
or storing in vault:
```
apiVersion: getcruise.com/v1alpha1
kind: CruiseServiceAccount
metadata:
  name: jonnys-sa
spec:
  publishConnectionDetailsTo:
    configRef:
      name: vault
    name: jonnys-sa
```

Is there a way to automatically set this for users so they don’t need to worry about it?
