### DISCUSSION TITLE
Connect terraform Vault provider in Crossplane ProviderConfig

### DISCUSSION THREAD

**Discussion by evgenii-rodionov-affise** [crossplane/crossplane#3936] [Q&A]
Hello!
I'm having trouble connecting to the Terraform Vault provider through crossplane ProviderConfig. I want to use an authorization token and pass it through the VAULT_TOKEN environment variable. I have read the [ProviderConfig API documentation](https://marketplace.upbound.io/providers/upbound/provider-terraform/v0.6.0/resources/tf.upbound.io/ProviderConfig/v1beta1) and am trying to use the following provider configuration:

```
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: terraform-provider-config
spec:
  configuration: |-
    provider "google" {
      credentials = "affise-staging-gcp-credentials.json"
      project = "devel-326713"  
    }
    terraform {
      backend "gcs" {
        bucket = "affise-terraform-infrastructure"
        prefix = "terraform/affise/stage"
        credentials = "affise-staging-gcp-credentials.json"
      }
    }
    provider "vault" {
      address         = "http://10.164.0.83:8200"
      skip_tls_verify = true
    }
  credentials:
    - env:
        name: VAULT_TOKEN
      filename: .vault-token
      secretRef:
        key: vault-token
        name: provider-terraform-vault
        namespace: crossplane-system
      source: Secret
    - filename: affise-staging-gcp-credentials.json
      secretRef:
        key: credentials
        name: provider-terraform
        namespace: crossplane-system
      source: Secret
    - filename: .git-credentials
      secretRef:
        key: .git-credentials
        name: provider-terraform
        namespace: crossplane-system
      source: Secret
```

but I  get an error - cannot diff (i.e. plan) Terraform configuration: no vault token found. 
Maybe I misunderstood the value of the ENV  field.

I attempted to use an alternate method by utilizing the [vars block in the workspace](https://marketplace.upbound.io/providers/upbound/provider-terraform/v0.6.0/resources/tf.upbound.io/Workspace/v1beta1#doc:spec-forProvider-vars) and creating a token variable within the provider configuration:
```
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: default
spec:
  deletionPolicy: Orphan
  forProvider:
    module:  XXXXXXX
    source: Remote
    vars:
    - key: vault_token
      value: testtoken
  providerConfigRef:
    name: terraform-provider-config
```

```
provider "google" {
  credentials = "affise-staging-gcp-credentials.json"
  project = "devel-326713"  
}

terraform {
   backend "gcs" {
      bucket = "affise-terraform-infrastructure"
      prefix = "terraform/affise/stage"
      credentials = "affise-staging-gcp-credentials.json"
   }
}
provider "vault" {
  address         = "http://10.164.0.83:8200"
  skip_tls_verify = true
  token = "${var.vault_token}" 
}
```

After that, I got an error - "cannot diff (i.e. plan) Terraform configuration: value for undeclared variable"

I also tried [varFiles](https://marketplace.upbound.io/providers/upbound/provider-terraform/v0.6.0/resources/tf.upbound.io/Workspace/v1beta1#doc:spec-forProvider-varFiles), but it didn`t works. 

Here's an improved version of your text:

I'm not sure what else to try at this point. Perhaps I should explore other Vault authentication methods that don't rely on environment variables. I would really appreciate some help in resolving this issue.

**Comment by bobh66** [comment]
This sounds like the functionality that will be provided by https://github.com/upbound/provider-terraform/pull/74

The current provider-terraform cannot set environment variables on a per-Workspace basis since by default all goroutines share the same environment.  This PR adds the ability to set environment variables for each individual Workspace.

**Comment by evgenii-rodionov-affise** [comment]
I solved my problem.  I found the API description for CRD ControllerConfig. First I created a Kubernetes  secret  with a vault token  
````
apiVersion: v1
kind: Secret
metadata:
  name: controller-config
  namespace: crossplane-system
type: Opaque
data:
  vault-token: XXXXXXXXXXXXXXXXXXXXXXXXXXX
````

After that, I added the following configuration for the Terraform provider. In this config, I add env VAULT_TOKEN to crossplane terraform provider with the value from controller-config secret
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: terraform-config
  labels:
    app: crossplane-provider-terraform
spec:
  args:
    - -d
  env:
    - name:  VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: controller-config
          key: vault-token
```
And In the end, I added controllerConfigRef to the provider
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: terraform-provider
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.6.0
  controllerConfigRef:
    name: terraform-config
```

After these settings, you can use the vault terraform provider with authentification through env VAULT_TOKEN.
