### DISCUSSION TITLE
In which order patches are applied?

### DISCUSSION THREAD

**Discussion by pahalampi** [crossplane/crossplane#3979] [Q&A] [answered]
Is there a specific order in which resource patching is done?

I'm creating AWS resources with Crossplane, and trying to apply dynamic tagging. Some tags come straight from the XR, while others are transformed when patching. 

Below is an example of a resource I'm creating. While applying this setup, only the environment tag ends up in the resource, regardless what fields `spec.tags` has.

```yaml
patches:
- type: FromCompositeFieldPath
  fromFieldPath: spec.tags
  toFieldPath: spec.forProvider.tags
- type: FromCompositeFieldPath
  fromFieldPath: spec.environment
  toFieldPath: spec.forProvider.tags.environment
```

**Comment by phisco** [comment]
Could you provide the whole Composition, the CompositeResourceDefinition and an example of Claim you are trying to apply?

**Reply by phisco** [reply, marked as answer]
And to answer your question patches are applied in the same order they are specified.

**Comment by bobh66** [comment]
Note that FromComposite and ToComposite patches are applied separately at different times in the reconciliation process, as the ToComposite patches typically rely on information that is not available when the FromComposite patches are applied.

**Comment by pahalampi** [comment]
Seems that the problem was not in the patching. That worked exactly as expected (and as @phisco described). 

I had defined the resource like this:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xexamples.example.com
spec:
  group: example.com
  names:
    kind: XExample
    plural: xexamples
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              environment:
                type: string
              tags:
                type: object
                properties:
                  cost-center:
                    type: string
                    default: "2311"
                  application:
                    type: string
                    default: example-app
            required:
            - environment
```

and created the resource like this, without any tag-fields:

```yaml
apiVersion: example.com/v1alpha1
kind: XExample
metadata:
  name: example
spec:
  environment: dev
```

Apparently it works so that the XR will be created without any tags even though the default values for `cost-center` and `application` exist. After adding an initialization for tags to my `XExample`
```yaml
  tags: {}
```
the default values are used.

So, an unrelated question to the initial topic: is this Kubernetes or Crossplane functionality? How could I enable the default values to be used for `tags.x` even if the `tags` object is not given at all?

**Reply by phisco** [reply]
I think the issue is that there is no default for tags itself, so it's going to be nil instead of an empty object, the following should work:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xexamples.example.com
spec:
  group: example.com
  names:
    kind: XExample
    plural: xexamples
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              environment:
                type: string
              tags:
                type: object
                default: {}   # <- this should do the trick
                properties:
                  cost-center:
                    type: string
                    default: "2311"
                  application:
                    type: string
                    default: example-app
            required:
            - environment
```
