### DISCUSSION TITLE
Not able to propagate secrets from managed kubernetes to main crossplane kubernetes

### DISCUSSION THREAD

**Discussion by kurzacz** [crossplane/crossplane#4061] [Q&A]
### What is the problem
In the kubernetes provisioned by crossplane **(cloud k8s)**, there are secrets that I want to pull to the cluster where crossplane resides **(edge k8s)**. To do this, I try to create managed Object from Crossplane Kubernetes Provider. This way, I'm able to create secret on _cloud k8s_, but it's data is not propagated to _edge k8s_. In order to achieve this, I try to define mapping with `connectionDetails` property, but no success. So far I was reading about similar cases, but wasn't able to succeed when using hints.

No matter what I do, it everytime ends the same: the expected propagated secret in _edge k8s_ is created, **but it's empty**.

### Reason behind
Service deployed on _cloud k8s_ stores its credentials in kubernetes secrets. They are not manageable by Crossplane. Deployed service does not exist in any providers, so I cannot use helpers like AWS PostgreSQL. So I try to:

1. Create Kubernetes Secret on _cloud k8s_, that will be manageable by Crossplane. To do that, I add a resource in a Composition. The resource is of type Object from Crossplane Provider Kubernetes
2. Populate managed secret with data from original secret
3. Configure managed secret in _cloud k8s_ so that it will propagate back to _edge k8s_.

### What I have tried so far
For now, I just want to propagate hardcoded secret from _cloud k8s_ to _edge k8s_. Let this secret have `cloudkey` key. As long as I understand, this key name must be added to XRD. So I added it:

XRD.yaml
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xservice.crossplane.foo.com
spec:
  group: crossplane.foo.com
  names:
    kind: XService
    plural: xservices
    singular: xservice
  claimNames:
    kind: Service
    plural: services
    singular: service
  connectionSecretKeys:
    - kubeconfig
    - cloudkey      # <-- I added cloudkey to inform Crossplane I want to have this field propagated
  versions:
    - name: v1alpha1
      served: true
      # ...
```

Then, I add hardcoded secret to my composition:

Composition.yaml
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: service
  labels:
    # ...
spec:
  compositeTypeRef:
    apiVersion: crossplane.foo.com/v1alpha1
    kind:XService
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    # ...
    - name: secret-expected-to-be-propagated
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: secret-that-will-have-edge-copy
                namespace: default
              stringData:
                cloudkey: FOOVALBARBAZ
          writeConnectionSecretToRef:
            name: cloud-secret-copy
            namespace: default
      connectionDetails:
      - fromConnectionSecretKey: cloudkey
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name    # <--- I patch providerConfigRef, because deploying in cloud k8s
```

Let me state the problem once again: `cloud-secret-copy` secret is properly created in _edge k8s_. **But it does not contain any data**. What I expected is to `cloud-secret-copy` have the `cloudkey` key and copied value FOOVALBARBAZ.

### Similar resources
[Manage secrets not coming from a provider](https://hub.syn.tools/appcat/explanations/crossplane-secrets-non-provider.html) - this article was a starting inspiration for me on how to replicate secrets in Crossplane

[Composite Resource Connection Secrets](https://docs.crossplane.io/v1.10/reference/composition/#composite-resource-connection-secrets) - I have read there that XRD needs to have declared fields about to propagate. I have added then the field `cloudkey`, but no success.

[Connection details are not propagated to secret #2606](https://github.com/crossplane/crossplane/issues/2606) - I followed the hints, especially regarding `writeConnectionSecretToRef` and `connectionDetails`, but it didn't help.

[API docs for Object in Crossplane Provider Kubernetes](https://marketplace.upbound.io/providers/crossplane-contrib/provider-kubernetes/v0.7.0/resources/kubernetes.crossplane.io/Object/v1alpha1#doc:spec-forProvider-manifest)

[API docs for Composition in Crossplane](https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.12.1)

**Comment by bobh66** [comment]
It sounds like you need to use `managementPolicy: Observe` so that provider-kubernetes knows that you don't want it to create the remote secret, you want it to retrieve the content of an already-existing secret.  See the examples - https://github.com/crossplane-contrib/provider-kubernetes/blob/main/examples/object/policy/observe.yaml

You will need to configure the provider-kubernetes Object manifest Secret object with the name and namespace of the remote Secret so it can find it.

**Reply by kurzacz** [reply]
Hello, thank you for your answer! 
I will try to adapt your suggestion so as to wrap secret I want to transfer. However, it cannot seem to solve my problem that replicated secret is empty. _Still, Crossplane does not copy secret content from cloud k8s to edge k8s._

### What I did
I have changed resource of composition, that previously were creating it's own secret. Now, as long as I understand, it tries to observe existing secret. So I started from creating a dummy secret in _cloud k8s_:
```
kubectl create secret generic example-cloud-secret --from-literal=cloudkey=FOOVALBARBAZ2
```

So, name of secret I try to control is `example-cloud-secret`. I try to replicate it to _edge k8s_. **Unfortunately, still replicated secret is empty.**

Composition.yaml
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: service
  labels:
    # ...
spec:
  compositeTypeRef:
    apiVersion: crossplane.foo.com/v1alpha1
    kind:XService
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    # ...
    - name: secret-expected-to-be-propagated
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:   # <-- added metadata with name and namespace of secret I want to replicate
          name: example-cloud-secret
          namespace: default
        spec:
          managementPolicy: Observe   # <-- added your suggestion of observing objects
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: example-cloud-secret   # <-- now I put a name of existing secret, created outside of Crossplane
                namespace: default
#              stringData:   # <--- removed hardcoded data, because I try to wrap around existing secret
#                cloudkey: FOOVALBARBAZ
          writeConnectionSecretToRef:
            name: cloud-secret-copy
            namespace: default
      connectionDetails:
      - fromConnectionSecretKey: cloudkey
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name    # <--- I patch providerConfigRef, because deploying in cloud k8s
```

### What has become working thanks to your answer
What has helped me, from your hints, is now Crossplane residing on _edge k8s_ has access to secret in _cloud k8s_. It does not solve my problem completely, but it is a definitely step forward. In another words, this deployed Object is aware of secret data in _cloud k8s_, as on below snippet:

```
# ...
 Status:
  At Provider:
    Manifest:
      API Version:  v1
      Data:
        Cloudkey:       Rk9PVkFMQkFSQkFaMg==
      Kind:             Secret
# ...
```
The only thing now I need is to make Crossplane copy those secret data and paste them into secret residing on _edge k8s_, which is for now empty.

### Where I suppose problem lies
So, the problem is, somehow Crossplane does not understand I want to copy `cloudkey` from secret `example-cloud-secret`. Do you know how to setup this mapping correctly?
I have tried to specify this information with following lines:
```
      connectionDetails:
      - fromConnectionSecretKey: cloudkey
```
But it does not bring the effect.
