### DISCUSSION TITLE
Is there a way to create synthetic connectionDetails values?

### DISCUSSION THREAD

**Discussion by jabbrwcky** [crossplane/crossplane#4088] [Q&A]
Hi,

I am trying to set up S3-Storage for [Thanos](https://thanos.io). I did already build a composite resource that builds the required S3-Bucket with IAM-Credentials/-policy, Bucket, KMS-Key, writing everything required to the connectionSecret.

Unfortunately, Thanos components expect the credentials to be in a single Secret value containing the configuration yaml required for accessing the bucket. e.g.:

```yaml
type: S3
config:
  bucket: thanos # <- src: crossplane S3 Bucket resource
  endpoint: thanos.s3.eu-central-1.amazonaws.com  # <- src: crossplane S3 Bucket resource
  region: eu-central-1
  access_key: "..." # <- src: crossplane IAM
  secret_key: "..." # <- src: crossplane IAM
  insecure: false
  sse_config:
    type: SSE-KMS
    kms_key_id: "..." # <- from crossplane KMS resource
```

As far as I understand the documentation values for the connection Secret can either be copied from a field path, another connection Secret or given as static value.

Can transformations also be applied for the connectionSecret fields by `combine` (already using it for generating the IAM policy) without exposing the access keys by combining to a field in the composite resource?
