### DISCUSSION TITLE
Composition selection for nested composites

### DISCUSSION THREAD

**Discussion by bobh66** [crossplane/crossplane#4102] [General]
Does anyone have any tricks or patterns for enabling composition selection via labels when using nested composites?

We have composites that are nested 6 or 7 levels deep and we would like to be able to allow for composition selection in the lower level composites without exposing input parameters all the way up the chain to the top level claim/composite.

One possibility is to add a generic object parameter like `compositeLabelSelectors` to the claim/composite and every child composite, which could have an attribute key for each composite and the value is the set of label k/v pairs needed to select a composition for that composite.  Then each composition would patch the content of `spec.parameters.compositeLabelSelector.foo` into `compositionSelector.matchLabels` for the `foo` composite.  A limitation is that multiple instances of the composite would all have the same label selectors.

If labels from the claim were copied to the composite, and then to all child composites, that might be another solution.

It seems like there should be a better way of influencing composition selection from the claim, without affecting the abstraction by adding a lot of inputs that only affect low-level composites.

Ideas are appreciated.  Thanks!

**Comment by blakebarnett** [comment]
We've started moving away from doing deep nesting to making things more of a "Mixin" model, where you dedicated a block of parameters to each composition you're using.

For example:
If using `XCoolThing` in your composition, you'd have: `spec.paramters.coolThing` and pass only the parameters that composition needs there.

To make this feasible we had to implement templating for XRDs, which we use YTT for, it looks something like this:

```
#@ load("@lambda:xrd.lib.yml", "defaultLambdaParamProps", "defaultLambdaStatusProps")
---
...
                parameters:
                  type: object
                  properties:
                    lambdaBase:
                      description: Parameters for the base Lambda composition which creates the function and related resources
                      type: object
                      properties:
                        _: #@ template.replace(defaultLambdaParamProps())
```

This lets us collapse the layer-cake to a single level and pull in what we need without duplicating parameters everywhere. I was hesitant to start using a templating solution but I feel like this is a pretty clear approach and makes our codebase look a lot cleaner without adding a lot of cognitive load.
