### DISCUSSION TITLE
How do we patch a key name ?

### DISCUSSION THREAD

**Discussion by mmuthukrishnan** [crossplane/crossplane#4158] [Q&A] [answered]
``` 

     - fromFieldPath: status.clusterName
        toFieldPath: spec.forProvider.tags[kubernetes.io/cluster/%s]
        policy: 
          fromFieldPath: Required
          mergeOptions:
            appendSlice: true
            keepMapValues: true
```

For the above snippet the **%s** in toFieldPath must be patched and at the same time the value must be given for the key from field path
