### DISCUSSION TITLE
Error Deploying Claim Of Helm Provider Resource: Empty Namespace

### DISCUSSION THREAD

**Discussion by arielsepton** [crossplane/crossplane#4249] [Q&A] [answered]
Hey everybody! I encountered an error while trying to deploy WordPress (a helm provider release) using a claim. The error message I received is as follows: "Composed resource 'wordpress': Cannot use dry-run create to name composed resource: an empty namespace may not be set during creation."

I have attempted various approaches to specify the namespace for the composed resource within the composition file, with no success.
Any insights, workarounds, or alternative methods to overcome this error would be greatly appreciated.

The composition: 

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
  labels: 
    crossplane.io/xrd: xwordpresses.releases.example.io
    provider: provider-helm
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: releases.example.io/v1alpha1
    kind: XWordpress
  resources:
  - name: wordpress
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release 
      spec:
        forProvider:
          chart:
            name: wordpress
            repository: https://turkenh.github.io/bitnami-charts
            version: 9.5.1 
    patches:
      - fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]  
        toFieldPath: "spec.forProvider.namespace"
```
The definition:

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xwordpresses.releases.example.io
spec:
  group: releases.example.io
  names:
    kind: XWordpress
    plural: xwordpresses
  claimNames:
    kind: Wordpress
    plural: Wordpresses
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A Wordpress is a composite resource that represents a Wordpress Installed
          type: object
          properties:
            spec:
              type: object
              properties:
                MyWordpressVersion:
                  type: string
              required:
                - MyWordpressVersion
```

The claim:

```
apiVersion: releases.example.io/v1alpha1
kind: Wordpress
metadata:
  namespace: default
  name: myWordpress
spec:
  MyWordpressVersion: "1.18"
```

**Comment by phisco** [comment, marked as answer]
Hi, I had to change a few things to lowercase to have it working, but it's working fine for me on the latest version of Crossplane 1.12.2 and the latest version on master of provider-helm (`kubectl crossplane install provider crossplanecontrib/provider-helm:master`):
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xwordpresses.releases.example.io
spec:
  group: releases.example.io
  names:
    kind: XWordpress
    plural: xwordpresses
  claimNames:
    kind: Wordpress
    plural: Wordpresses
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A Wordpress is a composite resource that represents a Wordpress Installed
          type: object
          properties:
            spec:
              type: object
              properties:
                MyWordpressVersion:
                  type: string
              required:
                - MyWordpressVersion
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
  labels: 
    crossplane.io/xrd: xwordpresses.releases.example.io
    provider: provider-helm
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: releases.example.io/v1alpha1
    kind: XWordpress
  resources:
  - name: wordpress
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release 
      spec:
        forProvider:
          chart:
            name: wordpress
            repository: https://turkenh.github.io/bitnami-charts
            version: 9.5.1 
    patches:
      - fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]  
        toFieldPath: "spec.forProvider.namespace"
---
apiVersion: releases.example.io/v1alpha1
kind: Wordpress
metadata:
  namespace: default
  name: my-wordpress
spec:
  MyWordpressVersion: "1.18"
```
With default providerConfig created as explained [here](https://github.com/crossplane-contrib/provider-helm/blob/master/examples/provider-config/provider-config-incluster.yaml) changing the name to `default`.
