### DISCUSSION TITLE
how to create composition can dynamic resources?

### DISCUSSION THREAD

**Discussion by nabeel-blankon** [crossplane/crossplane#4563] [Q&A] [answered]
**CompositeResourceDefinition**
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: service.nt-nabeel.com
spec:
  group: nt-nabeel.com
  names:
    kind: Service
    plural: service
  claimNames:
    kind: ServiceClaim
    plural: service-claims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - parameters
              properties:
                parameters:
                  type: object
                  required:
                    - a
                    - b
                  properties:
                    a:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                    b:
                      type: object
                      properties:
                        enabled:
                          type: boolean
``` 

**Composition**
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: service.nt-nabeel.com
spec:
  compositeTypeRef:
    apiVersion: nt-nabeel.com/v1alpha1
    kind: Service
  resources:
    - name: provider-config-kubernetes
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: InjectedIdentity
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
      readinessChecks:
        - type: None
    - name: service-a
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: service-a
                namespace: crossplane-system
              type: Opaque
              data: {}
      patches:
        - fromFieldPath: spec.claimRef.name
          toFieldPath: spec.providerConfigRef.name
    - name: service-b
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: service-b
                namespace: crossplane-system
              type: Opaque
              data: {}
      patches:
        - fromFieldPath: spec.claimRef.name
          toFieldPath: spec.providerConfigRef.name
``` 

**claim-services**
```
apiVersion: nt-nabeel.com/v1alpha1
kind: ServiceClaim
metadata:
  name: cliam-service-a
spec:
  compositionRef:
    name: service.nt-nabeel.com
  parameters:
    a:
      enabled: true
    b:
      enabled: false

---
apiVersion: nt-nabeel.com/v1alpha1
kind: ServiceClaim
metadata:
  name: claim-service-b
spec:
  compositionRef:
    name: service.nt-nabeel.com
  parameters:
    a:
      enabled: false
    b:
      enabled: true

---
apiVersion: nt-nabeel.com/v1alpha1
kind: ServiceClaim
metadata:
  name: claim-service-ab
spec:
  compositionRef:
    name: service.nt-nabeel.com
  parameters:
    a:
      enabled: true
    b:
      enabled: true
``` 

I want if I apply claim-service-a or claim-service-b, composition it will create resource service-a or service-b only, but if I apply claim-service-ab, composition it will create all resources in the composition.

can you tell me how to make what i expect to work in crossplane?
