### DISCUSSION TITLE
CombineFromComposite issue from a resource setting status vars

### DISCUSSION THREAD

**Discussion by mzupan** [crossplane/crossplane#4635] [General]
I have the following resource which I'm trying to set a bunch of status vars in an object

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: serviceaccount-irsa.platform.foo.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: platform.foo.io/v1alpha1
    kind: serviceaccount-irsa
  resources:
  - name: eks-cluster
    base:
      apiVersion: eks.aws.upbound.io/v1beta1
      kind: Cluster
      metadata:
        labels:
          resource: "Cluster"
        annotations:
          crossplane.io/external-name: staging
      spec:
        managementPolicies: ["Observe"]
        forProvider:
          region: us-east-1
    patches:
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.identity[0].oidc[0].issuer
        toFieldPath: status.eks.oidc
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.identity[0].oidc[0].issuer
        toFieldPath: status.eks.oidcUri
        transforms:
          - type: string
            string:
              type: TrimPrefix
              trim: 'https://'
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.roleArn
        toFieldPath: status.eks.accountId
        transforms:
          - type: string
            string:
              type: Regexp
              regexp:
                match: 'arn:aws:iam::(\d+):.*'
                group: 1
      - type: CombineFromComposite
        toFieldPath: status.eks.oidcArn
        combine:
          variables:
            - fromFieldPath: status.eks.accountId
            - fromFieldPath: status.eks.oidc
          strategy: string
          string:
            fmt: 'arn:aws:iam::%s:oidc-provider/%s'
```

If I remove 

```
      - type: CombineFromComposite
        toFieldPath: status.eks.oidcArn
        combine:
          variables:
            - fromFieldPath: status.eks.accountId
            - fromFieldPath: status.eks.oidc
          strategy: string
          string:
            fmt: 'arn:aws:iam::%s:oidc-provider/%s'
```

Everything works fine.. I'm just not able to get this working from status i have set above. Is this even possible?

**Comment by jbw976** [comment]
Are you able to also share the CompositeResourceDefinition that you're using? 👀

**Reply by mzupan** [reply]
sure

```

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: serviceaccount-irsa.platform.foo.io
  labels:
    provider: aws
spec:
  group: platform.foo.io
  names:
    kind: serviceaccount-irsa
    plural: serviceaccount-irsa
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: ServiceAccount IRSA IAM Role
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: IRSA configuration parameters.
                  properties:
                    serviceAccount:
                      type: object
                      description: Configuration for SA
                      properties:
                        name:
                          type: string
                          description: name kubernetes SA
                        namespace:
                          type: string
                          description: namespace kubernetes SA
                      required:
                      - name
                      - namespace
                    condition:
                      type: string
                      description: This is the whether or not the equals is a hard match or like query
                      default: StringEquals
                      enum:
                      - StringEquals
                      - StringLike
                    policyDocument:
                      type: string
                      description: The JSON policy document that is the content for the policy.
                  required:
                  - condition
                  - policyDocument
                  - serviceAccount
                deletionPolicy:
                  type: string
                  description: DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource.
                providerConfigRef:
                  type: object
                  description: crossplane provider credentials to use.
                  properties:
                    name:
                      type: string
                  required:
                  - name
              required:
              - parameters
            status:
              type: object
              properties:
                oidc:
                  type: string
                accountid:
                  type: string
                eks:
                  description: Freeform field containing information about the eks cluster status.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

 ```

**Comment by bobh66** [comment]
It looks like you want to store the output from `CombineFromComposite` into the Composite status?  That won't work - you need one more step:

- copy the data from the MR into the Composite status fields and transform it like you do today
- CombineFromComposite back to an annotation in the MR
``` 
        type: CombineFromComposite
        toFieldPath: metadata.annotations.oidcArn
        combine:
          variables:
            - fromFieldPath: status.eks.accountId
            - fromFieldPath: status.eks.oidc
          strategy: string
          string:
            fmt: 'arn:aws:iam::%s:oidc-provider/%s'
```
- ToCompositeFieldPath from the MR annotation to the Composite status
```
      - type: ToCompositeFieldPath
        fromFieldPath: metadata.annotations.oidcArn
        toFieldPath: status.eks.oidc
```
