### DISCUSSION TITLE
Ensuring uniqueness of AWS RDS instance names?

### DISCUSSION THREAD

**Discussion by cer** [crossplane/crossplane#4710] [Q&A]
I have

* Two K8s clusters in the same AWS account
* An application that creates an RDS database, e.g. `customer-database`

Problem:

* When deploying the application in both clusters both use the same `customer-database` RDS instance
* As a workaround, I've used `crossplane.io/external-name: customer-service-postgres-prod` but that's tedious and error prone.

It would be great if Crossplane could be configured to automatically prefix such names with a cluster-specific prefix to ensure uniqueness.

Thoughts?

**Comment by bobh66** [comment]
Hi @cer  - Typically Crossplane expects that it will create uniquely named resources to prevent this scenario, by using the `metadata.generateName` functionality to create a resource name based on the name of the Composite resource.  Users can override this by setting `metadata.name` or the label `crossplane.io/external-name` on the Composed/Managed resource, 

It is usually better not to change the generated names, but you can take the generated Composite name and add a prefix or suffix to add meaning to the name.  That allows you to still have a unique name with some additional information that might be useful for the user.

For example:

```
- type: FromCompositeFieldPath
  fromFieldPath: metadata.name
  toFieldPath: metadata.annotations["crossplane.io/external-name"]
  transforms:
  - type: String
    string:
      type: Format
      fmt: "%s-customer-database"
```

This will prefix the unique composite name to the `customer-database` string and produce a unique external name.

Does that help?

**Reply by cer** [reply]
@bobh66 I'm not using a composite resource. I've simply defined an `instance.rds`:

```yaml
apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: ...
```

I'd like to understand how using Composite resources would solve my problem.
Do you have a pointer to some easily understand documentation/examples on using Composite resources?

**Reply by cer** [reply]
@bobh66 Thanks for the suggestion to use Compositions.

BTW   `crossplane.io/external-name` is an annotation, not a label, right?

```
- type: FromCompositeFieldPath
  fromFieldPath: metadata.name
  toFieldPath: metadata.annotations["crossplane.io/external-name"]
  transforms:
  - type: String
    string:
      type: Format
      fmt: "%s-customer-database"
```
