### DISCUSSION TITLE
writeConnectionSecretsToNamespace appears not to be mandatory

### DISCUSSION THREAD

**Discussion by cer** [crossplane/crossplane#4762] [Q&A]
Following on from https://github.com/crossplane/crossplane/discussions/4710#discussioncomment-7168575, I created a `CompositeResourceDefinition` and a `Composition` that creates an `Instances.rds`.

The `Instances.rds` created by the `Composite` uses `connectionDetails` :

```yaml
  resources:
    - name: ...
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        ...
        spec:
          forProvider:

          writeConnectionSecretToRef:
             ....
      connectionDetails:
        - name: username
          fromConnectionSecretKey: username
      patches:

        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-secret"
      ....
```

The docs ([for example](https://docs.crossplane.io/knowledge-base/guides/connection-details/)) strongly imply that a `writeConnectionSecretsToNamespace` is required but I've found that its not necessary:
Crossplane happily creates the `Secret` containing composite connection details as specified by `writeConnectionSecretToRef`

```yaml
apiVersion: servicedatabase.chrisrichardson.net/v1alpha1
kind: ServiceDatabase
metadata:
  name: example-service-database-5
  namespace: default
spec: 
  dbName: service_database
  writeConnectionSecretToRef:
    name: example-service-secrets-5
    namespace: default
```

The `example-service-secrets-5` Secret contains the expected values.

So is `writeConnectionSecretsToNamespace` optional?
And how is it helpful to create secrets in a namespace that hardwired into the Composite rather than being passed in?

Please clarify. Thanks
