### DISCUSSION TITLE
A claim for a CompositeResource doesn't create specified connection details Secret

### DISCUSSION THREAD

**Discussion by cer** [crossplane/crossplane#4769] [Q&A]
I tried defining a claim for the CompositeResource I described in https://github.com/crossplane/crossplane/discussions/4762:

```yaml
apiVersion: servicedatabase.chrisrichardson.net/v1alpha1
kind: ServiceDatabaseClaim
metadata:
  name: example-service-database-x3
  namespace: default
spec: 
  dbName: service_database
  writeConnectionSecretToRef:
    name: example-service-secrets-x3
```

Unlike when I resources created the CompositeResource directly, when using a claim the `example-service-secrets-x3` Secret is not created.

Suggestions?
