### DISCUSSION TITLE
metadata.labels[crossplane.io/claim-name]: no such field

### DISCUSSION THREAD

**Discussion by emily-zall** [crossplane/crossplane#4863] [Q&A] [answered]
I have a Composition and Claim and the CompositeResource is getting created but without the `crossplane.io/claim-name` label that I thought would be set automatically and I need for creating my managed resources. I thought this label would be created automatically when the CompositeResource is created. What am I missing? thanks.

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: global-vault-access
  labels:
    crossplane.io/xrd: xglobal-vault-accesses.azure.simbachain.com
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: azure.simbachain.com/v1beta1
    kind: XGlobal-Vault-Access
  resources:
    - name: resource group
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        spec:
          deletionPolicy: Orphan
          forProvider: {}
      patches:
        - type: PatchSet
          patchSetName: location
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: metadata.name
          policy:
            fromFieldPath: Required
          transforms:
            - type: string
              string:
                fmt: "%s-rg"
        - type: PatchSet
          patchSetName: providerConfigRef
        - type: PatchSet
          patchSetName: tags
  patchSets:
    - name: location
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.location
          toFieldPath: spec.forProvider.location
          policy:
            fromFieldPath: Required
    - name: providerConfigRef
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providers.azure.providerConfigRef
          toFieldPath: spec.providerConfigRef
    - name: resourceGroupNameRef
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: spec.forProvider.resourceGroupNameRef.name
          policy:
            fromFieldPath: Required
          transforms:
            - type: string
              string:
                fmt: "%s-rg"
    - name: tags
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.tags
    - name: tenantId
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.tenantId
          toFieldPath: spec.forProvider.tenantId
          policy:
            fromFieldPath: Required
```
and 
```
➜ kubectl describe XGlobal-Vault-Access -A
Name:         blocks-simba-kongtest
Namespace:
Labels:       crossplane.io/composite=blocks-simba-kongtest
              kustomize.toolkit.fluxcd.io/name=cluster
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  crossplane.io/external-name: blocks-simba-kongtest
API Version:  azure.simbachain.com/v1beta1
Kind:         XGlobal-Vault-Access
Metadata:
  Creation Timestamp:  2023-10-20T21:50:40Z
  Finalizers:
    composite.apiextensions.crossplane.io
  Generation:        3
  Resource Version:  208332843
  UID:               3a3d0814-ba47-4016-b248-fb9ae78f627d
Spec:
  Composition Ref:
    Name:  global-vault-access
  Composition Revision Ref:
    Name:                     global-vault-access-77a0c0e
  Composition Update Policy:  Automatic
  Parameters:
    Issuer URL:  https://eastus.oic.prod-aks.azure.com/97fd3cb6-823b-4578-ab45-226a5925ce05/9fe04542-e99e-465b-92ea-566b2c27d584/
    Keyvault:
      Global Keyvault:
        Name:                 simbachain-global-vault
        Resource Group Name:  simbachain-global-rg
    Location:                 eastus
    Providers:
      Azure:
        Provider Config Ref:
          Name:       provider-config-azure
    Subscription Id:  b6b4b75f-a5b7-4620-bf5a-446735fffef5
    Tenant Id:        97fd3cb6-823b-4578-ab45-226a5925ce05
  Resource Refs:
    API Version:  azure.upbound.io/v1beta1
    Kind:         ResourceGroup
Status:
  Conditions:
    Last Transition Time:  2023-10-20T21:50:40Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-10-20T21:50:40Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
Events:
  Type     Reason                   Age                 From                                                             Message
  ----     ------                   ----                ----                                                             -------
  Normal   CompositionUpdatePolicy  25m                 defined/compositeresourcedefinition.apiextensions.crossplane.io  Default composition update policy has been selected
  Warning  ComposeResources         23m (x8 over 25m)   defined/compositeresourcedefinition.apiextensions.crossplane.io  composed resource "resource group": cannot apply the patch at index 1: metadata.labels[crossplane.io/claim-name]: no such field
  Normal   ComposeResources         23m (x8 over 25m)   defined/compositeresourcedefinition.apiextensions.crossplane.io  Composed resource "resource group" is not yet ready
  Normal   SelectComposition        28s (x31 over 25m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully selected composition
  ```
