### DISCUSSION TITLE
Crossplane RBAC doesn't allow creation of child resources of a Composition

### DISCUSSION THREAD

**Discussion by karthik-murugan-hpe** [crossplane/crossplane#4932] [Q&A] [answered]
By following the provider-template, I've implemented Operator for the resource "inventories".

I reference my Managed Resource in a Composition like below,
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdevices
spec:
  resources:
    - name: inventory
      base:
        apiVersion: myprovider.crossplane.io/v1alpha1
        kind: Inventory
...
...
```
When I create the claim for this Composition, Crossplane is unable to create the child resource. Describe on the claim reveals this error.

```
 Warning  ComposeResources         1s (x4 over 2s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  
    # composed resource "Inventory": cannot use dry-run create to name composed resource: inventories.myprovider.crossplane.io 
    # is forbidden: User "system:serviceaccount:crossplane-system:crossplane" cannot create resource "inventories" in 
    # API group "myprovider.crossplane.io" at the cluster scope
```

I checked the ClusterRole mapped to the service account mentioned above. It grants access to XRD, Composition resources but not the child resource and its apigroup. After explicitly adding another ClusterRole that grants access to the child resource' apigroup, I could get around this problem. Is this the expected behavior?

```
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.crossplane.io/aggregate-to-crossplane: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: crossplane
    meta.helm.sh/release-namespace: crossplane-system
  labels:
    app: crossplane
    app.kubernetes.io/component: cloud-infrastructure-controller
    app.kubernetes.io/instance: crossplane
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/part-of: crossplane
    app.kubernetes.io/version: 1.13.2
    helm.sh/chart: crossplane-1.13.2
  name: crossplane
rules:
- apiGroups:
  - infra.myprovider.com
  resources:
  - xdevices
  - xdevices/status
  verbs:
  - '*'
- apiGroups:
  - infra.myprovider.com
  resources:
  - xdevices/finalizers
  verbs:
  - update
- apiGroups:
  - infra.myprovider.com
  resources:
  - devices
  - devices/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - apiextensions.crossplane.io
  - pkg.crossplane.io
  - secrets.crossplane.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - watch
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - watch
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - watch
  - delete
```
