### DISCUSSION TITLE
Experience Report: Converting existing composition to use go-templating-function

### DISCUSSION THREAD

**Discussion by Piotr1215** [crossplane/crossplane#4943] [Show and tell]
# Context

Crossplane compositions are a powerful abstraction layer that enables platform teams to create a custom API for their internal customers to simplify and standardize the infrastructure management process. The composition authors wrestle with the complexity of cloud infrastructure and at the same time need to ensure stable and user-friendly API surface for the platform consumers. 

Historically, compositions were intended to support only very simple resources’ manipulation to allow the API calls to patch and transform the information passed from a claim or XR to the composition engine. The lack of touring complete language supporting the required transformations resulted in a very verbose YAML files with lots of repetitions, increasing the _toil_ of authoring compositions.  

With the addition of [compositions functions](https://github.com/crossplane/crossplane/releases/tag/v1.11.0) in the Crossplane v.1.11 it is possible to use a programming language (for now Go) to enrich and transform the authoring of compositions. 

This experience report details validating and testing the new [go-templating-function](https://github.com/crossplane-contrib/function-go-templating) by rewriting a simple internal platform-composites in the *go templating* style using the function engine.

# Use Case: Collapsing 2 compositions into 1

Since traditional composition's engine does not allow using conditionals, there is no way to render one composition or another using a parameter from claim. To illustrate this example, let’s look at the two compositions that render a GCP Bucket:

## Standard bucket

This very simple compostion renders a single GCP bucket

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xstoragebuckets.platform-composites.upbound.io
  labels:
    provider: gcp
    type: generic
spec:
  patchSets:
... Omitted for brevity
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: platform-composites.upbound.io/v1alpha1
    kind: XStorageBucket
  resources:
  - name: storagebucket
    base:
      apiVersion: storage.gcp.upbound.io/v1beta1
      kind: Bucket
      spec:
        forProvider: 
          location: us-west1
          storageClass: STANDARD
          providerConfigRef:
            name: default
    patches:
... Omitted for brevity
```

## Versioned Bucket

Another composition needs to be created to accommodate for a versioning setting.
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xstoragebuckets.platform-composites.upbound.io
  labels:
    provider: gcp
    type: generic
spec:
  patchSets:
... Omitted for brevity
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: platform-composites.upbound.io/v1alpha1
    kind: XStorageBucket
  resources:
  - name: storagebucket
    base:
      apiVersion: storage.gcp.upbound.io/v1beta1
      kind: Bucket
      spec:
        forProvider: 
          location: us-west1
          versioning:
            - enabled: true
          storageClass: STANDARD
          providerConfigRef:
            name: default
    patches:
... Omitted for brevity
```

In this case, we have to have 2 compositions and composition selector just for this one field.

## Using go-templating-function

The composition can be transformed as follows into just one using the `go-templating-function`

1. Install function

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/ezgi/function-go-templating:v0.0.1
  packagePullPolicy: Always
```

2. Convert the composition to use the go templating

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xstoragebuckets.platform-composites.upbound.io
  labels:
    provider: gcp
    type: generic
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: platform-composites.upbound.io/v1alpha1
    kind: XStorageBucket
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplate.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: storage.gcp.upbound.io/v1beta1
            kind: Bucket
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.metadata.name }}
              name: {{ .observed.composite.resource.metadata.name }}
              labels:
                owner: {{ .observed.composite.resource.spec.parameters.owner }}
                service: {{ .observed.composite.resource.spec.parameters.service }}
            spec:
              forProvider:
                location: {{ .observed.composite.resource.spec.parameters.location }}
                storageClass: {{ .observed.composite.resource.spec.parameters.class }}
              providerConfigRef:
                  name: {{ .observed.composite.resource.spec.parameters.environment }}
    - step: ready
      functionRef:
        name: function-auto-ready
```

Since this is new functionality, I had to ask and search for the right syntax. However, the errors I got on the XR were helpful in identifying the issues.

This implementation renders the *non-versioned* Bucket. Next steps are to change the XRD and template to accommodate for the versioning field.

Using the new `crossplane beta trace` command was helpful in checking the latest events on the composed resources:

![image](https://github.com/crossplane/crossplane/assets/8086638/2b85ed09-0c83-4c31-b0a5-fa64dc651f68)

## Adding the versioning field

1. Modify the XRD to set the versioning field with a boolean flag

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xstoragebuckets.platform-composites.upbound.io
spec:
  group: platform-composites.upbound.io
  names:
    kind: XStorageBucket
    plural: xstoragebuckets
  claimNames:
    kind: StorageBucket
    plural: storagebuckets
  defaultCompositionRef:
    name: storagebuckets.platform-composites.upbound.io
  connectionSecretKeys:
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Generic XRD parameters
                  properties:
                    versioningEnabled:
                      type: boolean
                      description: specify if the bucket should be versioned
                    owner:
                      type: string
                      description: Squad or individual who owns the cloud resource.
                    service:
                      type: string
                      description: Service resource belogs to, like shimmer, api etc.
                    location:
                      type: string
                      description: Passthrough location from cloud provider. Defaults to us-west1 for GCP.
                    environment:
                      type: string
                      description: Playground, dev, staging, production this maps to ProviderConfig that points to a specific project in GCP.
                    storageClass:
                      type: string
                      description: "Possible values: STANDARD, NEARLINE, COLDLINE. Defaults to STANDARD. The value is ingored for the secure bucket."
                  required:
                    - environment
                    - owner
                    - service
                    - versioningEnabled
              required:
                - parameters
```

2. Modify the composition template to add the conditional

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xstoragebuckets.platform-composites.upbound.io
  labels:
    provider: gcp
    type: generic
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: platform-composites.upbound.io/v1alpha1
    kind: XStorageBucket
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplate.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: storage.gcp.upbound.io/v1beta1
            kind: Bucket
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.metadata.name }}
              name: {{ .observed.composite.resource.metadata.name }}
              labels:
                owner: {{ .observed.composite.resource.spec.parameters.owner }}
                service: {{ .observed.composite.resource.spec.parameters.service }}
            spec:
              forProvider:
                location: {{ .observed.composite.resource.spec.parameters.location }}
                storageClass: {{ .observed.composite.resource.spec.parameters.storageClass }}
                {{- if .observed.composite.resource.spec.parameters.versioningEnabled }}
                versioning:
                  - enabled: true
                {{- end }}
              providerConfigRef:
                  name: {{ .observed.composite.resource.spec.parameters.environment }}
    - step: ready
      functionRef:
        name: function-auto-ready
```

3. Apply the claim with versioning enabled

```yaml
apiVersion: platform-composites.upbound.io/v1alpha1
kind: StorageBucket
metadata:
  name: sample-storage-12345
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      # Only provider GCP is available at the moment
      provider: gcp
      type: generic
  parameters:
    versioningEnabled: true
    owner: squad-platform
    service: platform-composites
    # Passthrough location from cloud provider
    # defaults to us-west1 for GCP
    location: us-west1 #Optional
    # This maps to ProviderConfig that points to a specific
    # project in GCP. Use default for local testing and playground for crossplane-playground
    environment: provider-gcp #Required
    # Possible values: STANDARD, NEARLINE, COLDLINE, ARCHIVE
    # Defaults to standard
    storageClass: STANDARD #Optional
```

The resource rendered correctly

```yaml
spec:
  deletionPolicy: Delete
  forProvider:
    location: us-west1
    project: squad-platform-playground
    publicAccessPrevention: inherited
    storageClass: STANDARD
    versioning:
    - enabled: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: provider-gcp
```

![image](https://github.com/crossplane/crossplane/assets/8086638/e01b3ed9-cc93-43cc-8150-b3792587ed51)

## Default values

Not all the schema fields are required, and for those the composition provides default values. `location` and `storageClass` are not required in the schema, and composition provides default values for those fields when omitted. Let’s add them to the template. Now supplying a `claim` without the location and storageClass fields will result in the default values being rendered like so.

```yaml
...
                location: {{ default "us-west1" .observed.composite.resource.spec.parameters.location }}
                storageClass: {{ default "STANDARD" .observed.composite.resource.spec.parameters.storageClass }}
...
```

## Bringing back PatchSets

This specific composition is very simple, but there are multiple others where the same patch needs to be applied to multiple resources. In the original composition we have the `ownerAndServiceLabels` that are applied to all resources that support labels.

```yaml
- name: ownerAndServiceLabels
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.owner
          toFieldPath: spec.forProvider.labels[owner]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.service
          toFieldPath: spec.forProvider.labels[service]
```

With the go-templating-function, it’s easy to define the *patchSet-like* behavior

Here is the modified composition

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xstoragebuckets.platform-composites.upbound.io
  labels:
    provider: gcp
    type: generic
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: platform-composites.upbound.io/v1alpha1
    kind: XStorageBucket
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplate.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            {{- define "ownerAndProjectLabels" }}
              labels:
                owner: {{ .observed.composite.resource.spec.parameters.owner }}
                service: {{ .observed.composite.resource.spec.parameters.service }}
            {{- end }}

            apiVersion: storage.gcp.upbound.io/v1beta1
            kind: Bucket
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.metadata.name }}
              {{ template "ownerAndProjectLabels" . }}
            spec:
              forProvider:
                location: {{ default "us-west1" .observed.composite.resource.spec.parameters.location }}
                storageClass: {{ default "STANDARD" .observed.composite.resource.spec.parameters.storageClass }}
                {{- if .observed.composite.resource.spec.parameters.versioningEnabled }}
                versioning:
                  - enabled: true
                {{- end }}
              providerConfigRef:
                  name: {{ .observed.composite.resource.spec.parameters.environment }}
    - step: ready
      functionRef:
        name: function-auto-ready
```

# Conclusion

In conclusion, the use of the `go-templating-function` in compositions authoring significantly simplifies the process of creating and managing resources with varying configurations and makes. 

It allows for the creation of compositions with conditional fields, reducing the need for multiple compositions for each variation of a resource. The re-introduction of PatchSets-like behavior makes the portability from P&T style compositions easier. 

Additionally using the [xrender function](https://github.com/negz/xrender) was very helpful and allows for checking how the resources will render based on the claim, composition and functions, like so (pro tip, running the command with `watch` makes the development loop even better):

![image](https://github.com/crossplane/crossplane/assets/8086638/140eb7a3-6312-4697-979d-e84bee4dfdf5)

```yaml
crossplane beta render ~/dev/platform-scratchpad/go-template-fn/examples/claim.yaml ~/dev/platform-scratchpad/go-template-fn/gcp-bucket/composite.yaml examples/functions.yaml
---
apiVersion: platform-composites.upbound.io/v1alpha1
kind: StorageBucket
metadata:
  name: sample-storage-12345
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/composition-resource-name: sample-storage-12345
  generateName: sample-storage-12345-
  labels:
    crossplane.io/composite: sample-storage-12345
    owner: squad-platform
    service: platform-composites
  name: sample-storage-12345
  ownerReferences:
  - apiVersion: platform-composites.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: StorageBucket
    name: sample-storage-12345
    uid: ""
spec:
  forProvider:
    location: us-west1
    storageClass: STANDARD
    versioning:
    - enabled: true
  providerConfigRef:
    name: provider-gcp
```

One nit is that it was a bit cumbersome is the long path to extracting values from the XRD, for example `.observed.composite.resource.spec.parameters.service` was a lot to type and can make the file a bit harder to read.

More information can be found in the [go-templating-function one-pager](https://github.com/crossplane/crossplane/pull/4935), big thanks to @ezgidemirel for creating the function! It signficantly improves the compostiions authoring process.
