### DISCUSSION TITLE
Provider configuration - via helm, which way is correct?

### DISCUSSION THREAD

**Discussion by nicraMarcin** [crossplane/crossplane#4988] [Q&A]
Hi,
I have question about configuring providers during install with helm. I'm going to use with AWS and use roles instead users. I've created role `arn:aws:iam::111122223333:role/crossplane-wi`.

in `my-values.yaml`
```yaml
provider:
  packages:
   - xpkg.upbound.io/upbound/provider-aws-s3:v0.43.1
   - xpkg.upbound.io/upbound/provider-aws-iam:v0.43.1

configuration:
  packages: []
   
```
How to configure these provider to use my aws role?
