### DISCUSSION TITLE
How to 3-way merge Composition patches

### DISCUSSION THREAD

**Discussion by nicks** [crossplane/crossplane#5171] [Q&A] [answered]
Hi! We're having trouble writing "reproducible" Compositions.

**Repro steps:**

Write a patch like this:

```
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.role
          toFieldPath: metadata.labels["my-label1"]
```

The next day, I decide that label name was wrong, so i modify the composition to do this:

```
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.role
          toFieldPath: metadata.labels["my-label2"]
```

**Expected behavior:**

Crossplane would re-apply the Composition and do a 3-way merge on the managed resource. The new resource would only have `my-label2`. `my-label1` would be removed.

**Actual behavior:**

Crossplane leaves the old state around, so that my resource has both `my-label1` and `my-label2`

**Additional info:**

This behavior seems very dangerous to me. It means Compositions can leak state from previous versions of the Composition. We can't guarantee that the desired state of the Composition reflects the current status of the resource.

Is there a way to get it to do a 3-way merge,  like Helm or `kubectl apply` would?
