### DISCUSSION TITLE
How can I get values from an Environment Config to a Composition and vice versa?

### DISCUSSION THREAD

**Discussion by tvandinther** [crossplane/crossplane#5436] [Q&A] [answered]
I have an environment config with some values, and I also have a composition with some values in spec. I need to get these values existing in the same context so that I can use `CombineFromComposite` or `CombineFromEnvironment` to patch a managed resource.

I saw in the [docs](https://docs.crossplane.io/latest/concepts/environment-configs/#patch-a-composite-resource) that you can patch a composite resource with an environment but I'm not able to get the values to appear in the status of the composition as I would expect. The `# Removed for Brevity` along with the inconsistent indentation in the example also makes me unsure of the correct way to define these patches. My environment section currently looks like this:

```yaml
spec:
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: cluster-metadata
    patches:
      - type: ToCompositeFieldPath
        fromFieldPath: oidcUri
        toFieldPath: status.oidcUri
      - type: ToCompositeFieldPath
        fromFieldPath: oidcArn
        toFieldPath: status.oidcArn
```

When I view the status of my composite resource I do not see these fields appear which in turn causes my combine patch to fail specifying a required property in `atProvider` on my managed resource.

Any thoughts or ideas? Thanks.

**Comment by bobh66** [comment]
Are the `status.oidcUri` and `status.oidcArn` fields defined in your XRD?  If not then kubernetes will discard them unless you tell it to allow unknown fields with the `x-kubernetes-preserve-unknown-fields: true` attribute.

**Comment by phisco** [comment]
Can you share your CompositeResourceDefinition? Or at least the part where you define those fields in the status

**Comment by tvandinther** [comment, marked as answer]
I've determined that it came down my usage of composition functions and using `mode: pipeline`. I got a working XR by using the `environment-config` and `patch-and-transform` functions together. I wrote to `status` from the environment patches section of patch and transform.

```yaml
mode: Pipeline
  pipeline:
    - step: environmentConfigs
      functionRef:
        name: crossplane-contrib-function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: cluster-metadata
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        environment:
          patches:
            - type: ToCompositeFieldPath
              fromFieldPath: oidcUri
              toFieldPath: status.irsa.oidcUri
            - type: ToCompositeFieldPath
              fromFieldPath: oidcArn
              toFieldPath: status.irsa.oidcArn
            - type: ToCompositeFieldPath
              fromFieldPath: clusterName
              toFieldPath: status.clusterName
```
