### DISCUSSION TITLE
Automatic IRSA configuration for provider installed from package

### DISCUSSION THREAD

**Discussion by vilkovtato** [crossplane/crossplane#5587] [Q&A]
Issue link: https://github.com/crossplane/crossplane/issues/5598

Hi, I'd like to kindly ask for help.

I'm have crossplane package with following content:
- composition
- compositionresourcedefinition
- (dependson) provider iam
- (dependson) provider s3
The configuration file looks like this:

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: myconfiguration
spec:
  crossplane:
    version: ">=v1.13.1"
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-aws-s3
    version: ">=v1.3.1"
  - provider: xpkg.upbound.io/upbound/provider-aws-iam
    version: ">=v1.3.1"
```
Now in the cluster, there is already installed default ProviderConfig:

```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
```

After installing my crossplane package into the cluster, the providers (s3,iam) are automatically using the aws credentials from the ProviderConfig.

But this should be now reworked to use IRSA.  After I changed the ProviderConfig to IRSA and install the crossplane package, the new created providers pods (for s3, iam) does not use IRSA, meaning the created service accounts for the providers pods does not have annotation with that IAM role.

When I will be installing the crossplane package to different eks clusters in different AWS accounts, the IAM role will be always different. This is why I need that after the package installation, the newly created providers will AUTOMATICALY use IRSA.

I didnt find (or did not figure it out) documentation, how to do it. 

Could anybody please help?

**Comment by bobh66** [comment]
https://github.com/crossplane-contrib/provider-upjet-aws/blob/main/AUTHENTICATION.md#authentication-using-irsa

**Reply by vilkovtato** [reply]
@bobh66 - thank you for help

But there is a problem. You are pointing to docu, where you are manually creating providers and there you can configure `ControllerConfig`, `Provider` and `ProviderConfig`:

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: irsa-controllerconfig
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/iam-role-name
spec:
  podSecurityContext:
    fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.4.0
  packagePullSecrets:
    - name: package-pull-secret
  controllerConfigRef:
    name: irsa-controllerconfig
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: irsa
spec:
  credentials:
    source: IRSA
```

But when you install providers via OCI image, there is no place to configure the `controllerConfigRef:`
