### DISCUSSION TITLE
Conditionals

### DISCUSSION THREAD

**Discussion by autarchprinceps** [crossplane/crossplane#5727] [Q&A]
I am still somewhat new to crossplane, but know my way around Terraform, CloudFormation and even a bit of CDK.
The thing I haven't really found an equivalent for yet, is conditionals/ternary operators.
For example in a Amazon MQ, if it is single instance, you need to provide it with one subnet, if it is multi az you need to provide it with two. You typically have and lookup 3 AZs/subnets.
In terraform that just means you do a
```terraform
subnet_ids        = var.deployment_mode == "ACTIVE_STANDBY_MULTI_AZ" ? [data.aws_subnets.private_subnets.ids[0], data.aws_subnets.private_subnets.ids[1]] : [data.aws_subnets.private_subnets.ids[0]]
```
And similar in CloudFormation you just use Fn::If

In crossplane I can certainly select only one subnet, as well as provide the deployment mode from a parameter as patches to in this case a apiVersion: mq.aws.upbound.io/v1beta1, kind: Broker, but similar things apply with a lot of resource types.
```yaml
- fromFieldPath: status.vpcData.subnets[0]
  toFieldPath: spec.forProvider.subnetIds[0]
- fromFieldPath: spec.deploymentMode
  toFieldPath: spec.forProvider.deploymentMode
```
But how would I provide a second subnet conditionally on what the deployment mode is? Or more general, how would I add any condition to what patch either gets applied at all, or what the value of the patch is taken from?
Conditions are basically everywhere in other IaC languages.
