### DISCUSSION TITLE
BasePathMapping with provider-aws-apigateway

### DISCUSSION THREAD

**Discussion by bjrobinson64** [crossplane/crossplane#5792] [Q&A]
Hello everyone, I am trying to deploy a RESTapi to aws using provider-aws-apigateway. I am having an issue with the BasePathMapping kind where it is not wanting to create correctly.

Here is the yaml I am using with dummy values:

```
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: BasePathMapping
metadata:
 name: apiName
spec:
 providerConfigRef:
  name: aws-dev
 forProvider:
  apiIdSelector:
   matchLabels:
    api: apiName
  domainName: domainName
  region: us-east-1
  stageName: stageName
``` 

When I run create this it will create correctly and it will connect the api to the custom domain name, however I need to add a base path like this:

```
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: BasePathMapping
metadata:
 name: apiName
spec:
 providerConfigRef:
  name: aws-dev
 forProvider:
  apiIdSelector:
   matchLabels:
    api: apiName
  domainName: domainName
  region: us-east-1
  stageName: stageName
  basePath: exp/v1/
``` 

When I try to create this I am getting this error:

```
async create failed: failed to create the resource: [{0 creating API Gateway Base Path Mapping: BadRequestException: API Gateway V1 doesn't support the slash character (/) in base path mappings. To create a multi-level base path mapping, use API Gateway V2. []}]
``` 

From what I have read API Gateway V2 is for WebSocket and HTTP apis and not necessarily for REST apis. I have been trying to look online and have not been able to find any examples of a BasePathMapping resource that actually uses the basePath section. Any help at all is greatly appreciated.
