### DISCUSSION TITLE
"already controlled by ProviderRevision" errors after upgrading providers

### DISCUSSION THREAD

**Discussion by zaczekvol** [crossplane/crossplane#5801] [Q&A]
Hi, we upgraded azure providers from 1.01 to 1.30. However, providers that were already in use (they manage some resources in azure), are stuck the following errors:
 packages/providerrevision.pkg.crossplane.io  cannot establish control of object: accounts.storage.azure.upbound.io is already controlled by ProviderRevision provider-azure-storage-e2a6272df00a

Following some recommendations, we tried to delete crd, but the deletion command hangs. What is interesting, the previously unused providers got update with no issues. There seems to be some sort of dependency lock. Would you have any advice?

**Comment by trampfox** [comment]
I encountered the same issue for the `tables.bigquery.gcp.upbound.io` CRD after upgrading the BigQuery provider and I managed to solve it by removing the provider revision from the `ownerReferences` of the CRD

```
[...]
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ProviderRevision
    name: provider-bigquery-85e8d6446b52
    uid: c1bf9988-91f0-4226-8514-c848dfefbeb1
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: false
    kind: Provider
    name: provider-gcp
    uid: ad9b8498-0358-498e-8d4c-b27a2d9ea17c
[...]
```

I'm unsure if there's a more elegant/cleaner solution, but this approach worked.
