### DISCUSSION TITLE
Compositions: how to create an arbitrary number of resources (e.g. using arrays)

### DISCUSSION THREAD

**Discussion by l-rossetti** [crossplane/crossplane#5819] [Q&A] [answered]
I'm implementing compositions by leveraging the go-template function. Compositions feel great until I need the composition to create an arbitrary number of resources. For example I have the following composite resource where vpcs and their subnets are arrays of elements with a `name` parameter.  The produced VPC or Subnet templates require a resource name annotation (e.g. `crossplane.io/composition-resource-name: vpc1-us-east-2-vpc`) which has forcefully to be dynamic (either based on the `name` parameter itself or the array index).

The issue I cannot fix is that if somebody modifies the `name` parameter or, in the "index" case, the array is shuffled, crossplane will detect a new resource name cause the annotation is updated, so it proceeds deleting the old resource and creating a new one.

--> How can I allow the composition to create an arbitrary number of resources without deleting the old ones when the annotation changes? 

The way I'm doing it now is to move the complexity of the arbitrary number of resources at helm chart level: basically the chart loops on the arrays and generates multiple composite resources, each with a `metadata.name` that depends on the `name` parameter in the values file. Doing so, the compositions will generate a fixed number of resources whose resource-name annotation is static. Of course if I modify the `name` parameter, the chart will produce a new composite but it does not delete the old one so I can intercept the "problem" with no risk of deleting something I don't want to delete. 
Is it possible moving this logic into the composition itself or this it not the expected way of using composition?

Composite resource:
```
apiVersion: aws.example.com/v1
kind: XComp
metadata:
  name: xcomptest
spec:
  parameters:
    deletionPolicy: Delete
    providerConfigName: aws-provider
    region: us-east-2
    
    vpcs:
    - name: vpc1   # can change
      cidr: 10.137.0.0/16
      subnets:
      - name: subnet1 # can change
        cidr: 10.137.1.0/24
      - name: subnet2 # can change
        cidr: 10.137.2.0/24
    - name: vpc2 # can change
      cidr: 10.138.0.0/16
      subnets:
      - name: subnet1 # can change
        cidr: 10.138.1.0/24
      - name: subnet2 # can change
        cidr: 10.138.2.0/24
```

Composition template with arbitrary number of objects:
```
{{ $params := .observed.composite.resource.spec.parameters }}
{{ $name := .observed.composite.resource.metadata.name }}
{{- range $vpc := $params.vpcs }}
{{ $id := printf "%s-%s-%s" $vpc.name $params.region "vpc" }}
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  labels:
    aws.example.com/resource-id: {{ $id }}
  annotations:
    {{ setResourceNameAnnotation ($id) }}
spec:
  forProvider:
    cidrBlock: {{ $vpc.cidr }}
    enableDnsHostnames: true
    enableDnsSupport: true
    tags:
      Name: {{ $id }}
    region: {{ $params.region }}
  providerConfigRef:
    name: {{ $params.providerConfigName }}
  deletionPolicy: {{ $params.deletionPolicy  }}
{{- range $v := $vpc.subnets }}
{{ $subnetId := printf "%s-%s-%s" $vpc.name "a" $v.name }}
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    {{ setResourceNameAnnotation ($subnetId) }}
spec:
  forProvider:
    cidrBlock: {{ $v.cidr }}
    tags:
      Name: {{ $subnetId }}
    region: {{ $params.region }}
    vpcIdSelector:
      matchControllerRef: true
      matchLabels:
        aws.example.com/resource-id: {{ $id }}
    availabilityZone: {{ $params.region }}a
  providerConfigRef:
    name: {{ $params.providerConfigName }}
  deletionPolicy: {{ $params.deletionPolicy }}
{{- end }}
{{- end }}
```

**Comment by bobh66** [comment, marked as answer]
> --> How can I allow the composition to create an arbitrary number of resources without deleting the old ones when the annotation changes?

The short answer is you can't - or more accurately you can but you probably shouldn't.

The Claim is telling Crossplane what you want to exist, and only what you want to exist.  If you change the name of an existing resource you are telling Crossplane that you no longer want the old resource and you want a new one with the specified name.  If you want the old one to continue to exist you should add a new entry for the new resource and leave the existing resource unchanged.

You definitely don't want to be using index numbers for composition-resource-names unless you know that the same resources will always be generated in the same order.  If the indices reshuffle things will get deleted/recreated which is almost never what you want.

There are ways to allow the cloud resources to continue to exist when the associated Managed Resources are deleted, but it sounds like you want the Managed Resources to continue to exist, which means you can add new but not change existing.

**Reply by l-rossetti** [reply]
Thank you for answering. 
So what I'm doing by moving the complexity at chart level seems the way of doing it. In my opinion this "limitation" should be documented very explicitly, cause I had many issues in understanding crossplane best practices since there are none in the documentation and someone can understand them only by investing really a lot of time testing the system. Something else coming to my mind is about the Composite state. I have understood it can be used not only for providing an overview but also to share some parameters between resources of the same composition. But this is again a best practice which is not highlighted anywhere (or maybe I missed it), and I guess there many others.

To conclude, my suggestion is to create a "Best Practices" page into the documentation cause this will fasten a lot crossplane understanding and will help adopters to estimate crossplane and its compositions in a more effective way.

**Comment by bobh66** [comment]
Thanks for the documentation suggestions.  We can definitely look into some improvements.

I'm curious why you view this as a "limitation"?  This is how Crossplane is designed to work - the actual state is mutated to match the requested state.  In this example the requested state was modified to remove one entry and create a new one, so that's what Crossplane did.  How is Crossplane supposed to know that you didn't want it to remove a resource that is no longer being requested in the Claim?

**Reply by l-rossetti** [reply]
I called it a "limitation" because with Crossplane, you can generate resources through compositions, monitor them, and perform reconciliation, but the generation of resources is limited to those you already know will exist. This forces developers to wrap the composition, for instance, with a Helm chart when dealing with an arbitrary number of resources. This is to prevent the provider-side resource from being deleted if the array is mixed or if a name (a non-unique parameter on the provider side) is changed.
Perhaps I shouldn't call it a "limitation" because this seems to be a feature of Crossplane. However, with this logic, compositions need other tools to cover the case I mentioned, so that's why it seems limited.

If this resource-name management that is specific to crossplane way of working (and not to the cloud provider or kubernetes itself) could be made transparent or less prone to the human error for the developer, compositions would become a more powerful and comprehensive tool. 

Regarding the best practices page, I believe it can help users understand how to leverage Crossplane to its fullest potential.

**Comment by bobh66** [comment]
I don't think I'm following the scenario you are describing, and how wrapping the claim(s) inside a Helm chart solves the problem.  Some people use Helm charts to deploy claims for a variety of reasons, but I don't know of any scenarios that require a Helm chart to do something that the Composition cannot achieve.

**Reply by negz** [reply]
I'm also not quite following what @l-rossetti is trying to do and why Helm appears to be necessary.

It should definitely be possible to compose an arbitrary number of resources using functions. The only constraints are:

* The function must produce the same set of resources every time it runs
* A resource's `gotemplating.fn.crossplane.io/composition-resource-name` annotation must be the same every time

If you're using a name that can change across runs (e.g. `subnet1`) I'd suggest adding an additional field (e.g. `id`) that won't and using that as the `composition-resource-name`.

**Reply by l-rossetti** [reply]
If I forget about the chart and build a composition whose resources have the `composition-resource-name` based on the `name` parameter of my example, whenever this parameter changes then crossplane will delete the resource and create a new one automatically (of course it depends on the `managementPolicies`) which is something critical that I don't want cause I don't have control over it. That's why having an Helm chart would solve this: the chart would create an arbitrary number of composites (e.g. the XVPCs), with a `metadata.name` that can change of course. But this change, in this case, would generate a new composite resource instead with a new kubernetes name: if someone changes the name, the old composite would still be there and would require an explicit deletion done by manual intervention (or via argocd) cause crossplane cannot delete it automatically since it is not in control of it. With this approach I would be able to intercept this kind of destructive changes (cause argocd would tell me "there is a new composite resource to be created while the old one should be deleted, it's up to you") and possibly I can avoid the deletion to happen because this is in my full control.

If I want to use only Compositions instead, I should support an additional `id` parameter (as per @negz suggestion) which must not be modified (even though I cannot enforce this,  because anyway someone would be able to update it being simply a composition parameter). Another issue with the `id` approach is that if someone wants to add an additional VPC for example, he would most likely copy/paste the parameters structure from an already existing one and so he would copy also the `id`. If he is not going to change the `id` keeping it unique within the composition, then crossplane would see two resources with same `id` and will keep only one (most likely the last one declared) cause it doesn't warn the user with an error and would delete the existing one which is again something I don't want.

So, I think that the `id` parameter may give a little bit more safety with respect to `vpc.name` but it does not really cover all the possible human error cases. Since here we are speaking about infrastructure which is a very critical topic, I would like to be in the safest possible case which until now I can only reach by introducing a wrapper like a chart (which overlaps with compositions in the ability of generating manifests from templates). This mechanism requires two layers, each with its own inputs and validations. Moreover adding an `id` parameter, which is only needed by crossplane an nothing else, to me seems a workaround that I would happily introduce only if there is a way to ensure that those ids would be unique within the composition (maybe through a function that checks the uniqueness or through Kubernetes AdmissionPolicy(ies)?!). In an ideal world this tracking logic should be hidden by crossplane. I don't even know if something can be done on crossplane side cause I understand that somehow it needs to be able to track resources... maybe I'm approaching it in a wrong way and it's only about changing my mindset.

**Reply by l-rossetti** [reply]
to add some context, the Helm chart template would look like this:
```
# .Values.subnets is an object mapping the subnet name to the subnet parameters
{{- range $subnetName, $subnet := .Values.subnets }}
---
apiVersion: aws.banksealer.com/v1
kind: XSubnet
metadata:
  name: {{ $subnetName }} # this will change when updating the name, so a new XSubnet composite is going to be applied to Kubernetes but the old one still remains until I explicitly delete it (and argocd will warn me about it)
spec:
  parameters:
    providerConfigName: {{ $.Values.providerConfigName }}
    deletionPolicy: {{ $.Values.deletionPolicy }}
    cidr: {{ $subnet.cidr }}
    # ... other parameters here coming from the .Values and passed as parameters to the composition...
{{- end }}
```

The XSubnet composition would be:
```
{{ $params := .observed.composite.resource.spec.parameters }}
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    {{ setResourceNameAnnotation ("subnet") }}
spec:
  forProvider:
    cidrBlock: {{ $params.cidr }}
    # .... 
  providerConfigRef:
    name: {{ $params.providerConfigName }}
  deletionPolicy: {{ $params.deletionPolicy }}
---
# other resources related to the XSubnet composition
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
# .... 
```
