### DISCUSSION TITLE
Using non-desired-state go composition function output for patch&transform

### DISCUSSION THREAD

**Discussion by LibertyWalk** [crossplane/crossplane#5864] [Q&A]
I have a composition which defines a pipeline. Inside the pipeline, I have a go composition function which returns a list of GUIDs. Currently, I'm writing this list into the pipeline context. Now, I want to use this list of GUIDs in my compostion somehow.
Let's say I want to use patch & transform to patch this list of GUID strings into the owners array of a azuread group.
But I cannot figure out how I would access the pipeline context inside of my composition.

Is that even possible? Would it maybe look something like:

```
              apiVersion: groups.azuread.upbound.io/v1beta1
              kind: Group
              spec:
                forProvider:
                  ....
                  owners: context.ownerIds # a preceding go composition function would write the ownerIds into the pipeline context
```

Or would I need to use https://github.com/crossplane-contrib/function-go-templating somehow?
