### DISCUSSION TITLE
Namespace/name of a Compositions combined secret

### DISCUSSION THREAD

**Discussion by cer** [crossplane/crossplane#5947] [Q&A]
The [Connection secrets in Compositions section the documentation](https://docs.crossplane.io/v1.17/concepts/connection-details/#connection-secrets-in-compositions) says:

> Crossplane also creates a secret object for the entire Composition saved in the namespace defined by writeConnectionSecretsToNamespace with a Crossplane generated name.

But my custom resource contains:

```
apiVersion: servicedatabase.chrisrichardson.net/v1alpha1
kind: ServiceDatabase
...
  writeConnectionSecretToRef:
    name: customer-service-postgres-secrets
    namespace: default
```

I never see the a Secret with a Crossplane generated name.

The combined secrets (ServiceDatabase only defines a single Instance.rds.. resource so I am assuming it's the combined secret)  appear to be written to the `customer-service-postgres-secrets` Secrets, which is great.

Do the docs need to be updated?
