### DISCUSSION TITLE
Run Crossplane Render in CI pipeline

### DISCUSSION THREAD

**Discussion by ma-ble** [crossplane/crossplane#5955] [Q&A]
Hi, 
is it possible to run

```crossplane render xr.yaml composition.yaml ./functions```

in a CI pipeline? 

Currently I have troubles with the fact that the function`s containers starting within the crossplane render process use localhost. The function containers run inside the dind container and their ports are only exposed on localhost and therefore not reachable from the pipeline container. How can I adjust my configuration in order to get access to the function containers to run "crossplane render" within a CI pipeline?

```
run_crossplane_render:
  stage: test
  image: $DOCKER_AND_CROSSPLANE_CLI
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  services:
    - docker:dind
  script:
    - crossplane render xr.yaml composition.yaml functions.yaml
```

I don`t want to use a VM in the pipeline as mentioned in this discussion (https://github.com/crossplane/crossplane/discussions/5790).

I`m using crossplane version: v1.17.0.
