### DISCUSSION TITLE
Crossplane configure Airflow to sync with GitHub

### DISCUSSION THREAD

**Discussion by sajmo744** [crossplane/crossplane#5964] [Q&A]
Hi,

I have Crossplane installed in KIND.  Using the below code I can successfully deploy Airflow using composition, but it doesn't sync with Github.  No gitsync sidecar container is there.  I have also applied my secrets yaml which stores my gitsync credential.

Using Helm manually works by setting the Gitsync values in a yaml file and Airflow successfully syncs with Github.  Just can't get it working with Crossplane.

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xairflow.composite.joe.blogs.net
spec:
  compositeTypeRef:
    apiVersion: joe.blogs.net/v1alpha1
    kind: XAirflow
  resources:
    - name: airflow-deployment
      base:
        apiVersion: helm.crossplane.io/v1alpha1
        kind: Release
        spec:
          forProvider:
            chart:
              name: airflow
              repository: https://airflow.apache.org
              version: 1.15.0
            namespace: airflow-deployment
            values:
              airflow:
                executor: "KubernetesExecutor"
                fernetKey: "45677890002345666765436653242433523687789="
                gitSync:
                  enabled: true
                  repo: "git@github.com:JOE-BLOGS/joeblogs-airflow-dag.git"
                  branch: "main"
                  rev: "HEAD"
                  depth: 1
                  subPath: "dags"
                  sshKeySecret: "airflow-ssh-secret"
                  maxFailures: 0
                  syncWait: 30
          providerConfigRef:
            name: provider-helm
```
