### DISCUSSION TITLE
Assist defining CompositeResourceDefinition having a specific Claim

### DISCUSSION THREAD

**Discussion by lamerix** [crossplane/crossplane#5970] [Q&A] [answered]
Hi there,

I am facing difficulties to define the correct `CompositeResourceDefinition` having a specific `Claim`.
The aim is to provide my users a way to pass their own custom configuration(s) in the `Claim` for S3 bucket policies.
When rendering locally with `crossplane beta render claim.yaml composition.yaml functions.yaml` (_I am with v.1.16_) all is rendered fine as per my expectations, i.e. I see the custom input attributes from the Claim put in the correct places as per the Composition. I am using `function-go-templating` in my Composition if that matters. Unfortunately cannot share more around my Composition due to NDA.
However when I push the Claim all the attributes for custom S3 policies are empty in my Control Plane, cloud hosted by Upbound. So far my suspicion for the empty attributes fall on the Definition as this is the only component in the entire setup I cannot test locally.

The `spec` part of my Claim is:
```
spec:
  parameters:
    name: my-crossplane-bucket
    region: us-east-1
    bucketPolicy:
      customPolicy:
        myS3statement1:
          effect:
            - Allow
          actions:
            - s3:Get*
            - s3:Put*
          principal:
            - myIAMuser1
            - myIAMuser2
          prefix:
            - /
            - /*
          conditions:
            - test: StringEquals
              variable: aws:sourceVpce
              values: ["vpce-111111111", "vpce-123456789"]
```
Where `spec.parameters.bucketPolicy.customPolicy` can have the definitions for multiple statements as `myS3statement1`.

When rendering locally I printed `spec.parameters.bucketPolicy.customPolicy` and got the following data structure that match the Claim above:
```
map[
  myS3statement1:map[
    actions:[
      s3:Get*
      s3:Put*
    ]
    conditions:[map[
      test:StringEquals
      values:[
        vpce-111111111
        vpce-123456789
      ]
      variable: aws:sourceVpce
      ]
    ]
    effect:[Allow]
    prefix:[
      /
      /*
    ]
    principal:[
      myIAMuser1
      myIAMuser2
    ]
  ]
]
```

Instead of sharing my Definition, actually I tested multiple ones, none of which seems to work with the cloud hosted Control Plane, I decided to ask directly what should be the correct `CompositeResourceDefinition` for `spec.parameters.bucketPolicy.customPolicy` having in mind the above Claim and data structure for `spec.parameters.bucketPolicy.customPolicy`.

Thanks in advance.

**Comment by lamerix** [comment, marked as answer]
After testing various definitions I finally get it working.
Sharing the definition that works for me according the mentioned claim.
```
bucketPolicy:
  type: object
  properties:
    customPolicy:
      type: object
      additionalProperties:
          type: object
          properties:
            actions:
              type: array
              items:
                type: string
            conditions:
              type: array
              items:
                type: object
                properties:
                  test:
                    type: string
                  values:
                    type: array
                    items:
                      type: string
                  variable:
                    type: string
            effect:
              type: array
              items:
                type: string
            prefix:
              type: array
              items:
                type: string
            principal:
              type: array
              items:
                type: string
```
