### DISCUSSION TITLE
context deadline exceeded: Get "https://xpkg.upbound.io/v2/"

### DISCUSSION THREAD

**Discussion by diegoavitorino** [crossplane/crossplane#5995] [General]
I'm facing the error bellow by trying to deploy any provider

Warning  UnpackPackage  35s   packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request failure: Get "https://xpkg.upbound.io/v2/": context deadline exceeded: Get "https://xpkg.upbound.io/v2/"

![image](https://github.com/user-attachments/assets/99d1603d-5ccd-4023-862d-a5051ba5a576)

I suspect it may be proxy, but I can not set env proxy

Error: strict decoding error: unknown field "spec.env"

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
   env:
     - name: NO_PROXY
       value: ".."
     - name: HTTP_PROXY
       value: "http://...."
     - name: HTTPS_PROXY
       value: "http://....."
  package: xpkg.upbound.io/upbound/provider-aws-s3:v1.14.0
  runtimeConfigRef:
    name: irsa-runtimeconfig

**Comment by bobh66** [comment]
Use the `extraEnvVars*` options in the helm chart to set the required proxy env vars:

```
# -- Add custom environmental variables to the Crossplane pod deployment.
# Replaces any `.` in a variable name with `_`. For example, `SAMPLE.KEY=value1` becomes `SAMPLE_KEY=value1`.
extraEnvVarsCrossplane: {}

# -- Add custom environmental variables to the RBAC Manager pod deployment.
# Replaces any `.` in a variable name with `_`. For example, `SAMPLE.KEY=value1` becomes `SAMPLE_KEY=value1`.
extraEnvVarsRBACManager: {}
```

**Comment by bobh66** [comment]
If your Provider deployments require proxy variables you can use `DeploymentRuntimeConfig` to set them.

**Reply by diegoavitorino** [reply]
By trying to set:

Error: strict decoding error: unknown field "spec.env"

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig
spec:
  env:
    - name: NO_PROXY
      value: "..."
    - name: HTTP_PROXY
      value: "..."
    - name: HTTPS_PROXY
      value: "..."
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::,,,:role/BURoleForCrossplane

**Comment by bobh66** [comment]
```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: runtimeconfig
spec:
  deploymentTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/ROLE
    spec:
      selector: {}
      template:
        spec:
          containers:
          - args:
            - --debug
            env:
            - name: NO_PROXY
              value: localhost
            name: package-runtime
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/ROLE
```
