### DISCUSSION TITLE
Confusion regarding controllerconfig usage on provider family

### DISCUSSION THREAD

**Discussion by ashishvaishno** [crossplane/crossplane#5998] [Q&A]
Hello,

I migrated to provider family last year, after doing so I am a bit confused whether I should still be using controllerconfig or not

In past I created a SA, controller config and referenced it in the provider
SA :
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-aws-provider
  namespace: crossplane-system
  annotations:
    eks.amazonaws.com/role-arn: xxxxx
```
Controller config :
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    eks.amazonaws.com/role-arn: xxxxx
  name: aws-controller-config
spec:
  args:
  - --debug
  - --enable-external-secret-stores
  podSecurityContext:
    fsGroup: 2000
  serviceAccountName: crossplane-aws-provider
```
Provider :
```
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-s3
spec:
  package: xpkg.upbound.io/upbound/provider-aws-eks:v1.0.0
  controllerConfigRef:
    name: aws-controller-config
```
Provider config using IRSA per env ([docs](https://marketplace.upbound.io/providers/upbound/provider-family-aws/latest/resources/aws.upbound.io/ProviderConfig/v1beta1#:~:text=source%3A%20PodIdentity-,irsa%2Dwith%2Drole%2Dchaining,-apiVersion%3A%20aws)):
```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider-config-<dev/stage/prod>
spec:
  assumeRoleChain:
  - roleARN: xxxx-<dev/stage/prod>
  credentials:
    source: IRSA
```

Because of this setup, now my audit logs has blow up and I can see that the SA is constantly getting updated. 
```
k get sa -n crossplane-system -w | grep crossplane-aws-provider                                                                                                                                                                                                       ─╯
NAME                                       SECRETS   AGE
crossplane-aws-provider                    0         480d
crossplane-aws-provider                    0         480d
crossplane-aws-provider                    0         480d
crossplane-aws-provider                    0         480d
crossplane-aws-provider                    0         480d
```
How can I fix this?

I am running crossplane version 1.14.5

Regards
Ashish
