### DISCUSSION TITLE
Updating AKS VM size gives requires disabling "lifecycle.prevent_destroy"

### DISCUSSION THREAD

**Discussion by sandkre** [crossplane/crossplane#6083] [Q&A] [answered]
I have an issue with updating my default node pool VM size In AKS.  I set the "temporaryNameForRotation" value and updated the VM size and got the following error:

`managed/containerservice.azure.upbound.io/v1beta1, kind=kubernetescluster  cannot run plan: plan failed: Instance cannot be destroyed: Resource azurerm_kubernetes_cluster.mycluster has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag`

YAML config:
```yaml
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: cluster-iac
  labels:
    clusterName: mycluster
spec:
  deletionPolicy: Orphan
  forProvider:
    kubernetesVersion: "1.30"
    defaultNodePool:
      - name: default
        vmSize: Standard_D4s_v5
        enableAutoScaling: true
        maxPods: 20
        maxCount: 2
        minCount: 1
    networkProfile:
      - networkPlugin: azure
    resourceGroupNameRef:
      name: my-rg
  providerConfigRef:
    name: cluster-config
```
Where can this lifecycle property be configured?

Version: 1.15.0
