### DISCUSSION TITLE
Composite Resource readiness and manged resources without readiness

### DISCUSSION THREAD

**Discussion by twobiers** [crossplane/crossplane#6086] [Q&A] [answered]
I had the Idea to create a composition using the function-go template which itself creates a ProviderConfig. The problem with this is, that the ProviderConfig is not a managed resource as per definition and does not have a resource readiness, which leads to the composite resource never becoming ready.

Is there a way to deal with that kind of problem? I might use the kuberentes provider to create the ProviderConfig manifest instead, but still I wonder if I could somhow "patch" the readiness or simlar.

Here is an example
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xproviderconfigs.example.com
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: XProviderConfig
  mode: Pipeline
  pipeline:
  - step: render-templates
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          apiVersion: azure.upbound.io/v1beta1
          kind: ProviderConfig
          metadata:
            annotations:
              {{ setResourceNameAnnotation "new-provider-config" }}
            name: new-provider-config
          spec:
            clientID: 4816e3b5-6474-4c68-9b7c-62f88405f6a8
            credentials:
              source: SystemAssignedManagedIdentity
            subscriptionID: 4816e3b5-6474-4c68-9b7c-62f88405f6a8
            tenantID: 4816e3b5-6474-4c68-9b7c-62f88405f6a8
          ---
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
```

**Comment by bobh66** [comment, marked as answer]
You can set the ready flag manually:

```
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: bucket
    gotemplating.fn.crossplane.io/ready: "True"
spec: {}
```
