### DISCUSSION TITLE
Problem pushing first composition function

### DISCUSSION THREAD

**Discussion by chelala** [crossplane/crossplane#6183] [Q&A] [answered]
Hello:

I followed https://docs.crossplane.io/latest/guides/write-a-composition-function-in-go/ tutorial for a function in go. 
The local building workflow and Manuel push works OK, and GitHub action for the most part works also OK, except for push. I followed the final paragraph about setting up secret in GitHub but Ir show errors.

> If you push the function to a GitHub repository the template automatically sets up continuous integration (CI) using [GitHub Actions](https://github.com/features/actions). The CI workflow will lint, test, and build your function. You can see how the template configures CI by reading .github/workflows/ci.yaml.
> 
> The CI workflow can automatically push packages to xpkg.upbound.io. For this to work you must create a repository at https://marketplace.upbound.io/. Give the CI workflow access to push to the Marketplace by creating an API token and [adding it to your repository](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository). Save your API token access ID as a secret named XPKG_ACCESS_ID and your API token as a secret named XPKG_TOKEN.

I created a free account in unbound some time ago and intend to push it to the organization.
In https://accounts.upbound.io/settings/tokens I added an API Token for pushing the composition function

The error is:

https://github.com/chelala/function-fluxcd-tenant-crossplane-providers-usage-resource-crbs/actions/runs/12356618603/job/34485141194#step:5:58
in the docker login step
Error: Error response from daemon: Get "https://xpkg.upbound.io/v2/": unauthorized:

in this test the XPKG_ACCESS_ID is the one created in the format 11111111-1111-1111-1111-111111111111
the XPKG_TOKEN is the whole ey....... token showed.

The repo is public: https://github.com/chelala/function-fluxcd-tenant-crossplane-providers-usage-resource-crbs

Any ideas how to make it work?

**Comment by jastang** [comment, marked as answer]
hi @chelala, since the workflow file in your repository uses `docker login`, you have to create a [robot token](https://docs.upbound.io/accounts/identity-management/robots/) instead of a personal access token to auth with xpkg.upbound.io in your CI.

Once you've created the robot token, the access ID and token should be updated in your GitHub Actions secrets respectively. the last step is to ensure your robot token has [write access to your repository](https://docs.upbound.io/accounts/identity-management/teams/#manage-repository-permissions).

thanks for identifying the issues here -- we'll follow up on the documentation as well to ensure it's more explicit as there are multiple token types.

**Reply by chelala** [reply]
Hi @jastang:
Your response have the solution!
the robot token looks promising but although I can create a robot and a token, my free account can't add a team and members to that team of the org.
here are my commands and responses:
```bash
# up login, etc.
........
❯ up robot create github
........

❯ up robot list
NAME     ID                                     DESCRIPTION   CREATED
github   11111111-1111-1111-1111-111111111111                 51m

❯ up robot token create --output=./github.token.json github github-token
.........

❯ cat ./github.token.json
......

❯ up team list
No teams found in chelala

❯ up team create team0
up: error: cannot build request: : {"error":"you have reached your maximum number of teams"}
```

On the other hand your clarification about `docker login` gave me the idea to just substitute the `docker login` step with a `crossplane xpkg login` using the original **PAT** not a robot token. If I understand, is not the recommended way but the account limitation prevents teams in orgs so no robots for now.

I removed
```yaml
      - name: Login to Upbound
        uses: docker/login-action@v3
        if: env.XPKG_ACCESS_ID != ''
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.XPKG_ACCESS_ID }}
          password: ${{ secrets.XPKG_TOKEN }}
```

and added in that place

```yaml
      - name: Crossplane XPKG Login
        if: env.XPKG_ACCESS_ID != ''
        run: "./crossplane xpkg login --account ${{ secrets.XPKG_ACCESS_ID }} --token ${{ secrets.XPKG_TOKEN }}"
```

It's all working ok in the repo workflow.
Thanks a lot for the quick and precise assistance.
