### DISCUSSION TITLE
How do I reference a resource in Azure

### DISCUSSION THREAD

**Discussion by artisticcheese** [crossplane/crossplane#6184] [Q&A]
Hello,

Learning crossplane in Azure and trying to understand how do you properly reference existing resources in Azure (only for reference point). Found how to do with with ResourceGroup but having trouble for child resources (example below is CDN profile). I added annotation but confused where exactly I put resource group in this case since CDN profile is child of resource group.  Code below does not work and fails with error below

```
`Message:               observe failed: failed to observe the resource: [{0 making Read request on Azure CDN Profile "crossplane-frontdoor" (Resource Group "<no value>"): cdn.ProfilesClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '11d3dc18-6d18-974a-53337a94418d' with object id '11d3dc18-4f98-974a-53337a94418d' does not have authorization to perform action 'Microsoft.Cdn/profiles/read' over scope '/subscriptions/11b16e25-0e5f--5f2e9adb26df/resourceGroups/<no value>/providers/Microsoft.Cdn/profiles/crossplane-frontdoor' or the scope is invalid. If access was recently granted, please refresh your credentials."  []}`
```

Crossplane

```
apiVersion: cdn.azure.upbound.io/v1beta1
kind: Profile
metadata:
  name: frontdoor-reference
  annotations:
    crossplane.io/external-name: crossplane-frontdoor
spec:
  managementPolicies: ["Observe"]
  forProvider:
    resourceGroupName: aso-greg-test-rg
  providerConfigRef:
    name: workload-identity-provider-config
 ```
