### DISCUSSION TITLE
Can not create FrontDoorRoute resource type

### DISCUSSION THREAD

**Discussion by artisticcheese** [crossplane/crossplane#6185] [Q&A]
Hello,

Trying to create resource below and getting error `Message:               observe failed: failed to observe the resource: [{0 parsing "<no value>/routes/product1-route" as an FrontDoorRoute ID: parsing Azure ID: parse "<no value>/routes/product1-route": invalid URI for request  []}]` which seems to be indicating that somewhere resourceID of CDN profile is not being referenced properly but can not figure out how to pass it since this resource does not expose it.

```
piVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorRoute
metadata:
  name: product1-route
spec:
  providerConfigRef:
    name: workload-identity-provider-config
  forProvider:
    cdnFrontdoorEndpointIdRef:
      name: product1-endpoint
    cdnFrontdoorOriginGroupIdRef:
      name: product1-origingroup
    cdnFrontdoorOriginIdsRefs:
      - name: product1-origin1
    cdnFrontdoorCustomDomainIdsRefs:
      - name: product1-customdomain1
    cdnFrontdoorRuleSetIdsRefs:
      - name: product1ruleset
    enabled: true
    forwardingProtocol: HttpsOnly
    httpsRedirectEnabled: true
    linkToDefaultDomain: false
    patternsToMatch:
      - /*
    supportedProtocols:
      - Http
      - Https
```
