### DISCUSSION TITLE
Required value: the fromFieldPath does not have a type compatible with the toFieldPath according to their schemas and no transforms were provided: string != array

### DISCUSSION THREAD

**Discussion by ValeriiVasianovych** [crossplane/crossplane#6292] [Q&A] [answered]
Hello, I would like to ask for help from those who have encountered this issue before. I created a SecurityGroup and want to attach it to an RDS instance, but the problem is that `vpcSecurityGroupIds` works with arrays, and I am passing the `securityGroupId` as a string, which results in the following error:

```
[ec2-user@ip-****** resources]$ k apply -f rds/
Warning: Composition "rdsc" invalid for schema-aware validation: spec.resources[4].patches[16].transforms: Required value: the fromFieldPath does not have a type compatible with the toFieldPath according to their schemas and no transforms were provided: string != array
```

[[Link to unbound RDS Docs](https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.37.1/resources/database.aws.crossplane.io/RDSInstance/v1beta1)](https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.37.1/resources/database.aws.crossplane.io/RDSInstance/v1beta1)

I would greatly appreciate any help you can offer.

---
 
composition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rdsc
  labels:
    crossplane.io/xrd: xrdscs.saas.example.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: saas.example.com/v1alpha1
    kind: XRDSC
  patchSets:
    - name: common-tags
      patches:
        - fromFieldPath: "spec.parameters.ownerName"
          toFieldPath: "spec.forProvider.tags.ownerName"
        - fromFieldPath: "spec.parameters.projectId"
          toFieldPath: "spec.forProvider.tags.projectId"
        - fromFieldPath: "spec.parameters.env"
          toFieldPath: "spec.forProvider.tags.env"
  resources:    
    - name: security-group
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        metadata:
          labels:
            type: security-group
        spec:
          forProvider:
            region: <PATCHED>
            vpcId: <PATCHED>
            tags:
              Name: <PATCHED>
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.vpcId"
          toFieldPath: "spec.forProvider.vpcId"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.securityGroupName"
          toFieldPath: "spec.forProvider.tags.Name"
        - type: ToCompositeFieldPath
          fromFieldPath: "status.atProvider.id"   <= Add value of security group generated id to status 
          toFieldPath: "status.securityGroupId"  <= Save id in CRD statuses
```
...

```yaml
    - name: rds-instance
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        metadata:
          name: <PATCHED>
        spec:
          forProvider:
            name: <PATCHED>
            dbName: <PATCHED>
            region: <PATCHED>
            instanceClass: <PATCHED>
            username: <PATCHED>
            engine: <PATCHED>
            allocatedStorage: <PATCHED>
            engineVersion: <PATCHED> 
            skipFinalSnapshot: <PATCHED>
            publiclyAccessible: <PATCHED>
            autoGeneratePassword: <PATCHED>
            vpcSecurityGroupIds: [PATCHED]
            passwordSecretRef:
              namespace: crossplane-system
              key: password
            writeConnectionSecretToRef:
              namespace: crossplane-system
            tags:
              Name: "sf-dev-vv-mariadb-crossplane"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-mariadb"
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "spec.forProvider.passwordSecretRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-input"
        - type: PatchSet
          patchSetName: common-tags
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.dbName"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.size"
          toFieldPath: "spec.forProvider.instanceClass"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.username"
          toFieldPath: "spec.forProvider.username"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.engine"
          toFieldPath: "spec.forProvider.engine"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.storageCapacity"
          toFieldPath: "spec.forProvider.allocatedStorage"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.engineVersion"
          toFieldPath: "spec.forProvider.engineVersion"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.skipFinalSnapshot"
          toFieldPath: "spec.forProvider.skipFinalSnapshot"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.publiclyAccessible"
          toFieldPath: "spec.forProvider.publiclyAccessible"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.autoGeneratePassword"
          toFieldPath: "spec.forProvider.autoGeneratePassword"
        - type: FromCompositeFieldPath
          fromFieldPath: "status.subnetGroupName"
          toFieldPath: "spec.forProvider.dbSubnetGroupName"
          policy:
            fromFieldPath: Required
        - type: FromCompositeFieldPath
          fromFieldPath: "status.securityGroupId"      <= Get name from CRD status 
          toFieldPath: "spec.forProvider.vpcSecurityGroupIds" <= Add-rewrite id to vpcSecurityGroupIds
          policy:
            fromFieldPath: Required 
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.writeConnectionSecretsToNamespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
```

definition.yaml
```yaml
[ec2-user@ip-10-176-20-148 resources]$ cat rds/definition.yaml 
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdscs.saas.example.com
spec:
  defaultCompositeDeletePolicy: Foreground
  defaultCompositionUpdatePolicy: Manual
  defaultCompositionRef:
    name: rdsc
  group: saas.example.com
  names:
    kind: XRDSC
    plural: xrdscs
  claimNames:
    kind: XRDS
    plural: rdses
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                    region:
                      type: string
                    size:
                      type: string
                    username:
                      type: string
                    engine:
                      type: string
                    storageCapacity:
                      type: integer
                    engineVersion:
                      type: string
                    skipFinalSnapshot:
                      type: boolean
                    publiclyAccessible:
                      type: boolean
                    autoGeneratePassword:
                      type: boolean
                    ownerName:
                      type: string
                    projectId:
                      type: string
                    env:
                      type: string
                    writeConnectionSecretsToNamespace:
                      type: string
                    securityGroupName:
                      type: string
                    vpcId:
                      type: string
                    vpcPrivateSubnets:
                      type: array
                      items:
                        type: string
              required:
                - parameters
            status:
              type: object
              properties:
                address:
                  type: string
                port:
                  type: integer
                password:
                  type: string
                subnetGroupName:
                  type: string
                securityGroupId:  <= This value of ID Security Group
                  type: string
```

**Comment by bobh66** [comment, marked as answer]
```
- type: FromCompositeFieldPath
  fromFieldPath: "status.securityGroupId"
  toFieldPath: spec.forProvider.vpcSecurityGroupIds[0]
  policy:
    fromFieldPath: Required 
```
