### DISCUSSION TITLE
pipeline step "patch-and-transform" returned a fatal result

### DISCUSSION THREAD

**Discussion by dotunolafunmiloye** [crossplane/crossplane#6293] [Q&A]
While trying to convert our pre v1.18 compositions to make then compatible,  running into this error:

 Warning  ComposeResources      32s (x5 over 4m40s)   defined/compositeresourcedefinition.apiextensions.crossplane.io cannot compose resources: pipeline step "patch-and-transform" returned a fatal result: cannot get Function input: cannot get function input *v1beta1.Resources from *v1.RunFunctionRequest: cannot unmarshal JSON from *structpb.Struct into *v1beta1.Resources: json: unable to unmarshal Go value of type v1beta1.Environment: unknown name "resources"                │

Here is a snippet of the Composition.

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: composition
spec:
  compositeTypeRef:
    apiVersion: example/v1beta1 
    kind: XInstance
  mode: Pipeline
  pipeline:
  - step: environmentConfigs
    functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - type: Reference
          ref:
            name: aws-env-config
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      environment:
        patches:
        - type: ToEnvironmentFieldPath
          fromFieldPath: spec.forProvider.domainName
          toFieldPath: domainName                
        - type: ToEnvironmentFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: namespace                 
        - type: FromEnvironmentFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

```

I have compared the new composition format to examples below and some more: 

https://docs.crossplane.io/latest/concepts/environment-configs/ and https://github.com/crossplane/crossplane/discussions/5436#discussioncomment-8634471

The function schema were also compared to 

https://marketplace.upbound.io/functions/upbound/function-patch-and-transform/v0.8.1/resources/pt.fn.crossplane.io/Resources/v1beta1

 and 

https://marketplace.upbound.io/functions/crossplane-contrib/function-environment-configs/v0.2.0/resources/environmentconfigs.fn.crossplane.io/Input/v1beta1

I can seem to figure out the root cause of the fatal error. Appreciate all guidance, pointers  and assistance.

Regards,
Dot
