### DISCUSSION TITLE
How to add external name to Amazon RDS?

### DISCUSSION THREAD

**Discussion by ValeriiVasianovych** [crossplane/crossplane#6294] [Q&A]
I’m passing the parameters name and dbName, but the database gets created with a random name, for example: terraform-20250221204234476600000002.

[Link to unbound RDS Docs](https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.37.1/resources/database.aws.crossplane.io/RDSInstance/v1beta1)](https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.37.1/resources/database.aws.crossplane.io/RDSInstance/v1beta1)

I would greatly appreciate any help you can offer.

composition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rdsc
  labels:
    crossplane.io/xrd: xrdscs.saas.crossplane.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: saas.crossplane.com/v1alpha1
    kind: XRDSC
  patchSets:
    - name: common-tags
      patches:
        - fromFieldPath: "spec.parameters.ownerName"
          toFieldPath: "spec.forProvider.tags.ownerName"
        - fromFieldPath: "spec.parameters.projectId"
          toFieldPath: "spec.forProvider.tags.projectId"
        - fromFieldPath: "spec.parameters.env"
          toFieldPath: "spec.forProvider.tags.env"

  resources:
    ...
    - name: rds-instance
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        metadata:
          name: <PATCHED>
          labels:
            crossplane.io/external-name: "sf-dev-vv-mariadb-crossplane" <= it is not working
        spec:
          forProvider:
            name: <PATCHED>                 <= This parameter should be patched
            dbName: <PATCHED>            <= This parameter should be patched
            region: <PATCHED>
            instanceClass: <PATCHED>
            username: <PATCHED>
            engine: <PATCHED>
            allocatedStorage: <PATCHED>
            engineVersion: <PATCHED> 
            skipFinalSnapshot: <PATCHED>
            publiclyAccessible: <PATCHED>
            autoGeneratePassword: <PATCHED>
            vpcSecurityGroupIds: [PATCHED]
            passwordSecretRef:
              namespace: crossplane-system
              key: password
            writeConnectionSecretToRef:
              namespace: crossplane-system
            tags:
              Name: "sf-dev-vv-mariadb-crossplane"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-mariadb"
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "spec.forProvider.passwordSecretRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-input"
        - type: PatchSet
          patchSetName: common-tags
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.name"       <= name: is not working
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"            
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.dbName"   <= dbName: is not working
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.size"
          toFieldPath: "spec.forProvider.instanceClass"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.username"
          toFieldPath: "spec.forProvider.username"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.engine"
          toFieldPath: "spec.forProvider.engine"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.storageCapacity"
          toFieldPath: "spec.forProvider.allocatedStorage"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.engineVersion"
          toFieldPath: "spec.forProvider.engineVersion"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.skipFinalSnapshot"
          toFieldPath: "spec.forProvider.skipFinalSnapshot"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.publiclyAccessible"
          toFieldPath: "spec.forProvider.publiclyAccessible"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.autoGeneratePassword"
          toFieldPath: "spec.forProvider.autoGeneratePassword"
        - type: FromCompositeFieldPath
          fromFieldPath: "status.subnetGroupName"
          toFieldPath: "spec.forProvider.dbSubnetGroupName"
          policy:
            fromFieldPath: Required
        - type: FromCompositeFieldPath
          fromFieldPath: "status.securityGroupId" 
          toFieldPath: "spec.forProvider.vpcSecurityGroupIds[0]"
          policy:
            fromFieldPath: Required 
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.writeConnectionSecretsToNamespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
      connectionDetails:
        - fromFieldPath: "status.atProvider.address"
          name: host
        - fromFieldPath: "status.atProvider.endpoint"
          name: endpoint
        - fromFieldPath: "spec.forProvider.username"
          name: username
        - fromConnectionSecretKey: "attribute.password"
          name: password
```

definition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdscs.saas.crossplane.com
spec:
  defaultCompositeDeletePolicy: Foreground
  defaultCompositionUpdatePolicy: Manual
  defaultCompositionRef:
    name: rdsc
  group: saas.crossplane.com
  names:
    kind: XRDSC
    plural: xrdscs
  claimNames:
    kind: XRDS
    plural: rdses
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                    region:
                      type: string
                    size:
                      type: string
                    username:
                      type: string
                    engine:
                      type: string
                    storageCapacity:
                      type: integer
                    engineVersion:
                      type: string
                    skipFinalSnapshot:
                      type: boolean
                    publiclyAccessible:
                      type: boolean
                    autoGeneratePassword:
                      type: boolean
                    ownerName:
                      type: string
                    projectId:
                      type: string
                    env:
                      type: string
                    writeConnectionSecretsToNamespace:
                      type: string
                    securityGroupName:
                      type: string
                    vpcId:
                      type: string
                    vpcPrivateSubnets:
                      type: array
                      items:
                        type: string
              required:
                - parameters
            status:
              type: object
              properties:
                address:
                  type: string
                port:
                  type: integer
                password:
                  type: string
                subnetGroupName:
                  type: string
                securityGroupId:
                  type: string
```

claim.yaml
```yaml
apiVersion: saas.crossplane.com/v1alpha1
kind: XRDS
metadata:
  name: rds-instance
  namespace: crossplane-system
  labels:
    crossplane.io/external-name: "sf-dev-vv-mariadb-crossplane"
spec:
  parameters:
    name: "sf-dev-vv-mariadb-crossplane"
    region: "eu-central-1"
    size: "db.t3.micro"
    username: "sfdbadmin"
    engine: "mariadb"
    storageCapacity: 30
    engineVersion: "10.6.14"
    skipFinalSnapshot: true
    publiclyAccessible: false
    autoGeneratePassword: true
    securityGroupName: "sf-dev-mariadb-sg"      
    ownerName: "SaaS-Team"
    projectId: "EKS Crossplane Project"
    env: "Development"
    writeConnectionSecretsToNamespace: "crossplane-system"
    vpcId: "vpc-09bdaf208556d****"
    vpcPrivateSubnets:
      - "subnet-0861a68d1e356*****"
      - "subnet-0fe37ed054b54*****"
```
