### DISCUSSION TITLE
composition limits metadata.name to 63 chars

### DISCUSSION THREAD

**Discussion by tehlers320** [crossplane/crossplane#6301] [General]
Im currently on v1.14.5 and trying to move to compositions my Xcompostion for some reason generates

```
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                type: string
            type: object
```

but i believe the k8s limit for a name is 253 chars. Does anybody know whats doing this or what the reason behind it is? 

labels are restricted to 63 chars. This is the metadata.name
