### DISCUSSION TITLE
spec.resourceRefs[5].namespace: field not declared in schema

### DISCUSSION THREAD

**Discussion by jingliming** [crossplane/crossplane#6491] [Q&A] [answered]
I got an error when I tried to define custom xrd and composition
```
Name:         iac-demo
Namespace:    
Labels:       crossplane.io/composite=iac-demo
              testing.upbound.io/example-name=iac-demo
Annotations:  <none>
API Version:  core.bizworks.dev/v1alpha1
Kind:         XIacDemo
Metadata:
  Creation Timestamp:  2025-05-28T07:22:58Z
  Finalizers:
    composite.apiextensions.crossplane.io
  Generation:        3
  Resource Version:  3666255
  UID:               77410e16-af27-4a4b-9237-ab6bb3354b4c
Spec:
  Composition Ref:
    Name:  iac-demo-composition
  Composition Revision Ref:
    Name:                     iac-demo-composition-40cfff3
  Composition Update Policy:  Automatic
  Rds:
    Account:   mingyuantemp
    Password:  Testmingyuan123
    Version:   8.0
  Vpc Id:      vpc-bp1hridgk1lq8pcysjh5c
  Vswitch Id:  vsw-bp1iv05wjj23lqb865xiw
Status:
  Conditions:
    Last Transition Time:  2025-05-28T07:22:58Z
    Message:               cannot compose resources: cannot update composite resource spec.resourceRefs: failed to create typed patch object (/iac-demo; core.bizworks.dev/v1alpha1, Kind=XIacDemo): .spec.resourceRefs[5].namespace: field not declared in schema
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason             Age                From                                                             Message
  ----     ------             ----               ----                                                             -------
  Normal   SelectComposition  23s                defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully selected composition: iac-demo-composition
  Normal   SelectComposition  23s                defined/compositeresourcedefinition.apiextensions.crossplane.io  Selected composition revision: iac-demo-composition-40cfff3
  Warning  ComposeResources   14s (x5 over 23s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot compose resources: cannot update composite resource spec.resourceRefs: failed to create typed patch object (/iac-demo; core.bizworks.dev/v1alpha1, Kind=XIacDemo): .spec.resourceRefs[5].namespace: field not declared in schema
```
How to fix it?  My configurations:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiacdemos.core.bizworks.dev
spec:
  group: core.bizworks.dev
  names:
    kind: XIacDemo
    plural: xiacdemos
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vpcId:
                  type: string
                vswitchId:
                  type: string
                kafka:
                  type: object
                  properties:
                    name:
                      type: string
                    topic:
                      type: string
                    consumerGroup:
                      type: string
                  required:
                    - topic
                    - consumerGroup
                redis:
                  type: object
                  properties:
                    account:
                      type: string
                    password:
                      type: string
                  required:
                    - account
                    - password
                rds:
                  type: object
                  properties:
                    account:
                      type: string
                    password:
                      type: string
                    version:
                      type: string
                  required:
                    - account
                    - password
                    - version
            status:
              type: object
              properties:
                vpcId:
                  type: string
                vswitchId:
                  type: string
                securityGroupId:
                  type: string
                rdsConnectionString:
                  type: string
                rdsId:
                  type: string
---

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: iac-demo-composition
spec:
  compositeTypeRef:
    apiVersion: core.bizworks.dev/v1alpha1
    kind: XIacDemo
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: iac-demo-secret
            base:
              apiVersion: v1
              data:
                rds-password: ""
                redis-password: ""
              kind: Secret
              metadata:
                name: middleware-password
                namespace: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.rds.account
                toFieldPath: spec.data.rds-account
              - type: FromCompositeFieldPath
                fromFieldPath: spec.rds.password
                toFieldPath: spec.data.rds-password
              - type: FromCompositeFieldPath
                fromFieldPath: status.rdsConnectionString
                toFieldPath: spec.data.rds-connectionString
          - name: aliCloud-rds-instance
            base:
              apiVersion: rds.alicloud.crossplane.io/v1alpha1
              kind: Instance
              metadata:
                labels:
                  testing.upbound.io/example-name: iac-demo
                name: iac-demo-rds-instance
              spec:
                forProvider:
                  engine: MySQL
                  engineVersion: "5.7"
                  instanceName: iac-demo-instance
                  instanceStorage: 20
                  instanceType: mysql.n2.medium.1
                  optimizedWrites: none
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.rds.version
                toFieldPath: spec.forProvider.engineVersion
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vswitchId
                toFieldPath: spec.forProvider.vswitchId
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.rdsId
          - name: aliCloud-rds-connection
            base:
              apiVersion: rds.alicloud.crossplane.io/v1alpha1
              kind: Connection
              metadata:
                name: iac-demo-rds-connection
              spec:
                forProvider:
                  connectionPrefix: iacdemo
                  instanceIdSelector:
                    matchLabels:
                      testing.upbound.io/example-name: iac-demo
            patches:
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.connectionString
                toFieldPath: status.rdsConnectionString
          - name: aliCloud-rds-account
            base:
              apiVersion: rds.alicloud.crossplane.io/v1alpha1
              kind: Account
              metadata:
                labels:
                  testing.upbound.io/example-name: iac-demo
                name: iac-demo-rds-account
              spec:
                forProvider:
                  accountName: mingyuan
                  accountPasswordSecretRef:
                    key: rds-password
                    name: iac-demo-secret
                    namespace: default
                  dbInstanceIdSelector:
                    matchLabels:
                      testing.upbound.io/example-name: iac-demo
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.rds.account
                toFieldPath: spec.forProvider.accountName
          - name: aliCloud-securityGroup
            base:
              apiVersion: ecs.alicloud.crossplane.io/v1alpha1
              kind: SecurityGroup
              spec:
                forProvider:
                  securityGroupName: iac-demo
            patches:
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.securityGroupId
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vpcId
                toFieldPath: spec.forProvider.vpcId
          - name: aliCloud-securityGroupRule
            base:
              apiVersion: ecs.alicloud.crossplane.io/v1alpha1
              kind: SecurityGroupRule
              spec:
                forProvider:
                  cidrIp: 0.0.0.0/0
                  ipProtocol: tcp
                  nicType: intranet
                  policy: accept
                  portRange: 80/80
                  priority: 1
                  type: ingress
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: status.securityGroupId
                toFieldPath: spec.forProvider.securityGroupId
#    - step: ready
#      functionRef:
#        name: function-auto-ready

---

apiVersion: core.bizworks.dev/v1alpha1
kind: XIacDemo
metadata:
  name: iac-demo
  labels:
    testing.upbound.io/example-name: iac-demo
spec:
  vpcId: vpc-bp1hridgk1lq8pcysjh5c
  vswitchId: vsw-bp1iv05wjj23lqb865xiw
  rds:
    account: mingyuantemp
    password: Testmingyuan123
    version: "8.0"
---
```

crossplane: v1.19
kubernetes:v1.30.7+orb1

**Comment by jbw976** [comment]
In Crossplane v1.x, managed resources are cluster scoped. Starting with the [v2 preview](https://github.com/crossplane/crossplane/releases/tag/v2.0.0-preview.1), you can start composing [namespaced resources](https://docs.crossplane.io/v2.0-preview/whats-new/#namespaced-managed-resources).

Perhaps if you remove the namespace from `aliCloud-rds-account`, this could work with v1.x?

**Reply by jingliming** [reply]
Perhaps if you remove the namespace from aliCloud-rds-account, this could work with v1.x?
---------------------------
How to remove it?

**Reply by jbw976** [reply]
edit the composition to remove the line that is setting namespace, then apply that to the control plane should do it 😄

**Reply by jingliming** [reply, marked as answer]
@jbw976 I solved the problem by introducing the kubernetes provider instead of directly using kubernetes resources.😊
```
......
          - name: iac-demo-secret
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              metadata:
                name: middleware-password
                annotations:
                  uptest.upbound.io/timeout: "60"
              spec:
                # Watch for changes to the Namespace object.
                # Watching resources is an alpha feature and needs to be enabled with --enable-watches
                # in the provider to get this configuration working.
                # watch: true
                forProvider:
                  manifest:
                    apiVersion: v1
                    data:
                      rds-password: ""
                      redis-password: ""
                    kind: Secret
                    metadata:
                      namespace: default
                providerConfigRef:
                  name: kubernetes-provider
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.rds.account
                toFieldPath: spec.forProvider.manifest.data.rds-account
                transforms:
                  - type: string
                    string:
                      type: Convert
                      convert: "ToBase64"
              - type: FromCompositeFieldPath
                fromFieldPath: spec.rds.password
                toFieldPath: spec.forProvider.manifest.data.rds-password
                transforms:
                  - type: string
                    string:
                      type: Convert
                      convert: "ToBase64"
              - type: FromCompositeFieldPath
                fromFieldPath: status.rdsConnectionString
                toFieldPath: spec.forProvider.manifest.data.rds-connectionString
                transforms:
                  - type: string
                    string:
                      type: Convert
                      convert: "ToBase64"
.......
```
