### DISCUSSION TITLE
Unable to create claim

### DISCUSSION THREAD

**Discussion by cmacsithigh** [crossplane/crossplane#6497] [General]
Hi there,

I am getting this error when trying to create a claim
```
Warning  BindCompositeResource  2s (x3 over 5s)  offered/compositeresourcedefinition.apiextensions.crossplane.io  cannot add finalizer to claim: cannot update object: the server could not find the requested resource (put managedserviceaccounts.crossplane.example.com lemon-claim)
```

This  is my `CompositeResourceDefinition`
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmanagedserviceaccounts.crossplane.example.com
  namespace: crossplane-system
spec:
  group: crossplane.example.com
  names:
    kind: XManagedServiceAccount
    plural: xmanagedserviceaccounts
    singular: xmanagedserviceaccount
  claimNames:
    kind: ManagedServiceAccount
    plural: managedserviceaccounts
    singular: managedserviceaccount
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            # This is only what the end will use will care about and be required to add
            spec:
              properties:
                name:
                  type: string
                readerAccessToCurrentSubscription:
                  type: boolean
                  default: false
                keyVaults:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      resourceGroup:
                        type: string
                storageAccounts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      resourceGroup:
                        type: string
                tags:
                  type: object
                  additionalProperties:
                    type: string
                  required:
                    - owner
              required:
                - name
            # This is for sharing data across resources in the composition
            status:
              type: object
              properties:
                clientId:
                  type: string
                principalId:
                  type: string
                config:
                  type: object
                  properties:
                    countryCode:
                      type: string
                    environment:
                      type: string
                    location:
                      type: string
                    oidcIssuerUrl:
                      type: string
                    shortEnvironment:
                      type: string
                    shortLocation:
                      type: string
                    subscriptionId:
                      type: string
```

This is my Composition
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-managed-service-account
  namespace: crossplane-system
  labels:
    crossplane.io/xrd: xmanagedserviceaccounts.crossplane.example.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: crossplane.example.com/v1
    kind: XManagedServiceAccount
  mode: Pipeline
  pipeline:
    - step: environment-config
      functionRef:
        name: function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: environment-config

    - step: config-setup
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        environment:
          patches:
            - type: ToCompositeFieldPath
              fromFieldPath: countryCode
              toFieldPath: status.config.countryCode
            - type: ToCompositeFieldPath
              fromFieldPath: environment
              toFieldPath: status.config.environment
            - type: ToCompositeFieldPath
              fromFieldPath: location
              toFieldPath: status.config.location
            - type: ToCompositeFieldPath
              fromFieldPath: oidcIssuerUrl
              toFieldPath: status.config.oidcIssuerUrl
            - type: ToCompositeFieldPath
              fromFieldPath: shortLocation
              toFieldPath: status.config.shortLocation
            - type: ToCompositeFieldPath
              fromFieldPath: shortEnvironment
              toFieldPath: status.config.shortEnvironment
            - type: ToCompositeFieldPath
              fromFieldPath: subscriptionId
              toFieldPath: status.config.subscriptionId
        resources: []

    - step: create-managed-identity
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: managed-identity
            base:
              apiVersion: managedidentity.azure.upbound.io/v1beta1
              kind: UserAssignedIdentity
              spec:
                providerConfigRef:
                  name: azure-provider-config
                forProvider:
                  tags:
                    managed_by: crossplane
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: status.config.subscriptionId
                    # resource group
                    - fromFieldPath: status.config.shortLocation
                    - fromFieldPath: status.config.countryCode
                    - fromFieldPath: status.config.shortEnvironment
                    # managed identity name
                    - fromFieldPath: status.config.shortLocation
                    - fromFieldPath: status.config.countryCode
                    - fromFieldPath: status.config.shortEnvironment
                    - fromFieldPath: spec.name
                  strategy: string
                  string:
                    fmt: "/subscriptions/%s/resourceGroups/%s-%s-%s-core-aks-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/%s-%s-%s-%s-aks-mid"
                toFieldPath: "metadata.annotations['crossplane.io/external-name']"
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: status.config.shortLocation
                    - fromFieldPath: status.config.countryCode
                    - fromFieldPath: status.config.shortEnvironment
                    - fromFieldPath: spec.name
                  strategy: string
                  string:
                    fmt: "%s-%s-%s-%s-aks-mid"
                toFieldPath: metadata.name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: status.config.shortLocation
                    - fromFieldPath: status.config.countryCode
                    - fromFieldPath: status.config.shortEnvironment
                    - fromFieldPath: spec.name
                  strategy: string
                  string:
                    fmt: "%s-%s-%s-%s-aks-mid"
                toFieldPath: spec.forProvider.name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: status.config.shortLocation
                    - fromFieldPath: status.config.countryCode
                    - fromFieldPath: status.config.shortEnvironment
                  strategy: string
                  string:
                    fmt: "%s-%s-%s-core-aks-rg"
                toFieldPath: spec.forProvider.resourceGroupName
              - type: FromCompositeFieldPath
                fromFieldPath: status.config.location
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: status.config.environment
                toFieldPath: spec.forProvider.tags.environment
              - type: FromCompositeFieldPath
                fromFieldPath: status.config.location
                toFieldPath: spec.forProvider.tags.location
              - type: FromCompositeFieldPath
                fromFieldPath: status.config.countryCode
                toFieldPath: spec.forProvider.tags.countryCode
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tags
                toFieldPath: spec.forProvider.tags
                policy:
                  toFieldPath: MergeObjects

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.clientId
                toFieldPath: status.clientId
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.principalId
                toFieldPath: status.principalId

    - step: create-federated-credentials
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $name := $.observed.composite.resource.spec.name }}
            {{ $namespace := $.observed.composite.resource.spec.namespace }}
            {{ $countryCode := $.desired.composite.resource.status.config.countryCode }}
            {{ $oidcIssuerUrl := $.desired.composite.resource.status.config.oidcIssuerUrl }}
            {{ $shortEnvironment := $.desired.composite.resource.status.config.shortEnvironment }}
            {{ $shortLocation := $.desired.composite.resource.status.config.shortLocation }}

            apiVersion: managedidentity.azure.upbound.io/v1beta1
            kind: FederatedIdentityCredential
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: FederatedIdentityCredential--{{ $namespace }}-{{ $name }}
              name: {{ $shortLocation }}-{{ $countryCode }}-{{ $shortEnvironment }}-{{ $name }}-aks-fc
            spec:
              forProvider:
                issuer: {{ $oidcIssuerUrl }}
                resourceGroupName: {{ $shortLocation }}-{{ $countryCode }}-{{ $shortEnvironment }}-core-aks-rg
                subject: "system:serviceaccount:{{ $namespace }}:{{ $name }}"
                parentIdRef:
                  name: {{ $shortLocation }}-{{ $countryCode }}-{{ $shortEnvironment }}-{{ $name }}-aks-mid
                audience:
                  - api://AzureADTokenExchange
              providerConfigRef:
                name: azure-provider-config

    - step: create-service-account
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $clientId := $.desired.composite.resource.status.clientId }}
            {{ $name := $.observed.composite.resource.spec.name }}
            {{ $namespace := $.observed.composite.resource.spec.namespace }}

            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Service-Account--{{ $namespace }}-{{ $name }}
              name: {{ $name }}
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: ServiceAccount
                  metadata:
                    name: {{ $name }}
                    namespace: {{ $namespace }}
                    annotations:
                      azure.workload.identity/client-id: {{ $clientId }}
                    labels:
                      azure.workload.identity/use: "true"
              providerConfigRef:
                name: provider-kubernetes

    - step: role-assignments
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $principalId := $.desired.composite.resource.status.principalId }}
            {{ $name := $.observed.composite.resource.spec.name }}
            {{ $namespace := $.observed.composite.resource.spec.namespace }}
            {{ $readerAccessToCurrentSubscription := $.observed.composite.resource.spec.readerAccessToCurrentSubscription }}
            {{ $countryCode := $.desired.composite.resource.status.config.countryCode }}
            {{ $shortEnvironment := $.desired.composite.resource.status.config.shortEnvironment }}
            {{ $shortLocation := $.desired.composite.resource.status.config.shortLocation }}
            {{ $subscriptionId := $.desired.composite.resource.status.config.subscriptionId }}

            {{- range $keyVault := $.observed.composite.resource.spec.keyVaults }}

            {{- if and $keyVault.subscriptionId (ne $keyVault.subscriptionId "") }}
              {{ $subscriptionId := $keyVault.subscriptionId }}
            {{ end }}

            {{- if and $namespace (ne $namespace "") }}
              {{ $namespace := $namespace }}
            {{ else }}
              {{ $namespace := $name }}
            {{ end }}

            {{ $expectedDatabaseKeyVault := printf "%s-%s-%s-database-kv" $shortLocation $countryCode $shortEnvironment }}
            {{ $expectedClearBankKeyVault := printf "%s-%s-%s-clearbank-kv" $shortLocation $countryCode $shortEnvironment }}

            {{ if or (eq $keyVault.name $expectedDatabaseKeyVault) (eq $keyVault.name $expectedClearBankKeyVault) }}
            ---
            apiVersion: authorization.azure.upbound.io/v1beta1
            kind: RoleAssignment
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: RoleAssignmentKeyVaultKeys--{{ $keyVault.name }}--{{ $namespace }}-{{ $name }}
              name: keyvault--keys--{{ $keyVault.name }}--{{ $name }}
            spec:
              providerConfigRef:
                name: azure-provider-config
              forProvider:
                scope: /subscriptions/{{ $subscriptionId }}/resourceGroups/{{ $keyVault.resourceGroup }}/providers/Microsoft.KeyVault/vaults/{{ $keyVault.name }}
                roleDefinitionName: "Key Vault Crypto Officer"
                principalId: {{ $principalId }}
            ---
            apiVersion: authorization.azure.upbound.io/v1beta1
            kind: RoleAssignment
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: RoleAssignmentKeyVaultSecrets--{{ $keyVault.name }}--{{ $namespace }}-{{ $name }}
              name: keyvault--secrets--{{ $keyVault.name }}--{{ $name }}
            spec:
              providerConfigRef:
                name: azure-provider-config
              forProvider:
                scope: /subscriptions/{{ $subscriptionId }}/resourceGroups/{{ $keyVault.resourceGroup }}/providers/Microsoft.KeyVault/vaults/{{ $keyVault.name }}
                roleDefinitionName: "Key Vault Secrets Officer"
                principalId: {{ $principalId }}
            {{ else }}
            ---
            apiVersion: keyvault.azure.upbound.io/v1beta1
            kind: AccessPolicy
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: AccessPolicy--{{ $keyVault.name }}--{{ $namespace }}-{{ $name }}
              name: keyvault--secrets---{{ $keyVault.name }}--{{ $name }}
            spec:
              providerConfigRef:
                name: azure-provider-config
              forProvider:
                keyPermissions:
                  - Get
                  - List
                certificatePermissions:
                  - Get
                  - List
                secretPermissions:
                  - Get
                  - List
                keyVaultId: /subscriptions/{{ $subscriptionId }}/resourceGroups/{{ $keyVault.resourceGroup }}/providers/Microsoft.KeyVault/vaults/{{ $keyVault.name }}
                objectId: {{ $principalId }}
                tenantId: <company-GUID>
            {{ end }}
            {{ end }}

            {{- range $storageAccount := $.observed.composite.resource.spec.storageAccounts }}
            ---
            apiVersion: authorization.azure.upbound.io/v1beta1
            kind: RoleAssignment
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: RoleAssignmentStorageAccount--{{ $storageAccount.name }}--{{ $namespace }}-{{ $name }}
              name: storage-account--{{ $storageAccount.name }}--{{ $name }}
            spec:
              providerConfigRef:
                name: azure-provider-config
              forProvider:
                scope: /subscriptions/{{ $subscriptionId }}/resourceGroups/{{ $storageAccount.resourceGroup }}/providers/Microsoft.Storage/storageAccounts/{{ $storageAccount.name }}
                roleDefinitionName: "Storage Account Contributor"
                principalId: {{ $principalId }}
            {{ end }}

            {{if $readerAccessToCurrentSubscription}}
            ---
            apiVersion: authorization.azure.upbound.io/v1beta1
            kind: RoleAssignment
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: RoleAssignmentCurrentSubscription--{{ $namespace }}-{{ $name }}
              name: current-subscription-reader--{{ $name }}
            spec:
              providerConfigRef:
                name: azure-provider-config
              forProvider:
                scope: /subscriptions/{{ $subscriptionId }}
                roleDefinitionName: "Reader"
                principalId: {{ $principalId }}
            {{end}}


    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready

```

This is my `Claim`
```
apiVersion: crossplane.example.com/v1
kind: ManagedServiceAccount
metadata:
  name: lemon-claim
  namespace: lemon-test
spec:
  name: lemon
  tags:
    owner: platform

```

Is there anything I'm missing?
