### DISCUSSION TITLE
Connection secrets within compositions - Existing secret is not controlled by UID

### DISCUSSION THREAD

**Discussion by imperialhound** [crossplane/crossplane#6565] [Q&A]
I was wondering if someone could help me better understand what I am doing wrong with connection secret refs within compositions. 

I have written a composition function to provision a RDS Postgres database with supporting infrastructure. I have an example of the composite resource and composition below
```
apiVersion: database.example.com/v1alpha1
kind: XPostgresDB
metadata:
  name: example-pg
spec:
  name: example-pg
  postgresSettings:
    storageType: gp3
    version: 16
  writeConnectionSecretToRef:
    name: example-db-connection-details
    namespace: example-namespace
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresdb
spec:
  compositeTypeRef:
    apiVersion: database.example.com/v1alpha1
    kind: XPostgresDB
  mode: Pipeline
  pipeline:
  - step: create-postgres-infrastructure
    functionRef:
      name: function-xpostgresdb
  - step: auto-ready-composition
    functionRef:
      name: function-auto-ready
```

The function templates an [RDS instance](https://marketplace.upbound.io/providers/upbound/provider-aws-rds/v1.23.1/resources/rds.aws.upbound.io/Instance/v1beta3) that defines the `writeConnectionSecretToRef` field. However, the secret's `ownerReference` is both being claimed by the managed resource and the xpostgresdb composite resource. This is preventing the connection details from being written to the secret with the following error.

```
cannot publish connection details: cannot apply connection secret: existing secret is not controlled by UID "4fa87263-2222-46b3-3311-84485c763c42"                                                                                                                                                                                                                                                                                                                                      
```

I would imagine that the managed resource should be the owner of the secret and not the composite resource, but I am probably not understanding something correctly.
