### ISSUE TITLE
Package design does not explain PackageInstall "spec.crd" installs   

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1017]
### What problem are you facing?

Part of #434 

The Stacks design calls out an installation option where a CRD name would be provided and the appropriate Stack would be found in the registry specified by `source` using a query for `crd`.

https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-stacks.md#installation-flow

```yaml
spec:
  source: registry.crossplane.io
  crd: wordpressinstances.wordpress.samples.stacks.crossplane.io/v1alpha1
```

There are some design complexities to consider and resolve in the design document:
* Since Stacks can provide multiple CRDs, should the CRD query parameter be a list of CRDs necessary to fulfill the StackInstall request?
  ```yaml
  spec:
    source: registry.crossplane.io
    crds:
    - wordpressinstances.wordpress.samples.stacks.crossplane.io/v1alpha1
    - foo.wordpress.samples.stacks.crossplane.io/v1alpha1
  ```
* Could multiple crd query entries result in the multiple `Stack` objects being created? A single StackInstall could result in StackA and StackB being installed and deleted when the StackInstall is deleted.
  This would be inline with:
  > The SM performs dependency resolution that determines all packages/Stacks that are required by this Stack and all of its dependent Stacks
* What happens if StackInstallA and StackInstallB have a single crd query for different CRDs contained within the same Stack? Does the last installed Stack error in failure? Does a second copy of the Stack get installed in the same namespace (how does this interact with CRD versioning)
* What happens when StackInstallA queries for a CRD provided by StackXa but StackInstallB queries for a CRD provided by StackXb which is incompatible with StackXa?

### How can Crossplane help?

The design should be updated to:
* define how the crd query parameter is used including conflict resolution for the scenarios described above
* consider support for multiple crd queries and determine if these should be additive filters or if the StackInstall should be resolved by installing all necessary Stacks (this would be in the spirit of automatic dependency resolution).
