### ISSUE TITLE
Merge Package and PackageInstall

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1089]
### What problem are you facing?

Per the [Stacks design](https://github.com/crossplaneio/crossplane/blob/e658defcdd626319157697e4f1f64bec92f3f582/design/design-doc-stacks.md#installation-flow) Crossplane `Stack` kinds are created by creating a `StackInstall`. This: 

* Feels imperative; typically in Kubernetes you operate on a `Foo` by operating on the `Foo` declaratively, not by submitting a `FooOperation`.
* Creates some questions about ownership and relationships. Why are Stack CRDs owned by the `StackInstall`, and not the (installed) `Stack`?

I imagine we landed at this design because the `Stack` is actually the result of invoking a Docker container, which outputs the content the stack consists of. We need some object to submit in order to run said container, and thus we have a `StackInstall`.

### How could Crossplane help solve your problem?

The `Stack` kind  is "a record of an installed Stack". It has a `spec`, but it doesn't seem to really be a configuration specification in the typical Kubernetes sense. I don't believe a user could (or would want to?) edit the spec.

Perhaps `StackInstall` should be merged into `Stack`, with the "how do you install this thing" bits (`StackInstall`) being the `spec` and the "what has been installed?" bits being the `status`.

**Comment by negz** [comment]
> Stack CRD instances can also be created directly by a user without any knowledge of packages at all. They can directly create any CRDs that their Stack requires and then create a Stack CRD instance that describes their Stack, its custom controller, etc. The Stack Manager will see this new instance and take the steps necessary to ensure the custom controller is running in the cluster and the Stack’s functionality is available.

My suggestion would however go against this pattern in which a user could create a `Stack` purely as a record or container of other things they did (i.e. installed some CRDs and controller managers).

**Comment by displague** [comment]
I wanted to capture some ranty noodling from [Slack](https://crossplane.slack.com/archives/CKXQK4P27/p1576597025048900) before the retention loses [it](https://crossplane.slack.com/archives/CKXQK4P27/p1576534484016600).

Nic points out in this issue's description that it is already confusing that the `StackInstall` owns some of the resources while the `Stack` owns others (ownership here is defined by parent labels).  This is further complicated by the StackInstall design (not implementation) which calls for StackInstalls that create multiple Stacks and the option to have multiple StackInstalls that can be fulfilled using existing Stacks (in both conditions this is to fulfill dependencies).

The following pseudo-yaml snippet, merging `StackInstall` and `Stack` bodies, illustrates how a `Stack` could become a wrapper for packaged deployments, in much the way a `Pod` is a wrapper for containers.

```yaml
kind: Stack
metadata:
  namespace: all-stack-artifacts-go-here # except ClusterRoles and CRDs
  name: intent-to-have-nice-things
spec:
  dependsOn:
  - crd: "foo.group/v1"
  - crd: "yolo.group/v1"
  - crd: "bar.group/v2"
    source: "barhut.bar"
  - package: "coolstack"
    source: "myplace.my"
status:
  conditionedStatus:
    conditions:
    - type: DependenciesMet # Are there Conflicts or impossible intents?
      status: "True"
    - type: AllTheDeploymentsCreated # Synced
      status: "True"
  deployedStackResources:
  - name: foo-stack-DEADBEEF
    source: dockerhub.io
    fulfills: [{ crd: "foo.group/v1" }, { crd: "yolo.group/v1" }]
    deploymentRef: { name: "foo-stack-deployment-DEADBEEF" }
    serviceaccountRef: {'foo-sa-DEADBEEF'}
    providedCRDRefs: [ {name: "foo..."}, {name: "yolo..."} ] 
  - name: bar-stack-DEADBEEF
    source: barhut.bar
    fulfills: [{ crd: "bar.group/v2" }]
    deploymentRef: { name: "bar-stack-deployment-DEADBEEF" }
    serviceaccountRef: {name: 'bar-sa'}
    providedCRDRefs: [ {name: "bar..."}, {name: ...} ] 
  - name: coolstack-DEADBEEF
    source: myplace.my
    fulfills: [{package: "coolstack"}]
    deploymentRef: { name: "coolstack-deployment-DEADBEEF"}
    serviceaccountRef: {name: 'coolstack-sa-DEADBEEF'}
    providedCRDRefs: [ {name: "thing1.coolstack..."}, {name: "thing2.coolstack..."} ]     
```

* _I wonder if there is any value in tracking the SA, Deployment, and CRD refs from the Stack if they can just be resolved through labels._
  _For example, the Stack doesn't hang on to refs of the SA and Clusterroles currently.  If a Stack becomes self-healing (of SAs and Deployments) then it will have to look-up the resources anyway, so a label on the artifacts seems as useful as a reference in the stack._
* _I don't know if the `fulfills` list (in the example) is actually useful, since it can be determined by looking at the `spec` of the `Stack` and the provided CRDs or package names.  I imagine if you changed the `dependsOn` spec of the stack that some packages may be updated, installed, or deleted._
  _The stack-manager would still take care of RBAC/isolation for each stack package's deployment._

To talk about this, we end up needing different terms for "Stack".

I'll use "merged `Stack`" to refer to the current `StackInstall` resource that states the intent to install Crossplane and K8s extending resource types and controllers.

"Stack Package" will refer to the Crossplane and K8s extending package that provides the CRDs, `install.yaml`, possibly a controller, and metadata.

With this approach, `ClusterStack` would be created to mirror the merged `Stack`. `ClusterStack` would be used to install cluster scoped CRDs (and their controllers) while the merged `Stack` would be used for namespaced scoped CRDs (and their controllers).

Issue #1150 is focused on ensuring there is only one instance of a particular stack package per cluster (ClusterStackInstall) or namespace (StackInstall).  But we can extend this idea to only one instance of a StackInstall or ClusterStackInstall. This limitation of a single StackInstall resource per namespace would simply management for the controller and users.

With the design that is currently expressed in docs, it is possible to get away with only using a single ClusterStackInstall and StackInstall per namespace to fulfill _all_ stack needs using fuzzy requirements ("any stack that provides wordpress crd" or "all stacks and dependencies required to install "wordpress" and "cloudsql").  Why would a user want more than one `StackInstall` per namespace?  _This part of the design is incomplete, however, because a StackInstall currently has no means to express that it was resolved through multiple Stacks (there is no plural StackRefs `status` list)._

Multiple merged Stacks may currently reside in a single namespace, each with their own set of dependencies.  But we see that a single merged Stack resource is sufficient because these dependencies _must_ be able to coexist within a single namespace and the Stack design is expressive enough that one Stack can represent that intent.

When we consider support for `Stacks` in multiple namespaces relying on the same CRDs and ClusterRoles, this becomes even more confusing.  There can be multiple parents to a resource.  If one contributing StackInstall is removed, should another StackInstall claim the parent labels for the installed resources?

It is much easier to identify the "parent" resource by label when there is only a single parent.

The stack spec is going to take a bit of rethink to accommodate versioning and dependency resolution.  A unified stack shape like the one above could help to accommodate these changes while keeping the overall user experience simple.  

Two types: Stack and ClusterStack.  
One Stack per namespace.
One ClusterStack per cluster.

Consolidated records would serve as the state-of-record for all Stack intent.  In cases where the dependency tree across Stacks is in conflict (bringing us back to versioning concerns), this single record would reflect that as status.

What benefits do we lose over having multiple StackInstall / ClusterStackInstall records?
