### ISSUE TITLE
Provider resource: support credentials as environment variables, or instance's metadata

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#1098]
### What problem are you facing?

Crossplane uses the `Provider` resource (e.g. [GCP provider](https://github.com/crossplaneio/stack-gcp/blob/master/apis/v1alpha3/types.go#L44)) to configure the corresponding cloud provider's credentials, as well as potentially other related information. The credentials are stored in a K8S secret, and used when accessing the cloud API.

In some cases it's desirable to get these credentials from the environment variables. For instance, one might want to manage the credentials through a third-party secret-manager, and provide it to the pod that's running the Provider controller (in this case `stack-gcp` pod that is created as a result of installing gcp stack) as an environment variable (or a file pointer), by a side-car initialization.

Additionally, pods that are running on GKE, EKS or AKS, can use instance's metadata to retrieve its identity and credentials (see [instance metadata](https://cloud.google.com/compute/docs/storing-retrieving-metadata) on GKE for example), and then use it to contact other services. Hence the Provider credentials can be set to default to be retrieved from instance metadata.

### How could Crossplane help solve your problem?

Crossplane should support getting cloud provider credentials through environment variables, or instance metadata.

**Comment by negz** [comment]
Just to clarify, the pod we're talking about in this context is the pod that is running the Crossplane controller-manager in question, right. e.g. The stack-gcp deployment pod(s)?

**Comment by soorena776** [comment]
@negz You are correct, the pod in question is the pod that controls the Provider CRD (e.g. `provider.gcp.crossplane.io/v1alpha3`)

Thanks for clarification, I was pointing at the wrong provider (fixed it).

**Comment by soorena776** [comment]
The pattern that I have seen in AWS and GCP, is to have a _credential chain_, where a few mechanisms are tried one after another to retrieve the credentials. For instance, in AWS most client libraries first inspect AWS environment variables, then the profile config setting under `~/.aws`, and then try the instance metadata api (assuming that it's an EC2 instance.)

I would envision we adopt a similar pattern. We could either have a set of well-known environment variables or credential file paths, or add additional fields to the Provider type to specify them:

```yaml
apiVersion: gcp.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: gcp-provider
spec:
  # replace this with your own gcp project id
  projectID: ${PROJECT_ID}

 # only one of the following three fields will be provided. If none provided, the default chain will be use to retrieve the credentials.

  # proposed fields
  credentialsEnvVar: cred_var
  credentialsFile : path/to/credFile

  # existing field
  credentialsSecretRef:
    namespace: ${PROVIDER_SECRET_NAMESPACE}
    name: gcp-account-creds
    key: credentials
```
