### ISSUE TITLE
Surface claim to resource compatibility in Crossplane's API

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1107]
### What problem are you facing?

Crossplane supports a set of resource claims that may be satisfied by binding to a managed resource. Resource claims may also trigger the dynamic provisioning of a managed resource, which is configured using the resource claim and a resource class as inputs. There is a many-to-many compatibility relationship between resource claims and managed resources, e.g.:

|                    | CloudSQLInstance | RDSInstance | GKECluster |
|--------------------|------------------|-------------|------------|
| **MySQLInstance**      | Compatible       | Compatible  | -          |
| **PostgreSQLInstance** | Compatible       | Compatible  | -          |
| **KubernetesCluster**  | -                | -           | Compatible |

However, this compatibility relationship is defined _only in code_. Each infrastructure stack instantiates a series of claim controllers (for binding, scheduling, and defaulting), each handling the combination of a particular managed resource and resource claim.

This means that there is no obvious way to discover (or as this issue relates to https://github.com/crossplaneio/crossplane/issues/1105, _define_) which managed classes of managed resource may satisfy a particular kind of claim.

### How could Crossplane help solve your problem?

At a minimum, Crossplane should make it easy for application owners to discover which classes of managed resource might satisfy a particular kind of claim. This issue is somewhat coupled to https://github.com/crossplaneio/crossplane/issues/1105, in which it would also be useful for infrastructure operators to _define_ which claims a managed resource can satisfy.

**Comment by negz** [comment]
@bassam has floated the idea of reframing the claim/class pattern as a "resource catalog entry" - something like a resource class that declares which claim it can satisfy, for example:

```yaml
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceCatalogEntry
metadata:
 name: mysql-default
spec:
 # the namespace-scoped resource
 resource: mysqlinstance.database.crossplane.io/v1beta1
 # the cluster-scoped resource that will be
 # dynamically provisioned and bound
 specTemplate:
   apiVersion: database.aws.crossplane.io/v1beta1
   kind: RDSInstance
   specTemplate:
     forProvider:
       dbInstanceClass: db.t2.small
       masterUsername: cool_user
       vpcSecurityGroupIDRefs:
         - name: sample-rds-sg
       dbSubnetGroupNameRef:
         name: sample-dbsubnetgroup
       allocatedStorage: <% size %>
       engine: mysql
       skipFinalSnapshotBeforeDeletion: true
     providerRef:
       name: aws-provider
 # binding related properties
 reclaimPolicy: Delete
```
