### ISSUE TITLE
Proposing update to icons array return types

### ISSUE THREAD

**Issue by rathpc** [crossplane/crossplane#1119]
### What problem are you facing?
Currently as part of a `Stack` CRD, an icons array is returned like the following:

```yaml
icons:
 - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciLz4K
   mediatype: image/svg+xml
```
It seems that there isn't much reason to keep the two properties separate since the same data
is being returned in an annotation within a CRD like so:

```yaml
stacks.crossplane.io/icon-data-uri: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciLz4K
```

Unless there is a strong justification to have icons represented two different ways it seems
better to be more consistent.

With that said I am proposing that we instead return stack icons like the following:

```yaml
icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciLz4KBIWXMA
```

As you can see I am suggesting that get rid of the array all together and just send a string to a
key called `icon`. The `icons` key does not feel like the appropriate place to return information
for other types of images that may be processed and perhaps those should be in a new
`graphics` key should that be necessary in the future.

-----

If that ends up being true we can return something like this for that:

```yaml
graphics:
- uri: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADZCAYAAADWmle6AAAACXBIWXMA
  someMetadata: banner
```

This way we can leave the icon separate and unique and still handle other images related to the
stack should they be included and accepted for parsing later on.
