### ISSUE TITLE
Stack image URI should not be included in the stack image

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1126]
### What problem are you facing?

The file `config/stack/install.yaml` has the following default content that describes how the controller pod would run:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "crossplaneio-minimal-gcp"
  labels:
    core.crossplane.io/name: "crossplaneio-minimal-gcp"
spec:
  selector:
    matchLabels:
      core.crossplane.io/name: "crossplaneio-minimal-gcp"
  replicas: 1
  template:
    metadata:
      name: "crossplaneio-minimal-gcp-controller"
      labels:
        core.crossplane.io/name: "crossplaneio-minimal-gcp"
    spec:
      containers:
      - name: "crossplaneio-minimal-gcp-controller"
        image: "crossplaneio/minimal-gcp"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

As far as I understand, this is included in the stack image. So, wherever I push the image, I have to make sure the image will be pulled from the image URI here in this `install.yaml`. In my opinion, this limits portability of the stack. There could well be cases where I want to use a different registry than the one I configured when I built the stack and just mirror and use a `StackInstall` with the correct image. But the pod will still try to pull from whatever image URI was in `install.yaml` when the image is built.

### How could Crossplane help solve your problem?

I think image should have no idea about where it's going to be pushed as I am already pointing to the actual image URI in `StackInstall` object. `install.yaml` could have a handlebar template like `{{ stackinstall.spec.package }}` or `{{ imageURI }}` and Crossplane can fill this with the value from `StackInstall` object.
