### ISSUE TITLE
Resource usage from workloads

### ISSUE THREAD

**Issue by bassam** [crossplane/crossplane#115]
We need to capture the concept of "using" a given resource like `MySqlInstance` or `Bucket` from a `Workload` or other kinds. We've discussed two approach for this usage, one that is weakly typed for example:

```
apiVersion: compute.conductor.io/v1alpha1
kind: Workload
...
  resources:
    - apiVersion: database.aws.conductor.io/v1alpha1
      kind: rdsinstance
      name: test-database
      namespace: default
...
```

where the the `Workload` has a list of references to resources that it "uses". This would help with the generation of secrets and other connection information, and also with future topology/region aware placement of the workload and its resources.

Another approach is to make the usage strongly typed, and similar to how `volumes:` in a PodSpec works. For example,

```
apiVersion: compute.conductor.io/v1alpha1
kind: Workload
...
  mysql:
    - name: test-database
       accessMode: readOnly
  bucket:
    - name: test-bucket
      accessMode: readWrite
...
```

The former approach enables extensibility by 3rd parties without needing to modify the workload spec. The latter providers a better user experience and enables us to set properties for "usage". One approach is to go with the strongly typed approach and work with APIMachinery SIG to enable strongly typed extensibility model.

This is related to #90.
