### ISSUE TITLE
Support installing any package via the Helm chart

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#1216]
### What problem are you facing?

Currently Crossplane helm chart allows installing a few specific stacks as part of Crossplane installation. It should be possible to install any generic stack. Otherwise the deployment process for Crossplane will not be the same if someone uses an stack other than the well known ones. 
### How could Crossplane help solve your problem?

The following is proposed for the values.yaml in the chart:
```yaml
clusterStacks:
  aws: ...
  gcp: ...
  generic:
    name: mystack
    image: my_public_dockerimage
    version: semver
```

**Comment by suskin** [comment]
@soorena776 Cool! Would you be able to tell us a little more about the use case? As in, what is the reason the user would want to install the stack at the same time as crossplane, rather than waiting until after crossplane is installed? Is it truly **any** stack, or is this more like a custom provider stack?

**Comment by soorena776** [comment]
As for why to install at the same time, the answer is the same answer to why to install aws, gcp, or azure stacks at the same time. When using helm charts for deployment, it's desirable that you don't have to create a single chart just to include the `ClusterStackInstall` CR in it, but pass the chart information to the existing Crossplane chart as variables. 

And by *any* stack, I mean any stack that can be installed using [`ClusterStackInstall`](https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/templates/clusterstackinstalls.yaml) resource.

**Comment by displague** [comment]
Does helm allow for this to be supplied as a cab or array of name:versions to produce multiple stackinstalls?

**Comment by soorena776** [comment]
> Does helm allow for this to be supplied as a cab or array of name:versions to produce multiple stackinstalls?

@displague according to the [docs](https://helm.sh/docs/chart_template_guide/variables/)  the `range` operator can be used which @turkenh has already done it in the [current][current-impl] implementation. We just need to change the [`vaules.yaml.tmpl`](https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/values.yaml.tmpl) to something like:

```yaml
clusterStacks:
  aws:
    name: aws
    version: master
    deploy: false
    image: crossplane/stack-aws
  gcp:
    name: gcp
    version: master
    deploy: false
    image: crossplane/stack-gcp
  azure:
    name: azure
    version: master
    deploy: false
    image: crossplane/stack-azure
  rook:
    name: rook
    version: master
    deploy: false
    image: crossplane/stack-rook
  generic:
    name: "[to be provided]"
    version: "[to be provided]"
    deploy: false
    image: "[to be provided]"
```

And then change the [current][current-impl] to something like:

```yaml
{{- range $key, $val := .Values.clusterStacks }}
{{- if $val.deploy }}
apiVersion: stacks.crossplane.io/v1alpha1
kind: ClusterStackInstall
metadata:
  name: "s{{ $val.name }}"
spec:
  package: "{{ $val.image }}:{{ $val.version }}"
---
{{- end }}
{{- end }}

```

[current-impl]: https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/templates/clusterstackinstalls.yaml
