### ISSUE TITLE
Package unpack format should be typed and well-defined

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1248]
To improve code quality, stack unpack could emit the following format:

```yaml
stack:
   the stack cr object here
stackdefinition:
   the stackdefinition cr here
crds:
  - each
  - crd
  - here

```

rather than the current format of:

```yaml
yaml
---
yaml
---
yaml
```

With the benefits being that we wouldn't need 'what is this?' conditions and we would not have to deal with unstructured.  

We would unmarshal directly using:

```go
type jobOutput struct {
  Stack *v1alpha1.Stack `json:"stack,omitempty"`
  StackDefinition *v1alpha1.StackDefinition `json:"stackdefinition,omitempty"`
  CRDs []apiextensions.CustomResourceDefinition `json:"crds,omitempty"`
}
```

_Originally posted by @displague in https://github.com/crossplaneio/crossplane/pull/1217/files_
