### ISSUE TITLE
template stacks: helm chart input translation

### ISSUE THREAD

**Issue by suskin** [crossplane/crossplane#1287]
### What problem are you facing?

As a stack author using a helm chart with template stacks, I'd like to be able to present an interface to my stack consumers which is different from the schema of the underlying values.yaml file (currently we just pass everything from the CR down unmodified). For example, if I want a simplified CR, or if I am wrapping a third-party helm chart which I can't control the values.yaml contract of.

### How could Crossplane help solve your problem?

This could be done by providing a way for us to translate CR fields into the values.yaml fields for template stacks which use a helm chart. The translation should be able to take the same type of  form as the translation that we already support for the `kustomize` engine type. For example, maybe it would look something like this:

```yaml
  behavior:
    engine:
      type: helm3
      helm3:
        values:
          bindings:
          - from: "spec.config.mysql.port"
            to: "mysql.port"
```
