### ISSUE TITLE
patch existing Kubernetes resource with KubernetesApplication

### ISSUE THREAD

**Issue by janwillies** [crossplane/crossplane#1380]
### What happened?
I want to patch an existing Kubernetes resource (see https://github.com/crossplane/provider-aws/pull/164). After removing the following checks:

- https://github.com/crossplane/crossplane/blob/master/pkg/controller/workload/kubernetes/resource/resource.go#L262
- https://github.com/crossplane/crossplane/blob/master/pkg/controller/workload/kubernetes/resource/resource.go#L333
- https://github.com/crossplane/crossplane/blob/master/pkg/controller/workload/kubernetes/application/application.go#L182

I'm getting:
```
'cannot sync resource: cannot patch object: DaemonSet.apps "aws-node"
        is invalid: spec.template.spec.containers[0].image: Required value'
```
I don't want to set a new image, I only want to add additional environment variables. This is the manifests:

```yaml
---
apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplication
metadata:
  name: custom-network
  namespace: user
spec:
  resourceSelector:
    matchLabels:
      app: custom-network
  # set to uid of KubernetesCluster or Name of KubernetesTarget
  targetRef:
    name: b59151a8-9e49-4361-9ad3-bd7e749c34f7
  resourceTemplates:
    - metadata:
        name: aws-node-daemonset-patch
        labels:
          app: custom-network
      spec:
        template:
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: aws-node
            namespace: kube-system
          spec:
            template:
              spec:
                containers:
                - name: aws-node
                  env:
                  - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
                    value: "true"
                  - name: ENI_CONFIG_LABEL_DEF
                    value: failure-domain.beta.kubernetes.io/zone
```

### What environment did it happen in?
Crossplane version: master
