### ISSUE TITLE
A Composition should be able to patch from a non-existent field path

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1455]
### What happened?

Currently if a `fromFieldPath` references a non-existent field it's considered an error, i.e.:

```
  Warning  ComposeResources   0s (x4 over 3s)  composite/networkgroups.azure.example.org  cannot apply the patch at index 0: metadata.labels: no such field
```

I believe we should not consider this an error. For example below we might want to copy the labels of the composite resource to a composed resource if those labels exist, but ignore it if they do not.

```yaml
    patches:
    - fromFieldPath: "metadata.labels"
      toFieldPath: "metadata.labels"
```

### How can we reproduce it?

Create any `kind: Composition` with the above `patches` example, and attempt to use it with a composite resource that has no labels set.

### What environment did it happen in?
Crossplane version:
