### ISSUE TITLE
composition: external-name override

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1469]
Implementation of `crossplane.io/external-name` annotation propagation to composed resources as designed [here](https://github.com/crossplane/crossplane/pull/1163/files#diff-0108add8ced3d7384cc6114d228ee9fbR986).

**Comment by negz** [comment]
What do you think about pushing this concern entirely into the `patches`? Specifically:

* We replicate the between a requirement and a composition as we do today.
* Compositions don't replicate the annotation to their composed resources by default.
* You can patch `{fromFieldPath: meta.anno[cp.io/e-name], toFieldPath: meta.anno[...]}`
* You can use the string format transform to add suffixes/prefixes if necessary

See the [this composition](https://github.com/crossplane/crossplane/blob/86d4d7/cluster/examples/composition/azure-sqlserver/definitions/networkgroup.yaml#L94) for an example. I like this because it would remove special case logic from our system and reuse an existing more generic feature (the string format transform) to allow it if folks wanted it. For example:

```yaml
    patches:
    - fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
      toFieldPath: "metadata.annotations[crossplane.io/external-name]"
      transforms:
      - type: string
        string:
          fmt: "%s-database-a"
```
