### ISSUE TITLE
Implement ApplicationScope in Crossplane

### ISSUE THREAD

**Issue by resouer** [crossplane/crossplane#1480]
### What problem are you facing?
We didn't find concrete use case for Scope concept on K8s before so we decide to skip it temporarily in Crossplane. Though we now found Scope is actually a strong need for traffic mgmt in app. For example the [Istio BookInfo sample](https://github.com/istio/istio/tree/master/samples/bookinfo) should be able to be modeled easily with Crossplane's application model.

The mapping would be:

- _Component_ - Deployment
- _Trait_ - Service/Ingress per Deployment
- _Scope_ - Service/Ingress/APIGateway across Deployments
- _ApplicationConfiguration_ - a YAML file to grouping Component/Trait/Scope together

Mirror issue: https://github.com/oam-dev/rudr/issues/558#issuecomment-622186672

### How could Crossplane help solve your problem?
Implement [Scope](https://github.com/oam-dev/spec/blob/master/5.application_scopes.md) feature in Crossplane's application model.

/cc @omkensey @ryanzhang-oss

**Comment by resouer** [comment]
@artursouza volunteered offline to tackle this issue, though I have no privilege to assign issue to him ...

@negz or @hasheddan  help?

**Comment by hasheddan** [comment]
@resouer i think he needs to be added to Crossplane org. @jbw976 could you add @artursouza?

**Comment by jbw976** [comment]
I have sent an invitation to @artursouza to join the Crossplane org as a member. Once he accepts then issues can be assigned to him. I've never understood that GitHub limitation 🤔

**Comment by hasheddan** [comment]
Thanks so much @jbw976 :)

**Comment by resouer** [comment]
@hasheddan Hi Daniel, seems now the issue can be assigned to Artur. Could you help with that?

**Comment by hasheddan** [comment]
@resouer done :)

**Comment by draveness** [comment]
Hi @artursouza, do we have any ongoing PR or implementations on this issue? :)

**Comment by wonderflow** [comment]
I'm not sure if there's any existing proposal about how to implement scope? @artursouza 

In my mind, scope is create by stand alone CR but component joining a scope should be controlled by oam-k8s-runtime.

For example, a workflow may be something like below:

1. Create a scope CR first

```
apiVersion: core.oam.dev/v1alpha2
kind: NetworkScope
metadata:
  name: my-vpc-network
  labels:
    region: us-west
    environment: production
spec:
  networkId:  my-vpc
  subnetIds:
  - my-subnet1
  - my-subnet2
  internetGatewayType: nat
```

2. create  AppConfig who's going to use this scope

```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: custom-single-app
spec:
  components:
    - componentName: backend
      scopes:
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: NetworkScope
            name: my-vpc-network
```

3. AppConfig Controller(oam-k8s-runtime) will know nothing about the schema of this NetworkScope, but he can change the annotation:

```
apiVersion: core.oam.dev/v1alpha2
kind: NetworkScope
metadata:
  name: my-vpc-network
  labels:
    region: us-west
    environment: production
  annotation:
     core.oam.dev/workloads: '[{"apiversion":"data.oam.dev/v1","kind":"Cassandra","name":"backend"},{"apiversion":"apps/v1","kind":"Deployment","name":"frontend"},]
spec:
  networkId:  my-vpc
  subnetIds:
  - my-subnet1
  - my-subnet2
  internetGatewayType: nat
```

4. finally the controller behind the NetworkScope can control these workload instances.

**Comment by artursouza** [comment]
Hi,

Sorry for the delay on this. Here is what I am thinking for ApplicationScope:

1. A CR(s) to deploy a resource first. In case of a network in Azure, it is done in 3 CRs, like in the example below:
```
---
apiVersion: network.azure.crossplane.io/v1alpha3
kind: VirtualNetwork
metadata:
  name: myvpc-example
spec:
  resourceGroupNameRef:
    name: aks-example
  location: West US 2
  properties:
    addressSpace:
      addressPrefixes:
        - 10.2.0.0/16
  reclaimPolicy: Delete
  providerRef:
    name: example
---
apiVersion: network.azure.crossplane.io/v1alpha3
kind: Subnet
metadata:
  name: mysubnet1-example
spec:
  resourceGroupNameRef:
    name: aks-example
  virtualNetworkNameRef:
    name: myvpc-example
  properties:
    addressPrefix: 10.2.0.0/24
    serviceEndpoints:
      - service: Microsoft.Sql
  reclaimPolicy: Delete
  providerRef:
    name: example
```

2. A CR to declare the Scope, referencing the resource above:
```
apiVersion: core.oam.dev/v1alpha2
kind: NetworkScope
metadata:
  name: myvpc-network
spec:
  networkId:  myvpc-example
  subnetIds:
  - mysubnet1-example
  - my-subnet2
  internetGatewayType: nat
```

3. Create AppConfig to use scope:
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: custom-single-app
spec:
  components:
    - componentName: backend
      scopes:
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: NetworkScope
            name: myvpc-network
```

4. AppConfig Controller(oam-k8s-runtime) must be aware of the structure of each Scope Kind. This way, it know how to provision the workloads underneath. The network controller cannot change the deployed workload. The network where a workload is deployed is defined at the creation time of the workload, so the appconfig controller must understand "NetworkScope".
