### ISSUE TITLE
Proposal: Introduce CompositionRevision

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1481]
### What problem are you facing?

The [experimental composition design](https://github.com/crossplane/crossplane/pull/1163) introduces the concept of a Crossplane resource that composes other resources. Under this design there is [an open question](https://github.com/crossplane/crossplane/pull/1452#discussion_r417671831) around which resource(s) should represent the authoritative desired state for an external resource.

There are a few moving parts under the current design:

* A composite infrastructure resource. A (mostly) arbitrary Kubernetes custom resource that is roughly equivalent to a Helm values file or a Terraform module `inputs.tf` file. From the user's perspective the composite infrastructure resource _is_ the resource. A [`NetworkGroup`](https://github.com/crossplane/crossplane/blob/86d4d7/cluster/examples/composition/azure-sqlserver/networkgroup.yaml) is an example of a composite resource; it's a concept defined by an infrastructure operator.

* An optional infrastructure requirement. An infrastructure requirement is a lightweight proxy for a composite resource; their schemas are for all intents and purposes identical. Requirements exist to enable separation of concerns. Application operators may not typically operate directly on a composite infrastructure resource, but may operate on it indirectly via its corresponding infrastructure requirement. A [`PrivatePostgreSQLServerRequirement`](https://github.com/crossplane/crossplane/blob/86d4d/cluster/examples/composition/azure-sqlserver/privatepostgresqlserver.yaml) is an example of a requirement; it is a proxy for a `PrivatePostgreSQLServer` composite infrastructure resource.

* A `Composition`. A template used to "fill in the blanks" - to specify the "base layer" over which the composite resource's spec is overlaid to render one or more composed resources. A ` Composition` is analogous to a set of Helm moustache templates or a Terraform module `main.tf`. One novel difference between Crossplane and the aforementioned tools is that multiple compositions may be able to satisfy a particular kind of composite resource. [This composition](https://github.com/crossplane/crossplane/blob/86d4d7/cluster/examples/composition/azure-sqlserver/definitions/networkgroup.yaml#L64) can satisfy the earlier `NetworkGroup` composite resource.

* The composed infrastructure resources. The outputs of the composition process. These are either primitive (atomic) managed infrastructure resources, or nested composite infrastructure resources. They're analogous to the (custom) resources rendered by a Helm chart, or the Terraform resources rendered by a Terraform module.

* The external infrastructure resources; the actual infrastructure ("external" to the Kubernetes API) that is being orchestrated by Crossplane.

The question we face is what combination of the composite resource (slash requirement), the composition, and the composed resources should be considered the authoritative desired state of the external resources. I see three options:

1. The composite resource and the composition are authoritative only at create time. They are used to render a set of composed resources which are henceforth authoritative. The user must edit the composed resources to enact any updates; updating the composite resource or the composition has no effect on existing composed resources. This is the closest option to Crossplane's contemporary model, in which resource claims and classes are authoritative only at create time.

2. The composite resource and the composition are authoritative at all times. Composed resources are effectively "read-only" (to the user) outputs of the composite resource and its composition. Composed resources that are directly edited after creation are automatically reset to the desired state declared by the composite resource and its selected composition every N duration (i.e. every reconcile of the composite). The user must edit the composite resource and/or composition in order to update the composed and thus external resources.

3. A hybrid approach. The composite resource is authoritative at all times, but the composition is only authoritative at create time. After create time the composed resources become authoritative for any field that is not controlled by the composite resource.

No one is suggesting option one in practice. Under this model application operators would have no control after creation time, because they can only influence a resource requirement which in turn influences the composite resource. If editing the composite resource does nothing to the composed resources, and only an infrastructure operator can edit the composed resources, then application operators may never update the resources that they provision.

Option two is the most conceptually simple. The composite resource and composition are authoritative at all times. Option two also allows application operators to influence any field at update time that they can influence at create time, because they may create and update resource requirements. Resource requirement configuration flows onto composite resource configuration which flows onto composed resource configuration. The major drawback to option two is that a composition may be used by many composite resources at once. Composed resources cannot be updated directly, and only a small subset of the sum of all composed resource fields map to composite resource fields. If the `spec.widgets` field of a composed resource is only ever set by the composition, then you must update the composition in order to update it. Updates to the composition may have a large blast radius if the composition is used by many composite resources.

Option three addresses the issues of option two through a compromise. Updates to the composition have no effect on existing composed resources; only newly created ones. Updates to a composite resource do flow on to composed and thus external resources. Option three is however the most conceptually complex; the composite resource is _always_ authoritative over _some_ fields. _Either_ the composition or the composed resources are authoritative for _other_ fields depending on where they are in their lifecycle (i.e. create time vs update time). Under this model it's difficult to determine which downstream (composed) fields are expected to be directly updatable, and which must be updated via the composite resource.

### How could Crossplane help solve your problem?

I propose Crossplane adopt what I believe is the conceptually simplest approach (option 2), and address its shortcomings by introducing a `CompositionRevision`, which would allow composite resources to pin to a particular snapshot of a `Composition`. This concept has prior art in the form of metacontroller's [`ControllerRevision`](https://metacontroller.app/api/controllerrevision/) and to a lesser extent the `apps/v1` `ControllerRevision`. It also opens up the possibility of building a Terraform-like client-side "diff before apply" UX around composite resources.

Under this proposal:

* A `Composition` would be mutable.
* Each mutation of a `Composition` would be snapshot as an immutable `CompositionRevision` (the same way a `Deployment` mutation is snapshot as a `ReplicaSet`).
* Composite resources would be pinned at creation time to a particular ` CompositionRevision` of their selected `Composition` - the one labelled `latest` by default.
* A composite resource's `spec.compositionRef` (which specifies the composition to use) would be a mutable reference to ` CompositionRevision`.

Take the below composite resource:

```yaml
apiVersion: vpc.example.org/v1alpha1
kind: VirtualNetwork
metadata:
  name: example
spec:
  location: us-west
  addressPrefix: 10.2.0.0/16
  compositionRef:
    name: vpc.azure.example.org
```

This resource represents an abstract VPC network. It uses the `vpc.azure.example.org` composition to determine exactly what resources it should compose. That composition looks something like:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: vpc.azure.example.org
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: vpc.example.org/v1alpha1
    kind: VirtualNetwork
  to:
  - base:
      apiVersion: network.azure.crossplane.io/v1alpha3
      kind: VirtualNetwork
      spec:
      # etc etc...
```

In practice when the above `Composition` was created, a controller would snapshot it as an identical `CompositionRevision`. In this example the name of the `CompositionRevision` is the name of the `Composition` suffixed with a hash of the `Composition`. The `CompositionRevision` is also labelled as the `latest` revision, and with its hash.

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositionRevision
metadata:
  name: vpc.azure.example.org.ae8fc1
  labels:
    apiextensions.crossplane.io/composition: vpc.azure.example.org
    apiextensions.crossplane.io/tags: ae8fc1,latest
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: vpc.example.org/v1alpha1
    kind: VirtualNetwork
  to:
  - base:
      apiVersion: network.azure.crossplane.io/v1alpha3
      kind: VirtualNetwork
      spec:
      # etc etc...
```

Furthermore, when the above composite resource was created, it would automatically pin to whatever `CompositionRevision` was the latest:

```yaml
# A composite resource.
apiVersion: vpc.example.org/v1alpha1
kind: VirtualNetwork
metadata:
  name: example
spec:
  location: us-west
  addressPrefix: 10.2.0.0/16
  compositionRef:
    name: vpc.azure.example.org
    # We find the latest CompositionRevision and pin its hash.
    revision: ae8fc1
```

Reconciles of the `VirtualNetwork` composite resource actually use the immutable `CompositionRevision` to render composed resources, not the `Composition`. The composite resource _can_ however pick a new `CompositionRevision` at any time. This revision could be of the same `Composition` it originally used, or a new one. This has several nice properties:

* Compositions can be updated without implicitly affecting existing composite resources.
* Existing composite resources can roll back and forward at their leisure.
* Existing composite resources can switch to a completely different composition if desired.
* crossplane-cli can compute and present diff of an updated composition before it's applied.

Imagine the following UX:

```yaml
# Edit the manifest of the existing vpc.azure.example.org Composition.
$ $EDITOR composition.yaml  

# Apply the updated vpc.azure.example.org Composition. Existing VirtualNetworks
# are unaffected, but new VirtualNetworks will use the new CompositionRevision.
$ kubectl apply -f composition.yaml 

# There's still only one composition.
$ kubectl get compositions
NAME                         AGE
vpc.azure.example.org        26h

# However now there are two revisions of that composition.
$ kubectl get compositionrevisions -l apiextensions.crossplane.io/composition=vpc.azure.example.org
NAME                          TAGS          AGE
vpc.azure.example.org.ae8fc1  ae8fc1,latest 1m
vpc.azure.example.org.9edb46  9edb46        26h

# The VirtualNetwork named example is using the original revision, 9edb46.
$ kubectl crossplane composite get-revision virtualnetwork example
9edb46

# We want to update to our new revision, which can be referred to as either
# ae8fc1 or latest.
$ kubectl crossplane composite set-composition virtualnetwork example vpc.azure.example.org:latest

Would apply the following changes:

  apiVersion: network.azure.crossplane.io/v1alpha3
  kind: VirtualNetwork
  metadata:
     name: example-akfj2
  spec:
    properties:
      addressSpace:
-       enableDdosProtection: false
+       enableDdosProtection: true
        addressPrefixes:
        - 10.2.0.0/16

Would you like to continue? (y/N):

# We may event want to completely change our composition
$ kubectl crossplane composite set-composition virtualnetwork example vpc.gcp.example.org:latest

Would apply the following changes:

  ---
- apiVersion: network.azure.crossplane.io/v1alpha3
- kind: VirtualNetwork
- metadata:
-    name: example-akfj2
- spec:
-   properties:
-     addressSpace:
-       enableDdosProtection: false
-       addressPrefixes:
-       - 10.2.0.0/16
+ apiVersion: compute.gcp.crossplane.io/v1alpha3
+ kind: Network
+ metadata:
+   name: example-mfj2f
+ spec:
+   forProvider:
+     autoCreateSubnetworks: false
+     routingConfig:
+       routingMode: REGIONAL
+ apiVersion: compute.gcp.crossplane.io/v1alpha3
+ ---
+ kind: Subnetwork
+ metadata:
+   name: example-2nd91
+ spec:
+   forProvider:
+     region: us-central1
+     ipCidrRange: 10.2.0.0/16

# If this broke the user could easily roll back to their previous configuration.
$ kubectl crossplane composite set-composition-composition virtualnetwork example vpc.azure.example.org:9edb46
```

We could do this by rendering the composed resources using the composite resource and the current composition, then rendering them again using the composite resource and the proposed composition, and then computing and displaying the diff.
