### ISSUE TITLE
allow users to define external scripts/function and  include interpolation support

### ISSUE THREAD

**Issue by arturrez** [crossplane/crossplane#1506]
### What problem are you facing?
I am trying to use `specTemplare.forProvider.privateClusterConfig.masterIpv4CidrBlock` in `GKEClusterClass` to control masterIpv4CidrBlock for GKECluster instances created using this class. This approach is similar to https://www.terraform.io/docs/configuration/functions/cidrsubnet.html using allocation strategy like http://jodies.de/ipcalc?host=192.168.0.1&mask1=24&mask2=28. 

I would like to define some master subnet and use something like https://www.terraform.io/docs/configuration/functions/cidrsubnet.html to allocate IP sub-ranges from it.

This is related to https://github.com/crossplane/crossplane/issues/1505

### How could Crossplane help solve your problem?
It can be achieved by using some external script/ function.

**Comment by negz** [comment]
```
cidrsubnet("172.16.0.0/12", 4, 2)
```

https://crossplane.io/docs/v0.11/introduction/composition.html

Under composition we could add a transform function that did this. For example:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: example-azure
  labels:
    purpose: example
    provider: azure
spec:
  from:
    apiVersion: example.org/v1alpha1
    kind: KubernetesCluster
to:
  - base:
      apiVersion: container.gcp.crossplane.io/v1beta1
      kind: GKECluster
      spec:
        forProvider:
          # fields omitted for brevity...
    patches:
    - fromFieldPath: spec.parameters.netNum
      toFieldPath: spec.forProvider.privateClusterConfig.masterIpv4CidrBlock
      transforms:
      - type: cidrsubnet
        prefix: 172.16.0.0/12
        newbits: 4
```

This would address this issue only (i.e. not #1505), in that the author of the `KubernetesCluster` would be able to specify which network number their cluster should be. That said, I'm not sure we should take this approach. If the `KubernetesCluster` composite resource (which is similar to a contemporary resource claim) was being created automatically by some other system, it would probably be better to just expose the `masterIpv4CidrBlock` as a `KubernetesCluster` spec field and let the higher level system handle allocating an appropriate CIDR.

**Comment by muvaf** [comment]
I think a nice setup for this case could be a custom mutating webhook where if the caller leaves the cidr blocks empty, the webhook would go query the provider API for the clusters in that network and their blocks to find a suitable one and fill those fields. All CRs in the control cluster would still be kept stateless and the query would be against the actual state.

Though I agree with @negz in the sense that I can't see a place in Crossplane where this would be there by default given that the CRs are defined by the user. Maybe we can implement it for common `InfrastructureDefinition` of `KubernetesCluster` in respective provider controllers but that feels like a long shot right now given that we don't yet have a webhook mechanism in place.

**Comment by enderv** [comment]
Came across this issue not sure if I should file a new one. This seems limited to the CIDR topic but would like a way to supply your own logic for transforms. Using the CIDR example instead of building it into crossplane just add a way you can supply your own function logic. If this is too off base for this let me know and I can open a new issue.

**Comment by kferrone** [comment]
In response to @enderv 

Maybe we could have something like:

```yaml
apiVersion: crossplane.io
kind: Transform
metadata:
  name: cidrsubnet
spec:
  image: mycidrimage:latest
  env: # we could use the env to retrieve the params from the functions
  - name: CIDR
     valueFrom:
       fromTransforms: prefix
  command: 
    - run_my_cidr_func $CIDR $BITS
  ... # the rest of the core k8s container spec
```

Then the transforms be like the above example:
```yaml
transforms:
      - type: cidrsubnet
         prefix: 172.16.0.0/12
         newbits: 4
```
