### ISSUE TITLE
Flesh out Kubernetes Clusters to support Node Pools and Worker Nodes

### ISSUE THREAD

**Issue by bassam** [crossplane/crossplane#152]
We need to flesh out our generic Kubernetes Cluster API to support node pools, worker nodes, and other features common across managed Kubernetes providers. For example, something like the following:

```
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: demo-cluster
spec:
  clusterVersion: 1.10
  nodePools:
    - name: default
       machineType: n1-standard-1
       autoScale: true
       minNodes: 1
       maxNodes: 10
    - name: performance
       machineType: n1-standard-1
       minNodes: 1
       maxNodes: 10
       taints:
         - high-performance:true:NoSchedule
```

Each Kubernetes cluster will have a `ResourceClass` of course that brings in implementation details and policy.
