### ISSUE TITLE
HealthScope

### ISSUE THREAD

**Issue by artursouza** [crossplane/crossplane#1597]
# Context

[HealthScope](https://github.com/oam-dev/spec/blob/master/standard/scopes/health_scope.md) aggregates the health status of multiple components via a web API.

In Rudr, it was implemented as described here: https://github.com/oam-dev/rudr/tree/master/healthscope

# Proposal

Re-implement Rudr's approach but for the new v1alpha2 spec.

1. Deploy OAM's health scope controller:
```
helm install healthscope ./charts/healthscope
```

```
export POD_NAME=$(kubectl get pods -l "app.kubernetes.io/name=healthscope,app.kubernetes.io/instance=healthscope" -o jsonpath="{.items[0].metadata.name}")
kubectl port-forward $POD_NAME 8080:80
```

The health scope controller (like in Rudr) does 2 things:
1. Periodically check health status of components and update the HealthScope resource status.
2. serve as a http server, to output aggregated health information.

Optionally, it can be extended to offer `/metrics` API so health status can be exported to Prometheus.

2. Instantiate HealthScope as per the v1alpha2 spec:
```
apiVersion: core.oam.dev/v1alpha2
kind: HealthScope
metadata:
  name: example-health-scope
spec:
  probe-method: GET
  probe-endpoint: /health
```

```
$ kubectl get healthscope
NAME              AGE
example-health-scope   31s
```
HealthScope controller keeps track of the healthscopes created.

2. Declare one ApplicationConfiguration, using the health-scope:
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: first-app
spec:
  components:
    - componentName: helloworld-python-v1
      parameterValues:
        - name: target
          value: Rudr
        - name: port
          value: "9999"
      scopes:
        - apiVersion: core.oam.dev/v1alpha2
           kind: HealthScope
           name: example-health-scope
```

Services generated as part of the ApplicationConfig have the following additional label:
```
healthscope.core.oam.dev/example-health-scope: true
```

Example:
```
$ k describe service helloworld-python-v1
Name:                     helloworld-python-v1
Namespace:                default
Labels:                   workload.oam.crossplane.io=2df4035f-8019-4600-9317-ffbf2ac409b0
                            healthscope.core.oam.dev/example-health-scope: true
Annotations:            <none>
Selector:                 containerizedworkload.oam.crossplane.io=2df4035f-8019-4600-9317-ffbf2ac409b0
Type:                     LoadBalancer
IP:                       10.97.248.231
Port:                     helloworld-python-v1  3003/TCP
TargetPort:               3003/TCP
NodePort:                 helloworld-python-v1  31919/TCP
Endpoints:                172.17.0.12:3003,172.17.0.13:3003
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

HealthScope controller can now query for all services in a health scope by selecting them based on label.

Finally, the health of the scope is reported in:

http://localhost:8080/scopes/example-health-scope

**Comment by hongchaodeng** [comment]
That's a great start!

Just one nit:

> healthscope.core.oam.dev/example-health-scope: true

In k8s , we usually use the following format instead:

```
 healthscope.core.oam.dev/name: example-health-scope
```

Label key is an indicator of the type, not the instance.

**Comment by artursouza** [comment]
But it can belong to many health scopes. It is a many to many relationship. So, the key cannot repeat.

— Artur Souza
________________________________

**Comment by hongchaodeng** [comment]
I see. In this case, why not add a status to indicate all the scopes in a component:

```yaml
kind: Component
status:
  scopes: ... list of scopes ...
```
They are all oam concepts and we should have a standardized status like this.

**Comment by hongchaodeng** [comment]
I think it is ambiguous on the "services" and diverging our discussions.
Could you write more details on how HealthScope controller check Components' health status?

**Comment by wonderflow** [comment]
Instead of using labels, what about aggregate all information into Scope instance.
```
apiVersion: core.oam.dev/v1alpha2
kind: HealthScope
metadata:
  name: foo
spec:
  workloadRefs:
    - apiVersion: core.oam.dev/v1alpha2
      kind: ContainerizedWorkload
      name: bar
    - apiVersion: alibaba.com/v1
      kind: RDS
      name: database
```

We can assume every OAM AppScope will have a fixed field such as `workloadRefs`. So oam-kubernetes-runtime can insert workloads to this fixed field without understand the AppScope.

This mechanism is a little like [workload and trait interaction mechanism](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/one-pager-trait-workload-interaction-mechanism.md).
