### ISSUE TITLE
Composition to reference fields from another base

### ISSUE THREAD

**Issue by janwillies** [crossplane/crossplane#1603]
Looking at solving https://github.com/crossplane/provider-aws/issues/212 with `Composition` I ran into the following:

1. need to reference a fieldpath from another base
2. fill a placeholder in a free form `spec.forProvider.assumeRolePolicyDocument: |`
3. only a substring of the string from 1. is needed

Here is the YAML file I came up with:
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: ekscluster-irsa
  labels:
    provider: aws
spec:
  from:
    apiVersion: example.org/v1alpha1
    kind: EKSClusterInstance
  to:
  - base:
      apiVersion: eks.aws.crossplane.io/v1beta1
      kind: Cluster
      spec:
        forProvider:
          roleArn: arn:aws:iam::1234567890:role/crossplane-eks-cluster-role
          resourcesVpcConfig:
            subnetIds:
              - subnet-abc
              - subnet-def
          version: "1.16"
        reclaimPolicy: Delete
        providerRef:
          name: aws  
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRole
      spec:
        forProvider:
          roleName: ekscluster-velero
          assumeRolePolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {
                      "${OIDC_PROVIDER}:sub": "system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME}"
                    }
                  }
                }
              ]
            }
        reclaimPolicy: Delete
        providerRef:
          name: aws
    patches:
    # need to get a field from the other base (`Cluster`), put it into this base spec.forProvider.assumeRolePolicyDocument... AND transform it
    # status.atProvider.identity.oidc.issue outputs the following URL:
    # https://oidc.eks.eu-central-1.amazonaws.com/id/F00BAR1C01C4F51A59436D9096A1A
    - fromFieldPath: "status.atProvider.identity.oidc.issuer"
      # the information needs to go into both ${OIDC_PROVIDER} placeholders (after transformation)
      toFieldPath: "spec.forProvider.assumeRolePolicyDocument...."
      transforms:
      - type: string
        string:
          fmt: "%s" # how to get a substring, only the last part after "..amazonaws.com/id/": F00BAR1C01C4F51A59436D9096A1A
  - base:
      apiVersion: identity.aws.crossplane.io/v1alpha1
      kind: IAMPolicy
      spec:
        forProvider:
          name: eksluster-name-s3-mybucket-admin
          document: |
            {
              "Version": "2012-10-17",
              "Statement":[{
                "Effect": "Allow",
                "Action": "s3:*",
                "Resource": ["arn:aws:s3:::my_bucket",
                             "arn:aws:s3:::my_bucket/*"]
                }
              ]
            }
        reclaimPolicy: Delete
        providerRef:
          name: aws
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRolePolicyAttachment
      metadata:
        name: ekscluster-velero
      spec:
        forProvider:
          roleNameRef:
            name: ekscluster-velero
          # https://github.com/crossplane/provider-aws/issues/232
          policyArn: arn:aws:iam::aws:policy/s3-mybucket-admin 
        reclaimPolicy: Delete
        providerRef:
          name: aws-provider
  - base:
      apiVersion: workload.crossplane.io/v1alpha1
      kind: KubernetesApplication
      metadata:
        name: velero-service-account
        # should the namespace be left out here since Composition is cluster-scoped?
        namespace: xyz
      spec:
        # should match the EKS Cluster from above
        targetRef:
          matchControllerRef: true
        resourceSelector:
          matchLabels:
            app: velero
        resourceTemplates:
        - metadata:
            name: velero-namespace
            labels:
              app: velero
          spec:
            template:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: velero
        - metadata:
            name: velero-service-account
            labels:
              app: velero
          spec:
            template:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: velero
                annotations:
                  eks.amazonaws.com/role-arn: arn:aws:iam::$AWS_ACCOUNT_ID:role/$IAM_ROLE_NAME
    # need to reference the IAMRole from above
    - fromFieldPath: "spec.forProvider.roleName"
      # the information needs to go into the $IAM_ROLE_NAME placeholder in the velero-service-account
      toFieldPath: "spec.resourceTemplates[1].spec.template.metadata.annotations['eks.amazonaws.com/role-arn']"
      transforms:
      - type: string
        string:
          fmt: "arn:aws:iam::1234567890:role/%s" # with static AWS Account
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
```
