### ISSUE TITLE
InfrastructureDefinitions cannot be included in a package

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1610]
### What problem are you facing?

I am trying to bundle a [stack package](https://github.com/crossplane/stack-gcp-sample/pull/55) and wanted to use a new type called `PrivateNetwork` that is defined by the stack. Since `InfrastructureDefinition`s require a new `ClusterRole` to be aggregated to core Crossplane `ServiceAccount`, I included it in the package and added the following to `dependsOn` section of `app.yaml`: `clusterrole.rbac.authorization.k8s.io/v1`

When I tried to install it, I get the following as output of `kubectl get package sample-gcp-stack -o yaml`:
```
...
status:
  conditionedStatus:
    conditions:
    - lastTransitionTime: "2020-06-23T12:08:10Z"
      reason: Resource is being created
      status: "False"
      type: Ready
    - lastTransitionTime: "2020-06-23T12:08:10Z"
      message: permissions contain a restricted rule
      reason: Encountered an error during resource reconciliation
      status: "False"
      type: Synced
```

In the codebase, I see that this error returned here https://github.com/crossplane/crossplane/blob/master/pkg/controller/packages/pkg/pkg.go#L549

So, Crossplane Package Managed does not allow any native types to be installed by the packages but in this case I need it because I'd like to use `InfrastructureDefinition`

### How could Crossplane help solve your problem?

The `ClusterRole` I need to install is very simple and specific to the particular type I just installed:
```
---
# This allows Crossplane to manage our new composite resource.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privatenetworks.gcpsample.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - gcpsample.crossplane.io
    resources:
      - privatenetworks
      - privatenetworks/status
    verbs:
      - "*"
```

But since the permissions are set on kind level, even if it's meaningless I cannot have a package that deals with `ClusterRole`s. So there are two options:

1. Crossplane can create the necessary `ClusterRole` immediately when the respective `InfrastructureDefinition` is created.
2. There is a mechanism already that lets core Crossplane to work with all types introduced via CRDs from packages. However, this is limited for the cases that you bring in an actual `CustomResourceDefinition`s like providers. In my case, I'd like to create an `InfrastructureDefinition`, whose result is essentially `CustomResourceDefinition` at API level. So, there should be a way to treat `InfrastructureDefinition`s in the packages the same way we treat bare `CustomResourceDefinition`s in the provider packages.

In either case, Crossplane does create a `ClusterRole` for itself. But that is already the case. In fact, if we don't do that, the users will need `ClusterRole` RBAC permissions from their cluster operators (or have them create it) for this simple action, which renders the cluster less secure than Crossplane creating `ClusterRole` for itself, targeting a specific type that it created.
