### ISSUE TITLE
InfrastructurePublication can be a field on InfrastructureDefinition

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1615]
### What problem are you facing?

Here is an example `InfrastructurePublication`:
```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: kubernetesclusters.common.crossplane.io
spec:
  infrastructureDefinitionRef:
    name: kubernetesclusters.common.crossplane.io
```

This can actually be a field on `InfrastructureDefinition` to avoid a separate resource call as well as the mechanics of deletion being dependent on each other; you have to delete `InfrastructurePublication` before `InfrastructureDefinition` and that causes some problems in some systems, for example Helm where the resources are deleted in order.

### How could Crossplane help solve your problem?

It can be a field on `InfrastructureDefinition` like `spec.publish: true` or `spec.publishAsRequirement` or `spec.availableInNamespaces: true`
