### ISSUE TITLE
Consider improving the UX of defaults in Compositions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1635]
### What problem are you facing?

In Crossplane a "composite resource" is a CR whose schema is defined by an InfrastructureDefinition. The composite resource is reconciled by composing one or more "composed resources". The relationship between the composite and the composed resources is configured by a Composition. The Composition specifies templates ("bases") for the composed resources, as well as a series of "patches" that patch each base by mapping fields from the composite resource.

It's currently possible to support default values, i.e. values that will be used when a field is omitted from the composite resource:

```yaml
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: clusters.example.upbound.io
spec:
  crdSpecTemplate:
    group: example.upbound.io
    version: v1alpha1
    names:
      kind: Cluster
      listKind: ClusterList
      plural: clusters
      singular: cluster
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Note that this field is not marked required. When it is omitted
              # the default value specified in the Composition will be used.
              clusterVersion:
                description: GKE cluster version
                type: string
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: clusters.example.upbound.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: example.upbound.io/v1alpha1
    kind: Cluster
  to:
    - base:
        apiVersion: container.gcp.crossplane.io/v1beta1
        kind: GKECluster
        spec:
          providerRef:
            name: gcp-provider
          forProvider:
            # This version is the 'default' version for the Cluster. It will be used if the
            # author of the Cluster CR omits the spec.clusterVersion.
            initialClusterVersion: 1.15.11-gke.17
      patches:
        - fromFieldPath: spec.clusterVersion
          toFieldPath: spec.forProvider.initialClusterVersion
    - base:
        apiVersion: container.gcp.crossplane.io/v1alpha1
        kind: NodePool
        spec:
          forProvider:
            # This version is the 'default' version for the NodePool. It will be used if the
            # author of the Cluster CR omits the spec.clusterVersion.
            version: 1.15.11-gke.17
      patches:
        - fromFieldPath: "spec.clusterVersion"
          toFieldPath: "spec.forProvider.version"
```

In the above abridged example both the composed `GKECluster` and the `NodePool` will default to version `1.15.11-gke.17`, unless the `Cluster` CR specifies a different value, which would then override the version in each base.

### How could Crossplane help solve your problem?

@ktintc has been experimenting with composition and expressed that she would prefer a UX that was closer to specifying a default value for the `fromFieldPath: spec.clusterVersion` rather than specifying defaults for each base. This has the advantage of not repeating the default value in multiple places in cases where that would be ready (i.e. specifying the same version in the GKECluster and NodePool bases).

Note that once we update to v1 CRDs (per https://github.com/crossplane/crossplane/issues/1435) we'll get something like this for free, because v1 CRDs support default values, and thus we'd be able to easily support that in our InfrastructureDefinitions, for example:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: clusters.example.upbound.io
spec:
  crdSpecTemplate:
    group: example.upbound.io
    version: v1alpha1
    names:
      kind: Cluster
      listKind: ClusterList
      plural: clusters
      singular: cluster
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              clusterVersion:
                description: GKE cluster version
                type: string
                # A default value can now be specified in the InfraDef
                default: 1.15.11-gke.17
```
