### ISSUE TITLE
Composite resources should support bidirectional patching

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1639]
### What problem are you facing?

Currently a `Composition` configures how the values of a composite resource's fields should be used to influence composed resources; the composite resource's spec values may be 'overlaid' or 'patched' onto the composed resources. For example the below `Composition` patches the external name annotation from the composite resource (the `KubeCluster`) to the composed resource (the `NodePool`):

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: mycomposition
spec:
  from:
    apiVersion: example.org/v1alpha1
    kind: KubeCluster
  to:
  - base:
      apiVersion: container.gcp.crossplane.io/v1alpha3
      kind: NodePool
      spec:
        # ...
  - patches:
    - fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      transforms:
        type: string
        string:
          fmt: "%s-a"
```

This allows a composite resource to control the desired state of its composed resources. Ideally it would also be possible to reflect the actual state of composed resources on the composite resource. For example a `KubeCluster`  resource that composed a `GKECluster` might want to reflect the `status.atProvider.status` (`RUNNING`, `PROVISIONING`, etc) of the `GKECluster` in its own status.

### How could Crossplane help solve your problem?

Crossplane could support bidirectional patching - both from composite to composed resource and from composed to composite resource. Presumably this would require us to rethink the `from` and `to` convention in the `Composition` schema.

This could look something like:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: mycomposition
spec:
  composite:
    apiVersion: example.org/v1alpha1
    kind: KubeCluster
  composed:
  - base:
      apiVersion: container.gcp.crossplane.io/v1beta1
      kind: GKECluster
      spec:
        # ...
  - patches:
    - fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      direction: CompositeToComposed  # Perhaps this is the default?
      transforms:
        type: string
        string:
          fmt: "%s-a"
    - fromFieldPath: status.atProvider.status
      toFieldPath: status.state
      direction: ComposedToComposite
```

**Comment by muvaf** [comment]
I feel like `direction` is too big of a property to let other fields unaffected. To elaborate:
```yaml
patches:
- fromFieldPath: metadata.annotations[crossplane.io/external-name]
  toFieldPath: metadata.annotations[crossplane.io/external-name]
  direction: CompositeToComposed  # Perhaps this is the default?
  transforms:
    type: string
    string:
      fmt: "%s-a"
- fromFieldPath: status.atProvider.status
  toFieldPath: status.state
  direction: ComposedToComposite
```

When I look at these two elements, they look very similar but what they are used for are vastly different. An example in Kubernetes is volume list where you have different types of volumes in each element of the array, but in volume case the resulting behavior of each element is same; a volume to be mounted. So, the form of input is different but output is of the same type. But in this case, I believe output is completely different between a patch with `direction: ComposedToComposite` and `direction: CompositeToComposed` while input looks pretty same.

In order to reduce the cognitive load and need for being extra careful, my suggestion would be to separate these two types of output into their own fields:
```yaml
patches:
- fromFieldPath: metadata.annotations[crossplane.io/external-name]
  toFieldPath: metadata.annotations[crossplane.io/external-name]
  transforms:
    type: string
    string:
      fmt: "%s-a"
outputs:
- fromFieldPath: status.atProvider.status
  toFieldPath: status.state
```

I think `patches` as a name is still good since it's right after the `base` that it will be applied to. Though I'm not fully sure about `outputs` name, open to suggestions. Maybe `propagations` but that could mean either direction.
