### ISSUE TITLE
Composed resources should respect external name annotation

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1640]
### What problem are you facing?

Crossplane resources support an annotation - `crossplane.io/external-name` - that may dictate or reflect the 'external' name of a resource - i.e. the unique identifier of that resource an the external system such as a cloud provider that Crossplane is orchestrating. This annotation works roughly like:

* If the external system generates its own unique ID, we set the annotation to that ID.
* If the external system allows the caller to specify a unique ID and the managed resource author...
  * specifies the annotation, we use its value as the unique ID.
  * omits the annotation, we set it to the managed resource's `metadata.name`.

When resource claims are being used this annotation is propagated between the claim and the managed resource it's bound to. This allows the resource claim author to influence the external name (aka unique ID) of the external resource by setting the annotation on their resource claim.

When composition is being used the annotation is propagated from the requirement (if any) to the composite resource. Whether the annotation is propagated from the composite resource to the composed resource to the composed resources is determined by the author of the `Composition`. If the author does not explicitly configure patches from the composite resource's annotation to the composed resources' annotations, the annotation will be non-functional. I believe this behaviour is likely to surprise users of Crossplane. `crossplane.io/external-name` sounds like a standard annotation that will be honored, but whether or not it has meaning above the managed resource level is likely to be highly inconsistent given that it's dependent on humans remembering to write configuration that propagates it.

### How could Crossplane help solve your problem?

I believe Crossplane should propagate the external name annotation from the composite resource to all composed resources by default. This ensures the annotation will always be honored.

The potential one-to-many relationship between a composite resource and its composed resources means there would be some gotches with this approach. Namely:

1. Two composed resources of the same kind would very likely experience name conflicts by default. For example a `KubeCluster` composite resource that composed two GKE `NodePool` managed resources would attempt to name them both the same thing by default.
1. There's no obvious way to propagate the annotation back from the composed resources to the composite resource in the case where the cloud provider does not allow us to specify an external name. If there are three composed resources, which resource's external name should be considered the external name of the one composite?

Both of these issues could be addressed by allowing `Composition` authors to override the default behaviour - to override the default relationship between the external name annotations. The first issue could be addressed by allowing a `Composition` to patch over the annotation that was set by default:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: mycomposition
spec:
  from:
    apiVersion: example.org/v1alpha1
    kind: KubeCluster
  to:
  - base:
      apiVersion: container.gcp.crossplane.io/v1alpha3
      kind: NodePool
      spec:
        # ...
  - patches:
    - fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      transforms:
        type: string
        string:
          fmt: "%s-a"
  - base:
      apiVersion: container.gcp.crossplane.io/v1alpha3
      kind: NodePool
      spec:
        # ...
  - patches:
    - fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      transforms:
        type: string
        string:
          fmt: "%s-b"
```

The second could be addressed effectively in reverse of the first, by letting the `Composition` author specify which composed resource (if any) should map its external name back to the composite resource. This would require something like https://github.com/crossplane/crossplane/issues/1639 to be implemented.

Ultimately this seems like a case of "which default behaviour is less bad", with a choice of:

* The annotation has no effect by default.
* The annotation is at risk of causing a naming conflict by default.

I prefer the latter choice because I believe is less surprising and it has less risk of human error. If the annotation has no effect unless the `Composition` author remembers to propagate it, a user could reasonably annotate their requirement or composite and have everything appear to work without issue. Their composed resources would create and the composite would appear to be ready, but in fact their annotation was being ignored. If the annotation causes a conflict when there are multiple resources of the same kind _and_ the `Composition` author did not address this then any composite resources using that `Composition` would always break, making it obvious that the `Composition` needed to be updated.

**Comment by kelvinwijaya** [comment]
Hi @negz 

Based on my testing with the latest version of crossplane v0.12.0, the composition did populate the annotation variables that i have passed from requirements objects, my S3Bucket object is created as per the external name supplied in the requirements object

```
apiVersion: crd.aws.abc.com/v1alpha1
kind: BucketRequirement
metadata:
  name: test-bucket
  annotations:
    crossplane.io/external-name: test-bucket-1
```

Composition object:

```
patches:
        - fromFieldPath: "metadata.labels"
          toFieldPath: "metadata.labels"
        - fromFieldPath: "metadata.annotations"
          toFieldPath: "metadata.annotations"
```

What i did is patches done at parent level instead of `metadata.annotations[crossplane.io/external-name]`
