### ISSUE TITLE
Metadata annotations fields and label should be propagated from requirement to managed resource object

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/crossplane#1654]
### What problem are you facing?

From requirement object : MySQLInstanceRequirement, i would like to pass the metadata annotations and labels information to the managed resource object : MySQLInstance

So that when the composition object could extract the metadata annotations or labels (other than `external-name`) to be map in the specification of the DB Object, this is useful when the annotation information is required as a Tag informations of the DBInstance that is being provisioned

```

apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
.
.
spec:
          forProvider:
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: false
            backupRetentionPeriod: 1
            copyTagsToSnapshot: true
            applyModificationsImmediately: true
            tags:
              - key: "Key0"
                value: ""
              - key: "Key1"
                value: ""
              - key: "Key2"
                value: ""
.
.
.
- fromFieldPath: "metadata.annotations.key0"
          toFieldPath: "spec.forProvider.tags[0].value"
        - fromFieldPath: "metadata.annotations.key1"
          toFieldPath: "spec.forProvider.tags[1].value"
        - fromFieldPath: "metadata.annotations.key2"
          toFieldPath: "spec.forProvider.tags[2].value"
.
.
```

### How could Crossplane help solve your problem?

By allowing any metadata annotations and label objects to be mapped.
