### ISSUE TITLE
Make composed resource readiness detection configurable

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1687]
### What problem are you facing?

Composite resources were designed to compose managed resources, and other composite resources. In practice the composite controller expects that the resources it composes:

* Are cluster scoped
* Can eventually become "ready", in the sense that their `type: Ready` status condition can transition to `status: True`.

The latter expectation is limiting on two fronts:

* In some cases it may be useful to include a `ProviderConfig` (fka `Provider`) in a `Composition`. For example a composition may want to create an EKS cluster and make it consumable by other providers (e.g. the [Helm provider](https://github.com/crossplane-contrib/provider-helm) or the [Rook provider](https://github.com/crossplane/provider-rook)) by composing a Kubernetes `ProviderConfig`.
* Per https://github.com/crossplane/crossplane/pull/1677 we plan to start introducing managed resources that are shims around Terraform providers. Terraform resources don't have a generic concept of 'readiness'.

### How could Crossplane help solve your problem?

Crossplane could allow the `Composition` author to describe what it means for a resource to be "ready". I suspect a reasonable approach would be:

1. If the composition specifies how to determine readiness, those conditions determine whether the resource is ready.
1. If the resource has a `Ready` status condition and it's not `True`, the resource is not ready.
1. If the resource has a `Ready` status condition and it is `True`, the resource is ready.
1. If the resource has no `Ready` status condition but `Synced` status condition is `True`, the resource is ready.

I imagine a `Composition` would allow authors to specify whether a resource is ready via something like:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: clusters.cnp.example.org
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: CoolComposite
  resources:
  - base:
      apiVersion: example.org/v1alpha1
      kind: CoolManaged
    patches:
    - fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    readiness:
    - fieldPath: status.atProvider.state
      type: Match
      match: "ONLINE"
```

**Comment by negz** [comment]
@muvaf would you be interested in tackling this? I suspect @rathpc would have good insight, as I recall he worked on a similar JSON path based approach to determining readiness at the frontend.

At the moment I believe our most pressing need is to include a `ProviderConfig` in a composition, so a good first step might be to simply update Crossplane to determine that a composed resource has no `Ready` condition and simply consider it to be ready.

**Comment by turkenh** [comment]
What about following a similar approach as [`kubectl wait`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait), where one can specify the condition to wait for:

```
kubectl wait --for=condition=ready pod -l app=test 
```

A new optional field (e.g. type `*string`) like `WaitForCondition` could help to satisfy most cases:

1. Not setting it, defaults to "Ready" which is the case right now.
2. Possible to wait custom conditions `WaitForCondition: Synced` 
3. To skip waiting at all, set it empty string: `WaitForCondition: ""` 

Or to be a little more flexible and to support [arbitrary jsonpath](https://github.com/kubernetes/kubernetes/issues/83094) in the future without changing api, a new field named `WaitFor`:

1. Not setting it, defaults to "condition=Ready" which is the case right now.
2. Possible to wait custom conditions `WaitFor: condition=Synced` 
3. To skip waiting at all, set it empty string: `WaitFor: Exists` (similar to `kubectl wait --for delete`)
4. Arbitrary jsonpath: `WaitFor: "jsonpath={.status.phase == "Running"}"` or [even more](https://github.com/kubernetes/kubernetes/issues/83094#issuecomment-567368568) `WaitFor: "jsonpath={ (.status.conditions.type == "Complete") or (.status.conditions.type == "Failed" }"`

I think, this way we can have a quick solution covering most cases and consider extending it based on feedback as @muvaf suggests above.

Alternatively we can name it as `ReadyCondition` or similar, if we believe word `Ready` better represents that it will effect readiness of the composite resource.

**Comment by muvaf** [comment]
@turkenh I think JSONPath isn't really that different than the `fieldpath` implementation we have and from what I can tell, there is no out-of-box support for evaluation of `==`, `>` and other operators. So, we have to write code on top of it or we'll use jsonpath just to get a value similar to the example above:

```yaml
readinessProbe:
  jsonPath: .status.containerStatuses[?(@.name=="crossplane")].restartCount
  type: Match
  match: "1"
```


However, as you can see in the example, it has support for [selecting](https://kubernetes.io/docs/reference/kubectl/jsonpath/) an element in the array via condition, i.e. in the array of `containerStatuses`, get the one with `name: crossplane`. I don't think the current `fieldpath` implementation we have handles this and it could be crucial. For example `.status.conditions[?(@.type=="Ready")].status` is a valid statement. How does the following look like?

```yaml
readinessProbe:
  jsonPath: .status.conditions[?(@.type==\"Ready\")].status
  type: Match
  match: True
```

For our immediate use-case, there isn't much difference:

```yaml
readinessProbe:
  jsonPath: metadata.uid
  type: NonEmpty
```

Though it is a nicer experience to use the same `fieldPath` across the CR given that we use it already in `patch`es. @negz do you think it's worth to implement `[@.XField]` operator in `fieldPath`? Having both `fieldPath` and `jsonPath` is also an option, maybe first have `fieldPath` and add `jsonPath` later.
