### ISSUE TITLE
Validation for dynamic provider allowed values

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#169]
A lot of resources have a set of allowed values by the cloud provider that will change over time, such as the allowed machine types, or the list of regions where a service is available.  We can hard code these lists into the controller code and the CRD schema validation, but those lists will become stale over time as the providers make updates.

It would be ideal to fetch these allowed values at runtime so we do not need to make any code changes when the allowed values change.  The best user experience does validation through CRD schema validation, which is performed up front during CRD create.  If the user's value is no good then they get an error at create time as opposed to later on downstream.  This could be accomplished by:
* webhook validation for CRDs
* controllers update the CRD with schema validation at runtime after fetching the allowed values from the provider (is this possible to update schema validation?)

Not all provider values have an API to fetch the list of allowed values, but we should do this for any that do.

Originally discussed in https://github.com/crossplaneio/crossplane/pull/150/files#r236804934

**Comment by jbw976** [comment]
Another great example for how this type of functionality could improve the user experience is the supported Kubernetes versions for Azure AKS clusters.  Those change over time, and if a resource class is specifying a version that is no longer supported, the AKS cluster will go to the following failed condition:

```
  status:
    Conditions:
    - LastTransitionTime: 2019-02-20T03:41:43Z
      Message: 'failed to start create operation for AKS cluster aks-2dad6b7d-34c1-11e9-935d-08002745fceb:
        containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request:
        StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The value
        of parameter orchestratorProfile.OrchestratorVersion is invalid." Target="orchestratorProfile.OrchestratorVersion"'
      Reason: failed to create cluster
      Status: "True"
      Type: Failed
```
It would be much better if we could look up what the allowed versions are and provide earlier admissions based validation, e.g. when the resource class is first being created.

For AKS, I think we could fetch the allowed Kubernetes versions through the [List Orchestrators API](https://docs.microsoft.com/en-us/rest/api/container-service/container%20service%20client/listorchestrators).  Yes, that is for Container Service resources, but I think it's also shared with AKS Managed Clusters resources too.
