### ISSUE TITLE
Define Connection Secret Format

### ISSUE THREAD

**Issue by ciaranRoche** [crossplane/crossplane#1712]
### What problem are you facing?

On provisioning a resource a connection secret is created, this connection secret contains the required data to connect to the resource. There may be use-cases where extra data is required by the user consuming this secret.  

An example use case, a user provisions a database when creating an rds instance. The connection secret created does not contain the postgres database name.
### How could Crossplane help solve your problem?

Provide a means for a user to define a custom connection secret based on readily available metadata via the managed resource spec/status

**Comment by muvaf** [comment]
Hi @ciaranRoche ! In managed resources, this isn't really possible as they are considered as the lowest level components. If you'd like to propose a new key in the connection secret, we can do that by making a code change. However, when you use higher level constructs like [Crossplane composition](https://crossplane.io/docs/v0.12/getting-started/publish-infrastructure.html), you define your own resources and decide on the keys in YAML.

When you use `CompositeResourceDefinition` (i.e. old `InfrastructureDefinition`), you have some options to decide how the connection secret of your composite resource looks like.

The first step is to decide what keys you'd like to expose in the final `Secret` via `InfrastructureDefinition.spec.connectionSecretKeys` array. These are the keys that will be available for the consumers.
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: postgresqlinstances.database.example.org
spec:
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
...
```

Then how the values for these keys are filled depends on the `Composition` you use. Here is an example `Composition`:
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: postgresqlinstances.aws.database.example.org
  labels:
    provider: aws
    guide: quickstart
    vpc: default
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: database.example.org/v1alpha1
    kind: PostgreSQLInstance
  to:
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            dbInstanceClass: db.t2.small
            masterUsername: masteruser
            engine: postgres
            engineVersion: "9.6"
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
```

As you can see, in `spec.to[0].connectionDetails` there is some information about what values you'd like `RDSInstance` to publish for consideration. In this example, by using only `fromConnectionSecretKey`, user would like a direct propagation of those keys. They could do:
```yaml
- name: myfinalkeyname # this will be the key name in the final secret
  fromConnectionSecretKey: username
```
or
```yaml
- name: myfinalkeyname
  value: my-constant-value # no matter what, this will be the value for myfinalkeyname in the final secret
```

[Here](https://github.com/crossplane/crossplane/blob/c81a3d7/apis/apiextensions/v1alpha1/composition_types.go#L285) is the full struct.

So, in your use case, do you think having a constant database name would be sufficient or do you actually need something like:
```yaml
- name: myfinalkey
  fromFieldPath: spec.somefield
```
