### ISSUE TITLE
k8s ExternalName Service for Provider Endpoints and Port Forwarding

### ISSUE THREAD

**Issue by kferrone** [crossplane/crossplane#1727]
### What problem are you facing?
I recently just realized AWS will randomly change the Endpoint for a service, therefore the URL to something like MySQL is not predictable. Basically all the providers, AWS Google, etc, generate big long URLs for your apps to connect to. These URLs also need to be distributed to developers so they can connect and manage these services.

Recently, I got slammed by my devs because they could no longer connect and I had to re-share the URL and they all had to update their connections. 

Fortunately Crossplane will reflect these kind of changes in the secret bindings, therefore the secret with connection details is always up to date. However, k8s will never update an environment variable or a file bound to a secret or a configmap within a pod. Even if it did, an app would probably have to restart to reflect these changes anyway. Therefore the only way for your app to see the new endpoint/details is to delete the pod and let it be recreated. We luckily have some smart health checks which check the DB connection, if it can't connect then the health check fails and k8s auto recreates the pod which indeed runs the app with the new updated connection details. 

My next issue with theses endpoints is they are not like how k8s likes to do hostnames. K8s uses service names as the hostname so that hostnames are always easily predictable. For example, if you have mysql installed in cluster with a service called `mysql` then the hostname is `mysql`.  This makes hostnames and services easy to predict. 

### How could Crossplane help solve your problem?

My big idea here is for Crossplane to optionally create a k8s service which can represent the external services endpoint. This way, even if the provider decides to change the endpoint, within the cluster the service would simply update like the secret does because of Crossplane. Then the hostname would always be predictably based on the name of the resource you created. 

The option to create such a service could be like this:
```yaml
kind: RDSInstance
apiVersion: database.aws.crossplane.io/v1beta1
metadata:
  name: mysql
spec:
  forProvider:
    ...
  providerRef:
    name: aws
  reclaimPolicy: Delete
  writeConnectionSecretToRef:
    name: mysql
  createExternalNameService: 
    name: mysql # if set this would be the option to create the ExternalName service
    ports:
    - port: 3306
      targetPort: 3306
      name: db
```

There are two ways this can be accomplished:

#### Option 1: Service of Type ExternalName

This is by far the easiest option, most recommendable as it is very easy to do, very unobtrusive, and non offensive. I actually already do this but I have to manually update the `externalName` when the endpoint changes and the resource has to be manually created when the service is finally provisioned, I wanna be lazy ya know. 

Basically it looks like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  # the name would be based on the underlying crossplane resource like how the connection secrets are named
  name: mysql
  namespace: default
spec:
  type: ExternalName
  # crossplane would update this along with the connection secret when things change
  externalName: mysql-abc123.yaddablabla.us-west-2.rds.amazonaws.com
  ports:
  - port: 3306
    targetPort: 3306
    name: db
```

Then I can decide for an app to use the endpoint within the connection secret, if it has a smart health check. However if you did not have such a fancy health check, you could simply use the service name as the hostname and not worry about restarts, ie `mysql`.  

Our devs use an SSH tunnel to access these services. It is much easier to tell them the remote host is simply `mysql` instead of `mysql-abc123.yaddablabla.us-west-2.rds.amazonaws.com`. Also when the endpoint changes, I simply update the service and the devs don't need to do anything. 

#### Option 2: Magical Proxy Pod  

This is definitely the hard way to go, however you would get magical powers. Basically there would be some kind of reverse-proxy service like HaProxy, Nginx, Envoy, etc. The reverse-proxy would be the pod for the k8s Services to select, which means more than one service would select the same pod. Then the the reverse-proxy would use the hostname or port or something from the service to decide which external endpoint to use. This way a developer could use `kubectl port-forward svc/mysql 3306:3306` and actually have AWS RDS MySQL forwarded on dev machine. The dev would not even need to know how or where mysql was installed. 

I have done this before with Nginx and it basically worked with everything but MySQL. MySQL turned out to be very difficult to reverse-proxy. I simply mapped each external service to a port on the Nginx Pod. Then I simply port-forward the nginx pod and choose a port to choose a service. eg `kubectl port-forward svc/nginx 27017:27017` to get DocumentDb on AWS. However this still had the downside that I had to manually change the endpoint when AWS decided to change it. Ultimately the SSH Tunnel was the option we chose as it was way less complex, especially with MySQL.
