### ISSUE TITLE
MySQLInstance composite resource not Ready

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/crossplane#1754]
### What happened?

I have created CompositeResource Definition for MySQLInstance , but seem when i check the event status:

![image](https://user-images.githubusercontent.com/11241076/93793944-1064dd00-fc6a-11ea-8c85-dd6c0fad0a01.png)

![image](https://user-images.githubusercontent.com/11241076/93794081-3ab69a80-fc6a-11ea-94bb-86f5a00fc024.png)

Is this feature implemented already for MySQLInstance? I tried with S3Bucket implementation using CompositeResourceDefinition and it is successfully bounded

### How can we reproduce it?

By creating CompositeResourceDefinition:

```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: mysqlinstances.crd.aws.abc.com
spec:
  claimNames:
    categories:
      - crd.aws.abc.com
    kind: ClaimMySQLInstance
    listkind: ClaimMySQLInstanceList
    plural: claimmysqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  crdSpecTemplate:
    group: crd.aws.abc.com
    version: v1alpha1
    names:
      kind: MySQLInstance
      listKind: MySQLInstanceList
      plural: mysqlinstances
      singular: mysqlinstance
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
.
.
.
```

### What environment did it happen in?
Crossplane version: v0.13.0-rc.114.g20493ac

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"cle
an", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTr
eeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kelvinwijaya** [comment]
Also to add on the latest version: v0.13.0-rc.161.gb48ee89. It also break for Bucket (Composite). The resource never been in ready state, when i revert to `rc.114.g20493ac` then it is fine, but still MySQLInstance(Composite) is not working yet

**Comment by kelvinwijaya** [comment]
I test few revision before the things break: the one that start to not working is `crossplane-0.13.0-rc.110.g5fa4896`

Hope it helps! I think probably due to some refactoring from publications to definitions

**Comment by muvaf** [comment]
The composite resource (the one whose kind is `MySQLInstance` in this case) becomes [`Ready`](https://github.com/crossplane/crossplane/blob/master/pkg/controller/apiextensions/composite/reconciler.go#L319) when all composed resources become `Ready`. Could you check the resources listed under `spec.resourceRefs` of `MySQLInstance` and see if their `status.conditions[type=Ready]` is `true`?

**Comment by kelvinwijaya** [comment]
Hi @muvaf 

I am testing back with the latest crossplane version `v0.13.0-rc.179.g9ee6139`

To demonstrate the behaviour, I am currently using kind: Bucket as my composite resource

Show below the status from composite claim: (e.g. kind: CSBucket):
![image](https://user-images.githubusercontent.com/11241076/93912349-3657b380-fd36-11ea-8799-3a5de28770e5.png)


Also I am viewing the composite resource manifest, I cant see any status there (only can see my spec):
![image](https://user-images.githubusercontent.com/11241076/93912974-0957d080-fd37-11ea-8c0d-ba98b5b682e9.png)


I believe this happen similarly to other resources say MySQLInstance

Thanks,
Kelvin

**Comment by negz** [comment]
@kelvinwijaya Are you able to run `kubectl describe mysqlinstances.crd.aws.abc.com`? There may be some events or status that will help us figure out what is going on. If you're using AWS resources, `kubectl get -o wide aws` might help too.

**Comment by kelvinwijaya** [comment]
Hi @negz ,


Here is the events log for your further investigation:

![image](https://user-images.githubusercontent.com/11241076/94329789-aabd7b80-fff0-11ea-80f7-9af6d05c8ad1.png)



Also  when i `kubectl get -o wide aws` , the s3bucket is not there
I am sure not sure why there is some error on:
```
cannot create object: s3buckets.storage.aws.crossplane.io is forbidden: User "system:serviceaccount:cr
ossplane-system:crossplane"
```
But i dont face it for version before `0.13.0-rc.110.g5fa4896`

**Comment by krishchow** [comment]
I believe this is an RBAC issue - you need to cluster role associated with this composition - see example gist below. You will need to create your own cluster role for this composition - i.e., change all the references to reflect your infrastructure definition. I generally create all my ClusterRoles at the same time I install Crossplane into a cluster.

https://gist.github.com/krishchow/3ff140cdbf8365fdace854279fcb3b65

**Comment by kelvinwijaya** [comment]
Thanks @krishchow .

Yes indeed i have added this before hand to extend the existing clusterrole by using the aggregate annotation

But the weird part is, the warning show that the user is prohibited to access API group : "storage.aws.crossplane.io" which is the crossplane base group object

**Comment by muvaf** [comment]
> But the weird part is, the warning show that the user is prohibited to access API group : "storage.aws.crossplane.io" which is the crossplane base group object

Interesting, provider installation does cover the creation of `ClusterRole`s for Crossplane pod to reconcile the new managed resources. How did you install the AWS Provider?

FWIW, RBAC manager has landed and it takes care of all RBAC related things including roles necessary for new claims & composites. If possible, I'd suggest trying to go through the same exercise with `master` https://github.com/crossplane/crossplane/pull/1728

Side note; to install a provider in `master`, you need to create the following:
```yaml
apiVersion: pkg.crossplane.io
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:master
```
