### ISSUE TITLE
CompositeResourceDefinition connectionSecretKeys param doesn't trigger Secret creation in Claim Resource namespace

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/crossplane#1765]
### What happened?
As previously in publication, if we defined connectionSecretKeys, the Secret will be created based on the name given in claim object with the name extracted from writeConnectionSecretToRef 

### How can we reproduce it?
Create MySQLInstance Claim Resource and observe whether the Secret is being created in the namespace

### What environment did it happen in?
Crossplane version: v0.13.0-rc.109.ga3425d5

**Comment by negz** [comment]
Thanks for the bug report @kelvinwijaya! Could you share your XRD, Composition, and Claim here? I just tried to reproduce the issue using the `docs/snippets/compose` examples in master (18324aa15a191bbb1a71a0161af5edd9f7bddfe6) but everything seems to be working as expected.

```console
$ kubectl describe postgresqlinstance.database.example.org|grep -A1 'Write Connection'
  Write Connection Secret To Ref:
    Name:  db-conn

$ kubectl get secret db-conn
NAME      TYPE                                DATA   AGE
db-conn   connection.crossplane.io/v1alpha1   4      41m
```

**Comment by kelvinwijaya** [comment]
Hi @negz ,

Thanks for checking, maybe there might be edge scenario in my params
Currently I am on : v0.13.0-rc.109.ga3425d5

My CompositionResourceDefinition:

```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: mysqlinstances.crd.aws.abc.com
spec:
  claimNames:
    categories:
      - crd.aws.abc.com
    kind: ClaimMySQLInstance
    listkind: ClaimMySQLInstanceList
    plural: csmysqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  crdSpecTemplate:
    group: crd.aws.abc.com
    version: v1alpha1
    names:
      kind: MySQLInstance
      listKind: MySQLInstanceList
      plural: mysqlinstances
      singular: mysqlinstance
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  masterUsername:
                    description: name for the master user
                    type: string
                  masterPasswordSecretRef:
                    description: 
                    type: object
                    properties:
                      name:
                        description: name for the masterpassword secret Reference
                        type: string
                      namespace:
                        description: namespace for the masterpassword secret Reference
                        type: string
                  dbInstanceClass:
                    description: compute and memory capacity of the DB instance
                    type: string
                    enum: ["db.t2.small", "db.t2.medium", "db.m4.large", "db.r5.large"]
                  engine:
                    description: name of the database engine to be used for this instance
                    type: string
                    enum: ["mysql", "aurora-mysql"]
                  engineVersion:
                    description: version number of the database engine to use.
                    type: string
                    enum: ["5.6", "5.7", "5.6.10a", "5.7.12"]
                  dbClusterIdentifier:
                    description: identifier of the DB cluster that the instance will belong to
                    type: string
                  readReplicaSourceDBInstanceIdentifier:
                    description: identifier of the source DB instance if this DB instance is a Read Replica
                    type: string
                  allocatedStorage:
                    description: amount of storage (in gibibytes) to allocate for the DB instance
                    type: integer
                  deletionProtection:
                    description: DB instance should have deletion protection enabled. 
                    type: boolean
                  skipFinalSnapshotBeforeDeletion:
                    description: Determines whether a final DB snapshot is created before the DB instance is deleted.
                    type: boolean
                required:
                  - dbInstanceClass
                  - engineVersion
                  - engine
                  - secretName
                  - allocatedStorage
            required:
              - parameters
```

And Composition:

```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: mysqlinstances.crd.aws.abc.com
spec:
  compositeTypeRef:
    apiVersion: crd.aws.abc.com/v1alpha1
    kind: MySQLInstance
  resources:
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            skipFinalSnapshotBeforeDeletion: false
            publiclyAccessible: false
            backupRetentionPeriod: 1
            copyTagsToSnapshot: true
            applyModificationsImmediately: true
            multiAZ: true
            region: us-east-1
          reclaimPolicy: Delete
      patches:
        - fromFieldPath: "metadata.labels"
          toFieldPath: "metadata.labels"
        - fromFieldPath: "metadata.annotations"
          toFieldPath: "metadata.annotations"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.forProvider.finalDBSnapshotIdentifier"
          transforms:
            - type: string
              string:
                fmt: "mysql-%s"
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
        - fromFieldPath: "metadata.namespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
        - fromFieldPath: "spec.parameters.masterUsername"
          toFieldPath: "spec.forProvider.masterUsername"
        - fromFieldPath: "spec.parameters.engine"
          toFieldPath: "spec.forProvider.engine"
        - fromFieldPath: "spec.parameters.dbInstanceClass"
          toFieldPath: "spec.forProvider.dbInstanceClass"
        - fromFieldPath: "spec.parameters.engineVersion"
          toFieldPath: "spec.forProvider.engineVersion"
        - fromFieldPath: "spec.parameters.allocatedStorage"
          toFieldPath: "spec.forProvider.allocatedStorage"
        - fromFieldPath: "spec.parameters.deletionProtection"
          toFieldPath: "spec.forProvider.deletionProtection"
        - fromFieldPath: "spec.parameters.dbClusterIdentifier"
          toFieldPath: "spec.forProvider.dbClusterIdentifier"
        - fromFieldPath: "spec.parameters.readReplicaSourceDBInstanceIdentifier"
          toFieldPath: "spec.forProvider.readReplicaSourceDBInstanceIdentifier"
        - fromFieldPath: "spec.parameters.skipFinalSnapshotBeforeDeletion"
          toFieldPath: "spec.forProvider.skipFinalSnapshotBeforeDeletion"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
```



Thanks,
Kelvin
