### ISSUE TITLE
Generic Cross-Resource References

### ISSUE THREAD

**Issue by kasey** [crossplane/crossplane#1770]
### What problem are you facing?
As mentioned in the design doc for terraform-based controller codegen(https://github.com/crossplane/crossplane/pull/1677/) , we will need to implement a generic cross-resource referencing scheme to compensate for the fact that terraform does not provide the necessary metadata for our code generator to understand which fields are cross-referenceable. 

### How could Crossplane help solve your problem?

A design document would allow us to collect feedback on the syntax and behavior of these references.

**Comment by negz** [comment]
Here's a strawman sketch of what generic cross-resource references might look like.

Today we have this for example:

```yaml
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: VPC
metadata:
  name: my-vpc
spec:
  ...
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: my-subnet
spec:
  forProvider
    vpcId: vpc-33fk3fjdf2  # The VPC's actual external name
    # Used to resolve the VPC's actual external name.
    # The resolution logic is written in Go as part of
    # adding support for a new managed resource.
    vpcIdRef:
      name: my-vpc
  ...
```

With generic cross-resource references this might look like:
```yaml
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: VPC
metadata:
  name: my-vpc
spec:
  ...
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: my-subnet
spec:
  # Open ended naming so we could extend this with other kinds
  # of field modifiers. Perhaps this is overthinking it?
  fieldModifiers:
  - fromRef:
      apiVersion: v1alpha2
      kind: VPC
      name: my-vpc
      fieldPath: metadata.annotations[crossplane.io/external-name]
    # Perhaps this should be scoped/limited to spec.forProvider?
    toFieldPath: spec.forProvider.vpcId
  forProvider:
    vpcId: vpc-33fk3fjdf2  # The VPC's actual external name
  ...
```

**Comment by muvaf** [comment]
That looks pretty good to me. Do we want to allow taking values from namespaced resources?

**Comment by negz** [comment]
Unstale please. I'm still pretty sure we're going to need this.

**Comment by negz** [comment]
Throwing out another idea (based on a demo of something related @apelisse) put together - I could see a distinct `Reference` type being in some ways better than an array of references embedded in a resource.

So instead of...

```yaml
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: VPC
metadata:
  name: my-vpc
spec:
  ...
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: my-subnet
spec:
  fieldModifiers:
  - fromRef:
      apiVersion: v1alpha2
      kind: VPC
      name: my-vpc
      fieldPath: metadata.annotations[crossplane.io/external-name]
    # Perhaps this should be scoped/limited to spec.forProvider?
    toFieldPath: spec.forProvider.vpcId
  forProvider:
    vpcId: vpc-33fk3fjdf2  # The VPC's actual external name
  ...
```

We'd have something like:

```yaml
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: VPC
metadata:
  name: my-vpc
  annotations:
    crossplane.io/external-name: vpc-123jdfdf
spec:
  ...
---
apiVersion: network.aws.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: my-subnet
spec:
  forProvider:
    vpcId: "" # I need a value to function!
  ...
---
apiVersion: crossplane.io/v1alpha1
type: Reference
metadata:
  name: subnet-to-vpc
spec:
  # A reference "from" a subnet "to" a VPC
  from:
    apiVersion: network.aws.crossplane.io/v1alpha2
    kind: Subnet
    name: my-subnet
    fieldPath: spec.forProvider.vpcId
  to:
  # An array to support the case where a reference is derived from multiple
  # fields in multiple objects? This would likely end up pretty close to
  # Composition patches, with transforms etc.
  - apiVersion: network.aws.crossplane.io/v1alpha2
    kind: VPC
    name: my-vpc
    fieldPath: metadata.annotations[crossplane.io/external-name]
```

Some challenges that come to mind:

* RBAC. The controller resolving the `Reference` type would need to read "to" resources and write to the "from" resource.
* Blocking reconciliation of the "from" (referencing) resource until the "to" (referenced) resource fieldpath value(s) were populated.
* Discoverability of references. You probably want to `kubectl describe <from> <name>` and see what it references (and vice versa?).

Presuming the controller responsible for resolving the `Reference` type was part of core Crossplane it would in most cases already have all the RBAC permissions it needed to resolve references from Crossplane types to other Crossplane types because the RBAC manager grants the Crossplane pod permission to read all XRs and MRs that it might need to compose.

I could imagine blocking and discoverability being handled by having the managed resource reconciler:

1. List all References and find any that are "from" its managed resource.
2. Record those references under (e.g.) `status.references`
3. Block further reconciliation until all recorded references were resolved
