### ISSUE TITLE
Pod leaked after unsuccessful provider installation

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#1788]
### What happened?

I used the following YAML to install AWS Provider:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:latest
```

I got the following because that image didn't exist:
```
crossplane-provider-aws-latest               0/1     ImagePullBackOff   0          2m53s
```

Then I fixed the tag and run `kubectl apply` with the following:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:master
```

Now I have:
```
crossplane-provider-aws-latest               0/1     ImagePullBackOff   0          5m3s
crossplane-provider-aws-master               0/1     Completed          0          2m42s
```

I was expecting that pod to be recreated with the new image path.

### How can we reproduce it?

As explained above.

### What environment did it happen in?
Crossplane version: 0.13.0-rc.235.g74e45fe
