### ISSUE TITLE
Support serving multiple XRD versions?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1871]
### What problem are you facing?

A Crossplane Composite Resource Definition (XRD) is an opinionated abstraction built on top of a Kubernetes Custom Resource Definition (CRD). A CRD extends the Kubernetes API server with support for a new resource. In addition to extending the API server with a new resource, an XRD:

* Places constraints on the new resource's schema - e.g. that it have a `spec.compositionRef` and `status.conditions`.
* Places constraints on users of the new resource - i.e. that they use the status subresource.
* Potentially creates two new resources; a Composite Resource (XR) and a Composite Resource Claim (XRC).
* Starts controllers to reconcile the XR and XRC it defines.

While an XRD is very similar in its schema to a CRD, it attempts to paper over some of the 'implementation details' involved in authoring a CRD. CRDs are typically intended to be authored by people writing Kubernetes controllers, while XRDs are intended to be authored by people configuring Crossplane and would thus be ideally a little simpler than CRDs.

One feature of CRDs that XRDs do not currently support is defining multiple versions of the same resource. A CRD author may define multiple versions (e.g. v1beta1, v1, v2, etc) of their defined resource. The API server can serve a particular resource at many different versions simultaneously, and each version may have its own schema. To configure this, the CRD author must specify, for each version:

* A validation schema.
* Whether it is 'served' - i.e. whether the API server exposes it to callers.
* Whether it is the storage version - i.e. whether it's the one version that is serialised to etcd.

Serving multiple versions makes it possible to safely make breaking changes to a CR's schema, but doing so requires the CRD author to define a conversion strategy - a way the API server can convert from one version to another and vice versa. Currently the only way to do this is by writing a conversion webhook.

Crossplane thus far has elected not to support multiple versions when authoring an XRD - we support only one. This means the XRD author does not have to determine which version is stored, which is served, and how to convert them but comes at the expense of XRD authors being unable to make in-place breaking changes to the schema of their XRs. Making a breaking change to a Crossplane XR schema (i.e. adding a new required field) requires first deleting all instances of the defined XR, then updating the XRD, then recreating the XRs.

### How could Crossplane help solve your problem?

As we approach v1beta1 of our composition APIs, we should consider whether we want to support multiple versions and if so how XR authors would enable XRD authors to specify how conversion between different versions should happen.

**Comment by negz** [comment]
It's worth noting that if we chose not to support multiple versions it would still be possible to make backward compatible updates to XR schemas; i.e. adding new optional fields. In many cases it would also be possible - but painful - to make breaking updates to XR schemas without disruption to infrastructure by using the `deletionPolicy` and external name of each managed resource - i.e.:

1. Ensure all composed managed resources have a stable external name derived from the XR name.
1. Ensure all composed managed resources have `spec.deletionPolicy: Orphan`
1. Delete all `v1` XRs - the external resources will be retained.
1. Delete the v1 XRD
1. Create the v2 XRD
1. Recreated the v2 equivalents of the XRs deleted in step 3. External resources should be re-adopted by Crossplane.

I'm curious to get the community's take on this. I personally suspect it might be a better approach for us to support only a single version in order to make the authoring experience simpler; I wonder how many folks will need to make breaking API changes to the schema of their XRs in-place in practice.

I think if we did want to support multiple versions we'd need to invest in an easy way to configure conversion between those versions; perhaps this would be a better fit for v2 of composition?

**Comment by negz** [comment]
Interestingly [declarative conversion was considered](https://github.com/kubernetes/community/blob/3c61bb0db08277d6f23d457927d3db628dbba350/contributors/design-proposals/api-machinery/customresource-conversion-webhook.md#alternatives-considered) when webhook conversion was designed:

> This section explains why Webhooks are chosen over declarative conversion. This does not mean the declarative approach will not be supported by the webhook would be first conversion method kubernetes supports.

If we do want to support serving multiple versions of an XR simultaneously, there's a question of whether that's a required feature to call Composition v1 or something we can ship later. I think it would be unfortunate to declare the Composition APIs as v1 (e.g. `apiextensions.crossplane.io/v1`) or even v1beta1 without conversion support but then need to introduce v2 shortly afterward to make breaking changes needed to support conversion.

One way we could future proof our API here would be to allow XRD authors to specify multiple versions, but require that they use the `None` conversion strategy; i.e. allow authors to serve multiple versions at once as long as all of those versions have identical schemas. This is practically of little use to the XRD author, but allows us to support user-friendly conversion in future without breaking changes to the `CompositeResourceDefinition` API.

This would mean making a breaking change to XRD in v0.14 (presumably as part of bumping it to v1beta1). Under such a change this v1alpha1 XRD...

```yaml
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.database.example.org
spec:
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  crdSpecTemplate:
    group: database.example.org
    version: v1alpha1
    names:
      kind: CompositePostgreSQLInstance
      plural: compositepostgresqlinstances
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                required:
                  - storageGB
            required:
              - parameters
```

... would look like this:

```yaml
---
apiVersion: apiextensions.crossplane.io/v1beta1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.database.example.org
spec:
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  # Is crdSpecTemplate still an appropriate name for this
  # object if it could evolve such that it's not a strict
  # subset of a CRD spec (e.g. because we add new conversion
  # strategies in future)? Perhaps we should just inline it
  # into the XRD spec?
  crdSpecTemplate:
    group: database.example.org
    names:
      kind: CompositePostgreSQLInstance
      plural: compositepostgresqlinstances
    # Note this is a single element array, and that the
    # 'crdSpecTemplate.version' field is replaced by
    # 'crdSpecTemplate.versions[0].name'.
    versions:
      - name: v1alpha1
        # Note that the XRD author now needs to specify whether
        # this version is served (i.e. enabled) and whether it is
        # the storage version (i.e. the version saved to etcd).
        served: true
        storage: true
        validation:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  parameters:
                    type: object
                    properties:
                      storageGB:
                        type: integer
                    required:
                      - storageGB
                required:
                  - parameters
    # The XRD author can omit 'conversion.strategy' - it will
    # default to 'None'. Crossplane would not support the
    # 'Webhook' conversion strategy. In future it may support
    # a Crossplane specific conversion strategy.
    conversion:
      strategy: None
```

The XRD author could add a new `v1beta1` version to the `versions` array, but its validation schema would need to match the existing `v1alpha1` version.

**Comment by muvaf** [comment]
> I personally suspect it might be a better approach for us to support only a single version in order to make the authoring experience simpler; I wonder how many folks will need to make breaking API changes to the schema of their XRs in-place in practice.

I believe the need for making breaking API changes on XRDs is just as much as usual CRDs; user defines an API and later on they might want to introduce breaking changes. From API perspective, XRDs add a few fields, nothing destructive. From reconciliation perspective, the main difference is that in CRD case, users write their own controller which is aimed at one version (one of the served versions) and in our case we provide the controller, which again will be reconciling one version. IMO, besides from how it's implemented, the controller aspect of this comparison is not really that different. In fact, users can have their own controllers reconciling the generated CRDs alongside ours.

> If we do want to support serving multiple versions of an XR simultaneously, there's a question of whether that's a required feature to call Composition v1 or something we can ship later. I think it would be unfortunate to declare the Composition APIs as v1 (e.g. apiextensions.crossplane.io/v1) or even v1beta1 without conversion support but then need to introduce v2 shortly afterward to make breaking changes needed to support conversion.

I think we'll have to support that anyway so let's make sure to make that breaking change now before calling it v1beta1/v1.

> One way we could future proof our API here would be to allow XRD authors to specify multiple versions, but require that they use the None conversion strategy; i.e. allow authors to serve multiple versions at once as long as all of those versions have identical schemas. This is practically of little use to the XRD author, but allows us to support user-friendly conversion in future without breaking changes to the CompositeResourceDefinition API.

Future-proofing the API sounds good to me. Though the controller needs to know which version the controller should fetch from the api-server, which could be just the first element in the array if we enforce schemas of all versions be the same. But I was thinking that we can just have `spec.selectedVersion` and reconcile that one without interfering with webhook business. We'd not be affected by the conversions at all since all we'd care would be that one version and we'd support the feature fully.

**Comment by mothershipper** [comment]
From an end user perspective, I could live without multiple versions, but it would be a bit of a smell. I'd probably start including the version as part of the resource name, so I don't end up with an inconsistent `PostgresDatabase` and `PostgresDatabaseV2` resources.

**Comment by negz** [comment]
> I believe the need for making breaking API changes on XRDs is just as much as usual CRDs

I suspect this will not prove true - that there will be _less_ need to make breaking changes for XRDs compared to CRDs. While CRDs and XRDs have a lot of similarity, their purpose and audience is different.

Regarding the different audiences and purposes - CRDs are written by software maintainers to express the API of their software, which I would imagine typically is typically pretty inflexible from release to release and likely has a large user base. XRDs are written by platform builders who may not be as deeply familiar with Go, etc, Kubernetes, etc as the typical CRD author is. XRDs express the API of a more flexible configuration; i.e. a Composition that can be easily updated in place alongside the XRD. I suspect most XRDs will have a smaller audience (i.e. internal platform consumers in close communication and collaboration with the platform builder). Anecdotally, for example, breaking API changes have been rarer and less troublesome in my past experience as an internal platform operator than they have been in my experience as a Crossplane maintainer.

That all said I'm splitting hairs here. On reflection I agree that there won't be _no_ need to make breaking changes to XR schemas and that we do need leave open a path to being able to serve multiple XR versions.

**Comment by negz** [comment]
Below is my proposal for `v1beta1` XRDs. Ideally would also apply to `v1` XRDs; they would be identical.

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.database.example.org
spec:
  # Note that crdSpecTemplate is removed; its previous fields are now directly
  # inline of the XRD's spec.
  group: database.example.org
  names:
    kind: CompositePostgreSQLInstance
    plural: compositepostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  # Note that versions is now an array. At first we will require that if there
  # are multiple versions they all use the same validation schema, because we
  # will only support the 'None' conversion strategy.
  versions:
    - name: v1alpha1
      # Served has identical semantics to CRDs; i.e. if served is false the API
      # stops serving this version. This is mostly useful to easily check if an
      # API still has any users (you can set it to false, but easily set it back
      # to true if anyone complains).
      served: true
      # Composed indicates that this is the version Crossplane will use to
      # compose an XR. From a platform builder's perspective this means that all
      # Compositions must target this version. Under the hood this means that
      # Crossplane will start a controller that watches for and reconciles this
      # version. We'll also always make this version the CRD's storage version.
      composed: true
      validation:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    storageGB:
                      type: integer
                  required:
                    - storageGB
              required:
                - parameters
```

I'm hoping we don't need to expose the storage version to XRD authors:

* There's no particular relationship between the storage version and conversion. If you use a conversion webhook it must be able to convert from any version to any other version, regardless of the storage version.
* When the storage version is changed all objects will slowly converge to be stored at that version - objects are always converted to the storage version when they're written or updated. We could have Crossplane automatically update all objects whenever the storage version (i.e. composed version) changed.

Instead I'd prefer to have XRD authors think about the 'composed' version; i.e. the versions that their `Compositions` must target. If in future we implemented a declarative way to configure conversion it could use a similar 'hub and spoke' model to that used by kubebuilder (which by convention uses the storage version as the hub), using our 'composed' version as the hub.
