### ISSUE TITLE
Create Random Generator Transformer for Composition

### ISSUE THREAD

**Issue by srueg** [crossplane/crossplane#1895]
### What problem are you facing?

Using the [provider-helm](https://github.com/crossplane-contrib/provider-helm), many Helm charts require the definition of a password. If no password is defined a random one is generated by the Helm templating engine which changes on each `helm upgrade` and might break the deployed application.
Asking for the password in a `parameter` is insecure because the pw won't be stored in a secret.

### How could Crossplane help solve your problem?

By providing a random string transformer such passwords could be generated on CompositeInstance creation and then be exposed in a connection secret (together with other info).

**Comment by negz** [comment]
I like this idea, though interestingly it's not really a 'transform' since it (presumably) doesn't take any input. 🤔 

```yaml
      patches:
        - fromFn:
            type: randomString
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
```

I wonder if something like the above would make sense? We'd have to make `frontFieldPath` optional, which makes me regret that we didn't go with an API more like:


```yaml
      patches:
        - from:
            type: FieldPath  # Optional - the default. Could also be "type: Function"
            fieldPath: "metadata.uid"
            transforms:
              map:
                some-uuid: some-value
        - to:
            type: FieldPath  # Optional - the default. Could also be "type: ConnectionSecretKey"
            fieldPath: "metadata.annotations[some-key]"
```

**Comment by srueg** [comment]
You're absolutely right it's not really a transform, though it might still need some input like length and used character set. 
I guess this would also be achievable with #1506 also but might be generic enough to be implemented "in-tree"?
And #1506 could be extended to also allow custom `fromFn` implementations?

I like the proposed `fromFn` API 👍 Maybe extended with input:

```
      patches:
        - fromFn:
            type: randomString
            randomString:
              length: 32
              charset: abcdedfghijklmnopqrstABCDEFGHIJKLMNOP0123456789+*%&
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
```

**Comment by muvaf** [comment]
@srueg We got together with folks from the community to [discuss](https://crossplane.slack.com/archives/CEF5N8X08/p1623172993129900) composition changes but sort of struggled to see whether it'd be worth to implement this feature. because implementing this would require non-trivial changes to patching machinery since currently fields are patched at every reconcile, hence generate a new value.

I might be off base here, but it sounds like you're trying to create a `Secret` with generated password and then refer to that `Secret` in your `Release` object in the `Composition`. If that's what you're looking for, it might be solved on managed resource level like we did with some database [resources](https://github.com/crossplane/provider-aws/blob/master/apis/database/v1beta1/rdsinstance_types.go#L441).

So could you give more details about the issue here?

**Comment by hferentschik** [comment]
> I might be off base here, but it sounds like you're trying to create a Secret with a generated password and then refer to that Secret in your Release object in the Composition. If that's what you're looking for, it might be solved on managed resource level like we did with some database resources.

Sure, one can use the Release `set` approach and `valueFrom.secretKeyRef` to inject the secret value. However that IMO just shifts the problem. How do I generate the value for the references secret then? Then I would like to have the _ randomString_ function and use it in conjunction with the Kubernetes provider to generate a _Secret_ with a random password. 

I think it comes down to the use case. If you are in a situation where you can (re)use the same static password then you can install Crossplane and create once off a Secret and reference it. However, I have a use case where we want to use Crossplane to manage the infrastructure for multiple tenants. Crossplane would in this case create a Kubernetes cluster for each tenant and install a given Helm chart. You don't want to reuse the same password in this case, but create a random one per tenant.

@muvaf - any ideas/suggestion on how to solve the multi-tenant scenario w/o the ability to generate random passwords?

**Comment by muvaf** [comment]
What I meant was we could possibly solve the problem on managed resource level. You can have [a toggle](https://github.com/crossplane/provider-aws/blob/2b8d7c5/apis/rds/v1alpha1/custom_types.go#L167) where the controller generates and stores the password in the empty input secret you provided.

**Comment by hferentschik** [comment]
> What I meant was we could possibly solve the problem on managed resource level. You can have a toggle where the controller generates and stores the password in the empty input secret you provided.

Are you suggesting a dedicated Crossplane specific resource, something like _pgk.crossplane.io.Password_? Provided one can then patch the secret value (which might not work until there is a way to patch between any kind of objects) this could work.

**Comment by hferentschik** [comment]
> Not really. What I meant was a field on the managed resources. Let's say we target Release type of provider-helm. The following is an example where you can reference a Secret as the source of the information:

I see. That would work for the Helm Release resource I guess. However, this is a resource-specific solution and you would have to add this option to other resources as well. For example, say I want to use the Kubernetes provider to generate `Secret` directly and seed it with a random value/password. 
Another example would be the SecretVersion of the new GCP Jet provider. I love that the new jet provider contains now all GCP resources and I would love to use `SecretVersion` to seed some secrets. However, it's the same problem. How do I generate this password? 

The suggested _randomString_ function is one option. Another IMO is to have a dedicated Crossplane resource for this. Similar to the random_password resource of Terraform.

**Comment by fabioaraujopt** [comment]
This would be really useful, some of the examples here relied on the fact the provider accept some kind of "SecretRef".
However in a composition containing this resource:
```
apiVersion: cache.aws.crossplane.io/v1alpha1
kind: ReplicationGroup
spec:
  forProvider: 
     authToken: "random_token"
     ...
```

how would crossplane solve the problem?

**Comment by MisterMX** [comment]
Related to https://github.com/crossplane-contrib/provider-aws/pull/1413

**Comment by negz** [comment]
Reopened - I agree this is one that we want. I removed the "good first issue" label because we found it was trickier than we expected API and implementation wise back in https://github.com/crossplane/crossplane/pull/2308 label but anyone is still welcome to give this a shot.

**Comment by muvaf** [comment]
If we're not happy with implementing it per-resource, maybe having a new type in provider-kubernetes could make sense. Something like `GeneratedSecret` with options to change the shape of what's produced and it'd write the generated content to its connection details secret, which can be referenced by other members of the composition.

**Comment by bobh66** [comment]
We use provider-terraform to generate random values and base64 encode them, then pass them as outputs to the places they are needed.

**Comment by turkenh** [comment]
I am wondering whether this could be achieved with a composition function instead 🤔

**Comment by jaylevin** [comment]
Hi @turkenh , I can confirm that Composite Functions can be used to accomplish this. I have a working example that can be used to patch a random string into any field on a composed resource.

**Comment by jbw976** [comment]
@jaylevin did you happen to publish/share your XFN anywhere for others to reference? 😇 one possibility (for now) could be to open it as a PR to https://github.com/negz/xfns/pulls. I'm sure those will get moved to a better location eventually, but it's not a bad start 😂

**Comment by bobh66** [comment]
> We use provider-terraform to generate random values and base64 encode them, then pass them as outputs to the places they are needed.

Example is here - https://github.com/upbound/provider-terraform/pull/174

**Comment by sauldeleon** [comment]
hey @jaylevin ,any chance to get your example shared? that would be fantastic! I am facing this issue too, need to generate a password per request and I think composition is the answer, but no idea how to achieve it

**Comment by jeanduplessis** [comment]
With Composition Functions reaching beta in 1.14, we won't implement this functionality natively in Crossplane. 
Users are encouraged to create and use a function in their composition pipeline.

**Comment by JensAc** [comment]
Hey there :slightly_smiling_face: , 
I had sort of the same issue and prototyped a working example [here](https://github.com/23technologies/xp-fn-rndstr). Maybe you can try it and provide some feedback @sauldeleon? 

In any case, it would be desirable to get an idea how the entire system is supposed to work together. For me it seems to be a little compartmentalized to have a separate function for every "custom" patch/transform/generation one wants to apply. IMHO this could lead to many very similar implementations of the same thing, couldn't it?

**Comment by danielloader** [comment]
I'm guessing, and yet to check, but my guess is that if you use `randAscii` or similar sprig template functions they'll be unique every single time the composition runs - making a constant drift and reconciliation on your resulting resources. In my case since the connection strings are used as envs via envFrom secretRef, this would cause my application pods to cycle every time the composition does a cycle.

I'm happy to be wrong on this, but that's what I would assume would happen - much like how it can/does happen in helm charts that try to generate secrets for first use logins. A subsequent helm upgrade regenerates it.

**Comment by bobh66** [comment]
Generating random values in a template needs to be conditional on whether the value was already generated or not, so that it doesn't change on every reconciliation.  If the field with the random value already exists in the `.observed.resources` version of the resource, that value should be preserved for the current iteration.

**Comment by j2L4e** [comment]
You can use [the `dig` function](https://masterminds.github.io/sprig/dicts.html) to just rewrite the string if it exists or default to a random one:

```
# resource "my-resource", omitted for brevity
spec:  
  secret: {{ dig "resources" "my-resource" "resource" "spec" "secret" (randAlphaNum 12) .observed }} 
```

You could also use an if/else block to check for existence and then keep the existing string or insert a freshly generated one.

**Comment by RyanTepera1** [comment]
I was able to use the `crossplane.io/paused: "true"` annotation to stop the reconciliation of an object with a randomly generated value so that it doesn't change.
https://docs.crossplane.io/latest/concepts/managed-resources/#paused

**Comment by RyanTepera1** [comment]
> I'm guessing, and yet to check, but my guess is that if you use `randAscii` or similar sprig template functions they'll be unique every single time the composition runs - making a constant drift and reconciliation on your resulting resources. In my case since the connection strings are used as envs via envFrom secretRef, this would cause my application pods to cycle every time the composition does a cycle.
> 
> I'm happy to be wrong on this, but that's what I would assume would happen - much like how it can/does happen in helm charts that try to generate secrets for first use logins. A subsequent helm upgrade regenerates it.

From my experience this is the case. Even if you use the dig function or an if statement to check if there is a value before implementing a `randAlphaNum 12` the value just re-randomizes everytime the resource reconciles.

**Comment by j2L4e** [comment]
> to check if there is a value before implementing a randAlphaNum 12

Maybe there's a misunderstanding here. It's not enough to check, you'll also have to insert the existing value into the template instead of generating a new one.

**Comment by Moulick** [comment]
Anyone has a working example for this, which also checks if string exists before creating a new random string?

**Comment by Moulick** [comment]
This below works very cleanly for me

```yaml
pipeline:
- step: create-username-and-password-secret
  functionRef:
    name: function-go-templating
    # This is the go-templating function. This is very similar to helm, and supports the sprig functions.
    # There are a few additional functions listed https://github.com/crossplane-contrib/function-go-templating#additional-functions
  input:
    apiVersion: gotemplating.fn.crossplane.io/v1beta1
    kind: GoTemplate
    source: Inline # Also supports storing the templates on disk, like put in configmap and mount to the function.
    delims:
      # Using custom delimiters to avoid helm trying to render the curly {{/* */}} in ArgoCD.
      left: "[["
      right: "]]"
    inline:
      template: |
        [[ $claimNamespace := index $.observed.composite.resource.metadata.labels "crossplane.io/claim-namespace" ]]
        ---
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        metadata:
          annotations:
            [[ setResourceNameAnnotation "admin-credentials" ]]
        spec:
          providerConfigRef:
            name: kubernetes-provider
          managementPolicies:
            - "*"
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                # name: No need to set the name here, it will take the metadata.name of the Object
                namespace: [[ $claimNamespace ]]
              data:
                password: [[ dig "resources" "admin-credentials" "resource" "spec" "forProvider" "manifest" "data" "password" (randAlphaNum 20 | b64enc ) .observed ]]
                username: [[ dig "resources" "admin-credentials" "resource" "spec" "forProvider" "manifest" "data" "username" (randAlphaNum 20 | b64enc ) .observed ]]
          readiness:
            policy: SuccessfulCreate
        ---
```
