### ISSUE TITLE
Support `convert` transform

### ISSUE THREAD

**Issue by marcinc** [crossplane/crossplane#1914]
### What problem are you facing?

At present, provider implementations of cloud resources aren't standardized and often require a different set of parameters in the format expected by their respective upstream APIs / implementation detail. This often leads to unnecessarily elaborate composition patches. One example of such resource would be S3 and GCP bucket and how tags/labels are defined in each: 

S3 bucket:
```
spec:
  forProvider:
    tagging:
      tagSet:
        - key: tagA
          value: valA
        - key: tagB
          value: valB
```

GCP bucket:
```
spec:
  labels:
    tagA: valA
    tagB: tagB
```

### How could Crossplane help solve your problem?

Crossplane could add a support for the additional transform allowing to modify the parameter object (map) to an equivalent array of objects whereby `<key-name>: <value>` from the original object would be transformed to 
```
- key: <key-name>
  value: <value>
```

Proposed transform example (for XRD defining `tags` [object] parameter):
```
# AWS

patches:
  - fromFieldPath: "spec.parameters.tags"
    toFieldPath: "spec.forProvider.tagging.tagSet"
    transforms:
      - type: convert   # this could be also named `collect`, `object_convert` or similar... 
        keyFieldName: key
        valFieldName: value

# GCP - no need to transform here...

patches:
  - fromFieldPath: "spec.parameters.tags"
    toFieldPath: "spec.labels"
```
where, `convert` (or any other suitable name) transformer expects an object and returns an equivalent array of objects with key & value field names as specified (defaulting to "key" & "value" respectively, when none provided).

Alternatively, as it really feels like a map problem, it could extend current `map` transform potentially:
```
  - fromFieldPath: "spec.parameters.tags"
    toFieldPath: "spec.forProvider.tagging.tagSet"
    transforms:
      - type: map
        convert:
           keyFieldName: key
           valFieldName: value
```  

This would allow for more flexibility when defining XRDs and respective compositions.
