### ISSUE TITLE
Support Overriding the Image in ControllerConfig

### ISSUE THREAD

**Issue by srueg** [crossplane/crossplane#1938]
### What problem are you facing?

We have some clusters which aren't allowed to access https://hub.docker.com/ directly. They can only pull images via a registry mirror (e.g. `remote-docker.artifactory.example.com/<org>/<image>:<tag>`). The mirror acts as a pull-through cache and serves the exact same images as Docker hub.
Creating a `Provider` we can specify the correct provider image:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: remote-docker.artifactory.example.com/crossplane/provider-helm:v0.3.6
```
The provider meta config in this image references the Docker hub again though and there's currently no way to override this. The only workaround currently would be to copy the provider image and change the meta config accordingly. This imposes unnecessary image copies and maintenance though.

### How could Crossplane help solve your problem?

Using the new controller config (#974) it could be possible to override the controller image for a provider:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-helm
spec:
  image: remote-docker.artifactory.example.com/crossplane/provider-helm-controller
```
