### ISSUE TITLE
Deduplicate repeated patches within a composition

### ISSUE THREAD

**Issue by benagricola** [crossplane/crossplane#1960]
### What problem are you facing?
When creating a `Composition` with a large number of base resources, it seems common to use the same patch definitions repeatedly for settings which apply to multiple resources, for example applying the following to pretty much every base within a `Composition`:

```yaml
patches:
- fromFieldPath: metadata.labels
  toFieldPath: metadata.labels
- fromFieldPath: metadata.annotations
  toFieldPath: metadata.annotations
```

### How could Crossplane help solve your problem?

It would be really cool to allow patches to be defined once, and then referenced where necessary from each base.

@negz suggested something like this in Slack, which I like:

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  # ...
spec:
  # Sets of patches that can be referenced by id so you don't need to repeat yourself.
  patchSets:
  - id: metadata
    patches:
    - fromFieldPath: metadata.labels
      toFieldPath: metadata.labels
    - fromFieldPath: metadata.labels
      toFieldPath: metadata.labels
  - id: coolness
    patches:
    - fromFieldPath: spec.coolness
      toFieldPath: spec.amountOfCool
  resources:
  - base:
      # ...
    # Includes the patchSets above; use instead of or in addition to patches
    patchSets:
    - id: metadata
    - id: coolness
```

I'm not averse to submitting a PR to do this (on the assumption that I can work out how to implement, being relatively unfamiliar with the codebase 😄 )

**Comment by negz** [comment]
@benagricola I'm happy to work on this too, though I'm fairly slammed for the next few weeks so it might take me a while to get around to it. If you'd like to have a go feel free to ping me if you get stuck or need a review.

**Comment by benagricola** [comment]
@negz Had a bit of a poke around the code and ISTM that the difficulty here is that the `Composition` (which defines the additional `patchSets`) is not available during the `Render()` method of the composed resource. 

My first idea to work around this is to load the `PatchSet` list into the composite resource (`cp resource.Composite`) using a new Configurator. The `PatchSet` list can then be retrieved in the `Render()` method and used to apply the patches.

Because the composite resource (actually `Unstructured`) is in `crossplane-runtime`, it seems to make sense to not add patching code there, but I could create a new extended resource type in `crossplane` which embeds `resource.Composite` and applies the relevant additional methods.

Does this sound sane to you or am I missing something that would make this simpler? 

The other option I could think of is to try and load the Composition from the API during `Render()`, but that would involve an API call for each resource - which seems wasteful if the necessary data can be injected directly on creation of the composite resource.

**Comment by negz** [comment]
@benagricola If I recall correctly we pass the `ComposedTemplate` (which is part of the `Composition`, which we have in the reconciler) to `Render()`, which includes the `patches` array (and presumably would include the array of `patchSets` the resource wanted to include too). 

https://github.com/crossplane/crossplane/blob/8f840d9ddf43662fe10c1ca14edf5e3e222e9a43/apis/apiextensions/v1alpha1/composition_types.go#L83

What do you think about passing the array of available patchsets to `Render` too, so that it can include those the `ResourceTemplate` wants?

**Comment by muvaf** [comment]
I feel like, in practice, the patchsets here would be mostly either Kubernetes or Crossplane fields unless there are many of the same kind of resources in the `resources` array. Because most of the resources have unique sets of parameters in `forProvider` section with very few exceptions, like `region`. @benagricola how do you feel about needing this functionality for more than `labels` and `annotations`? Do you have some use cases in mind where you had to write the same patchset for many resources in the same `Composition` for fields other than those two?

An alternative could be to have `Labels` and `Annotations` as hard-coded patch types, similar to transforms, with no other field required, like:
```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  # ...
spec:
  resources:
  - base:
      # ...
    # Reuse the patches array we already have.
    patches:
    - type: Labels
    - type: Annotations
```

**Comment by benagricola** [comment]
@negz thanks, that was the context I was looking for - somehow skipped over where the composed resource is created and then passed directly to the `Render()` method 😂 - that looks like it'd be much simpler.

@muvaf Yeah, those were examples I chose because they apply to everything, but you're right - they're likely to be identical or very similar across the board.

Another example I can think of where predefined patch types wouldn't work is one of my XRD's which generates 2 namespaces, where the name of the namespace created and then used by other resources within the XRD is determined by an input value (e.g. claim name or instance name + transform).

I think predefined patch types is a great idea as well, but if there's any need to transform one of those super common fields then I don't think they'll suffice, unless they were also configurable, which I think is covered more succinctly with the custom `patchSet` / `patchType` idea.

I like the interpolated `type: ...` field using the existing `patches` field though - maybe something like the below works?

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  # ...
spec:
  patchTypes:
  - type: CustomNS
    patches:
    - fromFieldPath: spec.parameters.blah
      toFieldPath: metadata.namespace
      transforms:
      - type: string
        string:
          fmt: "custom-%s"
  resources:
  - base:
      # ...
    # Reuse the patches array we already have.
    patches:
    - type: Labels
    - type: Annotations
    - type: CustomNS
    - fromFieldPath: spec.parameters.myField
      toFieldPath: spec.forProvider.locationConstraint
    # ...
```

**Comment by muvaf** [comment]
Yeah, that looks good to me. We'd not make the UI more complex for users who don't need that functionality while providing it to who need it.

**Comment by benagricola** [comment]
Hmm, thinking about this style more, it actually seems to be conflating `patchTypes` (which I copied from `patchSets` above) with a patch entry in the base resource, which right now refers to a single patch.

Should a `patchType` defined on the composition only define a single 'named' patch, which can then be referenced multiple times (but each patch must be referenced individually on each resource)?

Or should `patches` on the base resource refer to either a single unnamed patch (with relevant fields set) or a patch type consisting of a list of `patches`?

Keeping each `patchType` as a single patch identified by name seems the simplest, but means that applying the same set of named patches in order to each resource becomes repetitive.

**Comment by benagricola** [comment]
https://github.com/benagricola/crossplane/commit/fa4af7203f583f11aba95a09050157dba7d04fa5 WIP implementation of `patchType` as a single patch rather than a list of patches. Seems pretty succinct code-wise. Needs doc, more tests and some bits and pieces moved around before PR / review.

If we wanted types to be a list of patches rather than individuals, then I think we'd need to go the previous route and add a new field to the `ComposedTemplate` to avoid affecting the  existing `Patches` functionality. But I think for my use case at least, individual patches is enough deduplication for this to be a useful feature.

**Comment by negz** [comment]
I agree that fixed/built in patch sets probably aren't the way to go here - I suspect we'll appreciate a more flexible approach in future. I do like the `type` approach though, as it opens us up for other types of patches (e.g. "reverse" patches from the composed resource to the composite resource). I think it could work together with the `patchSets` approach. Something like:


```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  # ...
spec:
  patchSets:
  - id: CustomNS
    patches:
    - fromFieldPath: spec.parameters.blah
      toFieldPath: metadata.namespace
      transforms:
      - type: string
        string:
          fmt: "custom-%s"
  resources:
  - base:
      # ...
    # Reuse the patches array we already have.
    patches:
    - type: PatchSet
      id: CustomNS
    - type: FieldPath  # Or just 'Patch'? This would be the default type, if omitted.
      fromFieldPath: spec.boop
      toFieldPath: spec.doop
```

**Comment by benagricola** [comment]
I've managed to get the format pretty similar to the above:

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  # ...
spec:
  # ...
  patchSets:
    - id: metadata
      patches:
      - fromFieldPath: metadata.labels
        toFieldPath: metadata.labels
    - id: parameters
      patches:
      - fromFieldPath: spec.parameters.location
        toFieldPath: spec.forProvider.locationConstraint
        transforms: {} # ...
      - fromFieldPath: spec.parameters.namePrefix
        toFieldPath: metadata.generateName
        transforms:
          - type: string
            string:
              fmt: 'added-by-parameters-set-%s'
  resources:
    - base:
        # ...
      patches:
        - type: ref
          id: metadata
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - type: ref
          id: parameters
```

Types are currently `ref` and `std` (implied) - can rename these of course.

`patchSets.patches` and `resource.patches` both use the same type definition (`[]Patch`) but an error will be thrown if someone attempts to use a reference type patch from within the `patchSets` definition.

I'll double check everything and submit a PR for review later today.
