### ISSUE TITLE
Composition transform patch: Introduce a way to getValues from an array of fieldPaths

### ISSUE THREAD

**Issue by rozcietrzewiacz** [crossplane/crossplane#1973]
### What problem are you facing?
Currently the `string` transform allows a single placeholder substitution in the `fmt` string. This allows pre-/in-/suffixing. Here's a use case where it would make more sense to consume a list of input `fromFieldPaths` for subsequent `%s` placeholders.

Consider a Composition that provisions an s3 bucket on AWS along with a set of IAM objects that reference it, resulting in a tight IRSA setup:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: irsabuckets.xxx.com
  namespace: crossplane-system
spec:
  compositeTypeRef:
    apiVersion: xxx.com/v1alpha1
    kind: IRSABucket
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
      patches:
      - fromFieldPath: "spec.parameters.region"
        toFieldPath: "spec.forProvider.locationConstraint"
    - base:
        apiVersion: identity.aws.crossplane.io/v1beta1
        kind: IAMRole
        spec:
          forProvider:
           assumeRolePolicyDocument: |
                 {
                   "Statement": [
                     {
                       "Action": "sts:AssumeRoleWithWebIdentity",
                       "Condition": {
                         "StringLike": {
                           "oidc.eks.AWS_REGION.amazonaws.com/id/XXXXX:sub": "system:serviceaccount:NAMESPACE:BUCKETNAME-access"
                         }
                       },
                     "Effect": "Allow",
                     "Principal": {
                       "Federated": "arn:aws:iam::AWS_ACCOUNT:oidc-provider/oidc.eks.AWS_REGION.amazonaws.com/id/XXXXX"
                       },
                     "Sid": ""
                     }
                   ],
                   "Version": "2012-10-17"
                 }
    - base:
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMPolicy
        patches:
        # (construct the policy document in the similar manner to th eIAMRole)
    - base:
        apiVersion: identity.aws.crossplane.io/v1beta1
        kind: IAMRolePolicyAttachment
        # (...)
```

In order to fill in all the necessary fields in `Policy` and `Role` documents, one would need to either use external templating (with Helm for example) or wrestle with some weird stack of partial patches. 

### How could Crossplane help solve your problem?
By having an array equivalent of  `fromFieldPath`

**Comment by rozcietrzewiacz** [comment]
https://github.com/crossplane/provider-aws/issues/315 Would allow to work around the issue in case of `IAMPolicy`. One could go the route of serializing all supported json documents in various resources... And that would probably be the cleanest way to do it, once all those document fields are supported in all providers. But until that is done, having multiple `%s` in a `fmt` string would unlock a lot of potential.

**Comment by negz** [comment]
This should be doable, but I suggest we add a `type` field to help make the Composition author's intent clear when they could be specifying either `fromFieldPath` or `fromFieldPaths`. We have to leave the former in place in order to maintain backward compatibility.

I'm thinking something like:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: Example
  resources:
    - base:
        # ...
      patches:
      - type: FromCompositeField  # Today's behaviour. The default if type is omitted.
        fromFieldPath: "spec.parameters.region"
        toFieldPath: "spec.forProvider.locationConstraint"
      - type: FromCompositeFields
        fromFieldPaths:
        - "spec.parameters.someField"
        - "spec.parameters.otherField"
        toFieldPath: "spec.forProvider.exampleField"
        transforms:
        - type: SomeTransformThatCombinesManyFields
```

I believe this API change would be compatible with https://github.com/crossplane/crossplane/issues/1639, which could be a different `type` - e.g.:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: Example
  resources:
    - base:
        # ...
      patches:
        # The reverse of today's behaviour; patch from the composed to the composite.
      - type: FromComposedField
        fromFieldPath: "status.atProvider.cidr"
        toFieldPath: "status.cidr"
```

**Comment by rozcietrzewiacz** [comment]
@negz Absolutely. How about having the following set of types (could be added over time): `OneToOne` (default), `OneToMany`, `ManyToOne` (case at hand) ?

**Comment by negz** [comment]
@rozcietrzewiacz I think we need to pick types that will accomodate a small handful of use cases we have. I've written up the ones I know of in https://github.com/crossplane/crossplane/issues/1974.

> OneToMany

Do we need to cover this case? Wouldn't it be functionally the same as including multiple patches that each patch from the same XR field, but patch to different composed resource fields?

**Comment by rozcietrzewiacz** [comment]
> > OneToMany
>
> Do we need to cover this case? Wouldn't it be functionally the same as including multiple patches that each patch from the same XR field, but patch to different composed resource fields?

I agree, it looks like a minor optimization and I don't think there would be much demand for it - so I would leave it out at least in first api update. But some day, with the growth of provider base and use cases, someone might find it really useful. I mentioned it merely for completeness, also to justify the simple naming pattern.

**Comment by benagricola** [comment]
Was having a think about this earlier as I have the same specific problem as @rozcietrzewiacz RE: IRSA in an EKS cluster, and ISTM that there's some unknowns that would need to be cleared up around how a 'many to one' patch type (`FromCompositeFieldPaths`?) would work.

1) What happens if one or more of the `From` fields are not set? Gut says that most use-cases for this revolve around patching multiple values into a template (using a string Transform), and without all of the values that template is likely to be invalid (missing values for placeholders would cause error markers from `Sprintf`). Should it behave like `FromCompositeFieldPath` and just not apply the patch (with no error) if one of the `From` fields doesn't exist?

2) `FromCompositeFieldPath` currently defaults `ToFieldPath` to `FromFieldPath` if not set. For multiple `From` fields it seems like there's no safe assumption there, so `ToFieldPath` should be mandatory.

3) At what point should Transforms be applied? For the above use-case, it makes sense for the list of values retrieved from the `From` fields to be passed to the Transform as one, with the string transform then deciding what to do with its' list of input values (just passing them to `Sprintf`), but what about the other transforms, e.g. Math.multiply on a list of numbers?, or `Map` on multiple values? (or are these simply invalid and should not be possible?)

4) What is sane default behaviour, does passing a list and formatting it as comma separated strings make sense?

**Comment by benagricola** [comment]
Name suggestion: `FromMultipleCompositeFieldPaths` or something similar to avoid confusion with the other patch types. 

Implementation of the actual patch method seems simple, but introduces a chunk of complexity around how transforms are applied.

Based on the above discussion around `OneToMany`, it seems safe to assume that patches will only target a single destination field, which means a multiple-input-value patch type needs to combine all of its' input values into a single output value at some point during processing - either when the user decides with particular `Transform` configuration, or based on the last `Transform` in the patch, or using a default `Transform` if none are supplied.

ISTM that the last transform on a patch could be important. If that last transform is passed more than one input value, then it _must_ be able to combine them into a single output value. If there are no transforms defined on the patch, then I think we need to either apply a default transformation to combine all of the values, or error (`FromMultipleCompositeFieldPaths returned multiple values`). Example:

```yaml
# Example 1
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  resources:
    - base:
        apiVersion: identity.aws.crossplane.io/v1beta1
        kind: IAMRole
      patches:
      - type: FromMultipleCompositeFieldPaths
        fromMultipleFieldPaths:
          # Paths have to be repeated if field is required multiple times
          - spec.parameters.awsAccountId
          - spec.parameters.eksClusterRegion
          - spec.parameters.eksClusterId
          ...
          - spec.parameters.serviceAccount
        toFieldPath: spec.forProvider.assumeRolePolicyDocument
        transforms:
          - type: string
            # When combine set, all values will be passed to `Resolve` method in 
            # one go as []interface{}, and the transform will return a single 
            # interface{} value.
            # When unset, `Resolve` will be called with interface{} for each input
            # value, and the transform will return []interface{}.
            # If combine is unset but transform is last in list, combine can either
            # be automatically set to force a single output value, or an error
            # thrown to indicate an invalid config.
            combine: true
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::%s:oidc-provider/oidc.eks.%s.amazonaws.com/id/%s"
                      },
                      "Action": "sts:AssumeRoleWithWebIdentity",  
                      "Condition": {
                        "StringLike": {
                          "oidc.eks.%s.amazonaws.com/id/%s:sub": "system:serviceaccount:%s"
                        }
                      }
                    }
                  ]
                }
```

However - a user might want to combine multiple values _prior_ to the final transform, something like this:

```yaml
# Example 2
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  resources:
    - base:
        apiVersion: database.example.io/v1beta1
        kind: AppInstance
      patches:
      - type: FromMultipleCompositeFieldPaths
        fromMultipleFieldPaths:
          - spec.parameters.maximumGlobalMemoryMb
          - spec.parameters.maximumMemoryRedisMb
        toFieldPath: spec.forProvider.appConfig
        transforms:
          - type: math
            multiply: 1024 # Multiply each input value by this
          - type: math
            combine: subtract # Subtract multiplied input 2 from input 1
          - type: string
            string:
              fmt: "memoryLimitKb=%d"
```

Or rather than the existing transforms supporting combination (which they may not, for example the `convert` transform), should this be the job of a new `combine` transform that implements different combine methods?

```yaml
# Example 1 w/ Combine transform
transforms:
  - type: combine
    combine: string.fmt # Format multiple values to single
    string:
      fmt: "%s/%s/%s...."

# Example 2 w/ Combine transform
transforms:
  - type: math
    multiply: 1024 # Multiply each input value by this
  - type: combine
    combine: math.subtract # Subtract multiplied input 2 from input 1
  - type: string
    string:
      fmt: "memoryLimitKb=%d"
```

**Comment by benagricola** [comment]
I've implemented the multiple-source patch type and a transform that allows multiple values to be combined - but it's currently implemented as a single `Transform` that could then have other `Combine` methods underneath it, like this:

```yaml
transforms:
  - type: combine
    combine: string
    string:
      fmt: "%s/%s"
  ...
  - type: combine
    combine: math
    math:
      operation: multiply
  ...
```

But I think it might be simpler if each `Combine` action is just implemented as a new `Transform` type:

```yaml
transforms:
  - type: combine-string
    string:
      fmt: "%s/%s"
  ...
  - type: combine-math
    math:
      operation: multiply
```

For some combine actions that means we can use the existing Transform structs, and makes each transform object a little simpler. Thoughts?

**Comment by negz** [comment]
@benagricola I wonder if there's some way this could play with the patch set you recently added?

I need to write up the issues, but one thing we've heard some demand for and are considering is patching from some common useful sources that aren't part of the Composition - thing things like `type: FromConfigMap`, `type: FromSecret`, or `type: FromNamespace`. If we do implement these I could see folks wanting to potentially do things like "grab this field from the XR, this field from a ConfigMap, and this field from a Namespace annotation and merge them all together". I'm wondering if there's some way we could merge multiple distinct patches.

**Comment by benagricola** [comment]
> I'm wondering if there's some way we could merge multiple distinct patches.

A sort of.... patch of patches? I could see that working, yeah, something like a `PatchSet` but instead of applying the individual patches to an output field, patch them to a temporary location, with some sort of 'patch of patches' setting to control how they're combined?

Transforms on the 'sub patches' apply as usual to massage individual values, a combine setting is used to control how the individual values are combined (reduced?) and in theory, a transform setting on the 'patch of patches' could be used to massage the final value.

Just riffing here:

```yaml
  resources:
    - base:
        apiVersion: v1
        kind: Secret # Lazy testing, should not use native resources
        metadata:
          namespace:
        type: kubernetes.io/opaque
        data: {}
      patches:
        - type: PatchSet
          patchSetName: Metadata

        # New FromMultiplePatches type
        - type: FromMultiplePatches
          toFieldPath: spec.forProvider.appConfig
          patches:
            - fromFieldPath: metadata.annotations["foo"]  # Value bar
              transforms:
                - type: map
                  map:
                    bar: "baz" # Output value baz
            - type: FromConfigMap
              fromConfigMap: ConfigMapName
              configMapKey: fieldTwo # Value fromConfigMap
            - type: FromSecret
              fromSecret: SecretName
              secretKey: fieldThree # Value fromSecret
          combine:
            string:
              fmt: |
                Annotation Value: %s
                ConfigMap Value: %s
                Secret Value: %s
          transforms:
            - ...
```

**Comment by benagricola** [comment]
Okay. I think implementing this directly on `PatchSet` would indeed make this nice and clean:

### Sketch

```yaml
patchSets:
  ...
  - patchSetName: CombineFields
    patches:
      - fromFieldPath: spec.parameters.fieldOne
      - fromFieldPath: spec.parameters.fieldTwo
        transforms:
          ...
    combine:
      type: string
      string:
        fmt: "%s / %s"
resources:
  - base:
      apiVersion: v1
      kind: ...
      metadata:
        namespace: ...
    patches:
      - type: PatchSet
        patchSetName: Metadata

      - type: PatchSet
        patchSetName: CombineFields
        toFieldPath: spec.forProvider.combinedField
        transform:
          ...
```

### Implementation

1. During `InlinePatchSets()`, check if each `PatchSet` has a `Combine` set. If it does, either:
   - Override the `ToFieldPath` of each patch with a constant, or 
   - Introduce an additional field on `Patch` that tells the patch to apply to a temporary location
2. Append each `PatchSet` to the list of patches, if they have a `Combine` set - after dereferencing their member patches.
3. During `Render()`, create a new temporary variable (`*[]interface{}`) which is passed as a third argument to `p.Apply()`.
4. When running `p.Apply()` on a 'normal' patch type, we should use whatever option is chosen in 1. to decide whether to patch to `toFieldPath`, or simply store the value in the temporary location.
5. Add an `applyFromPatchSet()` method which will combine the values that are available in the temporary location, and then reset the temp variable (so multiple `PatchSets` with `combine` can be used).

The only 2 parts here I'm a little unsure of are the options in 1. and the 'temporary storage' in 3. - are these safe? Will rewriting `ToFieldPath` cause a change to the API resource? 

### Benefits
 - `PatchSet` can define a list of _source_ fields on the `Composition`, but we can use the  existing `toFieldPath` when the `PatchSet` is referenced to allow the same value to be combined into different resources / fields.
 - We can still use transforms on the individual patches, and potentially on the combined value as well.

**Comment by benagricola** [comment]
I've implemented the above here: https://github.com/crossplane/crossplane/compare/master...benagricola:Multi-Source-PatchSet - it seems to work well, with my manual testing, and original + new tests pass. 

Not entirely convinced by using `toFieldPath` to communicate the 'temporary' nature of the patch though 🤔

**Comment by muvaf** [comment]
It seems that we somehow need to make sure that all transforms need to be compatible with multiple inputs. What would you think about having this as a `transform` type? This way we'd not have to worry about other transforms or patch types because the logic would be contained in the lowest level, `transform`. For example:
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: irsabuckets.xxx.com
  namespace: crossplane-system
spec:
  compositeTypeRef:
    apiVersion: xxx.com/v1alpha1
    kind: IRSABucket
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
      patches:
      - fromFieldPath: "spec.parameters.region"
        toFieldPath: "spec.forProvider.locationConstraint"
    - base:
        apiVersion: identity.aws.crossplane.io/v1beta1
        kind: IAMRole
        spec:
          forProvider:
           assumeRolePolicyDocument: |
                 {
                   "Statement": [
                     {
                       "Action": "sts:AssumeRoleWithWebIdentity",
                       "Condition": {
                         "StringLike": {
                           "oidc.eks.%s.amazonaws.com/id/XXXXX:sub": "system:serviceaccount:%s:%s-access"
                         }
                       },
                     "Effect": "Allow",
                     "Principal": {
                       "Federated": "arn:aws:iam::%s:oidc-provider/oidc.eks.%s.amazonaws.com/id/XXXXX"
                       },
                     "Sid": ""
                     }
                   ],
                   "Version": "2012-10-17"
                 }
      patches:
      - fromFieldPath: "spec.forProvider.assumeRolePolicyDocument"
        toFieldPath: "spec.forProvider.assumeRolePolicyDocument"
        transforms:
        - type: fmt
          fmt:
            values:
            - fromFieldPath: "somefield"
            - fromFieldPath: "some.other.field"
            - fromFieldPath: "lots.of.fields"
```

**Comment by benagricola** [comment]
> It seems that we somehow need to make sure that all transforms need to be compatible with multiple inputs. What would you think about having this as a `transform` type? This way we'd not have to worry about other transforms or patch types because the logic would be contained in the lowest level, `transform`. For example:
> ...

@muvaf I may be misunderstanding your example sketch but it looks like the `fmt` transform would be able to retrieve values, like a patch does currently? 

It almost looks like the `values` field is a `PatchSet` that is automatically reduced to a single value based on the settings passed to the `fmt` transform.

Would that involve implementing lookup functionality in both places? e.g. if I wanted to look up a value from a `ConfigMap` and the `Composition`, would I need to implement a new patch type as well as lookup functionality in the transform?

I suppose Patches could implement a `Lookup()` method or something similar so this could be used in both places (and by the existing Apply()` method).

**Comment by benagricola** [comment]
> @benagricola I wonder if there's some way this could play with the patch set you recently added?
> 
> I need to write up the issues, but one thing we've heard some demand for and are considering is patching from some common useful sources that aren't part of the Composition - thing things like `type: FromConfigMap`, `type: FromSecret`, or `type: FromNamespace`. If we do implement these I could see folks wanting to potentially do things like "grab this field from the XR, this field from a ConfigMap, and this field from a Namespace annotation and merge them all together". I'm wondering if there's some way we could merge multiple distinct patches.

@negz I was just revisiting the PatchSet implementation based on your comment and I think with #2077 potentially changing the _direction_ of one or more patches within a set, it isn't viable to use a `PatchSet` as the source of multiple values anymore.

Happy to focus on getting #2093 into a mergeable state if there's agreement that the approach makes sense.

**Comment by muvaf** [comment]
> I may be misunderstanding your example sketch but it looks like the fmt transform would be able to retrieve values, like a patch does currently?

Yes, we could probably reuse some structs there to make this easier. The retrieval would be contained in the transform's resolve function. What I want to achieve is to have only the transforms that are designed to work with multiple values implement multiple input mechanisms as opposed to having to make sure all transforms work with multiple inputs or to make them compatible with some compromises in our API. @benagricola Do you think this could work?

**Comment by benagricola** [comment]
> Yes, we could probably reuse some structs there to make this easier. The retrieval would be contained in the transform's resolve function. What I want to achieve is to have only the transforms that are designed to work with multiple values implement multiple input mechanisms as opposed to having to make sure all transforms work with multiple inputs or to make them compatible with some compromises in our API. @benagricola Do you think this could work?

I don't think value retrieval in transforms is a particular concern, except all of the existing patch types already retrieve values themselves, and having value retrieval in two places might be confusing. 

The separation between patches being 'get and set values' and transforms being 'pipeline to modify values between get and set' is relatively clear right now.

With additional patch types that do _not_ directly retrieve values themselves then I think transforms capable of value retrieval could have more merit.

In the example you have `fromFieldPath: "spec.forProvider.assumeRolePolicyDocument"` - it looked like the intention was to read that static value from the field on the base resource the patch was being applied to; but we don't have a patch type that is capable of that yet (we either read -> set from composite to composed or from composed to composite, never between fields on the same resource afaict). 

In that case I could see a `Constant` patch type (that just takes an input value - #2013) being of use, with the addition of value retrieval in the transforms.

My work on #2093 implements this without any behaviour change to the existing transforms on single values, and does not change the existing transform API.

The only change to the transforms themselves is that they _can_ accept multiple values, and can choose to either transform each value individually, or perform some sort of consolidation or reduction method on them, if necessary (currently only `string.fmt` does this). This leaves the door open for additional transform types e.g. using `strings.Join`. 

The multi-source patch type can be used as follows, which I think is relatively clear:

```yaml
 - type: FromManyCompositeFieldPaths
  # Retrieve two values from XRD parameters
  fromManyFieldPaths: 
    - spec.parameters.fieldOne # value = "one"
    - spec.parameters.fieldTwo # value = "two"
  toFieldPath: metadata.annotations["description"]
  transforms:
    - type: map      # Map each value to another value
      map:           # ["one","two"] -> ["1","2"]
        one: "1"
        two: "2"

    - type: string   # Format all values into a single output
      string:        # ["1","2"] -> "Field One: 1 - Field Two: 2" 
        fmt: "Field One: %s - Field Two: %s"
```

Note that you could do the same with a single-value patch type using almost exactly the same transform pipeline, which I think is pretty intuitive:

```yaml
 - type: FromCompositeFieldPath
  # Retrieve one value from XRD parameters
  fromFieldPath: spec.parameters.fieldOne # value = "one"
  toFieldPath: metadata.annotations["description"]
  transforms:
    - type: map      # Map field value to another value
      map:           # "one" -> "1"
        one: "1"
        two: "2"

    - type: string   # Format value into output
      string:        # "1" -> "Field One: 1" 
        fmt: "Field One: %s"
```
