### ISSUE TITLE
Introduce composition patch types.

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1974]
### What problem are you facing?

Crossplane Compositions consist of an array of 'base' resources, each with an array of zero or more patches. Currently these patches support patching from a field path within an XR to a field path within the base (composed) resource. Each patch may also include zero or more simple transforms. Currently `fromFieldPath` and `toFieldPath` are required fields.

For example:
```yaml
# ...
resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          forProvider:
            acl: private
            locationConstraint: unknown
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: aws:kms
        patches:
          - fromFieldPath: metadata.annotations
            toFieldPath: metadata.annotations
            transforms:
            - # ...
```

Since this API was introduced we've identified a handful of features that could fit as part of the `Patch` struct (the type that represents an entry in the `patches` array). These include:

* https://github.com/crossplane/crossplane/issues/1960 - Allowing references to sets of predefined patches.
* https://github.com/crossplane/crossplane/issues/1639 - Patching from a composed resource back to the XR.
* https://github.com/crossplane/crossplane/issues/1973 - Mapping an array of 'from' field paths mapped to a single 'to' path.

Supporting all of these functions would likely mean making all or most of the `Patch` struct fields optional, and relying on the user to set the appropriate fields for their use case (e.g. don't set both `fromFieldPath` and `fromFieldPaths`). It's good practice in Kubernetes API design to use a "differentiator" field (often called `type`) to allow the user to clearly specify their intent when they intend to set a subset of optional fields. For example:

```yaml
patches:
# The user wants to patch from one field of the XR to one field of
# the composed resource.
- type: FromCompositeField
  fromFieldPath: spec.parameters.foo
  toFieldPath: spec.forProvider.bar
# The user wants to include a patch set; this type lets Crossplane
# know that it's okay for them to omit the field paths, but that they
# must include an id.
- type: PatchSet
  id: CustomNS
```

I'd like us to consider the use cases we're aware of today before we introduce the patch `type` field, to increase the chances we pick a future proof naming scheme.

### How could Crossplane help solve your problem?

We could sketch out some example YAML that covers the above use cases in order to arrive at a user friendly and extensible set of patch types!

Here's a straw man example:

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  name: example 
spec:
  # ...
  patchSets:
    - id: labels
      # Note that these patches can have a type too.
      patches:
      - fromFieldPath: metadata.labels
        toFieldPath: metadata.labels
  resources:
    - base:
        # ...
      patches:
        # A reference to the above patchset with id 'metadata'
        - type: PatchSet
          id: labels
        # The functionality we have today - this type is the default
        # when the type is omitted.
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        # Patches from many composite fields to one composed field,
        # combining them using some kind of transform (maybe a
        # simple concatenation by default?)
        - type: FromCompositeFieldPaths
          fromFieldPaths:
          - metadata.annotations[namespace]
          - metadata.annotations[name]
          toFieldPath: metadata.annotations[namespacedname]
          transforms:
          - type: String
            fmt: "%s/%s"
        # The inverse of today's behaviour; patches from the composed
        # resource back to the composite.
        - type: FromComposedFieldPath
          fromFieldPath: status.atProvider.widgets
          toFieldPath: status.widgetCount
```

**Comment by benagricola** [comment]
Just while it's front-of-mind with `type: FromCompositeFieldPaths` - I wonder if there's a situation here where rather than using _all_ fields, you might want to pick the first field that exists or isn't empty, and whether that's a different patch type or another setting on `FromCompositeFieldPaths` :)

**Comment by negz** [comment]
@benagricola I'd probably go with another type there, perhaps something like `FromFirstNonEmptyCompositeFieldPath` if that's not too verbose.

**Comment by muvaf** [comment]
We've had a lengthy discussion in https://github.com/crossplane/crossplane/pull/1972#discussion_r528726387 related to this issue. I'm copying my proposal here since it's related:
```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
spec:
  customPatches: # The struct here has 'name' field and inlined patch struct.
  - name: Metadata
    resourcePatchList: # The mechanism of the patch is identified by the field used here.
    - fromFieldPath: metadata.labels
    - fromFieldPath: metadata.annotations
  - name: Location
    resourcePatch:
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.locationConstraint
resources:
- base:
   # ...
  patches:
  - customPatchRef: # One of patch types in the patch struct.
      name: Metadata
  - customPatchRef:
      name: Location
  - compositePatch: # compositePatch means we're patching the composite, it's a type of patch.
      fromFieldPath: status.atProvider.ARN
      toFieldPath: status.rdsARN
  - resourcePatchList: # resourcePatchList is a list of resource patches where composed is patched.
    - fromFieldPath: spec.size
      toFieldPath: spec.forProvider.dbSize
```

**Comment by negz** [comment]
@muvaf It looks like your proposal above contains a list of objects under the `patches` array, each with a different key set (e.g. `customPatchRef` or `compositePatch`).

Each entry in patches needs to be an object, and that object had a corresponding Go type it would need to have all of the `customPatchRef`, `compositePatch`, and `resourcePatchList` fields. When this happens in the Kubernetes API (and polymorphic APIs in general) [it's considered](https://github.com/kubernetes/kubernetes/issues/35345) [good practice](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) to use a discriminator field (often named `type` or `fooType`) to make which object key is the expected to set explicit (i.e. whether to expect `customPatchRef`, or `resourcePatchList`). I don't think this proposal negates the need for a `type` field. Nor do I think we should be _trying_ to negate the need for a `type` field.

It's also worth noting that this proposal appears to be backward incompatible. I think we'd need to move things up to the same level as `patches` to be compatible, e.g:

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
spec:
  customPatches: # The struct here has 'name' field and inlined patch struct.
  - name: Metadata
    resourcePatchList: # The mechanism of the patch is identified by the field used here.
    - fromFieldPath: metadata.labels
    - fromFieldPath: metadata.annotations
  - name: Location
    resourcePatch:
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.locationConstraint
resources:
- base:
   # ...
  patches:
  - # Regular patches as they exist today
  customPatches:
  -   name: Metadata
  compositePatches:
  -  fromFieldPath: status.atProvider.ARN
     toFieldPath: status.rdsARN
  resourcePatches:
   - fromFieldPath: spec.size
     toFieldPath: spec.forProvider.dbSize
```

Given that we're using a `type` discriminator field already in several places (e.g. the transforms array and the provider config credentials type) I think we should continue to do so here, rather than offering several arrays of similar-but-different concepts.

**Comment by negz** [comment]
I just did a bit of a survey of the Kubernetes API looking for instances of discriminator fields - they include the Deployment strategy, HPA metric source and targets, and Service type. I believe the reason they're not present in older parts of the API (e.g. volume source, env var source) is because there has historically been some controversy as to whether adding them would constitute a breaking API change. According to [the Unions KEP](https://github.com/kubernetes/enhancements/blob/65dc03a1e1436e2b1193c998a8cbf4f844f921b7/keps/sig-api-machinery/20190325-unions.md#discriminator) it seems that the plan is to introduce them:

> For backward compatibility reasons, discriminators should be added to existing union structures as an optional string. This has a nice property that it's going to allow conflict detection when the selected union field is changed. We also do strongly recommend new APIs to be written with a discriminator, and tools (kube-builder) should probably enforce the presence of a discriminator in CRDs.

**Comment by muvaf** [comment]
Thanks for references! I agree with Tim here https://github.com/kubernetes/kubernetes/issues/35345#issuecomment-275834360 . However, I see that the [KEP](https://github.com/apelisse/enhancements/blob/c192aeb95be857b79d997a54e1b8bf7beac62c67/keps/sig-api-machinery/20190325-unions.md) you linked for discriminators is accepted and there is an effort to migrate the existing APIs. So, Kubernetes community decided in favor of discriminators and since we're strictly following that, having the discriminators should be the way to go.

> I just did a bit of a survey of the Kubernetes API looking for instances of discriminator fields - they include the Deployment strategy, HPA metric source and targets, and Service type.

Keep in mind that the discriminators are not used the same way in your [initial suggestion](https://github.com/crossplane/crossplane/issues/1974#issue-746074026) where all configuration fields live at the same level with `type`. If the chosen type needs to be configured, it has its own field.

```yaml
# Deployment
spec:
  replicas: 3
  strategy:
        type: RollingUpdate
        rollingUpdate: # Each type gets its own field because each has its own configuration parameters.
           maxSurge: 25%
           maxUnavailable: 25%  
...
# HPA
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
...
# Service
spec:
  type: NodePort
  selector:
    app: echo-hostname
ports:
    - nodePort: 30163
      port: 8080 
      targetPort: 80
# Our transform
patches:
  - fromFieldPath: "metadata.uid"
    toFieldPath: "spec.writeConnectionSecretToRef.name"
    transforms:
      - type: string
        string:
          fmt: "%s-postgresql"
```

What this would look like in our case is something like the following:
```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
spec:
  customPatches:
# fwiw, name is recommended over id whenever uniqueness is limited. see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture
# and I think we should use name over id if the value is human-written rather than machine-generated.
  - name: Metadata /identifiers.md#objectives-for-names-and-uids
    type: ResourcePatchList
    resourcePatchList:
    - fromFieldPath: metadata.labels
    - fromFieldPath: metadata.annotations
  - name: Location
    type: ResourcePatch
    resourcePatch:
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.locationConstraint
resources:
- base:
   # ...
  patches:
  - type: CustomPatch
    customPatchName: Metadata # or customPatch.name
  - type: CustomPatch
    customPatchName: Location
  - type: CompositePatch
    compositePatch:
      fromFieldPath: status.atProvider.ARN
      toFieldPath: status.rdsARN
  - type: ResourcePatchList
    resourcePatchList:
    - fromFieldPath: spec.size
      toFieldPath: spec.forProvider.dbSize
```

> It's also worth noting that this proposal appears to be backward incompatible. I think we'd need to move things up to the same level as patches to be compatible

Yes, it is but we could keep the existing fields for a while. In fact, I don't really think this should affect our decision here that much. The amount of users who will use the final v1 API far exceeds the amount of users who are currently using the existing one and will be affected. And we have a way to not break them, too, either by keeping the existing fields as an exception or write a webhook or just say it's `v1beta1 -> v1`, here is the manual migration doc. So, I'd definitely go for whatever we think is the best instead of optimizing for the least API change as long as we have the means to handle those changes, which we have in that case.

As a side note, I think we put ourselves in a position where we don't invest in webhooks because we don't have a breaking change yet (or just decided to break since they were `v1alpha1`) but at the same time we stay away from breaking changes because we don't have webhooks as automated approach to handle them. Until a breaking change that is important enough to make us implement the webhooks just for that, our API decisions seems to be affected and I don't think this is an effect that we'd like to consider in order to make the best decision for the long term.

**Comment by negz** [comment]
> If the chosen type needs to be configured, it has its own field.

I don't see any indication that this is a strict requirement - in fact in the KEP's given example the `TopLevelUnion` type (which inlines its nested structs) would render out as:

```yaml
topLevelUnion:
  name: example
  unionType: A
  fieldA: 22
```

Note that `fieldA` is a simple `int` field at the same level as the discriminator, rather than being a value nested in an object.

I don't feel moving the discriminated values into a nested object is worthwhile for two reasons:

1. It doesn't seem like enough of a win to justify making a breaking API change.
1. In some cases the same fields could apply to multiple patch types - e.g. `fromFieldPath` and `toFieldPath` would each make sense whether you were patching from composite to composed or vice versa.

> `customPatches`

The patches in this array aren't any more 'custom' than the array of patches associated with each entry in the `resources` array, so this name doesn't really make sense to me. I still prefer the idea of a named set of patches - i.e. `patchSets`. This is [an established name](https://en.wiktionary.org/wiki/patchset) for the concept of set of patches in software engineering. If folks are really against `patchSets` as a name I'm open to other suggestions. The concept we're trying to get across is that these are predefined groups or sets of patches that can be applied to a resource by name to avoid the Composition author needing to repeat themself.

> I think we should use name over id if the value is human-written rather than machine-generated

Per my previous comment, my concern here is the likelihood that `name` will be conflated with the desired name of the composite resource if we embrace this convention inside `Composition`. For example:

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  name: example
resources:
- name: this-is-the-name-of-the-resource-array-entry
  base:
    apiVersion: crossplane.io/v1alpha1
    kind: Example
    spec:
      # ...
```

That said, I can see both sides of this argument - it would be good to be consistent - so I'm happy to take that small UX risk and use `name`.

To my mind, this all lands us back at something quite similar to what I originally proposed:

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  name: example 
spec:
  # ...
  patchSets:
    - name: labels
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
  resources:
    - base:
        # ...
      patches:
        # A reference to the above patchset named 'metadata'
        - type: PatchSet
          patchSetName: labels
        # The functionality we have today - this type is the default
        # when the type is omitted.
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        # Patches from many composite fields to one composed field,
        # combining them using some kind of transform (maybe a
        # simple concatenation by default?)
        - type: FromCompositeFieldPaths
          fromFieldPaths:
          - metadata.annotations[namespace]
          - metadata.annotations[name]
          toFieldPath: metadata.annotations[namespacedname]
          transforms:
          - type: String
            fmt: "%s/%s"
        # The inverse of today's behaviour; patches from the composed
        # resource back to the composite.
        - type: FromComposedFieldPath
          fromFieldPath: status.atProvider.widgets
          toFieldPath: status.widgetCount
```
