### ISSUE TITLE
Distribute app to provisioned kubernetes cluster

### ISSUE THREAD

**Issue by jianh619** [crossplane/crossplane#1991]
### What problem are you facing?

I can create kubernetes cluster on public cloud via crossplane , by leveraging OAM , crossplane help me to deploy application on kubernetes clusters , so I'm wondering , if there's way for me to distribute application on clusters , e.g I can specify app running on Cluster A/B/C from AWS , instead login in each cluster , to install OAM and deploy app ? I'm trying to use crossplane to manage our public kubernetes clusters , including managing the app life-cycle 

### How could Crossplane help solve your problem?

I can list clusters created via crossplane
```
# kubectl get clusters -A
NAME             READY   SYNCED   AGE
jian-cluster     True    True     2d22h
sample-cluster   True    True     3d
```
Is it possible to assign a job to one/more cluster to install OAM and the application ?

**Comment by gyliu513** [comment]
> I can create kubernetes cluster on public cloud via crossplane

@jianh619 can you show some detail how did you provision a k8s cluster via crossplane? Any links or samples that I can refer?

**Comment by jianh619** [comment]
@gyliu513 
I find this example https://github.com/crossplane/provider-aws/tree/master/examples/eks , but seems it's out of date , so I modify some attributes according to API spec , https://doc.crds.dev/github.com/crossplane/provider-aws
```
---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: sample-cluster
  labels:
    example: "true"
spec:
  forProvider:
    region: us-east-1
    roleArn: <your rolearn>
    resourcesVpcConfig:
      publicAccessCidrs:
      - 0.0.0.0/0
      endpointPublicAccess: true
      subnetIds:
        - <available subnetid>
    version: "1.16"
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: default
  providerConfigRef:
    name: default

---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: my-group
  labels:
    example: "true"
spec:
  forProvider:
    region: us-east-1
    nodeRole: <your rolearn>
    subnets:
      - <available subnetid>
    clusterNameRef:
      name: sample-cluster
```
