### ISSUE TITLE
Dependencies are not found if provided without registry

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#2008]
### What happened?

`go-containerregistry` defaults to `index.docker.io` as registry if none is provided. We account for this when a package identifies itself in the `Lock`, but not for identifying dependencies. This means that having a dependency on something like `crossplane/provider-aws` will always fail to find a matching dependency, but `registry.upbound.io/crossplane/provider-aws` or `index.docker.io/crossplane/provider-aws` will work.

The simplest solution to this is to update the dependency searching to use registry defaulting. However, this will break functionality in the future if we change to a different default. Alternatively, we could have packages add themselves to the `Lock` without the default registry added. (i.e. if I install `crossplane/provider-aws` it would be added to the `Lock` as `crossplane/provider-aws` rather than `<default-registry>/crossplane/provider-aws`).

Regardless of the direction we choose, we should always encourage using full registry paths rather than falling back on a default.

### How can we reproduce it?

1. Install `crossplane`
2. `kubectl crossplane install hasheddan/getting-started-with-aws:v0.1.0`
3. See that `provider-aws` is installed successfully, but `getting-started-with-aws` never becomes healthy and reports missing dependency

```
🤖 (crossplane) k get pkg
NAME                                                       INSTALLED   HEALTHY   PACKAGE                                     AGE
configuration.pkg.crossplane.io/getting-started-with-aws   True        Unknown   hasheddan/getting-started-with-aws:v0.1.0   49s

NAME                                                 INSTALLED   HEALTHY   PACKAGE                                             AGE
provider.pkg.crossplane.io/crossplane-provider-aws   True        True      crossplane/provider-aws:v0.16.0-rc.0.57.g641be176   40s
```

```
Events:
  Type     Reason               Age                From                                              Message
  ----     ------               ----               ----                                              -------
  Warning  ResolveDependencies  29s (x4 over 61s)  packages/configurationrevision.pkg.crossplane.io  missing dependencies: [crossplane/provider-aws]
```

4. Observe packages in `Lock`

```
packages:
  - dependencies:
    - constraints: '>=v0.14.0-0'
      package: crossplane/provider-aws
      type: Provider
    name: getting-started-with-aws-b269422271fa
    source: index.docker.io/hasheddan/getting-started-with-aws
    type: Configuration
    version: v0.1.0
  - dependencies: []
    name: crossplane-provider-aws-9d325be8ac27
    source: index.docker.io/crossplane/provider-aws
    type: Provider
    version: v0.16.0-rc.0.57.g641be176

```

### What environment did it happen in?
Crossplane version: `1.0.0-rc.0.81.gdce235c8`
