### ISSUE TITLE
Can't update `connectionDetails` for existing resources

### ISSUE THREAD

**Issue by bandesz** [crossplane/crossplane#2024]
### What happened?

I had a typo in the name of the connection secret. CompositeResourceDefinition had "awsSecretAccessKey" while in the Composition object I had "awsSecretAccesskey" in connectionDetails (or the other way around). After fixing the typo (sorry, I don't remember which one had the wrong name) the generated connection secret didn't have awsSecretAccessKey, only awsAccessKeyID.

I've deleted the existing claim and created a new one, but still the same result.

I've deleted and recreated the Composition/CompositeResourceDefinition which fixed the issue.

I haven't used a Configuration, as I'm installing the Composition/CompositeResourceDefinition using a Helm chart.

### How can we reproduce it?

Composition relevant part:
```
    - base:
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMAccessKey
        metadata:
          name: METADATA_UID
        spec:
          deletionPolicy: Delete
          forProvider:
            accessKeyStatus: Active
            userNameSelector:
              matchControllerRef: true
          writeConnectionSecretToRef:
            name: METADATA_UID-iam-access
            namespace: kore-crossplane
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "metadata.name"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-iam-access-key"
      connectionDetails:
        - name: awsAccessKeyID
          fromConnectionSecretKey: username
        - name: awsSecretAccessKey
          fromConnectionSecretKey: password
```

CompositeResourceDefinition relevant part:
```
  connectionSecretKeys:
    - awsAccessKeyID
    - awsSecretAccessKey
```

Crossplane version: 0.14.0
