### ISSUE TITLE
Composition Dependency and Ordered Creation

### ISSUE THREAD

**Issue by krishchow** [crossplane/crossplane#2072]
### What problem are you facing?
Although my default Crossplane creates all resources in a composition in order, this typically does not include the entire reconciliation lifecycle for provisioning some abstract resource. Just applying a resource does not mean that has been created, and we may have other resources in the composition rely on a previous resource. Currently, within Crossplane the main mechanism for handling these issues is the reconciliation loop, however, this is not always feasible if we are working with resources outside of the Crossplane ecosystem. Similar issues also arise if we want to make stronger claims about the resources we are creating (e.g., if we want to block the creation of an RDS database until we are certain that all of the subnets were created).

This is a use case that was previously outlined in a [discussion](https://crossplane.slack.com/archives/CEG3T90A1/p1610110813347800) on the Crossplane Slack. 

### How could Crossplane help solve your problem?
I think it would be a good idea to have a depends_on field at the top level of each composition, similar to readinessChecks, where users can input fields to assign dependency to some other resource. The easiest kind would be a dependency on the previous resource in the composition, but we could also expand this to dependency on any other resource and utilize the same base API types as the readinessChecks. I have a draft PR which I will open up soon for this issue.

**Comment by negz** [comment]
I'd like some more context before we proceed with this enhancement. Can you share some concrete examples in which this might be used, and how our current approach of eventually consistent reconcilers (which I believe is fairly idiomatic to Kubernetes) falls short?

> Currently, within Crossplane the main mechanism for handling these issues is the reconciliation loop, however, this is not always feasible if we are working with resources outside of the Crossplane ecosystem.

What do you mean by "resources outside of the Crossplane ecosystem", here?

**Comment by krishchow** [comment]
An example of where this might be useful is for one-off resources or certain resources that expect dependencies are fulfilled prior to creation (where the reconciler is not designed to support ambiguous scenarios). Similar to the [Terraform depends_on](https://www.terraform.io/docs/configuration/meta-arguments/depends_on.html), this should be rarely used, but effectively required in some scenarios.

As for resources outside of the Crossplane ecosystem, currently, in Crossplane, there is support for composing arbitrary (i.e.,  not from Provider/Crossplane) resources via the `readinessChecks` field in the ComposedTemplate. This could naturally extend to not only built-in Kubernetes resources (e.g., using a job to configure a Postgres database) but also resources exposed by other Operators. 

In the scenario, you want to use a Job, and you don't want to select a predefined maximum time (or iterations) for the retry logic, this `depends_on` field could allow the Job to depend on a Postgres instance provisioned by RDS, as opposed to some finite maximum time.

**Comment by negz** [comment]
> As for resources outside of the Crossplane ecosystem, currently, in Crossplane, there is support for composing arbitrary (i.e., not from Provider/Crossplane) resources via the readinessChecks field in the ComposedTemplate.

It's worth noting that per https://github.com/crossplane/crossplane/issues/1730 our support for arbitrary resources is not intentional. I'm planning to dive deeper on that issue this quarter, but for the time being it's explicitly not a case that we're designing for in Crossplane.

**Comment by krishchow** [comment]
Even outside of directly including external resources within a composition, this depends_on functionality is still useful if you include any external resources defined in a Helm chart (which you can create via the Helm Provider)

**Comment by muvaf** [comment]
I think the use cases that we come up with to justify `depends_on` need to include only managed resources since as @negz pointed out, composition is designed for composing managed resources. For example, right now we deploy all at the same time and dependency resolution happens via cross-resource references (`*Ref` fields). The cases where this is not enough will be covered by https://github.com/crossplane/crossplane/issues/1770 where (I assume) will allow you to refer to another resource in a way that was not intended by the author of that resource. So, this could help you in the sense that you might be able to refer to a `Job` but the details of that feature are still to be fleshed out.

**Comment by krishchow** [comment]
Hmm, interesting, could #1770 be used to create a reference from a job to some other resource such that the creation is blocked until the other resource finishes being provisioned? I could see that working, although it does feel like a slightly hacky solution. 

As for what I mentioned before, exclude that I mentioned jobs being provisioned through a composition, although that's how I've tested the attached PR, it's not relevant for the issue. The same use case can be seen through the use of the Helm Provider, which also just include creating arbitrary Kubernetes resources. For a more concrete example, check out [https://github.com/redhat-et/crossplane-quay](https://github.com/redhat-et/crossplane-quay). This repository references a Helm chart that can be found in the repository [https://github.com/redhat-et/quay-chart](https://github.com/redhat-et/quay-chart).

Essentially, we use the AWS Provider to spin up some dependencies for Quay, then we want to create an instance of Quay using the Quay Operator. However, we cannot rely on the reconcile loop for the Quay operator, and instead, we would like to block the creation of the CR until the secrets are ready. The current way I am achieving this is through a blocking pre-install hook, a notion of depends_on since I think this is not a use case that is unheard of.

**Comment by muvaf** [comment]
> The same use case can be seen through the use of the Helm Provider, which also just include creating arbitrary Kubernetes resources.

Yes, I believe we hit this in one of the Upbound reference platforms where we wanted to pre-install some stuff to the provisioned cluster.

> could #1770 be used to create a reference from a job to some other resource such that the creation is blocked until the other resource finishes being provisioned?

I think yes. I wouldn't expect a CR to be reconciled before all of the references are resolved but that's still to be designed.

**Comment by negz** [comment]
I like the idea of potentially using #1770 to address this use case. Or if that feels like too much of a hack, generally building this down at the managed resource level rather than up at the Composition level (similar to how we've built cross resource references thus far). I suspect this will simplify the implementation of things like depending on a resource that isn't part of your composition (as well as dependencies from resources that aren't part of compositions at all).

**Comment by cdenneen** [comment]
Just ran into this issue where `Composition` containing a `Role` and `Cluster`:

```yaml
Name:         apqa-test-1-g7nff
Namespace:    
Labels:       crossplane.io/claim-name=
              crossplane.io/claim-namespace=
              crossplane.io/composite=apqa-test-1
              name=eks-cluster-role
Annotations:  crossplane.io/composition-resource-name: eks-cluster-role
              crossplane.io/external-create-pending: 2022-02-01T17:43:13Z
              crossplane.io/external-create-succeeded: 2022-02-01T17:43:14Z
              crossplane.io/external-name: apqa-test-1-g7nff
API Version:  iam.aws.crossplane.io/v1beta1
Kind:         Role
Metadata:
  Creation Timestamp:  2022-02-01T17:43:13Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generate Name:  apqa-test-1-
  Generation:     33
  Managed Fields:
    API Version:  iam.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:crossplane.io/composition-resource-name:
        f:generateName:
        f:labels:
          .:
          f:crossplane.io/claim-name:
          f:crossplane.io/claim-namespace:
          f:crossplane.io/composite:
          f:name:
        f:ownerReferences:
          .:
          k:{"uid":"40195700-6631-4108-baff-8da9b02cbb75"}:
            .:
            f:apiVersion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:assumeRolePolicyDocument:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      crossplane
    Operation:    Update
    Time:         2022-02-01T17:53:24Z
    API Version:  iam.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-create-pending:
          f:crossplane.io/external-create-succeeded:
          f:crossplane.io/external-name:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:spec:
        f:forProvider:
          f:maxSessionDuration:
          f:path:
          f:tags:
      f:status:
        .:
        f:atProvider:
          .:
          f:arn:
          f:roleID:
        f:conditions:
    Manager:    crossplane-aws-provider
    Operation:  Update
    Time:       2022-02-01T17:53:24Z
  Owner References:
    API Version:     aws.platformref.crossplane.io/v1alpha1
    Controller:      true
    Kind:            EKSCluster
    Name:            apqa-test-1
    UID:             40195700-6631-4108-baff-8da9b02cbb75
  Resource Version:  8351165
  UID:               09de58fe-d1fb-490e-9f0e-398a9b706f48
Spec:
  Deletion Policy:  Delete
  For Provider:
    Assume Role Policy Document:  {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {"Service": "eks.amazonaws.com"},
      "Action": "sts:AssumeRole"
    }
  ]
}
    Max Session Duration:  3600
    Path:                  /
    Tags:
      Key:    Service
      Value:  Kubernetes
      Key:    Support Team
      Value:  Cloud Services
      Key:    crossplane-providerconfig
      Value:  apqa
      Key:    crossplane-kind
      Value:  role.iam.aws.crossplane.io
      Key:    crossplane-name
      Value:  apqa-test-1-g7nff
  Provider Config Ref:
    Name:  apqa
Status:
  At Provider:
    Arn:      arn:aws:iam::XXXX:role/apqa-test-1-g7nff
    Role ID:  AROA2PNUROSTZER7IQX4J
  Conditions:
    Last Transition Time:  2022-02-01T17:43:14Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-02-01T17:43:14Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:
  Type    Reason                   Age                 From                                Message
  ----    ------                   ----                ----                                -------
  Normal  CreatedExternalResource  10m                 managed/role.iam.aws.crossplane.io  Successfully requested creation of external resource
  Normal  UpdatedExternalResource  21s (x36 over 10m)  managed/role.iam.aws.crossplane.io  Successfully requested update of external resource
```

```yaml
Name:         apqa-test-1-6qskh
Namespace:    
Labels:       crossplane.io/claim-name=
              crossplane.io/claim-namespace=
              crossplane.io/composite=apqa-test-1
Annotations:  crossplane.io/composition-resource-name: eks-cluster
              crossplane.io/external-name: apqa-test-1-6qskh
API Version:  eks.aws.crossplane.io/v1beta1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2022-02-01T17:43:14Z
  Generate Name:       apqa-test-1-
  Generation:          2
  Managed Fields:
    API Version:  eks.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:crossplane.io/composition-resource-name:
        f:generateName:
        f:labels:
          .:
          f:crossplane.io/claim-name:
          f:crossplane.io/claim-namespace:
          f:crossplane.io/composite:
        f:ownerReferences:
          .:
          k:{"uid":"40195700-6631-4108-baff-8da9b02cbb75"}:
            .:
            f:apiVersion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:region:
          f:resourcesVpcConfig:
            .:
            f:endpointPrivateAccess:
            f:endpointPublicAccess:
            f:securityGroupIdSelector:
              .:
              f:matchLabels:
                .:
                f:networks.aws.platformref.crossplane.io/network-id:
            f:subnetIdSelector:
              .:
              f:matchLabels:
                .:
                f:networks.aws.platformref.crossplane.io/network-id:
                f:type:
                f:visibility:
          f:roleArnSelector:
            .:
            f:matchControllerRef:
            f:matchLabels:
              .:
              f:name:
          f:tags:
            .:
            f:Service:
            f:Support Team:
          f:version:
        f:providerConfigRef:
          .:
          f:name:
        f:writeConnectionSecretToRef:
          .:
          f:name:
          f:namespace:
    Manager:      crossplane
    Operation:    Update
    Time:         2022-02-01T17:43:13Z
    API Version:  eks.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-name:
      f:spec:
        f:forProvider:
          f:tags:
            f:crossplane-kind:
            f:crossplane-name:
            f:crossplane-providerconfig:
      f:status:
        .:
        f:atProvider:
          .:
          f:identity:
            .:
            f:oidc:
          f:resourcesVpcConfig:
        f:conditions:
    Manager:    crossplane-aws-provider
    Operation:  Update
    Time:       2022-02-01T17:43:14Z
  Owner References:
    API Version:     aws.platformref.crossplane.io/v1alpha1
    Controller:      true
    Kind:            EKSCluster
    Name:            apqa-test-1
    UID:             40195700-6631-4108-baff-8da9b02cbb75
  Resource Version:  8343460
  UID:               87ba757f-1b8a-48b6-b96b-7ba0c24ce1ff
Spec:
  Deletion Policy:  Delete
  For Provider:
    Region:  us-east-1
    Resources Vpc Config:
      Endpoint Private Access:  true
      Endpoint Public Access:   false
      Security Group Id Selector:
        Match Labels:
          networks.aws.platformref.crossplane.io/network-id:  apqa-use1
      Subnet Id Selector:
        Match Labels:
          networks.aws.platformref.crossplane.io/network-id:  apqa-use1
          Type:                                               subnet
          Visibility:                                         private
    Role Arn Selector:
      Match Controller Ref:  true
      Match Labels:
        Name:  eks-cluster-role
    Tags:
      Service:                      Kubernetes
      Support Team:                 Cloud Services
      Crossplane - Kind:            cluster.eks.aws.crossplane.io
      Crossplane - Name:            apqa-test-1-6qskh
      Crossplane - Providerconfig:  apqa
    Version:                        1.21
  Provider Config Ref:
    Name:  apqa
  Write Connection Secret To Ref:
    Name:       40195700-6631-4108-baff-8da9b02cbb75-ekscluster
    Namespace:  crossplane-system
Status:
  At Provider:
    Identity:
      Oidc:
    Resources Vpc Config:
  Conditions:
    Last Transition Time:  2022-02-01T17:43:14Z
    Message:               cannot resolve references: mg.Spec.ForProvider.RoleArn: referenced field was empty (referenced resource may not yet be ready)
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                           Age                    From                                   Message
  ----     ------                           ----                   ----                                   -------
  Warning  CannotResolveResourceReferences  9m12s (x2 over 9m12s)  managed/cluster.eks.aws.crossplane.io  cannot resolve references: mg.Spec.ForProvider.RoleArn: referenced field was empty (referenced resource may not yet be ready)
```

The matchLabel selector should have worked but appears to have been an ordering issue:

```yaml
        kind: Cluster
        spec:
          forProvider:
            roleArnSelector:
              matchControllerRef: true
              matchLabels:
                name: eks-cluster-role
```

Deleting the `Cluster` (leaving the `Role`) and allowing the `Composition` to recreate the `Cluster` resolved the issue.
Having a `dependsOn` would be useful or the `roleArnSelector` should have attempted to resolve this more than just 2x in less than 2m. Even at 10m+ it still had only tried the 2x.

**Comment by cdenneen** [comment]
The `Cluster` created upon second attempt now finding `Role` but then the `Addons` and `NodeGroup` were stuck on `clusterName` selector.

**Comment by muvaf** [comment]
@cdenneen Are they created not created at all or created but not reconciled since the reference is not resolved?

**Comment by cdenneen** [comment]
After I delete the resources that are “stuck” they recreate when they reconcile. So the second “creation” finds the dependency and creates. The original resource can’t find its reference but gets stuck that it doesn’t Try more than 2 or 3 relatively short. The Role was created in less than 2m but cluster was stuck after 2 tries in less than 2m and then nodegroup was stuck on the cluster 3x in less than 10m. 
I’m running this under Fluxv2 so have a kustomize controller doing reconciliation so after I delete the composition does try to reconcile which will create the resources I deleted. 
In solution that isn’t running this after you delete cluster you’d have to recreate and then the same with nodeGroup. 
Dependencies would allow for the resources to wait to even attempt to create until they are READY but at its simplest if the Retries just kept happening to find those references they probably would have eventually created without need for dependencies (just not as efficient)

**Comment by muvaf** [comment]
> Retries just kept happening to find those references they probably would have eventually created without need for dependencies (just not as efficient)

That is actually the case; the whole system is eventually consistent, at every reconciliation it tries to resolve the references. Wonder why it didn't do that in your case.

**Comment by cdenneen** [comment]
After that 2x I’m the case of the Cluster (waiting on Role) and 3x in the case of the NodeGroup (waiting on Cluster) they never tried again. The Age kept growing with no more `x` attempted. @Chrisupbound said they have seen same issue from time to time.

**Comment by muvaf** [comment]
@negz Could this be related to the backoff behavior somehow? I know that we ask for a requeue if reference isn't resolved.

**Comment by haarchri** [comment]
Something with 1.6 since this Release we can see this also from time to time in our environment

**Comment by shanproofpoint** [comment]
When allowing resources to become consistent in the reconciliation loops, some ci cd tools like argocd are stuck when webhooks wait for each other cyclicly. The same can happen for kubernetes provider objects that depend on each other dynamically.

**Comment by shanproofpoint** [comment]
After reading above comments, I also realize and concur that incomplete cleanups on retries may conflate the cyclic stuck reconciliation problems.

**Comment by yebolenko** [comment]
any update on this issue?
Do you intend to add dependency between resources?

**Comment by bobh66** [comment]
The reference to #3393 above is intended to solve this issue.

**Comment by shanproofpoint** [comment]
> 

I just want to give you a warning that that dependsOn does not do what you think it does - that is wait on resources. It will also introduce cleanup trouble as well because there are ordered cleanups that crossplane does not do well when this is added to the mix.

**Comment by shanproofpoint** [comment]
the only sure way to currently wait for things is to  patch policy required on an annotation value

**Comment by jfmrm** [comment]
@shanproofpoint for me using this introduces an error on the composition level. So no resource is created.

> the only sure way to currently wait for things is to
>
>        policy:
>            fromFieldPath: Required
> on an annotation value

**Comment by dee-kryvenko** [comment]
I am currently evaluating Crossplane and I just run into this issue as well.

I understand eventual consistency argument and I agree with it. I think introducing `dependsOn` would be an anti-pattern.

Yet, this issue cannot be denied. I am having a fairly basic use case, trying to create a KMS, IAM role and attach a policy to it that would allow to use aforementioned KMS.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: v1alpha1-vaultdependencies.example.com
  labels:
    crossplane.example.com/flavor: default
spec:
  compositeTypeRef:
    apiVersion: aws.example.com/v1alpha1
    kind: VaultDependency
  patchSets:
  - name: set-region
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.awsRegion"
      toFieldPath: "spec.forProvider.region"
  resources:
  - base:
      apiVersion: kms.aws.upbound.io/v1beta1
      kind: Key
      spec:
        forProvider:
          keyUsage: ENCRYPT_DECRYPT
          deletionWindowInDays: 30
        providerConfigRef:
          name: provider-aws-local-account
    patches:
    - type: PatchSet
      patchSetName: set-region
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.kms.arn
  - base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: Role
      metadata:
        labels:
          vault/role: "1"
      spec:
        providerConfigRef:
          name: provider-aws-local-account
    patches:
    - type: PatchSet
      patchSetName: set-region
    - type: CombineFromComposite
      combine:
        strategy: string
        variables:
        - fromFieldPath: spec.kubernetesClusterIssuerARN
        - fromFieldPath: spec.kubernetesClusterIssuer
        - fromFieldPath: spec.kubernetesNamespace
        string:
          fmt: >
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "%s"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {
                      "%s:sub": "system:serviceaccount:%s:vault"
                    }
                  }
                }
              ]
            }
      toFieldPath: spec.forProvider.assumeRolePolicy
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.iam.arn
  - base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: Policy
      metadata:
        labels:
          vault/policy: "1"
      spec:
        providerConfigRef:
          name: provider-aws-local-account
    patches:
    - type: PatchSet
      patchSetName: set-region
    - type: CombineFromComposite
      combine:
        strategy: string
        variables:
        - fromFieldPath: status.kms.arn
        string:
          fmt: >
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Action": [
                    "kms:Encrypt",
                    "kms:Decrypt",
                    "kms:DescribeKey"
                  ],
                  "Effect": "Allow",
                  "Resource": [
                    "%s"
                  ]
                }
              ]
            }
      toFieldPath: spec.forProvider.assumeRolePolicy
  - base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: RolePolicyAttachment
      spec:
        forProvider:
          roleSelector:
            matchControllerRef: true
            matchLabels:
              vault/role: "1"
          policyArnSelector:
            matchControllerRef: true
            matchLabels:
              vault/policy: "1"
        providerConfigRef:
          name: provider-aws-local-account
    patches:
    - type: PatchSet
      patchSetName: set-region
```


And it fails to create the Policy:

```
composed resource "2": cannot use dry-run create to name composed resource: Policy.iam.aws.upbound.io "vault-khb8n" is invalid: spec: Invalid value: "object": no such key: initProvider evaluating rule: policy is a required parameter
```

As long as such basic plumbing scenario does not work out of the box - I am not sure how anybody can seriously use this in production. Unless I am doing something wrong or this just broke in the recent versions - seriously, there is no way no one ever thought of this.
