### ISSUE TITLE
Make "runAsUser" and "runAsGroup" configurable in ProviderDeployment

### ISSUE THREAD

**Issue by pdettori** [crossplane/crossplane#2080]
### What problem are you facing?

I want to deploy Crossplane and Crossplane providers on OpenShift. Since OpenShift has security context constraints, I get this error when trying to deploy a provider:

```
 message: 'pods "crossplane-provider-ibm-cloud-12f6b13091ae-797bbd5f56-" is forbidden:
      unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser:
      Invalid value: 2000: must be in the ranges: [1000620000, 1000629999]]'
``` 

The same issue happens with Crossplane, however Crossplane has options in the helm chart to configure the security context by deploying the helm chart with:

```
helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --set securityContextCrossplane.runAsUser=1000620000 --set securityContextCrossplane.runAsGroup=1000620000
```
that solves the problem for Crossplane, but not for Provider deployment, indeed those options are hardcoded in https://github.com/crossplane/crossplane/blob/94f34fd38f9367ac2be667d8a987aed336f6bdd2/internal/controller/pkg/revision/deployment.go#L32-L33

### How could Crossplane help solve your problem?

A possible solution would be to propagate the values used in the helm chart for the Crossplane controller to the Provider deployment, or introduce new variables in the helm chart for the security context of the provider deployment. In any case it would be important to have a way to configure those settings for the provider deployment.

For more info and a workaround for OpenShift, [see this issue](https://github.com/crossplane-contrib/provider-ibm-cloud/issues/19#issuecomment-760699511)

**Comment by pdettori** [comment]
Note that there is also a related issue for the AWS Provider: https://github.com/crossplane/crossplane/issues/2080

**Comment by hasheddan** [comment]
Also see https://crossplane.io/docs/v1.0/introduction/packages.html#speccontrollerconfigref

**Comment by krishchow** [comment]
This seems to work perfectly! @pdettori e.g., https://gist.github.com/krishchow/f4ecb1fbad04d84aa7e142abfdb472bf

Openshift handles setting the securityContext, so we just set the to default to null

**Comment by cg2p** [comment]
Please elaborate @krishchow 

I recreated my OpenShift environment and *removed* the privileged `oc adm policy ...` as per [this](https://github.com/crossplane-contrib/provider-ibm-cloud/issues/19).

Then from the IBM Cloud provider install instructions, instead of executing this:
```
kubectl crossplane install provider crossplane/provider-ibm-cloud:alpha
```
I can apply this yaml as per your [gist](https://gist.github.com/krishchow/f4ecb1fbad04d84aa7e142abfdb472bf)
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: openshift-config
  namespace: crossplane-system
spec:
  securityContext: {}
  podSecurityContext: {}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: provider-ibm-cloud
spec:
  package: crossplane/provider-ibm-cloud:alpha
  controllerConfigRef:
    name: openshift-config
```

So when you say "Openshift handles setting the securityContext, so we just set the to default to null".

Logged in with my IAM userid to the OpenShift cluster, without those workaround privileges, then where are you supposed to let the Crossplane provider install correctly under that IAM userid?

We have lost the step to do `runAsUser` to @pdettori original point. The goal is a solution where we do not need hardcoded values.

**Comment by krishchow** [comment]
In my Openshift 4.4 cluster, if I create the Provider with an empty securityContext as specified ControllerConfig, Openshift fills in the pods `spec.securityContext.fsGroup` and `spec.containers[0].securityContext.runAsUser` values with the appropriate IDs. 

Prior to this, I used to use `oc edit` to modify the Deployment for the Provider I was creating, and remove the hardcoded values. This was a sufficient workaround, but it required modifying each Provider, which of course didn't scale.

**Comment by cg2p** [comment]
ok let me try in my environment again.

Are we executing the same steps i.e. applying that yaml above, and not executing `kubectl crossplane install provider crossplane/provider-ibm-cloud:alpha`?

I am using OpenShift 4.5 on IBM Cloud, are using OpenShift on the AWS?

Also, where do you look to confirm OpenShift has fills in the pods values with the appropriate IDs?

And, finally what `apiVersion` did you use for `Provider` and `ControllerConfig` just in case that becomes relevant?

Thanks

**Comment by krishchow** [comment]
Yes exactly, you should be able to apply the manifest in the gist instead of using the `install provider` command. 

I am using Openshift on AWS.

I confirm that Openshift fills in the pod values by using `kubectl describe pods -n crossplane-system`. `crossplane-system` is the namespace where I expect my providers to be created. The apiVersion for the Provider and ControllerConfig is v1 and v1alpha1 respectively.

**Comment by pdettori** [comment]
@krishchow thank you, it works well for me on my OpenShift 4.5 with the IBM Cloud Provider. I just slightly modified your snippet for my provider:

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: openshift-config-ibm-cloud
  namespace: crossplane-system
spec:
  securityContext: {}
  podSecurityContext: {}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-ibm-cloud
  namespace: crossplane-system
spec:
  package: crossplane/provider-ibm-cloud:alpha
  controllerConfigRef:
    name: openshift-config-ibm-cloud
```    
Perhaps only minor issue is that I can't use "kubectl crossplane" to install the provider, but this looks good enough to me.
