### ISSUE TITLE
How to grant RBAC permissions for composition managed resources

### ISSUE THREAD

**Issue by cheewaio** [crossplane/crossplane#2084]
### What problem are you facing?

I've created a composition, for example:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
  labels:
    provider: example
spec:
  resources:
  - base:
      apiVersion: example.comv1alpha1
      kind: ExampleA
      spec:
           foo: bar
  - base:
      apiVersion: example.comv1alpha1
      kind: ExampleB
      spec:
           bar: foo
```

What is the recommended way to specify the ClusterRole permissions needed for crossplane service account to create the base managed resources (ExampleA and and ExampleB)?

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane.example.com
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - example.com
  resources:
  - "*"
  verbs:
  - "*"
```

### How could Crossplane help solve your problem?

I am looking for a way to package the RBAC permission requests. I notice there is a mechanism to specify `permissionRequests` for the provider controller in the provider crossplane.yaml. Is there something similar for the configuration crossplane.yaml?

**Comment by cheewaio** [comment]
Here is my understanding:
- XRDs included in the configuration package are scanned, and permissions are automatically aggregated to the `crossplane` clusterrole
- Managed resource CRDs included in the provider package are scanned, and permissions are automatically aggregated to the `crossplane` clusterrole
- additional resource permissions can be requested in the provider `crossplane.yaml`, provided that the permissions are enabled in `crossplane:allowed-provider-permissions` clusterrole
 For example:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane.example.com
  labels:
    rbac.crossplane.io/aggregate-to-allowed-provider-permissions: "true"
rules:
- apiGroups:
  - example.com
  resources:
  - "*"
  verbs:
  - "*"
```
