### ISSUE TITLE
Optionally mark certain patches as required

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2094]
### What problem are you facing?

https://github.com/crossplane/crossplane/blob/65e42d5/apis/apiextensions/v1/composition_types.go#L266

Currently Crossplane will happily allow you to patch from a non-existent field path - treating the patch as a no-op. This enables 'opportunistic' patching - i.e. "patch from this field if it exists". This us useful for some use cases, but in others it would be better to return an error (and retry again later) when a patch's source is not available. For example in https://github.com/crossplane/crossplane/issues/2091 the goal is to patch from the XR's `spec.claimRef.name`, which may not exist for a brief period when the XR is first created. Ideally in this case we'd return an error and try again, eventually succeeding when the claim was specified.

### How could Crossplane help solve your problem?

Crossplane could allow Composition authors to specify whether a particular patch is required or not. i.e.:

```yaml
      patches:
        - fromFieldPath: "spec.claimRef.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "example-%s"
          # Better names welcome. I'm going for something like
          # "required: true" but using an enum to keep things open
          # ended per API conventions.
          strategy: Required
```

The default behaviour would match today's (i.e. the patch would be a no-op), but if `strategy: Required` we'd instead return an error and retry.
