### ISSUE TITLE
Composite should be able to take ownership of existing managed resource

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#2096]
### What problem are you facing?

Today we have a well-defined way of importing an existing external resource as managed resource using `crossplane.io/external-name` annotation. However, there isn't a documented way of migrating existing external resources into a composition setting.

### How could Crossplane help solve your problem?

I think this could be achieved in two ways:
* Import external resources as managed resource and then have the composite adopt them when it's created instead of creating new ones.
* Configure `Composition` in a way that will propagate some values from claim into composed resources `crossplane.io/external-name` so that when it's created, it will automatically take ownership of the external resource.

I think the second option is not really a good way since the goal of using composition is to be able to use it as blueprint and repeat the process but after the migration, it won't be useful to have the patches that get the external name from the user input. So, I believe we should invest in the first option.

**Comment by jbhennin** [comment]
This is exactly what we need and it is critical to the adoption of crossplane.
In theory once a resource is migrated and adopted, we would want to generate the claim.yaml according to our XRD so that users can manage the resource going forward.

**Comment by negz** [comment]
> I think the second option is not really a good way since the goal of using composition is to be able to use it as blueprint and repeat the process but after the migration, it won't be useful to have the patches that get the external name from the user input. So, I believe we should invest in the first option.

What if the Composition was written such that the source of the external names were optional annotations on the XR? i.e. If you create the XR with those annotations it adopts the existing resources, but if you don't it happily creates new ones. I suspect this would still be awkward, but slightly less awkward than option one. This could look something like:

```yaml
resources:
- base:
    apiVersion: s3.aws.crossplane.io/v1beta1
    kind: Bucket
    spec:
      # ...
    patches:
    # This patch is a no-op if there is no adopt-existing-bucket annotation
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.annotations[adopt-existing-bucket]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
```

Under option one (import external resources as managed resources, then attach them) I imagine you would:

1. Create N managed resources with enough context that they can successfully adopt the existing external resources. The context in this case would involve adding external name annotations and setting any required fields to the same values as the existing external resources.
2. Repeat 1, but at the Composition scope. i.e. Write a Composition that will render out managed resources that are compatible with the existing external resources.
3. Create an XR to adopt the imported managed resources - e.g. by carefully setting its `resourceRefs` array. Crossplane should notice the existing managed resources don't have controller refs and allow it to adopt them.

Where as under option two (writing an XR that creates managed resources that in turn adopt external resources) you would:

1. Write a Composition with enough context that it could adopt existing external resources (e.g. the above annotation propagation, and again matching up any existing required fields).
2. Create an XR, carefully setting its adoption annotations.

**Comment by jbhennin** [comment]
@negz I agree Option 2 is a little awkward and may break your "goals" for composition but it is potentially simpler for us to implement/automate the migration.

**Comment by muvaf** [comment]
Option 2 seems more feasible when it's optional. I'm wondering about how applicable being optional is for other fields you need to fill to adopt a resource. For example, `spec.forProvider.region` is required in most resources, or `spec.forProvider.vpcId` in some resources. If I try to write a `Composition` in that case, I'd need a logic that says `patch this field with information from claim if it is given, if not use this other value`. We don't have this if-condition ability currently and I'm not really sure if we want to have it.

I guess a workaround for that would be that after getting a resource adopted, you can switch to another `Composition` that does not have the adoption logic so new creations flow normally.

**Comment by negz** [comment]
@jbhennin put together an XRD and Composition that can be used to try out option two above:

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: composites3buckets.aws.storage.test.company.com
  labels:
    guide: s3bucket
    provider: aws
    vpc: default
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: storage.test.company.com/v1alpha1
    kind: CompositeS3Bucket
  patchSets:
    - name: Metadata
      patches:
        - fromFieldPath: metadata.annotations
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
            locationConstraint: us-west-2
            versioningConfiguration:
              status: Enabled
            tagging:
              tagSet: []
      patches:
        - type: PatchSet
          patchSetName: Metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.locationConstraint"
        - fromFieldPath: "spec.parameters.version_enabled"
          toFieldPath: "spec.forProvider.versioningConfiguration.status"
        - fromFieldPath: "spec.parameters.tags"
          toFieldPath: "spec.forProvider.tagging.tagSet"
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.annotations[adopt-existing-bucket]
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: composites3buckets.storage.test.company.com
  annotations:
    adopt-existing-bucket:
spec:
  group: storage.test.company.com
  names:
    kind: CompositeS3Bucket
    plural: composites3buckets
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    description: Specifies the Region where the bucket will be created. default to 'us-west-2'.
                  version_enabled:
                    type: string
                    description: The versioning state of the bucket, either Enabled or Suspend, default to 'Enabled'.
                    enum: ["Enabled", "Suspend"]
                  tags:
                    type: array
                    description: Sets the tags for a bucket. Use tags to organize your AWS bill to reflect your own cost structure.
                    items:
                      type: object
                      additionalProperties:
                        type: string
                    example:
                        - key: project_name
                          value: "fu"
                        - key: project_dept
                          value: "bar"
```
