### ISSUE TITLE
Some Fields not Propagated by Composition 

### ISSUE THREAD

**Issue by srueg** [crossplane/crossplane#2158]
### What happened?

Some fields which are defined in a Composition were not propagated to the created managed resources.
The composition includes a Release (from https://github.com/crossplane-contrib/provider-helm) with a `.spec.connectionDetails`. The created `Release` is missing said `.spec.connectionDetails`.

### How can we reproduce it?

Create a composition & composite as follows:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    argocd.argoproj.io/instance: spks-crossplane
    name: 7cfbf56c-7e7b-43fa-8c83-484ee87515d8
    service.syn.tools/cluster: dbaas-redis-prod-01
    service.syn.tools/id: ce33f629-086c-4120-9526-7f263f0ee91f
    service.syn.tools/name: redis-k8s
    service.syn.tools/plan: small
    service.syn.tools/sla: standard
    service.syn.tools/updatable: "true"
spec:
  compositeTypeRef:
    apiVersion: syn.tools/v1alpha1
    kind: CompositeRedisInstance
  resources:
  - base:
      apiVersion: helm.crossplane.io/v1alpha1
      kind: Release
      spec:
        connectionDetails:
        - apiVersion: v1
          fieldPath: status.loadBalancer.ingress[0].ip
          kind: Service
          name: haproxy
          toConnectionSecretKey: endpoint
        forProvider: ...
...
        writeConnectionSecretToRef:
          namespace: spks-crossplane
    patches:
    - fromFieldPath: metadata.labels[crossplane.io/composite]
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-endpoints'
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.labels[crossplane.io/composite]
      toFieldPath: spec.connectionDetails[0].namespace
      type: FromCompositeFieldPath
```

```yaml
apiVersion: syn.tools/v1alpha1
kind: CompositeRedisInstance
metadata:
  creationTimestamp: "2021-02-23T10:41:06Z"
  generation: 2
  labels:
    crossplane.io/composite: c8e5eba0-0286-4a11-b504-aa21da914c1d
    service.syn.tools/cluster: dbaas-redis-prod-01
    service.syn.tools/id: ce33f629-086c-4120-9526-7f263f0ee91f
    service.syn.tools/instance: c8e5eba0-0286-4a11-b504-aa21da914c1d
    service.syn.tools/name: redis-k8s
    service.syn.tools/plan: small
    service.syn.tools/sla: standard
  name: c8e5eba0-0286-4a11-b504-aa21da914c1d
  resourceVersion: "48520554"
  selfLink: /apis/syn.tools/v1alpha1/compositeredisinstances/c8e5eba0-0286-4a11-b504-aa21da914c1d
  uid: 42548e86-bdad-4fa4-963a-ce71fdeb7a97
spec:
  compositionRef:
    name: 7cfbf56c-7e7b-43fa-8c83-484ee87515d8
  resourceRefs:
  - apiVersion: helm.crossplane.io/v1alpha1
    kind: Release
    name: c8e5eba0-0286-4a11-b504-aa21da914c1d-fg9bm
  - apiVersion: v1
    kind: Secret
    name: c8e5eba0-0286-4a11-b504-aa21da914c1d
  - apiVersion: helm.crossplane.io/v1alpha1
    kind: Release
    name: c8e5eba0-0286-4a11-b504-aa21da914c1d-nbrnp
  - apiVersion: helm.crossplane.io/v1alpha1
    kind: Release
    name: c8e5eba0-0286-4a11-b504-aa21da914c1d-xhsp9
status:
  conditions:
  - lastTransitionTime: "2021-02-23T10:41:37Z"
    reason: Available
    status: "True"
    type: Ready
```

### What environment did it happen in?
Crossplane version: v1.0
provider-helm: v0.5.0

**Comment by muvaf** [comment]
@srueg Can you use `Required` patch policy for that specific patch and share the output of `kubectl describe CompositeRedisInstance c8e5eba0-0286-4a11-b504-aa21da914c1d` ?

**Comment by srueg** [comment]
I did some further tests but couldn't get it to work or show any error/logs whatsoever. Unknown fields are just silently dropped which might be happening here?

Manually adding the `spec.connectionDetails` to the composed `Release` works just fine.

**Comment by srueg** [comment]
Apparently the `spec.connectionDetails` get lost somewhere in the call to `r.client.Apply()`: https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/composite/reconciler.go#L451

Adding some debug output shows that the `cd` variable correctly contains the `connectionDetails` before the call and after `Apply()` they're gone.

**Comment by srueg** [comment]
I tried to set a `listType` for the connectionDetails in the CRD, without any luck. For some reason the patch ignores/removes the list of connectionDetails.

https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy

**Comment by srueg** [comment]
I did another test and added a really simple `[]string` field to the Release CRD. It's the same behavior: even if I set the field in the Composition, it's not set on the composed resource. It just gets deleted. I suspect the patch type `application/merge-patch+json` to be somehow the problem but can't really pin it down.

**Comment by hasheddan** [comment]
@srueg I believe you are correct because a merge patch cannot manipulate array elements. You could attempt to patch the entire `connectionDetails` object, but that would require exposing it on the XR / XRC.

**Comment by srueg** [comment]
But the issue with rather with the Kubernetes API patching, not with the Crossplane `patches`. I added some debug logging and clearly see that the rendered resource is correct. Only once applied to the API the lists are dropped.
I also don't understand why even the `Create()` call doesn't create the lists properly: https://github.com/crossplane/crossplane-runtime/blob/master/pkg/resource/api.go#L139

Additionally this would be a problem with all managed resources that include such lists, right?

**Comment by muvaf** [comment]
Hmm that's really interesting. I used the following YAMLs to reproduce:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeredisinstances.syn.tools
spec:
  group: syn.tools
  names:
    kind: CompositeRedisInstance
    plural: compositeredisinstances
  connectionSecretKeys:
    - endpoint
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test-helm
  labels:
    argocd.argoproj.io/instance: spks-crossplane
    name: 7cfbf56c-7e7b-43fa-8c83-484ee87515d8
    service.syn.tools/cluster: dbaas-redis-prod-01
    service.syn.tools/id: ce33f629-086c-4120-9526-7f263f0ee91f
    service.syn.tools/name: redis-k8s
    service.syn.tools/plan: small
    service.syn.tools/sla: standard
    service.syn.tools/updatable: "true"
spec:
  compositeTypeRef:
    apiVersion: syn.tools/v1alpha1
    kind: CompositeRedisInstance
  resources:
  - base:
      apiVersion: helm.crossplane.io/v1alpha1
      kind: Release
      spec:
        forProvider:
          chart:
            name: crossplane
            repository: "crossplane-stable/crossplane"
            version: "1.1.0"
          namespace: crossplane-system
        connectionDetails:
        - apiVersion: v1
          fieldPath: status.loadBalancer.ingress[0].ip
          kind: Service
          name: haproxy
          toConnectionSecretKey: endpoint
        writeConnectionSecretToRef:
          namespace: spks-crossplane
    patches:
    - fromFieldPath: metadata.labels[crossplane.io/composite]
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-endpoints'
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.labels[crossplane.io/composite]
      toFieldPath: spec.connectionDetails[0].namespace
      type: FromCompositeFieldPath
```

Then created an instance and confirmed the behavior @srueg is seeing; after `Apply`, `cd` doesn't have the `spec.connectionDetails` anymore as if it doesn't exist in the target schema and api-server drops it.
```yaml
apiVersion: syn.tools/v1alpha1
kind: CompositeRedisInstance
metadata:
  name: testing
spec: {}
```

What's more interesting is that I created a `Release` object like the following:
```yaml
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: testing-muvaf
spec:
  connectionDetails:
  - apiVersion: v1
    fieldPath: status.loadBalancer.ingress[0].ip
    kind: Service
    name: haproxy
    toConnectionSecretKey: endpoint
  forProvider:
    chart:
      name: crossplane
      repository: crossplane-stable/crossplane
      version: 1.1.0
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: testing-endpoints
    namespace: spks-crossplane
```

It's created successfully and I run the following command successfully with the YAML that has the `spec.connectionDetails[0].namespace`:
```
# /tmp/release.yaml has spec.connectionDetails[0].namespace=crossplane-system
$ kubectl patch release testing-muvaf --type merge --patch "$(cat /tmp/release.yaml)"
```

However, when I try to patch the composed resource with my YAML that has the namespace, I get the following error:
```
# testing-bvdkh is the composed resource name.
# /tmp/release.yaml has spec.connectionDetails[0].namespace=crossplane-system
$ kubectl patch release testing-bvdkh --type merge --patch "$(cat /tmp/release.yaml)"
Error from server: failed to update object (json PATCH for helm.crossplane.io/v1beta1, Kind=Release) managed fields: failed to update ManagedFields: failed to convert new object: .spec.connectionDetails: field not declared in schema
```

So, there is some error that is not returned in client-go. I guess it silents the error and because it's a schema error, it just drops the field. But I'm not sure why we get a schema error in the first place and how it's related to managed fields.

But this didn't explain why it's dropped during the creation. Then I realized that dry-run drops this field, hence run the following command with the exact YAML rendered:
```
$ kubectl create -f /tmp/dry-run.yaml --dry-run
error: error validating "/tmp/dry-run.yaml": error validating data: ValidationError(Release.spec): unknown field "connectionDetails" in io.crossplane.helm.v1alpha1.Release.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

Then I realized, @srueg is using `v1alpha1` version which doesn't have `spec.connectionDetails`. After changing `Composition.spec.resources[0].apiVersion` to `helm.crossplane.io/v1beta1`, everything worked as expected.
