### ISSUE TITLE
Cannot create a composite of SQS and SNS

### ISSUE THREAD

**Issue by wizbit** [crossplane/crossplane#2164]
### What happened?
Creating a composite of SQS and SNSSubscription with arn of the sqs linked into the subscription is failing with an error regarding no being able to patch status

### How can we reproduce it?
XRD
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: pmcsqs.pmconnect.systems
spec:
  defaultCompositionRef:
    name: compositesqs.pmconnect.systems
  group: pmconnect.systems
  names:
    kind: PMCSQS
    plural: pmcsqs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    topicArnRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    filterPolicy:
                      type: string
                  required:
                    - topicArnRef
            status:
              type: object
              properties:
                address:
                  type: string
                arn:
                  type: string
```
XR
```yaml


apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositesqs.pmconnect.systems
  labels:
    provider: pmconnect
spec:
  compositeTypeRef:
    apiVersion: pmconnect.systems/v1alpha1
    kind: PMCSQS
  resources:
    - name: queue
      patches:
        - fromFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: 'staging-%s'
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "sqs-%s"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.arn
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.url
          toFieldPath: status.address
      base:
        apiVersion: sqs.aws.crossplane.io/v1beta1
        kind: Queue
        spec:
          providerConfigRef:
            name: aws-provider
          deletionPolicy: Delete
          writeConnectionSecretToRef:
            namespace: aws
          forProvider:
            region: eu-west-1
    - name: connection
      patches:
        - fromFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: 'staging-sns-sub-%s'
        - fromFieldPath: spec.parameters.topicArnRef
          toFieldPath: spec.forProvider.topicArnRef
        - fromFieldPath: status.arn
          toFieldPath: spec.forProvider.endpoint
          policy:
            fromFieldPath: Required
      base:
        apiVersion: notification.aws.crossplane.io/v1alpha1
        kind: SNSSubscription
        spec:
          providerConfigRef:
            name: aws-provider
          deletionPolicy: Delete
          forProvider:
            region: eu-west-1
            protocol: sqs
  writeConnectionSecretsToNamespace: aws
```

Resources deployed
```yaml
apiVersion: notification.aws.crossplane.io/v1alpha1
kind: SNSTopic
metadata:
  name: test-sns
spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    name: test-sns-devops
    region: eu-west-1
  writeConnectionSecretToRef:
    name: test-sns
    namespace: devops
---
apiVersion: pmconnect.systems/v1alpha1
kind: PMCSQS
metadata:
  name: test-sqs
spec:
  parameters:
    topicArnRef:
      name: test-sns
  writeConnectionSecretToRef:
    name: test-sqs
    namespace: devops
```

### What environment did it happen in?
Crossplane version:  v1.1.0-rc.116.g797d2f61
AWS EKS
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

`kubectl describe pmcsqs test-sqs`
```
Name:         test-sqs
Namespace:
Labels:       crossplane.io/composite=test-sqs
Annotations:  API Version:  pmconnect.systems/v1alpha1
Kind:         PMCSQS
Metadata:
  Creation Timestamp:  2021-02-25T15:02:34Z
  Generation:          2
  Resource Version:    324555244
  Self Link:           /apis/pmconnect.systems/v1alpha1/pmcsqs/test-sqs
  UID:                 a0674159-2a9b-4290-96b1-5be1f9ba3c06
Spec:
  Composition Ref:
    Name:  compositesqs.pmconnect.systems
  Parameters:
    Topic Arn Ref:
      Name:  test-sns
  Write Connection Secret To Ref:
    Name:       test-sqs
    Namespace:  devops
Events:
  Type     Reason                Age                   From                                                             Message
  ----     ------                ----                  ----                                                             -------
  Normal   CompositionSelection  11m                   defined/compositeresourcedefinition.apiextensions.crossplane.io  Default composition has been selected
  Warning  ComposeResources      6m54s (x12 over 11m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot render composed resource from resource template at index 1: cannot apply the patch at index 2: status: no such field
```

`kubectl get pmcsqs test-sqs -o yaml`
```
apiVersion: pmconnect.systems/v1alpha1
kind: PMCSQS
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"pmconnect.systems/v1alpha1","kind":"PMCSQS","metadata":{"annotations":{},"name":"test-sqs"},"spec":{"parameters":{"topicArnRef":{"name":"test-sns"}},"writeConnectionSecretToRef":{"name":"test-sqs","namespace":"devops"}}}
  creationTimestamp: "2021-02-25T15:02:34Z"
  generation: 2
  labels:
    crossplane.io/composite: test-sqs
  name: test-sqs
  resourceVersion: "324555244"
  selfLink: /apis/pmconnect.systems/v1alpha1/pmcsqs/test-sqs
  uid: a0674159-2a9b-4290-96b1-5be1f9ba3c06
spec:
  compositionRef:
    name: compositesqs.pmconnect.systems
  parameters:
    topicArnRef:
      name: test-sns
  writeConnectionSecretToRef:
    name: test-sqs
    namespace: devops
```

`kubectl get managed`
```
NAME                                                                     READY   SYNCED   STATE       VERSION   AGE
replicationgroup.cache.aws.crossplane.io/staging-csm-shared-redis        False   True     modifying   6.x       8d
replicationgroup.cache.aws.crossplane.io/staging-platform-shared-redis   False   True     modifying   6.x       16d
replicationgroup.cache.aws.crossplane.io/staging-product-shared-redis    False   True     modifying   6.x       28d

NAME                                                            VPCID          READY   SYNCED   AGE
cachesubnetgroup.cache.aws.crossplane.io/staging-cache-subnet   vpc-78fe631c   True    True     34d

NAME                                                               READY   SYNCED   ID                     VPC            AGE
securitygroup.ec2.aws.crossplane.io/staging-cache-security-group   False   True     sg-051ef37b60a12228b   vpc-78fe631c   34d

NAME                                                           READY   SYNCED   AGE
iamrole.identity.aws.crossplane.io/pmc-staging-iam-test-role   True    True     10d

NAME                                               READY   SYNCED   TOPIC-NAME        DISPLAY-NAME   AGE
snstopic.notification.aws.crossplane.io/test-sns   True    True     test-sns-devops                  2d1h
```
