### ISSUE TITLE
List Available Compositions for an XR

### ISSUE THREAD

**Issue by jbhennin** [crossplane/crossplane#2179]
### What problem are you facing?
App Devs are primarily separated from the creation of the composition and resource definition process ( as they should be).   
There are scenarios in which one XR could have multiple compositions in order to create a specific set of resources.    
Currently if the app dev is not aware of the available compositions they are unable to utilize the `compositionSelector` feature.

### How could Crossplane help solve your problem?

In order to be able to effectively use the `compositionSelector` feature, we need a way to surface what compositions are available.

If the definition is the main interface for app devs, could we supply the list of available compositions and their purpose here? 

something like:
```
  schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            ......
          compositionSelector:
          .....
```
