### ISSUE TITLE
Resource in endless modification loop

### ISSUE THREAD

**Issue by mf-lit** [crossplane/crossplane#2187]
### What happened?

I'm observing the following issue when managing an RDSInstance with crossplane.
The resource manifest for the RDSInstance is as follows:
```
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: demo-db
spec:
  providerConfigRef:
    name: crossplane-provider-aws  
  forProvider:
    engine: postgres
    engineVersion: "12.5"
    allocatedStorage: 10
    masterUsername: root
    multiAZ: false
    dbInstanceClass: db.t2.small
    region: eu-west-1
    deletionProtection: false
    publiclyAccessible: false
    storageEncrypted: false
    enablePerformanceInsights: false
    skipFinalSnapshotBeforeDeletion: true
    vpcSecurityGroupIds:
      - sg-<redacted>
    dbParameterGroupName: demo-postgres12
    dbSubnetGroupNameRef:
      name: demo-db
  deletionPolicy: Delete
  writeConnectionSecretToRef:
    namespace: crossplane-poc
    name: demo-db

```
Both the instance and the subnetgroup are created succesfully, but the instance constantly goes in and out of a "modifying" state.

The following event appears on the instance resource:
```
Normal  UpdatedExternalResource  4m41s (x78 over 40m)  managed/rdsinstance.database.aws.crossplane.io  Successfully requested update of external resource
```

A bit of digging, and it seems that the ParameterGroup is being "updated" on the instance every few minutes, and so the instance itself keeps flipping-in-and-out-of a `Modifying` state.

I don't understand why this is occurring and I'm so far unable to troubleshoot further, there's nothing logged by the provider to suggest why it's making this change. I appreciate that I should perhaps be opening this issue against the provider and not crossplane, but some general guidance about how to troubleshoot this would be appreciated, thanks.

![image](https://user-images.githubusercontent.com/9348839/109941796-6d5dc800-7ccb-11eb-813f-150105e18421.png)

### What environment did it happen in?
Crossplane version: 1.0
Kubernetes version: (EKS) 1.18, kubectl 1.18
