### ISSUE TITLE
EC2RoleRequestError Event on CacheCluster creation, infra not created

### ISSUE THREAD

**Issue by nrutigs** [crossplane/crossplane#2194]
### What happened?

After applying a `CacheCluster` the infrastructure is not created and I see the following when describing it:

```
k -n crossplane-system describe cachecluster/aws-rediscluster
Name:         aws-rediscluster
Namespace:
Labels:       <none>
Annotations:  crossplane.io/external-name: nrutigliano-crossplane-redis
API Version:  cache.aws.crossplane.io/v1alpha1
Kind:         CacheCluster
Spec:
  For Provider:
    Cache Node Type:  cache.t2.micro
    Cache Security Group Names:
      eks-cluster-sg-sandbox-2090130209
    Cache Subnet Group Name:  VPC-SUBNET-US-WEST-2A-APP-DEFAULT
    Engine:                   redis
    Num Cache Nodes:          1
    Region:                   us-west-2
  Provider Config Ref:
    Name:  aws-config
  Write Connection Secret To Ref:
    Name:       redis-secrets
    Namespace:  crossplane-test
Status:
  At Provider:
    Cache Parameter Group:
    Configuration Endpoint:
    Notification Configuration:
    Pending Modified Values:
  Conditions:
    Last Transition Time:  2021-03-06T00:06:10Z
    Message:               observe failed: cannot describe Cache Cluster: EC2RoleRequestError: no EC2 instance role found
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                         Age                   From                                          Message
  ----     ------                         ----                  ----                                          -------
  Warning  CannotObserveExternalResource  2m54s (x58 over 63m)  managed/cachecluster.cache.aws.crossplane.io  cannot describe Cache Cluster: EC2RoleRequestError: no EC2 instance role found
```

### How can we reproduce it?

I'm trying to create the CacheCluster to be accessible by apps within my EKS cluster. I've recreated my `providerConfig` `aws-config` with new credentials and my AWS account has the following policy attached:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

```
apiVersion: cache.aws.crossplane.io/v1alpha1
kind: CacheCluster
metadata:
  name: aws-rediscluster
  namespace: crossplane-test
  annotations:
    crossplane.io/external-name: nrutigliano-crossplane-redis
spec:
  forProvider:
    region: us-west-2
    engine: redis
    cacheNodeType: cache.t2.micro
    numCacheNodes: 1
    cacheSecurityGroupNames:
      - eks-cluster-sg-sandbox-2090130209
    cacheSubnetGroupName: VPC-SUBNET-US-WEST-2A-APP-DEFAULT
  providerConfigRef:
    name: aws-config
  writeConnectionSecretToRef:
    name: redis-secrets
    namespace: crossplane-test
```

### What environment did it happen in?
Crossplane version: 1.1
Kubernetes: v1.16.15 on EKS
