### ISSUE TITLE
convert transform could not resolve: input type int64 is not supported

### ISSUE THREAD

**Issue by ytsarev** [crossplane/crossplane#2201]
### What happened?

`transforms` fails with
```
  Warning  ComposeResources   22s (x4 over 22s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot render composed resource from resource template at index 0: cannot apply the patch at index 1: transform at index 0 returned error: convert transform could not resolve: input type int64 is not supported
```
in an attempt to convert an integer to string

### How can we reproduce it?

In a CompositeResourceDefinition create integer parameter like
```
                  CostCenter:
                    type: integer
```
in Composition define the transformation:
```
        - fromFieldPath: "spec.parameters.CostCenter"
          toFieldPath: "spec.forProvider.tagging.tagSet[1].value"
          transforms:
            - type: convert
              convert:
                toType: string
```
Apply the claim which contains the integer parameter specified
```
    CostCenter: 12345
```
Observe
```
  Warning  ComposeResources   116s (x12 over 5m56s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot render composed resource from resource template at index 0: cannot apply the patch at index 1: transform at index 0 returned error: convert transform could not resolve: input type int64 is not supported
```
in Composite resource event log

### What environment did it happen in?
Crossplane version: v1.1
