### ISSUE TITLE
Dependencies handling between multiple providers on composite deletion

### ISSUE THREAD

**Issue by haraldatbmw** [crossplane/crossplane#2212]
### What happened?
My use-case causes an deletion issue with my composite-example (see https://github.com/crossplane/crossplane/discussions/2192) which uses Azure and SQL provider. They share a connection-secret inside the same composite. If I delete the claim all resources of the azure-provider (resource-group, postgresql-server, ...) gets deleted but the resources of the sql-provider (database, role, grant) remains. 

The events on the database resource looks like this:
```
Events:
   Type     Reason                   Age                  From                                           Message
   ----     ------                   ----                 ----                                           -------
   Normal   DeletedExternalResource  4m16s                managed/database.postgresql.sql.crossplane.io  Successfully requested deletion of external resource
   Warning  CannotConnectToProvider  16s (x9 over 3m46s)  managed/database.postgresql.sql.crossplane.io  cannot get credentials Secret: Secret "postgresqlserver-admin-d806dbca-e71c-489f-9bee-34bf5b0504de" not found
```

The database resource (sql-provider) uses a secret which was created by the postgresqlserver (azure-provider) which already is deleted.

The ProviderConfig for the sql-provider looks like this:

```
apiVersion: postgresql.sql.crossplane.io/v1alpha1                                                                                                                                                                   
kind: ProviderConfig  
...

spec:
  credentials:
    connectionSecretRef:
      name: postgresqlserver-admin-d806dbca-e71c-489f-9bee-34bf5b0504de
      namespace: crossplane-system
    source: PostgreSQLConnectionSecret
status:
  conditions:
  - lastTransitionTime: "2021-03-09T11:15:07Z"
    message: Blocking deletion while usages still exist
    reason: InUse
    status: "True"
    type: Terminating
  users: 3  
```

### How can we reproduce it?
Deploy the xrd, composite and the claim of example on https://github.com/crossplane/crossplane/discussions/2192.
After successful provisioning delete the claim.

### What environment did it happen in?
Crossplane version: 1.1.0
