### ISSUE TITLE
Provider showing status UnknownPackageRevisionHealth (Version upgrade)

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/crossplane#2217]
### What happened?
New Installation of crossplane v1.1 using helm chart
And also updating the provider aws to v0.17.0

Provider showing `Unknown` status

Error shown from crossplane logs:
```
2021-03-16T07:08:10.647Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ProviderRevision","name":"provider-aws-6b36ca882d8e","uid":"ddd
34f09-db0b-4272-a49b-d4beb54753d2","apiVersion":"pkg.crossplane.io/v1","resourceVersion":"242489702"}, "reason": "SyncPackage", "message": "Successfully configured package
 revision"}
2021-03-16T07:08:10.663Z        ERROR   controller-runtime.manager.controller.packages/providerrevision.pkg.crossplane.io       Reconciler error        {"reconciler group"
: "pkg.crossplane.io", "reconciler kind": "ProviderRevision", "name": "provider-aws-6b36ca882d8e", "namespace": "", "error": "cannot update package revision status: Provid
erRevision.pkg.crossplane.io \"provider-aws-6b36ca882d8e\" is invalid: [status.foundDependencies: Required value, status.installedDependencies: Required value, status.inva
lidDependencies: Required value]", "errorVerbose": "ProviderRevision.pkg.crossplane.io \"provider-aws-6b36ca882d8e\" is invalid: [status.foundDependencies: Required value,
 status.installedDependencies: Required value, status.invalidDependencies: Required value]\ncannot update package revision status\ngithub.com/crossplane/crossplane/interna
l/controller/pkg/revision.(*Reconciler).Reconcile\n\t/home/runner/work/crossplane/crossplane/internal/controller/pkg/revision/reconciler.go:444\nsigs.k8s.io/controller-run
time/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal
/controller/controller.go:293\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/crossplane/crossplane/.work/pk
g/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
.1\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/ut
il/wait.JitterUntilWithContext.func1\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachiner
y/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/
pkg/util/wait.BackoffUntil\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util
/wait.JitterUntil\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Jit
terUntilWithContext\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.U
ntilWithContext\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99\nruntime.goexit\n\t/opt/hostedtoolcache/g
o/1.14.15/x64/src/runtime/asm_amd64.s:1373"}
github.com/go-logr/zapr.(*zapLogger).Error
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:297
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
        /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99
```

ProviderRevisions `events` looks normal:

```
  Normal   SyncPackage        3m18s (x245 over 3h33m)  packages/providerrevision.pkg.crossplane.io  Successfully configured package revision
  Normal   BindClusterRole    2m49s (x290 over 3h33m)  rbac/providerrevision.pkg.crossplane.io      Bound system ClusterRole to provider ServiceAccount(s)
```

ProviderRevision Version as shown: (Notice that DEP-Found and DEP-Installed are empty -> scroll to the right end)
```
NAME                        HEALTHY   REVISION   IMAGE                                                                                             STATE      DEP-FOUND   D
EP-INSTALLED   AGE
provider-aws-3e328e2397f5             5          crossplane/provider-aws:v0.17.0                                                                   Active
               3h34m
provider-aws-6b36ca882d8e   True      4          crossplane/provider-aws:v0.16.0                                                                   Inactive   0           0
               55d
```

kubectl get providerrevisions provider-aws-3e328e2397f5 -o yaml (Does not have `status` shown, suspect status update failed):

```
spec:
  desiredState: Active
  ignoreCrossplaneConstraints: false
  image: crossplane/provider-aws:v0.17.0
  packagePullPolicy: Always
  revision: 5
  skipDependencyResolution: false
```

kubectl get providers provider-aws -o yaml
```
spec:
  ignoreCrossplaneConstraints: false
  package: crossplane/provider-aws:v0.17.0
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
status:
  conditions:
  - lastTransitionTime: "2021-03-12T07:41:20Z"
    reason: UnknownPackageRevisionHealth
    status: Unknown
    type: Healthy
  - lastTransitionTime: "2021-03-15T22:29:29Z"
    reason: ActivePackageRevision
    status: "True"
    type: Installed
  currentIdentifier: crossplane/provider-aws:v0.17.0
  currentRevision: provider-aws-3e328e2397f
```

### How can we reproduce it?
Update Provider resource to new version `0.16.0 -> 0.17.0`

### What environment did it happen in?
Crossplane version: v1.1.0
