### ISSUE TITLE
Composition Selector Transform

### ISSUE THREAD

**Issue by Henni** [crossplane/crossplane#2232]
### What problem are you facing?
I want to build compositions, which depend on other resources and their attributes, which might be created through other compositions. For example I want to pass an AWS subnet to a composition. But instead of the subnet resource name I want the subnetId to be filled in, which I possibly do not know, when composing the XRC.
I want to pass the resource name (e.g. `sample-subnet`) to my XRC and want Crossplane to automatically lookup the proper field (e.g. `status.atProvider.subnetId: subnet-123456`)

```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: sample-subnet
spec:
  [...]
status:
  atProvider:
    subnetId: subnet-123456
```

### How could Crossplane help solve your problem?
I believe Crossplane could solve this quiet nicely by introducing a selector transform:
```yaml
kind: Composition
[...]
patches:
- fromFieldPath: spec.parameters.subnetName
  toFieldPath: spec.forProvider.subnetId
  transform:
    type: selector
    selector:
      # like corev1.ObjectReference https://pkg.go.dev/k8s.io/api/core/v1?utm_source=godoc#ObjectReference
      apiVersion: "ec2.aws.crossplane.io/v1beta1"
      kind: "Subnet"
      fieldPath: "status.atProvider.subnetId"
```

What do you think? Could this be a valuable addition to Compositions?
