### ISSUE TITLE
Claim (and Composite) crossplane.io/external-name annotation not updating

### ISSUE THREAD

**Issue by iAnomaly** [crossplane/crossplane#2249]
### What happened?

1. I created a claim without a `crossplane.io/external-name` annotation
2. I try to add `crossplane.io/external-name` to the claim via Helm OR just via `kubectl edit <claim>` but the annotation doesn't apply. 
3. Querying the claim or the composite for the annotation results in an empty value:
`kubectl get <claim> <name> -o=jsonpath='{.metadata.annotations.crossplane\.io/external-name}'`
`kubectl dev get <composite> <name> -o=jsonpath='{.metadata.annotations.crossplane\.io/external-name}' `
4. `kubectl describe` of the claim or the composite shows the key under annotations but with no value
5. I *think* deleting the claim and recreating will probably resolve this issue but we need to be able to edit claim annotations and have them patch through the layers on change, not just on creation. Am I misunderstanding the current behavior of when annotations and patches reconcile? Does this only occur on creation?

### How can we reproduce it?

xrd and composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeiam.test.com
spec:
  claimNames:
    kind: IAM
    plural: iam
  defaultCompositionRef:
    name: iam
  group: test.com
  names:
    kind: CompositeIAM
    plural: compositeiam
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  policy:
                    type: object
                    properties:
                      document:
                        type: string
                    required:
                    - document
                  role:
                    type: object
                    properties:
                      serviceAccount:
                        type: string
            required:
            - parameters
    served: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: iam
  labels:
    purpose: iam
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: test.com/v1alpha1
    kind: CompositeIAM
  patchSets:
  - name: external-name
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
  resources:
  - name: role
    base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRole
      spec:
        deletionPolicy: Orphan
        providerConfigRef:
          name: provider-aws
    patches:
    - fromFieldPath:  metadata.annotations[crossplane.io/external-name]
      transforms:
        - type: string
          string:
            fmt: "%s-role"
    - fromFieldPath: spec.parameters.role.serviceAccount
      toFieldPath: spec.forProvider.assumeRolePolicyDocument
      transforms:
        - type: string
          string:
            fmt: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {...snip...}
                ]
              }
  - name: policy
    base:
      apiVersion: identity.aws.crossplane.io/v1alpha1
      kind: IAMPolicy
      spec:
        deletionPolicy: Orphan
        providerConfigRef:
          name: provider-aws
    patches:
    - fromFieldPath:  metadata.annotations[crossplane.io/external-name]
      transforms:
        - type: string
          string:
            fmt: "%s-policy"
    - fromFieldPath: spec.parameters.policy.document
      toFieldPath: spec.forProvider.document
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.name
  - name: roleAttachment
    base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRolePolicyAttachment
      spec:
        deletionPolicy: Orphan
        forProvider:
          policyArnSelector:
            matchControllerRef: true
          roleNameSelector:
            matchControllerRef: true
        providerConfigRef:
          name: provider-aws
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositeiam.test.com
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - test.com
  resources:
  - compositeiam
  - compositeiam/status
  - iam
  - iam/status
  verbs:
  - "*"
```

claim:
```
      claim-instance:
        apiVersion: test.com/v1alpha1
        kind: IAM
        metadata:
          annotations:
            crossplane.io/external-name: prefix-{{ requiredEnv "env" }}
        spec:
          parameters:
            policy:
              document: |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {...snip...}
                    ]
                }
            role:
              serviceAccount: prefix-{{ requiredEnv "env" }}
```

### What environment did it happen in?
Crossplane version: v1.1.0
Provider version: provider-aws:v0.17.0
