### ISSUE TITLE
Composite Reconciler Performance

### ISSUE THREAD

**Issue by srueg** [crossplane/crossplane#2256]
### What happened?

I did some further tests and debugging and it seems the limiting factor in our case is not the concurrency of the reconciler but the default rate limiter `DefaultControllerRateLimiter`: https://github.com/kubernetes/client-go/blob/v0.20.1/util/workqueue/default_rate_limiters.go#L39

With around 2000 composites it takes on my local k3d cluster >6 minutes to reconcile all of them. With `longWait  = 1 * time.Minute` for the composite reconciler this means it's constantly reconciling the composites and hitting the rate limit while doing so.
https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/composite/reconciler.go#L46

I think it would make sense to make the `longWait` of the composite reconciler dynamic based on total composite count.
Or at least make it configurable (in our case `10m` would be fine).
That way once all composites are reconciled (e.g. after a restart) new composites can be reconciled much faster and are not rate limited.

Relates to #2157, #2167

### How can we reproduce it?

Setup
```
k apply -f - <<EOF
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeredisinstances.syn.tools
spec:
  connectionSecretKeys: []
  group: syn.tools
  names:
    kind: CompositeRedisInstance
    plural: compositeredisinstances
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
EOF

k apply -f - <<EOF
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test
spec:
  compositeTypeRef:
    apiVersion: syn.tools/v1alpha1
    kind: CompositeRedisInstance
  resources:
  - base:
      apiVersion: v1
      kind: Secret
      stringData:
        test: sometest
    patches:
    - fromFieldPath: metadata.labels[crossplane.io/composite]
      toFieldPath: metadata.name
      type: FromCompositeFieldPath
    - fromFieldPath: kind
      toFieldPath: metadata.namespace
      transforms:
      - map:
          CompositeRedisInstance: default
        type: map
      type: FromCompositeFieldPath
    readinessChecks:
    - type: None

```

Create 2000 composites
```
for i in {1..2000}; do k create -f - <<EOF
apiVersion: syn.tools/v1alpha1
kind: CompositeRedisInstance
metadata:
  generateName: test-
spec:
  compositionRef:
    name: test
EOF ; done
```

### What environment did it happen in?
Crossplane version: `v1.1.1`
