### ISSUE TITLE
Composite resource in tutorial for GCP postgresqlinstance is never ready.

### ISSUE THREAD

**Issue by esn89** [crossplane/crossplane#2266]
### What happened?

I followed the bootstrapping steps here to get started and to play around with Crossplane:
https://crossplane.io/docs/v1.1/getting-started/install-configure.html#using-self-hosted-crossplane

I did the GCP version which involved this step:
`kubectl crossplane install configuration registry.upbound.io/xp/getting-started-with-gcp:v1.1.1`

I have done all the steps and moved onto here:
https://crossplane.io/docs/v1.1/getting-started/provision-infrastructure.html

However, I see that my composite is never ready:

```
kubectl get composite
NAME          READY   COMPOSITION                                             AGE
my-db-rs5th   False   compositepostgresqlinstances.gcp.database.example.org   23h
```

Which, in turn affects my claim:
```
kubectl get claim
NAME    READY   CONNECTION-SECRET   AGE
my-db   False   db-conn             24h
```

Which, finally, affects my `postgresqlinstance`:

```
Status:
  Conditions:
    Last Transition Time:  2021-04-13T21:19:06Z
    Reason:                Composite resource claim is waiting for composite resource to become Ready
    Status:                False
    Type:                  Ready
Events:                    <none>
```

Interestingly enough, when I `describe` the composite, it shows a message of success:

```
Events:
  Type    Reason             Age                   From                                                             Message
  ----    ------             ----                  ----                                                             -------
  Normal  SelectComposition  96s (x2910 over 24h)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully selected composition
 ```
 
### How can we reproduce it?
Simply follow the steps of the tutorial/guide.

### What environment did it happen in?
Crossplane version: 
```
kubectl-crossplane --version
v1.1.1
```

* Cloud provider: GCP 1.18.16-gke.502 

* Kubernetes version (use `kubectl version`)
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes distribution: GKE
* OS (e.g. from /etc/os-release) `PRETTY_NAME="Container-Optimized OS from Google"`
* Kernel (e.g. `uname -a`) `Linux 5.4.89+ x86_64`

**Comment by jbw976** [comment]
Hey there @esn89! Underneath that composite resource will be some lower level resources that directly map to the cloud provider services - e.g. CloudSQL.

You can get some more information by showing all managed resources with:
```
kubectl get managed
```

Does a CloudSQL instance show up there? there may be an event or status condition on that resource that tells you the underlying root cause here.  You may be able to see that with:
```
kubectl describe cloudsqlinstance.database.gcp.crossplane.io
```

**Comment by esn89** [comment]
Thanks.  I found the issue with your `describe` command.  Turns out it was a policy @ Org-level which won't let me have a public IP.

By the way, I am missing something for my PostgreSQL instance, for the `kind: CloudSQLInstance`:

I have set:
```  
writeConnectionSecretToRef:
    name: db-creds
    namespace: backend
```

When I do: 
`kubectl get secrets db-creds -n backend -o yaml`

I get most of the fields, including `username`, but the `password` is no where to be found.  Do you know why that is the case?

**Comment by jbw976** [comment]
Good question.  I'd expect password to be there also, since it's defined as part of the composition: https://github.com/crossplane/crossplane/blob/master/docs/snippets/package/gcp/composition.yaml#L43

Take a look at the other secrets in the `crossplane-system` namespace - does the password show up in the secret for the CompositePostgreSQLInstance? Does password show up in the secret for `CloudSQLInstance`?

Trying to figure out if the password field shows up in any of the layers :)

**Comment by esn89** [comment]
@jbw976 
Oh sorry, I forgot to tell you that I skipped the composite for now.  I am using a regular `CloudSQLInstance` like so:


```
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: my-db
  namespace: default
spec:
  deletionPolicy: "Orphan"
  forProvider:
    databaseVersion: "MYSQL_5_7"
    failoverReplica:
      name: bulkreceiver-db-failover
    instanceType: "CLOUD_SQL_INSTANCE"
    region: "us-central1"
    settings:
      activationPolicy: "ALWAYS"
      availabilityType: "REGIONAL"
      backupConfiguration:
        binaryLogEnabled: true
        enabled: true
        location: "us"
        replicationLogArchivingEnabled: true
        startTime: "18:00"
      dataDiskSizeGb: 20
      dataDiskType: "PD_SSD"
      databaseFlags:
        - name: "log_bin_trust_function_creators"
          value: "on"
      ipConfiguration:
        privateNetwork: "projects/devtestproject/global/networks/vpc"
      locationPreference:
        zone: "us-central1-a"
      maintenanceWindow:
        day: 1
        hour: 16
        updateTrack: "canary"
      tier: "db-n1-standard-2"
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: db-creds
    namespace: backend
```

In this case, the password does not show up in the `db-creds` secrets in the `backend` namespace.

**Comment by jbw976** [comment]
Ah I see you're using CloudSQLInstance directly now. Reviewing the code again now, it seems like we'll try to generate a password after creating the database instance here: https://github.com/crossplane/provider-gcp/blob/master/pkg/controller/database/cloudsql.go#L150-L168

are there any events or status on this CloudSQLInstance that would indicate that creating the initial root user and password is failing?  You've already run `kubectl describe cloudsqlinstances.database.gcp.crossplane.io`, there are no events/status shown in there that may give a hint?

**Comment by esn89** [comment]
@jbw976 

Correct, I am using the CloudSQLInstance directory for the time being.

I haven't had such luck with the events, I have ran the describe on the DB:
`kubectl describe cloudsqlinstances my-db`

```  Conditions:
    Last Transition Time:  2021-04-15T19:11:15Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2021-04-15T19:08:14Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:                    <none>
```

It looks pretty clean to me.  The initial `root` user (the username) is created successfully, I can see that in my secrets:

`kubectl get secrets db-creds -n backend -o yaml`

```
apiVersion: v1
data:
  connectionName: <REDACTED>
  endpoint: <REDACTED>
  privateIP: <REDACTED>
  serverCACertificateCert: <REDACTED>
  serverCACertificateCertSerialNumber: <REDACTED>
  serverCACertificateCommonName: <REDACTED>
  serverCACertificateCreateTime: <REDACTED>
  serverCACertificateExpirationTime: <REDACTED>
  serverCACertificateInstance: <REDACTED>
  serverCACertificateSha1Fingerprint: <REDACTED>
  username: <REDACTED>
kind: Secret
```
