### ISSUE TITLE
Composite resource claim status does not get updated when creating multiple resources

### ISSUE THREAD

**Issue by alexandru-crossover** [crossplane/crossplane#2290]
### What happened?
We are currently using XRCs with a simple XR that combines an SNS topic and a subscription. Quite often we are noticing that the XRC status gets stuck and it does not transition to a Ready state even if the corresponding SNSTopic and SNSSubscription resources are ready. This happens mostly when we have multiple resources created at the same time, but it's not always reproducible. The logs and the resource events are showing  multiple `Operation cannot be fulfilled on compositetopicsubscriptions.core.devflows.io "dev-alex-test-flow-0505-11-506-50511-0-4w6dx": the object has been modified; please apply your changes to the latest version and try again` errors. The logs are also showing reconciler errors:
```
2021-05-06T09:15:11.980Z    ERROR    controller-runtime.manager.controller.composite/compositeapiroutes.core.devflows.io    Reconciler error    {"name": "n-3377-github-listener6-506-5056-master-service-ldwng", "namespace": "", "error": "cannot update composite resource status: Operation cannot be fulfilled on compositeapiroutes.core.devflows.io \"n-3377-github-listener6-506-5056-master-service-ldwng\": the object has been modified; please apply your changes to the latest version and try again", "errorVerbose": "Operation cannot be fulfilled on compositeapiroutes.core.devflows.io \"n-3377-github-listener6-506-5056-master-service-ldwng\": the object has been modified; please apply your changes to the latest version and try again\ncannot update composite resource status\ngithub.com/crossplane/crossplane/internal/controller/apiextensions/composite.(*Reconciler).Reconcile\n\t/home/runner/work/crossplane/crossplane/internal/controller/apiextensions/composite/reconciler.go:532\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:293\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/asm_amd64.s:1373"}
github.com/go-logr/zapr.(*zapLogger).Error
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:297
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
    /home/runner/work/crossplane/crossplane/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99
```
Sometimes we can get the status to be updated if we recreate the crossplane pod or the XR composition, though this does not always help. We are seeing similar behavior with another XR, that combines an API GW route and integration.

### How can we reproduce it?
TopicSubscription XRD:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositetopicsubscriptions.core.devflows.io
spec:
  defaultCompositionRef:
    name: topic-subscription-composition
  group: core.devflows.io
  names:
    kind: CompositeTopicSubscription
    plural: compositetopicsubscriptions
  claimNames:
    kind: TopicSubscription
    plural: topicsubscriptions
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                endpoint:
                  type: string
                protocol:
                  type: string
                region:
                  type: string
                topicName:
                  type: string
              required:
                - endpoint
                - protocol
                - region
                - topicName
            status:
              type: object
              properties:
                subscriptionStatus:
                  type: string
                topicArn:
                  type: string
```

TopicSubscription composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: topic-subscription-composition
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: core.devflows.io/v1
    kind: CompositeTopicSubscription
  resources:
    - name: snstopic
      base:
        apiVersion: notification.aws.crossplane.io/v1alpha1
        kind: SNSTopic
        spec: {}
      patches:
        - fromFieldPath: "spec.topicName"
          toFieldPath: "metadata.name"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.topicName"
          toFieldPath: "spec.forProvider.name"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
          policy:
            fromFieldPath: Required
        - type: ToCompositeFieldPath
          fromFieldPath: "status.atProvider.arn"
          toFieldPath: "status.topicArn"
    - name: snssubscription
      base:
        apiVersion: notification.aws.crossplane.io/v1alpha1
        kind: SNSSubscription
        spec: {}
      patches:
        - fromFieldPath: "spec.topicName"
          toFieldPath: "metadata.name"
          policy:
            fromFieldPath: Required
          transforms:
            - type: string
              string:
                fmt: "%s-subscription"
        - fromFieldPath: "spec.endpoint"
          toFieldPath: "spec.forProvider.endpoint"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.protocol"
          toFieldPath: "spec.forProvider.protocol"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.topicName"
          toFieldPath: "spec.forProvider.topicArnRef.name"
          policy:
            fromFieldPath: Required
        - type: ToCompositeFieldPath
          fromFieldPath: "status.atProvider.status"
          toFieldPath: "status.subscriptionStatus"
```

To reproduce the issue, create 10 TopicSubscriptions in a directory and then `kubectl apply` all of them.

Example TopicSubscription:
```
apiVersion: core.devflows.io/v1
kind: TopicSubscription
metadata:
  name: alex-dev-test-0506510
  namespace: alex-dev
spec:
  endpoint: arn:aws:lambda:us-east-1:346945241475:function:alex-dev-sns-test
  protocol: lambda
  region: us-east-1
  topicName: alex-dev-test-0506510
```
![image](https://user-images.githubusercontent.com/31855210/117284961-1a8dc180-ae70-11eb-8037-3102bbf754f9.png)
![image](https://user-images.githubusercontent.com/31855210/117284984-1feb0c00-ae70-11eb-8573-27e870835700.png)
![image](https://user-images.githubusercontent.com/31855210/117284998-24afc000-ae70-11eb-8e5e-d0a66c4f25d5.png)
![image](https://user-images.githubusercontent.com/31855210/117285013-2a0d0a80-ae70-11eb-8c9a-b3fc6e7fbc6c.png)

### What environment did it happen in?
Crossplane version: 1.1.1
Cloud provider: AWS
Kubernetes version: 1.18.9

**Comment by alexandru-crossover** [comment]
Updates to the TopicSubscription `revisionID` happen every 5 to 60 secondsm with the `reason` field alternating between `Composite resource claim is waiting for composite resource to become Ready` and `cannot update composite resource: Operation cannot be fulfilled on compositetopicsubscriptions.core.devflows.io "alex-dev-test-050651-s4q9v": the object has been modified; please apply your changes to the latest version and try again`.

Updates to the CompositeTopicSubscription `revisionID` happen every 2-3 seconds.

Stopping the Crossplane pod stopped the updates, which confirms that it is the only component trying to update those resources.

**Comment by muvaf** [comment]
Hmm it could have to do with patching `metadata.name`, which we don't really suggest doing. Could you try with removing those patches? You can patch `metadata.annotations[crossplane.io/external-name]` to choose the name of the resource in the provider, or in this case only `spec.forProvider.name` for `SNSTopic` would be enough since it seems external-name is made up of ARN for that resource.

**Comment by alexandru-crossover** [comment]
@muvaf I've removed the `metadata.name` patches and used the `topicArnSelector`:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: topic-subscription-composition
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: core.devflows.io/v1
    kind: CompositeTopicSubscription
  resources:
    - name: snstopic
      base:
        apiVersion: notification.aws.crossplane.io/v1alpha1
        kind: SNSTopic
        spec: {}
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.topicName"
          toFieldPath: "spec.forProvider.name"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
          policy:
            fromFieldPath: Required
        - type: ToCompositeFieldPath
          fromFieldPath: "status.atProvider.arn"
          toFieldPath: "status.topicArn"
    - name: snssubscription
      base:
        apiVersion: notification.aws.crossplane.io/v1alpha1
        kind: SNSSubscription
        spec:
          forProvider:
            topicArnSelector:
              matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.endpoint"
          toFieldPath: "spec.forProvider.endpoint"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.protocol"
          toFieldPath: "spec.forProvider.protocol"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
          policy:
            fromFieldPath: Required
        - type: ToCompositeFieldPath
          fromFieldPath: "status.atProvider.status"
          toFieldPath: "status.subscriptionStatus"
```

This did not help. The `TopicSubscription` status still does not get updated and the same `the object has been modified; please apply your changes to the latest version and try again` messages can be seen in the logs.

I'm also seeing some `Composite resource spec or metadata was patched - terminating reconcile early` messages, but I'm not sure if this is relevant.

**Comment by alexandru-crossover** [comment]
The issue is also reproducible on version 1.2.1. 

Any other info/tests that I can do to further debug this?

**Comment by chlunde** [comment]
I had the same issue with `Composite resource spec or metadata was patched - terminating reconcile early`, but I'm not sure if it is the same issue, but I also use `ToCompositeFieldPath` with a `status` field:

```yaml
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
...
      patches:
        - fromFieldPath: "status.atProvider.arn"
          toFieldPath: "status.bucketArn"
          type: ToCompositeFieldPath
```

I tried the following patch:

```diff
diff --git a/internal/controller/apiextensions/composite/reconciler.go b/internal/controller/apiextensions/composite/reconciler.go
index 688200a6..4a518799 100644
--- a/internal/controller/apiextensions/composite/reconciler.go
+++ b/internal/controller/apiextensions/composite/reconciler.go
@@ -23,6 +23,7 @@ import (
        "github.com/pkg/errors"
        corev1 "k8s.io/api/core/v1"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+       unstructuredv1 "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
        "k8s.io/apimachinery/pkg/runtime/schema"
        "sigs.k8s.io/controller-runtime/pkg/client"
        "sigs.k8s.io/controller-runtime/pkg/manager"
@@ -492,6 +493,14 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
        // We pass a deepcopy because the update method doesn't update status,
        // but calling update resets any pending status changes.
        updated := cr.DeepCopyObject().(client.Object)
+
+       // if we .Update with a different status field, we will get a new
+       // resource version even if the spec and metadata is unchanged, at
+       // least on v1.18.9-eks-d1db3c. The status might be updated due to
+       // a ToCompositeFieldPath patch.
+       updatedObject := updated.(*unstructuredv1.Unstructured).Object
+       delete(updatedObject, "status")
+
        if err := r.client.Update(ctx, updated); err != nil {
                log.Debug(errUpdate, "error", err)
                r.record.Event(cr, event.Warning(reasonCompose, err))
```

To run with a patch:

```bash
kubectl -n crossplane-system scale --replicas=0 deployment/crossplane
make run # github.com/crossplane/crossplane + patch, after logging in to the k8s cluster
# Remember to scale back when done testing
```
