### ISSUE TITLE
RDSInstance: missing masterUsername in secret

### ISSUE THREAD

**Issue by nbenaglia** [crossplane/crossplane#2291]
### What happened?

In a RDSInstance manifest I specified the **writeConnectionSecretToRef** as specified in API (https://doc.crds.dev/github.com/crossplane/provider-aws/database.aws.crossplane.io/RDSInstance/v1beta1@v0.16.0#spec-writeConnectionSecretToRef):

```
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
  ...
   forProvider:
  ...
  masterUsername: admin
  ...
  writeConnectionSecretToRef:
      name: {{ .Release.Name }}-credentials
      namespace: {{ .Release.Namespace}}
```

The created secret doesn't contain the masterUsername as instead expected:

```
{
  "endpoint": "...",
  "password": "...",
  "port": "..."
}
```

### What environment did it happen in?
Crossplane version:  v1.2.1
crossplane/provider-aws-controller: v0.18.0
