### ISSUE TITLE
ToCompositeFieldPath patch doesn't do anything

### ISSUE THREAD

**Issue by bandesz** [crossplane/crossplane#2300]
### What happened?

Tried to use the "ToCompositeFieldPath" patch type to update back some status.atProvider fields to the claim's status. The fields don't get created on the status subresource.

Am I using it wrong?

### How can we reproduce it?

Composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    description: AWS KMS key for encrypting an RDS database
    helm.fluxcd.io/antecedent: kore-crossplane:helmrelease/eks-dev-crossplane-aws-kms
  labels:
    crossplane-configuration: crossplane-aws-kms
    provider: aws
  name: aws-kms-key-rds
spec:
  compositeTypeRef:
    apiVersion: aws.crossplane.kore.appvia.io/v1alpha1
    kind: KMSKey
  resources:
  - base:
      apiVersion: kms.aws.crossplane.io/v1alpha1
      kind: Key
      spec:
        forProvider:
          policy: |-
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": "arn:aws:iam::123123123123:root"
                  },
                  "Action": [
                    "kms:CancelKeyDeletion",
                    "kms:DescribeKey",
                    "kms:GetKeyPolicy",
                    "kms:GetKeyRotationStatus",
                    "kms:ListResourceTags",
                    "kms:ScheduleKeyDeletion"
                  ],
                  "Resource": "*"
                },
                {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": "arn:aws:iam::123123123123:root"
                  },
                  "Action": [
                    "kms:GenerateDataKey",
                    "kms:Decrypt"
                  ],
                  "Resource": "*",
                  "Condition": {
                    "StringEquals": {
                      "kms:ViaService": [
                        "rds.eu-west-2.amazonaws.com"
                      ]
                    }
                  }
                },
                {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": "arn:aws:iam::123123123123:role/kore-service-03cc1f53-3bf0-45c0-a325-6c1a4bf39e40"
                  },
                  "Action": [
                    "kms:DisableKey",
                    "kms:EnableKey",
                    "kms:PutKeyPolicy",
                    "kms:ScheduleKeyDeletion",
                    "kms:TagResource",
                    "kms:UntagResource",
                    "kms:UpdateKeyDescription"
                  ],
                  "Resource": "*"
                }
              ]
            }
          region: eu-west-2
    name: Key
    patches:
    - fromFieldPath: spec.parameters.deletionPolicy
      toFieldPath: spec.deletionPolicy
      type: FromCompositeFieldPath
    - fromFieldPath: status.atProvider.arn
      toFieldPath: status.arn
      type: ToCompositeFieldPath
    - fromFieldPath: status.atProvider.keyID
      toFieldPath: status.keyID
      type: ToCompositeFieldPath
```

XRD:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  annotations:
    description: AWS KMS key
    helm.fluxcd.io/antecedent: kore-crossplane:helmrelease/eks-dev-crossplane-aws-kms
  labels:
    category: cryptography
    crossplane-configuration: crossplane-aws-kms
    provider/aws: "true"
    type: kms
  name: kmskeys.aws.crossplane.kore.appvia.io
spec:
  claimNames:
    kind: KMSKeyInstance
    plural: kmskeyinstances
  group: aws.crossplane.kore.appvia.io
  names:
    kind: KMSKey
    listKind: KMSKeyList
    plural: kmskeys
    singular: kmskey
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              parameters:
                properties:
                  deletionPolicy:
                    default: Delete
                    description: |
                      Specifies what will happen to the KMS key when this resource is deleted - either `Delete` or `Orphan`.
                    enum:
                    - Delete
                    - Orphan
                    type: string
                required:
                - deletionPolicy
                type: object
            required:
            - parameters
            type: object
        type: object
    served: true
```

Claim:
```
apiVersion: aws.crossplane.kore.appvia.io/v1alpha1
kind: KMSKeyInstance
metadata:
  annotations:
    crossplane.io/external-name: ""
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"aws.crossplane.kore.appvia.io/v1alpha1","kind":"KMSKeyInstance","metadata":{"annotations":{},"name":"kms-test","namespace":"crossplane-test"},"spec":{"compositionRef":{"name":"aws-kms-key-rds"},"parameters":{"deletionPolicy":"Delete"}}}
  name: kms-test
  namespace: crossplane-test
spec:
  compositionRef:
    name: aws-kms-key-rds
  parameters:
    deletionPolicy: Delete
  resourceRef:
    apiVersion: aws.crossplane.kore.appvia.io/v1alpha1
    kind: KMSKey
    name: kms-test-vnpx8
status:
  conditions:
  - lastTransitionTime: "2021-05-11T11:44:16Z"
    reason: Available
    status: "True"
    type: Ready
```

Key resource:
```
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    crossplane.io/composition-resource-name: Key
    crossplane.io/external-name: 5ab34d58-03cd-4fbb-b111-837e01c75045
  creationTimestamp: "2021-05-11T11:43:45Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  labels:
    crossplane.io/claim-name: kms-test
    crossplane.io/claim-namespace: crossplane-test
    crossplane.io/composite: kms-test-vnpx8
  name: kms-test-vnpx8-ws4xg
  ownerReferences:
  - apiVersion: aws.crossplane.kore.appvia.io/v1alpha1
    controller: true
    kind: KMSKey
    name: kms-test-vnpx8
    uid: 71d9fb34-0b4d-40c8-bdd6-6eae71aa7008
spec:
  deletionPolicy: Delete
  forProvider:
    enabled: true
    policy: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::123123123123:root"
            },
            "Action": [
              "kms:CancelKeyDeletion",
              "kms:DescribeKey",
              "kms:GetKeyPolicy",
              "kms:GetKeyRotationStatus",
              "kms:ListResourceTags",
              "kms:ScheduleKeyDeletion"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::123123123123:root"
            },
            "Action": [
              "kms:GenerateDataKey",
              "kms:Decrypt"
            ],
            "Resource": "*",
            "Condition": {
              "StringEquals": {
                "kms:ViaService": [
                  "rds.eu-west-2.amazonaws.com"
                ]
              }
            }
          },
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::123123123123:role/kore-service-03cc1f53-3bf0-45c0-a325-6c1a4bf39e40"
            },
            "Action": [
              "kms:DisableKey",
              "kms:EnableKey",
              "kms:PutKeyPolicy",
              "kms:ScheduleKeyDeletion",
              "kms:TagResource",
              "kms:UntagResource",
              "kms:UpdateKeyDescription"
            ],
            "Resource": "*"
          }
        ]
      }
    region: eu-west-2
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:kms:eu-west-2:123123123123:key/5ab34d58-03cd-4fbb-b111-837e01c75045
    awsAccountID: "123123123123"
    creationDate: "2021-05-11T11:43:46Z"
    enabled: true
    encryptionAlgorithms:
    - SYMMETRIC_DEFAULT
    keyID: 5ab34d58-03cd-4fbb-b111-837e01c75045
    keyManager: CUSTOMER
    keyState: Enabled
  conditions:
  - lastTransitionTime: "2021-05-11T11:43:46Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2021-05-11T11:43:46Z"
    reason: Available
    status: "True"
    type: Ready
```

### What environment did it happen in?
Crossplane version: v1.2.1
AWS provider: v0.18.0

**Comment by janwillies** [comment]
You need to specify the status subresource in the xrd: 
```yaml
# The status subresource can be optionally defined in the XRD
          # schema to allow observed fields from the composed resources
          # to be set in the composite resource and claim.
          status:
            type: object
            properties:
              address:
                description: Address of this MySQL server.
                type: string
```
