### ISSUE TITLE
Provide a way to use composed resource fields in connectionDetails

### ISSUE THREAD

**Issue by fsniper** [crossplane/crossplane#2302]
### What problem are you facing?
I am currently working with xrds and composites with provider-sql. The composed resources (database.postgresql) gets a generated name to prevent resource collisions. As Crossplane resources are cluster scoped, naming can be an issue unless random strings are used. 

Here I would like to have the composite define connection secrets with values from  composed_resource->metadata.name or composed_resource->spec.paramaters.any_param. 

### How could Crossplane help solve your problem?
Crossplane could implement a connectionDetails function fromComposedField or alike.
```
    connectionDetails:
    - fromComposedField: metadata.name
```

**Comment by negz** [comment]
I was just going to take a quick stab at this, and realised it's actually possible already if folks feel okay with having an extra step. We don't currently support directly surfacing a _composed_ resource fields as connection details, but we do support:

1. Patching the value from a composed resource field to a composite resource field.
2. Exposing a composite resource field as a connection detail.

So in your use case for example, you could expose the `metadata.name` of the composed `Database` as a field of your composite resource - let's say `status.dbName` then expose that as a connection detail using the [`FromFieldPath` connection detail](https://github.com/crossplane/crossplane/blob/v1.3.0/apis/apiextensions/v1/composition_types.go#L774). This would look something like:


```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
# etc...
spec:
  resources:
  - base:
      apiVersion: mysql.crossplane.io/v1alpha1
      kind: Database
      spec:
        # etc...
    patches:
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: status.dbName
    connectionDetails:
    - type: FromFieldPath
      name: database-name
      fromFieldPath: status.dbName
```

It's also worth noting that the actual name of the database is not fundamentally non-deterministic. You can set the `crossplane.io/external-name` annotation on the `Database` resource to specify the name you'd like to use for the database. e.g.:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
# etc...
spec:
  resources:
  - base:
      apiVersion: mysql.crossplane.io/v1alpha1
      kind: Database
      metadata:
        annotations:
          # The actual SQL database will be named 'my-database' regardless of the
          # metadata.name of the Database managed resource. You could also patch
          # this in from the composite resource to make it configurable.
          crossplane.io/external-name: my-database
      spec:
        # etc...

```
