### ISSUE TITLE
Explain how to enable the debug flag in the troubleshooting-doc

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#2304]
### What problem are you facing?
I wanted to enable debug logging. I went to the troubleshooting doc, and thought I had to modify the provider deployment and pause crossplane to do it. It turns out there is a CRD for it..

### How could Crossplane help solve your problem?
Add example under troubleshooting docs
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
...
spec:
  args:
  - --debug
```
