### ISSUE TITLE
Crossplane Support for String transforms

### ISSUE THREAD

**Issue by librannk** [crossplane/crossplane#2336]
Feature to transform Strings
In order to handle dependencies between two compositions, I created a higher level composition which worked but I am facing now issue with transforming the values returned and while looking for transforming options I found only below ones
1) map
2) math 
3) fmt

there isn't an option to transform strings like trim, substring, etc.

Exact UseCase :
1) creating HostedZone in AWS
2) need hosted zone id for other services, thereby using status.atProvider.hostedZone.id
3) hosted zone id is coming like  Hosted Zone Id:         /hostedzone/Z098DDXXFEEGGSS
4) need to trim the zone id "Z098DDXXFEEGGSS" from the above

**Comment by negz** [comment]
This seems quite reasonable and self contained. Do you want to take a shot at sketching out an API for these features here in the issue?

**Comment by librannk** [comment]
yes, i can give it a shot, not a pro in go though :) ..
also, there is 1 more related issue created by me: https://github.com/crossplane/provider-aws/issues/682

**Comment by psinghal20** [comment]
Hi @negz @librannk, I took a look at this issue and the current implementation of the string transform. What do you think about adding different string operations as separate transforms? I was thinking of adding one initially for Trim and Substring:
```
trim:
    suffix: '-test' # remove '-test' suffix from string
    prefix: '/hostedzone/' # remove '/hostedzone/' prefix from string
    whitespace: true # remove whitespace, we can make this default true I think
substring:
    start: <Start index in string>
    end: <End index in string>
```
One other thing we can do is group all these string transforms together under `string` transform and add another `type` subfield under it. Something like this:
```
string:
    type: fmt/trim/substring
    fmt:
    trim:
    substring:
```
In the first scenario, there would not be a redundant type subfield which I kind of like but in the second case, we would be able to group similar types of string transforms under a single group. Let me know what do you guys think! :smile:
