### ISSUE TITLE
Improve DX for conditional patching in Composition API

### ISSUE THREAD

**Issue by tohjustin** [crossplane/crossplane#2364]
### What problem are you facing?

I'm creating a composition with the `Queue` managed resource from [provider-aws](https://doc.crds.dev/github.com/crossplane/provider-aws/sqs.aws.crossplane.io/Queue/v1beta1@v0.18.1) to allow namespace-isolated tenants in our clusters to provision SQS queues.

- To implement namespace isolation (i.e. a `Queue` provisioned by an XRC cannot reference another `Queue` with different claim namespace as its dead-letter queue), I would patch the XR's `spec.forProvider.redrivePolicy.deadLetterTargetArnSelector.matchLabels[crossplane.io/claim-namespace]` field to ensure that the selector can only match with other `Queues` that has the same claim namespace.
- However this patch should only happen when the XRC creator wants their Queue managed resource to have a dead-letter queue (i.e. `spec.redrivePolicy.deadLetterTargetRef` field in the XRC isn't empty).

Implementing this composition would require conditional patching (i.e. patch from field B only if field A exists) which seems to be achievable by using the `CombineFromComposite` patch type with `Optional` patch policy.

Here's my attempt to achieve this:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  resources:
  - patches:
    - fromFieldPath: spec.redrivePolicy.deadLetterTargetRef
      toFieldPath: spec.forProvider.redrivePolicy.deadLetterTargetArnSelector.matchLabels[crossplane.io/claim-name]
    # The patch below only happens when `spec.redrivePolicy.deadLetterTargetRef` exists
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.redrivePolicy.deadLetterTargetRef
        - fromFieldPath: metadata.labels[acme.co/namespace]
        strategy: string
        string:
          # `%.s` below is to omit the `spec.redrivePolicy.deadLetterTargetRef` value
          # since we only want the value of `metadata.labels[acme.co/namespace]`
          # for patching `deadLetterTargetArnSelector.matchLabels[crossplane.io/claim-namespace]`
          fmt: "%.s%s"
      toFieldPath: spec.forProvider.redrivePolicy.deadLetterTargetArnSelector.matchLabels[crossplane.io/claim-namespace]
      transforms:
      - type: string
        string:
          fmt: “%s”
  # ...
```

### How could Crossplane help solve your problem?

Provide a nicer (& perhaps more powerful?) API to perform conditional patching in Compositions
