### ISSUE TITLE
Labelled Resources created via XRC's are not pruned with "kubectl apply --prune -l <labels>"

### ISSUE THREAD

**Issue by rkr-kununu** [crossplane/crossplane#2365]
### What happened?
I'm evaluating Crossplane v1.2.2.  One _alpha_ feature we use heavily is kubectl's [prune](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#alternative-kubectl-apply-f-directory-prune-l-your-label) option.

For other non-crossplane CRD's, for example Traefik v2, the prune option works as expected.  However, for resources constructed by using defined XRC's, they seem to be ignored by "--prune".

### How can we reproduce it?

I'm rather new to Crossplane, but I hope it's as easy as add a label to a resource constructed using an XRC.  This is what I'm using:

`original.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kun-namespace: use-xrd-interface
  labels:
    evaluate.com/bundle: use-xrd-interface
  name: use-xrd-interface
---
apiVersion: resources.evaluate.it/v1alpha1
kind: Bucket
metadata:
  labels:
    evaluate.com/bundle: use-xrd-interface
  name: rkr-test-bucket-v2
  namespace: use-xrd-interface
spec:
  parameters:
    location: au-east
    storageGB: 20
    version: "5.7"
  writeConnectionSecretToRef:
    name: rkr-test-bucket-v2-results-v2
```

`modified.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kun-namespace: use-xrd-interface
  labels:
    evaluate.com/bundle: use-xrd-interface
  name: use-xrd-interface
```

Once applied (assuming you've already created an XRC for "compositebuckets.resources.evaluate.it/v1alpha1"): `kubectl apply -f original.yaml`

Then run: `kubectl apply -f ./modified.yaml --prune -l 'evaluate.com/bundle in (use-xrd-interface)'`

I would expect "bucket.resources.evaluate.it/rkr-test-bucket-v2" to be pruned.

One additional observation (which may or may not be related):
If I run:
```
$ kubectl get all -l 'evaluate.com/bundle in (use-xrd-interface)' -n use-xrd-interface
No resources found in use-xrd-interface namespace.
```

However, if I run:
```
$ kubectl get bucket.resources.evaluate.it -l 'evaluate.com/bundle in (use-xrd-interface)' -n use-xrd-interface
NAME                 READY   CONNECTION-SECRET               AGE
rkr-test-bucket-v2   False   rkr-test-bucket-v2-results-v2   47m
```

I wonder if Crossplane is not "hooking" into whatever Kubernetes claims as `all`.  If so, then I can see how the prune feature would miss those resources too.

### What environment did it happen in?
Crossplane version: v1.2.2
Crossplane provider-aws: v0.18.1
Kubernetes distro: k3s
Kubectl version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10+k3s2", GitCommit:"a095b455f6c0dce0a463f9283013f07e2321e5c3", GitTreeState:"clean", BuildDate:"2020-10-30T19:28:08Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
