### ISSUE TITLE
Overwrite package parameters in configuration 

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#2367]
### What problem are you facing?

We use a custom Docker registry to deploy Crossplane and its providers. Currently, `meta.pkg.crossplane.io/Configuration` provides no way to overwrite provider package configurations, such as the controller image. The only way is to rebuild the packages directly.

An alternative would be to deploy `pkg.crossplane.io/Provider` directly together with a `pkg.crossplane.io/ControllerConfig` without using configurations.

### How could Crossplane help solve your problem?

Crossplane configurations should expose a method to reference a `ControllerConfig` for each provider (and maybe include it in  the package?) to allow modifying the default settings of the provider package. Something like this:

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: my-crossplane
spec:
  crossplane:
    version: ">=v1.1.0"
  dependsOn:
    - provider: my.custom.registry/crossplane/provider-aws
      controllerConfigRef:
        name: provider-aws
      version: "v0.18.0"
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws
spec:
  image: my.custom.registry/crossplane/provider-aws-controller:v0.18.0
  replicas: 1
  args: []
```
