### ISSUE TITLE
ControllerConfig with provider-aws: Kube permissions denied when running with LEADER_ELECTION: true

### ISSUE THREAD

**Issue by stephenrlouie** [crossplane/crossplane#2372]
### What happened?

[origin slack thread](https://crossplane.slack.com/archives/C01718T2476/p1623689121130700)
I wanted to try the aws-provider in HA mode and found that after increasing the replica count and enabling the LEADER_ELECTION env variable I began running into permissions problems with kubernetes. First was a denial on `leases` and second was a permission denied on `configmaps`. The fix is making the proper rolebinding to the service account. I'm not certain why changing the configuration like this would impact existing bindings.

### How can we reproduce it?

Deploy the AWS provider with ControllerConfig set to `replica: 1` and env `LEADER_ELECTION: false`. 

```
provider-aws-0113aaace17b-6f766dc997-n7f7k › provider-aws
provider-aws-0113aaace17b-6f766dc997-n7f7k provider-aws I0615 12:28:05.566489       1 request.go:655] Throttling request took 1.029475498s, request: GET:https://172.20.0.1:443/apis/scheduling.k8s.io/v1beta1?timeout=32s
```

Update ControllerConfig to have 3 replicas and `LEADER_ELECTION=true` to see the broken permissions.
```
provider-aws-0113aaace17b-777d6bf9d4-2gdp7 provider-aws E0615 12:30:31.433255       1 leaderelection.go:325] error retrieving resource lock crossplane-dev/crossplane-leader-election-provider-aws: leases.coordination.k8s.io "crossplane-leader-election-provider-aws" is forbidden: User "system:serviceaccount:crossplane-dev:provider-aws-0113aaace17b" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "crossplane-dev"
provider-aws-0113aaace17b-777d6bf9d4-j4l5k provider-aws E0615 12:30:32.440502       1 leaderelection.go:325] error retrieving resource lock crossplane-dev/crossplane-leader-election-provider-aws: leases.coordination.k8s.io "crossplane-leader-election-provider-aws" is forbidden: User "system:serviceaccount:crossplane-dev:provider-aws-0113aaace17b" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "crossplane-dev"
```
I was able to fix by setting the rolebinding for the service-account to the `ClusterRole: crossplane`. 

#### Kube Yamls
[Essentially copies from the public docs](https://crossplane.io/docs/v1.2/concepts/packages.html#speccontrollerconfigref)
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: "crossplane/provider-aws:master"
  controllerConfigRef:
    name: aws-config
```

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
spec:
  replicas: 3 
  env:
    - name: LEADER_ELECTION
      value: "true"
```

### What environment did it happen in?
Crossplane version: 1.2.2 (deployed from the helm chart)
Cloud provider: Amazon/EKS 
Kubernetes Version: 1.18.16
