### ISSUE TITLE
ConnectionDetails secret fails to populate with multiple resources

### ISSUE THREAD

**Issue by wizbit** [crossplane/crossplane#2376]
### What happened?
ConnectionDetails are not updated if more than one resource is defined in a composite.
The secret `topic-testing` is created but empty, removing the resource `Publish` causes the secret to be populated.

### How can we reproduce it?
XRD
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: testtopics.pmconnect.systems
spec:
  defaultCompositionRef:
    name: testnotification.pmconnect.systems
  group: pmconnect.systems
  names:
    kind: TestTopic
    plural: testtopics
  connectionSecretKeys:
    - endpoint
    - test
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    team:
                      description: The team that the queue belongs to.
                      type: string
                  required:
                    - team
            status:
              type: object
              properties:
                arn:
                  type: string
                  description: ARN is the Amazon Resource Name (ARN) specifying the SNS Topic.
```

XR
```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  name: testnotification.pmconnect.systems
  labels:
    provider: pmconnect
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: pmconnect.systems/v1alpha1
    kind: TestTopic
  resources:
    - name: Topic
      base:
        apiVersion: notification.aws.crossplane.io/v1alpha1
        kind: SNSTopic
        spec:
          providerConfigRef:
            name: aws-provider
          deletionPolicy: Delete
          forProvider:
            name: null
            displayName: null
            region: eu-west-1
            tags:
              - key: "pmc:team"
                value: null
      patches:
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.name"
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.displayName"
        - fromFieldPath: spec.parameters.team
          toFieldPath: spec.forProvider.tags[0].value
        - fromFieldPath: status.atProvider.arn
          toFieldPath: status.arn
          type: ToCompositeFieldPath
      connectionDetails:
        - name: endpoint
          type: FromFieldPath
          fromFieldPath: status.atProvider.arn
        - name: test
          type: FromValue
          value: "42"
    - name: Publish
     base:
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMPolicy
        spec:
          providerConfigRef:
            name: aws-provider
          deletionPolicy: Delete
      patches:
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.name"
          transforms:
            - type: string
              string:
                fmt: "%s-publish"
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.document"
          transforms:
            - type: string
              string:
                fmt: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Sid": "Publish",
                        "Effect": "Allow",
                        "Action": "sns:Publish",
                        "Resource": "arn:aws:sns:*:*:%s-publish"
                      }
                    ]
                  }
```

Object
```yaml
apiVersion: pmconnect.systems/v1alpha1
kind: TestTopic
metadata:
  name: testing
  namespace: default
spec:
  parameters:
    team: test
  writeConnectionSecretToRef:
    name: topic-testing
    namespace: default
```

### What environment did it happen in?
Crossplane version: v1.1.1
Kubernetes version: 1.17
Kubernetes distribution: EKS
