### ISSUE TITLE
Add static label to providers identifying the package

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#2398]
### What problem are you facing?
We have installed `provider-sql` using the `Provider` CRD. I would like to restart the deployment using a predictable name, and add security groups to the pods, but the names of the pods/deployments are generated. One way to achieve this would be to use label selectors.

```
apiVersion: pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: crossplane-provider-sql
spec:
  package: crossplane/provider-sql:v0.2.0
```
```
    labels:
      pkg.crossplane.io/revision: crossplane-provider-sql-16bdf1af9403
      pod-template-hash: 997d559fb
```

### How could Crossplane help solve your problem?
Add a label at least for the package name, without tags. It might be useful to add more labels too as they will show up in prometheus etc.
