### ISSUE TITLE
Rendered Annotations on Managed Resources Get Lost if a Patch on the root Annotations Object is Specified

### ISSUE THREAD

**Issue by ulucinar** [crossplane/crossplane#2416]
### What happened?

This is one of the three issues that surfaced when discussing #2211. 
As discussed [here](https://github.com/crossplane/crossplane/issues/2211#issuecomment-853889836), if a patch from XR to MR (managed resource) is defined on the root `metadata.annotations` object, and if the XR has a non-zero `metadata.annotations` map, then for instance, the `crossplane.io/composition-resource-name` annotation, which is added during the rendering of the composed from its template base, is lost. 

Conceptually this is similar to #2211, however, in my opinion, this is a bug in the XR reconciler when it invokes `APIDryRunRenderer.Render` to render a composed. `APIDryRunRenderer.Render` loses the `crossplane.io/composition-resource-name` annotation it adds [here](https://github.com/crossplane/crossplane/blob/589f8c337f516a4f3f8e47e73aeaeee8d0158ca7/internal/controller/apiextensions/composite/composed.go#L345) when applying the patches [here](https://github.com/crossplane/crossplane/blob/589f8c337f516a4f3f8e47e73aeaeee8d0158ca7/internal/controller/apiextensions/composite/composed.go#L356), if there exists a patch from XR to composed on `metadata.annotations` and if XR has non-zero annotations. 

I propose to unconditionally merge the paths `metadata.annotations` and `metadata.labels` disallowing overrides of already existing values when applying patches. This is different than adding a new patch specification API that will control how objects are replaced/merged. 

Another question is should we allow a patch to be defined on certain other paths like `metadata.name`, `metadata.namespace`. etc. that also get rendered at the same site? My proposal would be just to make such patch specifications ineffective, and even with an admission controller disallow them.

Without #2353, this problem is amplified because we get an empty superfluous external-name annotation on the XR that satisfies one of the preconditions of the issue reported here.

### How can we reproduce it?

As a result of a claim such as this:
```
apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  annotations:
    crossplane.io/external-name: name-from-claim
...
```
and a selected composition such as:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
...
spec:
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.annotations
      type: FromCompositeFieldPath
...
```
you get a composed such as this:
```
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/external-name: name-from-claim
  generation: 1
...
```
where the `crossplane.io/composition-resource-name` annotation gets lost. Of course, the same problem exists for other rendered fields.

### What environment did it happen in?
Crossplane version: 1.3
