### ISSUE TITLE
Unreliable/intermittent creation of composite secrets

### ISSUE THREAD

**Issue by mf-lit** [crossplane/crossplane#2417]
### What happened?

<details>
<summary><code>claim</code></summary>

```yaml
apiVersion: crossplane.example/v1alpha1
kind: MarcQueue 
metadata:
  name: marctest
  labels:
    marc: test
  annotations:
    crossplane.io/external-name: marctest
spec:
  parameters:
    tags:
      managed_by: crossplane
      foo: bar
  writeConnectionSecretToRef:
    name: marctest-queue
```

</details>

<details>
<summary><code>xrd</code></summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: marcqueuecomposites.crossplane.example
spec:
  claimNames:
    kind: MarcQueue
    plural: marcqueues
  connectionSecretKeys:
  - url
  - arn
  - endpoint
  defaultCompositionRef:
    name: marcqueuecomposite
  group: crossplane.example
  names:
    kind: MarcQueueComposite
    plural: marcqueuecomposites
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              parameters:
                properties:
                  deletionPolicy:
                    description: Delete or Orphan resource on deletion
                    type: string
                  kmsMasterKeyId:
                    description: KMS Key Alias
                    type: string
                  region:
                    description: Region for queue
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    description: AWS resource tags
                    type: object
                type: object
            required:
            - parameters
            type: object
        type: object
    served: true
```

</details>

<details>
<summary><code>composition</code></summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: marcqueuecomposite
spec:
  compositeTypeRef:
    apiVersion: crossplane.example/v1alpha1
    kind: MarcQueueComposite
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.labels
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.annotations
      type: FromCompositeFieldPath
  resources:
  - base:
      apiVersion: sqs.aws.crossplane.io/v1beta1
      kind: Queue
      spec:
        deletionPolicy: Orphan
        forProvider:
          kmsMasterKeyId: alias/aws/sqs
          region: eu-west-1
          tags:
            managed_by: crossplane
        providerConfigRef:
          name: crossplane-provider-aws
        writeConnectionSecretToRef:
          namespace: crossplane
    connectionDetails:
    - fromFieldPath: status.atProvider.url
      name: url
      type: FromFieldPath
    - fromFieldPath: status.atProvider.arn
      name: arn
      type: FromFieldPath
    - fromConnectionSecretKey: endpoint
    patches:
    - patchSetName: Metadata
      type: PatchSet
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-marcqueue'
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.tags
      toFieldPath: spec.forProvider.tags
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameter.kmsMasterKeyId
      toFieldPath: spec.forProvider.kmsMasterKeyId
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameter.deletionPolicy
      toFieldPath: spec.deletionPolicy
      type: FromCompositeFieldPath
  writeConnectionSecretsToNamespace: crossplane
```

</details>

We're seeing some really bizarre behaviour around the creation of composite secrets. With the xrd and composition above we're finding that only one composite secret key is written (`arn`) and the other two (`url` and `endpoint`) are never populated.

We've also experimented with reducing the number of secrets to one. When this one secret is `arn`, it works pretty reliably, but when it's `url` it's incredibly hit-and-miss, most often the key is never created but occasionally it is with no apparent pattern.

FWIW, setting `--debug` doesn't reveal anything useful, we just see positive messages like:
`DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"MarcQueueComposite","name":"marctest-4vbss","uid":"fd1d0323-b25f-4e88-9fc6-5680f5357b72","apiVersion":"crossplane.example/v1alpha1","resourceVersion":"5179122"}, "reason": "PublishConnectionSecret", "message": "Successfully published connection details"}`

Also, there's never any problem with the MR secret being populated (when we configure the composition accordingly), only the composite secret and claim secret have issues.

I wish I could be a bit more explicit in this report, but despite spending a few hours trying to figure this out we're more confused than ever! Clearly the behaviour is incorrect, but we just can't identify a pattern. I'm more than willing to spend time narrowing this down further (this issue is a serious problem for us) but need to reach out for some help with next steps please. We're pretty lost with this right now.

Possibly related:
https://github.com/crossplane/crossplane/issues/2376
https://github.com/crossplane/crossplane/issues/2253

### What environment did it happen in?
Crossplane version:  1.13.0 (also 1.11.1)
AWS provider: 0.19.0 (also 0.18.0)
Kubernetes version: 1.19 (EKS)

**Comment by hasheddan** [comment]
@mf-lit your Crossplane version is listed as `1.13.0`, which is not an existing version. Did you mean `1.3.0` or possibly `1.1.3`? Also, would you be able to provide (obscured) managed resource secret and the `Queue` managed resource itself? I wonder if those fields are being intermittently wiped from the status / connection secret of the managed resource somehow.

**Comment by hasheddan** [comment]
Also noting here from #2253:
> This particular XR is for SQS queues, we have other XRs (for IAM and RDS for example) that have no problem with this. (So I guess this might be an issue with the provider not crossplane-core, but opening it here since I'm unsure).

Are you still only seeing this happen with `Queue`?

**Comment by mf-lit** [comment]
Ah yes, that was a typo sorry - I meant 1.3.0

(MR was sent by DM)

Yes, we're only seeing this with Queue still.

The other two composites we're using extensively are for RDS and IAM:
The RDS composite has four connection secrets (all of which are `fromConnectionSecretKey`), we've had no such issues with it.
The IAM composite has a single secret which is `fromFieldPath: "status.atProvider.arn"`, again no issues.

We're working on a DynamoDB composite today actually, I'll update if we have interesting behaviour with that one.

**Comment by iAnomaly** [comment]
@mf-lit Thanks for creating this issue and #2253. I've now gone down the rabbit hole trying to get things working and also using `Queue`. I'm going to document the journey here and hopefully clarify for others and maybe even provide an explanation for what you are seeing.

### What environment did it happen in?
Crossplane version: 1.7.0
AWS provider: 0.26.0
Kubernetes version: 1.22 (EKS)

First, it took me a lot of trial and error to wrap my head around how `writeConnectionSecretToRef` works at different layers and there are three of them:
1. Using `writeConnectionSecretToRef` at the Managed Resource layer. That is, you can/could set `writeConnectionSecretToRef` on MRs themselves such as directly on a `Queue`. You are doing this in your example above for the `writeConnectionSecretToRef.namespace` when you include this field on your `Composition.spec.resources[0].base`:
```yaml
        writeConnectionSecretToRef:
          namespace: crossplane
````

2. The second layer is the Composite (XR) layer as defined ABOVE/OUTSIDE `Composition.spec.resources` in the Composition. The field to use there is `writeConnectionSecretsToNamespace`. It does not appear you can set the Secret name for this layer as the current behavior appears to create a Secret of `type` `connection.crossplane.io/v1alpha1` named as the XR's `metadata.uid`.

3. Finally, there is a third layer if you are instantiating your XR through a Claim. At this layer `namespace` isn't even accepted as a property to `writeConnectionSecretToRef` and it appears the Claim's controller tries to copy/propagate the contents of the XR layer Secret (the one of type `connection.crossplane.io/v1alpha1`) into the secret name you specify under `writeConnectionSecretToRef.name` in the Claim AT THE SAME NAMESPACE AS THE CLAIM ITSELF (remember, Claims are a namespaced construct where XRs and MRs are not). I'm actually seeing errors here like `cannot propagate connection details from composite: cannot create or update connection secret: refusing to modify uncontrolled secret of type "Opaque"` because I'm creating the Secret externally and trying to have Crossplane to use it. Maybe there is some annotation that will let me proceed past this protection mechanism.

Finally, with `Queue` specifically I am seeing inconsistent behavior of which keys are written, but not the same behavior you are seeing. Specifically,
My CompositeResouceDefinition (XRD) defines:
```yaml
  connectionSecretKeys:
  - endpoint
  - QUEUE_ARN
  - QUEUE_URL
  - DLQ_ARN
  - DLQ_URL
```
My Composition defines two `Queues`, a main queue with a redrive policy to a second dead-letter queue.
The main queue defines:
```yaml
    connectionDetails:
    - type: FromFieldPath
      name: QUEUE_ARN
      fromFieldPath: status.atProvider.arn
    - type: FromFieldPath
      name: QUEUE_URL
      fromFieldPath: status.atProvider.url
    - type: FromConnectionSecretKey
      name: endpoint
      fromConnectionSecretKey: endpoint
```
The DLQ defines:
```yaml
    connectionDetails:
    - type: FromFieldPath
      name: DLQ_ARN
      fromFieldPath: status.atProvider.arn
    - type: FromConnectionSecretKey
      name: DLQ_URL
      fromConnectionSecretKey: endpoint
```
FINALLY, the behavior I am seeing is that the `type: FromFieldPath` connection details are being written to the XR Secret as expected (so that's `QUEUE_ARN`, `QUEUE_URL` and `DLQ_ARN`. Notebly both of the `type: FromConnectionSecretKey` are missing: `endpoint` and `DLQ_URL`.

So back to your original issue, I have some suggestions if you want to try them to further assist in unraveling the mystery of Crossplane ejected Secrets and narrowing down the specific edge cases that might be bugs or just need much better documentation:

1. I would try removing the `writeConnectionSecretToRef.namespace` you are setting in your `Composition.spec.resources[0].base` since you appear to be trying to us Composite Secrets rather than MR Secret.
2. Since you are setting `writeConnectionSecretsToNamespace: crossplane` in your Composition, try:
* Describing your XR and looking for its `metadata.uid`: `kubectl describe MarcQueueComposite`
* Describing the XR controlled Secret that should exist in `crossplane` namspace (since you set `writeConnectionSecretsToNamespace: crossplane`): `kubectl -n crossplane get Secret/<XR.metadata.uid> -o yaml` Do you any of your `Composition.resources[*].connectionDetails[*].name` here? I would expect that you do.
3. I don't know what namespace you created your `MarcQueue` Claim in, but do you see anything interesting in the `annotations` of the `marctest-queue` Secret there?

Hopefully some of this helps. I'm still working through how I might get an existing `type: Opaque` Secret to by accepted as a Claim `writeConnectionSecretToRef` target.
