### ISSUE TITLE
Can readinessChecks support syntax that matches a string inside an array

### ISSUE THREAD

**Issue by morningspace** [crossplane/crossplane#2433]
### What problem are you facing?

I have a resource that I would like to refer inside my Composition definition where the readinessChecks can be determined based upon the appearance of a specific text inside an array in `status` field. Just as an example:
```
status:
  conditions:
  - lastTransitionTime: "2021-07-07T15:20:15Z"
    status: "True"
    type: Initialized
  - lastTransitionTime: "2021-07-07T15:20:23Z"
    reason: InstallSuccessful
    status: "True"
    type: Deployed
```

Ideally, I could say something as the resource is ready when `status.conditions[*].type` contains `Deployed`. However, it looks the current readinessChecks only supports a few types of matching syntax which couldn't address the above problem. 

### How could Crossplane help solve your problem?

Can readinessChecks support syntax such as `MatchString` where it accepts an array of elements and determine it's true when the property value of one element matches the specified text.
