### ISSUE TITLE
Allow Crossplane's Claim CRs to be created by parent operator

### ISSUE THREAD

**Issue by pgodowski** [crossplane/crossplane#2434]
### What problem are you facing?

We would like to have the Application which uses OLM/Operator code to create all the prerequisites for the application operand to be started. Some of those prerequisites are Crossplane's Claims, to ensure that e.g. the database is created via Crossplane, and the connection details are exposed to the consuming code. Claim CRs are created within operator's reconciler loop.

What we found out, is that Crossplane (`v1.0.0`) adds `.spec.resourceRef`, at runtime, which forces the parent operator either skip this field during reconciliation loop (to ensure Claim CR is still in place), or do not check Claim CR at all. Most of our operators follow the convention that `.spec` section is not modified by other components.

```yaml
spec:
  compositionSelector:
    matchLabels:
      consumer: foobar
  parameters:
    kafka: {}
  resourceRef:
    apiVersion: example.vendor.com/v1alpha1
    kind: KafkaComposite
    name: foobar-h2p2q
  writeConnectionSecretToRef:
    name: foobar-bindinfo
status:
  conditions:
    - lastTransitionTime: '2021-07-02T13:44:08Z'
      reason: Available
      status: 'True'
      type: Ready
  connectionDetails:
    lastPublishedTime: '2021-07-02T13:44:08Z'
```

### How could Crossplane help solve your problem?

I do believe, that the `.spec` field of Claims shall not be updated by Crossplane. Insteaad, the `referenceRef` should be moved to `.status` instead.

There is a fork repo with the initial (dirty) patch available, with more details: https://github.com/IBM/ibm-crossplane/pull/19 .
If there is a cleaner way to solve the problem and ensure there is smallest possible impact to APIs, happy to have the conversation.

@negz 

cc @arturobrzut
