### ISSUE TITLE
error: unable to recognize "STDIN": no matches for kind "ProviderConfig" in version "gcp.crossplane.io/v1beta1"

### ISSUE THREAD

**Issue by ejf-coders51** [crossplane/crossplane#2440]
### What happened?
Error on ProviderConfig deployment

### How can we reproduce it?
Create a cluster
kind create cluster

Install crossplane

kubectl create namespace crossplane-system
helm install crossplane --namespace crossplane-system crossplane-stable/crossplane

Install gcp provider

kubectl crossplane install provider crossplane/provider-gcp:v0.12.0

When i try to deploy the config like this

```
PROJECT_ID=my-project
echo "apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: ${PROJECT_ID}
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-creds
      key: creds" | kubectl apply -f -
```

i receive this error, like the v1beta don't know that type of resource

`error: unable to recognize "STDIN": no matches for kind "ProviderConfig" in version "gcp.crossplane.io/v1beta1"
`

### What environment did it happen in?
Crossplane version: v1.3.0
