### ISSUE TITLE
Race condition while setting XR's `spec.claimRef`

### ISSUE THREAD

**Issue by ulucinar** [crossplane/crossplane#2458]
### What happened?

Previously while working on some experiments with compositions to answer a [question](https://crossplane.slack.com/archives/C01718T2476/p1624587843169500) in the Crossplane providers slack channel, I have observed a race condition that causes an AWS `Bucket` MR (and the corresponding S3 bucket) to leak. If a bucket leaks and when the corresponding claim is deleted, the leaked `Bucket` MR and the corresponding S3 bucket are not deleted. 

### How can we reproduce it?

Back then, I could reproduce the issue with the following manifests. Please note that the race condition does not always occur by definition. Also please find some relevant logs related to the issue in the comments section together with `git diff` to generate those logs.
```
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositebuckets.aws.example.org
spec:
  group: aws.example.org
  names:
    kind: CompositeBucket
    plural: compositebuckets
  claimNames:
    kind: CompositeBucketClaim
    plural: compositebucketclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true

---
apiVersion: aws.example.org/v1alpha1
kind: CompositeBucketClaim
metadata:
  name: my-bucket-with-policy
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: aws
      policy: test

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-with-policy
  labels:
    provider: aws
    policy: test
spec:
  compositeTypeRef:
    apiVersion: aws.example.org/v1alpha1
    kind: CompositeBucket
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
            locationConstraint: us-east-1
      patches:
        - fromFieldPath: "spec.claimRef.name"
          toFieldPath: "metadata.annotations['crossplane.io/external-name']"
        - fromFieldPath: "status.atProvider.arn"
          toFieldPath: "metadata.annotations['bucket-arn']"
          type: ToCompositeFieldPath
    - name: bucket-policy
      base:
        apiVersion: s3.aws.crossplane.io/v1alpha3
        kind: BucketPolicy
        spec:
          forProvider:
            region: us-east-1
            policy:
              version: '2012-10-17'
              statements:
                - action:
                    - s3:ListBucket
                    - s3:GetBucketLocation
                    - s3:ListBucketMultipartUploads
                    - s3:PutBucketCORS
                  effect: Allow
                  principal:
                    allowAnon: true
      patches:
        - fromFieldPath: "spec.resourceRefs[0].name"
          toFieldPath: "spec.forProvider.bucketNameRef.name"
        - fromFieldPath: "metadata.annotations['bucket-arn']"
          toFieldPath: "spec.forProvider.policy.statements[0].resource[0]"
```

### What environment did it happen in?
Crossplane version: v1.3.0 (commit id where the observation was made: b1a6b2080a54fa05bd905391874a8256fb3fd240)
