### ISSUE TITLE
Promote `ControllerConfig` to v1beta1

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2468]
### What problem are you facing?

The `ControllerConfig` type was added back in [v0.14.0](https://github.com/crossplane/crossplane/releases/tag/v0.14.0). It has had undergone some evolution since introduced, and appears to have proved useful to users. We need to make a decision on whether it is ready to promote to v1beta1.

### How could Crossplane help solve your problem?

We should determine what we want to do with `ControllerConfig` - e.g. update it to v1beta1 as is, remove it, or leave it as is. If we do decide to leave it as is it we should define what we would want from the type in order for it to reach v1beta1.

**Comment by negz** [comment]
I'm assigning @hasheddan (at least for now) since he originated this type and has done most of the work on it. Do you feel like it's close to v1beta1?

**Comment by hasheddan** [comment]
@negz to be honest I am still not sure on this one. It is undoubtedly used fairly heavily by Crossplane users, and I have anecdotally heard pretty positive feedback. That being said, as I mentioned in [a recent conversation](https://github.com/crossplane/crossplane/issues/2384#issuecomment-889180160), I worry about it continuing to grow in size as a sort of "kitchen sink" for anything that we don't think makes sense on a `Provider` or that we want to keep isolated from an RBAC perspective. If we felt the need to go ahead and promote it, that would likely turn out fine, but when I think about a future of potentially supporting function packages / custom composition, I wonder if we can address these issues with a more elegant controller configuration mechanism.

**Comment by negz** [comment]
If I recall correctly, part of us adding `ControllerConfig` was as a proving ground for things we might add to `Provider`. Am I remembering that right? Is there anything we have on `ControllerConfig` today that might make sense to migrate to the `Provider` type?

I do think we'll need some kind of a plan to proceed here; I'm hesitant to leave this type in alpha indefinitely. Let's discuss it at the community meeting.

**Comment by jbw976** [comment]
Added it to the agenda for [Aug 12 community meeting](https://docs.google.com/document/d/1q_sp2jLQsDEOX7Yug6TPOv7Fwrys6EwcF5Itxjkno7Y/edit#heading=h.3znynaj7c7go)

**Comment by dee0sap** [comment]
Below is our usage.   The primary thing we are doing is dealing with is the fact that our deployments can only pull from a private registry.  So
- ControllerConfig specifies the image location
- Provider spec forces use of prepopulated image cache

Also in dev clusters we are using --debug so that we have the logs to track down the intermittent problem https://github.com/crossplane/crossplane-runtime/issues/277

Anyhoo, as long as we don't lose the ability to work with a private registry and to set the debug log level we will be Ok.

```

 {{ $.Values.providersDeploy }}: |-
    {{ range $provider := $.Values.providers -}}
    apiVersion: pkg.crossplane.io/v1alpha1
    kind: ControllerConfig
    metadata:
      name: {{ .name }}
      namespace: {{ $.Values.namespace }}
    spec:
      image: {{ printf "%s%s%s" $.Values.landscape.image.registry $.Values.imageRepo .image }}
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        {{- range $index, $secret := $.Values.imagePullSecrets }}
        - name: {{ $secret -}}
        {{- end }}
      args:
        - --debug
    ---
    apiVersion: pkg.crossplane.io/v1beta1
    kind: Provider
    metadata:
      name: {{ .name }}
      namespace: {{ $.Values.namespace }}
    spec:
      package: {{ .name }}
      packagePullPolicy: Never
      controllerConfigRef:
        name: {{ .name }}
      packagePullSecrets:
        {{- range $index, $secret := $.Values.imagePullSecrets }}
        - name: {{ $secret -}}
        {{- end }}
    status:
      currentIdentifier: {{ .name }}
    ---
```
