### ISSUE TITLE
Volume support in ControllerConfig

### ISSUE THREAD

**Issue by zonybob** [crossplane/crossplane#2535]
### What problem are you facing?

I need to use provider-aws and I need to override the AWS client's CA bundle (this can be done in `aws-sdk-go-v2` via `AWS_CA_BUNDLE=/path/to/pem` ... https://github.com/aws/aws-sdk-go-v2/blob/f5b68d198dbefe144696aa0051ed854571b5d614/config/env_config.go#L146-L162)
My issue is that there does not seem to be a way (without using mutating webhooks on the provider pod or something similar) to get a pem file mounted on the AWS provider (I looked in `ControllerConfig` but did not see anything for volume mounts).

### How could Crossplane help solve your problem?

If `ControllerConfig` supported adding volume mounts from `ConfigMap` or `Secret` I could configure the CA bundle reference and the `AWS_CA_BUNDLE` env all from the `ControllerConfig` definition.

Additional reference:
https://crossplane.slack.com/archives/C01718T2476/p1630066636007500

**Comment by hasheddan** [comment]
@zonybob thanks for raising this! I would be in support of this feature, though I do want to mention that the functionality provided by `ControllerConfig` is being discussed in a broader sense in #2468 -- I don't think it needs to block implementation of volume support though :)

**Comment by zonybob** [comment]
@hasheddan thanks for that reference.
FWIW (and maybe to assist anyone else stumbling upon this) I have been able to work around this issue using a Kyverno mutating policy shown below...
Still I look forward to Crossplane handling this without dependencies.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-aws-ca-bundle
spec:
  rules:
    - name: "Add CA Bundle to AWS Provider"
      match:
        resources:
          namespaces:
            - crossplane-system
          kinds:
            - Pod
          names:
            - "crossplane-provider-aws-*"
      mutate:
        overlay:
          spec:
            containers:
              - (name): "*"
                env:
                  - name: AWS_CA_BUNDLE
                    value: /certs/ca.crt
                volumeMounts:
                  - name: ca-certs
                    mountPath: /certs
            volumes:
              - name: ca-certs
                configMap:
                  name: aws-ca-bundle
                  items:
                    - key: ca.crt
                      path: ca.crt

```
