### ISSUE TITLE
Proposal: Adding `fromCompositeFieldPath` to `connectionDetails`

### ISSUE THREAD

**Issue by mcbenjemaa** [crossplane/crossplane#2560]
### What problem are you facing?

Difficulties to span `connectionDetails`  

### How could Crossplane help solve your problem?

[Proposal]
Sometimes you gotta fetch `connectionDetails` from composite resource fields.

Hence, It'd be better to add this functionality.
For instance, a `fromCompositeFieldPath`  should be added to the `connectionDetails`  in the Composition.

However, The combination and transformation of fields also could be helpful in this case.

**Comment by mcbenjemaa** [comment]
relates to #2551

**Comment by negz** [comment]
@mcbenjemaa Thanks for the proposal! 

We already have a (poorly documented) `FromFieldPath` type of connection detail that reads a value from a _composed_ resource. Could you give me a little bit more information about your use case? I'm wondering if `FromFieldPath` would work for you, or if you really need the value to come from an XR field.

**Comment by mcbenjemaa** [comment]
@negz I have a Helm release and I'm trying to construct a hostname from the status of my composite resource.
It would be more easier for me to get `connectionDetails` from the status of my `composite` resource.

Although, there's a workaround to get this field from `connectionDetails` of the release but I think it's worth to have this kind of field supported in the `connectionDetails`.

PS: I have submitted a PR, don't hesitate to have a look.

**Comment by negz** [comment]
> It would be more easier for me to get connectionDetails from the status of my composite resource.

Can you explain _why_ this is easier, please? I presume your status field is derived from a composed resource field, right? Could you just use that composed resource field?

**Comment by mcbenjemaa** [comment]
No, I can't use the composed resource field because I need to combine it and transform it.

this is a simple example: 
```yaml
    # patch status host  
    - type: CombineToComposite
      combine:
        variables:
          - fromFieldPath: "metadata.name"
          - fromFieldPath: "spec.forProvider.namespace"
        strategy: string
        string:
          fmt: "%s-client-service.%s"
      toFieldPath: status.host

```

then, I have the `status.host` published to the composite resource which is great.
that was the idea, later on the `connectionDetails` could just fetch it :)

I have also some other uses cases Where I would set a DNS name in the composite spec, and I want to supply it to the secret as `connectionDetails`.
