### ISSUE TITLE
ToUpper/ToLower Composition string transform

### ISSUE THREAD

**Issue by erikgb** [crossplane/crossplane#2579]
### What problem are you facing?

We are building a Crossplane provider for Cohesity, and our first goal is to allow end-users to provision their S3 buckets. And while we technically made this work, we had to "hack" inside the provider when setting ACLs on bucket (Cohesity call it a view). 

This is our composition, at least parts of it:

````yaml
- base:
    apiVersion: views.cohesity.crossplane.io/v1alpha1
    kind: View
    spec:
      forProvider:
        acl:
          accessControlPolicy:
            owner:
              id: ADMIN@LOCAL@
            grants:
              - grantee:
                  id: ADMIN@LOCAL@
                  type: CanonicalUser
                permission: FULL_CONTROL
              - grantee:
                  type: CanonicalUser
                permission: READ
        protocolAccess: kS3Only
        viewBoxId: 40342
      providerConfigRef:
        name: cohesity-test
  patches:
    - type: PatchSet
      patchSetName: namespaced-name
    - type: CombineFromComposite
      toFieldPath: spec.forProvider.acl.accessControlPolicy.grants[1].grantee.id
      combine:
        variables:
          - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          - fromFieldPath: metadata.labels[crossplane.io/claim-name]
        strategy: string
        string:
          fmt: "%s-%s@LOCAL@"
````

Somehow the Cohesity API requires the `grantee.id` to be specified in UPPERCASE - even if the User (which is another managed resource in our composition) doesn't require it. 😒 So while the User managed resource external-name is set to `<claim-namespace>-<claim-name>`, we need to convert this to UPPERCASE when refering to the User in the managed View ACL.

As a workaround, we are now uppercasing the `grantee.id` in provider-cohesity View-controller: `ID:          pointer.String(strings.ToUpper(g.Grantee.ID))`. **What I would like to see, is a way to do this in the composition**.

### How could Crossplane help solve your problem?

I [asked the community about this on Slack](https://crossplane.slack.com/archives/CEG3T90A1/p1631656007364600), and @negz suggested to raise an issue - asking for a toLower/toUpper string transform.

And while I am not that experienced with Crossplane, I think our use case could be solved by introducing a new string transform:

````yaml
patches:
  - type: CombineFromComposite
    toFieldPath: spec.forProvider.acl.accessControlPolicy.grants[1].grantee.id
    combine:
      variables:
        - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
        - fromFieldPath: metadata.labels[crossplane.io/claim-name]
      strategy: string
      string:
        fmt: "%s-%s@LOCAL@"
        convert: Upper
````

**Comment by mcbenjemaa** [comment]
I think I might need it as well.

**Comment by negz** [comment]
I think we'd want the `ToUpper` as a transform, right? The proposed API shows it as a combine strategy. So perhaps something like:

```yaml
patches:
  - type: CombineFromComposite
    toFieldPath: spec.forProvider.acl.accessControlPolicy.grants[1].grantee.id
    combine:
      variables:
        - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
        - fromFieldPath: metadata.labels[crossplane.io/claim-name]
      strategy: string
      string:
        fmt: "%s-%s@LOCAL@"
    transforms:
    - type: string
      string:
        # Add a type field so we know when to expect fmt vs convert
        type: Convert
        # convert is an enum of conversion types.
        convert: ToUpper
```
