### ISSUE TITLE
Make provider setup available using gitops approach

### ISSUE THREAD

**Issue by paulcarlton-ww** [crossplane/crossplane#2580]
### What problem are you facing?

I am trying to deploy crossplane and use it to configure AWS infrastructure via gitops methodology.
I can install controller using flux2 Helm Controller but adding the aws provider requires use of crossplane cli as per https://crossplane.io/docs/v1.4/getting-started/install-configure.html, i.e. 

```
kubectl crossplane install configuration registry.upbound.io/xp/getting-started-with-aws:v1.4.1
```

### How could Crossplane help solve your problem?
I'd like to be able to trigger this setup by defining a CRD or other object in a git repo and having flux apply it to the cluster.
I could create a docker image containing kubectl with crossplane plugin and define a job to run this but I'm wondering if there is a better way to achieve this.?

**Comment by negz** [comment]
Hi @paulcarlton-ww! This should actually be possible today - the `kubectl crossplane` command you reference is actually just creating a `Configuration` resource under the hood. Take a look at https://crossplane.io/docs/v1.4/concepts/packages.html#installing-a-package for more detail, but I think what you're looking for would be:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: my-org-infra
spec:
  package: registry.upbound.io/xp/getting-started-with-aws:v1.4.1
```

Let me know if I've misunderstood what you're looking for.
