### ISSUE TITLE
Crossplane resource describe provides wrong information.

### ISSUE THREAD

**Issue by vinsguru** [crossplane/crossplane#2586]
We have created a Composition called `S3Bucket` on top of Crossplane `Bucket` resource. Our base composition is like this initially.

```
resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
            locationConstraint: us-west-2
            objectLockEnabledForBucket: false
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            versioningConfiguration:
              status: Enabled
```

 We build the configuration v1 and push it into our k8s cluster. Let's assume that we have provisioned few buckets using the composition. Everything looks great so far.

 Now due to some requirement change , we have to change the composition like this & build a new configuration (v2) and push. (object lock became `true`)

```
 resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
            locationConstraint: us-west-2
            objectLockEnabledForBucket: true
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            versioningConfiguration:
              status: Enabled
```

 **S3 does not allow object lock to be changed on the existing buckets.**
    
   If I try to describe the existing buckets (created with v1), **_we see the description saying that object lock is enabled_**. But the AWS console shows that it is disabled.

`kubectl describe bucket -o json `
