### ISSUE TITLE
Support for fromFieldPath, nil/null and default value in map transform

### ISSUE THREAD

**Issue by samidbb** [crossplane/crossplane#2589]
### What problem are you facing?
Related to the case mentioned in #2588
So we are basically trying to build a package that offers claim to create sqldatabase instances on AWS on-demand (dynamic provisioning).

User has to specify boolean parameter `isProduction` to tell whether the instance is running in production  mode or in non-production mode. 
XRD:
```yaml
...
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  isProduction:
                    description: Specify whether it is intended to run in production environment or not
                    type: boolean
...
```
Based on the provided value, `skipFinalSnapshotBeforeDeletion` will be set.
We are also setting `finalDBSnapshotIdentifier` to be the claim name. So this is the logic in our composition: 
```yaml
...
     - fromFieldPath: spec.claimRef.name    
       toFieldPath: spec.forProvider.finalDBSnapshotIdentifier
       transforms:
       - type: string
         string:
           fmt: "%s-final"
...
```
The claim and RDSInstance resource are created without any issues. The problem occurs when we delete the claim and the Crossplane tries to delete the associated RDSInstance when `skipFinalSnapshotBeforeDeletion` is set to true.
Crossplane fails to delete the RDSInstance automatically with this error message from the provider: 
`cannot delete RDS instance: InvalidParameterCombination: Only one of SkipFinalSnapshot and FinalDBSnapshotIdentifier can be specified`

The issue is that the `FinalDBSnapshotIdentifier` is not ignored when `SkipFinalSnapshot` is set to true. 

Now I tried to "cheat" the system by passing an empty string to make the provider ignore the `FinalDBSnapshotIdentifier` field. So current implementation now looks like this:
```yaml
...
    - fromFieldPath: "spec.parameters.isProduction"
      toFieldPath: "spec.forProvider.finalDBSnapshotIdentifier"
      transforms:
      - type: convert
        convert:
          toType: string      
      - type: map
        map:
          "false": ""
          "true": "something"
...
```
Which worked, but this solution is not really useful. This is because it also sets a fixed value for the `FinalDBSnapshotIdentifier` field, and this ID must be unique in the list of the snapshots created on AWS. So we still want the value for ID to be dynamic when `isProduction` is set to true.

I also tested doing the same with terraform. The AWS provider for terraform does not have the same issue. It simply ignores the FinalDBSnapshotIdentifier when SkipFinalSnapshot is set. When I looked in the code or AWS provider for crossplane, it looks like that you are just passing the parameters to AWS without any additional logic to ignore the `FinalDBSnapshotIdentifier` unlike AWS provider for terraform (Now this could also be an another issue to be dealt with in provider-aws repo) But the idea here, it creates an extra need to support building a more complex logic if we are directly exposed to AWS API.

### How could Crossplane help solve your problem?
To solve our challenge I would like to suggest the following:
1) Implementing the support for `fromFieldPath` in the map transform. 
2) We will also benefit a lot from having the option to set a map entry value to `nil`, or having a default value for map transform being set in case of key is not found in the list, instead of getting an error.

So the logic we can end up writing could be done in this way:
```yaml
...
    - fromFieldPath: "spec.parameters.isProduction"
      toFieldPath: "spec.forProvider.finalDBSnapshotIdentifier"
      transforms:
      - type: convert
        convert:
          toType: string
      - type: map
        map:
          "false": nil
          "true": source.fromFieldPath
...
```
or in this way if default value is introduced:
```yaml
...
    - fromFieldPath: "spec.parameters.isProduction"
      toFieldPath: "spec.forProvider.finalDBSnapshotIdentifier"
      transforms:
      - type: convert
        convert:
          toType: string
      - type: map
         map:
          "true": source.fromFieldPath
         default: nil
...
```
