### ISSUE TITLE
Proposal: Optionally skip 'intermediate' connection secrets

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2594]
### What problem are you facing?

For a claim to write a connection secret many things need to align, including (but not limited to):

1. The actual 'source' of connection details (i.e. composed resources) writing connection details to secrets.
2. The XR aggregating the connection details from the secrets in 1 to its own connection secret.
3. The claim propagating the connection details from 2 to its own connection secret.

This leads to some unintuitive behaviour, namely:

1. We create a whole bunch of secrets (by convention in `crossplane-system` that are really just intermediary stores used to build a claim connection secret key.
2. We have an (IMO) awkward `spec.writeConnectionSecretsToNamespace` field in the `Composition` type that we use to configure the namespace XRs should write their connection secrets to if they're dynamically provisioned (i.e. automatically created by a claim).
3. If you claim an existing XR that doesn't write a connection secret your claim can't write a connection secret either.

### How could Crossplane help solve your problem?

I don't think a distinct XR connection secret is actually needed in the (very common) case where we dynamically provision an XR in response to someone creating a claim. I'm pretty sure we could just tell the XR to write its connection details to whatever secret the claim specified, and have the claim and XR share ownership (in the owner ref sense) of the connection secret. This way there'd only be one layer of aggregation - composed resource -> claim secret.

This would be a behaviour change so it would presumably need to be controlled by an API knob, probably on the XRD. Something like:

```yaml
kind: CompositeResourceDefinition
spec:
  # A new optional field.
  connectionDetails:
    # Another optional field.
    # Default would be something like AlwaysWriteXR (today's behaviour)
    # SkipXR would set the XR's secret to the claim's
    propagationStrategy: SkipXR
```
