### ISSUE TITLE
Connection details are not propagated to secret

### ISSUE THREAD

**Issue by eloo** [crossplane/crossplane#2606]
### What happened?
Hi,

i was about to create a composition for s3 bucket and want to create connection details but the secret is every time empty. 

If im going to let the MR create its connection details this secret is filled with the data as expected. But the composition or claim secret is still empty. 

I've also tested a fixed value like this
```yaml
        - name: test
          value: "string-value"
```
but this is also not working. 

So it seems like connectionDetails isn't working at all right now :( 

### How can we reproduce it?
composition:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket-composition
  labels:
    provider: aws
    crossplane.io/xrd: composites3bucketinstances.my.group
spec:
  compositeTypeRef:
    apiVersion: my.group/v1alpha1
    kind: CompositeS3BucketInstance
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: poc-dev-bucket
          labels:
            name: poc-dev-bucket
        spec:
          forProvider:
            locationConstraint: eu-west-1
            acl: private
            versioningConfiguration:
              status: Enabled
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
          providerConfigRef:
            name: aws-provider-config
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.locationConstraint
      connectionDetails:
        - fromConnectionSecretKey: endpoint
```
xrd:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: composites3bucketinstances.my.group
spec:
  group: my.group
  names:
    kind: CompositeS3BucketInstance
    plural: composites3bucketinstances
  claimNames:
    kind: S3BucketInstance
    plural: s3bucketinstances
  connectionSecretKeys:
  - endpoint
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                required:
                - region
            required:
            - parameters
```

claim:
```yaml
apiVersion: acp.com/v1alpha1
kind: S3BucketInstance
metadata:
  name: composite-bucket-instance
  namespace: test-dev
  annotations:
    crossplane.io/external-name: composite-bucket-instance-test
spec: 
  parameters:
    region: eu-central-1
  writeConnectionSecretToRef:
    name: composite-bucket-instance-details
  compositionSelector:
    matchLabels:
      provider: aws
```

### What environment did it happen in?
Crossplane version: crossplane/crossplane:v1.4.1
Cloud provider or hardware configuration - aws-provider v0.19.1
Kubernetes version (use kubectl version) - v1.21.2-eks-0389ca3
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) - EKS
OS (e.g. from /etc/os-release) - Amazon Linux

**Comment by denist-huma** [comment]
@eloo I am new to crossplane too and had the same question once.

Why do you expect to have ConnectionSecretKey: endpoint in a bucket? It has no such thing in its API.

Actually, that is no code exists at all to create a connection secret for a bucket here. https://github.com/crossplane/provider-aws/blob/5e832d622a5a7dec61808766650dd88a91a14a9b/pkg/controller/s3/bucket.go
I compared to the iamaccesskey that creates a connection secret:
 https://github.com/crossplane/provider-aws/blob/5e832d622a5a7dec61808766650dd88a91a14a9b/pkg/controller/identity/iamaccesskey/controller.go it has 
```go
conn = managed.ConnectionDetails{
			xpv1.ResourceCredentialsSecretUserKey:     []byte(aws.StringValue(response.AccessKey.AccessKeyId)),
			xpv1.ResourceCredentialsSecretPasswordKey: []byte(aws.StringValue(response.AccessKey.SecretAccessKey)),
		}
```

You can get only "status.atProvider.arn" from a bucket to use it inside your XR. 
I don't know how to get it, [How to get back a real S3 bucket name in a secret?](https://crossplane.slack.com/archives/CEG3T90A1/p1633083579223000) the question is still open

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositebuckets.aws.storage.huma.com
  labels:
    provider: aws
    vpc: default
spec:
  # This Composition declares that it satisfies the CompositeBucket
  # resource defined above - i.e. it patches "from" a CompositeBucket.
  # Note that the version in apiVersion must be the referenceable version of the
  # XRD.
  compositeTypeRef:
    apiVersion: storage.huma.com/v1alpha1
    kind: CompositeBucket
  # When an XR is created in response to a claim Crossplane needs to know where
  # it should create the XR's connection secret. This is configured using the
  # 'writeConnectionSecretsToNamespace' field.
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
            locationConstraint: eu-west-2
            accelerateConfiguration:
              status: Enabled
            versioningConfiguration:
              status: Enabled
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
      # Patches copy or "overlay" the value of a field path within the composite
      # resource XR to a field path within the composed resource CR.
      patches:
        - fromFieldPath: "status.atProvider.arn"
          toFieldPath: "metadata.annotations['bucket-arn']"
          type: ToCompositeFieldPath
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.annotations['bucket-name']"
          type: ToCompositeFieldPath
          ```

I suggest using my gist as reference: https://gist.github.com/denist-huma/cf6ae14f62dc7d96d74736dbdd5f67e8
> In my IAMAccessKey I got this annotation visible and populated. But the secret has only the username and password, missing a bucket-name key I want.

**Comment by denist-huma** [comment]
Since my issue is like this with "connectionDetails.fromFieldPath", I add it to not create an additional one.


### What happened?

How to get back a real S3 bucket name in a secret?
After I have a first step forward with custom CompositeBucket, I am struggling to make work connectionDetails.fromFieldPath: "metadata.annotations['bucket-name']"
In my IAMAccessKey I got this annotation visible and populated. But the secret has only the username and password, missing a bucket-name key I want.

The CompositeBucket is working together with a bucket policy, IAM user, access key.

@muvaf was helping me in [slack](https://crossplane.slack.com/archives/CEG3T90A1/p1633083579223000) but the problem is not solved. I used all the suggested options.
Not working connectionDetails: 

```yaml
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
            locationConstraint: eu-west-2
            accelerateConfiguration:
              status: Enabled
            versioningConfiguration:
              status: Enabled
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
      # Patches copy or "overlay" the value of a field path within the composite
      # resource XR to a field path within the composed resource CR.
      patches:
        - fromFieldPath: "status.atProvider.arn"
          toFieldPath: "metadata.annotations['bucket-arn']"
          type: ToCompositeFieldPath
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.annotations['bucket-name']"
          type: ToCompositeFieldPath
      # Tried to get back a real S3 bucket name in a secret
      # connectionDetails:
      #   - fromFieldPath: "metadata.name"
      #     name: bucket-name
      #     type: FromFieldPath
```

```yaml
    - name: access-key
      base:
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMAccessKey
        spec:
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.annotations['user-name']"
          toFieldPath: "spec.forProvider.userNameRef.name"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-iam-access-key"
        # Tried to get back a real S3 bucket name in a secret
        # - fromFieldPath: "metadata.annotations['bucket-name']"
        #   toFieldPath: "metadata.annotations['bucket-name']"
        #   policy:
        #     fromFieldPath: Required
      # In addition to a base and patches, this composition declares that
      # it can fulfil the connectionSecretKeys contract required by the definition.
      # This resource writes a connection secret
      # with a username and password that may be used to connect to it.
      # These connection details will also be exposed via the composite resource's
      # connection secret. Exactly one composed resource must provide each secret
      # key, but different composed resources may provide different keys.
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        # Tried to get back a real S3 bucket name in a secret
        # - fromFieldPath: "metadata.annotations['bucket-name']"
        #   name: bucket
        #   type: FromFieldPath
 ```

My secret is still the same as the usual IAM access key secret, 2 entries.
 ```sh
$ kubectl get secret my-private-bucket-secret -n operator-sandbox
NAME                       TYPE                                DATA   AGE
my-private-bucket-secret   connection.crossplane.io/v1alpha1   2      41s
```

### How can we reproduce it?

I have my manifests in [my gist](https://gist.github.com/denist-huma/cf6ae14f62dc7d96d74736dbdd5f67e8) 

### What environment did it happen in?
Crossplane version: 0.14.1
* Kubernetes version (use `kubectl version`) v1.19.12-gke.2101
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) GKE

**Comment by eloo** [comment]
@denist-huma 
i'm expecting the bucketname as "endpoint" and the region because is the behaviour you will see when you create just a s3 bucket as managed resource. 
so IMHO it would make sense to have the same for a composition. 

further i see the same behaviour if i create a composition with a redis cluster..
and here i really really need that secret because the token is autogenerated

**Comment by denist-huma** [comment]
> here I really really need that secret because the token is autogenerated
me too :+1:

**Comment by eloo** [comment]
finally i have managed to make my compositions working.
the ticket https://github.com/crossplane/crossplane/issues/2593 had the important information gathered.

in my case the issue was that i have missed to add the writeSecretToRef in every managed resource in the composition.
In general this feels like a bit overhead but at least its working for now.

**Comment by denist-huma** [comment]
> in my case the issue was that i have missed to add the writeSecretToRef in every managed resource in the composition. In general this feels like a bit overhead but at least its working for now.

@eloo please share your find. 
And if add "spec.writeConnectionSecretToRef.namespace: crossplane-system", the bucket creation breaks, not even shoving errors, just an empty buckets list.
The AWS S3 bucket CRD has no spec.writeConnectionSecretToRef!?

**Comment by eloo** [comment]
@denist-huma 
for the manage resource you need to use `writeConnectionSecretToRef` which is defined in the CRD here https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/Bucket/v1beta1@v0.19.1

so could look like this
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket-composition
  labels:
    provider: aws
    crossplane.io/xrd: composites3bucketinstances.group.com
spec:
  compositeTypeRef:
    apiVersion: group.com/v1alpha1
    kind: CompositeS3BucketInstance
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: poc-dev-bucket
          labels:
            name: poc-dev-bucket
        spec:
          forProvider:
            locationConstraint: eu-west-1
            acl: private
            versioningConfiguration:
              status: Enabled
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
          providerConfigRef:
            name: aws-provider-config
          writeConnectionSecretToRef:
            name: s3bucket-access
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.locationConstraint
      connectionDetails:
        - fromConnectionSecretKey: endpoint
          name: endpoint
        - fromConnectionSecretKey: region
          name: region
```

**Comment by denist-huma** [comment]
thanks @eloo!
I got success too!
you can close this issue

**Comment by negz** [comment]
Thanks for helping each other folks! I'll close this.

**Comment by negz** [comment]
Breadcrumbs for future readers: there is some troubleshooting docs for secrets at https://crossplane.github.io/docs/v1.4/reference/composition.html#composite-resource-connection-secrets.

**Comment by wwentland** [comment]
If you want to utilise external secret stores with  `spec.publishConnectionDetailsTo` a few changes have to be mase as it does not seem to work out of the box.

Install crossplane with:

```
helm upgrade -i crossplane --namespace crossplane-system crossplane-stable/crossplane --set 'args={--enable-external-secret-stores}'
```

Which allows you to configure a provider similar to:

```
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: foo-controller
  ...
spec:
  args:
  - --enable-external-secret-stores
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: foo-provider
spec:
  package: ...
  controllerConfigRef:
    name: foo-controller
```

You can then do something along the lines of:

```
---
apiVersion: ...
kind: ...
metadata:
  name: foo-resource
spec:
  forProvider:
    ...
  providerConfigRef:
    name: foo-provider
  publishConnectionDetailsTo:
    name: foo-resource-connection-details
```

Refer to the following for further details:

- https://github.com/crossplane/crossplane/blob/master/design/design-doc-external-secret-stores.md
- https://docs.crossplane.io/v1.10/reference/composition/#composite-resource-connection-secrets
- https://docs.crossplane.io/v1.10/guides/vault-as-secret-store/
- https://docs.crossplane.io/v1.10/reference/composition/#connection-details
