### ISSUE TITLE
Crossplane ControllerConfig annotations being added to pod but not deployment

### ISSUE THREAD

**Issue by slimm609** [crossplane/crossplane#2652]
### What happened?

according to the documentation, `Metadata that will be added to the provider Pod.` however in the ticket it says it should apply to both deployments as well as pods.  
https://github.com/crossplane/crossplane/issues/2438

The annotations show on the pod but not the deployment. 

### How can we reproduce it?

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws
spec:
  metadata:
    annotations:
     deployment-annotation: "my-annotation"
```
The annotation shows up on the pod but not the deployment.

### What environment did it happen in?
Crossplane version: 
Crossplane v1.4.1
