### ISSUE TITLE
When upgrading aws provider from v0.19.0 to v0.20.0,  multiple providers are installed

### ISSUE THREAD

**Issue by yshu2017** [crossplane/crossplane#2665]
### What happened?

When upgrading aws provider from v0.19.0 to v0.20.0,  multiple providers are installed. Due to multiple aws-providers, resource creation is failing.  

`kubectl get providers` generates the following results:

`NAME           INSTALLED  HEALTHY  PACKAGE `           
`crossplane-provider-aws  True    False   crossplane/provider-aws:v0.20.0  3m33s`
`provider-aws       True    True   crossplane/provider-aws:v0.20.0  49m`

### What environment did it happen in?
Crossplane version:  1.3.0
aws-provider version: from v0.19.0 upgrade to v0.20.0

Provider is installed with the following yaml:

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${IAM_ROLE_NAME}
spec:
  podSecurityContext:
    fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:${CROSSPLANE_PROVIDER_VERSION}
  controllerConfigRef:
    name: aws-config
```
