### ISSUE TITLE
problem with policy mergeOptions in composition 

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#2685]
we have a problem in composition to patch additional  label for matchLabels in subnetIdSelector for eks cluster

composition:
```
     - name: EKS-Cluster
      base:
        apiVersion: eks.aws.crossplane.io/v1beta1
        kind: Cluster
        spec:
          forProvider:
            roleArnSelector:
              matchControllerRef: true
              matchLabels:
                role: controlplane
            subnetIdSelector:
              matchLabels:
                access: public
[...]
    - fromFieldPath: spec.forProvider.networkRef.id
      policy:
        mergeOptions:
          appendSlice: true
          keepMapValues: true
      toFieldPath: spec.forProvider.resourcesVpcConfig.subnetIdSelector.matchLabels[networks.aws.platformref.example.de/network-id]
      type: FromCompositeFieldPath
```
 
at the moment matchLables is overriden - no merge no additional add
```
       subnetIdSelector:
        matchLabels:
          networks.aws.platformref.dkb.de/network-id: poc-internet-cluster-network              

```

expected:

```
       subnetIdSelector:
        matchLabels:
          access: public
          networks.aws.platformref.dkb.de/network-id: poc-internet-cluster-network
```

any ideas ?

### What environment did it happen in?
Crossplane version: 1.4.1
