### ISSUE TITLE
Compositions - matchControllerRef: true in selector picks unexpected resource

### ISSUE THREAD

**Issue by robertgates55** [crossplane/crossplane#2688]
I'm trying to create a composition that creates an RDS cluster, plus a new kms key, isolated dbsubnet, db instances, etc.

What's the correct pattern to have the resources in a composition reference each other? Eg in the below, I create a kms key and a dbcluster. I want to ensure that the kms key created _by this composition_ is the one that's consumed by the dbcluster: 
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mysqlclusters.aws.database.du.co
spec:
  compositeTypeRef:
    apiVersion: database.du.co/v1alpha1
    kind: XMySQLCluster
  resources:
  - name: kmskey
    base:
      apiVersion: kms.aws.crossplane.io/v1alpha1
      kind: Key
      spec:
        forProvider:
          region: eu-west-1
  - name: dbcluster
    base:
      apiVersion: rds.aws.crossplane.io/v1alpha1
      kind: DBCluster
      spec:
        forProvider:
          ...
          kmsKeyIDSelector:
            matchController: true
          ...
          region: eu-west-1
        ...
```

However, what actually happens is another kms key in the cluster (created by the same controller, hence `matchController`) is picked.

Is there a way to do the equivalent of `matchComposition: true` on a selector? Or some way of patching in common labels and then dynamically doing `matchLabels` on the Selector?
