### ISSUE TITLE
MergeOption: appendSlice is overwriting instead of appending

### ISSUE THREAD

**Issue by eloo** [crossplane/crossplane#2690]
### What happened?

Hi all, i guess the mergeOption: appendSlice is broken.
Seems like the appendSlice is not respected and the tagset is overwritten.
Is this a known issue?
Thanks

### How can we reproduce it?
I have the following composition with patches

```yaml
  resources:
    - base: 
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: METADATA_UID
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-provider-config
          forProvider:
            acl: private
            locationConstraint: REGION
            versioningConfiguration:
              status: Enabled
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            tagging:
              tagSet: 
                - key: namespace
                  value: MY_NAMESPACE
          writeConnectionSecretToRef:
            name: METADATA_NAME-MR-s3bucket-managed-resource
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.tagging.tagSet
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
```

My claim has the following:
```yaml
    tags:
      - key: another-tag
        value: with-value
```

So the following would be expected result:
```yaml
            tagging:
              tagSet: 
                - key: namespace
                  value: MY_NAMESPACE
                - key: another-tag
                  value: with-value
```

But i get the following:
```yaml
    tagging:
      tagSet:
      - key: another-tag
        value: with-value
```

### What environment did it happen in?
Crossplane version: 

Crossplane version: 1.4.1

Cloud provider or hardware configuration - aws-provider v0.20.0-rc
Kubernetes version (use kubectl version) - v1.21.2-eks-0389ca3
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) - EKS
OS (e.g. from /etc/os-release) - Amazon Linux

**Comment by EdgeJ** [comment]
I've had the same issue.  
My composition has the following configuration:
```
  resources:
  - name: bucket
    base:
      spec:
          tagging:
            tagSet:
            - key: createdBy
              value: crossplane
    patches:
    - fromFieldPath: "spec.parameters.tags"
      toFieldPath: "spec.forProvider.tagging.tagSet"
      policy:
        mergeOptions:
          appendSlice: true
          keepMapValues: true
```

But when I apply a claim like this:
```
spec:
  parameters:
    region: us-east-2
    tags:
    - key: account
      value: demo
    - key: test
      value: "yes"
```

The resulting tags are:
```
    Tags:
      Key:    account
      Value:  demo
      Key:    test
      Value:  yes
```

**Comment by eloo** [comment]
@negz @jbw976 
have you tested the fix from @EdgeJ 

for it looks still that appendSlice is not working. 

with version 1.9.0 i still the same replace instead of merge as with 1.4.1

can you please check if this is really fixed? for me this is still buggy and thus we should reopen this ticket.

**Comment by jbw976** [comment]
I have not personally tested the fix myself @eloo 😊  - a couple questions though:

* can you share a streamlined repro scenario and manifests that show the behavior you're still seeing?
* is your scenario covered by #3335 by any chance? There's been a lot of discussion there recently on a similar issue.

**Comment by eloo** [comment]
@jbw976 
> is your scenario covered by https://github.com/crossplane/crossplane/issues/3335 by any chance? There's been a lot of discussion there recently on a similar issue.

i guess the mentioned issue is not covering this bug because in this issue here its about adding new items to a slice and not editing

> can you share a streamlined repro scenario and manifests that show the behavior you're still seeing?
you can use the definition and composition from here: 
https://github.com/aws-samples/crossplane-aws-blueprints/blob/main/compositions/aws-provider/s3/definition.yaml
and the same composition (general-purpose.yaml) with additional tags in the composition like this:

```yaml
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket.awsblueprints.io
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    s3.awsblueprints.io/configuration: standard
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XObjectStorage
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
  resources:
    - name: s3-bucket
      connectionDetails:
        - name: bucket-name
          fromConnectionSecretKey: endpoint
        - name: region
          fromConnectionSecretKey: region
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          forProvider:
            acl: private
            locationConstraint: us-west-2
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            tagging:
                tagSet:
                - key: composition
                  value: value
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tagging.tagSet
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.bucketName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.bucketArn
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"
```

and this claim
https://github.com/aws-samples/crossplane-aws-blueprints/blob/main/examples/aws-provider/composite-resources/s3/general-purpose.yaml

then the output will look like this (for bucket)
```
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-west-2
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    serverSideEncryptionConfiguration:
      rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
    tagging:
      tagSet:
      - key: env
        value: test
      - key: anotherKey
        value: anotherValue
```

but tagSet should be
```
      tagSet:
      - key: composition
        value: value
      - key: env
        value: test
      - key: anotherKey
        value: anotherValue
```

so its still the same issue as in my very first post here

**Comment by EdgeJ** [comment]
I decided to test this out locally myself to verify whether this fix actually worked. When I create the same compositions/claims against Kubernetes, I see that it does work in the sense that the created bucket has the correct tags:
```sh
aws --profile crossplane-demo --region us-west-2 s3api get-bucket-tagging --bucket standard-object-storage-jfxn7-pmw2k
TagSet:
- Key: env
  Value: test
- Key: anotherKey
  Value: anotherValue
- Key: composition
  Value: value
```

But, to @eloo 's point, I did notice that the objects on the Kubernetes cluster don't necessarily reflect the patching that happened. I don't expect the claim to be updated with the patches, but I was somewhat surprised to see the resulting composite object does not have all of the tags in the spec:
```yaml
spec:
  claimRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: ObjectStorage
    name: standard-object-storage
    namespace: default
  compositionRef:
    name: s3bucket.awsblueprints.io
  compositionSelector:
    matchLabels:
      awsblueprints.io/environment: dev
      awsblueprints.io/provider: aws
      s3.awsblueprints.io/configuration: standard
  compositionUpdatePolicy: Automatic
  resourceConfig:
    providerConfigName: crossplane-dev-account
    region: us-west-2
    tags:
    - key: env
      value: test
    - key: anotherKey
      value: anotherValue
  resourceRefs:
  - apiVersion: s3.aws.crossplane.io/v1beta1
    kind: Bucket
    name: standard-object-storage-jfxn7-pmw2k
  writeConnectionSecretToRef:
    name: 9cced544-aa85-47de-88c1-1ea69fa8fd00
    namespace: crossplane-system
```

So, I would say this is ultimately _working_, but maybe there could be some UI/UX improvements here to reflect that the patches did indeed occur in the resulting XR.

**Comment by EdgeJ** [comment]
Actually, I take back what I said about the XR not reflecting the patching. Thinking about it some more, I realized that I should be looking at the underlying MR instead. When checking that I see the patches as expected:
```
  spec:
    deletionPolicy: Delete
    forProvider:
      acl: private
      locationConstraint: us-west-2
      paymentConfiguration:
        payer: BucketOwner
      publicAccessBlockConfiguration:
        blockPublicAcls: true
        blockPublicPolicy: true
        ignorePublicAcls: true
        restrictPublicBuckets: true
      serverSideEncryptionConfiguration:
        rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
      tagging:
        tagSet:
        - key: composition
          value: value
        - key: env
          value: test
        - key: anotherKey
          value: anotherValue
```
