### ISSUE TITLE
Map transformation from string to array string

### ISSUE THREAD

**Issue by etcshad0vv** [crossplane/crossplane#2698]
Hello,
I am trying to create a map for thumbprintlist based on region for AWS IAM Provider within a `Composition`

```
        - type: FromCompositeFieldPath
          fromFieldPath: status.cluster.region
          toFieldPath: spec.forProvider.thumbprintList[0]
          policy:
            fromFieldPath: Required
          transforms:
            - type: map
              map:
                eu-west-1: 5a6dcd2137c572a977f26fe414671aea066f47bc
```

### What problem are you facing?

I am getting the following error in composition 
```
": spec.resources.patches.transforms.map.Pairs in body must be of type string: "object"
  Warning  CreateRevision  <invalid> (x22 over 8m11s)  revisions/composition.apiextensions.crossplane.io  (combined from similar events): CompositionRevision.apiextensions.crossplane.io "aws-eks-jvfml" is invalid: spec.resources.patches.transforms.map.Pairs: Invalid value: "object": spec.resources.patches.transforms.map.Pairs in body must be of type string: "object"
```

### How could Crossplane help solve your problem?

I am not sure if it's a syntax or limitation in Go, please if you can assist on mapping strings back to an array string.
