### ISSUE TITLE
status.conditions: not an object when referencing array element

### ISSUE THREAD

**Issue by fherbert** [crossplane/crossplane#2754]
### What happened?
I'm defining the status for my composition as:
```
- type: ToCompositeFieldPath
  fromFieldPath: status.conditions[0].status
  toFieldPath: status.controlPlaneStatus  
- type: ToCompositeFieldPath
  fromFieldPath: status.conditions[0].status
  toFieldPath: status.nodePoolStatus
```

The managed resource gets created and status looks like:

```
status:
  atProvider:
    fqdn: ""
    id: /subscriptions/1234567890/resourcegroups/resourcegroup/providers/Microsoft.ContainerService/managedClusters/rfod
    kubeAdminConfig:
    - host: https://rfod.privatelink.azmk8s.io:443
      username: clusterAdmin_resourcegroup_rfod
    kubeConfig:
    - host: https://rfod.privatelink.azmk8s.io:443
      username: clusterUser_resourcegroup_rfod
    privateFqdn: rfod.privatelink.azmk8s.io
  conditions:
  - lastTransitionTime: "2021-12-09T04:11:01Z"
    reason: Deleting
    status: "False"
    type: Ready
  - lastTransitionTime: "2021-12-08T19:42:27Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2021-12-08T19:51:54Z"
    reason: Success
    status: "True"
    type: AsyncOperation
```

But the claim resource status never gets updated. The debug log from the crossplane control has:
```
2021-12-09T04:10:19.884Z	DEBUG	crossplane.controller-runtime.manager.events	Warning	{"object": {"kind":"CompositeCluster","name":"rfod-team-aks-rfhjj","uid":"174c9235-7d69-4913-be98-ac231a530f1f","apiVersion":"rfod.foo.com/v1alpha1","resourceVersion":"92408144"}, "reason": "ComposeResources", "message": "status.conditions: not an object"}
```

### How can we reproduce it?
I used example kubernetes manifest from https://github.com/vfarcic/devops-toolkit-crossplane/blob/master/packages/k8s/aks.yaml

### What environment did it happen in?
Crossplane version: v1.5.0
Azure Jet Provider: v0.5.0
