### ISSUE TITLE
Patch a field into multiple arrays

### ISSUE THREAD

**Issue by EdgeJ** [crossplane/crossplane#2784]
### What problem are you facing?

There are times where an array of objects have a common data point that is either cumbersome to code by hand, or must be derived from some other place.  A specific example I am working on is creating an S3 BucketPolicy, using the ARN derived from a Bucket created by the same composition:

```yaml
  resources:
  - name: bucket
    base:
      apiVersion: s3.aws.crossplane.io/v1beta1
      kind: Bucket
      spec:
        forProvider:
          acl: private
          locationConstraint: us-east-1
          publicAccessBlockConfiguration:
            # block all public access by default
            blockPublicAcls: true
            blockPublicPolicy: true
            ignorePublicAcls: true
            restrictPublicBuckets: true
          serverSideEncryptionConfiguration:
            rules:
            - applyServerSideEncryptionByDefault:
                sseAlgorithm: AES256
          tagging:
            tagSet:
            - key: createdBy
              value: crossplane
    patches:
    # get the bucket ARN to supply to the policy resource
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: metadata.annotations[crossplane.io/bucket-arn]
  - name: bucketPolicy
    base:
      apiVersion: s3.aws.crossplane.io/v1alpha3
      kind: BucketPolicy
      spec:
        forProvider:
          bucketNameSelector:
            matchControllerRef: true  # select the bucket created by this composition
          policy:
            version: "2012-10-17"
            statements:
            - action:
              - s3:ListBucket*
              - s3:GetBucket*
              - s3:PutBucket*
              effect: Allow
              principal:
                awsPrincipals: []
              resource: []
          region: us-east-1
    patches:
    - fromFieldPath: spec.parameters.bucketPolicy.allowedIAMRoleArn
      toFieldPath: spec.forProvider.policy.statements[0].principal.awsPrincipals[0].iamRoleArn
    - fromFieldPath: metadata.annotations[crossplane.io/bucket-arn]
      toFieldPath: spec.forProvider.policy.statements[0].resource[0]
```

In this case, it would be useful to allow users to specify additional policy statements to append to the statements created by default in the composition, but there is no good way to apply the calculated bucket ARN value to multiple array items.  

### How could Crossplane help solve your problem?

Add a patch type that can apply a single object element to an indeterminate number of object arrays.  For example:

```yaml
resources:
- name: sample-bucket
  spec:
    forProvider:
      policy:
        statements:
        - resource: []
  patches:
  # append array elements of policy statements to the existing default
  - fromFieldPath: spec.parameters.bucketPolicy.additionalPolicies
    toFieldPath: spec.forProvider.policy.statements
    policy:
      mergeOptions:
        appendSlice: true
  # insert the annotation added to the XR into each array element in statements
  - type: ArrayInsert
    fromFieldPath: metadata.annotations[crossplane.io/bucket-arn]
    toFieldPath: spec.forProvider.policy.statements.resource[0]
```

I think this is _somewhat_ related to #2335 but I think the functionality differs somewhat with that issue being more about programmatically looping over input arrays and this being more the case of straightforward patching, but on multiple items.
