### ISSUE TITLE
update Guide vault-injection and add provider-aws

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#2785]
### How could Crossplane help solve your problem?

update guide https://crossplane.io/docs/v1.5/guides/vault-injection.html for provider-aws

**create policy**
```
vault policy write provider-creds - <<EOF
path "secret/data/provider-creds/*" {
    capabilities = ["read", "list"]
}
EOF
```

**create role**
```
vault write auth/kubernetes/role/crossplane-providers  \
        bound_service_account_names="*" \
        bound_service_account_namespaces=crossplane-system \
        policies=provider-creds \
        ttl=24h
```

create vault secret
```
vault kv put secret/provider-creds/aws-default access_key="access" secret_key="secret"
```

controller-config
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: vault-config
spec:
  args:
    - --debug
  metadata:
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "crossplane-providers"
      vault.hashicorp.com/agent-inject-secret-creds.txt: "secret/provider-creds/aws-default"
      vault.hashicorp.com/agent-inject-template-creds.txt: |
        {{- with secret "secret/provider-creds/aws-default" -}}
          [default]
          aws_access_key_id="{{ .Data.data.access_key }}"
          aws_secret_access_key="{{ .Data.data.secret_key }}"
        {{- end -}}
```
