### ISSUE TITLE
KMS key and alias do not work when applied at the same time 

### ISSUE THREAD

**Issue by betoui** [crossplane/crossplane#2815]
### What happened?
When I apply a key and its alias in the same file or in two different files at the same time 

The examples below work fine when applied sequentially (key first, alias second) 

When applied at the same time it looks like `targetKeyIdRef` is treated like the `keyId` and crossplane cannot find it. 

```
Events:
  Type     Reason                        Age               From                                 Message
  ----     ------                        ----              ----                                 -------
  Warning  CannotCreateExternalResource  8s (x6 over 13s)  managed/alias.kms.aws.crossplane.io  cannot create Alias in AWS: NotFoundException: Invalid keyId my-key
  ```

I tried a few different things including restarting the provider but nothing seems to work. 

This is currently clashing with our deployment templates. 

### How can we reproduce it?

``` yaml
 apiVersion: kms.aws.crossplane.io/v1alpha1
 kind: Key
 metadata:
     name: my-key
     namespace: crossplane
 spec:
     deletionPolicy: Delete
     forProvider:
         region: <my-region>
         pendingWindowInDays: 21 
         tags:
         - tagKey: app
           tagValue: test
     providerConfigRef:
         name: provider-aws-config
  
---
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Alias
metadata:
    name: my-test
    namespace: crossplane
spec:
    deletionPolicy: Delete
    forProvider:
        region: <my-region>
        targetKeyIdRef:
            name: my-key
    providerConfigRef:
        name: provider-aws-config

```

### What environment did it happen in?
crossplane:v1.5.0
kubectl:v1.22
provider-aws:v0.22.0

I have also raise the issue [here](https://github.com/crossplane/provider-aws/issues/1049)
