### ISSUE TITLE
Crossplane v1.6.1 not able to handle package deployments 

### ISSUE THREAD

**Issue by mcbenjemaa** [crossplane/crossplane#2839]
### What happened?

Updating to `1.6.1` makes crossplane not able to handle new package deployments (providers, configurations).
No information in the describe mode, events, and no `pkgrev`
no logs even in debug mode!

Although, it was working in `1.5.1` once updating to `1.6.1` the packages are being marked as unhealthy and could not handle any new packages..

same applies when using public pkg e.g.

```
k crossplane install provider crossplane/provider-kubernetes:v0.1.0
```

The only thing I can see is this e.g. (no pkgrev)

```
(⎈ |dev-tec-myadm-sa:default)☁  ~  k get provider
NAME                  INSTALLED   HEALTHY   PACKAGE                                                    AGE
provider-kubernetes                         some-registry/provider-kubernetes:v0.1.0                   63m
```

Here's more information of our setup:

- We are using a DTR(Docker trusted registry) and we will migrate to Google artifact registry.

- We have a PROXY, so we set proxy entries in crossplane core POD (public communication).

```yaml
env: 
- name: http_proxy
  value: http://something:80
- name: https_proxy
  value: http://something:80
- name: no_proxy
  value: something-different, 127.0.0.1, localhost, metadata, metadata.google.internal, *.googleapis.com

```

- We use `imagePullSecrets` 

Ref: [slack-discussion](https://crossplane.slack.com/archives/CEG3T90A1/p1642001970110600)

### How can we reproduce it?

Update crossplane to v1.6.1 while using a PV for cache.
TBD

### What environment did it happen in?
Crossplane version: v1.6.1
We are using our own registry!
Environment GKE.
K8s version: v1.21.5
We are using a PV for cache.
