### ISSUE TITLE
Add SYNCED status column to XRC and XR

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#2850]
### What problem are you facing?

Currently Crossplane adds a `READY` column to a XRC and XR that is either `True` or `False` depending on the state of the managed resources:

```yaml
- additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
```

However, it is difficult to distinguish between MR and composition issues without looking inside the XRC or XR. This can be especially troublesome if you have a lot of XRCs.

### How could Crossplane help solve your problem?

Crossplane should add an additional column called `SYNCED` to every XRC and XR similar to the `SYNCED` column of managed resources:

```yaml
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
```

This would require adding an additional `Synced` condition to `status.conditions`, i.e:

```yaml
  - lastTransitionTime: "2021-12-17T12:50:27Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
