### ISSUE TITLE
Custom Provider proposal

### ISSUE THREAD

**Issue by mcbenjemaa** [crossplane/crossplane#2860]
### What problem are you facing?

No supports for certain internal applications.

####  CustomProvider

The idea I Have is to somehow generate a resource definition from an OPENAPI spec!
In my current project, we are leveraging crossplane to build a control plane to provide a multi-tenant environments.

We always have the issue of not having support for either cloud APIs or any internal application APIs..
That being said, I have noticed the implementation of terrajet, that's awesome, it could help in many uses-cases... 

But not for all!

Basically we have a lot of internal applications, we wanted to have crossplane supports so that we can enable application teams self-service (that's our goal!).

But, unfortunately, no support for those providers...

I have the idea to build a component that can help in this situation. 
essentially,  interpret an OPENAPI spec into a provider. (Which means submitting an openapi spec,  you got custom resources that you can apply)

that's really will take a lot of time for me....

Our uses case, for instance we have (Jira, Gitlab, Confluence, ServiceNow, Harbor, DTR registry, Internal application for credentials, Databases API driven, some other internal application... )

we wanted to combine crossplane with HNC to build a control plane so that our application teams could use it: 

For example:

- create a new jira project.
- create a new space in confluence
- create a database..
- etc....

My idea is that crossplane could have an option that lets you submit an OpenAPI spec and that creates custom resources, you can eventually apply...

This what I have thought about:
* Crossplane can have a new component (controller) that handles this new strategy of building a custom provider.

     - I assume it's best to separate this logic from crossplane core, for performance perspectives, as the core handles composition and XRDs...

* Additionally, this component can be enabled or disabled via helm values...

Following is a better overview of what this component can provide:

* Adding support for a new resource, e.g. `CustomProviderDefinition`

Maybe something like! (this is yet my proposal, it can be detailed in a design document...)

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CustomProviderDefinition
metadata:
  name: myprovider.internal.example.org
spec:
  group: internal.example.org
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:               # this is the schema of the API, 
       raw:
  providerConfigSpec:    # To construct a provider config 
     openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
  providerConfigRef:    # Or maybe in a seprate resource.
```

Once you apply it, the new component (I have mentioned) creates CRDs based on the endpoints. e.g. ever resource endpoint that has `GET, POST, PUT, DELETE` can be implemented.

In the status of this `CustomProviderDefinition` you will find the created CRDs...

Then, now you are able to create this new kind...

Example:

```yaml
apiVersion: internal.example.org/v1alpha1
kind: MyNewKind
metadata:
  name: MyNewResource
spec:
  storageGB: 100       # example....
  providerConfigRef:   # to select which config to use.
      name: default
      namespaces: default 
```

The trick is here!

Now applying this resource, will combine it with the providerconfig and creates  REST Calls to the underlying service... 
So, this component will handle the reconciliation of those new kinds.

The next trick is the status and the health of those resources:
- I think using a `GET` call, we can confirm the presence of the resource.

Summary: This new component is able to build REST calls based on new `CustomProviderDefinition` /providerconfig.. And this will handle their reconciliation.

Note this is only a proposal if it's really reasonable, it's great to see this happening, I think this will be great to enhance crossplane extensibility.

PS: The name I gave e.g. `CustomProviderDefinition`, `providerconfig` those are just samples.
I wrote this quickly, so there might be some typos
