### ISSUE TITLE
Rendered CRD from an XRD is not getting recreated after deletion

### ISSUE THREAD

**Issue by luebken** [crossplane/crossplane#2870]
### What happened?

I've created the following simple XRD: 
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xacmebuckets.storage.example.com
spec:
  group: storage.example.com
  names:
    kind: XAcmeBucket
    plural: xacmebuckets
  claimNames:
    kind: AcmeBucket
    plural: acmebuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  bucketName:
                    description: The Bucket name
                    type: string
                required:
                - bucketName
            required:
            - parameters
```
which successfully rendered two CRDs: 
```
kubectl get crds | grep acme
acmebuckets.storage.example.com                     2022-01-27T13:26:51Z
xacmebuckets.storage.example.com                    2022-01-27T13:26:51Z
```
afterwards, I've deleted one CRD:
```
kubectl delete crds acmebuckets.storage.example.com
customresourcedefinition.apiextensions.k8s.io "acmebuckets.storage.example.com" deleted
```
and was expecting that it would be rerendered / recreated but it wasn't:

```
kubectl get crds | grep acme
xacmebuckets.storage.example.com                                2022-01-31T13:29:32Z
```

### How can we reproduce it?

See above

### What environment did it happen in?
Crossplane version: crossplane-1.6.1
