### ISSUE TITLE
Changing composition via compositionSelector not working and keeps garbage

### ISSUE THREAD

**Issue by braghettos** [crossplane/crossplane#2875]
### What happened?

I wrote two compositions and I install them via Configuration: https://github.com/krateoplatformops/krateo-module-core. I wad trying to claim the composition of OpenShift. Initially I used a 

```
spec:
  compositionSelector:
    matchLabels:
      provider: kubernetes
```

in the claim, but then I deleted the claim and changed it to the following one:

```
spec:
  compositionSelector:
    matchLabels:
      provider: openshift
```

In the composition for kubernetes (_composition-kubernetes.yaml_), I manage two releases via provider-helm (one for argocd and one for our dashboard), while in the composition for openshift (_composition-openshift.yaml_) I manage only one release (the one for our dashboard) and for argocd I apply a manifest via _provider-kubernetes_.

What happened is that both the compositions are applied in the cluster i.e. ArgoCD is created twice, with the provider-helm and the provider-kubernetes.

### How can we reproduce it?

Requirement: have an OpenShift cluster available with the gitops-operator installed.

Then:

`kubectl apply -f https://github.com/krateoplatformops/krateo-module-core/blob/main/defaults/krateo-package-module-core.yaml`

And then apply the following claim:

```
apiVersion: modules.krateo.io/v1alpha1
kind: Core
metadata:
  name: krateo-module-core
spec:
  compositionSelector:
    matchLabels:
      provider: openshift
  organization: Krateo PlatformOps
  frontendUrl: https://krateo.example.com
  frontend:
    service:
      type: ClusterIP
  backendUrl: https://krateo.example.com
  backend:
    service:
      type: ClusterIP
  ingress:
    enabled: true
  lighthouse:
    enabled: false
  providers:
    github:
      clientId: xx
      clientSecret: xx
      token: xx
  argo-cd:
    version: 3.33.1
  krateo-dashboard:
    postgresql:
      volumePermissions:
        enabled: false
        securityContext:
          runAsUser: "auto"
      securityContext:
        enabled: false
      shmVolume:
        chmod:
          enabled: false
      containerSecurityContext:
        enabled: false
    version: 0.3.132
```

### What environment did it happen in?
* Crossplane version: `1.5.0`
* Cloud provider or hardware configuration: `on premise, vmware`
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+e790d7f", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2021-12-14T02:10:38Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): `OpenShift`
