### ISSUE TITLE
packagePullSecrets not working on v1.6.2

### ISSUE THREAD

**Issue by fahedouch** [crossplane/crossplane#2876]
### What happened?

`401 authorization required` on private registry when using the latest stable version `v1.6.2` 

it works with `v1.6.1` 
### How can we reproduce it?

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: test
spec:
  package: "eu.gcr.io/xxx"
  packagePullPolicy: Always
  packagePullSecrets:
    - name: gcr-json-key
  ```
### What environment did it happen in?
Crossplane version:  v1.6.2
