### ISSUE TITLE
Label propagation from XRs to MRs is inconsistent

### ISSUE THREAD

**Issue by EdgeJ** [crossplane/crossplane#2879]
### What happened?

When creating objects from the aws provider through a composition, labels that are passed into the claim propagate to the XRs but are inconsistently applied to the MRs.

### How can we reproduce it?

Copies of the YAML manifests I used can be found in this gist: https://gist.github.com/EdgeJ/68f085192c87db48cd5ad13da74ed804

Applying these locally, I see the XRD I've created with the claim with the correct label:
```
➜ kubectl get xclouduser example-user-84ph7 -o yaml
apiVersion: iam.aws.simspace.com/v1alpha1
kind: XCloudUser
metadata:
<SNIP>
  labels:
    crossplane.io/claim-name: example-user
    crossplane.io/claim-namespace: crossplane-dev-account
    crossplane.io/composite: example-user-84ph7
    user-group: example-group
```

But the `User` object created from the XR is missing the label:
```
➜ kubectl get users.iam.aws.crossplane.io example-user-84ph7-q4rvb -o yaml
apiVersion: iam.aws.crossplane.io/v1beta1
kind: User
metadata:
<SNIP>
  labels:
    crossplane.io/claim-name: example-user
    crossplane.io/claim-namespace: crossplane-dev-account
    crossplane.io/composite: example-user-84ph7
```

Other resources do not have this problem. For example, when creating an IAM Policy with the `policy.iam.aws.crossplane.io` type, the labels correctly propagate and can be used for a `labelSelector`.

### What environment did it happen in?
Crossplane version: v1.6.2
Kubernetes version: v1.22
Kubernetes distro: Docker for Desktop
OS: macOS 12.2
