### ISSUE TITLE
Composition resources not synced when updating a claim

### ISSUE THREAD

**Issue by lsoica** [crossplane/crossplane#2882]
### What happened?
Composition resources not reconciled on Claim update.

### How can we reproduce it?
I have these APIs defined:
 - An XRD, XPostgreSQLInstance
 - One Composition that leverage the Kubernetes provider to compose a Postgres deployment through Flux CRs (one HelmRelease and one HelmRepository as its resources)
 - A claim that instantiate the XR with the above composition and with custom configuration

First time I deploy the Claim, everything is smooth. 
Next, when I change a parameter on the claim, that's used in a patch in the Composition:
 - the claim is updated
 - the XR is updated
 - the Composition resources that are defined as kubernetes provider Object are not updated.

### What environment did it happen in?
Crossplane version: 1.6

**Comment by negz** [comment]
@lsoica are you expecting the `Composition` itself to be updated? That won't happen - the `Composition` is used to render distinct, new resources (mostly managed resources). If you're not seeing those managed resources being updated, could you please `kubectl describe` your claim and XR, and provide the output here.

**Comment by lsoica** [comment]
@negz my expectation is that, if I update a parameter in the claim, that's used in the Composition in a patch for one of the managed resources, to have those managed resources updated. Is this a misunderstanding on my side ?

Below is the:
 - claim
 - XR
 - composition
 - managed resource
In the claim, spec.providerSpecificParameters.someOtherValue: 5
In the composition, "providerSpecificParameters" is used in a patch on the managed resource.
In the XR, spec.providerSpecificParameters.someOtherValue: 5
In the managed resource: providerSpecificParameters.someOtherValue: 4

```
$ kubectl describe PostgreSQLInstance -A
Name:         nci-service-postgres-default
Namespace:    nci-service-postgres
Labels:       <none>
Annotations:  <none>
API Version:  nci.com/v1alpha1
Kind:         PostgreSQLInstance
Metadata:
  Creation Timestamp:  2022-02-07T12:11:19Z
  Finalizers:
    finalizer.apiextensions.crossplane.io
  Generation:  3
  Managed Fields:
...
  Resource Version:  1245515
  UID:               da76a46c-de72-4e19-9298-8ab5fcf7ccc8
Spec:
  Composition Ref:
    Name:  postgresql-nci
  Composition Selector:
    Match Labels:
      Provider:               provider-nci
  Composition Update Policy:  Automatic
  Parameters:
    Storage GB:  20Gi
  Provider Specific Parameters:
    Some Other Value:  5
    Some Value:        1
    Target Name:       nci-service-postgres
    Target Namespace:  nci-service-postgres
  Resource Ref:
    API Version:  nci.com/v1alpha1
    Kind:         XPostgreSQLInstance
    Name:         nci-service-postgres-default-k8fvd
  Write Connection Secret To Ref:
    Name:  nci-service-postgres-default
Status:
  Conditions:
    Last Transition Time:  2022-02-07T12:11:22Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Connection Details:
    Last Published Time:  2022-02-07T12:11:22Z
Events:
  Type    Reason                      Age                 From                                                             Message
  ----    ------                      ----                ----                                                             -------
  Normal  ConfigureCompositeResource  26m (x15 over 42h)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully applied composite resource
  Normal  BindCompositeResource       26m (x10 over 42h)  offered/compositeresourcedefinition.apiextensions.crossplane.io  Successfully bound composite resource
```

```
$ kubectl describe XPostgreSQLInstance nci-service-postgres-default-k8fvd
$ kubectl describe XPostgreSQLInstance nci-service-postgres-default-k8fvd
Name:         nci-service-postgres-default-k8fvd
Namespace:    
Labels:       crossplane.io/claim-name=nci-service-postgres-default
              crossplane.io/claim-namespace=nci-service-postgres
              crossplane.io/composite=nci-service-postgres-default-k8fvd
Annotations:  <none>
API Version:  nci.com/v1alpha1
Kind:         XPostgreSQLInstance
Metadata:
  Creation Timestamp:  2022-02-07T12:11:19Z
  Generate Name:       nci-service-postgres-default-
  Generation:          5
  Resource Version:  1751306
  UID:               1dc5cdfa-49ce-4db9-a7b3-d651d180382d
Spec:
  Claim Ref:
    API Version:  nci.com/v1alpha1
    Kind:         PostgreSQLInstance
    Name:         nci-service-postgres-default
    Namespace:    nci-service-postgres
  Composition Ref:
    Name:  postgresql-nci
  Composition Selector:
    Match Labels:
      Provider:               provider-nci
  Composition Update Policy:  Automatic
  Parameters:
    Storage GB:  20Gi
  Provider Specific Parameters:
    Some Other Value:  5
    Some Value:        1
    Target Name:       nci-service-postgres
    Target Namespace:  nci-service-postgres
  Resource Refs:
    API Version:  kubernetes.crossplane.io/v1alpha1
    Kind:         Object
    Name:         nci-service-postgres-default-k8fvd-glkbm
    API Version:  kubernetes.crossplane.io/v1alpha1
    Kind:         Object
    Name:         nci-service-postgres-default-k8fvd-p257n
  Write Connection Secret To Ref:
    Name:       1dc5cdfa-49ce-4db9-a7b3-d651d180382d
    Namespace:  nci-service-postgres-default
Status:
  Conditions:
    Last Transition Time:  2022-02-07T12:11:21Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Connection Details:
    Last Published Time:  2022-02-07T12:11:20Z
Events:
  Type    Reason             Age                   From                                                             Message
  ----    ------             ----                  ----                                                             -------
  Normal  SelectComposition  60s (x2544 over 42h)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully selected composition
```

```
$ kubectl describe composition postgresql-nci
Name:         postgresql-nci
Namespace:    
Labels:       crossplane.io/xrd=xpostgresqlinstances.nci.com
              provider=provider-nci
Annotations:  <none>
API Version:  apiextensions.crossplane.io/v1
Kind:         Composition
Metadata:
  Creation Timestamp:  2022-02-07T11:40:49Z
  Generation:          6
  Managed Fields:
...
  Resource Version:  1244876
  UID:               0fb758e1-2464-4989-b063-a06c262b0c8d
Spec:
  Composite Type Ref:
    API Version:  nci.com/v1alpha1
    Kind:         XPostgreSQLInstance
  Resources:
    Base:
      API Version:  kubernetes.crossplane.io/v1alpha1
      Kind:         Object
      Spec:
        For Provider:
          Manifest:
            API Version:  helm.toolkit.fluxcd.io/v2beta1
            Kind:         HelmRelease
            Metadata:
              Name:       nci-service-postgres-default
              Namespace:  nci-service-postgres-default
            Spec:
              Chart:
                Spec:
                  Chart:     postgres
                  Interval:  1m0s
                  Source Ref:
                    Kind:  HelmRepository
                    Name:  nci-service-postgres-default
              Install:
                Remediation:
                  Retries:  30
              Interval:     1m0s
              Values:
                Global:
                  backup_dir:   /backup
                  Domain Name:  primary-cluster-1
                  Nci:
                    Logging:
                      Mode:  full
                    Monitoring:
                      Mode:  full
                    Services:
                      Nci - Common:
                        Images:
                          Init Chown:
                            Image Pull Policy:  IfNotPresent
                            Name:               init-chown
                            Repository:         nci-container-os
                            Tag:                g927a9bb
                      Nci - Storage:
                        Persistent Volumes:
                          Backup Restore:
                            Signature:
                              Host Path:
                                Path:              /var/lib/docker/persistent/backup-restore-dir
                              Storage Class Name:  hostpath
                        Storage Classes:
                          Default:         hostpath
                          Host - Storage:  hostpath
                  Registry:                nci-docker.artifactory6.ds.jdsu.net
        Provider Config Ref:
          Name:  kubernetes-provider
    Name:        nciservicepostgresinstance
    Patches:
      From Field Path:  spec.providerSpecificParameters
      Policy:
        Merge Options:
          Keep Map Values:  true
      To Field Path:        spec.forProvider.manifest.spec.values
      Type:                 FromCompositeFieldPath
      From Field Path:      spec.providerSpecificParameters.targetNamespace
      To Field Path:        spec.forProvider.manifest.metadata.namespace
      Type:                 FromCompositeFieldPath
      From Field Path:      spec.providerSpecificParameters.targetName
      To Field Path:        spec.forProvider.manifest.metadata.name
      Type:                 FromCompositeFieldPath
      From Field Path:      spec.providerSpecificParameters.targetName
      To Field Path:        spec.forProvider.manifest.spec.chart.spec.sourceRef.name
      Type:                 FromCompositeFieldPath
      From Field Path:      spec.parameters.storageGB
      To Field Path:        spec.forProvider.manifest.spec.values.global.persistence.size
      Type:                 FromCompositeFieldPath
    Base:
      API Version:  kubernetes.crossplane.io/v1alpha1
      Kind:         Object
      Spec:
        For Provider:
          Manifest:
            API Version:  source.toolkit.fluxcd.io/v1beta1
            Kind:         HelmRepository
            Metadata:
              Name:       nci-service-postgres-default
              Namespace:  nci-service-postgres-default
            Spec:
              Interval:  1m0s
              Timeout:   1m0s
              URL:       https://artifactory6.ds.jdsu.net:443/artifactory/nci-helm/
        Provider Config Ref:
          Name:  kubernetes-provider
    Name:        nciserviceshelmrepo
    Patches:
      From Field Path:                    spec.providerSpecificParameters.targetNamespace
      To Field Path:                      spec.forProvider.manifest.metadata.namespace
      Type:                               FromCompositeFieldPath
      From Field Path:                    spec.providerSpecificParameters.targetName
      To Field Path:                      spec.forProvider.manifest.metadata.name
      Type:                               FromCompositeFieldPath
  Write Connection Secrets To Namespace:  nci-service-postgres-default
Events:                                   <none>
```

```
$ kubectl describe Object nci-service-postgres-default-k8fvd-glkbm
Name:         nci-service-postgres-default-k8fvd-glkbm
Namespace:    
Labels:       crossplane.io/claim-name=nci-service-postgres-default
              crossplane.io/claim-namespace=nci-service-postgres
              crossplane.io/composite=nci-service-postgres-default-k8fvd
Annotations:  crossplane.io/composition-resource-name: nciservicepostgresinstance
              crossplane.io/external-name: nci-service-postgres-default-k8fvd-glkbm
API Version:  kubernetes.crossplane.io/v1alpha1
Kind:         Object
Metadata:
  Creation Timestamp:  2022-02-07T12:11:20Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generate Name:  nci-service-postgres-default-k8fvd-
  Generation:     1
  Owner References:
    API Version:     nci.com/v1alpha1
    Controller:      true
    Kind:            XPostgreSQLInstance
    Name:            nci-service-postgres-default-k8fvd
    UID:             1dc5cdfa-49ce-4db9-a7b3-d651d180382d
  Resource Version:  1253630
  UID:               a37c4a98-cf3d-4f2d-88dd-49c64eaf1ca8
Spec:
  For Provider:
    Manifest:
      API Version:  helm.toolkit.fluxcd.io/v2beta1
      Kind:         HelmRelease
      Metadata:
        Name:       nci-service-postgres
        Namespace:  nci-service-postgres
      Spec:
        Chart:
          Spec:
            Chart:     postgres
            Interval:  1m0s
            Source Ref:
              Kind:  HelmRepository
              Name:  nci-service-postgres
        Install:
          Remediation:
            Retries:  30
        Interval:     1m0s
        Values:
          Some Other Value:  4
          Some Value:        1
          Target Name:       nci-service-postgres
          Target Namespace:  nci-service-postgres
  Provider Config Ref:
    Name:  kubernetes-provider
Status:
  At Provider:
    Manifest:
      API Version:  helm.toolkit.fluxcd.io/v2beta1
      Kind:         HelmRelease
      Metadata:
        Annotations:
          kubectl.kubernetes.io/last-applied-configuration:  ...
        Creation Timestamp:                                  2022-02-07T12:46:25Z
        Finalizers:
          finalizers.fluxcd.io
        Generation:  1
        Name:              nci-service-postgres
        Namespace:         nci-service-postgres
        Resource Version:  1253562
        UID:               4e8bf698-4123-4897-abe5-5cf01a65f6c5
      Spec:
        Chart:
          Spec:
            Chart:               postgres
            Interval:            1m0s
            Reconcile Strategy:  ChartVersion
            Source Ref:
              Kind:   HelmRepository
              Name:   nci-service-postgres
            Version:  *
        Install:
          Remediation:
            Retries:  30
        Interval:     1m0s
        Values:
          Some Other Value:  4
          Some Value:        1
          Target Name:       nci-service-postgres
          Target Namespace:  nci-service-postgres
      Status:
        Conditions:
          Last Transition Time:          2022-02-07T12:47:05Z
          Message:                       Release reconciliation succeeded
          Reason:                        ReconciliationSucceeded
          Status:                        True
          Type:                          Ready
          Last Transition Time:          2022-02-07T12:47:05Z
          Message:                       Helm install succeeded
          Reason:                        InstallSucceeded
          Status:                        True
          Type:                          Released
        Helm Chart:                      nci-service-postgres/nci-service-postgres-nci-service-postgres
        Last Applied Revision:           12.0.0
        Last Attempted Revision:         12.0.0
        Last Attempted Values Checksum:  7d2fb4ad9b31dd428c18994fa529cdf232d1fafa
        Last Release Revision:           1
        Observed Generation:             1
  Conditions:
    Last Transition Time:  2022-02-07T12:46:25Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-02-07T12:11:20Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:                    <none>
```

**Comment by kertzi** [comment]
I hit this issue too, so I wonder what is correct way to update existing configuration? 
In my case for example ec2 instance type from t3.micro to t3.small.

I have understood too that If I change parameter value in claim which is patched in composition to update value in forProvider this should reflect changes to actual infra.

**Comment by kertzi** [comment]
Also find out that when changing some of forProvider parameter in composition it doesn't get updated to managed resource.

For example changing ec2 instance type in composition it will not trigger any updates to actual environment.
But when ADDING new resource to composition it will update that to actual environment.

So there is something broken in link between Composition and XRs created for that Composition. I use Claim to provision XRs

**Comment by ezgidemirel** [comment]
Hello @lsoica, I tried to reproduce the issue with Crossplane 1.7.0, but couldn't be successful. The update I made on the claim propagated to the managed resource and to the cloud provider. Could you please give it another try with the latest version and/or share your composition/definition/claim manifests with me? Thanks!

**Comment by noyoshi** [comment]
I think the issue was that updating the composition didn't update all the resources using that composition within the cloud provider? Not that updating a claim updates the resources in the cloud provider. I have hit this case where it sometimes works and sometimes doesn't, although with my case its the azure-terrajet provider.

**Comment by Ottovsky** [comment]
I am observing the same behavior with crossplane v1.8.0, when updating claim, the update is propagated to the XR, but the composition resources do not reflect this update.

**Comment by Ram8978** [comment]
> when I tried to update the claim, the change not propagated to the cloud provider. I am using Crossplane 1.9.0. Example: RDS storage from 20G

**Comment by ride808** [comment]
@ezgidemirel I hit this issue as well in crossplane v1.10.1. I applied the resources below and then tried to update my claim's storageGB parameter to see the two ec2 instances get updated with larger storage. The claim showed as synced but no changes were made to the managed ec2 cloud instances.

xrd:

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xadmininstances.hades.org
spec:
  group: hades.org
  names:
    kind: XAdminInstance
    plural: xadmininstances
  claimNames:
    kind: AdminInstance
    plural: admininstances
  connectionSecretKeys:
  - admin-1
  - admin-2
  defaultCompositionRef:
    name: admin-server
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                required:
                - storageGB
            required:
            - parameters
```

XR:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: admin-server
  labels:
    crossplane.io/xrd: xadmininstances.aws.hades.org
    provider: provider-aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: hades.org/v1alpha1
    kind: XAdminInstance
  resources:
  - name: securitygroup
    base:
      apiVersion:  ec2.aws.crossplane.io/v1beta1
      kind: SecurityGroup
      spec:
        forProvider:
          region: us-east-1
          vpcId: vpc-0186b862b83f5cd71
          description: Admin server for Environment
          ingress:
            - fromPort: 0
              toPort: 65535
              ipProtocol: tcp
              ipRanges:
                - cidrIp: 10.77.77.20/32
            - fromPort: 22
              toPort: 22
              ipProtocol: tcp
              ipRanges:
                - cidrIp: 10.77.77.10/32
            - fromPort: 22
              toPort: 22
              ipProtocol: tcp
              ipRanges:
                - cidrIp: 166.28.0.0/16
            - fromPort: 443
              toPort: 443
              ipProtocol: tcp
              ipRanges:
                - cidrIp: 0.0.0.0/32
            - fromPort: 8080
              toPort: 8084
              ipProtocol: tcp
              ipRanges:
                - cidrIp: 0.0.0.0/32
            - fromPort: 80
              toPort: 80
              ipProtocol: tcp
              ipRanges:
                - cidrIp: 0.0.0.0/0
        providerConfigRef:
          name: provider-aws
    patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "metadata.name"
        toFieldPath: "spec.forProvider.groupName"
  - name: admin-instance-1
    base:
      apiVersion:  ec2.aws.crossplane.io/v1alpha1
      kind: Instance
      spec:
        forProvider:
          region: us-east-1
          imageId: ami-02ae903c0b1d9fd12
          instanceType: t3.medium
          keyName: hades-key
          blockDeviceMappings:
          - deviceName: /dev/sdx
            ebs:
              volumeType: gp3
          subnetId: subnet-08d3a539398176845
          securityGroupSelector:
            matchControllerRef: true
          tags:
            - key: Name
              value: somogyi-admin-1
        providerConfigRef:
          name: provider-aws
    patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.parameters.storageGB"
        toFieldPath: "spec.forProvider.blockDeviceMappings[0].ebs.volumeSize"
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.writeConnectionSecretToRef.name"
        toFieldPath: "spec.publishConnectionDetailsTo.name"
    connectionDetails:
    - name: admin-1
      type: FromFieldPath
      fromFieldPath: status.atProvider.privateIpAddress
  - name: admin-instance-2
    base:
      apiVersion:  ec2.aws.crossplane.io/v1alpha1
      kind: Instance
      spec:
        forProvider:
          region: us-east-1
          imageId: ami-02ae903c0b1d9fd12
          instanceType: t3.medium
          keyName: hades-key
          blockDeviceMappings:
          - deviceName: /dev/sdx
            ebs:
              volumeType: gp3
          subnetId: subnet-08d3a539398176845
          securityGroupSelector:
            matchControllerRef: true
          tags:
            - key: Name
              value: somogyi-admin-2
        providerConfigRef:
          name: provider-aws
    patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.parameters.storageGB"
        toFieldPath: "spec.forProvider.blockDeviceMappings[0].ebs.volumeSize"
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.writeConnectionSecretToRef.name"
        toFieldPath: "spec.publishConnectionDetailsTo.name"
    connectionDetails:
    - name: admin-2
      type: FromFieldPath
      fromFieldPath: status.atProvider.privateIpAddress
```

Claim:

```
apiVersion: hades.org/v1alpha1
kind: AdminInstance
metadata:
  namespace: default
  name: somogyi-admin
spec:
  parameters:
    storageGB: 30
  compositionSelector:
    matchLabels:
      provider: provider-aws
  writeConnectionSecretToRef:
    name: my-admin-server-connection-details
```

**Comment by ride808** [comment]
Should this issue be re-opened?

**Comment by edgarkiechle** [comment]
Any updates regarding this? Same issue is happening to me, updating a parameter on the claim that is patched in the composition does not trigger any updates on the deployed resources in the cloud. I actually have to delete the managed resource to see it recreated with the updated value. Surely this is not the expected behavior.

**Comment by bobh66** [comment]
>  Surely this is not the expected behavior.
It may be, depending on the resource and the attribute that is being updated.  Many managed resource attributes are immutable and cannot be changed after deployment without deleting and recreating the resource, which in general is not something the provider is going to do by default.

**Comment by edgarkiechle** [comment]
> It may be, depending on the resource and the attribute that is being updated. Many managed resource attributes are immutable and cannot be changed after deployment without deleting and recreating the resource, which in general is not something the provider is going to do by default.

Changing subnets service endpoints or increasing storage should be something that is reflected on the managed resource as they do not force resource recreation.

**Comment by jbw976** [comment]
One thing I'd like to understand better here is if this behavior is at the composition machinery layer or it's at the provider reconciliation layer (i.e. specific to the provider-aws EC2 instance controller).

@edgarkiechle would you be willing to help with a little investigation to confirm this?  One test to perform would be to just directly create the managed resource (not within a composition), then update one of the fields in question.  Does the update get propagated to the cloud provider?  If it does not, then we may be able to conclude that the behavior isn't within the composition machinery, and can follow up more appropriately on the provider.

**Comment by jfmrm** [comment]
I'm facing a similar issue, some times when I update my Composition my Composite Resource doesn't sync. What happened was:
1. Updated Composition, and it propagated well, but introduced and error on the Composite Resource sync.
2. I updated again the Composition, the Composite Resource Claim picked up the change and propagated to the Composite Resource, the Composite Resource is able to select the new Composite Revision, but it never syncs.

**Comment by siredmar** [comment]
I cam across this issue too. 
I changed a value in my composite resource and expected that the new value is propagated to the corresponding managed resource what didn't happen. I needed to delete the whole composite resource and recreate in order to get the new configuration i defined in my claim.

**Comment by siredmar** [comment]
@jbw976 what information do you need to investigate further?

**Comment by ashishvaishno** [comment]
Hello,

I am also facing a similar issue. I am creating a IAM role and passing a parameter for the name of the role in my claim. When I try to update the role name, it doesnt get reflected. 

Regards
Ashish

**Comment by mattfield** [comment]
Also having the same issue.

When the `vpcSecurityGroupIdRefs` field in a Composition that creates an RDS Cluster had the wrong value, the reference doesn't resolve to a known object and so the XR creation fails. When this value is corrected, the XR creation is not retried/re-rendered by the Composition, despite the field value changing.

I've also observed the same issue with references to security groups, preferred maintenance window, and preferred backup window. I've checked and none of these fields are immutable, and shouldn't trigger recreation of the underlying resource, so I'd expect the change of these values to trigger the Composition to render a proposed change to the resources it creates, but it doesn't.

I'm on Crossplane 1.13.2, EC2/RDS providers v0.37.0.

**Comment by sanketgawade** [comment]
I have also ran same issue. 
The statemachine claim is not updating the Definition for the step function. 
Running Crossplane 1.10.1 aws-provider v0.38.0

**Comment by Shwethamuralikrishnaa** [comment]
I'm also facing a similar issue, I'm attempting to update/modify our pre-existing claim using a composition and XRD, but I haven’t been successful so far.
In the first test case, I tried to enable _EventBridge: true_ and set it as the default in the composition. Later I updated the composition and set it to false (and tried it vice-versa as well).

In the second test case, I added the tag _s3-Backup-Enabled: Yes_ to the S3 bucket via composition, and later attempted to update the tag in the composition to _s3-Backup-Enabled: Yes123_
However, in both cases, the managed resources were not updated.

**Comment by pierluigilenoci** [comment]
@jeanduplessis Thank you!

**Comment by johnathan-sq** [comment]
This seems to be still happening. I've noticed this happening when the update from a Claim is an object. The behaviour I've seen is. If I have a ConfigMap with data and I want to patch the data field with that in my Claim, it will always appends rather than replace with mergeOptions set to nothing. Maybe this is a trend above? I tested it with `string` type and it seems to update each and every time, but only with objects it appends rather than replaces. This may be a new issue not sure.

**Comment by jbw976** [comment]
There seem to be a couple different scenarios being discussed in this issue, both resulting in the underlying composed resources for an XR not being updated accordingly:

1. A value is updated on a `Claim`
2. The logic is updated within a `Composition`, which creates a new `CompositionRevision`

At least for `#2`, I just yesterday saw this behavior working OK while debugging a separate issue. I happened to update my `Composition` multiple times while iterating over it to get the behavior correct.  I ended up with 4+ `CompositionRevisions` and with each new revision, I noticed that while it did sometimes take 2-3 minutes, the composed resources defined within the `Composition` were indeed updated to new values via their new logic in the new `CompositionRevision`.

So at least there is a recent datapoint that updating a `Composition` isn't completely broken.

So, if folks happen to run into these cases in the future, it would be great to share:

1. What version of Crossplane are you running? (this issue was first opened for v1.6 and things have changed a lot since then)
2. Are you using Functions and [`Pipeline` mode](https://docs.crossplane.io/latest/concepts/compositions/#use-composition-functions) or are you using the traditional patch and transform `Resources` mode for your composition?
3. A complete and scoped repro scenario that will demonstrate this behavior.
    1.  An example of a clearly defined and easily repeatable repro scenario can be seen in https://gist.github.com/jbw976/4d145d97c1de7f3fa57a7bca437bbe4b.
    2. This makes it so much easier to debug the issue quickly and is really appreciated! 🤓

**Comment by grafanalf** [comment]
I am seeing what I believe is the same behaviour that is explained here under Crossplane 1.14.9:

1. I produced a change to a Composition which triggers a new CompositionRevision.
2. Existing Claims are updated to use this latest CompositionRevision.
3. The underlying managed resources, however, are not updated.

Furthermore, the Crossplane documentation for 1.14 mention that all CompositionRevision resources have a `current` field, which I don't see in our deployments:

```
◦ kubectl get compositionrevision -l crossplane.io/composition-name=staticdnsloadbalancer
NAME                            REVISION   XR-KIND                  XR-APIVERSION                                AGE
staticdnsloadbalancer-883b963   1          XStaticDnsLoadBalancer   ipv4.infra.crossplane.grafana.net/v1alpha1   3d
staticdnsloadbalancer-c11b235   2          XStaticDnsLoadBalancer   ipv4.infra.crossplane.grafana.net/v1alpha1   18h
staticdnsloadbalancer-f40a1eb   3          XStaticDnsLoadBalancer   ipv4.infra.crossplane.grafana.net/v1alpha1   13h
```

```
◦ kubectl get staticdnsloadbalancer prometheus-dev-05-dev-us-east-0 -o json | jq .spec.compositionRevisionRef
{
  "name": "staticdnsloadbalancer-f40a1eb"
}
```

However, the managed resource seems to be in fact using the configuration as per `staticdnsloadbalancer-c11b235`, since the latest revision is removing an annotation from the underlying managed resource, but this change hasn't been applied.

**Comment by zoe-tek** [comment]
I am having this issue as well with updating the composition. New claims create a DB with the imageCatalogRef but running DB resources do not get updated. I can update the resource myself with the change and it rolls out the change to the instance. the composite resource has the new CompositionRevisions. Do i need to add a new label for this to work and does the claim need to have that label?

[Changing the label and the spec values simultaneously is critical for deploying new changes to the dev channel.](https://docs.crossplane.io/latest/concepts/composition-revisions/#update-composition-spec-and-label)

Version: function-patch-and-transform:v0.7.0 id.

Changed the composition from `imageName: ""` to

```
imageCatalogRef:
  name: postgresql
  major: ""
  apiGroup: postgresql.cnpg.io
  kind: ClusterImageCatalog
```
and changed the patch but the what the user puts in stays the same.

old
```
- type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.engineVersion
            toFieldPath: spec.forProvider.manifest.spec.imageName
            transforms:
            - string:
                type: Format
                fmt: "quay.io/enterprisedb/postgresql:%s"
              type: string
```

new
```
- type: FromCompositeFieldPath
            fromFieldPath: spec.parameters.engineVersion
            toFieldPath: spec.forProvider.manifest.spec.imageCatalogRef.major
```

**Comment by zoe-tek** [comment]
@phisco It is not changing. I have 2 test db clusters running. I made the change yesterday, after 10min i manually updated one of the clusters. The other one never got the update.
I might see an issue, i walked thru a new cluster and i thought AWS RDS engineVersion was an integer, but it's a string and cnpg wants an integer. So maybe while the crossplane resource accept the change cnpg does not. I don't see a good way to convert a string to an integer without hardcoding all the values. Might not be hard though, 13-17 is not a lot.

**Comment by zoe-tek** [comment]
Got the formatting to work with this but it still won't update old resources.
```
- type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.engineVersion"
            toFieldPath: "spec.forProvider.manifest.spec.imageCatalogRef.major"
            transforms:
            - type: convert
              convert:
                toType: float64
```
The function-patch-and-transform logs show 
`{"level":"info","ts":1736527226.3273108,"caller":"fn/fn.go:284","msg":"Successfully processed patch-and-transform resources","tag":"","xr-version":"kubic.***.***/v1alpha1","xr-kind":"CompositePostgreSQLInstance","xr-name":"pg-cnpg-b6hhg","resource-templates":1,"existing-resources":1,"warnings":0}`
