### ISSUE TITLE
Transformation: Map String to Integer

### ISSUE THREAD

**Issue by philippart** [crossplane/crossplane#2887]
### What problem are you facing?
Create a transform that maps a string value to an integer.
Doing this today requires 3 steps:
- map string to an intermediate string
- store the intermediate string as a XR field (annotation for example)
- convert that string field into an integer

### How could Crossplane help solve your problem?
Allow the above in 1 step (e.g. transform type = mapToInteger).

**Comment by rkoalign** [comment]
You can probably get this done without having to store intermediate string as XR field. You can have multiple transform types in a single transform block and your input will be transformed in the sequence those transform types are specified. For example:

```
          transforms:
            - type: map
              map:
                small: "2"
                medium: "4"
                large: "8"
            - type: convert
              convert:
                toType: int
```
If your input field is a string "medium", then the resultant value after these transforms should be an integer 4.
