### ISSUE TITLE
Identified more Silent Errors

### ISSUE THREAD

**Issue by kferrone** [crossplane/crossplane#2896]
### What happened?

I'm attempting to make a composition. Once again, I probably have done something wrong but there is no help from Crossplane to figure out what is wrong. No logs, no events, no warnings, no status. Just hangs and does nothing again. 

### How can we reproduce it?

I boiled down the composition to the absolute simplest I can and I still get nothing. I'm totally at a loss here. Anyone else see what is wrong here? 

`definition.yaml`
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: foobars.example.com
spec:
  group: example.com
  names:
    kind: FooBar
    plural: foobars
  defaultCompositionRef:
    name: foo-bar-time
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  description:
                    type: string
                    default: A thing of sorts
            required:
            - parameters
```
`composition.yaml`
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: foo-bar-time
  labels:
    crossplane.io/xrd: foobars.example.com
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: example.com/v1
    kind: FooBar
  resources:

  # build up the role
  - name: irsa-role
    base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: Role
      spec:
        deletionPolicy: Delete
        forProvider:
          assumeRolePolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "arn:aws:iam::123:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/123"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {
                      "oidc.eks.us-west-2.amazonaws.com/id/123:sub": "system:serviceaccount:default:foo"
                    }
                  }
                }
              ]
            }
          description: The EFS CSI driver policy and role for kubernetes volumes.
          path: /
        providerConfigRef:
          name: default
    patches:
    - fromFieldPath: metadata.name
    - fromFieldPath: spec.parameters.description
      toFieldPath: spec.forProvider.description
```
`example.yaml`
```yaml
apiVersion: example.com/v1
kind: FooBar
metadata:
  name: efs-vol
spec:
  parameters:
    description: Just a test
```

**Comment by kferrone** [comment]
I have discovered a perfect time for an event to propagate to the xr. When a patchset references a non existent patchset. Simply let the user know in the events. 

I am also discovering that certain resources need defaults in the base instead of just omitting then letting the patches set the value.  

Would be nice to see any error about missing items. For example if a kind is misspelled or apiVersion is old or just wrong. 

It's easier to debug when I made the composition than when I'm debugging a team member. It's just a lot of trial and error in a sea of yaml.

**Comment by haarchri** [comment]
we had today an silent issue with cluster.eks.aws.crossplane.io resource
no isse, no report, no debug 

```
            resourcesVpcConfig:
              - securityGroupIdsSelector:
              + securityGroupIdSelector:
                matchControllerRef: true
```
