### ISSUE TITLE
Support float64 values in Math/multiply Transform Type in Compositions

### ISSUE THREAD

**Issue by ccremer** [crossplane/crossplane#2931]
It would be helpful if the math transformation is actually a float64-style numeric value and not just a plain integer.

Use case:
We have the idea to imply a memory-to-CPU ratio when a User provisions a claim with a scale-model.
For example, we provide a parameter `spec.parameters.memoryLimitGB` and based from that value, we can automatically calculate the `spec.template.spec.containers[*].resources.request.memory` in a Deployment/Statefulset to be a third of that value (e.g. factor = `0.3`). And also calculate the CPU limit, e.g. "2GB memory limit equals to 0.75 CPU limit" (factor=`0.375`)

### What problem are you facing?

The following validation pretty much sums it up:

`The Composition is invalid: spec.resources.patches.transforms.math.multiply: Invalid value: "number": spec.resources.patches.transforms.math.multiply in body must be of type integer: "number"`

This error effectively means I cannot use a multiplication factor with decimals and cannot multiply values with `1.5` for example, or divide by 2 with factor of `0.5`

A patch like this doesn't work:
```yaml
        - fromFieldPath: spec.parameters.memoryLimitGB
          toFieldPath: spec.forProvider.values.resources.requests.memory
          transforms:
            - type: math
              math:
                multiply: 0.3
            - type: string
              string:
                fmt: "%.2fGi"
```

### How could Crossplane help solve your problem?

* Change the `math.multiply` type from `Integer` to `Float64` (if that's possible without breaking changes)
* Add another property with another name and deprecate `multiply` (e.g. `math.multiplication` or `math.multiplyBy`, name debatable)
* Alternatively, even going further: Support the resource Unit, e.g. a string input value like `500Mi` with a factor of `3.5` automatically results in `1750Mi` or `1.708984Gi`.
