### ISSUE TITLE
Support a 'json' transformation type to render connection secrets in proper json

### ISSUE THREAD

**Issue by AaronME** [crossplane/crossplane#2943]
### What problem are you facing?
I am working with a terrajet provider based on [hashicorp/vault](https://registry.terraform.io/providers/hashicorp/vault/latest/docs). The `vault_generic_secret` resource requires that secret data be submitted as a json-formatted string.

Currently, emitting a json-formatted string requires manually constructing proper json using the string "fmt" transform, which could quickly become unreadable and unworkable.

### How could Crossplane help solve your problem?
Implement a 'json' transform which could be used to wrap any string in proper json formatting.

For example:
provider-gcp currently offers a connection secret for a GKE cluster which contains `clusterCA`, `endpoint`, and `kubeconfig.`

It is easy to render `endpoint` in json with:
```
transforms:
- type: string
  string:
    type: Format
    fmt: '{"clusterCA":"%s"}'
```
 
However, both `clsuterCA` and `kubeconfig` are multi-line strings and would not survive this simple form of json encoding.

Another example is a serviceaccount from the same provider:

The privateKey for a ServiceAccount is already a json. When passed to a resource expecting json input, the fields are interpreted as individual fields instead of treating the full json as a string value.

Crossplane could provider a format which would accept any of these fields and allow them to be encoded into safe json that would look like the following:

```yaml
transforms:
- type: string
   string:
    type: Encode
    encode: JSON
  ```

**Comment by YashasviChaurasia** [comment]
@Aaron, I would like to work on this issue.
Kindly assign me if I have your approval.
Thank you

**Comment by mcanevet** [comment]
@YashasviChaurasia are you still interested in working on this? I'd really like to have this feature.

**Comment by rammelmueller** [comment]
Is this functionality supported somehow by now?

**Comment by bobh66** [comment]
https://docs.crossplane.io/latest/guides/function-patch-and-transform/#string-convert

**Comment by rammelmueller** [comment]
Thanks for the link! Is this supposed to also with for `connectionDetails`, like this example:
```
    connectionDetails:
      - type: FromConnectionSecretKey
        fromConnectionSecretKey: attribute.client_secret
        name: some-secret
        transforms:
          - type: string
            string:
              type: Convert
              fmt: "ToJson"
```
If so.. somehow I can't make it work.
