### ISSUE TITLE
Automatic update of composition revision is not working

### ISSUE THREAD

**Issue by eloo** [crossplane/crossplane#2954]
### What happened?
Working with composition revisions i try to understand and test the functionality and possibilities we have with the revisions and how we can update our claims. 

So i have created a simple composition and also two claims. One claim with manual update and the second one with automatic update.
Then i have updated the composition to get a new revision. But both claims stick with the old revision. 

So the automatic revision policy seems not to work.

Manual revision update for the "manual" claim seems to work as expected.

### How can we reproduce it?
My claims
```
apiVersion: test.cloud.com/v1
kind: TestRedisInstance
metadata:
  name: test-redis-instance-auto
spec:
  parameters:
    redisClusterName: test-redis-instance-auto
    region: eu-central-1
    plan: micro
    deletionPolicy: Delete
    cacheSubnetGroupName: test-elysium-test-cloud-com
    tags:
      - key: another-tag
        value: with-value
  compositionUpdatePolicy: Automatic
  writeConnectionSecretToRef:
    name: redis-instance-jowe-access-auto
---
apiVersion: test.cloud.com/v1
kind: TestRedisInstance
metadata:
  name: test-redis-instance-manual
spec:
  parameters:
    redisClusterName: test-redis-instance-manual
    region: eu-central-1
    plan: micro
    deletionPolicy: Delete
    cacheSubnetGroupName: test-elysium-test-cloud-com
    tags:
      - key: another-tag
        value: with-value
  compositionUpdatePolicy: Manual
  compositionRevisionRef:
    name: test-redis-composition-jnfc5
  writeConnectionSecretToRef:
    name: redis-instance-jowe-access-manual
```

Output of the claims: (revision is fetched like this: `REVISION:.spec.compositionRevisionRef.name`)
```
NAMESPACE   NAME                         READY   REVISION
default     test-redis-instance-auto     True    test-redis-composition-jnfc5
default     test-redis-instance-manual   True    test-redis-composition-jnfc5
```

Output for revisions:
```
test-redis-composition-d5px6           2          True      9m35s
test-redis-composition-jnfc5           1          False     165m
```

In the logs i see a lot of 
```
the object has been modified; please apply your changes to the latest version and try again
```
for the test-redis-instance-auto

### What environment did it happen in?
Crossplane version: v1.6.3
Provider-AWS version: v0.241

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
