### ISSUE TITLE
How to associate an EIP to an EC2 instance using crossplane

### ISSUE THREAD

**Issue by sharigitpersonal** [crossplane/crossplane#2978]
### What happened?

I am trying to create an EC2 instance and an EIP and associate the same to the EC2 created. 
This is possible in terraform using the EIP association modules. Is there anything similar in crossplane.

I have created an ec2 and eip separately . Manually attached the EIP to the EC2 for the moment. 
Unable to identify the right entries in the yaml to associate the EIP to the EC2. 

### How can we reproduce it?

I see the CRD has a statement that ask user to associate the EIP to the network interface like this. 
```
networkInterfaces:
                    items:
                      description: InstanceNetworkInterface describes a network interface.
                      properties:
                        association:
                          description: The association information for an Elastic
                            IPv4 associated with the network interface.
                          properties:
                            ipOwnerId:
                              description: The ID of the owner of the Elastic IP address.
                              type: string
                            publicDnsName:
                              description: The public DNS name.
                              type: string
                            publicIp:
                              description: The public IP address or Elastic IP address
                                bound to the network interface.
                              type: string
                          type: object
```
How to associate the EIP to an EC2 like we do it in terraform ?  If anyone is aware of it , please share the knowledge. 

### What environment did it happen in?
Crossplane version: 
crossplane/crossplane:v1.6.2
aws-provider - v0.25.0
