### ISSUE TITLE
Track usage of Secret StoreConfig and Prevent deletion while it is in use

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#2998]
### What problem are you facing?

With External Secret Stores, [a new API](https://github.com/crossplane/crossplane/blob/master/design/design-doc-external-secret-stores.md#api) is proposed to write connection details to Secret Stores including Kubernetes. This API introduces a new CRD, namely `StoreConfig`. 

To write/publish a connection secret, a resource (managed/composite/claim) needs to define:

```yaml
spec:
  publishConnectionDetailsTo:
    name: my-connection-secret
    configRef:
      name: default
```

which requires a `StoreConfig` resource exists with the referenced name.

```yaml
apiVersion: secrets.crossplane.io/v1alpha1
kind: StoreConfig
metadata:
  name: default
spec:
  type: Kubernetes
  defaultScope: crossplane-system
```

If a `StoreConfig` resource is deleted while there are connection secret owner resources that depend on it, reconciliation will start failing as the controller no longer knows how to connect to the Secret Store. This will prevent actions including deletion of the resource. 

This problem is very similar to [this resolved issue](https://github.com/crossplane/crossplane/issues/1737) with the `ProviderConfig` resource. 

### How could Crossplane help solve your problem?

We need to Track usage of `StoreConfig` resources and prevent deletion until no resource depends on the configuration.  This problem is very similar to [this resolved issue](https://github.com/crossplane/crossplane/issues/1737) with the `ProviderConfig` resource, hence I am guessing we can implement a similar solution.
