### ISSUE TITLE
ComposeResources behaviour is inconsistent when the spec of Composed Resource is not fully specified

### ISSUE THREAD

**Issue by ytsarev** [crossplane/crossplane#3009]
### What happened?

Incosistency can be demonstrated by 3 different cases

1. When we have Composed Resource as part of the Composition without specification of full spec like

```
    - name: iam-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
      patches:
        - fromFieldPath: spec.parameters.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "kudos-%s-credstash"
        - fromFieldPath: spec.parameters.name
          toFieldPath: spec.forProvider.name
          transforms:
            - type: string
              string:
                fmt: "kudos-%s-credstash"
```

the Composition will fail to be created with
```
cannot apply composed resource: cannot create object: Policy.iam.aws.crossplane.io "kudos-xsautest-credstash" is invalid: spec.forProvider.document: Required value
```

2. In the meantime, if we remove patching of `metadata.name` like

```
    - name: iam-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
      patches:
#        - fromFieldPath: spec.parameters.name
#         toFieldPath: metadata.name
#        transforms:
#           - type: string
#             string:
 #               fmt: "kudos-%s-credstash"
        - fromFieldPath: spec.parameters.name
          toFieldPath: spec.forProvider.name
          transforms:
            - type: string
              string:
                fmt: "kudos-%s-credstash"
```

we wiil observe the same error for a while in event stream

```
17s         Warning   ComposeResources               xtenant/xsautest-9nq82                                                cannot render composed resource from resource template at index 1: cannot use dry-run create to name composed resource: Policy.iam.aws.crossplane.io "xsautest-9nq82-zsfvt" is invalid: spec.forProvider.document: Required value
```

but the creation of the composed resources will eventually succeed

```
k get managed
Warning: Please use v1beta1 version of SNS group.
NAME                                     READY   SYNCED   EXTERNAL-NAME
key.kms.aws.crossplane.io/kms-xsautest   True    True     6dd6a6fc-3600-46ce-8080-abef6909be7e

NAME                                                ARN                                                         READY   SYNCED   AGE
policy.iam.aws.crossplane.io/xsautest-9nq82-dpwpd   arn:aws:iam::609897127049:policy/kudos-xsautest-credstash   True    True     34s
```

3. In addition to that we can get `metadata.name` patching back and in addition provide default dummy spec in `base` like

```
    - name: iam-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
        spec:
          forProvider:
            document: to-be-patched ## Dummy value as a workaround
      patches:
       - fromFieldPath: spec.parameters.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "kudos-%s-credstash"
```

In this case, it will work smoothly without any errors.

### How can we reproduce it?

All fill for reproduction can be found at https://gist.github.com/ytsarev/77f57f59ec6360e80c782f39cf95254a

### What environment did it happen in?
Crossplane version: 

```
NAME                	NAMESPACE     	REVISION	UPDATED                             	STATUS  	CHART                          	APP VERSION
universal-crossplane	upbound-system	1       	2022-03-24 09:05:44.583466 +0100 CET	deployed	universal-crossplane-1.6.3-up.1	1.6.3-up.1
```
