### ISSUE TITLE
Managed resource stuck / How to force reconcile

### ISSUE THREAD

**Issue by eloo** [crossplane/crossplane#3010]
### What happened?
I have created a claim which is going to spin up a role, a policy and a rolepolicyattachment (provider-aws). 
While not all resources and their dependencies were in ready state the rolepolicyattachment ( rpa ) was set to not ready with the following error:

```
'cannot resolve references: mg.Spec.ForProvider.PolicyARN: referenced
      field was empty (referenced resource may not yet be ready)'
```

Totally fine with that. 
But after a few minutes all role and the policy has been changed to ready. 
But the rpa is still stuck in the same state and the `lastTransitionTime` does not change. 

So how can this be fixed? AFAIK there is no "reconcile" command or so which can be triggered.

### How can we reproduce it?
- Create these three resources
- Maybe enforce the role or policy to be buggy and be fixed later
- See the rpa being not ready
- Wait
- Fix the role and policy
- See rpa stuck in not ready

### What environment did it happen in?
Crossplane version: 
crossplane/crossplane:v1.6.3
crossplane/provider-aws-controller:v0.24.1

### Kubectl output

```
spec:
  deletionPolicy: Delete
  forProvider:
    policyArnRef:
      name: gomock-server-pre-us-east-1-s3-qfhtg
    roleName: gomock-server-pre-us-east-1-role
  providerConfigRef:
    name: aws-provider-config
status:
  atProvider:
    attachedPolicyArn: ""
  conditions:
  - lastTransitionTime: "2022-03-28T16:07:53Z"
    message: 'cannot resolve references: mg.Spec.ForProvider.PolicyARN: referenced
      field was empty (referenced resource may not yet be ready)'
    reason: ReconcileError
    status: "False"
    type: Synced
```

```
NAME                                       ARN                                                                          READY   SYNCED   AGE
gomock-server-pre-us-east-1-s3-qfhtg   arn:aws:iam::....:policy/gomock-server-pre-us-east-1-s3-policy   True    True     39m
```

So maybe the question here is how can i enforce a new reconcile?
It seems that the pull interval is here not kicking in. So its maybe related to the sync interval. But this is often a bit too long. 

E.g. in FluxCD there is a cli which can trigger a reconcile. Maybe such a thing would be also useful here?

**Comment by Smana** [comment]
Seems also be related to this issue https://github.com/crossplane/crossplane/issues/2072

**Comment by Smana** [comment]
Following a conversation on Slack we applied the following changes that allowed us to fix the issue:
* upgraded to the provider-aws version v0.26.1
* changed the providerconfig as follows:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::...
  name: aws-config
spec:
  args:
  - --max-reconcile-rate=100
  podSecurityContext:
    fsGroup: 2000
```
