### ISSUE TITLE
Problem deploying composition revisions in configuration packages

### ISSUE THREAD

**Issue by wilhelmi** [crossplane/crossplane#3015]
Hit stumbling block with composition revision and configuration packages. Revisions are enabled in Crossplane 1.7.0, when I make changes to the composition locally and apply them they work as expected. I get multiple revisions, and I can point the claim to the desired revision.

Next step was to package up the changes. Created 2 packages each representing the stages I ran through above. When I apply the first package, I can create the claim and all works as expected.

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
 name: test-package-3
 namespace: crossplane-system
spec:
 package: gcr.io/....crossplane/demo:0.0.3
```
However when I try to install the second configuration package the new composition revision never gets installed

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
 name: test-package-4
 namespace: crossplane-system
spec:
 package: gcr.io/..../crossplane/demo:0.0.4
```

This seems to be the relevant error event:

cannot establish control of object: xtests.demo.com is already controlled by ConfigurationRevision test-package-3-b2857c468e58 (UID 1b6214f9-e997-4708-8025-1f028847ead4)
