### ISSUE TITLE
Support for field transforms on fromFieldPath that are part of Combine patch

### ISSUE THREAD

**Issue by samidbb** [crossplane/crossplane#3025]
### What problem are you facing?
We want to avoid using annotations and status fields as temporary fields in our compositions. 

Right now we are forced to do the followings on our composition that defines Topic in our Custom Confluent provider:
```
    - fromFieldPath: spec.parameters.availability
      policy:
        fromFieldPath: Required
      toFieldPath: metadata.annotations[crossplane.io/availability]
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/availability]
      toFieldPath: "status.availability"
      policy:
        fromFieldPath: Required
      transforms:
      - type: map
        map:
          "public": "pub."
          "private": ""
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: status.availability
          - fromFieldPath: spec.claimRef.namespace
          - fromFieldPath: spec.parameters.name
        strategy: string
        string:
          fmt: "%s%s.%s"
      toFieldPath: spec.forProvider.manifest.spec.forProvider.topic.name 
```
Input example: 
availability: public
name: mytopic

Resulting topic name:
pub.mynamespace.mytopic

Storing temporary variables in labels, annotations and status field for doing operations can impose security problems when we start reading field values from secrets. 
### How could Crossplane help solve your problem?

```
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: status.availability
          transforms:
          - type: map
            map:
              "public": "pub."
              "private": "" 
          - fromFieldPath: spec.claimRef.namespace
          - fromFieldPath: spec.parameters.name
        strategy: string
        string:
          fmt: "%s%s.%s"
      toFieldPath: spec.forProvider.manifest.spec.forProvider.topic.name 
```

This solution will make the process of authoring less complicated for normal users who are going to adopt Crossplane in our organisation

**Comment by Speeddymon** [comment]
Would like this to be reopened.

Also noticed that the proposed solution has a spacing problem:

```
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: status.availability
            transforms: # This section needed 2 more spaces
            - type: map
              map:
                "public": "pub."
                "private": "" # End This section needed 2 more spaces
          - fromFieldPath: spec.claimRef.namespace
          - fromFieldPath: spec.parameters.name
        strategy: string
        string:
          fmt: "%s%s.%s"
      toFieldPath: spec.forProvider.manifest.spec.forProvider.topic.name 
```

**Comment by ytsarev** [comment]
Totally valid request, reopening :)

**Comment by conclusionlogic** [comment]
Had a similar use case just now. Wanted to patch a Name tag value to a Subnet MR:
```
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.tags[4].value
          combine:
            variables:
              - fromFieldPath: spec.id
              - fromFieldPath: spec.id
                transforms:
                  - type: map
                    map:
                      development-eu: eu-west-2
                      staging-eu: eu-west-2
                      production-eu: eu-west-1
            strategy: string
            string:
              fmt: "%s-private-%sa"
```
I thought/hoped it would be possible to patch the value and get `development-eu-private-eu-west-2a` but instead I got `development-eu-private-development-eua`.
In my case, I can of course work around this limitation by simply pivoting to explicit region variable on the CompositeResource but would have liked to abstract that level of detail away from "config"...
