### ISSUE TITLE
Support for replace string transform

### ISSUE THREAD

**Issue by samidbb** [crossplane/crossplane#3026]
### What problem are you facing?
We are always stumpling into the challenge of the limitation of not being able to do a simple string replace without the need for using annotations and status field temporarily  

The challenge with the current approach is illustrated in this issue: https://github.com/crossplane/crossplane/issues/3025
### How could Crossplane help solve your problem?

An example of how it can implemented:
```
  - type: CombineFromComposite
    combine:
      variables:
        - fromFieldPath: status.availability
        - fromFieldPath: spec.claimRef.namespace
        - fromFieldPath: spec.parameters.name
      strategy: string
      string:
        fmt: "%s.%s.%s"
      - type: string
        string:
          type: Replace
          replace: 'public'
          value: 'pub'
    toFieldPath: spec.forProvider.topic.name 
```
input string: public.mynamespace.mytopic
output: pub.mynamespace.mytopic
