### ISSUE TITLE
Regular expression group capture string transformation

### ISSUE THREAD

**Issue by jessesuen** [crossplane/crossplane#3028]
### What problem are you facing?

Crossplane currently supports a limited number of string transformations:
* fmt
* trim
* convert

However, I feel these are quite limiting. Crossplane could additionally support a regular expression syntax along with group capture, which would be much more flexible. It would even obsolete the need for TrimPrefix/TrimSuffix.

### How could Crossplane help solve your problem?

Imagine we had something like this:

```yaml
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.aws.accountNumber
          transforms:
            - type: string
              string:
                regexp: "arn:aws:iam::(\d+):.*"
                group: 1
```

So if the the ARN was: `arn:aws:iam::12345678910:role/role-name` it would extract `12345678910` from it. The account number could then be fed into other resources like `assumeRolePolicyDocument` of a Role.

**Comment by negz** [comment]
This sounds reasonable to me - I think it would be a good compliment to the existing trim transforms, which are still nice for simple cases due to their easier API.

**Comment by kiote** [comment]
Hello, I'd like to work on this issue.

**Comment by kiote** [comment]
Hi @jessesuen, do you have any ideas on how it should work with more complex cases, than in your example?

Atm I see that I can start with something very simple like regex returns one match, this match goes to the resulting string unchanged.

In this case, we don't even need `group`, and can keep this type of interface:

```
transforms:
 - type: string
   string:
     regexp: "arn:aws:iam::(\d+):.*"
```

or even 

```
transforms:
 - type: regexp
   regexp: "arn:aws:iam::(\d+):.*"
```
I personally like the second option more, because then we are not coupled with string interface and can add new options to regex type if needed in the future.  

So if you have no objections, I'll try to implement the second option.
