### ISSUE TITLE
Replacing claims ignores old composite resource

### ISSUE THREAD

**Issue by smileisak** [crossplane/crossplane#3049]
### What happened?

When replacing a claim using `kubectl replace` strategy (PUT) a new underlying composite resource will be created which is normal, but the old one still available and should be deleted.

The expected behavior is to have only one composite resource from the replace claim.

### How can we reproduce it?

To reproduce this issue, you can follow these steps:

1. Install crossplane in a kind cluster.
1. Install [provider-kubernetes](https://github.com/crossplane-contrib/provider-kubernetes).
2. Create a dummy xrd:
    ```yaml
      apiVersion: apiextensions.crossplane.io/v1
      kind: CompositeResourceDefinition
      metadata:
        name: xdummies.example.com
      spec:
        defaultCompositionRef:
          name: dymmy
        group: example.com
        names:
          kind: XDummy
          plural: xdummies
        claimNames:
          kind: Dummy
          plural: dummies
        versions:
          - name: v1alpha1
            served: true
            referenceable: true
            schema:
              openAPIV3Schema:
                type: object
                properties:
                  spec:
                    type: object
                  status:
                    type: object
    ```
1. Create the default providerconfig for the provider-kubernetes
1. Create the dummy composition:
    ```yaml
        apiVersion: apiextensions.crossplane.io/v1
        kind: Composition
        metadata:
          name: dummy
          labels:
            purpose: example
        spec:
          compositeTypeRef:
            apiVersion: example.com/v1alpha1
            kind: XDummy
          patchSets:
            - name: metadata
              patches:
                - fromFieldPath: metadata.labels
          resources:
            - name: pod
              base:
                apiVersion: kubernetes.crossplane.io/v1alpha1
                kind: Object
                spec:
                  forProvider:
                    manifest:
                      apiVersion: v1
                      kind: Pod
                      metadata:
                        name: example
                        namespace: default
                      spec:
                        containers:
                        - image: nginx:latest
                          name: example
                          ports:
                          - containerPort: 80
                            name: http
                            protocol: TCP
       
                  providerConfigRef:
                    name: default
              patches:
                - fromFieldPath: metadata.name
                  toFieldPath: metadata.name
    ```
1. Create a dummy resource:
    ```yaml
    apiVersion: example.com/v1alpha1
    kind: Dummy
    metadata:
       name: example1
       namespace: default
    spec: {}
    ```
   ```bash
    kubectl apply -f dummy.yaml
   ```
1. Replace the same dummy resource:
   ```bash
    kubectl replace -f dummy.yaml
   ```

### What environment did it happen in?
Crossplane version: v1.6.4
* Cloud provider or hardware configuration: GKE
* Kubernetes version 
    ```bash
    Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
    ```
* Kubernetes distribution: GKE
