### ISSUE TITLE
Enhance `multiply` of transform `math` type with support of `float64`

### ISSUE THREAD

**Issue by ytsarev** [crossplane/crossplane#3059]
### What problem are you facing?

Currently  `multiply` of transform `math` type is limited to work with `int` and `int64` only.

If we try the constructs like

```
    - fromFieldPath: "status.maxConnPerSku"
      toFieldPath: "spec.forProvider.criteria[0].threshold"
      transforms:
      - type: convert
        convert:
          toType: float64
      - type: math
        math:
          multiply: 90
```

we will encounter patching failure of
```
 "reason": "ComposeResources", "message": "cannot render composed resource from resource template at index 3: cannot apply the patch at index 4: transform at index 1 returned error: math transform could not resolve: input is required to be a number for math transformer"}
```

In other words, `multiply` does not work with decimals on both sides of the equation: both inputs and multiplication factors are required to be integer only. 

It is seriously limiting in cases we need to deal with decimal values coming from source fields and/or multiply by a non-integer value like e.g. `1.05` or `0.9`

### How could Crossplane help solve your problem?

Enable `multiply` to support `float64`

Related code: https://github.com/crossplane/crossplane/blob/b49ddde2627ac732c53cae4a683024253cfe81b0/apis/apiextensions/v1/composition_transforms.go#L121-L137
