### ISSUE TITLE
Proposal: Ability to add spec parameters  to composition/claim connection secret

### ISSUE THREAD

**Issue by kertzi** [crossplane/crossplane#3070]
It would be nice to have possibility to pass composition/claim spec parameter value to composite's connection secret. 

Example use case:
We have defined parameter in XRD which value we want to end up to claim's connection secret. Because it's useful for infra "consumer" to have all needed details in one place.

Currently we do this with little hack where we just pick one resource in composition and first patch parameter value to resource's metadata and get it from there in connectionDetails:

```yaml
resources:
  - name: cassandra-user
    base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: User
      metadata:
        labels:
          user: user
      spec:
        forProvider:
          path: /
    patches:
    - type: FromCompositeFieldPath <--- here we patch param value keyspaceName to metadata
      fromFieldPath: spec.keyspaceName
      toFieldPath: metadata.annotations[cassandra-keyspace-name]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.aws.region
      toFieldPath: metadata.annotations[cassandra-endpoint]
      transforms:
      - type: string
        string:
          fmt: 'cassandra.%s.amazonaws.com'
    connectionDetails:
    - type: FromFieldPath <--- and here we get it from resource details to connection secret
      name: cassandra-keyspace-name
      fromFieldPath: metadata.annotations[cassandra-keyspace-name]
    - type: FromFieldPath
      name: cassandra-endpoint
      fromFieldPath: metadata.annotations[cassandra-endpoint]
    - type: FromValue
      name: cassandra-port
      value: '1234'
```

One way to achieve this could be add some "dummy resource" which can do things like this 
or 
Add field in to composition spec directly which tells crossplane which values are added directly to connectionDetails

Thanks!

### Resources

Links to the API docs and code that describe this particular `connectionDetails` section and it's current abilities.

* API docs: https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.12.1#spec-resources-connectionDetails
* Code: https://github.com/crossplane/crossplane/blob/v1.12.1/apis/apiextensions/v1/composition_common.go#L188
