### ISSUE TITLE
Add lifecycle configuration to ControllerConfig

### ISSUE THREAD

**Issue by bobh66** [crossplane/crossplane#3084]
### What problem are you facing?
provider-terraform needs to be able to gracefully shutdown any running terraform commands when before the pod is terminated.  This is needed to avoid locks being left behind on Lease objects in the kubernetes back end.

One way to do this would be to use the pod lifecycle configruation to define a preStop hook that sends a HUP signal to all running terraform processes so they can shut down cleanly before the pod exits.

```
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh","-c","while killall -HUP terraform; do sleep 1; done"]
```

### How could Crossplane help solve your problem?

Add support for the lifecycle configuration to the ControllerConfig definition so those attributes can be copied into the pod definition at runtime.

See https://github.com/crossplane-contrib/provider-terraform/issues/46
