### ISSUE TITLE
Connection Details FromFieldPath type not working

### ISSUE THREAD

**Issue by garreeoke** [crossplane/crossplane#3086]
### What happened?
Trying to set connection details from a composed resource's status and put it in to the connection secret.  However, no values are written.

### How can we reproduce it?

- Find a valid status field in a managed resource. In my case it was status.arn. 
- Use that resource in a composition and attempt to put that data in the connection secret

**XRD**
```
connectionSecretKeys:
   - arn
```

**Composition**
```
connectionDetails:
        - type: FromFieldPath
          name: arn
          fromFieldPath: status.atProvider.arn
```

- Secrets are created for the compostions, but no values and no errors on the resources.

### What environment did it happen in?
Crossplane version:  1.7
Kubernetes: v1.23.4
Kind cluster
