### ISSUE TITLE
Proposal: Ability to use combine in ConnectionDetails

### ISSUE THREAD

**Issue by adrienzieba** [crossplane/crossplane#3096]
### What problem are you facing?
In composition, it can happen that connectionDetails give you information in a format that is not the one expected. For example, when we create a AWS Access Key, we get the username (Access ID) and the password (Access secret) as 2 key in the secrets.
if we want to create a secret containing only the aws-creds (combining id+secret) we need a manual step taking this information to create following format 

```
[default]
aws_access_key_id=XXX
aws_secret_access_key=XXX
```

### How could Crossplane help solve your problem?
It would be useful if we can use combine in ConnectionDetails. As a bonus, we could get information from other kubernetes resources if required (similar to what has been done in the [kubernetes-provider](https://github.com/crossplane-contrib/provider-kubernetes/blob/main/examples/object/references/patches-from-multiple-resources.yaml)). Something like :

```
connectionDetails:
- name: aws-creds 
  combine:
    variables:
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
    strategy: string
    string:
      fmt: | 
        [default]
        aws_access_key_id=%s
        aws_secret_access_key=%s
```

It could be related to https://github.com/crossplane/crossplane/issues/2772.
