### ISSUE TITLE
[1.6.6] upgrade configuration package - cannot resolve package dependencies: missing dependencies

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#3115]
### What happened?
durin upgrade package(in `Configuration`) from v1.65.0 to version v1.67.0 composition updates we get the following error in configurationrevision:
`cannot resolve package dependencies: missing dependencies`

```yaml
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-sop
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  package: 12345678910.dkr.ecr.eu-central-1.amazonaws.com/crossplane/sop:v1.67.0
```

```
Spec:
  Desired State:                  Active
  Ignore Crossplane Constraints:  true
  Image:                          12345678910.dkr.ecr.eu-central-1.amazonaws.com/crossplane/sop:v1.67.0
  Package Pull Policy:            IfNotPresent
  Revision:                       47
  Skip Dependency Resolution:     false
Status:
  Conditions:
    Last Transition Time:  2022-05-27T10:56:41Z
    Reason:                UnknownPackageRevisionHealth
    Status:                Unknown
    Type:                  Healthy
  Controller Ref:
    Name:                  
  Found Dependencies:      4
  Installed Dependencies:  3
Events:
  Type     Reason               Age                    From                                              Message
  ----     ------               ----                   ----                                              -------
  Warning  SyncPackage          17m                    packages/configurationrevision.pkg.crossplane.io  cannot update annotations for package revision: Operation cannot be fulfilled on configurationrevisions.pkg.crossplane.io "crossplane-sop-0b1ca882a1d3": the object has been modified; please apply your changes to the latest version and try again
  Warning  ResolveDependencies  8m25s (x14 over 17m)   packages/configurationrevision.pkg.crossplane.io  cannot resolve package dependencies: missing dependencies: [crossplane/provider-aws crossplane/provider-kubernetes]
  Warning  ResolveDependencies  6m35s (x2 over 6m43s)  packages/configurationrevision.pkg.crossplane.io  cannot resolve package dependencies: missing dependencies: [crossplane/provider-aws crossplane/provider-kubernetes]
```

in pkgrev we can see that all providers installed and active:

```
NAME                                                                             HEALTHY   REVISION   IMAGE                                                         STATE      DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/crossplane-provider-aws-f6a4a9bdba04          True      1          crossplane/provider-aws:v0.23.0                               Inactive                               126d
providerrevision.pkg.crossplane.io/crossplane-provider-aws-f78664a342f1          True      2          crossplane/provider-aws:v0.24.1                               Active                                 93d
providerrevision.pkg.crossplane.io/crossplane-provider-helm-f6c5ce0da0dd         True      1          crossplane/provider-helm:v0.9.0                               Active                                 149d
providerrevision.pkg.crossplane.io/crossplane-provider-kubernetes-acc90e12eb7b   True      3          crossplane/provider-kubernetes:v0.3.0-rc.15.g82b335c-main     Active                                 84d
providerrevision.pkg.crossplane.io/crossplane-provider-kubernetes-c2f4051377f9   True      2          crossplane/provider-kubernetes:v0.2.0-rc.0.10.gc79df6f-main   Inactive                               142d
providerrevision.pkg.crossplane.io/crossplane-provider-zpa-a6023f4d8e8e          True      2          crossplane/provider-zpa:v0.2.0                                Active                                 115d
providerrevision.pkg.crossplane.io/crossplane-provider-zpa-bb9432e119a0          True      1          crossplane/provider-zpa:v0.1.0                                Inactive                               149d

NAME                                                                  HEALTHY   REVISION   IMAGE                                                                        STATE      DEP-FOUND   DEP-INSTALLED   AGE
configurationrevision.pkg.crossplane.io/crossplane-sop-0b1ca882a1d3   Unknown   47         12345678910.dkr.ecr.eu-central-1.amazonaws.com/crossplane/sop:v1.67.0   Active     4           3               15m
configurationrevision.pkg.crossplane.io/crossplane-sop-ae0330fa1715   True      46         12345678910.dkr.ecr.eu-central-1.amazonaws.com/crossplane/sop:v1.65.0   Inactive   4                           16d

```

configuration.yaml
```
---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: sop
spec:
  crossplane:
    version: ">=v1.6"
  dependsOn:
  - provider: crossplane/provider-helm
    version: "v0.9.0"
  - provider: crossplane/provider-aws
    version: "v0.24.1"
  - provider: crossplane/provider-kubernetes
    version: "v0.3.0-rc.15.g82b335c-main"
  - provider: crossplane/provider-zpa
    version: "v0.2.0"

```

for now we changed to 

```yaml
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-sop
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  skipDependencyResolution: true ## we add skipDependencyResolution to get rid of the issue 🗡️  
  package: 12345678910.dkr.ecr.eu-central-1.amazonaws.com/crossplane/sop:v1.67.0
```

### What environment did it happen in?
Crossplane version: 1.6.6
