### ISSUE TITLE
Getting error with maxReconcileRate flag not found

### ISSUE THREAD

**Issue by ChrisJBurns** [crossplane/crossplane#3117]
### What happened?
Upgraded my Crossplane version to use the `maxReconcileRate` but it turns out, the flag isn't found when the init container starts.

### How can we reproduce it?
Install Crossplane with Flux like so and watch it blow (at least in my case)
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: crossplane
    app.kubernetes.io/part-of: crossplane
  name: crossplane
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: crossplane
  namespace: crossplane
spec:
  interval: 1m
  url: https://charts.crossplane.io/master/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane
spec:
  chart:
    spec:
      chart: crossplane
      version: 1.9.0-rc.0.9.g243f1f47
      sourceRef:
        kind: HelmRepository
        name: crossplane
  interval: 1m
  values:
    maxReconcileRate: 100
    resourcesCrossplane:
      limits:
        cpu: 1000m
```

![image](https://user-images.githubusercontent.com/29541485/171229060-b50d8c5e-b8e2-475e-a26e-7705db89dfc7.png)

### What environment did it happen in?
Crossplane version: 1.9.0-rc.0.9.g243f1f47
EKS
