### ISSUE TITLE
Allow deterministic Composite Resource Names

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#3120]
### What problem are you facing?

Crossplane composite resource names are generated by the kube API server through setting `generatedName` to `<claim-name>-`. The server will append a random string as suffix to make the object's name unique:

https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/claim/configurator.go#L134

```go
        if !meta.WasCreated(cp) {
		// The API server returns an available name derived from
		// generateName when we perform a dry-run create. This name is
		// likely (but not guaranteed) to be available when we create
		// the composite resource. If the API server generates a name
		// that is unavailable it will return a 500 ServerTimeout error.
		cp.SetGenerateName(fmt.Sprintf("%s-", cm.GetName()))
		return errors.Wrap(c.client.Create(ctx, cp, client.DryRunAll), errName)
	}
```

Because of this randomness, creating the same claim multiple times will result in different composite names which makes migration tasks and traceability very difficult.

### How could Crossplane help solve your problem?

Crossplane should offer a second, deterministic name generator.

For example, the generated name could be combination of the claim's name and namespace. The folks at [loft-sh/vcluster](https://github.com/loft-sh/vcluster) do something similar. There the name is a combination of name, namespace and cluster name:

```
<SERVICE_ACCOUNT>-x-<SERVICE_ACCOUNT_NAMESPACE>-x-<VIRTUAL_CLUSTER_NAME>
```

If the name is too long, it is trimmed:

```
<52 Characters of previous mentioned string>-<First 10 Characters SHA256 Hash of previous mentioned string>
```

To ensure backwards compatibility, the feature should be enabled via a feature flag, i.e. `--enable-deterministic-composite-names`.

**Comment by negz** [comment]
I have a vague recollection that we did used to include the claim namespace at some point, but moved away from that. Perhaps because the resulting XR names were being truncated?

**Comment by MisterMX** [comment]
Some more thoughts:

* It might be necessary to have different composite names for different XRDs. In this case the configuration would need to be part of the XRD spec instead of a CLI argument.
* Users might have the need for a more complex name generation per claim. This could be solved by providing the user a mini go template mechanism (similar to helm).

Proposal:

Add a new field `spec.composite.name.template` where the user can define a helm/go `text/template` that is executed by the reconciler:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: test.example.com
spec:
  composite:
    name:
      # produces something like 
      # default.test-a909b.test
      template: '{{ printf "%s.%s-%s.%s" .Claim.Namespace .Claim.Kind (sha1sum .Claim.GVK | abbrev 5) .Claim.Name  }}'
```
