### ISSUE TITLE
External resources: unable to delete when required field removed from CRD but not from the corresponding required list.

### ISSUE THREAD

**Issue by tbmetcalfe** [crossplane/crossplane#3121]
This is somewhere between a bug and a feature request. 

### What happened?
While developing an external resource, I accidentally updated its CompositeResourceDefinition where a field was deleted but was not removed from the required list. I made this update while a resource still existed. 

Before CRD:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfoo.cool.xr.example.com
spec:
  group: xfoo.cool.xr.example.com
  names:
    kind: XFoo
    plural: xfoos
  claimNames:
    kind: Foo
    plural: foos
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                importantField:
                  description: Super important field
                  type: string
                importantField2:
                  type: string
                  description: Super important field number 2
              required:
                - importantField
                - importantField2
```

After CRD:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfoo.cool.xr.example.com
spec:
  group: xfoo.cool.xr.example.com
  names:
    kind: XFoo
    plural: xfoos
  claimNames:
    kind: Foo
    plural: foos
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # note that importantField is missing
                importantField2:
                  type: string
                  description: Super important field number 2
              required:
                - importantField #but not missing here
                - importantField2
```

Since then this resource cannot be deleted, it simply hangs. When I try to do anything, it says that the field is required 

```Invalid value: "The edited file failed validation": ValidationError(XFoo.spec): missing required field "importantField" in com.example.xr.cool.v1alpha1.XFoo.spec)```

 When I add the field in question (by using `kubectl edit`), I get  the following error: 

```ValidationError(XFoo.spec): unknown field "importantField" in com.example.xr.cool.v1alpha1.XFoo.spec```

Please note that this resource does not currently manage any cloud resources, but it is designed to managed some AWS resources. It appears to be in a catch 22 state. 

I've tried deleting it, force deleting it, removing the finalizers, reverting the broken change, among other things! I suspect it may actually be impossible to delete this external resource. 

The only error that seems relevant in the logs:

```1.6541903362952018e+09	ERROR	crossplane.controller.defined/compositeresourcedefinition.apiextensions.crossplane.io	Reconciler error	{"reconciler group": "apiextensions.crossplane.io", "reconciler kind": "CompositeResourceDefinition", "name": "xfoo.cool.xr.example.com", "namespace": "", "error": "cannot apply rendered composite resource CustomResourceDefinition: existing object is not controlled by UID \"883f1a8b-6f7f-44ad-a81a-3b4ba8121860\""}```

### How can we reproduce it?
Create an external resource. Remove a required field but don't remove the fact that it's required. Try deleting that external resource and watch it hang. 

### What environment did it happen in?
Crossplane version: 1.8.1

* Cloud provider: AWS
* Kubernetes version: v1.21.9-eks-0d102a7
* AKS
