### ISSUE TITLE
`packagePullPolicy: IfNotPresent` ignore for Provider

### ISSUE THREAD

**Issue by antoninbas** [crossplane/crossplane#3157]
### What happened?
I am building a custom version of https://github.com/crossplane-contrib/provider-aws with `make build`. I didn't want to push the images to a registry, so I loaded them manually to my Kind Nodes (with `kind load docker-image <IMG>`) and set `packagePullPolicy` to `IfNotPresent`. However, installation of the provider failed, as crossplane was trying to pull the image from the registry anyway, and that image didn't exist. After pushing the image to the registry, installation succeeded.

### How can we reproduce it?
I used the following `Provider` and `ControllerConfig` resources:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: "antoninbas/provider-aws:latest"
  packagePullPolicy: IfNotPresent
  controllerConfigRef:
    name: provider-aws-controller-config
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws-controller-config
spec:
  image: antoninbas/provider-aws-controller
  imagePullPolicy: IfNotPresent
```

The images were both available on both Kind Nodes:
```
# crictl images | grep "antoninbas/provider-aws"
docker.io/antoninbas/provider-aws-controller   latest               a5f43b5b2ff65       156MB
docker.io/antoninbas/provider-aws              latest               cfe08d8974d8c       4.88MB
```

Logs from the crossplane Pod:
```text
.656376945386823e+09	INFO	crossplane.controller.packages/providerrevision.pkg.crossplane.io	Starting workers	{"reconciler group": "pkg.crossplane.io", "reconciler kind": "ProviderRevision", "worker count": 10}
1.6563769464898486e+09	DEBUG	crossplane	cannot unpack package	{"controller": "packages/provider.pkg.crossplane.io", "request": "/provider-aws", "uid": "56027e54-0268-4196-a805-596fe6569e8a", "version": "4337", "name": "provider-aws", "error": "failed to fetch package digest from remote: HEAD https://index.docker.io/v2/antoninbas/provider-aws/manifests/latest: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)"}
1.6563769464904702e+09	ERROR	crossplane.controller.packages/provider.pkg.crossplane.io	Reconciler error	{"reconciler group": "pkg.crossplane.io", "reconciler kind": "Provider", "name": "provider-aws", "namespace": "", "error": "cannot unpack package: failed to fetch package digest from remote: HEAD https://index.docker.io/v2/antoninbas/provider-aws/manifests/latest: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
1.6563769464905949e+09	DEBUG	crossplane.events	Warning	{"object": {"kind":"Provider","name":"provider-aws","uid":"56027e54-0268-4196-a805-596fe6569e8a","apiVersion":"pkg.crossplane.io/v1","resourceVersion":"4337"}, "reason": "UnpackPackage", "message": "cannot unpack package: failed to fetch package digest from remote: HEAD https://index.docker.io/v2/antoninbas/provider-aws/manifests/latest: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)"}
```

### What environment did it happen in?
Crossplane version: 1.8.1
```bash
helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --version 1.8.1
```

```
$ kind version
kind v0.12.0 go1.17.8 darwin/amd64
```
