### ISSUE TITLE
InjectedIdentity Credentials Source Not Working

### ISSUE THREAD

**Issue by WilliamCoffeyTri** [crossplane/crossplane#3160]
I've been trying for a while now to crop up Crossplane to manage AWS resources, but I've been running into a lot of problems with providing Crossplane authentication in a manner I'm comfortable with. I stumbled into the InjectedIdentity credentials source, which I'd hoped would be the solution I needed, but this does not appear to be working as expected. I can create a pod in the same namespace and with the same role ARN annotations and properly receive AWS access rights, but when Crossplane attempts to create a resource I receive

`failed to create the Instance resource: api error ValidationError: Request ARN is invalid`

I've been unable to find much documentation of this capability at all, so I am uncertain if a step in the configuration process is being missed or if there's some kind of bug/environmental issue.

I have:

- Set up an OIDC provider associated with my EKS cluster.
- Attached the appropriate role/policy.
- Created a Provider and a ProviderConfig, by the YAMLs added below.

Are there additional steps required for Crossplane to take advantage of the InjectedIdentity when interacting with AWS?

Thanks.

```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  assumeRoleWithWebIdentity:
    roleARN: "eks.amazonaws.com/role-arn=arn:aws:iam::[…]:role/[…]"
  credentials:
    source: InjectedIdentity
```
    
 ```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: ascp-config
  annotations:
    eks.amazonaws.com/role-arn: eks.amazonaws.com/role-arn=arn:aws:iam::[…]:role/[…]
spec:
  podSecurityContext:
    fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: "crossplane/provider-aws:v0.27.0"
  controllerConfigRef:
    name: ascp-config
```
