### ISSUE TITLE
Duplicate of secret when trying to publish from composition

### ISSUE THREAD

**Issue by Shadowraze228** [crossplane/crossplane#3172]
### What happened?

When crossplane deployed with `--enable-external-secret-stores` secrets are duplicated because `publishConnectionDetailsWithStoreConfigRef` field in Composition CRD defaulted and can't be disabled. 

So in result i have 2 secrets with same data in Vault:
- UID name secret(e.g. `crossplane-system/0348bc2b-3d7b-4cf0-8d61-5ce8d52d9703`)
- expected secret (e.g. `crossplane-system/path/to/secret`)

### How can we reproduce it?
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
spec:
  group: database.example.org
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  secretPath:
                    type: string
                  secretConfigName:
                    type: string
                required:
                  - secretPath
                  - secretConfigName
            required:
              - parameters
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstances
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  publishConnectionDetailsWithStoreConfigRef: 
    name: vault
  resources:
  - name: rdsinstance
    base:
      apiVersion: database.aws.crossplane.io/v1beta1
      kind: RDSInstance
      spec:
        forProvider:
          engine: postgres
          engineVersion: "13"
          dbInstanceClass: db.t3.medium
          region: eu-central-1
          dbSubnetGroupName: "REDACTED"
          masterUsername: vaultrdstest
          vpcSecurityGroupIds: ["REDACTED"]
          allocatedStorage: 20
          autoMinorVersionUpgrade: true
          backupRetentionPeriod: 0
          enableIAMDatabaseAuthentication: false
          enablePerformanceInsights: false
          skipFinalSnapshotBeforeDeletion: true
          multiAZ: false
          port: 5432
          preferredBackupWindow: 06:15-06:45
          preferredMaintenanceWindow: sat:09:21-sat:09:51
          publiclyAccessible: false
          storageEncrypted: false
          storageType: gp2
        providerConfigRef:
          name: aws
    patches:
      - fromFieldPath: "spec.parameters.secretPath"
        toFieldPath: "spec.publishConnectionDetailsTo.name"
      - fromFieldPath: "spec.parameters.secretConfigName"
        toFieldPath: "spec.publishConnectionDetailsTo.configRef.name"
    connectionDetails:
      - fromConnectionSecretKey: username
      - fromConnectionSecretKey: password
      - fromConnectionSecretKey: endpoint
      - fromConnectionSecretKey: port
```
```yaml
apiVersion: database.example.org/v1alpha1
kind: XPostgreSQLInstance
metadata:
  name: my-rds
  namespace: crossplane
spec:
  parameters:
    secretPath: path/to/secret
    secretConfigName: vault
```

### What environment did it happen in?
Crossplane version: `1.8.1`
Kubernetes version: 
```
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
