### ISSUE TITLE
Unable to patch XRC metadata.label

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/crossplane#3180]
The XRC metadata.label doesn't get patched, while the XR metadata.label does get patched

### What happened?

Given the following patch in my composition

```yaml
    - type: ToCompositeFieldPath
      toFieldPath: metadata.labels[servicebinding.io/provisioned-service]
      fromFieldPath: status.atProvider.settingsVersion
      transforms:
      - type: convert
        convert:
          toType: string
      - type: string
        string:
          fmt: true%.0s
```

Given a CloudSql MR with the following status 

```yaml
status:
  atProvider:
    backendType: SECOND_GEN
[...]
    settingsVersion: 1
    state: RUNNABLE
```

Then the XR has the proper label `servicebinding.io/provisioned-service: "true"`:

```
metadata:
  labels:
    crossplane.io/claim-name: kuttl-pg-instance
    crossplane.io/claim-namespace: 75-crossplane-resources-ytt
    crossplane.io/composite: kuttl-pg-instance-fctz2
    servicebinding.io/provisioned-service: "true"
```

but the XRC does not and has a no metadata.labels

### How can we reproduce it?

See snippets above, along with additional context and details in the slack related thread https://crossplane.slack.com/archives/CEG3T90A1/p1657228846677309

### What environment did it happen in?
Crossplane version: 1.8.0
* Cloud provider or hardware configuration: gcp
* Kubernetes version (use `kubectl version`): 1.23.5
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift). Openshift
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)
-->
