### ISSUE TITLE
Proposal - provide full control over connection Secret (in addition to data fields)

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/crossplane#3181]
### What problem are you facing?

In order to implement the the k8s service binding spec at https://github.com/servicebinding/spec#provisioned-service, I need the 
Secret type to be patched by the composition

>  The Secret type (.type verses .data.type fields) SHOULD reflect this value as servicebinding.io/{type}, substituting {type} with the Secret data type.

Currently, crossplane only provides control over the connection secret `.data` fields

### How could Crossplane help solve your problem?

The [composition's connection details](https://crossplane.io/docs/v1.8/reference/composition.html#connection-details) would include an additional `path` entry to specify the path to the Secret resource into which the connection key would be set. The default value of the path attribute being `.stringData`

Given the following composition fragment

```yaml
      connectionDetails:
      - type: FromValue
        name: port
        value: "5432"
        path: ".stringData" # optional, matches the default value in this example
      - type:  FromValue
        name: type
        value: "servicebinding.io/mysql"
        path: "."
      - type:  FromValue
        name: "custom.org/label"
        value: "custom-value"
        path: "metadata.labels"
```

The XRC connection secret would be

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: ...
  namespace: ...
  labels:
     "custom.org/label": "custom-value"
type: "servicebinding.io/mysql"
stringData:
  port: 5432
```
