### ISSUE TITLE
Bad error message on missing MR secret from Composition

### ISSUE THREAD

**Issue by AaronME** [crossplane/crossplane#3194]
### What happened?
Crossplane error indicates it is attempting to write to the same secret for both MR and XR when External Secret Store is enabled. This seems to be https://github.com/crossplane/crossplane/issues/3172. Error message is ambiguous.

### How can we reproduce it?

**This test requires a StoreConfig named `vault` which is pointing to a working Vault instance.**

1. Publish the following Composite Resource to a cluster where crossplane is running with the `--enable-external-secret-stores` flag: 

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeessinstances.ess.example.org
  annotations:
    feature: ess
spec:
  group: ess.example.org
  names:
    kind: CompositeESSInstance
    plural: compositeessinstances
  claimNames:
    kind: ESSInstance
    plural: essinstances
  connectionSecretKeys:
    - publicKey
    - publicKeyType
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  serviceAccount:
                    type: string
                required:
                  - serviceAccount
            required:
              - parameters
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: essinstances.ess.example.org
  labels:
    feature: ess
spec:
  compositeTypeRef:
    apiVersion: ess.example.org/v1alpha1
    kind: CompositeESSInstance
  resources:
    - name: serviceaccount
      base:
        apiVersion: iam.gcp.crossplane.io/v1alpha1
        kind: ServiceAccount
        spec:
          forProvider:
            displayName: a service account to test ess
    - name: serviceaccountkey
      base:
        apiVersion: iam.gcp.crossplane.io/v1alpha1
        kind: ServiceAccountKey
        spec:
          forProvider:
            serviceAccountSelector:
              matchControllerRef: true
      connectionDetails:
        - fromConnectionSecretKey: publicKey
        - fromConnectionSecretKey: publicKeyType
```
2. Deploy a Claim against this composite:
```yaml
apiVersion: ess.example.org/v1alpha1
kind: ESSInstance
metadata:
  name: vault-ess
  namespace: default
spec:
  parameters:
    serviceAccount: ess-test-sa
  compositionSelector:
    matchLabels:
      feature: ess
  publishConnectionDetailsTo:
    name: vault-ess-claim-conn
    metadata:
      labels:
        environment: development
        team: backend
    configRef:
      name: vault
```
3. The error `cannot propagate connection details from composite: cannot establish control of existing connection secret` will appear in the event stream.
4. The CompositeEssInstance is showing this in the spec:
```
  publishConnectionDetailsTo:
    configRef:
      name: default
    name: 96961ead-7083-4dc8-a9c5-25bc638ae88b
```
5. Examining vault, there is an empty secret for `96961ead-7083-4dc8-a9c5-25bc638ae88b`. This might indicate that the composite cannot establish control because the MR secret is "missing". (Error message clears if we add `publishConnectionDetailsTo` to MR spec.)

### What environment did it happen in?
Crossplane version: 1.7.2-up.2

* kind version 0.14.0
* v1.21.12
* kindest
* N/A
* 20.6.0 Darwin Kernel
