### ISSUE TITLE
Crossplane cannot delete kubernetes secrets generated by External Secrets Stores

### ISSUE THREAD

**Issue by AaronME** [crossplane/crossplane#3195]
### What happened?
We deployed a composite which set the `publishConnectionDetailsTo` to the `default` StoreConfig.
### How can we reproduce it?
1. Run crossplane with `--enable-external-secret-stores` flag
2. Configure the following StoreConfigs
```yaml
---
apiVersion: secrets.crossplane.io/v1alpha1
kind: StoreConfig
metadata:
  name: default
spec:
  type: Kubernetes
  defaultScope: upbound-system
---
apiVersion: gcp.secrets.crossplane.io/v1alpha1
kind: StoreConfig
metadata:
  name: default
spec:
  type: Kubernetes
  defaultScope: upbound-system
```
3. Launch a Claim targeting these storeConfigs.
4. Observe Managed Resources and Secrets will create successfully.
5. Delete the Claim.
6. Note an error on deleting the Composite Resource: `cannot unpublish connection details: cannot delete from secret store: cannot delete secret: secrets \"2b4271cf-ab12-4b8a-86b6-86b74b333fd9\" is forbidden: User \"system:serviceaccount:upbound-system:crossplane\" cannot delete resource \"secrets\" in API group \"\" in the namespace \"upbound-system\"`

### What environment did it happen in?
Crossplane version: 1.7.2-up.2

kind version 0.14.0
v1.21.12
kindest
N/A
20.6.0 Darwin Kernel
