### ISSUE TITLE
XRD spec.versions[0].schema.openAPIV3Schema is weakly typed as an object instead of full openapi schema

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/crossplane#3197]
### What problem are you facing?

As a crossplane XRD author, in order to write provide quality openapi schemas for my XRDs, I need to leverage IDE completion based on the XRD CRD schema definition.

Currently the XRD CRD is defining spec.versions[0].schema.openAPIV3Schema  as a plain object without detailing supported fields

https://github.com/crossplane/crossplane/blob/6494953ca4d5a56350fbe696d351f9a416aae48e/cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml#L273-L277

### How could Crossplane help solve your problem?

It might be possible for XRD CRD to instead reference the openapi v3 schema fields, possibly with a URI (see related specs at https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-5) , in order to get completion just like CRD authors experience natively, see the following example of editing a sample CRD in intellij:

![image](https://user-images.githubusercontent.com/4748380/179801851-4fd5676d-44e7-4d5c-b8f1-cd4a046b600f.png)

**Comment by gberche-orange** [comment]
Actually, it seem the K8S CRD openapi schema is also currently defining top level fields which is insufficient to properly author a CRD schema
![image](https://user-images.githubusercontent.com/4748380/179807053-f2e7f871-c926-4959-8667-6a0183f6ae62.png)

**Comment by MisterMX** [comment]
Defining a schema for `openAPIV3Schema` requires recursive schema definition which is currently not supported by Kubernetes at the moment. See https://github.com/kubernetes/kubernetes/issues/62872.

It works for CRDs because they are a built-int type.

**Comment by negz** [comment]
Yeah, sadly this is a painful known issue. We've discussed writing a validation webhook for it since CRD machinery can't handle it internally - that seems like the most promising path forward.

**Comment by gberche-orange** [comment]
Thanks @MisterMX and @negz for the follow up

> We've discussed writing a validation webhook for it since CRD machinery can't handle it internally - that seems like the most promising path forward.

I guess this would cover the case of rejecting invalid schemas in XRDs, but not yet improving the authoring experience by supporting coding assistance (completion, syntax check, inline documentation).

**Comment by gberche-orange** [comment]
I'm currently working around this issue using the [carvel ytt  YAML template engine](https://carvel.dev/ytt/) with which I inline a valid Json schema file (natively supported by IDEs such as intellij) into my XRD

https://www.jetbrains.com/help/idea/json.html#ws_json_using_schemas
> Schemas from the JSON Schema Store can be applied to YAML files as well.

```yaml
#@ load("/definition-xrd-schema.lib.yaml", "schema")
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.orange.com #! must be consistent with spec.names.plural
spec:
[...]
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
         openAPIV3Schema: #@ schema()
```

definition-xrd-schema.lib.yaml:
```yaml
#! A valid Json schema draft 6 which gets inlied as the openapiSchema v2 for XRD
#! To set as a Json schema in intellij, select bottom left drop down "Json schema version 4"
#! which is what supports openapi v2: see https://swagger.io/specification/v2/
#! This is a workaround for lack of openapi schema in XRD
#! See https://github.com/crossplane/crossplane/issues/3197
#@ def schema():
type: object
description: "PostgreSQLInstance provisions a managed database instance with the postgresql dialect."
properties:
  #! try to explicitely declare the metadata.labels[servicebinding.io/provisioned-service]=true that we try to set
  metadata:
    type: object
    properties:
      labels:
        type: object
        properties:
          "servicebinding.io/provisioned-service":
            type: string
  spec:
    description: "The desired behavior of this Postgresql Instance"
    type: object
    properties:
      plan:
        description: "Plan controls SLA of the Postgresql instance including capacity, performance, availability. "
        type: string
        enum:
          - "small"
          - "medium"
          - "large"
        default: "small"
```        


![image](https://user-images.githubusercontent.com/4748380/180217413-6924a940-ba63-4927-8de6-fcd4bd37c34b.png)

**Comment by tnthornton** [comment]
>I guess this would cover the case of rejecting invalid schemas in XRDs, but not yet improving the authoring experience by supporting coding assistance (completion, syntax check, inline documentation).

This is pretty spot on. The resulting feedback loop is pretty rough as well.

>As a XRD author, I'm currently working around this issue using the [carvel ytt YAML template engine](https://carvel.dev/ytt/) with which I inline a valid Json schema file (natively supported by IDEs such as intellij) into my XRD

This is pretty interesting. This solution is primarily focused on authoring the XRD itself and getting type hints there, right? Or does it also cover XRs and claims?

FWIW, we included a [language server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide), in the `up` CLI that gives _some_ schema validation on claims, XRs, and _some_ validation in XRDs.
Roughly what the current feature set covers is:
* claims are validated using their corresponding XRD
* XR resources are validated in the following ways:
    * if the resource is another XR the corresponding XRD is used
    * if the resource is a MR the corresponding CRD is used
* for XRDs the openAPIV3Schema is validated for "correctness". This is mostly to try to help with typing a fundamentally invalid schema.

The language server is currently in an alpha state. Given that it is implementing the language server protocol, it should work with IntelliJ. 

> Disclaimer: personally I've verified that you can get feedback from the language server into IntelliJ, but I haven't used it much beyond that.

If you're interested in checking it out you can get the `up` CLI (xpls is bunding in that binary) [here](https://github.com/upbound/up). The corresponding work I did to get the language server to integrate with Goland can be found [here](https://github.com/upbound/up-ls/pull/50).

**Comment by bobh66** [comment]
@tnthornton this looks really useful - however the link to the up-ls repo is broken - it doesn't seem to be a public repo on github.

**Comment by tnthornton** [comment]
@bobh66 sorry about that. The important steps were:
```
Installed LSP plugin in Goland.
Configured LSP server to execute up xpls serve --verbose
```

**Comment by bobh66** [comment]
thanks!

**Comment by tnthornton** [comment]
If you happen to use VSCode, we also have a very thin extension that starts up the language server and listens to diagnostics https://marketplace.visualstudio.com/items?itemName=Upboundio.upbound.

**Comment by gberche-orange** [comment]
thanks @tnthornton 

> claims are validated using their corresponding XRD
For XRC, the plain openapi schema seems sufficient to get full coding assistance. What additional info would give the XRD that is'nt in the corresponding generated CRD ?

> Given that it is implementing the language server protocol, it should work with IntelliJ.
From https://youtrack.jetbrains.com/issue/IDEABKL-7409 I see that LSP support in intellij isn't very strong 

> This solution is primarily focused on authoring the XRD itself and getting type hints there, right? Or does it also cover XRs and claims?

I however also use the ytt templating for authoring Compositions (including base resources and patches). See sample below


![image](https://user-images.githubusercontent.com/4748380/180871805-b5cc379d-3c0f-4745-910c-b00b39fcb2f4.png)![image](https://user-images.githubusercontent.com/4748380/180871390-c31fab3e-9172-43ea-b1fb-a3e4fa4ef34d.png)

<details><summary>code snippet of the yaml ytt templating to render these resources as valid Composition</summary>

composition.yaml
```
#@ load("/cloudsql-resource-data.lib.yaml", "resource")
#@ load("/cloudsql-others-data.lib.yaml", "others")
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstances.gcp.database.orange.com
  labels:
    provider: gcp
spec:
  writeConnectionSecretsToNamespace: 75-crossplane-gcp-cnx-secrets
  compositeTypeRef:
    apiVersion: database.orange.com/v1alpha1
    kind: XPostgreSQLInstance
  #@ resource_yaml_fragment = resource()
  #@ resource = { "base": dict(**resource_yaml_fragment) }
  #@ other_elements = dict(**others()["spec"]["resources"][0])
  #@ other_elements.pop("base")
  #@ resource.update(other_elements)
  #@ resources = [ resource ]
  resources: #@ resources
```

cloudsql-resource-data.lib.yaml:
```
#! To be excluded from output, this lib have no yaml document --- header
#@ load("@ytt:data", "data")
#@ def resource():
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: cloudsql
spec:
  forProvider:
    databaseVersion: POSTGRES_14
    region: #@ data.values.external_gcp_region
    settings:
      tier: db-f1-micro
      #!              tier: db-custom-1-3840 # 1 CPU, 3840 MB RAM. See https://cloud.google.com/sql/docs/postgres/create-instance#machine-types
      availabilityType: "ZONAL" #! for HA db use REGIONAL
      backupConfiguration: { #! for HA db ie. REGIONAL set both following to true
        binaryLogEnabled: false,
        enabled: false
      }
      
      #!      dataDiskType: PD_SSD
      dataDiskType: PD_HDD #! cheaper
      ipConfiguration:
        ipv4Enabled: false
        privateNetwork: #@ "projects/{}/global/networks/{}".format(data.values.external_gcp_project_id, data.values.external_gcp_poc_openshift_cluster_vpc_network)
        requireSsl: false
      databaseFlags: #! Orange security requirement
        - name: "log_checkpoints"
          value: "on"
        - name: "log_connections"
          value: "on"
        - name: "log_disconnections"
          value: "on"
        - name: "log_lock_waits"
          value: "on"
        - name: "log_temp_files"
          value: "10000" #! 10,000 KB. The security spec isn't providing a value and suggest "0" as default value:  If all temporary files are not logged, it may be more difficult to identify potential performance issues that may be due to either poor application coding or deliberate resource starvation attempts.

  writeConnectionSecretToRef:
    name: default-name-overriden-by-patch
    namespace: 75-crossplane-gcp-cnx-secrets
#@ end
```

cloudsql-others-data.lib.yaml:
```
#! To be excluded from output, this lib have no yaml document --- header
#@ def others():
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  resources:
    - patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        #!        - fromFieldPath: "spec.parameters.storageGB"
        #!          toFieldPath: "spec.forProvider.settings.dataDiskSizeGb"

        #! Try to implement the service binding spec
        #! https://github.com/servicebinding/spec#provisioned-service
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: status.binding.name

        #!  To facilitate discoverability, it is RECOMMENDED that a CustomResourceDefinition exposing a Provisioned Service add servicebinding.io/provisioned-service: "true" as a label.
        - type: ToCompositeFieldPath
          toFieldPath: metadata.labels[servicebinding.io/provisioned-service]
          fromFieldPath: status.atProvider.settingsVersion #! try to wait for a field which is only available when the resource is ready
          transforms:
            #! first convert int to string
            - type: convert
              convert:
                toType: string
            #! then format string with zero length
            - type: string
              string:
                fmt: "true%.0s"
                #! constant string %.0s prints the string with a max zero width. Otherwise gofmt reports
                #! an error about the argument not being used.
                #! EXTRA string
                #! more at https://pkg.go.dev/fmt
                #! https://github.com/golang/go/issues/8151
                #! interactive test https://go.dev/play/
      connectionDetails:
      - type: FromConnectionSecretKey
        name: host
        fromConnectionSecretKey: privateIP
      - type: FromConnectionSecretKey
        name: username
        fromConnectionSecretKey: username
      - type: FromConnectionSecretKey
        name: password
        fromConnectionSecretKey: password
      - type: FromValue
        name: port
        value: "5432"
      - type:  FromValue
        name: type
        value: "postgresql"
      - type:  FromValue
        name: provider
        value: "gcp cloudsql"
      - type:  FromValue
        name: database #! required by spring-clod-bindings when jdbc-url is missing, see https://github.com/spring-cloud/spring-cloud-bindings#postgresql-rdbms
        value: ""



      base: {}

  compositeTypeRef:
    apiVersion: dummy
    kind: dummy

#@ end
```
</details>
