### ISSUE TITLE
Composition Patch map default value or regexp match

### ISSUE THREAD

**Issue by blut** [crossplane/crossplane#3199]
Hello

If possible, I'd like to set a default value for a composite resource patch of type map.

### What problem are you facing?
We have a value map for different environments.
With multiple dev-environments, I'd like to define the value for all dev enviroments through a map default value or a map regexp match. 

Currently I have to specify each environment in my patch map
![image](https://user-images.githubusercontent.com/4506959/180457022-b9184b80-8b67-4b97-bd46-e487caff7887.png)

Especially for dev environments I'd like to use a regexp or a default value
```
    - fromFieldPath: metadata.labels['crossplane.io/claim-namespace']
      policy:
        fromFieldPath: Required
      toFieldPath: spec.forProvider.tags[6].value
      transforms:
      - map:
          .*-dev: DEV
```

**Comment by MisterMX** [comment]
Thanks for opening this issue @blut. I stumbled across this multiple times as well.

Thing is that `map` is serialized into `map[string]string` and don't think its a good idea to make an exception for a special key like `_default`.

I can imagine something like

```yaml
      transforms:
      - map:
          .*-dev: DEV
        mapDefault: "default-value"
```

**Comment by blut** [comment]
Would you think interpreting map keys as rexexp would break many use-cases?
We might consider a separate transform type, such as regexpMap.

**Comment by MisterMX** [comment]
> Would you think interpreting map keys as rexexp would break many use-cases?

I think regex support could be enabled via a flag:

```yaml
      transforms:
      - map:
          .*-dev: DEV
        mapDefault: "default-value"
        mapRegexEnabled: true
```

**Comment by negz** [comment]
> I think regex support could be enabled via a flag.

This could also be a different kind of transform entirely (e.g. `matches` or something). I don't feel strongly though.

**Comment by MisterMX** [comment]
> This could also be a different kind of transform entirely (e.g. matches or something). I don't feel strongly though.

Yeah, some other languages like Godot's GDScript are using `match` instead of switch / case and maps. Although I have a feeling that it might confuse people in this case since `map` would just be a low-level version of `match`.

What about having a `mapPolicy` property where we have more freedom and can put everything there to configure map transforms? I.e.

```yaml
      transforms:
      - map:
          .*-dev: DEV
        mapPolicy:
          mode: RegExp # Default would be somthing like `EqualKey`
          fallbackValue: `default-value`
```
