### ISSUE TITLE
Cannot publish secret: "not owned by UID"

### ISSUE THREAD

**Issue by enrichman** [crossplane/crossplane#3203]
### What happened?

Crossplane and `provider-aws` deployed with `--enable-external-secret-stores` flag.
When a claim is asking to `publishConnectionDetailsTo` this secret then it will not be updated because the owner is different:

```
Warning  PublishConnectionSecret  4s (x5 over 18s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot publish connection details: cannot write to secret store: cannot apply secret: existing secret is not owned by UID "8eea7db1-3c40-4717-acf7-e4e7488bd17b"
```

### How can we reproduce it?

Created a secret, and then asked for a claim:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysecret-connection
  namespace: mynamespace
---
apiVersion: awsblueprints.io/v1alpha1
kind: DynamoDBTable
metadata:
  name: mytable
  namespace: mynamespace
spec:
  publishConnectionDetailsTo:
    name: mysecret-connection
    configRef:
      name: default
    # etc
```

### What environment did it happen in?

Crossplane version: v1.9.0 (local cluster, k3d)
K3S: v1.21.7+k3s1
openSUSE Tumbleweed
5.18.9-2-default

**Comment by turkenh** [comment]
@enrichman this is expected to happen when the secret has an owner other than the MR itself which is the `DynamoDBTable` here. Did you check who owns that secret, i.e. where `ownerReferences` field points to. 

This could happen when multiple MRs/XRs pointing to the same secret as the connection secret.

**Comment by enrichman** [comment]
It seems that it didn't have an owner at all, but I guess that the problem was due to the Composition that I was using: https://github.com/aws-samples/crossplane-aws-blueprints/blob/main/compositions/aws-provider/dynamodb/provisioned-composite-key.yaml

Could the 
```yaml
writeConnectionSecretsToNamespace: crossplane-system
```
be a problem? I was using also an existing secret, and I don't know if that's an issue.

I've tried to edit the Composition changing that part to:

```yaml
publishConnectionDetailsWithStoreConfigRef:
  name: default
```

and without creating any secret, and it seems that the secret was created.

BUT now I'm facing the problem that not all the fields of the secrets are publihshed, only the `region`.

This is the edited composition: 

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dynamo-provisioned-composite.dynamodb.awsblueprints.io
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    dynamodb.awsblueprints.io/capacity: provisioned
    dynamodb.awsblueprints.io/pkType: composite
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XDynamoDBTable
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
  resources:
    - name: table
      connectionDetails:
        - name: tableName
          fromConnectionSecretKey: tableName
        - name: tableArn
          fromConnectionSecretKey: tableArn
        - type: FromFieldPath
          name: region
          fromFieldPath: spec.forProvider.region
      base:
        apiVersion: dynamodb.aws.crossplane.io/v1alpha1
        kind: Table
        spec:
          deletionPolicy: Delete
          forProvider:
            attributeDefinitions:
              - attributeName: ""
                attributeType: ""
              - attributeName: ""
                attributeType: ""
            billingMode: PROVISIONED
            keySchema:
              - attributeName: ""
                keyType: HASH
              - attributeName: ""
                keyType: RANGE
            provisionedThroughput:
              readCapacityUnits: 5
              writeCapacityUnits: 5
            region: ""
            sseSpecification:
              enabled: true
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tableIndex.hashKeyName
          toFieldPath: spec.forProvider.attributeDefinitions[0].attributeName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tableIndex.hashKeyType
          toFieldPath: spec.forProvider.attributeDefinitions[0].attributeType
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tableIndex.rangeKeyName
          toFieldPath: spec.forProvider.attributeDefinitions[1].attributeName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tableIndex.rangeKeyType
          toFieldPath: spec.forProvider.attributeDefinitions[1].attributeType
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tableIndex.hashKeyName
          toFieldPath: spec.forProvider.keySchema[0].attributeName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.throughputConfig.read
          toFieldPath: spec.forProvider.provisionedThroughput.readCapacityUnits
        - type: FromCompositeFieldPath
          fromFieldPath: spec.throughputConfig.write
          toFieldPath: spec.forProvider.provisionedThroughput.writeCapacityUnits
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tableIndex.rangeKeyName
          toFieldPath: spec.forProvider.keySchema[1].attributeName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.tableARN
          toFieldPath: status.tableARN
```

**Comment by enrichman** [comment]
Ok, in the end it worked adding again this part:

```yaml
       base:
         spec:
           writeConnectionSecretToRef:
             namespace: crossplane-system
             name: ""

        patches:
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-dynamodb-table"
```

but I see that the published secret is of the `connection.crossplane.io/v1alpha1` type. Is it possible to use an existing secret, or they needs to be of this specific type?
