### ISSUE TITLE
Add a `--version` flag

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3239]
### What problem are you facing?

I'm currently trying to figure out what version of Crossplane a particular build is by creating a `Configuration` that will only work on that version, e.g.

```yaml
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: is-this-the-right-version
spec:
  crossplane:
    version: "v1.9.0-up.2"
```

### How could Crossplane help solve your problem?

Life would be a lot simpler if I could just run `crossplane --version` to find out what version a particular binary was.
