### ISSUE TITLE
Bug/Clarification removing XR fields, once set, does actually get removed

### ISSUE THREAD

**Issue by tbmetcalfe** [crossplane/crossplane#3248]
### What happened?

I've created an XR with a particular XRD with some optional parameter which has a default value as specified in its corresponding Composition.

If you choose to override this field when using the XR and then choose to remove this overridden field, the overridden field persists where I would have expected it to revert to the default value. Therefore to actually use the default value, one must override it with the default value. Perhaps this is intentional but maybe some docs on this could be useful. 

### How can we reproduce it?

XRD
```yaml
 #[...]
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            properties:
              parameters:
                properties:
                  optionalField:
                    type: string
```

Composition
```yaml
#[...]
  resources:
    - base:
        apiVersion: service.aws.crossplane.io/v1alpha1
        kind: SomeResource
        metadata:
          name: example-resource
        spec:
          deletionPolicy: Orphan
          forProvider:
            optionalField: someDefaultValue
      - fromFieldPath: spec.parameters.optionalField
          toFieldPath: spec.forProvider.optionalField
          type: FromCompositeFieldPath
```

XR Before
```yaml
apiVersion: service.crossplane.example.com/v1alpha1
kind: SomeResource
metadata:
  name: demo
spec:
  parameters:
    optionalField: overriddenField
```

XR After
```yaml
apiVersion: service.crossplane.example.com/v1alpha1
kind: SomeResource
metadata:
  name: demo
spec:
  parameters: {} # note that optionalField has been removed and therefore expecting to now be the default value (someDefaultValue)
```

Then run `kubectl get someresource.service.crossplane.example` and you should be presented with 

```yaml
apiVersion: service.crossplane.example.com/v1alpha1
kind: SomeResource
metadata:
  name: demo
spec:
  parameters:
    optionalField: overriddenField # note that the overridden field persists despite it being removed from the manifest
# [...]
```

### What environment did it happen in?
Crossplane version: 1.9.0
AWS Provider version: 0.29.0

Cloud provider or hardware configuration: AWS EKS
Kubernetes version (use kubectl version): v1.21.14-eks-18ef993
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS
