### ISSUE TITLE
cannot get authorizer from client credentials config: failed to get SPT from client credentials: parameter 'activeDirectoryEndpoint' cannot be empty

### ISSUE THREAD

**Issue by makdeniz** [crossplane/crossplane#3273]
### What happened?

I got this error both from my local kind cluster and AKS. Any idea?

### How can we reproduce it?

```yaml
apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: example-rg
spec:
  location: Germany West Central
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: 
v1.9.0
provider-azure-controller:v0.19.0
