### ISSUE TITLE
Missing `writeConnectionSecretToRef` field from Composite Resource in XR. 

### ISSUE THREAD

**Issue by Creatone** [crossplane/crossplane#3313]
### What happened?

Missing `writeConnectionSecretToRef` field from Composite Resource in XR. 
It's present in the XR `kubectl.kubernetes.io/last-applied-configuration` annotation.

### How can we reproduce it?

I'm missing this field each time.
### What environment did it happen in?
Crossplane version: 1.9.0, 1.8.1

**Comment by turkenh** [comment]
@Creatone could you give some more details, ideally with some example YAMLs?

**Comment by Creatone** [comment]
Example claim:
```
apiVersion: my-api.com/v1alpha1
kind: KafkaInstance
metadata:
  name: kafka-example
  namespace: my-ns
spec:
  parameters:
    replicas: 1
  compositionSelector:
    matchLabels:
      provider: ionos-strimzi
  writeConnectionSecretToRef:
    name: kafka-secret
```

and I want to use `writeConnectionSecretToRef.Name` in this composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kafka-strimzi
  labels:
    crossplane.io/xrd: xkafkainstances.my-api.com
    ...
spec:
  compositeTypeRef:
    apiVersion: my-ip.com/v1alpha1
    kind: XKafkaInstance
  resources:
    ...
    - name: kafkaK8sCluster
      base:
        apiVersion: ...
        kind: ...
        spec:
          ...
      patches:
        - fromFieldPath: spec.writeConnectionSecretToRef.name
          toFieldPath: spec.writeConnectionSecretToRef.name
      ...    
```

Sorry I cannot share all details.
