### ISSUE TITLE
Support merging with an array item in composition patches

### ISSUE THREAD

**Issue by ulucinar** [crossplane/crossplane#3335]
### What problem are you facing?

We have recently encountered an issue with a Crossplane composition that patches the selector field of an array item. Crossplane [does a merge patch](https://github.com/crossplane/crossplane-runtime/blob/619edbacb81eb9b4ccb6a5a7ba8f07d74cc07dc9/pkg/resource/api.go#L157), which overrides the whole array element together with the target field and the reference field. This causes the already resolved target fields to get lost, leaving only the selector field. 

In such cases, there is a race condition between the Crossplane's composite reconciler (who composes and patches the composed resource) and the associated Crossplane provider's managed resource reconciler.

Here's how the situation can be observed:
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: myresources.xp.test.com
spec:
  group: xp.test.com
  names:
    kind: MyResource
    listKind: MyResourceList
    plural: myresources
    singular: myresource
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MyResource is the Schema for the myresources API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MyResourceSpec defines the desired state of MyResource
            properties:
              forProvider:
                description: A is an example field of MyResource. Edit myresource_types.go
                  to remove/update
                properties:
                  b:
                    properties:
                      targetRefs:
                        items:
                          description: A Reference to a named object.
                          properties:
                            name:
                              description: Name of the referenced object.
                              type: string
                            policy:
                              description: Policies for referencing.
                              properties:
                                resolution:
                                  default: Required
                                  description: Resolution specifies whether resolution
                                    of this reference is required. The default is
                                    'Required', which means the reconcile will fail
                                    if the reference cannot be resolved. 'Optional'
                                    means this reference will be a no-op if it cannot
                                    be resolved.
                                  enum:
                                  - Required
                                  - Optional
                                  type: string
                                resolve:
                                  description: Resolve specifies when this reference
                                    should be resolved. The default is 'IfNotPresent',
                                    which will attempt to resolve the reference only
                                    when the corresponding field is not present. Use
                                    'Always' to resolve the reference on every reconcile.
                                  enum:
                                  - Always
                                  - IfNotPresent
                                  type: string
                              type: object
                          required:
                          - name
                          type: object
                        type: array
                      targetSelector:
                        description: A Selector selects an object.
                        properties:
                          matchControllerRef:
                            description: MatchControllerRef ensures an object with
                              the same controller reference as the selecting object
                              is selected.
                            type: boolean
                          matchLabels:
                            additionalProperties:
                              type: string
                            description: MatchLabels ensures an object with matching
                              labels is selected.
                            type: object
                          policy:
                            description: Policies for selection.
                            properties:
                              resolution:
                                default: Required
                                description: Resolution specifies whether resolution
                                  of this reference is required. The default is 'Required',
                                  which means the reconcile will fail if the reference
                                  cannot be resolved. 'Optional' means this reference
                                  will be a no-op if it cannot be resolved.
                                enum:
                                - Required
                                - Optional
                                type: string
                              resolve:
                                description: Resolve specifies when this reference
                                  should be resolved. The default is 'IfNotPresent',
                                  which will attempt to resolve the reference only
                                  when the corresponding field is not present. Use
                                  'Always' to resolve the reference on every reconcile.
                                enum:
                                - Always
                                - IfNotPresent
                                type: string
                            type: object
                        type: object
                      targets:
                        items:
                          type: string
                        type: array
                    type: object
                  bArr:
                    items:
                      properties:
                        targetRefs:
                          items:
                            description: A Reference to a named object.
                            properties:
                              name:
                                description: Name of the referenced object.
                                type: string
                              policy:
                                description: Policies for referencing.
                                properties:
                                  resolution:
                                    default: Required
                                    description: Resolution specifies whether resolution
                                      of this reference is required. The default is
                                      'Required', which means the reconcile will fail
                                      if the reference cannot be resolved. 'Optional'
                                      means this reference will be a no-op if it cannot
                                      be resolved.
                                    enum:
                                    - Required
                                    - Optional
                                    type: string
                                  resolve:
                                    description: Resolve specifies when this reference
                                      should be resolved. The default is 'IfNotPresent',
                                      which will attempt to resolve the reference
                                      only when the corresponding field is not present.
                                      Use 'Always' to resolve the reference on every
                                      reconcile.
                                    enum:
                                    - Always
                                    - IfNotPresent
                                    type: string
                                type: object
                            required:
                            - name
                            type: object
                          type: array
                        targetSelector:
                          description: A Selector selects an object.
                          properties:
                            matchControllerRef:
                              description: MatchControllerRef ensures an object with
                                the same controller reference as the selecting object
                                is selected.
                              type: boolean
                            matchLabels:
                              additionalProperties:
                                type: string
                              description: MatchLabels ensures an object with matching
                                labels is selected.
                              type: object
                            policy:
                              description: Policies for selection.
                              properties:
                                resolution:
                                  default: Required
                                  description: Resolution specifies whether resolution
                                    of this reference is required. The default is
                                    'Required', which means the reconcile will fail
                                    if the reference cannot be resolved. 'Optional'
                                    means this reference will be a no-op if it cannot
                                    be resolved.
                                  enum:
                                  - Required
                                  - Optional
                                  type: string
                                resolve:
                                  description: Resolve specifies when this reference
                                    should be resolved. The default is 'IfNotPresent',
                                    which will attempt to resolve the reference only
                                    when the corresponding field is not present. Use
                                    'Always' to resolve the reference on every reconcile.
                                  enum:
                                  - Always
                                  - IfNotPresent
                                  type: string
                              type: object
                          type: object
                        targets:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                type: object
            type: object
          status:
            description: MyResourceStatus defines the observed state of MyResource
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmyresources.test.com
spec:
  group: test.com
  names:
    kind: XMyResource
    plural: xmyresources
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
            required:
              - name

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
  labels:
    purpose: example
spec:
  compositeTypeRef:
    apiVersion: test.com/v1alpha1
    kind: XMyResource
  resources:
    - name: myresource
      base:
        apiVersion: xp.test.com/v1alpha1
        kind: MyResource
        metadata:
        spec:
          forProvider: {}
      patches:
        - fromFieldPath: "spec.name"
          toFieldPath: spec.forProvider.bArr[0].targetSelector.matchLabels[key2]

---
apiVersion: test.com/v1alpha1
kind: XMyResource
metadata:
  name: test
spec:
  name: testName
  compositionRef:
    name: example
```

If, after applying these manifests, the following patch is applied on the composed resource (simulating the provider's action):
```yaml
spec:
  forProvider:
    b:
      targets:
      - testTarget1.a
      - testTarget1.b
      targetRefs:
      - name: targetName1.a
      - name: targetName1.b
      targetSelector:
        matchLabels:
          key1: val1
    bArr:
      - targets:
        - testTarget2.a
        - testTarget2.b
        targetRefs:
        - name: targetName2.a
        - name: targetName2.b
        targetSelector:
          matchLabels:
            key2: val2
```
, one can observe that the `spec.forProvider.bArr[0].targets` and `spec.forProvider.bArr[0].targetRefs` fields are emptied.

### How could Crossplane help solve your problem?

We can introduce a new patch policy that will merge, instead of replace, array items. The current behavior of [JSON merge patch](https://tools.ietf.org/html/rfc7386) works as expected but the resulting behavior is not intuitive and can easily cause issues.

**Comment by bobh66** [comment]
Did you try the mergeOptions appendSlice policy as described here:  https://crossplane.io/docs/v1.9/reference/composition.html#compositions ?

**Comment by ulucinar** [comment]
Hi @bobh66,
Thank you for the pointer. I think the appendSlice is for appending a new slice item in addition to the existing ones in the observed state when patching. However, what we need here is to be able to merge with an existing slice item via a designated key. This would be similar to Kubernetes strategic merge patching with a similar need for the specification of a `patchMergeKey` in addition to specifying the patch policy.

**Comment by negz** [comment]
Is there any upstream machinery that could help with this? In particular I suspect we're overdue to move to server-side apply which appears to have 'built in' support for merge strategies on custom resources - https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy

**Comment by muvaf** [comment]
If I'd like to patch `spec.forProvider.bArr[0].targetSelector.matchLabels[key2]` and other properties of `spec.forProvider.bArr[0]` get affected by this for some reason, I'd say this is a bug regardless of the underlying machinery. So I changed the label to `bug`.

**Comment by negz** [comment]
@muvaf I don't disagree - my point is that I'm wary of continuing to "reinvent the wheel" by teaching our client-side patching logic how to do what it seems SSA already does.

**Comment by muvaf** [comment]
@negz Oh yeah, my comment wasn't really directed towards what approach we'd like to take. Just wanted to change it to be considered as a bug, which I think would impact whether we add a policy if we consider it as feature or improve the existing behavior if it's considered as bug.

From what I'm reading the doc you shared, `Using Server-Side Apply in a controller` section does describe the behavior we'd like so I'd like to give it a try and if it works that'd be my preference as well.

If it doesn't, I think another option could be to generate a set of `fieldpath.SetValue` statements from the given template and prepend it to the statements produced from `patches` array of the composition. Then we'd fetch the existing object, run all `fieldpath.SetValue` statements on it and then call `Update` instead of patching. It's indeed a bit reinventing the wheel if the SSA would work out of box.

**Comment by muvaf** [comment]
I just gave it a shot. Added an applicator to crossplane-runtime in https://github.com/crossplane/crossplane-runtime/pull/358 that uses server-side apply as described [here](https://github.com/kubernetes-sigs/controller-runtime/issues/347).

First, I wanted to reproduce the behavior with what @ulucinar provided. Just needed to add the following to give Crossplane permissions to work with the CRD:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: add-crd-permissions
  labels:
    crossplane.io/scope: "system"
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - xp.test.com
    resources:
      - myresources
    verbs:
      - '*'
```

Then I applied the claim and went ahead and `kubectl edit`ed the following managed resource:
```yaml
spec:
  forProvider:
    bArr:
    - targetSelector:
        matchLabels:
          key2: testName
```
to be like the following:
```yaml
spec:
  forProvider:
    bArr:
    - targetRefs:
      - name: ola 
      targetSelector:
        matchLabels:
          key2: testName
```

Then I confirmed that in the next reconciliation, the `targetRefs` field is gone. Then I shut down Crossplane pod and started my local Crossplane that uses the new server-side applicator, only needed to change [this line](https://github.com/crossplane/crossplane/blob/b0437b7/internal/controller/apiextensions/composite/reconciler.go#L320) after making it use my local crossplane-runtime from [this draft PR](https://github.com/crossplane/crossplane-runtime/pull/358).

Once it's back up, unfortunately, I got the same behavior. Please do check my code to see if I used SSA properly. If it's correct and we're sure it doesn't work for us, we can start working on a client patching approach implemented as another `Applicator`.

**Comment by muvaf** [comment]
I run another experiment today with the OpenAPI markers. In SSA (it doesn't work with client-side), you can designate a field to be the identifier of the array item and I did that by adding another field called `index` to the list above. The schema became the following for `bArr` field:
```yaml
bArr:
  items:
    properties:
      index:
        type: integer
      targetRefs: ...
      targetSelector: ...
      targets: ...
    type: object
    required: ["index"]
  type: array
  x-kubernetes-list-type: map
  x-kubernetes-list-map-keys: ["index"]
```

Then in the `Composition` template I assigned `0` to the `index` of the first element. It worked. When I added `targetRefs: [{name: "ola"}]` to the `0`th element of the array, it didn't get erased because SSA treated the list as a map by using `index` as key, hence instead of replacing the list it applied the patches of each element to their corresponding in the api-server. When I used our classic patching applicator, the additional properties weren't effective, they only worked with SSA.

What I'm wondering now is whether we can get away by having `x-kubernetes-list-map-keys` use the index of the item to identify it so that we don't have to add additional field to every array item struct. Just asked on [Kubernetes Slack](https://kubernetes.slack.com/archives/C0EG7JC6T/p1664442841067319).
