### ISSUE TITLE
Consider removing `aggregationRule` to support working in restricted environments

### ISSUE THREAD

**Issue by Piotr1215** [crossplane/crossplane#3339]
### What problem are you facing?

Crossplane requires admin privileges on the crossplane service account due to

```yaml
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      [rbac.crossplane.io/aggregate-to-crossplane](http://rbac.crossplane.io/aggregate-to-crossplane): "true"
```
This prevents Crossplane from working in restricted environments.

### How could Crossplane help solve your problem?

Remove the `aggregationRule` to enable Crossplane to work in restricted environments.
