### ISSUE TITLE
Deprecate `fromConnectionSecretKey` in `Composition`?

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3361]
### What problem are you facing?

Crossplane connection details were originally hardcoded to be Kubernetes Secrets, but we now have alpha support for secret stores that allow you to write them to other stores such as Vault. To that end we've started replacing references to "connection secrets" with "connection details" to distinguish them from Kubernetes Secrets.

Currently the documentation for the Composition type has the following example:

```yaml
    # You can include connection details to propagate from this CloudSQLInstance
    # up to the XPostgreSQLInstance XR (and then on to the PostgreSQLInstance
    # claim). Remember that your XRD must declare which connection secret keys
    # it supports.
    connectionDetails:
    - name: hostname
      fromConnectionSecretKey: hostname
```

I believe `fromConnectionSecretKey` means "from the connection secret of the composed resource", but folks using a different store may not have a secret.

### How could Crossplane help solve your problem?

We could find a more general replacement for `fromConnectionSecretKey` (perhaps just `fromKey`?), and mark the `fromConnectionSecretKey` as deprecated.
