### ISSUE TITLE
field publishConnectionDetailsTo is dependant on writeConnectionSecretToRef

### ISSUE THREAD

**Issue by asajoshi** [crossplane/crossplane#3399]
### What happened?
- Installed vault as external-secret-store as per [crossplane-vault-doc](https://crossplane.io/docs/v1.9/guides/vault-as-secret-store.html )(followed until step [install_configure_crossplane](https://crossplane.io/docs/v1.9/guides/vault-as-secret-store.html#install-and-configure-crossplane))

- Installed provider-aws instead of gcp

- Created a simple s3 composition, claim and XRD yaml files.

- When field **writeConnectionSecretToRef** is disabled in s3-XR.yaml, only composite secret (unnamed) get created in vault with no data . 
<img width="488" alt="image" src="https://user-images.githubusercontent.com/113517017/196883751-f0cdbb0a-cd0f-4c7a-bfb7-dcc18f783bdb.png">

- When field  **writeConnectionSecretToRef** is  enabled in s3-XR.yaml, both composite and claim secrets get created and fields endpoint and region get propagated to those secrets.
- why is this field necessary for **publishConnectionDetailsTo** to work?? According to the [design document](https://github.com/crossplane/crossplane/blob/master/design/design-doc-external-secret-stores.md), two fields can behave separately and the requirement of **writeConnectionSecretToRef** this field is not mentioned anywhere.

### How can we reproduce it?

provider_controller_config.yaml
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: vault-config
  #annotations:
    #eks.amazonaws.com/role-arn: arn:aws:iam::XXX:XXX
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
    - --enable-external-secret-stores
  metadata:
    annotations:
      vault.hashicorp.com/agent-inject: \"true\"
      vault.hashicorp.com/agent-inject-token: \"true\"
      vault.hashicorp.com/role: crossplane
      vault.hashicorp.com/agent-run-as-user: \"2000\"
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:v0.32.0
  controllerConfigRef:
    name: vault-config

```

storeconfig_for_aws.yaml
```
apiVersion: aws.crossplane.io/v1alpha1
kind: StoreConfig
metadata:
  name: vault
spec:
  type: Vault
  defaultScope: team-a
  vault:
    server: http://vault.vault-system:8200
    mountPath: secret/
    version: v2
    auth:
      method: Token
      token:
        source: Filesystem
        fs:
          path: /vault/secrets/token

```

storeconfig_for_crossplane.yaml
```
apiVersion: secrets.crossplane.io/v1alpha1
kind: StoreConfig
metadata:
  name: vault
spec:
  type: Vault
  defaultScope: team-a
  vault:
    server: http://vault.vault-system:8200
    mountPath: secret/
    version: v2
    auth:
      method: Token
      token:
        source: Filesystem
        fs:
          path: /vault/secrets/token

```

s3-claim.yaml 
```
apiVersion: example.org/v1alpha1
kind: S3  # must match the composite resource name
metadata:
  name: s3buckettestbyasa
  namespace: team-a
spec:
  compositionSelector:
    matchLabels:
      crossplane.io/xrd: xs3s.example.org  # must match the labels in XR.yaml
      provider: aws
  parameters:
    bucketName: "x125testbyasa"
  publishConnectionDetailsTo:
    name: mys3connection
    metadata:
      labels:
        environment: prod
        team: team-a
    configRef:
      name: vault
```

s3-XR.yaml
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3.example.org # <name.group>
  labels:
    crossplane.io/xrd: xs3s.example.org  # name_plural.group
    provider: aws
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: vault
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XS3
  patchSets:
    - name: metadata
      patches:
        - fromFieldPath: metadata.labels
  resources:
    - name: s3BucketTest
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: crossplane-test-by-aj
          namespace: crossplane-system
        spec:
          forProvider:
            acl: private
            locationConstraint: us-west-2
            versioningConfiguration:
              status: Enabled
          providerConfigRef:
            name: default
          #writeConnectionSecretToRef:
            #name: s3-connection-with-oldparam
            #namespace: team-a
      connectionDetails:
          - fromConnectionSecretKey: endpoint
          - fromConnectionSecretKey: region
```

s3-XRD.yaml
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3s.example.org
  labels:
    cluster-owner: team-app
spec:
  group: example.org
  names:
    kind: XS3
    plural: xs3s
  claimNames:
    kind: S3
    plural: s3s
  connectionSecretKeys:
    - endpoint
    - region
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    bucketName:
                      description: The name of the bucket.
                      type: string
                  required:
                    - bucketName
              required:
                - parameters
            status:
              type: object
              properties:
                bucketName:
                  description: Name of the s3 bucket
                  type: string

```

### What environment did it happen in?
Crossplane version: 1.9.1
OS: Mac
kubectl version: 
   Client Version: v1.21.13
   Server Version: v1.22.13-eks-15b7512
cloud provider: aws 
crossplane/provider-aws:v0.32.0

**Comment by negz** [comment]
CC @turkenh

**Comment by turkenh** [comment]
To build connection secrets for composites/claims, MRs should persist their connection details using either `writeConnectionSecretToRef` and/or the new  `publishConnectionDetailsTo` field. In other words, composite/Claim controllers fetches connection details of composed MRs to build connection secrets. 

If we don't configure our MRs to persist their connection details using `writeConnectionSecretToRef` and/or the new  `publishConnectionDetailsTo` field, there is no way a claim/composite controller to get that data.

So, this is how connection secrets of composites/claims work in general and not something specific to `publishConnectionDetailsTo`. I would suggest you to be consistent and use `publishConnectionDetailsTo` by changing your composition as below:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3.example.org # <name.group>
  labels:
    crossplane.io/xrd: xs3s.example.org  # name_plural.group
    provider: aws
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: vault
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XS3
  patchSets:
    - name: metadata
      patches:
        - fromFieldPath: metadata.labels
  resources:
    - name: s3BucketTest
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: crossplane-test-by-aj
          namespace: crossplane-system
        spec:
          forProvider:
            acl: private
            locationConstraint: us-west-2
            versioningConfiguration:
              status: Enabled
          providerConfigRef:
            name: default
+         publishConnectionDetailsTo:
+           name: s3-connection-with-oldparam
+           configRef:
+             name: vault
      connectionDetails:
          - fromConnectionSecretKey: endpoint
          - fromConnectionSecretKey: region
```
