### ISSUE TITLE
Support composition revision selectors

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/crossplane#3415]
### What problem are you facing?
Composition revision is an alpha feature that we target to promote with this [issue](https://github.com/crossplane/crossplane/issues/2656). Currently,  composition revision names are generated automatically. Therefore it’s not convenient to use them with `compositionRevisionRef` and GitOps tools like ArgoCD or Flux. Even if we merge this [PR](https://github.com/crossplane/crossplane/pull/3391) to have consistent names between multiple clusters, calculating the hashes beforehand and hardcoding the names in claims/composites are not user-friendly. Therefore, implementing composition revision selectors is discussed in several issues like https://github.com/crossplane/crossplane/issues/2656 and https://github.com/crossplane/crossplane/issues/2544.

In this issue, we’d like to summarize some of the use cases which utilize composition selectors and propose a design:

1. As a platform builder, I’d like to set a specific composition revision in my claims/composites (e.g., `version: v0.1.0`) to manage upgrades easily. 
2. As a platform builder, I’d like to test the `alpha` composition with a set of canary claims/composites (e.g., `channel: alpha`) and then mark the composition as `stable` to update the more critical ones.

In both cases, we do not want to interact with composition revisions directly. Because the lifecycle of composition revisions is managed by the composition controller. Instead, we want to update the label of the composition and propagate all of its labels to the revision in the creation time. This means a new composition revision needs to be created each time we update the labels. Right now, composition revision creation is triggered only by compositions’ spec updates. If we want to avoid this change, we can discuss the revision labeling option. 

For the second use case, we may want to assign the latest revision with the `stable` label to automatically update our claims/composites. To track this information, it's proposed to increment the revision number even if the existing composition was created before. In this way, we can know the creation order of revisions with different labels. 

An example can be found below to visualize the second scenario more easily:

1) Create a simple composition that has a single spec field `appVersion`. 

<details>
  <summary>composition</summary>
  
  ```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    channel: alpha
  name: mycomp.aws.platformref.upbound.io
spec:
    appVersion: v0.1.0
```
</details>

2) Corresponding composition revision will be created automatically by the composition controller:
 <details>
  <summary>composition-revision</summary>
  
  ```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositionRevision
metadata:
  labels:
    crossplane.io/composition-name: mycomp.aws.platformref.upbound.io
    crossplane.io/composition-spec-hash: 2a576a29cd87e20
    channel: alpha
  name: mycomps.aws.platformref.upbound.io-2a576
  ...
spec:
  revision: 1
  resources:
  - base:
      apiVersion: …
      kind: ..
      spec:
        forProvider:
          appVersion: v0.1.0
  ...
```

</details>

3) Create a claim which selects composition revisions in the `alpha` channel:
 <details>
  <summary>claim</summary>

```yaml
apiVersion: aws.platformref.upbound.io/v1alpha1
kind: MyApp
metadata:
  name: myAppDev
spec:
  compositionRevisionSelector:
    matchLabels:
      channel: alpha
```
</details>

4) Update the composition to mark it as `stable` after becoming confident about `appVersion: v0.1.0`:
 <details>
  <summary>composition</summary>
  
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    channel: stable
  name: mycomp.aws.platformref.upbound.io
spec:
  appVersion: v0.1.0
```
</details>

5) Following composition revision will be created with the same spec but a different label:
 <details>
  <summary>composition-revision</summary>
  
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositionRevision
metadata:
  labels:
    crossplane.io/composition-name: mycomp.aws.platformref.upbound.io
    crossplane.io/composition-spec-hash: df131fec4e53e1af
    channel: stable
  name: mycomps.aws.platformref.upbound.io-df131
  ...
spec:
  revision: 2
  resources:
  - base:
      apiVersion: …
      kind: ..
      spec:
        forProvider:
          appVersion: v0.1.0
  ...
```
</details>

6) Update the composition to test a newer `appVersion` by changing both the label and the spec. 
 <details>
  <summary>composition</summary>
  
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    channel: alpha
  name: mycomp.aws.platformref.upbound.io
spec:
  appVersion: v0.2.0
  ...
```
 </details>
 
7) The update above will trigger the creation of the following composition revision and will update the claims which are listening to the `alpha` channel.
 <details>
  <summary>composition-revision</summary>
  
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositionRevision
metadata:
  labels:
    crossplane.io/composition-name: mycomp.aws.platformref.upbound.io
    crossplane.io/composition-spec-hash: efbd77ff84831d2e
    channel: alpha
  name: mycomps.aws.platformref.upbound.io-efbd7
  ...
spec:
  revision: 3
  resources:
  - base:
      apiVersion: …
      kind: ..
      spec:
        forProvider:
          appVersion: v0.2.0
  ...
```
</details>

It's worth mentioning that, in step 6, updating the composition's label and spec at the same time has different effects than updating the label first and then the spec. In the second option, we end up having the same composition as the first step which will cause updating the revision number of the composition revision at step 2.  

Another important note is, unlike other reference solvers we have on Crossplane, we need to resolve `compositionRevison` field in each reconciliation. Otherwise, we cannot support the channel scenario.
