### ISSUE TITLE
Add MR mocking to support automated tests by crossplane users

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/crossplane#3417]
### What problem are you facing?

I've been adopting a test-driven-approach to my crossplane composition using kuttl, ytt and kapp controller, so every change is triggering a test job with good test coverage:
- kuttl assertions on XR and MR, and XRCs and their connection secrets
- E2E tests with an app consummong XRCs secrets

I'm now reaching a phase where this TDD approach is blocked by too slow response times from XR (GCP CloudSql in my case), and financial/environmental costs of having XR indeed reconcile.

### How could Crossplane help solve your problem?

My problem would be solved if crossplane would introduce XR mock capability: ability to tell XR to not reconcile but instead move to a predicatable status and populate a predictable connection secret content.

Something along these lines:

```yaml
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: cloudsql
spec:
  # Tell crossplane controllers to not reconcile this resource through providers, instead reconcile to specified mock state
  providerMockedState: 
    status: # Status will converge to the following state
      atProvider:
        state: RUNNABLE
      conditions:
        - reason: Available
          status: "True"
          type: Ready
        - reason: ReconcileSuccess
          status: "True"
          type: Synced

    #connection secret would be created and filled with the following inlined content (exclusive with connectionSecretContentRef)
    connectionSecretContent: 
      connectionName: my-gcp-project:europe-west1:sample-db-47thw-7nvrg
      endpoint: 10.x.y.z
      password: xxx
      # [...]

    #connection secret would be created and filled with the data from the specified secret reference (exclusive with connectionSecretContent)
    connectionSecretContentRef: 
      name: existing-secret-with-desired-content
      namespace: typical-namespace-for-my-mr-cnx-secrets

  forProvider:
[...]
```

Such a mocking behavior would crossplane users ability to run tests covering most of their authored crossplane XRD and composition:
* cheaper
* much faster 
* with incresead coverage: e.g. being able to test error conditions

I would likely leverage this mocking behavior when asked by XRC spec field such as `dry-run` (that would not be surfaced in the XRD openapi schema.)

**Comment by turkenh** [comment]
I am wondering if this could be done with an external component rather than XP itself 🤔 
Imagine something like `provider-mock` where you instruct the provider (via Custom Resources) on which MR should be watched and what to do when they are created with a similar schema you shared above.

**Comment by bobh66** [comment]
This might be an interesting application of crisscross - you could have an external process running test/mock providers and register the resources with crisscross instead of installing the "real" providers.  I started work on a pluggable python module that would receive HTTP requests from crisscross and return the desired response formats, executing different class implementations of the reconciliation methods based on the resource in the request, but it's still very much pre-alpha.  I can see cases where you could have test modules that would respond with the desired data for specific resource types or resource names.

**Comment by gberche-orange** [comment]
thanks @turkenh @bobh66 for your responses, and sorry for my late response, I was out of office past 2 weeks.

> I am wondering if this could be done with an external component rather than XP itself 🤔
Imagine something like provider-mock where you instruct the provider (via Custom Resources) on which MR should be watched and what to do when they are created with a similar schema you shared above.

Can you please clarify whether you mean 
- a) the Composition would still reference a real provider MR (e.g. `apiVersion: database.gcp.crossplane.io/v1beta1, kind: CloudSQLInstance`) and that an another controller brought by `provider-mock` from would update the CloudSQLInstance status and create the cnx secret ? How would we prevent race conditions from real provider (e.g. `provider-gcp`) and `provider-mock`, as well as real provider still trying to provision real resource (e.g. a CloudSql instance)
- b) the Composition would instead Reference a `provider-mock` MR  (e.g. `apiVersion: database.gcp.crossplane.io/mock, kind: CloudSQLInstance`, note the `mock` api version instead of `v1beta1`) only watched by the `provider-mock`  controller ?

If you mean b), then let's try to continue the analogy of crossplance composition authoring with traditional programming practices that have brought associated testing practices, including mocks (part of doubles)

The [XUnit Test Patterns](http://xunitpatterns.com/index.html) book [introduces doubles](http://xunitpatterns.com/Test%20Double.html) as 

> When we are writing a test in which we cannot (or chose not to) use a real [depended-on component (DOC)](http://xunitpatterns.com/DOC.html), we can replace it with a Test Double. The Test Double doesn't have to behave exactly like the real [DOC](http://xunitpatterns.com/DOC.html); it merely has to provide the same API as the real one so that the SUT thinks it is the real one!

This is supported by the following goals, principles and smells summarized in the screenshot below:

![image](https://user-images.githubusercontent.com/4748380/200284992-3467b7f2-ef35-4fef-8e57-4f4dc0408088.png)

In our context of automated tests for crossplane composition authoring, the SUT (system under test) is the XRD, and Composition. 

I worry that using a dedicated crossplane provider `provider-mock` (possibly implemented by [crisscross](https://github.com/crossplane-contrib/crisscross)) would break the followings :
* principle `don't modify the SUT`: the composition would needs to change to refer to the  `provider-mock`  MRs instead of `provider-gcp` MRs
* code smells `Test logic in production`: the composition will need to use conditional logic to reference the  the  `provider-mock`  MRs instead of `provider-gcp` MRs. I'm not clear how this is currently possible in the composition specs. This would likely require to create a distinct "test" composition that would share part of its code with the "SUT" production code

This is why I had originally imagined crossplane built-in support for injecting mocks in the MR syntax.

I now wonder whether you you instead meant:

c) the Composition would still reference a real provider MR (e.g. `apiVersion: database.gcp.crossplane.io/v1beta1, kind: CloudSQLInstance`) and the implementation of `provider-gcp` would not provision a CloudSqlInstance if it had detected a mock CR say  `apiVersion: mock.crossplane.io/v1beta1, kind: ManagedResourceMock` that instructs to return a specified mocked response for a given MR reference ?

Something like the following

```yaml
apiVersion: mock.crossplane.io/v1beta1
kind: ManagedResourceMock
metadata:
  name: cloudsql-mock
spec:
  # Do not reconcile the referenced resource with real-world, instead reconcile to specified mock state
  managedResourceSelector:
    matchKind:
      apiVersion: database.gcp.crossplane.io/v1beta1
      kind: CloudSQLInstance
    matchLabels:
      crossplane.io/claim-name: sample-static-db

  # Specify the status to set in the MR
  providerMockedState:
    status: # Status will converge to the following state
      atProvider:
        state: RUNNABLE
      conditions:
        - reason: Available
          status: "True"
          type: Ready
        - reason: ReconcileSuccess
          status: "True"
          type: Synced

    #connection secret would be created and filled with the following inlined content (exclusive with connectionSecretContentRef)
    connectionSecretContent:
      connectionName: my-gcp-project:europe-west1:sample-db-47thw-7nvrg
      endpoint: 10.x.y.z
      password: xxx
      # [...]

    #connection secret would be created and filled with the data from the specified secret reference (exclusive with connectionSecretContent)
    connectionSecretContentRef:
      name: existing-secret-with-desired-content
      namespace: typical-namespace-for-my-mr-cnx-secrets
```


That would be a much better approach since the SUT (XRD + Composition) would not be modified at all, and the test code (mock behavior specs) would only be present in the test environment.

Can you envision a technical implementation that would not require changes to providers to support such mocks CRs?
