### ISSUE TITLE
Tag deleted from claim spec is added back

### ISSUE THREAD

**Issue by ulucinar** [crossplane/crossplane#3421]
### What happened?

We have observed an issue with @stevendborrelli where a tag is deleted from a map in a claim spec parameter, and it gets added back to the claim. Please see below for an example XRD, claim and composition.

After you remove the tag key from the claim’s `spec.parameters.tags` map (and expect first the XR’s corresponding map to be updated, and then the MR’s `spec.forProvider.tags` map to be replaced because of the composition’s relevant patch), the removed key gets reinserted by the [`claim.APIClaimConfigurator`](https://github.com/crossplane/crossplane/blob/d5c522e9b29b2b1d050c9181ddfa4608a3725ebb/internal/controller/apiextensions/claim/reconciler.go#L490), which configures a claim using the associated XR. At this point, the tag key is missing (from `spec.parameters.tags`) in the claim but it still exists in the XR. The `APIClaimConfigurator` merges the spec of the XR into the claim’s spec using `mergo.Merge`. And  `mergo.Merge` puts the missing key in the claim’s `spec.parameters.tags` from the XR’s map (which still contains it) while merging these maps.

There is no race condition involved. The claim reconciler uses a `resource.APIPatchingApplicator` to patch the XR via a JSON-merge patch but this can not remove the key (map not replaced, there is now a missing key in a map, which has no effect). However, `resource.APIPatchingApplicator` [fetches the current spec of the XR](https://github.com/crossplane/crossplane-runtime/blob/fa5545f26b0458d4680502cfc0415048318baa85/pkg/resource/api.go#L136) and puts it into the same object that will later be used to [configure the claim](https://github.com/crossplane/crossplane/blob/d5c522e9b29b2b1d050c9181ddfa4608a3725ebb/internal/controller/apiextensions/claim/reconciler.go#L490) (via the `APIClaimConfigurator` as explained above).
Thus the claim acquires back the deleted key.

### How can we reproduce it?

Using the following XRD, claim and composition, please delete the `test` key from claim's (`AWSGlueTrigger`) `spec.parameters.tags`:

```yaml

apiVersion: dataservices.lmig.com/v1alpha1
kind: AWSGlueTrigger
metadata:
  namespace: upbound-system
  name: ateam-glue-test-trigger-instance1
  annotations:
    crossplane.io/external-name: ateam-glue-trigger-tags-test
spec:
  parameters:
    description: "test trigger for A-team test 2"
    workflowName: "a-team-workflow1"
    type: ON_DEMAND
    actions:
      - jobName: "ateam-glue-name1"
    tags:
      deployment_guid: "0000-9-9-99999"
      lm-troux_uid: "0000-9-9-99999"
      test: new_tag
  compositionSelector:
    matchLabels:
      purpose: glue-trigger
      provider: aws

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gds-glue-trigger-pattern
  labels:
    crossplane.io/xrd: xawsgluetriggers.dataservices.lmig.com
    purpose: glue-trigger
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: dataservices.lmig.com/v1alpha1
    kind: XAWSGlueTrigger
  writeConnectionSecretsToNamespace: default
  resources:
  - name: glue-trigger
    base:
      apiVersion: glue.aws.upbound.io/v1beta1
      kind: Trigger
      spec:
        forProvider:
          region: us-east-1
          tags: {}
    patches:
      - fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
        toFieldPath: "metadata.annotations[crossplane.io/external-name]"
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.description
        toFieldPath: spec.forProvider.description
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.workflowName
        toFieldPath: spec.forProvider.workflowName
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.type
        toFieldPath: spec.forProvider.type
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.actions
        toFieldPath: spec.forProvider.actions
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.predicate
        toFieldPath: spec.forProvider.predicate
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.startOnCreation
        toFieldPath: spec.forProvider.startOnCreation
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.tags
        toFieldPath: spec.forProvider.tags


---

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xawsgluetriggers.dataservices.lmig.com
  labels:
    purpose: glue-trigger
    provider: aws
spec:
  defaultCompositionRef:
    name: gds-glue-trigger-pattern
  group: dataservices.lmig.com
  names:
    kind: XAWSGlueTrigger
    plural: xawsgluetriggers
  claimNames:
    kind: AWSGlueTrigger
    plural: awsgluetriggers
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    description:
                      type: string
                    workflowName:
                      type: string
                    startOnCreation:
                      type: boolean
                    type:
                      type: string
                      enum: [CONDITIONAL, ON_DEMAND, SCHEDULED]
                    actions:
                      type: array
                      items:
                        type: object
                        properties:
                          jobName:
                            type: string
                          arguments:
                            type: object
                            additionalProperties:
                              type: string
                    predicate:
                      type: array
                      items:
                        type: object
                        properties:
                          logical:
                            type: string
                            enum: [AND, ANY]
                          conditions:
                            type: array
                            items:
                              type: object
                              properties:
                                operator:
                                  type: string
                                jobName:
                                  type: string
                                state:
                                  type: string
                                  enum: [SUCCEEDED, STOPPED, TIMEOUT, FAILED]
                        required:
                          - conditions
                    tags:
                      description: Tags map required for comliance
                      type: object
                      additionalProperties:
                          type: string
                  required:
                    - actions
                    - tags
                    - type
              required:
                - parameters
```

### What environment did it happen in?
Crossplane version: `v1.10.0`
