### ISSUE TITLE
[Crossplane v1.10.0] Package manager constantly enqueues reconciles due to unstable object refs in status

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#3425]
### What happened?

In https://github.com/crossplane/crossplane/pull/3176, the package manager's revision reconciler was updated to concurrently install resources in a given package. After doing so, the reconciler updates the status of the revision with a list of `objectRefs` for everything it installed.

```yaml
...
    objectRefs:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: accelerators.globalaccelerator.aws.upbound.io
      uid: f1e69f55-55c3-4cfc-ad35-0a22a8883293
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: accesskeys.iam.aws.upbound.io
      uid: 222e9f0e-1c78-4a82-a008-327477b8e43b
...
```

Because the installation is now concurrent, the ordering of this list is non-deterministic, meaning that it is likely for it to change on every reconcile. This causes another reconcile to be enqueued over and over again, which leads to constant CRD updates.

### How can we reproduce it?

Configure kind:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        # enable auditing flags on the API server
        extraArgs:
          audit-log-path: /var/log/kubernetes/kube-apiserver-audit.log
          audit-policy-file: /etc/kubernetes/policies/audit-policy.yaml
        # mount new files / directories on the control plane
        extraVolumes:
          - name: audit-policies
            hostPath: /etc/kubernetes/policies
            mountPath: /etc/kubernetes/policies
            readOnly: true
            pathType: "DirectoryOrCreate"
          - name: "audit-logs"
            hostPath: "/var/log/kubernetes"
            mountPath: "/var/log/kubernetes"
            readOnly: false
            pathType: DirectoryOrCreate
  # mount the local file on the control plane
  extraMounts:
  - hostPath: ./audit-policy.yaml
    containerPath: /etc/kubernetes/policies/audit-policy.yaml
    readOnly: true
```

Create kind cluster:
```
kind create cluster --config kind-config.yaml
```

Run Crossplane with debug logging:
```
🤖 (crossplane) go run ./cmd/crossplane/ core start --debug --cache-dir="./cache"
```

Install a package:
```
up ctp provider install xpkg.upbound.io/upbound/provider-aws:v0.18.0
```

View regular reconciles for provider revisions:
```
1.6672378642638264e+09	DEBUG	crossplane	Reconciling	{"controller": "packages/providerrevision.pkg.crossplane.io", "request": "/upbound-provider-aws-80ff1ee1c639"}
1.6672378779715407e+09	DEBUG	crossplane.events	Normal	{"object": {"kind":"ProviderRevision","name":"upbound-provider-aws-80ff1ee1c639","uid":"2deb92e5-6900-4ce6-aec8-e09d58a06623","apiVersion":"pkg.crossplane.io/v1","resourceVersion":"8243"}, "reason": "SyncPackage", "message": "Successfully configured package revision"}
...
```

Observe audit log:

`🤖 (crossplane) docker exec kind-control-plane tail +1f /var/log/kubernetes/kube-apiserver-audit.log `
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"25f4f7f6-372f-420f-950b-922bd052ec6f","stage":"RequestReceived","requestURI":"/apis/apiextensions.k8s.io/v1/customresourcedefinitions/vpcendpointserviceallowedprincipals.ec2.aws.upbound.io?dryRun=All","verb":"update","user":{"username":"kubernetes-admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.18.0.1"],"userAgent":"crossplane/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"customresourcedefinitions","name":"vpcendpointserviceallowedprincipals.ec2.aws.upbound.io","apiGroup":"apiextensions.k8s.io","apiVersion":"v1"},"requestReceivedTimestamp":"2022-10-31T17:37:46.406958Z","stageTimestamp":"2022-10-31T17:37:46.406958Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"25f4f7f6-372f-420f-950b-922bd052ec6f","stage":"ResponseComplete","requestURI":"/apis/apiextensions.k8s.io/v1/customresourcedefinitions/vpcendpointserviceallowedprincipals.ec2.aws.upbound.io?dryRun=All","verb":"update","user":{"username":"kubernetes-admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.18.0.1"],"userAgent":"crossplane/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"customresourcedefinitions","name":"vpcendpointserviceallowedprincipals.ec2.aws.upbound.io","apiGroup":"apiextensions.k8s.io","apiVersion":"v1","resourceVersion":"1354"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2022-10-31T17:37:46.406958Z","stageTimestamp":"2022-10-31T17:37:46.416056Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"1f9ef001-ed08-420c-aeff-93537b2f1889","stage":"RequestReceived","requestURI":"/apis/apiextensions.k8s.io/v1/customresourcedefinitions/vpcendpointservices.ec2.aws.upbound.io?dryRun=All","verb":"update","user":{"username":"kubernetes-admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.18.0.1"],"userAgent":"crossplane/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"customresourcedefinitions","name":"vpcendpointservices.ec2.aws.upbound.io","apiGroup":"apiextensions.k8s.io","apiVersion":"v1"},"requestReceivedTimestamp":"2022-10-31T17:37:46.427974Z","stageTimestamp":"2022-10-31T17:37:46.427974Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"541f4ae0-a8fc-4f81-957f-d5b9da7d01aa","stage":"RequestReceived","requestURI":"/apis/apiextensions.k8s.io/v1/customresourcedefinitions/vpcendpointsubnetassociations.ec2.aws.upbound.io?dryRun=All","verb":"update","user":{"username":"kubernetes-admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.18.0.1"],"userAgent":"crossplane/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"customresourcedefinitions","name":"vpcendpointsubnetassociations.ec2.aws.upbound.io","apiGroup":"apiextensions.k8s.io","apiVersion":"v1"},"requestReceivedTimestamp":"2022-10-31T17:37:46.447049Z","stageTimestamp":"2022-10-31T17:37:46.447049Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"1f9ef001-ed08-420c-aeff-93537b2f1889","stage":"ResponseComplete","requestURI":"/apis/apiextensions.k8s.io/v1/customresourcedefinitions/vpcendpointservices.ec2.aws.upbound.io?dryRun=All","verb":"update","user":{"username":"kubernetes-admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.18.0.1"],"userAgent":"crossplane/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"customresourcedefinitions","name":"vpcendpointservices.ec2.aws.upbound.io","apiGroup":"apiextensions.k8s.io","apiVersion":"v1","resourceVersion":"1357"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2022-10-31T17:37:46.427974Z","stageTimestamp":"2022-10-31T17:37:46.453321Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"7a222833-d5fd-4d2e-9e99-87210af54c69","stage":"RequestReceived","requestURI":"/apis/apiextensions.k8s.io/v1/customresourcedefinitions/vpcipv4cidrblockassociations.ec2.aws.upbound.io?dryRun=All","verb":"update","user":{"username":"kubernetes-admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.18.0.1"],"userAgent":"crossplane/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"customresourcedefinitions","name":"vpcipv4cidrblockassociations.ec2.aws.upbound.io","apiGroup":"apiextensions.k8s.io","apiVersion":"v1"},"requestReceivedTimestamp":"2022-10-31T17:37:46.466648Z","stageTimestamp":"2022-10-31T17:37:46.466648Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"541f4ae0-a8fc-4f81-957f-d5b9da7d01aa","stage":"ResponseComplete","requestURI":"/apis/apiextensions.k8s.io/v1/customresourcedefinitions/vpcendpointsubnetassociations.ec2.aws.upbound.io?dryRun=All","verb":"update","user":{"username":"kubernetes-admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.18.0.1"],"userAgent":"crossplane/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"customresourcedefinitions","name":"vpcendpointsubnetassociations.ec2.aws.upbound.io","apiGroup":"apiextensions.k8s.io","apiVersion":"v1","resourceVersion":"1360"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2022-10-31T17:37:46.447049Z","stageTimestamp":"2022-10-31T17:37:46.468694Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
...
```

### What environment did it happen in?
Crossplane version: v1.10.0
