### ISSUE TITLE
RBAC permissions issue in OpenShift

### ISSUE THREAD

**Issue by el-mail** [crossplane/crossplane#3443]
### What happened?
I've got a permission issue that seems to only apply to OpenShift. 
Similar issues here:
https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/434
https://github.com/spotahome/redis-operator/issues/98
https://github.com/jaegertracing/jaeger-operator/issues/461

### How can we reproduce it?
1. Run crossplane on openshift
2. Try to change the version in `Provider` and `ControllerConfig`
3. Note errors logs on `crossplane` and `crossplane-rbac-manager`: 

`DEBUG	crossplane	cannot apply ClusterRole	{"controller": "rbac/providerrevision.pkg.crossplane.io", "request": "/provider-aws-edfa6e79bd65", "uid": "77a14918-0cab-4c77-9bd1-04dc085682f2", "version": "1592953204", "name": "provider-aws-edfa6e79bd65", "role-name": "crossplane:provider:provider-aws-edfa6e79bd65:aggregate-to-edit", "role-name": "crossplane:provider:provider-aws-edfa6e79bd65:aggregate-to-view", "role-name": "crossplane:provider:provider-aws-edfa6e79bd65:system", "error": "cannot update object: clusterroles.rbac.authorization.k8s.io \"crossplane:provider:provider-aws-edfa6e79bd65:system\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}`

`ERROR	crossplane.controller.rbac/providerrevision.pkg.crossplane.io	Reconciler error	{"reconciler group": "pkg.crossplane.io", "reconciler kind": "ProviderRevision", "name": "provider-aws-edfa6e79bd65", "namespace": "", "error": "cannot apply ClusterRole: cannot update object: clusterroles.rbac.authorization.k8s.io \"crossplane:provider:provider-aws-edfa6e79bd65:system\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}`

### What environment did it happen in?
Crossplane version: v1.10.1
$ oc version
Client Version: v4.2.0-alpha.0-1570-g3c85519
Kustomize Version: v4.5.4
Server Version: 4.10.13 (Openshift)
Kubernetes Version: v1.23.5+b463d71

**Comment by el-mail** [comment]
also error logs
```cannot render composed resource from resource template at index 1: cannot use dry-run create to name composed resource: User.iam.aws.crossplane.io "test-jrmg4-gxs8p" is invalid: spec.writeConnectionSecretToRef.name: Required value
cannot render composed resource from resource template at index 2: cannot use dry-run create to name composed resource: AccessKey.iam.aws.crossplane.io "test-jrmg4-rpm54" is invalid: spec.writeConnectionSecretToRef.name: Required value
cannot render composed resource from resource template at index 3: cannot use dry-run create to name composed resource: BucketPolicy.s3.aws.crossplane.io "test-jrmg4-sllnq" is invalid: spec.writeConnectionSecretToRef.name: Required value
cannot apply composed resource: cannot create object: buckets.s3.aws.crossplane.io "crossplane-test" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>```

**Comment by dlydiard** [comment]
I worked around this problem by creating:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-rbac-manager-openshift
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-rbac-manager-openshift
subjects:
  - kind: ServiceAccount
    name: rbac-manager
    namespace: upbound-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-rbac-manager-openshift
rules:
  - verbs:
      - update
    apiGroups: # new providers must be added to the role
      - pkg.crossplane.io
      - providerconfigs.aws.upbound.io
    resources:
      - '*/finalizers'
```

However, this problem also exists for the `provider-aws-(uid)` SA. Since the SA has a random suffix in the name, i'm not sure how to fix this. Is there a way to override the name of the SA that gets created by the Provider?

**Comment by dlydiard** [comment]
Update used:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-openshift
subjects:
  - kind: Group
    name: system:serviceaccounts
    namespace: upbound-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-openshift
rules:
  - verbs:
      - update
    apiGroups: # new providers must be added to the role
      - pkg.crossplane.io
      - aws.upbound.io
      - providerconfigs.aws.upbound.io
      - providerconfigusages.aws.upbound.io
      - rds.aws.upbound.io
      - s3.aws.upbound.io
    resources:
      - '*/finalizers'
```
This seemed to do the trick using the aws provider for s3/rds on OpenShift.

**Comment by chobostar** [comment]
I found some more issues with missing RBAC, so I decided to clarify the issue.

### What happened?

Crossplane rbac-manager doesn't support clusters with [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) plug-ins enabled. Because of missing `update` verb on `/finalizers` subresources.

As a result:
- rbac-manager unable to create roles inside namespaces
- new crossplane providers unable to get installed properly
- composite resources unable to be managed properly

### How can we reproduce it?

```bash
$ kind create cluster --config - <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          enable-admission-plugins: OwnerReferencesPermissionEnforcement
EOF

$ helm repo add crossplane-stable https://charts.crossplane.io/stable
$ helm repo update
$ helm upgrade --install crossplane crossplane-stable/crossplane --set rbacManager.args={'--debug'}
```
after pods are up, check logs:
```
$ kubectl logs deployment/crossplane-rbac-manager | grep -i error
1.6685820751909177e+09	DEBUG	crossplane	cannot apply Roles	{"controller": "rbac/namespace", "request": "/kube-node-lease", "uid": "c58ef92e-eab7-4ec3-a49d-854ce118c144", "version": "6", "name": "kube-node-lease", "role-name": "crossplane-admin", "error": "cannot create object: roles.rbac.authorization.k8s.io \"crossplane-admin\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
1.668582075291848e+09	ERROR	crossplane.controller.rbac/namespace	Reconciler error	{"reconciler group": "", "reconciler kind": "Namespace", "name": "kube-node-lease", "namespace": "", "error": "cannot apply Roles: cannot create object: roles.rbac.authorization.k8s.io \"crossplane-admin\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
1.668582075391143e+09	DEBUG	crossplane	cannot apply Roles	{"controller": "rbac/namespace", "request": "/kube-system", "uid": "52664d38-3555-4be0-b364-500a574fce07", "version": "4", "name": "kube-system", "role-name": "crossplane-admin", "error": "cannot create object: roles.rbac.authorization.k8s.io \"crossplane-admin\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```

### What environment did it happen in?

I believe it reproducible in every cluster with `enable-admission-plugins: OwnerReferencesPermissionEnforcement`, bea

---
Moreover, It might be not Crossplane's code issue or it could be intention, however:
1. ERROR messages aren't flushed to logs in default log level INFO. If you want to see ERROR, set `--debug` args.
2. Current [e2e tests](https://github.com/crossplane/crossplane/blob/3a40c4faa10f3001ddc47bf8c917239ccd18bad3/cluster/local/integration_tests.sh#L79-L148) check only successful deployment rollout, It doesn't check runtime issues, i.e. reconcile errors.

**Comment by chobostar** [comment]
> this problem also exists for the `provider-aws-(uid)` SA. Since the SA has a random suffix in the name, i'm not sure how to fix this. Is there a way to override the name of the SA that gets created by the `Provider`?

the fix is still not merged for it: https://github.com/crossplane/crossplane/pull/2880

Additional notes:
1. This wildcards usage:
```
    resources:
      - '*/finalizers'
```
 is against [best practices](https://kubernetes.io/docs/concepts/security/rbac-good-practices/#least-privilege):
```
Avoid providing wildcard permissions when possible, especially to all resources
```
2. Here
```
subjects:
  - kind: Group
    name: system:serviceaccounts
    namespace: upbound-system
```
 I believe correct subject should be:
```
subjects:
- kind: Group
  name: system:serviceaccounts:upbound-system
  apiGroup: rbac.authorization.k8s.io
```
according to [examples](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-binding-examples)

3. If I am not wrong, new ClusterRole for rbac-manager should have additional annotation:
```
    rbac.crossplane.io/aggregate-to-admin: "true"
    rbac.crossplane.io/aggregate-to-crossplane: "true"
```

**Comment by gberche-orange** [comment]
I'm also reproducing the problem in crossplane opensource version 1.10.1 on openshift 4.10.30 but I'm not what that triggered the problem since the [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) seems present by default in openshift since version 4.6, which is quite old now. 

```
$ oc version
Client Version: 4.10.25
Server Version: 4.10.30
Kubernetes Version: v1.23.5+012e945
```
@negz any idea of the root cause of the issue since I understand crossplane has been tested on openshift for a long time ?

**Comment by gberche-orange** [comment]
I've worked around the issue in the opensource version with

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-crossplane-full-finalizer-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*/finalizers"
    verbs:
      - "*"
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-crossplane-full-finalizer-role-binding
roleRef:
  kind: ClusterRole
  name: openshift-crossplane-full-finalizer-role
subjects:
- kind: ServiceAccount
  name: rbac-manager
  namespace: <<crossplane-installation-namespace>>
- kind: ServiceAccount
  name: crossplane
  namespace: <<crossplane-installation-namespace>>
```
