### ISSUE TITLE
ToComposite Patches are executed out-of-order

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#3454]
### What happened?

Composition patches are not executed in the order they are listed. 

All `ToComposite*` patches in Crossplane are not executed within the order they are listed. Given the following patch list:

```yaml
patches:
 - type: FromCompositeFieldPath # 1
 - type: ToCompositeFieldPath   # 2
 - type: FromCompositeFieldPath # 3
```

One would expect the execution order `1 - 2 - 3`. However,`ToComposite*` patches are executed only *after* the composed resources have been rendered *and* created on the cluster. This means the effective execution order is `1 - 3 - 2`.

AFAIK this behaviour is undocumented. To me, it feels like a design flaw as well.

https://github.com/crossplane/crossplane/blob/80b427dabfd3aba08865aaf8f41fc0ac62db0abb/internal/controller/apiextensions/composite/reconciler.go#L616

### How can we reproduce it?

See example above.

### What environment did it happen in?

Crossplane version: v1.10.0

**Comment by negz** [comment]
> However, ToComposite* patches are executed only after the composed resources have been rendered and created on the cluster.

Often `ToComposite` patches are used to patch data that doesn't exist until the "from" (composed) resource has been created - e.g. to copy status information from the composed resource to the composite. Given this constraint, how would you propose it should work instead?

**Comment by MisterMX** [comment]
I don't have an issue with the way these patches are used. The problem I see here is that the API does imply a specific order which isn't actually given. I've had multiple users complaining that there patches "don't work" because they expected their `ToComposite*` patches to be executed in the order the defined them.

To make this clearer in the API, there should be a designated field `patchesAfterApply` that removes this ambiguity:

```yaml
patches:
- type: FromCompositeFieldPath
- type: FromCompositeFieldPath
patchesAfterApply:
- type: ToCompositeFieldPath
- type: ToCompositeFieldPath
```
