### ISSUE TITLE
Updating XRC does not update the managed resource

### ISSUE THREAD

**Issue by thiagoabdo** [crossplane/crossplane#3457]
### What happened?
Updating a XRC list does not reflect in the managed resource 

### How can we reproduce it?

<details><summary>XRD:</summary>

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xobjectstorages.storage.example.io
spec:
  claimNames:
    kind: ObjectStorage
    plural: objectstorages
  group: storage.example.io
  names:
    kind: XObjectStorage
    plural: xobjectstorages
  connectionSecretKeys:
    - region
    - bucket-name
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: ObjectStorageSpec defines the desired state of ObjectStorage
              properties:
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value
                        provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - providerConfigName
                  - region
                  - tags
                  type: object
              required:
              - resourceConfig
              type: object
            status:
              description: ObjectStorageStatus defines the observed state of ObjectStorage
              properties:
                bucketName:
                  type: string
                bucketArn:
                  type: string
              type: object
          type: object
```

</details>

<details><summary>Composition:</summary>

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket.storage.example.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: storage.example.io/v1alpha1
    kind: XObjectStorage
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: s3bucket
      connectionDetails:
        - name: bucket-name
          fromConnectionSecretKey: endpoint
        - name: region
          fromConnectionSecretKey: region
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          providerConfigRef:
            name: aws-provider
          deletionPolicy: Delete
          forProvider:
            acl: private
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            tagging:
              tagSet:
                - key: owner
                  value: to_be_patched
                - key: created_by_crossplane
                  value: "true"
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tagging.tagSet
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.bucketName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.bucketArn
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.locationConstraint
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-s3bucket"
           
```

</details>

<details><summary>Claim:</summary>

```
apiVersion: storage.example.io/v1alpha1
kind: ObjectStorage
metadata:
  name: test-xplane2
spec:
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: test-xplane2-info
  resourceConfig:
    providerConfigName: aws-provider
    region: eu-west-1
    tags:
      - key: env
        value: test
      - key: test_tag
        value: test
```

</details>

Create the Object Storage, try to changing tags or deleting them. No changes will reflect at the manage resource, they are reflected in the XObjectStorage resource tho. 
Is this expected or known? Is there a workaround for it?

### What environment did it happen in?
Crossplane version: v1.9.1
Aws provider: v0.32.0
Kubernetes: eks 1.23
