### ISSUE TITLE
Enable RBAC configuration for controllers to observe cross-provider resources

### ISSUE THREAD

**Issue by stewartshea** [crossplane/crossplane#3483]
### What problem are you facing?
I'm attempting to allow resources in one provider depend on a resource created by another provider, but the currently configured rbac configurations don't allow that. To provide a specific example; 

The `gcp` provider creates an external address; 
```
---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Address
metadata:
  name: linkerd-platform-gateway-address
  labels:
        env: "${env}"
spec:
  deletionPolicy: Delete
  forProvider: 
    addressType: "EXTERNAL"
    description: "linkerd-platform-gateway-address"
    region: "${region}"
  providerConfigRef:
    name: providerconfig-gcp
```

From there, I'd like the `kubernetes` provider to sync the created address into a managed cluster; 

```
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: linkerd-platform-gateway-ip-${cluster_name}
spec:
  deletionPolicy: Delete
  references: 
  - dependsOn: 
      apiVersion: compute.gcp.crossplane.io/v1beta1
      kind: Address
      name: linkerd-platform-gateway-address
    patchesFrom: 
      apiVersion: compute.gcp.crossplane.io/v1beta1
      kind: Address
      name: linkerd-platform-gateway-address
      fieldPath: spec.forProvider
    toFieldPath: data
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: linkerd-platform-gateway-address
        namespace: flux-system
  providerConfigRef:
    name: provider-kubernetes-${cluster_name}
```

The error returned is related to the lack of rbac to permit the observation of the resource; 
```
    Message:               observe failed: cannot resolve resource references: cannot get referenced resource: addresses.compute.gcp.crossplane.io "linkerd-platform-gateway-address" is forbidden: User "system:serviceaccount:crossplane-system:provider-kubernetes-e3a9c3ae909b" cannot get resource "addresses" in API group "compute.gcp.crossplane.io" at the cluster scope
```

I realize I can manually craft some of the roles required, but with the unique service account naming of each provider SA this becomes a little messy in our automation (not impossible, just messy), and it feels like this might be better handled by the rbac manager with some ability to extend the roles it creates. 

### How could Crossplane help solve your problem?
A couple of ideas come to mind here while thinking this through: 
- provide the ability to specify the service account names to use when the provider is installed (which simplifies layering in rbac policies)
- enable rbac manager to slurp up additional custom roles/rolebindings 
- enable rbac manager to enforce some sort of policy that allows cross provider access (this is probably the most difficult and might conflct with how others like to manage their rbac configurations)
