### ISSUE TITLE
SIG for XRD and Composition Automation

### ISSUE THREAD

**Issue by natereid72** [crossplane/crossplane#3509]
I can't find an issue template in the Crossplane repo to suggest a SIG. So defaulting to '`bug`.

I'd like an issue template for proposed SIG groups. I find no SIGs for Crossplane and that is a concern to me. Crossplane is a CNCF project that appears to be controlled by a single company. If it is an open source CNCF project, it needs transparency and true community driven direction.

**Comment by negz** [comment]
We don’t currently have a concept of a SIG under our project governance, though we have created informal “SIG” Slack channels in the past. Do you have an example of a SIG structure/process that you think would work well for Crossplane?

**Comment by natereid72** [comment]
roughed out a yaml structure to create an XRD and Composition scaffold from. Just going to use python for a janky poc with it. End game could be a simple web frontend delivered via a container image that follows the logic.

This first pass will lack integration with provider CRD documentation and just scaffold a basic Composition starting point, with common patches and alignment to XR kind/api. Will produce complete XRD.

Looking for anyone that would like to collaborate on this initiative.

```yaml
# Composition Scaffolding
compositionGen:
  skipXRD: false
  simpleName: my-composition
# XRD Creation
xrdGen:
  apiPath: my-api-path.my-api-path
  apiVersion: version
  kind: my-kind
  # Begin XR Schema
  xrdSchema:
    spec: object
      some-object: object
        some-text-value: text
      some-list: list
      some-number: int
    status: object
      xr: object
        values: freeform
```

**Comment by nabuskey** [comment]
I am interested in this. I think Composition authoring is a the biggest pain point for me when using Crossplane, especially when you have to stitch together more than ~5 resources with dependencies in between them. A tool like this would be great to have. I did a bit of prototyping as well. I used Go structs and controller-gen to generate XRD schemas. It worked for XRD, but I couldn't find a good way to encapsulate wiring logic for composition. Perhaps we can leverage composition functions for it.

**Comment by natereid72** [comment]
Hey @nabuskey, very cool. I believe the large benefit will come from Composition generation as well. I've envisioned it being a gui front end with a backend that caches the provider crd api docs. Then enables you to use a canvas to drop resources in, be prompted for required values, graphically link resource templates to configure required patches, etc.

That is a large scope of work. This is why I am focused on a simple scaffolding of base Composition to begin with. I'm not clear on your thoughts around Composition Functions use. Can you describe that a but more?

**Comment by natereid72** [comment]
this is what I'm thinking for a simple starting point. Will take me a day to write ur in py. I would guess an hour or less for a proficient coder. 

### take a yaml def:

```yaml
# API
apiSchema:
  path: test.path.io
  version: v1beta1
  kind: prototype
# XRD Creation
xrdSchema:
  genClaim: true
  spec:
    some-object:
      some-text-value: text
    some-list: list
    some-number: int
    some-boolean: boolean
    some-freeform: freeform
  status:
    xr:
      values: freeform
# Composition Scaffolding
compositionGen:
  skipXRD: false
  simpleName: my-composition
  labels:
    cloud: someCloud
  ```

### And produce an XRD and Composition as:

XRD

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: my-composition.test.path.io
spec:
  group: test.path.io
  names:
    kind: XPrototype
    plural: xprototypes
  claimNames:
    kind: Prototype
    plural: prototypes
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              some-object:
                type: object
                properties:
                  some-text-value:
                      type: string
```
etc.

Composition Scaffolding:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: my-composition.test.path.io
  compositeTypeRef:
    apiVersion: test.path.io/v1beta1
    kind: prototype
  resources:
```
