### ISSUE TITLE
Granular management policies (e.g. ability to ignore changes etc.)

### ISSUE THREAD

**Issue by timnee** [crossplane/crossplane#3516]
### What problem are you facing?

Crossplane provides reconciliation of all parameters under `spec`.  There are cases where this is not desired post initial creation.  Such as when a parameter is managed outside of Crossplane.  For example [AutoScalingGroup DesireCapacity](https://doc.crds.dev/github.com/upbound/provider-aws/autoscaling.aws.upbound.io/AutoscalingGroup/v1beta1@v0.21.0#spec-forProvider-desiredCapacity) could be updated during a scaling event triggered by Cloudwatch.  

[Slack thread](https://crossplane.slack.com/archives/CEG3T90A1/p1670285697486339)

### How could Crossplane help solve your problem?

Add an equivalent to [Terraform's lifecycle ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) for parameters that are updated outside of Crossplane and keep it from being reconciled.  

I agree with @turkenh [suggestion](https://crossplane.slack.com/archives/CEG3T90A1/p1670356012575189?thread_ts=1670285697.486339&cid=CEG3T90A1) 
```
spec:
  ignoreChanges:
    - desiredCapacity
 ```

**Comment by linaking-guidewire** [comment]
I have a similar issue, using the same provider. We create DynamoDB [Tables](https://doc.crds.dev/github.com/upbound/provider-aws/dynamodb.aws.upbound.io/Table/v1beta1@v0.24.0) with autoscaling ([Policy](https://doc.crds.dev/github.com/upbound/provider-aws/appautoscaling.aws.upbound.io/Policy/v1beta1@v0.24.0) + [Target](https://doc.crds.dev/github.com/upbound/provider-aws/appautoscaling.aws.upbound.io/Target/v1beta1@v0.24.0)). The autoscaler scales the read and write capacity, and then Crossplane resets it back to the `readCapacity` and `writeCapacity` defined on the Table, which effectively makes autoscaling useless.

@turkenh's proposed solution would solve this case as well.
```
spec:
  ignoreChanges:
    - readCapacity
    - writeCapacity
```

**Comment by turkenh** [comment]
Another use case from [slack](https://crossplane.slack.com/archives/CEG3T90A1/p1674744295223779):

> I am creating nodegroup for eks with the below specs scalingConfig:
>  - minSize: 1
>    maxSize: 5
>    desiredSize: 1
>
> and I am using node autoscaler. There is a race condition between crossplane and node autoscaler. Node autoscaler increases the desired size due to resource requirement but crossplane decrease it to desired size set in composition.

**Comment by turkenh** [comment]
As pointed by @negz [here](https://github.com/crossplane/crossplane/pull/3531#discussion_r1072945963), another solution could be something like `spec.initProvider`:

```yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: sample-eks-ng
spec:
  # Desired state that will be used only on initial creation (optional)
  initProvider:
    scalingConfig:
      - desiredSize: 1
  # Desired state that will be enforced on every reconcile (optional, if the resource already exists)
  forProvider:
    scalingConfig:
      - maxSize: 3
        minSize: 1
status:
  # The observed state, updated on every reconcile.
  atProvider:
    scalingConfig:
      - desiredSize: 3
        maxSize: 3
        minSize: 1
```
