### ISSUE TITLE
Connection secret could not be written with `existing secret is not owned by UID`

### ISSUE THREAD

**Issue by jonnylangefeld** [crossplane/crossplane#3520]
### What happened?

I have a simple composition with a GCP service account and a service account key and want to find the key in a connection secret. When I apply the custom service account resource `CruiseServiceAccount`, all underlying resources get created, but the connection secret is empty. There is a warning in the events of the `XCruiseServiceAccount` resource:
```
Warning  PublishConnectionSecret  48s (x5 over 3m20s)    defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot publish connection details: cannot write to secret store: cannot apply secret: existing secret is not owned by UID "402e5318-d97c-4efb-86c1-779e4ab3dea1"
```

However, that does not seem right as the secret has that XRD with that very UID as owner:
```
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2022-12-09T06:35:25Z"
  name: 402e5318-d97c-4efb-86c1-779e4ab3dea1
  namespace: crossplane-system
  ownerReferences:
  - apiVersion: getcruise.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XCruiseServiceAccount
    name: jonnys-sa-bs4x5
    uid: 402e5318-d97c-4efb-86c1-779e4ab3dea1
  resourceVersion: "1217002088"
  uid: fb7a3a37-bcd1-48b1-b540-79db4113a794
type: connection.crossplane.io/v1alpha1
```

The secret doesn't have any values either.

### How can we reproduce it?

Create the following resources:

<details>
<summary>`Composition` yaml:</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcruiseserviceaccounts.getcruise.com
  labels:
    provider: gcp
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: getcruise.com/v1alpha1
    kind: XCruiseServiceAccount
  resources:
    - name: serviceaccount
      base:
        # https://doc.crds.dev/github.com/upbound/provider-gcp/cloudplatform.gcp.upbound.io/ServiceAccount/v1beta1
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: ServiceAccount
        spec:
          forProvider: {}
      patches:
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.description
          policy:
            fromFieldPath: Required
          combine:
            variables:
              - fromFieldPath: spec.claimRef.namespace
              - fromFieldPath: spec.claimRef.name
            strategy: string
            string:
              fmt: "%s/%s"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.email
          toFieldPath: status.serviceAccountEmail
          policy:
            fromFieldPath: Required
    - name: serviceaccountkey
      base:
        # https://doc.crds.dev/github.com/upbound/provider-gcp/cloudplatform.gcp.upbound.io/ServiceAccountKey/v1beta1
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: ServiceAccountKey
        spec:
          forProvider:
            publicKeyType: TYPE_X509_PEM_FILE
            serviceAccountIdSelector:
              matchControllerRef: true
```
</details>

<details>
<summary>`XRD` yaml:</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcruiseserviceaccounts.getcruise.com
spec:
  group: getcruise.com
  names:
    kind: XCruiseServiceAccount
    plural: xcruiseserviceaccounts
  claimNames:
    kind: CruiseServiceAccount
    plural: cruiseserviceaccounts
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: {}
```
</details>

<details>
<summary>yaml to apply the resource:</summary>

```yaml
apiVersion: getcruise.com/v1alpha1
kind: CruiseServiceAccount
metadata:
  name: jonnys-sa
spec: {}
```
</details>

### What environment did it happen in?
Crossplane version: `1.10.1`
Kubernetes version: `v1.21.14`

**Comment by turkenh** [comment]
@jonnylangefeld, thanks a lot for the concise reproduction steps. It makes our lives way easier while investigating the issue 🙌 

When I applied the manifests you provided, I didn't get the `secret is not owned by UID` error you encountered.
However, I got an empty connection secret instead, which I believe is not the intended behavior.

To propagate connection secrets from composed resources back to composite (hence claim), you need to:
- Store a connection secret for the composed resource by providing `writeConnectionSecretToRef` 
- Use `connectionDetails.fromConnectionSecretKey` to propagate already stored secrets up to composite connection secret.

With the updated composition below, I could get a secret for my composite:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcruiseserviceaccounts.getcruise.com
  labels:
    provider: gcp
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: getcruise.com/v1alpha1
    kind: XCruiseServiceAccount
  resources:
    - name: serviceaccount
      base:
        # https://doc.crds.dev/github.com/upbound/provider-gcp/cloudplatform.gcp.upbound.io/ServiceAccount/v1beta1
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: ServiceAccount
        spec:
          forProvider: {}
      patches:
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.description
          policy:
            fromFieldPath: Required
          combine:
            variables:
              - fromFieldPath: spec.claimRef.namespace
              - fromFieldPath: spec.claimRef.name
            strategy: string
            string:
              fmt: "%s/%s"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.email
          toFieldPath: status.serviceAccountEmail
          policy:
            fromFieldPath: Required
    - name: serviceaccountkey
      connectionDetails:
        - fromConnectionSecretKey: private_key
      base:
        # https://doc.crds.dev/github.com/upbound/provider-gcp/cloudplatform.gcp.upbound.io/ServiceAccountKey/v1beta1
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: ServiceAccountKey
        spec:
          forProvider:
            publicKeyType: TYPE_X509_PEM_FILE
            serviceAccountIdSelector:
              matchControllerRef: true
          writeConnectionSecretToRef:
            name: sa-key
            namespace: crossplane-system
```
