### ISSUE TITLE
Cannot deploy PostgreSQLInstance by following the "Getting Started" instruction

### ISSUE THREAD

**Issue by ZhiminXiang** [crossplane/crossplane#3533]
### What happened?
I followed the instruction https://docs.crossplane.io/v1.10/getting-started/install-configure/, and was able to install crossplane.

But for the step https://docs.crossplane.io/v1.10/getting-started/provision-infrastructure/, I cannot successfully set up PostgresDB by creating the GCP PostgreSQLInstance CR.
I found the following error in the XPostgreSQLInstance:

```
message: 'cannot publish connection details: cannot write to secret store: cannot
        apply secret: existing secret is not owned by UID "91bdaef9-0277-48a9-b860-fcb8da7229dd"'
```

Here is the XPostgreSQLInstance CR:
```
apiVersion: database.example.org/v1alpha1
kind: XPostgreSQLInstance
metadata:
  creationTimestamp: "2022-12-15T08:06:13Z"
  finalizers:
  - composite.apiextensions.crossplane.io
  generateName: my-db-
  generation: 5
  labels:
    crossplane.io/claim-name: my-db
    crossplane.io/claim-namespace: default
    crossplane.io/composite: my-db-fsp7n
  name: my-db-fsp7n
spec:
  claimRef:
    apiVersion: database.example.org/v1alpha1
    kind: PostgreSQLInstance
    name: my-db
    namespace: default
  compositionRef:
    name: xpostgresqlinstances.gcp.database.example.org
  compositionSelector:
    matchLabels:
      provider: gcp
  compositionUpdatePolicy: Automatic
  parameters:
    storageGB: 20
  publishConnectionDetailsTo:
    configRef:
      name: default
    name: 91bdaef9-0277-48a9-b860-fcb8da7229dd
  resourceRefs:
  - apiVersion: database.gcp.crossplane.io/v1beta1
    kind: CloudSQLInstance
    name: my-db-fsp7n-lm9rp
  writeConnectionSecretToRef:
    name: 91bdaef9-0277-48a9-b860-fcb8da7229dd
    namespace: crossplane-system
status:
  conditions:
  - lastTransitionTime: "2022-12-15T08:06:13Z"
    message: 'cannot publish connection details: cannot write to secret store: cannot
      apply secret: existing secret is not owned by UID "91bdaef9-0277-48a9-b860-fcb8da7229dd"'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### How can we reproduce it?

Follow the "getting started" instruction.

### What environment did it happen in?
* Crossplane version: 1.10.1
* Kubernetes version (use `kubectl version`): 1.21
* * Kubernetes distribution: GKE
