### ISSUE TITLE
Can't pull Custom Provider image from private DockerHub

### ISSUE THREAD

**Issue by vyrwu** [crossplane/crossplane#3551]
### What happened?
Can't pull private image after installing custom `Provider` via CRD, with DockerHub credentials mounted via `packagePullSecrets`:
```
cannot unpack package: failed to fetch package digest from remote: HEAD https://index.docker.io/v2/vyrwu/provider-github/manifests/v0.1.0: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details) 
```

### How can we reproduce it?

```
cat <<EOF | kubectl apply -f -
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-github
spec:
  package: vyrwu/provider-github:v0.1.0
  packagePullSecrets:
  - name: dockerhub

---
apiVersion: v1
data:
  .dockerconfigjson: <REDACTED> 
kind: Secret
metadata:
  name: dockerhub
  namespace: crossplane-system
type: kubernetes.io/dockerconfigjson
EOF
```

```bash
> kubectl get secret dockerhub --output="jsonpath={.data.\.dockerconfigjson}" --namespace crossplane-system | base64 --decode
{"auths":{"https://index.docker.io/v2/":{"username":"<REDACTED>","password":"<REDACTED>","email":"<REDACTED>","auth":"<REDACTED>"}}}%
```

### What environment did it happen in?
Crossplane version: 1.8.1
EKS version: v1.23.13-eks-fb459a0
