### ISSUE TITLE
commonLables in configuration.pkg for Composition Revisions Labels

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#3555]
### What problem are you facing?
we want to add commonLables in configuration.pkg, that can be used for composition revisions lables, in a automatic way
example:

```
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: test
spec:
  package: sop:v1.193.0
  commonLabels:
    version: v1.193.0
    channel: beta
```

when using ci and gitops tooling to package and deploy configuration packages it is not an option to update labels manually - nor is it feasible to use calculated hashes from compositionrevisions
