### ISSUE TITLE
`x-kubernetes-validations` on XRD's spec gets dropped in CRD

### ISSUE THREAD

**Issue by jutley** [crossplane/crossplane#3604]
### What happened?

I created an XRD which uses the `x-kubernetes-validations` field on the for the top-level `spec` property. I also am using it in deeper fields within `spec`.

When the CRD is generated from the XRD, the spec's `x-kubernetes-validations` is gone, but the nested field has its `x-kubernetes-validations` intact.

I suspect this is a result of 

### How can we reproduce it?

Here is a minimal XRD that demonstrates the issue.

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtests.test.example.com
spec:
  group: test.example.com
  names:
    kind: XTest
    plural: xtests
  claimNames:
    kind: Test
    plural: tests
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                counter:
                  type: integer
                  x-kubernetes-validations:
                    - rule: self >= oldSelf
                      message: counter can only increase
              x-kubernetes-validations:
                - rule: '!has(oldSelf.counter) || has(self.counter)'
                  message: cannot be removed
```

Check the keys in the resulting CRD's spec definition. The `x-kubernetes-validations` field is missing.
```
→  kubectl get crd tests.test.example.com -o json | jq '.spec.versions[0].schema.openAPIV3Schema.properties.spec | keys'
[
  "properties",
  "type"
]
```

Check the nested field and see that the field _does_ exist.
```
→  kubectl get crd tests.test.example.com -o json | jq '.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.counter | keys'
[
  "type",
  "x-kubernetes-validations"
]
```

### What environment did it happen in?
Crossplane version: `1.11.0-rc.0.195.g3ce766b3`
Kubernetes version: `1.25.0`
