### ISSUE TITLE
Implement `imagePullSecrets` for Composition Functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3717]
### What problem are you facing?

The [Composition Functions design](https://github.com/crossplane/crossplane/blob/40649e2ce9cac78fc4e16f3366b78ccd4dfb46e8/design/design-doc-composition-functions.md) called for an array of `imagePullSecrets` that would be used to provide credentials to authenticate to a private OCI repository. This functionality was not implemented in time for the v1.11 release and had to be cut.

```yaml
apiVersion: apiextensions.crossplane.io/v2alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-function
    type: Container
    container:
      image: private.example.org/my-cool-function:0.1.0
      imagePullSecrets:
      - namespace: crossplane-system
        name: my-xpkg-io-creds
```

These secrets would be resolved to an [`ImagePullAuth`](https://github.com/crossplane/crossplane/blob/40649e2ce9cac78fc4e16f3366b78ccd4dfb46e8/apis/apiextensions/fn/proto/v1alpha1/run_function.proto#L42) message in the `RunFunctionRequest`:

```proto
// ImagePullAuth configures authentication to a remote OCI registry.
// It corresponds to go-containerregistry's AuthConfig type.
// https://pkg.go.dev/github.com/google/go-containerregistry@v0.11.0/pkg/authn#AuthConfig
message ImagePullAuth {
  string username = 1;
  string password = 2;
  string auth = 3;
  string identity_token = 4;
  string registry_token = 5;
}
```

### How could Crossplane help solve your problem?

We should implement `imagePullSecrets`. I believe to do so we need to:

* Update the `Composition` and `CompositionRevision` type definitions.
* Use the [`k8schain`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/authn/k8schain) package to resolve the secrets to an `ImagePullAuth`.

This would be a novel use of `k8schain` but I think it should work. Typically `k8schain` is passed as an argument to the go-containerregistry code that does the image pulling, but in our case that code exists inside `xfn` on the "other side" of the gRPC connection from Crossplane.
