### ISSUE TITLE
Support passing credentials to Composition Functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3718]
### What problem are you facing?

When reviewing the [Composition Functions design](https://github.com/crossplane/crossplane/blob/40649e2ce9cac78fc4e16f3366b78ccd4dfb46e8/design/design-doc-composition-functions.md) @turkenh pointed out that we don't currently have a secure way for a Composition Function to authenticate to an external system. We don't expect Composition Functions to _orchestrate_ external systems directly - we expect them to produce composed resources for Crossplane to orchestrate. We do however expect that Composition Functions might need to _query_ external systems in order to determine what Crossplane should do.

It's currently possible to specify an arbitrary `config` object for a function. This object will be copied verbatim to the config object of `FunctionIO`. This is not appropriate for passing credentials because the `Composition` is available as plaintext to any one with RBAC access to view them.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-Function
    type: Container
    container:
      image: xkpg.io/my-cool-Function:0.1.0
    config:
      apiVersion: database.example.org/v1alpha1
      kind: Config
      metadata:
        name: cloudsql
      spec:
        version: POSTGRES_9_6
```

I can't think of any other good alternatives, either.

* It's not a good idea to bake your credentials into your function's OCI image, especially because we don't yet support private OCI images per https://github.com/crossplane/crossplane/issues/3717.
* Composition Functions aren't run as Pods, so there's no way to inject credentials e.g. via a volume or environment variable.

### How could Crossplane help solve your problem?

We should make it possible to securely specify credentials. One option might be to support loading the entire `config` object from a (more) secure source such as a Kubernetes secret or a Secret Store (https://github.com/crossplane/crossplane/issues/3670). Something like:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-Function
    type: Container
    container:
      image: xkpg.io/my-cool-Function:0.1.0
    config:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: my-cool-config
```

**Comment by negz** [comment]
CC @turkenh and @ezgidemirel. I feel like this is related to the broader question of how we would _read_ secrets from a secret store (e.g. to use those secrets to set a database password or similar).

**Comment by negz** [comment]
I put this into the v1.12 milestone but now I'm thinking there's too much of a dependency on secret stores, and I'm reluctant to target both for v1.12. I'd be happy to re-add this if secret stores is trending to move out of alpha.

**Comment by blakebarnett** [comment]
FWIW I think it'd be totally fine to only support reading from k8s Secrets, given that things like https://external-secrets.io exist and it's probably not in scope to support writing to external secrets stores right?

**Comment by negz** [comment]
I think the updated design (https://github.com/crossplane/crossplane/pull/4306) gives us some more flexibility here. For example if we also move forward with something like the Package Runtime Config proposal (https://github.com/crossplane/crossplane/pull/4322) it will be possible to inject credentials into a Function by adding files or env vars to its container. That might not be the ideal UX, but it will at least make referencing credentials _possible_.

**Comment by negz** [comment]
So right now in Crossplane v1.14 Functions support `ControllerConfig`. It's not ideal (we would rather use `RuntimeConfig` per https://github.com/crossplane/crossplane/issues/4699) but it does let you affect the volumes, environment variables, etc of a Function. So with v1.14 it's going to be _possible_ to pass credentials securely to a Function.

The limitation with the implementation right now is that these credentials are then essentially baked into the Function - every caller would be able to use the same set of credentials. It's not clear to me how much of an issue this is in the context of v1.14. How much demand is there to support _per call_ credentials being passed to Functions?

**Comment by negz** [comment]
Here's an updated sketch of how this might look:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  mode: Pipeline
  pipeline:
  - step: run-a-function-that-needs-credentials
    functionRef:
      name: function-awscli
    credentials:
      source: Secret
      secretRef:
        name: aws-cli-creds
```

**Comment by negz** [comment]
Here's an alternative sketch. This one scratches the itch I have to treat credentials as just another kind of input. I think it might be overly complicated though. It's based on a sketch @turkenh's at https://github.com/crossplane/crossplane/issues/4141#issuecomment-1731335767.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  mode: Pipeline
  pipeline:
  - step: observe-default-vpc
    functionRef:
      name: function-query-aws
    inputs:
    - source: Inline
      input:
        apiVersion: query.aws.crossplane.io/v1beta1
        kind: Query
        spec:
          resource: vpc
          region: us-west-1
          query: Vpcs[].VpcId
          filters:
          - Name=tag:Environment,Values=Production
    - source: Reference
      inputRef:
        apiVersion: v1
        kind: Secret
        namespace: default
        name: aws-cli-creds
```

Some thoughts on this sketch:
* The API is pretty verbose, especially if you just want to provide a single input or set of credentials.
* There's some overlap with https://github.com/crossplane/crossplane/issues/4583. You could use it to pass arbitrary Kubernetes resources to a Function, including an `EnvironmentConfig`.
* It probably makes life a bit more difficult for Function authors - for example if your Function only supports exactly one input resource you need to figure out what to do if you get N of them.
* "Inputs" to a Function become not only the input type(s) _defined_ by the Function but anything.
* You could potentially install the Function's input type(s) as CRDs if you wanted to.
