### ISSUE TITLE
Allow ignoring environment config if it does not exists

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#3723]
### What problem are you facing?

I don't know if I am using environment config the bad way but I can't figure how to ignore selection of an `EnvironmentConfig` if it does not exists.

Let's say I have the following `EnvironmentConfig` resources:

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  labels:
    provider-name: default-provider
  name: defaut-provider-config
data:
  id: 123456
 ```
 
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  labels:
    provider-name: other-provider
  name: other-provider-config
data:
  id: 456789
 ```

Then I have a XRD with an optional field `providerConfigRef.name` in spec

In my composition I want to load the `default-provider-config EnvironmentConfig` if `providerConfigRef.name` is not referenced in my XR, and the correct provider `EnvironmentConfig` if it is referenced (let's say `other-provider-config EnvironmentConfig` if `providerConfigRef.name : other-provider`). 

So I tried to add the following environment in the associated composition:

```yaml
...
environment:
  environmentConfigs:
    - type: Selector
      selector:
        matchLabels:
        - key: provider-name
          type: Value
          value: default-provider
    - type: Selector
      selector:
        matchLabels:
        - key: provider-name
          type: FromCompositeFieldPath
          valueFromFieldPath: spec.providerConfigRef.name
```

The problem is if `spec.providerConfigRef.name` does not exists, crossplane will fail reconciliation with the following message: `cannot select environment: failed to build reference at index 1: failed to resolve value for label at index 0: spec.providerConfigRef: no such field` 

### How could Crossplane help solve your problem?

Maybe there is a workaround to this issue, but if not it would be neat to have a way to ignore missing environment config, the same way as patches are ignored if field path does not exists
