### ISSUE TITLE
Allow regex replace string transforms

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#3759]
### What problem are you facing?

My use case is I want to replace all new lines in a string with `\n`. There is no way to do this kind of transformation with Crossplane actually.

### How could Crossplane help solve your problem?

I don't know how it could be implemented, i thought about regex replace, but it would be maybe smarter to think about a way to implement a wide range of string transformations instead of just adding a feature each time somebody needs it (using sprig library maybe?).

**Comment by fabioaraujopt** [comment]
This already exists after version [v1.10.0](https://github.com/crossplane/crossplane/releases/tag/v1.10.0).

You can implement it as following:

```
        - type: ToCompositeFieldPath
          fromFieldPath: XXX
          toFieldPath: XXX
          transforms:
            - type: string
              string:
                type: Regexp
                regexp:
                  match: '(http[s]?:\/\/)?([^\s]+\/)(.*)'
                  group: 3
```
