### ISSUE TITLE
Support Yaml filter expressions in composition patches

### ISSUE THREAD

**Issue by nakamume** [crossplane/crossplane#3765]
### What problem are you facing?

Consider the following composition def
```
resources:
- name: res-a
  base:
    apiVersion: pq.xyz.io/v1beta1
    kind: Workspace
    spec:
      forProvider:
        vars:
        - key: var_a
          value: ""
        - key: var_c
          value: ""
  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: spec.var_a
    toFieldPath: spec.forProvider.vars[0].value
  - type: FromCompositeFieldPath
    fromFieldPath: spec.var_c
    toFieldPath: spec.forProvider.vars[1].value
```

In order to patch the `vars`, the array index numbers need to be mentioned (eg. `toFieldPath: spec.forProvider.vars[0].value`). It's very problematic and error prone when there are lots of fields in the array and/or when fields are added/removed (as this changes the indexes of other fields).

### How could Crossplane help solve your problem?

I tried using [JMESPath](https://jmespath.org/) style filter expressions to patch based on filters. Something like:
```
resources:
- name: res-a
  base:
    apiVersion: pq.xyz.io/v1beta1
    kind: Workspace
    spec:
      forProvider:
        vars:
        - key: var_a
          value: ""
        - key: var_c
          value: ""
  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: spec.var_a
    toFieldPath: spec.forProvider.vars[?key == 'var_a'].value
  - type: FromCompositeFieldPath
    fromFieldPath: spec.var_c
    toFieldPath: spec.forProvider.vars[?key == 'var_c'].value
```

But it seems not supported. Getting following warning:
```
cannot apply the patch at index 0: spec.forProvider.vars is not an object
```

Can we add support for JMESPath style filter expressions. (It would be great if entire JMESPath spec)
