### ISSUE TITLE
upgrading aws provider creates second Provider instance and both of them get unhealthy status

### ISSUE THREAD

**Issue by mateusz-lubanski-sinch** [crossplane/crossplane#3784]
### What happened?
After upgrading aws provider from `v0.36.1` version to `v0.37.0` crossplane created second Provider object and both of them get unhealthy status

![image](https://user-images.githubusercontent.com/115790821/220071793-04689d1b-2c9a-44c7-98ec-52eb1aaa43e2.png)

### How can we reproduce it?

Before patching crossplane aws provider we had below Provider configuration:
```
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: crossplane-provider-aws
  annotations:
    eks.amazonaws.com/role-arn: xxx
spec:
  args:
    - --enable-external-secret-stores
  podSecurityContext:
    fsGroup: 2000
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
    - containerPort: 8080
      name: metrics
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-aws
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.36.1"
  controllerConfigRef:
    name: crossplane-provider-aws
```

Than we changed only package version to `package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.37.0"`

After applying aws provider upgrade we noticed that second Provider object was created on our cluster:
![image](https://user-images.githubusercontent.com/115790821/220071793-04689d1b-2c9a-44c7-98ec-52eb1aaa43e2.png)

Deleting `crossplane-contrib-provider-aws` Provider helped solve the problem:
 - `crossplane-provider-aws` Provider was upgraded to `0.37.0`
 - provider get back to Healthy status

### What environment did it happen in?

* crossplane `1.11.0`
* provider: `xpkg.upbound.io/crossplane-contrib/provider-aws:v0.36.1` upgraded to `xpkg.upbound.io/crossplane-contrib/provider-aws:v0.37.0`
* AWS EKS `1.21` & `1.22`

**Comment by haarchri** [comment]
Can you post full output of  
kubectl get providers
kubectl get pkgrev 

Looks like you have multiple providers with different metadata.name

**Comment by turkenh** [comment]
I agree with @haarchri.

From the screenshot you shared, there are two provider packages with `metadata.name` is set as `crossplane-contrib-provider-aws` and `crossplane-provider-aws`. `metadata.name` of a provider package is provided by the user while creating the package and happens before the Crossplane package manager starts its operation. 

Closing this as it looks like a user error. Feel free to reopen if this is still an issue or if I am missing something :)

**Comment by mateusz-lubanski-sinch** [comment]
Let me try describe problem I was facing 

I have defined Provider with custom name `crossplane-provider-aws`
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-aws
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.36.1"
  controllerConfigRef:
    name: crossplane-provider-aws
```

After deploying it I can see with get providers one aws provider with exact same name `crossplane-provider-aws`

After some time when I patch provider version to newer version (e.g. `0.37.0`):
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-aws
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.37.0"
  controllerConfigRef:
    name: crossplane-provider-aws
```

After applying above code I ended up with 2 providers
 - `crossplane-contrib-provider-aws`
 - `crossplane-provider-aws`

I did not define anywhere `crossplane-contrib-provider-aws` 
Providers are are in unhealthy state and I have to delete manually `crossplane-contrib-provider-aws` 

I will let you know if this happen again after another patching
