### ISSUE TITLE
Can't use Composition Function to update XR status

### ISSUE THREAD

**Issue by bradkwadsworth-mw** [crossplane/crossplane#3812]
### What happened?
Trying to update a status field in my XR, but it seems to alway be overwritten with conditions. I was trying to replicate a `ToCompositeFieldPath` patch, but it never seems to be written. Updating other fields in the desired state such as labels works fine, but status fields look to be uneditable.

### How can we reproduce it?
I have the following in my definition.yaml
```yaml
piVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.catalog.projectx.mavenwave.dev
spec:
  group: catalog.projectx.mavenwave.dev
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: BucketClaim
    plural: bucketclaims
  defaultCompositionRef:
    name: gcp-bucket
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
...
          status:
            type: object
            properties:
              bucket:
                type: object
                properties:
                  id:
                    type: string
```

Here's a snippet of my Python code that updates the status field.
```python
try:
  Functionio = read_Functionio()
except yaml.parser.ParserError as err:
  sys.stdout.write("cannot parse FunctionIO: {}\n".format(err))
  sys.exit(1)
...
status = deepcopy(Functionio["observed"]["composite"]["resource"]["status"])
Functionio["desired"]["composite"]["resource"]["status"] = status
Functionio["desired"]["composite"]["resource"]["status"]["bucket"] = {"id": "bar"}
Functionio["desired"]["composite"]["resource"]["metadata"]["labels"] = {"id": "bar"}

write_Functionio(Functionio)
```

The `Functionio["desired"]["composite"]["resource"]["metadata"]["labels"] = {"id": "bar"}` works as expected while the `Functionio["desired"]["composite"]["resource"]["status"]["bucket"] = {"id": "bar"}` does not.

### What environment did it happen in?
Crossplane version: 
v0.11.0, v0.11.1, 1.12.0-rc.0

* Cloud provider or hardware configuration
xpkg.upbound.io/upbound/provider-gcp:v0.28.0
* Kubernetes version (use `kubectl version`)
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:22:09Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
Kind
* OS (e.g. from /etc/os-release)
MacOS Ventura 13.2
* Kernel (e.g. `uname -a`)
Darwin Kernel Version 22.3.0
