### ISSUE TITLE
values.yaml.tmpl sets args default to empty mapping instead of empty sequence

### ISSUE THREAD

**Issue by bobh66** [crossplane/crossplane#3831]
### What happened?
The crossplane helm chart values.yaml.tmpl sets the default values for the `args` parameters to empty mappings/objects instead of empty sequences/lists:

```
args: {}
```

Also in rbacManager:
```
rbacManager:
  deploy: true
  skipAggregatedClusterRoles: false
  replicas: 1
  managementPolicy: All
  leaderElection: true
  args: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
```

and xfn:

```
xfn:
  enabled: false
  image:
    repository: crossplane/xfn
    tag: v1.12.0-rc.0.87.gcfb37b72.dirty
    pullPolicy: IfNotPresent
  args: {}
```

Since all of these `args` parameters are referenced as sequences in the helm chart manifests, the default values should be empty sequences to prevent confusion.

### What environment did it happen in?
Crossplane version: 1.11
