### ISSUE TITLE
Backoff is not working if external creation fails

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#3840]
### What happened?

When the creation of the external resource fails, Crossplane provider controllers keep retrying without exponential backoff. This results in too many API requests to the Cloud APIs, which may lead to [additional costs](https://github.com/crossplane/crossplane/issues/3455#issuecomment-1341414919).

After creating a GCP bucket with a service account that lacks of enough permissions; We keep getting custom resource updated in each reconciliation, although it keeps failing. This adds the resource to the queue again, resetting the back-off window. The updates were going to `metadata.annotations` as follows:

Reconcile `n`:
```
  metadata:
    annotations:
      crossplane.io/external-create-failed: "2023-01-23T10:38:37+03:00"
      crossplane.io/external-create-pending: "2023-01-23T10:38:36+03:00"
      crossplane.io/external-name: crossplane-example-bucket-hasan-backoff
```

Reconcile `n+1`:
```
  metadata:
    annotations:
      crossplane.io/external-create-failed: "2023-01-23T10:39:14+03:00"
      crossplane.io/external-create-pending: "2023-01-23T10:39:13+03:00"
      crossplane.io/external-name: crossplane-example-bucket-hasan-backoff
```

As you can see, both `crossplane.io/external-create-failed` and `crossplane.io/external-create-pending` annotations gets updated with new timestamps.

<img width="1257" alt="Screen Shot 2023-01-23 at 13 56 08" src="https://user-images.githubusercontent.com/9900707/214023424-166bed2d-94cc-4a68-9459-a4cc1ca37ade.png">

Observed initially as part of the experiments [here](https://github.com/crossplane/crossplane/issues/3455#issuecomment-1400230662).

### How can we reproduce it?

Create a GCP bucket with a service account that does not have enough permissions.

### Related issues

- https://github.com/crossplane/crossplane/issues/3455
