### ISSUE TITLE
PatchSet of composition as a different CRD

### ISSUE THREAD

**Issue by venkatk-25** [crossplane/crossplane#3847]
### Modularity/maintainability of Patchsets
For our use case we need to define a set of common patches to resources across multiple compositions. Some of our use cases 
1. defining common set of tags(few examples like one can be namespace of claimname. configuration pkg name, etc...) 
2. Defining some defaults to some MR which appears across multiple compositions.

The updation of the patchsets as a platform is not maintainable if they are not defined modularly and a change in logic of desired patch in these would result in updation of all compostions.

### How could Crossplane help solve your problem?
1. Would be great if Patchset can be made independent CRD and then referenced from different compositions, this becomes more maintainable long term.

A crd like:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Patchset
metadata:
  name: multitenancy-patches
spec:
      patches:
      - fromFieldPath: "spec.claimRef.namespace"
        toFieldPath: "spec.providerConfigRef.name"
```

and compostion reference it like:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: sns-poc
spec:
  compositeTypeRef:
    apiVersion: jpmc.com/v1alpha1
    kind: XSns
  resources:
    - name: Topic
      base:
        apiVersion: sns.aws.crossplane.io/v1beta1
        kind: Topic
        metadata:
          name: crossplane-poc-topic
        spec:
          forProvider:
            displayName: crossplane-poc-topic
          providerConfigRef:
            name:
      patches:
        - type: PatchSet
          patchSetRef: multitenancy-patches
```

A trigger in the patch should trigger the updation of all the compostions referencing it. Giving a very basic example here for example.

### Alternates:
1. We could define configuration package itself as helm/or any templatization engine.and templatize the patchset and define the patchset in common template file. 
2. Define these patchsets as OPA policies instead and automatically inject into all compostions.

This is something we can do though would mean more tooling on top of packaging tools of crossplane. A more native approach would be more maintainable and helpful
