### ISSUE TITLE
Composition Functions to support `ToCompositeFieldPath` patch

### ISSUE THREAD

**Issue by giepa** [crossplane/crossplane#3874]
Related to #3812

### What problem are you facing?
We need a way to keep XR status fields synchronised with status fields of resources. Previously this was solved with a `ToCompositeFieldPath` patch, however it is not clear if this is achievable using composition functions.

### How could Crossplane help solve your problem?
Perhaps this could be achieved in the `FunctionIO` schema as below:
```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: FunctionIO
...
desired:
  resources:
    - name: db-instance
      resource:
        apiVersion: sql.gcp.upbound.io/v1beta1
        kind: DatabaseInstance
        metadata:
          name: platform-ref-gcp-db-p9wrj-tvvtg
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.someValue
          toFieldPath: status.myStatus
```
