### ISSUE TITLE
Unable to unset optional fields in Claim

### ISSUE THREAD

**Issue by glrf** [crossplane/crossplane#3877]
### What happened?

We're unable to remove any fields from a claim. This means we can't "unset" an optional field.

As an example, given the following claim, where the field `foo` is optional:

```yaml
apiVersion: glrf.xyz/v1alpha1
kind: FooBar
metadata:
  name: test
spec:
  parameters:
    foo: bar
```

If we remove the field `foo` (i.e. set `parameters: {}`) the field is added back in.

### How can we reproduce it?

1. On a completely fresh cluster install Crossplane `v1.11.2` using helm:

```bash
helm install crossplane \
crossplane-stable/crossplane \
--namespace crossplane-system \
--create-namespace
```

2. Create the following XRD

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfoobars.glrf.xyz
spec:
  group: glrf.xyz
  names:
    kind: XFooBar
    plural: xfoobars
  claimNames:
    kind: FooBar
    plural: foobars
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  foo:
                    type: string
            required:
            - parameters
```

3. Create the following Claim

```yaml
apiVersion: glrf.xyz/v1alpha1
kind: FooBar
metadata:
  name: test
spec:
  parameters:
    foo: bar
```

4. Try to remove the field `foo` by applying

```yaml
apiVersion: glrf.xyz/v1alpha1
kind: FooBar
metadata:
  name: test
spec:
  parameters: {}
```

5. See that the claim is reverted back to having a field `foo` with value `bar`

### What environment did it happen in?
Crossplane version: 1.11.2 / 1.11.0 / 1.10.0

On OpenShift 4.11.28 - Kubernetes 1.25.6

Also reproduced on k3d Kubernetes version 1.22
