### ISSUE TITLE
Combine from parameters, status and environmentConfig values

### ISSUE THREAD

**Issue by fabioaraujopt** [crossplane/crossplane#3926]
### What problem are you facing?
I'm trying to create a ConfigMap whose data is a merge between elements of both status and the EnvironmentConfig, check this example:

```
patches: 
  - type: CombineFromEnvironment
      policy:
        fromFieldPath: Required
      combine:
        variables:
          - fromFieldPath: environmentFieldA
          - fromFieldPath: environmentFieldB
          - fromFieldPath: status.FieldC
          - fromFieldPath: parameters.FieldD
          # add more
        strategy: string
        string:
          fmt: |
             someExample: %s.%s.&s
```

### How could Crossplane help solve your problem?
We should create something to allow this kind of usecase.

**Comment by bobh66** [comment]
I believe you can initialize the environment with `parameters.FieldD` and use `ToEnvironmentFieldPath` to copy `status.FieldC` into the environment (with `policy.fromFieldPath: Required`) and then combine them all from the Environment, again using `policy.fromFieldPath: Required`

**Comment by ytsarev** [comment]
Hey @fhopfensperger 

Direct status propagation from MR to Environment indeed does not work. However, you can use the following workaround:

```
spec:
  environment:
    environmentConfigs:
      - ref:
          name: my-environment-config
    patches:
      - type: FromCompositeFieldPath
        fromFieldPath: metadata.annotations[cmKey] # patch environment key from metadata annotation, see below how it's populated
        toFieldPath: ecKey2
```

```
        - type: ToCompositeFieldPath # patch to XR
          fromFieldPath: status.atProvider.manifest.data.cmKey 
          toFieldPath: metadata.annotations[cmKey] # patch status to XR annotation
          transforms:
            - type: string
              string:
                fmt: "%s-from-configmap"
          policy:
            fromFieldPath: Required
```

```
        - type: CombineFromEnvironment
          combine:
            strategy: string
            variables:
              - fromFieldPath: ecKey1
              - fromFieldPath: ecKey2 # it will be patch from status->metadata->Environment so it will have the value of `status.atProvider.manifest.data.cmKey `
            string:
              fmt: "target-%s-%s"
          toFieldPath: spec.forProvider.manifest.data.new
```

So we can propagate MR status to Environment through intermediate XR patching (we used metadata in this case).

Hope it helps :)

**Comment by fhopfensperger** [comment]
@ytsarev thanks for this workaround, indeed it's working. Before there was `EnvironmentConfig`, we used `ConfigMap` in combination with provider-kubernetes and actually did the same trick of putting status information of one MR into the composite status / annotations and then using them in other MRs. I had hoped that `EnvironmentConfig` could provide us with a more user-friendly API here.
For now it's working :)

**Comment by MisterMX** [comment]
From an API perspective, combining values from different sources could be solved by adding a `source` property to every variable:

```yaml
combine:
  variables:
    - source: Environment
      fromFieldPath: region
    - source: Composite
      fromFieldPath: spec.parameters.accountId
```

However, I think this would require a rewrite of the patching implementation, because right now the corresponding function only has two arguments `from` and `to` and is indifferent what these objects are (composite, composed or environment).

I am not sure if it is worth the effort implementing this because combining composite and environment can be done by copying the data into the environment before the rendering using `spec.environment.patches` and then using `CombineFromEnvironment` in the resources. As said before, including the composed status is not possible since it is not available during rendering. See also #3454.

If no one has strong feelings about this, I would suggest to close this issue.
