### ISSUE TITLE
Unable to serve multiple Composite apiVersions at the same time

### ISSUE THREAD

**Issue by AaronME** [crossplane/crossplane#3928]
### What happened?
I'm currently running several databases on version `v1` of a composite. I would like to make `v2alpha1` available without disabling `v1`.  (The specific case is to support migrating compositions to the `official-providers` from Upbound).

My case includes being able to test both versions in my CI pipeline, where both will need to be deployed to a control plane to test behavior.

Considering that only one version [may be referenceable](https://docs.crossplane.io/v1.11/concepts/composition/#hl-6-46), and  that compositions [must match a referenceable version](https://docs.crossplane.io/v1.11/concepts/composition/#hl-7-14), it is unclear how to support multiple versions on the same control plane. 

### How can we reproduce it?
1. Create A Composite (XMysqlDatabase) with two versions like so:
```yaml
  defaultCompositionRef:
    name: v2.mysqldatabases.platform.example.io
  versions:
    - name: v1
      served: true
      referenceable: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            ...
    - name: v2alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            ...
```
1. Prepare two compositions, each referencing a different version:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: v1.mysqldatabases.platform.example.io
spec:
  compositeTypeRef:
    apiVersion: platform.example.io/v1
    kind: XMySQLDatabase
...
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: v2.mysqldatabases.platform.example.io
spec:
  compositeTypeRef:
    apiVersion: mysqldatabases.platform.example.io/v2alpha1
    kind: XMySQLDatabase
...
```
1. Deploy this Composite to a cluster and wait for it to become established and offered.
1. Create two claims:
```yaml
apiVersion: platform.example.io/v1
kind: MySQLDatabase
metadata:
  name: example-database
spec:
  compositionRef:
    name: v1.mysqldatabases.platform.example.io
...
---
apiVersion: platform.example.io/v2alpha1
kind: MySQLDatabase
metadata:
  name: example-database-v2
...
```
1. Note that both will appear in the cluster as `v2alpha1`:

```
$ kubectl describe mysqldatabases
Name:         example-database-v2
API Version:  platform.example.io/v2alpha1
Kind:         MySQLDatabase
...
Name:         example-database
API Version:  platform.example.io/v2alpha1
Kind:         MySQLDatabase
```

### What environment did it happen in?
Crossplane version: 
- crossplane:v1.11.1-up.1
- kubernetes v1.24.7 (kind)
