### ISSUE TITLE
Resource fails to create when environmentConfig selector doesn't find a match

### ISSUE THREAD

**Issue by jtucci** [crossplane/crossplane#3938]
### What happened?
I defined the below Composition that uses environmentConfigs. If one of the selectors doesn't find a match but the other does, I expected the environment object to be built based off of the EnvironmentConfigs it does find. In this example, because one of the selectors does not find a match the XR fails with a reconciliation error: 

"error": cannot select environment: failed to build reference at index 0: no EnvironmentConfig found that matches labels

This composition needs to be used both directly as is and re-used within a nested composition. When used in a nested composition only the XR is created since the claim is at the parent resource level. In this case no claimRef.namespace field is used and instead the parent passes its claimRef.namespace into the resource groups 'id' field. On the other hand, when used directly, claimRef.namespace does exist but spec.id would be empty. I don't think the resource should fail to be created just because the selector doesn't find a match. 

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xresourcegroups.azure.ic.orchestrate.cloud.sap
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: azure.ic.orchestrate.cloud.sap/v1alpha1
    kind: XResourceGroup
  environment:
    environmentConfigs:
      - type: Selector
        selector:
          matchLabels:
            - type: FromCompositeFieldPath
              key: app
              valueFromFieldPath: spec.id
      - type: Selector
        selector:
          matchLabels:
            - type: FromCompositeFieldPath
              key: app
              valueFromFieldPath: spec.claimRef.namespace
....
....
````

### How can we reproduce it?
Create a composition which uses two selectors under environment.environmentConfigs where only one of the selectors will find a valid match and the other will fail. 

### What environment did it happen in?
Crossplane version: 1.11.1
