### ISSUE TITLE
Additionally added EnvironmentConfigs in Composition are not propagated to XR

### ISSUE THREAD

**Issue by P0t4T0o** [crossplane/crossplane#3941]
### What happened?

Given composition which references at least one env config:
if `environmentConfigs` list in Composition resource is extended by adding new references, these references are not propagated to XR, hence patching from newly added environment config fails.

### How can we reproduce it?

1. create composition which references env config `env-1` and patches some value from it into managed resource
   - eg. claim Demo and composite resource XDemo
2. update composition by extending `environmentConfigs` list with new env config `env-2` and apply
3. managed resource is not patched

describe XR (new env config is missing):
```yaml
Spec:
    API Version:  composite.demo.io/v1alpha1
    Kind:         Demo
    Name:         claim-1
    Namespace:    customer
  Composition Ref:
    Name:  xdemos.composite.demo.io
  Composition Revision Ref:
    Name:                     xdemos.composite.demo.io-8228a38
  Composition Update Policy:  Automatic
  Environment Config Refs:
    API Version:  apiextensions.crossplane.io/v1alpha1
    Kind:         EnvironmentConfig
    Name:         env-1
```

describe current composition revision:

```yaml
Spec:
  Composite Type Ref:
    API Version:  composite.demo.io/v1alpha1
    Kind:         XDemo
  Environment:
    Environment Configs:
      Ref:
        Name:  env-1
      Type:    Reference
      Ref:
        Name:  env-2
      Type:    Reference

```

---
note: if whole `Environment Config Refs:` section in XR is removed. XR immediately selfheals and successfully patches values from new env configs 

---

### What environment did it happen in?
Crossplane version: 

kubernetes: rancher desktop k8s 1.25.6 & EKS 1.22
kubectl: 1.26.1
kernel: Darwin Kernel Version 21.6.0
