### ISSUE TITLE
Failed to fetch packages for Provider/Configuration old revisions

### ISSUE THREAD

**Issue by fhopfensperger** [crossplane/crossplane#3942]
### What happened?
Crossplane tries to pull **old** `ProviderRevision` and `ConfigurationRevision` even if they are in state `Inactive`.
Is it intentional that Crossplane keeps trying to pull old revisions from the remote registry? 

#### Background: 
We see in the events many `Parser backend cannot be initialized: Package could not be fetched from remote` messages because the package version no longer exists in the remote registry due to a container image registry (Azure Container registry) cleanup. 

### How can we reproduce it?

Deploy at least two different Configuration (or Provider) package versions one after another. Try to delete the first version from the remote registry and monitor the events. You will find something like:

```
# events
default                   1s          Warning   ParsePackage                      configurationrevision/iac-platform-configuration-32e7d4450782         cannot initialize parser backend: failed to fetch package from remote: GET https://xx.azurecr.io/v2/configurations/iac-platform-configuration/manifests/1.3.21: MANIFEST_UNKNOWN: manifest tagged by "1.3.21" is not found; map[Tag:1.3.21]
default                   0s          Warning   ParsePackage                      configurationrevision/iac-platform-configuration-5447be2ca321         cannot initialize parser backend: failed to fetch package from remote: GET https://xxx.azurecr.io/v2/configurations/iac-platform-configuration/manifests/1.3.11: MANIFEST_UNKNOWN: manifest tagged by "1.3.11" is not found; map[Tag:1.3.11]
...
default             2m5s        Warning   ParsePackage                      providerrevision/provider-jet-github-ddd1c3ffa7fe                     cannot initialize parser backend: failed to fetch package from remote: GET https://xxx.azurecr.io/v2/acp/provider-jet-github/manifests/0.1.5: MANIFEST_UNKNOWN: manifest tagged by "0.1.5" is not found; map[Tag:0.1.5]

```

### What environment did it happen in?
Crossplane version: 1.11.2
Kubernetes Server version: `Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.17-eks-48e63af", GitCommit:"47b89ea2caa1f7958bc6539d6865820c86b4bf60", GitTreeState:"clean", BuildDate:"2023-01-24T09:34:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by ytsarev** [comment]
@hasheddan do you know if it is expected behavior?

**Comment by hasheddan** [comment]
@fhopfensperger what `packagePullPolicy` do you have set? This is expected behavior as inactive package revisions still need to add owner refs to their CRDs. However, if `packagePullPolicy` is set to `IfNotPresent` then it will use the cached content rather than trying to re-pull. If you want it to not even attempt you can also set `packagePullPolicy: None`. Here is the logic being used: https://github.com/crossplane/crossplane/blob/115a25ba0769e90fdb5d9f4e75e1ad3ebcef963a/internal/controller/pkg/revision/reconciler.go#L409

**Comment by fhopfensperger** [comment]
@hasheddan & @ytsarev thanks for supporting. For `Configuration` we have set:
```
spec:
  ignoreCrossplaneConstraints: false
  package: xxx.azurecr.io/configurations/iac-platform-configuration:1.5.20
  packagePullPolicy: IfNotPresent
  packagePullSecrets:
  - name: dockerconfigjson
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
```
For providers we have set:
```
spec:
  controllerConfigRef:
    name: provider-jet-github-controllerconfig
  ignoreCrossplaneConstraints: false
  package: xxx.azurecr.io/acp/provider-jet-github:0.3.5
  packagePullPolicy: Always
  packagePullSecrets:
  - name: dockerconfigjson
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
```
