### ISSUE TITLE
Combining data from Composite and EnvironmentConfigs

### ISSUE THREAD

**Issue by clementblaise** [crossplane/crossplane#3947]
### What problem are you facing?

EnvironmentConfigs are an excellent addition to enable better modularity in writing composition. It works very well for patching a single parameter. Still, there is a dead end if it is necessary to combine data from multiple sources, such as the Composite and Environments.

I am currently using an admission webhook to add annotations on the composite so that it's possible to use combine:
```
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.assumeRolePolicy
          combine:
            variables:
              - fromFieldPath: metadata.annotations[acme.org/accountId]
              - fromFieldPath: metadata.annotations[acme.org/oidc]
              - fromFieldPath: metadata.annotations[acme.org/oidc]
              - fromFieldPath: spec.namespace
              - fromFieldPath: spec.name
            strategy: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::%s:oidc-provider/%s"
                      },
                      "Action": "sts:AssumeRoleWithWebIdentity",
                      "Condition": {
                        "StringEquals": {
                          "%s:sub": "system:serviceaccount:%s:%s"
                        }
                      }
                    }
                  ]
                }
          policy:
            fromFieldPath: Required
```

This example is for our XServiceAccount and temples an IAM Role; it takes the `namespace` and `name` from the composite but requires information related to the environment, such as the `accountId` and `oidc`.

We are using this mechanism successfully across our Composition, but it would be nice to have native support for it in Crossplane.

### How could Crossplane help solve your problem?

I see two options; we would either need a way to pass data from the Composite to the EnvironmentConfigs or adding/updating combine patch to enable it.

**Comment by clementblaise** [comment]
@bobh66 Thanks, but I don't think it applies to this situation; the goal is avoiding having `accountId` and `oidc` in the spec of the XR. They could be written into an EnvironmentConfig as part of XR for a Cluster, but the problem is accessing Composite and EnvironmentConfigs data within a patch.

**Comment by bobh66** [comment]
I haven't tested this but based on the design document (https://github.com/crossplane/crossplane/blob/master/design/one-pager-composition-environment.md) I would expect it to work as you need it to, assuming an existing EnvironmentConfig that has `accountId` and `oidc`:

```yaml
kind: Composition
spec:
  environment:
    environmentConfigs:
      - type: Reference # this is the default
        ref:
          name: cluster-info-environment
    patches:   # Merge some data from the Composite into the local environment
    - type: FromCompositeFieldPath
      fromFieldPath: spec.namespace    # maybe should be metadata.namespace?
      toFieldPath: namespace
    - type: FromCompositeFieldPath    # maybe should be metadata.name?
      fromFieldPath: spec.name
      toFieldPath: name

  resources:
  - name: resourceA
    base:
      kind: Foo
      apiVersion: ......
    patches:
    - type: CombineFromEnvironment
      toFieldPath: spec.forProvider.assumeRolePolicy
      combine:
        variables:
          - fromFieldPath: accountId
          - fromFieldPath: oidc
          - fromFieldPath: oidc
          - fromFieldPath: namespace
          - fromFieldPath: name
        strategy: string
        string:
          fmt: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "arn:aws:iam::%s:oidc-provider/%s"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {
                      "%s:sub": "system:serviceaccount:%s:%s"
                    }
                  }
                }
              ]
            }
      policy:
        fromFieldPath: Required
```

If this doesn't work that would be good to know so we can understand why.
