### ISSUE TITLE
EnvironmentPatch missing  FromEnvironmentFieldPath patch

### ISSUE THREAD

**Issue by clementblaise** [crossplane/crossplane#3965]
### What happened?

When using the FromEnvironmentFieldPath in an environment patches I got the following error:
```bash
The Composition "xserviceaccount.acme.org" is invalid: spec.environment.patches[0].type: Unsupported value: "FromEnvironmentFieldPath": supported values: "FromCompositeFieldPath", "ToCompositeFieldPath", "CombineFromComposite", "CombineToComposite"
```

As stated on the design doc is it should possible to use it : https://github.com/crossplane/crossplane/blob/edadd8c596553b290bd0d32f97c950fbcbc363d2/design/one-pager-composition-environment.md?plain=1#L127-L135

### How can we reproduce it?

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xserviceaccount.acme.org
spec:
  compositeTypeRef:
    apiVersion: acme.org/v1alpha1
    kind: XServiceAccount
  environment:
    environmentConfigs:
      - ref:
          name: demo
    patches:
      - type: FromEnvironmentFieldPath
        fromFieldPath: name
        toFieldPath: status.name
```

### What environment did it happen in?
Crossplane version: 1.11.3
