### ISSUE TITLE
Support Json marshal in Composition transforms

### ISSUE THREAD

**Issue by ra-grover** [crossplane/crossplane#3969]
### What problem are you facing?

I am trying to combine IamRole/Policy/RolePolicyAttachment via a Composition. The problem that I face is that `Policy.spec.forProvider.document` is a JSON string and we dont want to expose the complete string to our users and want to make it structured. 
For example (CompositeResource):
```apiVersion: myplatform.crossplane/v1alpha1
kind: XMyPlatformIam
spec:
  compositionUpdatePolicy: Automatic
  statement:
    - Action:
        - s3:*
      Effect: Allow
      Resource:
        - arn:aws:s3:::example-bucket 
```

The problem is that while defining a Composition, I am not seeing an option in `Transforms` to convert that structured object to json or apologies if I am missing something from [Composition Docs](https://docs.crossplane.io/v1.10/reference/composition/ )
### How could Crossplane help solve your problem?

I want to check if there is an option to put Yaml and Json marshals as an option in Transforms while defining my composition.

**Comment by ra-grover** [comment]
Thanks @bobh66. This is what I thought, but this one limits the number of policies that can be added at once, if I am not wrong. For example I want the ability to have multiple policies in one:
```
spec:
  policy:
    Version: "2012-10-17"
    Statement:
      - Action:
          - "iam:CreateServiceLinkedRole"
        Effect: "Allow"
        Resource: "*"
      - Action:
          - "ec2:DescribeAccountAttributes"
          - "ec2:DescribeAddresses"
          - "ec2:DescribeAvailabilityZones"
        Effect: "Allow"
        Resource: "*"
      - Action:
          - "ec2:AuthorizeSecurityGroupIngress"
          - "ec2:RevokeSecurityGroupIngress"
        Effect: "Allow"
        Resource: "*"
      - Action:
          - "ec2:CreateSecurityGroup"
        Effect: "Allow"
        Resource: "*"
```
