### ISSUE TITLE
Facing issue while installing crossplane helm chart

### ISSUE THREAD

**Issue by Swapnil-CSI** [crossplane/crossplane#3973]
### What happened?

Tried to install crossplane using the helm chart but it is showing below error.
```
[swapnil@bharshankar crossplane]$ helm install crossplane . -f values.yaml -n crossplane-system
Error: INSTALLATION FAILED: template: crossplane/templates/serviceaccount.yaml:9:18: executing "crossplane/templates/serviceaccount.yaml" at <.Values.serviceAccount.customAnnotations>: nil pointer evaluating interface {}.customAnnotations
[swapnil@bharshankar crossplane]$
```
content of values.yaml file
```
replicas: 1

deploymentStrategy: RollingUpdate

image:
  repository: crossplane/crossplane
  tag: v1.11.1
  pullPolicy: IfNotPresent

nodeSelector: {}
tolerations: []
affinity: {}

# -- Custom labels to add into metadata
customLabels: {}

# -- Custom annotations to add to the Crossplane deployment and pod
customAnnotations: {}

# -- Custom annotations to add to the serviceaccount of Crossplane
serviceAccount:
  customAnnotations: {}

leaderElection: true
args: {}

provider:
  packages: []

configuration:
  packages: []

imagePullSecrets: {}

registryCaBundleConfig: {}

webhooks:
  enabled: false

rbacManager:
  deploy: true
  skipAggregatedClusterRoles: false
  replicas: 1
  managementPolicy: All
  leaderElection: true
  args: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

priorityClassName: ""

resourcesCrossplane:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

securityContextCrossplane:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

packageCache:
  medium: ""
  sizeLimit: 5Mi
  pvc: ""
  configMap: ""

resourcesRBACManager:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

securityContextRBACManager:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

metrics:
  enabled: false

extraEnvVarsCrossplane: {}

extraEnvVarsRBACManager: {}

podSecurityContextCrossplane: {}

podSecurityContextRBACManager: {}

# The alpha xfn sidecar container that runs Composition Functions. Note you also
# need to run Crossplane with --enable-composition-functions for it to call xfn.
xfn:
  enabled: false
  image:
    repository: crossplane/xfn
    tag: v1.11.1
    pullPolicy: IfNotPresent
  args: {}
  extraEnvVars: {}
  securityContext:
    runAsUser: 65532
    runAsGroup: 65532
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    # These capabilities allow xfn to create better user namespaces. It drops
    # them after creating a namespace.
    capabilities:
      add: ["SETUID", "SETGID"]
    # xfn needs the unshare syscall, which most RuntimeDefault seccomp profiles
    # do not allow.
    seccompProfile:
      type: Unconfined
  cache:
    medium: ""
    sizeLimit: 1Gi
    pvc: ""
    configMap: ""
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
```

### How can we reproduce it?

git clone the crossplane repo. Go to path crossplane/cluster/charts/crossplane/
Add values.yaml file and Install the helm chart using below command.
```
helm install crossplane . -f values.yaml -n crossplane-system
```

### What environment did it happen in?
Crossplane version: 1.11.1
