### ISSUE TITLE
Objects failing with "cannot fetch Composition: no compatible CompositionRevisions found"

### ISSUE THREAD

**Issue by ra-grover** [crossplane/crossplane#3976]
### What happened?
Objects of XRDs are failing with :
```
message: 'cannot fetch Composition: no compatible CompositionRevisions found'
      reason: ReconcileError
```
There are no composite revisions being created for Compositions as per the documentation:

> Each time you edit a Composition Crossplane will automatically create a CompositionRevision that represents that ‘revision’ of the Composition - that unique state.

### How can we reproduce it?
Upgrade Crossplane from 1.8.1 to 1.11.3, create a CompositeResource and a Composition. 
The objects of Composite resource will fail with the above mentioned error.

### What environment did it happen in?
Crossplane version: 1.11.3
Kube version: v1.23.16-eks-48e63af

**Comment by negz** [comment]
@ra-grover Are there any Composition Revisions at all? What API version and kind is your XR, and what is the `compositeTypeRef` of your  Composition? They need to match for the XR to find a compatible revision.

**Comment by ra-grover** [comment]
@negz Yes there no Composition Revisions at all.
Tried with two different Composite resources.
```
 k get compositionrevisions
No resources found
```

XR is ```apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition```
and has status:
```
status:
  conditions:
    - lastTransitionTime: '2023-04-11T20:08:50Z'
      reason: WatchingCompositeResource
      status: 'True'
      type: Established
    - lastTransitionTime: '2023-04-11T20:08:51Z'
      reason: WatchingCompositeResourceClaim
      status: 'True'
      type: Offered
  controllers:
    compositeResourceClaimType:
      apiVersion: rcp.crossplane/v1alpha1
      kind: RcpIam
    compositeResourceType:
      apiVersion: rcp.crossplane/v1alpha1
      kind: XRcpIam
```

Also in the composition, I can confirm that I have the `compositeTypeRef` correctly configured.
```
spec:
  compositeTypeRef:
    apiVersion: runtime.crossplane/v1alpha1
    kind: XRuntimeIam
```
