### ISSUE TITLE
MergeOption: appendSlice is still overwriting instead of appending

### ISSUE THREAD

**Issue by b-m-f** [crossplane/crossplane#3993]
Same problem as https://github.com/crossplane/crossplane/issues/2690.

Using 
```
        mergeOptions:
          appendSlice: true
          keepMapValues: true
```
as described in the [docs](https://docs.crossplane.io/v1.9/reference/composition/#compositions) leads to whole values being replaced instead of having arrays appended to each other.

Running `helm.sh/chart: universal-crossplane-1.11.1-up.1`.

I was able to trace the code https://github.com/crossplane/crossplane/blob/2015c64c48aba497ef87275b62d78f77e5e41498/internal/controller/apiextensions/composite/merge.go#L33 but could not find where it is actually being invoked.

Where previously https://github.com/crossplane/crossplane/blob/2015c64c48aba497ef87275b62d78f77e5e41498/apis/apiextensions/v1/composition_patches.go#L198 applied the MergeOptions this does not seem to be done on [master](https://github.com/crossplane/crossplane/blob/9a0f0acb31c6b94b62262ad83cbd3899f9505b4d/apis/apiextensions/v1/composition_patches.go) anymore.

Thats where I stopped digging and decided to open this Issue.

**Comment by phisco** [comment]
This sounds like a behaviour we want to investigate further to check whether we introduced a regression at some point.
@b-m-f, do you happen to have an example manifest reproducing the issue?

**Comment by b-m-f** [comment]
Will double check next week and come up with a manifest.

**Comment by b-m-f** [comment]
Well, didn't recheck yet, but I'll post here when I get to it ;)

**Comment by AaronME** [comment]
We are also seeing that append is failing for us.

This works. but when mapOne is absent, we get a "null" entry in the first position.
```    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: status.mapOne
      toFieldPath: spec.forProvider.fields.maps[0]
      policy:
        mergeOptions:
          appendSlice: true
    - type: FromCompositeFieldPath
      fromFieldPath: status.mapTwo
      toFieldPath: spec.forProvider.fields.maps[1]
      policy:
        mergeOptions:
          appendSlice: true
```

This will overwrite mapOne instead of appending:
```
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: status.mapOne
      toFieldPath: spec.forProvider.fields.maps[0]
      policy:
        mergeOptions:
          appendSlice: true
    - type: FromCompositeFieldPath
      fromFieldPath: status.mapTwo
      toFieldPath: spec.forProvider.fields.maps[0]
      policy:
        mergeOptions:
          appendSlice: true
```

This does not work:
```
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: status.mapOne
      toFieldPath: spec.forProvider.fields.maps[]
      policy:
        mergeOptions:
          appendSlice: true
    - type: FromCompositeFieldPath
      fromFieldPath: status.mapTwo
      toFieldPath: spec.forProvider.fields.maps[]
      policy:
        mergeOptions:
          appendSlice: true
```

Nor does this:
```
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: status.mapOne
      toFieldPath: spec.forProvider.fields.maps
      policy:
        mergeOptions:
          appendSlice: true
    - type: FromCompositeFieldPath
      fromFieldPath: status.mapTwo
      toFieldPath: spec.forProvider.fields.maps
      policy:
        mergeOptions:
          appendSlice: true
```

**Comment by turkenh** [comment]
@b-m-f gentle ping on providing manifests for reproduction :) 

@AaronME thanks for the examples, it is not clear to me what are the types for `status.mapOne` or `spec.forProvider.fields.maps`? Are they maps or arrays?

While trying to reproduce #4026, I came up with the following manifests which show that append is working as expected (instead of overwriting):

**Definition:**

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnopresources.nop.example.org
spec:
  group: nop.example.org
  names:
    kind: XNopResource
    plural: xnopresources
  claimNames:
    kind: NopResource
    plural: nopresources
  connectionSecretKeys:
  - test
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            coolField:
              type: string
            oddNumbers:
              type: array
              items:
                type: string
            evenNumbers:
              type: array
              items:
                type: string
          required:
          - coolField
        status:
          type: object
          properties:
            coolerField:
              type: string
```

**Composition:**

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  resources:
  - name: nop-resource-1
    base:
      apiVersion: nop.crossplane.io/v1alpha1
      kind: NopResource
      spec:
        forProvider:
          fields:
            someField: "someValue"
          conditionAfter:
          - conditionType: Ready
            conditionStatus: "False"
            time: 0s
          - conditionType: Ready
            conditionStatus: "True"
            time: 10s
    patches:
      - fromFieldPath: spec.oddNumbers
        toFieldPath: spec.forProvider.fields.allNumbers
        policy:
          mergeOptions:
            appendSlice: true
      - fromFieldPath: spec.evenNumbers
        toFieldPath: spec.forProvider.fields.allNumbers
        policy:
          mergeOptions:
            appendSlice: true
```

Claim:

```yaml
apiVersion: nop.example.org/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: apiextensions-composition-pandt
spec:
  coolField: "foo"
  oddNumbers:
  - one
  evenNumbers:
  - two
  - four
```

Which composes:

```yaml
  ...
  spec:
      fields:
        allNumbers:
        - one
        - two
        - four
```

If I append `three` the to `spec.oddNumbers` in the claim, then the composed resource becomes which appends properly:

```yaml
  ...
  spec:
      fields:
        allNumbers:
        - one
        - two
        - four
        - three
```

**Comment by AaronME** [comment]
@turkenh You appear to be patching only strings.

Can you run your examples but merge objects?

In my example, `mapOne` and `mapTwo` are "maps."

And "maps" is []maps.

If I get time I'll try to come up with a clean example composition and definition.

**Comment by jbw976** [comment]
/fresh this one still concerns me, although I don't know if anyone has verified recently it is still reproducible

**Comment by kc8421** [comment]
It is still reproducible with latest version.  Using nested compositions (environment > n+1 xsubnet) and having for example predefined list of Azure SecurityGroup resources in xsubnet composition and patching array (SecurityGroups) input from environment with appendSlice enabled, does end up having only the patched items but not the ones that were defined into forProvider already.

**Comment by zargor** [comment]
Append slice does not work at least how I would expect, so maybe I do not follow it good enough.
If you have some default array, and you want to merge it with another array (or better say to `appendSlice` to it), it ends up by overwriting complete array.
Though it does work, from the point of merging, when both arrays are the same but e.g. with different values. Then it merges them properly. 

Now the case that does not work.

For instance in base spec `forProvider`:
```
                  targetTrackingScalingPolicyConfiguration:
                    - predefinedMetricSpecification:
                        - predefinedMetricType: "DynamoDBReadCapacityUtilization"
#                      scaleInCooldown: 0
#                      scaleOutCooldown: 0
#                      targetValue: 70
```

And a patch:
```
              - type: FromCompositeFieldPath
                 fromFieldPath: spec.autoscalingDefaults
                 toFieldPath: spec.forProvider.targetTrackingScalingPolicyConfiguration
                 policy:
                   mergeOptions:
                     appendSlice: true
                     # keepMapValues: true
```

Now if `spec.autoscalingDefaults` is supplied like this:
```
-  scaleInCooldown: 0
    scaleOutCooldown: 0
    targetValue: 70
```

The `predefinedMetricSpecification` information gets lost and only new values are kept (no merging effect).

From the docs:
With an array input, use `appendSlice: true` to append the array data to the end of the existing array.

LIke said, it could be I am missing some point however, would be awesome if you can direct to how such case should be approached. I guess it can be quite convinient to have such possibility.

**Comment by aarontorg** [comment]
@jbw976 is this still broken in v1.16? Trying to add a value to an array in the status with the below patch. It does not work. Trying to update the composition give the following error: 

Warning: Composition "xnetworks.xp.sapns2.io" invalid for schema-aware validation: spec.resources[3].patches[5].transforms: Required value: the fromFieldPath does not have a type compatible with the toFieldPath according to their schemas and no transforms were provided: string != array

 ```
- fromFieldPath: status.atProvider.id
   toFieldPath: status.endpointSubnets
   policy:
     mergeOptions:
       appendSlice: true
   type: ToCompositeFieldPath
```
