### ISSUE TITLE
Ability for patches within same resource to overwrite target array or map

### ISSUE THREAD

**Issue by shanproofpoint** [crossplane/crossplane#4026]
In a composition, if there are 2 patches that contribute information to a target array or map, there should be an option to merge the results but erase what was there first.  The inability to take things away from the target array or map results in the need to manually purge the attribute and wait for crossplane to repopulate. This could be nerve wracking in an emergency situation.

```
        - type: FromCompositeFieldPath
          fromFieldPath: spec.frontDetails.specifiedTlsCerts
          toFieldPath: spec.forProvider.sslCertificates
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
              mergeOnlyForSisterPatches: true

        - type: FromCompositeFieldPath
          fromFieldPath: status.processingData.discoveredSslCerts
          toFieldPath: spec.forProvider.sslCertificates
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
              mergeOnlyForSisterPatches: true

```

given:
```
  specifiedTlsCerts : [ "a", "b" ]
  discoveredTlsCerts: [ "c", d" ]

  the outcome will be [ "a", "b", "c", "d" ]
```
and if we later remove "c" the outcome will not change. It then becomes impossible to clean the array or map without manual intervention.

It would be preferable to have an option to have the outcome reflecting the removal of "c" in aggregate: ["a", "b", "d" ]

so some option like :
```
mergeOnlyForSisterPatches: true
```

### What problem are you facing?
See above.

**Comment by chlunde** [comment]
what happens with if you do this?

```yaml
        - type: FromCompositeFieldPath
          fromFieldPath: spec.frontDetails.specifiedTlsCerts
          toFieldPath: spec.forProvider.sslCertificates

        - type: FromCompositeFieldPath
          fromFieldPath: status.processingData.discoveredSslCerts
          toFieldPath: spec.forProvider.sslCertificates
          policy:
            mergeOptions:
              keepMapValues: true
 ```
