### ISSUE TITLE
appendSlice does not remove items not in list

### ISSUE THREAD

**Issue by bradkwadsworth-mw** [crossplane/crossplane#4036]
### What happened?
If I create a patch that uses `appendSlice: true` to merge items in a list in a definition everything works fine. But, if I remove an item in that list in my XR, the item is not removed in the composed resource.Would it be possible to remove non-existent items in an XR that is merged/overwritten in the composed resource?

### How can we reproduce it?
definition.yaml
```yaml
...
cluster:
  type: object
  properties:
    authorizedNetworks:
    type: array
    items:
      type: object
      description: Authorized networks to connect to Kube API.
      required:
      - cidrBlock
      properties:
        cidrBlock:
          type: string
...
```

composition.yaml
```yaml
...
base:
  apiVersion: container.gcp.upbound.io/v1beta1
  kind: Cluster
  spec:
    forProvider:
      masterAuthorizedNetworksConfig:
      - cidrBlocks:
        - displayName: bastion
patches:
- type: FromCompositeFieldPath
   fromFieldPath: spec.parameters.bastion.subnet.cidr
   toFieldPath: spec.forProvider.masterAuthorizedNetworksConfig[0].cidrBlocks[0].cidrBlock
- type: FromCompositeFieldPath
   fromFieldPath: spec.parameters.cluster.authorizedNetworks
   toFieldPath: spec.forProvider.masterAuthorizedNetworksConfig[0].cidrBlocks
   policy:
     mergeOptions:
        appendSlice: true
...
```

XR
```yaml
...
spec:
  parameters:
    cluster:
      authorizedNetworks:
      - cidrBlock: 5.6.7.8/32
...
```

composed resource
```yaml
...
apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster 
spec:
  forProvider:
    masterAuthorizedNetworksConfig:
    - cidrBlocks:
       - cidrBlock: 10.2.16.0/28
          displayName: bastion
       - cidrBlock: 5.6.7.8/32
...
```
modified XR
```yaml
...
spec:
  parameters:
    cluster:
      authorizedNetworks: []
...
```

composed resource after edit
```yaml
...
apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster 
spec:
  forProvider:
    masterAuthorizedNetworksConfig:
    - cidrBlocks:
       - cidrBlock: 10.2.16.0/28
          displayName: bastion
       - cidrBlock: 5.6.7.8/32
...
```

### What environment did it happen in?
Crossplane version:  1.12.0

* Cloud provider or hardware configuration: xpkg.upbound.io/upbound/provider-gcp:v0.31.0
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"darwin/amd64"}
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): GKE
