### ISSUE TITLE
Ability to patch into the key of an object value

### ISSUE THREAD

**Issue by cdloh** [crossplane/crossplane#4065]
### What problem are you facing?

Presently there is no way to patch the key name of an object value. Which makes any keys that are dynamic impossible to work with.

An example resource from provider-cloudflare 

```
apiVersion: account.cloudflare.upbound.io/v1alpha1
kind: APIToken
metadata:
  namespace: default
  name: cf-test-apitoken
spec:
  forProvider:
    name: "cf-test-apitoken"
    policy:
      - effect: allow
        permissionGroups:
          - "dafdsagrt42409uhfhjtnl44957"
        resources:
          "com.cloudflare.api.account.zone.${UUID IN HERE}": "*"
```

All keys under resources usually have a UUID (either a zone ID or account ID) as part of the string. In the example above I would like to patch a zone id in place of `${UUID IN HERE}`, this of course would come from a Zone resource.

### How could Crossplane help solve your problem?

Let me create resources that have dynamic keys within objects.

**Comment by negz** [comment]
@cdloh Do you have an idea of what kind of API you'd expect here? It seems like we'd need to support `toFieldPath` having a dynamically derived value.

**Comment by cdloh** [comment]
@negz   I'd spent some time chatting to @ytsarev  about this last week and didn't really have a good solid answer but maybe some initial thoughts.

1. It needs to be able to support all other patching abilities
2. It could probably expand on the transform API?

One thought I had would be that the `toFieldPath` (and maybe the `fromFieldPath`) can either be a `string` or `object` if it's an object it acts exactly like a normal patch except it doesn't have a `toFieldPath` 

eg
```

- type: ToCompositeFieldPath
  fromFieldPath: status.atProvider.ssl[0].validationRecords[0].txtValue
  toFieldPath:
	  type: CombineFromComposite
	  combine:
		variables:
		  - fromFieldPath: spec.parameters.dynamicFieldValue
		strategy: string
		string:
		  fmt: "spec.paramaters.%s"
	  policy:
		fromFieldPath: Required
  policy:
	fromFieldPath: Required
```



An alternative (that I think might be superior?) would be create a new type of `PatchSet` that has a similar API type as the transform patch and then add a field to patches called `toFieldPathRef` that is a named reference to the new type of Patch

eg

```
- ToFieldPatches:
  - name: ToFieldExample
    type: CombineFromComposite
    combine:
    variables:
      - fromFieldPath: spec.parameters.dynamicFieldValue
    strategy: string
    string:
      fmt: "spec.paramaters.%s"
    policy:
      fromFieldPath: Required

- PatchSets:
  - type: ToCompositeFieldPath
    fromFieldPath: status.atProvider.ssl[0].validationRecords[0].txtValue
    toFieldPathRef: ToFieldExample
    policy:
      fromFieldPath: Required
```

Both pretty rough ideas but hope they come across!

**Comment by jbw976** [comment]
Another example use case for patching a key can be found in https://github.com/crossplane/crossplane/discussions/4158

**Comment by mmuthukrishnan** [comment]
I need this feature definitely. There are few use cases where I need to patch both keyname and value.

**Comment by AaronME** [comment]
We attempted to provision grafana dashboards as configmaps. Grafana is looking for dashboards defined like so:
```
---
apiVersion: v1
kind: ConfigMap
data:
  dashboard.json: "{}" # JSON containing dashboard configuration
```

These are mounted into Grafana's pod as the file `dashboard.json`. To avoid collisions, and avoid toil-some duplication in the config, we would need the ability to set `data.["{%s}.json"]` from a patch.

**Comment by haarchri** [comment]
@AaronME other option is to use grafana provider https://github.com/grafana/crossplane-provider-grafana/blob/main/examples/cloud-stack-chain/6.dashboard.yaml#L9

**Comment by avinakollu** [comment]
+1 on this feature. This would be great to have. We currently need to tag our EKS cluster subnets with the Key "kubernetes.io/cluster/${EnvironmentName}-eks-cluster"

At the moment there is no way to do this using composition.

**Comment by jbw976** [comment]
Just a reminder for folks that are interested in this issue to add a 👍 reaction to it, as described in https://github.com/crossplane/crossplane/issues/4048, so it's easier to gather data on the popular issues 🙇

**Comment by PavelPikat** [comment]
Another use case for patching the key would be passing `varmap` to `provider-terraform`, where a module expects named keys in `map` variables 

e.g.
```
  apiVersion: tf.upbound.io/v1beta1
  kind: Workspace
  <...>
  spec:
    forProvider:
    <...>
    varmap:
       mymap:
         object-key-to-be-patched: <--- this need to be dynamic
            object-property: some-value
 
```

**Comment by turkenh** [comment]
I just opened a PR adding support for `FromJSON` convert transform, enabling patching keys (as a workaround ?).

With that PR and following manifests, I could get a key patched in the tags of VPC:

**definition:**

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnopresources.nop.example.org
spec:
  group: nop.example.org
  names:
    kind: XNopResource
    plural: xnopresources
  claimNames:
    kind: NopResource
    plural: nopresources
  connectionSecretKeys:
  - test
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            clusterName:
              type: string
          required:
          - clusterName
```

**composition:**

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  resources:
  - name: vpc-1
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: VPC
      spec:
        forProvider:
          cidrBlock: 172.16.0.0/16
          region: us-west-1
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.clusterName
      toFieldPath: spec.forProvider.tags
      transforms:
      - type: string
        string:
          type: Format
          fmt: '{"kubernetes.io/cluster/%s": "true"}'
      - type: string
        string:
          type: Convert
          convert: "FromJson"
```

claim:

```yaml
apiVersion: nop.example.org/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: apiextensions-composition-pandt
spec:
  clusterName: "dev-cluster"
```

I got the following VPC:

```yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
...
spec:
  ...
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: us-west-1
    tags:
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: apiextensions-composition-pandt-s77qm-7z2cq
      crossplane-providerconfig: default
      kubernetes.io/cluster/dev-cluster: "true"
```
