### ISSUE TITLE
Consider moving Composition's logical validation code to CEL Validation rules

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#4084]
### What problem are you facing?

Validation rules for CRDs have [recently](https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/) been promoted to `Beta` in Kubernetes `v1.25` and are still in `Beta` at the time I'm writing (`v1.27`). These rules allow developers to specify how custom resources are validated using the Common Expression Language (CEL), allowing to encode directly into the CRD itself, much more complex constraints that were previously only enforceable through a Validating Webhook, e.g. validating if an integer field is less than or equal to another integer field, checking if an entry with a specific key exists in a map based on some other field, verifying that a required field remains unchanged once set, etc...

We have already started using them for Observe Only Resources, see #3531, where they allow setting some fields as not required if and only if the `managementPolicy` key is set to `ObserveOnly`. Here an example from [upbound/provider-aws](https://github.com/upbound/provider-aws/blob/d4c0c2d786830535678b500305204d116d6ebc68/package/crds/xray.aws.upbound.io_samplingrules.yaml#L312):
```yaml
...
          spec:
...
            required:
            - forProvider
            type: object
            x-kubernetes-validations:
            - message: fixedRate is a required parameter
              rule: self.managementPolicy == 'ObserveOnly' || has(self.forProvider.fixedRate)
            - message: host is a required parameter
              rule: self.managementPolicy == 'ObserveOnly' || has(self.forProvider.host)
            - message: httpMethod is a required parameter
              rule: self.managementPolicy == 'ObserveOnly' || has(self.forProvider.httpMethod)
            - message: priority is a required parameter
              rule: self.managementPolicy == 'ObserveOnly' || has(self.forProvider.priority)
            - message: reservoirSize is a required parameter
              rule: self.managementPolicy == 'ObserveOnly' || has(self.forProvider.reservoirSize)
...
```

We recently introduced and enabled by default a ValidatingWebhook for Compositions as discussed in #3756 to shift left as much as possible any user error, trying to improve the developer experience around Compositions as per #3957.

The design document was splitting the validation task into two separate [kinds](https://github.com/crossplane/crossplane/pull/3756/files#diff-8dfb220f48da6208755c36731275d4d8ff51209399fedbffd3c2ea3e073fa55fR213): 
- **logical validation**: checking the Composition is logically valid and well-formed, according to runtime expectations not encoded in the CRD due to their complexity, which previously led to runtime errors only shown to the user via events or through some resource status.
- schema-aware validation, divided again in two phases:
  - fieldPaths schema-aware validation: checking all `fieldPaths` used in a Composition are valid according to the available schemas.
  - rendered resources schema-aware validation: actually rendering all resources, if possible, providing a mocked minimal Composite Resource, in order to then validate them against their schema, if available.

**Logical Validation** implementation mostly consists of switches checking that for each type specified by some `type` field, other required keys are actually present, erroring out in case they are missing, or similar other checks. It's obvious this looks like a good fit for CEL Validation rules, so I think we should reconsider this topic and decide whether we think it would be worth moving them to Validation rules. 

Here a non-comprehensive list of benefits and drawbacks I can think of at the time of writing:

**Benefits**:
- less Go code: rules would "just" be in an annotation and automatically added to the generated Composition's CRD.
- even less Go code: if all checks could be ported, we could potentially remove the ValidatingWebhook and the code its setup requires altogether. N.B.: we would still have to keep it if we decided to keep and graduate schema-aware validation down the line, as that would never be portable.
- enforcing done by the ApiServer, not Crossplane itself, so impossible to have runtime issues such as a `nil pointer dereference` panics, crashing Crossplane itself.
- a simple plugin enforcing json schema validation with Validation Rules would be able to catch many more errors, without being explicitly importing Crossplane's code. Given that these (`x-kubernetes-validations`) are not part of the official json-schema [spec](https://json-schema.org/specification.html), general purpose schema validators won't enforce it out of the box, but a Kubernetes specific one could definitely do that easily just relying on the upstream Kubernetes validation code.
- CRDs would be self-documenting, a user could understand which fields are required just by looking at the CRD, instead of reading some Go code. Although CEL rules can be a little bit obscure per se, messages can help 

**Drawbacks**:
- CEL rules are still in `Beta`, so they could still be dropped in the future. I consider that only a remote possibility, given the interest and the adoption rate, and the fact that we already "adopted" them for `ObserveOnly Resources`, but it's still worth mentioning.
- less Go code, given that rules would be "just" an annotation and inlined in the schemas, we would not be able to write unit tests for those, and we would have to rely only on E2Es. N.B. at the time of writing, validation of rules is only performed at CRD "deploy" time, when they get checked against the rest of the schema itself, while no checks are enforced at "build" time, see [here](https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/#why-cel).
- in the code we would have to assume resources are "valid", totally relying on the CRDs being up-to-date, without any way to check them against its own definition of validity, risking runtime errors if the code is not coherent with the CRD, e.g. a user forgot to update the CRD or modified it for any reason. We would still have to spread the checks around the codebase and code "defensively".

I feel like the most important points are:
- to have all these rules at least clearly encoded somewhere instead of relying on checks spread across the codebase.
- to shift left, surfacing any error as soon as possible, avoiding showing them only at "runtime".
- keeping the validation logic near to the code itself.

Both approaches cover the above points, so there is no urgency to move to Validation rules, the main selling point I see would the benefit of the self-documenting nature of Validation rules for users looking at the CRD.

### How could Crossplane help solve your problem?

Reconsider the choice in the future and expand the above considerations.
