### ISSUE TITLE
Claim "Ready" condition has a free text message in reason field

### ISSUE THREAD

**Issue by yhrn** [crossplane/crossplane#4094]
### What happened?

The status.conditions.[].reason field for the "Ready" condition on Claims contains a free text message instead of a programmatic identifier as specified [here](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1510-L1520).

For example:
```yaml
status:
  conditions:
  - lastTransitionTime: "2023-05-16T12:18:10Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-05-16T12:18:10Z"
    reason: Composite resource claim is waiting for composite resource to become Ready
    status: "False"
    type: Ready
```

### How can we reproduce it?

Create a claim and look at the status.

### What environment did it happen in?

Crossplane version: 1.12.1
