### ISSUE TITLE
Design Document for Cross-Resource Dependencies

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4100]
### What problem are you facing?

As the project continues to evolve, we have identified two prominent patterns of dependencies between managed resources:

- Referencing arbitrary fields from another resource, also known as **generic resource references**. For instance, a subnet that requires the ID of a VPC.
- Depending on the existence of another resource for successful operation, also known as **deletion ordering**. An example of this is a Helm release deployed into a Kubernetes cluster managed by Crossplane.

After initial discussions and investigations (#1770, #3393 and [this doc](https://docs.google.com/document/d/1Yu3GxNMJOOMWMjD6gEw5QtT8Fz5qQSyo18ZZFKqcqKw/edit#heading=h.9bmn90amk3gk)) we have come to believe that both types of dependencies could be addressed through a unified design by introducing a new type as proposed [here](https://github.com/crossplane/crossplane/issues/3393#issuecomment-1548709959). 

### How could Crossplane help solve your problem?

Write a design doc for cross-resource dependencies.

**Comment by turkenh** [comment]
I've put some thinking on what an API would look like for a generic type that would solve both the deletion ordering and generic referencing starting from the one proposed [here](https://github.com/crossplane/crossplane/issues/3393#issuecomment-1548709959).

> ```yaml
> # A Reference used only for deletion ordering.
> kind: Reference
> metadata:
>   name: release-uses-cluster
> spec:
>   # A 'blocking' reference prevents all of the 'to' (Cluster) resources from being
>   # deleted until the 'from' resource (the Release) is gone.
>   deletion: Blocking
>   from:
>     apiVersion: helm.crossplane.io/v1beta1
>     kind: Release
>     name: my-prometheus-chart
>   to:
>   - apiVersion: eks.upbound.io/v1beta1
>     kind: Cluster
>     name: my-cluster
> ```
> 
> ```yaml
> # A reference used only to derive field values.
> apiVersion: crossplane.io/v1alpha1
> type: Reference
> metadata:
>   name: subnet-to-vpc
> spec:
>   # A 'non-blocking' reference is the default. The VPC can be deleted before
>   # the Subnet.
>   deletion: NonBlocking
>   from:
>     apiVersion: network.aws.crossplane.io/v1alpha2
>     kind: Subnet
>     name: my-subnet
>     # Note the optional fieldPath is specified here and below.
>     fieldPath: spec.forProvider.vpcId
>   to:
>   # An array to support the case where a reference is derived from multiple
>   # fields in multiple objects? This would likely end up pretty close to
>   # Composition patches, with transforms etc. We'd probably want to support
>   # selectors here too, not only explicit references.
>   - apiVersion: network.aws.crossplane.io/v1alpha2
>     kind: VPC
>     name: my-vpc
>     fieldPath: metadata.annotations[crossplane.io/external-name]
> ```
> 

The first issue I was having was the confusion with the reversed direction of the from/to fields compared to the one that my brain used to (from the composition patches). Especially when I want to include transforms, then it gets more confusing, e.g. `spec.to` transforms into `spec.from`.

When I imagine the future of this API with similar support as composition patches with transforms, I ended up introducing a new `type` field to support functionality similar to [Combine](https://github.com/crossplane/crossplane/blob/d038cf0a44b711ee63c134e0d54d42bc5deb7502/apis/apiextensions/v1/composition_patches.go#L95) typed patches and used this as an advantage to fix confusion about direction mentioned above.


```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
type: Reference
metadata:
  name: subnet-to-vpc
spec:
  type: PatchesFieldPath
  patchesFieldPath:
    from:
      apiVersion: network.aws.crossplane.io/v1alpha2
      kind: VPC
      name: my-vpc
      fieldPath: metadata.annotations[crossplane.io/external-name]
    to:
      apiVersion: network.aws.crossplane.io/v1alpha2
      kind: Subnet
      name: my-subnet
      # Note the optional fieldPath is specified here and below.
      fieldPath: spec.forProvider.vpcId
    transforms:
      - type: string
        string:
          fmt: "id:%s"
```

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
type: Reference
metadata:
  name: subnet-to-vpc
spec:
  type: PatchesWithCombine
  patchesWithCombine:
    variables:
      from:
        - apiVersion: s3.aws.crossplane.io/v1beta1
          kind: Bucket
          name: my-bucket
          fieldPath: metadata.annotations[crossplane.io/external-name]
        - apiVersion: s3.aws.crossplane.io/v1beta1
          kind: Bucket
          name: my-bucket
          fieldPath: metadata.annotations[crossplane.io/external-name]
    strategy: string
    to:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: Policy
      name: my-policy
      fieldPath: spec.forProvider.document
    string:
        fmt: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [ "s3:*" ],
                "Resource": [
                  "arn:aws:s3:::%s",
                  "arn:aws:s3:::%s/*"
                ]
              }
            ]
          }
```

I don't know the exact details of the [reasoning](https://github.com/crossplane/crossplane/pull/2093#issuecomment-854160245) behind the design of the API for _Combine*_ type patches and but if it were purely for backward compatibility, we could still come up with a more straightforward API here without requiring to introduce the `type` field. 

However, at this point, I am starting to believe the patching case (generic cross-resource referencing) would require more consideration and grow in a different direction, not necessarily related to the deletion-ordering use case not only API-wise but also implementation-wise. 

So, I am questioning whether we would really want to solve the two use cases with one API:
- Are there enough actual use cases that would benefit from combining both with a single API? e.g. I want the resource that I patched from, not deleted before the resource I patched to.
- Would the API/implementation be cleaner and more explicit once we have separate APIs?
