### ISSUE TITLE
`spec.revisionActivationPolicy` is not set based on its parent's policy

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/crossplane#4114]
### What happened?

When I Installed a provider with `spec.revisionActivationPolicy=Manual`, I expected to see that its dependency would also have the same policy. If there are no parents with `spec.revisionActivationPolicy=Automatic` deployed on the cluster, the child resource should have `spec.revisionActivationPolicy=Manual`. 

### How can we reproduce it?

Apply the following manifest and observe that provider-family-gcp will be deployed with `revisionActivationPolicy=Automatic`:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-release-candidates-provider-gcp-container
spec:
  package: xpkg.upbound.io/upbound-release-candidates/provider-gcp-container:v0.34.0
  revisionActivationPolicy: Manual
```

### What environment did it happen in?
Crossplane version: v1.12.1
