### ISSUE TITLE
XRDs have empty top-level description field with kubectl explain

### ISSUE THREAD

**Issue by mbbush** [crossplane/crossplane#4129]
### What happened?
When I specify a `description` field for my XRDs at the top level, the way I would normally do for an openapiv3 spec, it shows up as `<empty>` when I call `kubectl explain` on the custom resource type. 

### How can we reproduce it?
When I define a CompositeResourceDefinition using `kubectl apply -f` pointing to a file containing the following yaml, and then run `kubectl explain xmissingdescriptions` (or similar on `xmissingdescriptions.spec`) I see 
```
DESCRIPTION:
     <empty>
```
rather than the descriptions I included. 

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmissingdescriptions.example.com
spec:
  claimNames:
    kind: MissingDescription
    plural: missingdescriptions
  group: example.com
  names:
    kind: XMissingDescription
    plural: xmissingdescriptions
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: I would like to have this description show up in kubectl explain, but it does not.
          properties:
            spec:
              type: object
              description: I would also like this description to show up in kubectl explain.
              properties:
                id:
                  description: I can put a description here.
                  type: string
                parameters:
                  type: object
                  description: I can put a description here too.
                  properties:
                    stringParameter:
                      type: string
                      description: This shows up fine in kubectl explain.
                    objectParameter:
                      type: object
                      description: This shows up as well.
              required:
                - id
                - parameters
            status:
              type: object
```

### What environment did it happen in?
Crossplane version: 1.11
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.24.13-eks-0a21954
