### ISSUE TITLE
Require containerized Composition Functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4138]
### What problem are you facing?

Today all Composition Functions are OCI containers that take a `FunctionIO` on stdin, mutate it, and write it to stdout. Crossplane runs OCI containers using a sidecar called `xfn`, but we expect there will be other OCI function runner implementations. See [the design document](https://github.com/crossplane/crossplane/blob/e7be8efab0cef960ce979e70c7b5ee6e46ebbc34/design/design-doc-composition-functions.md) for the full background.

While all Functions are currently OCI containers, we designed the API to allow for other types of containers in future. Here's an example of a containerized Composition Function:

```yaml
apiVersion: apiextensions.crossplane.io/v2alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-function
    type: Container
    container:
      image: xkpg.io/my-cool-function:0.1.0
```

We thought about two other possible types of Function - `Webhook` and "interpreter" (e.g. Python). For example:

```yaml
apiVersion: apiextensions.crossplane.io/v2alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-function
    type: Webhook
    webhook:
      url: https://example.org/my-cool-function
```

```yaml
apiVersion: apiextensions.crossplane.io/v2alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-function
    type: Python
    python: |
      # Pretend this is a real function
      print("Hello world!")
```

It turns out that it's actually possible to build many different "types" of functions using an OCI image as an adaptor. For example in https://github.com/crossplane/crossplane/issues/4050 @duizabojul uses a containerized function that just sends the `FunctionIO` it gets to a webhook. At least one other community member has built a similar function, but I now can't find it.

I like this pattern because:

* It simplifies what a Function artifact is - it's always an OCI image.
* It decouples adding and updating support for new Function types from Crossplane releases.

### How could Crossplane help solve your problem?

I suggest we "close the door" on Functions that aren't containers at the Crossplane API level. So all Functions would look like this:

```yaml
apiVersion: apiextensions.crossplane.io/v2alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-function
    image: xkpg.io/my-cool-function:0.1.0
```

Notice that `type: Container` is gone, and `image` is not nested under a `container` block.

Under this model a Webhook function might look like this:

```yaml
apiVersion: apiextensions.crossplane.io/v2alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-function
    image: xkpg.io/webhook-fn:v1.0.0
    config:
      apiVersion: example.org/v1
      kind: Webhook
      url: https://example.org/my-cool-function
```

Similarly, an interpreter function might look like this:

```yaml
apiVersion: apiextensions.crossplane.io/v2alpha1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XPostgreSQLInstance
  functions:
  - name: my-cool-function
    image: xkpg.io/python-fn:v1.0.0
    config:
      apiVersion: example.org/v1
      kind: Python
      script: |
        # Pretend this is real code
        print("Hello world!")
```

It's worth noting that there are certainly some downsides to this. Namely:

* The `config` block is opaque at the `Composition` level, so if you make a mistake (e.g. typo a field, indent something wrong) you won't know about it until you run the Function.
* There's a compute cost associated with running OCI functions, as pointed out in https://github.com/crossplane/crossplane/issues/4050. I would hope we can improve on this though - i.e. build a webhook Function that doesn't have too much overhead.
