### ISSUE TITLE
Support for Querying/Filtering for Import and Observe

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4141]
### What problem are you facing?

Crossplane introduced support for [Observe Only resources](https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md) as an alpha feature with the v1.12 release, which enables observing external resources and representing them as read-only managed resources in the Kubernetes API. To observe a resource, the user needs to provide enough information to identify the external resource uniquely, typically the [external-name annotation](https://docs.crossplane.io/latest/concepts/managed-resources/#external-name) and the [identifier fields](https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md#identifier-fields) if any. 

However, in some cases, it is not convenient to provide this information rather it is more feasible to query and/or filter the external resources with the help of some additional parameters, typically tags, labels, or custom fields. This would enable users to flexibly and efficiently identify and observe/import their resources, especially when dealing with a large number of resources or complex resource structures.

This functionality is left as [future work](https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md#identifier-fields) in the Observe Only resources design primarily because it violates a fundamental principle with managed resources, that is, having a one-to-one relationship between a managed resource and the external resource that it represents. When it comes to querying and filtering, it is possible that:

- There are more than one matching resources
- There are no matching resources
- The matching resource may change in time, e.g., most-recent AMI

So, this functionality should be implemented by an upper layer rather than as additional functionality in the managed resources.

### How could Crossplane help solve your problem?

Possible options proposed in the design doc are (see further details [there](https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md#querying-and-filtering)):

- **Option A**: Introduce a new resource type, `Query Resource`

- **Option B**: Defer this to the Composition layer, specifically, Compositions Functions

**Comment by WolfGanGeRTech** [comment]
There are some AWS resources that would benefit a lot from this, for instance EFS and KMS.
When these resources are created they generate an "id" which we don't know beforehand, so we can't use "external-name". This means that we can't import the resource unless we wait resouces to launch and then update the claim to add the "external-name" with the id generated.

**Comment by clementblaise** [comment]
It would be very handy for AWS Identity Center managed Roles, especially in the context of configuring SSO access to EKS. I haven't found a workaround other than hardcoding the Role name as they are created with a random ID as well.

**Comment by clementblaise** [comment]
@turkenh I had thought about using TF Datasource, but this looks simpler to implement. Anyway, I like the approach now that Functions are set to become the standard for writing compositions with the support of P&T.

In my case, I am authenticating `Provider` using AssumeRole (a combination of a `ControllerConfig` and a `ProviderConfig`); from what I have seen, it seems to be a common practice. Using a single `ControllerConfig` or the new `DeploymentRuntimeConfig` would limit query ability to a single account. I saw @negz [evoked](https://github.com/crossplane/crossplane/issues/3718#issuecomment-1739996309) having a Function input defined as CRDs; it seems like a nice option to offer a generic equivalent of `ProviderConfig` for Functions and could help solve this shortcoming.

**Comment by autarchprinceps** [comment]
Honest question from someone just getting started with crossplane: How do you guys use it without something as basic as a data source that can find resources based on tags or properties?

Crossplane seems to have a lot of really detailed tools to deal with rare problems, but you can't even lookup your subnets, vpcs, etc.?
Do you guys just hardcode everything you could possibly want to lookup in Environments?
Because otherwise I couldn't image how to even write one composition properly, unless it creates every resource itself, not to mention that things like networking are needed for the Kubernetes in which crossplane runs, so you can't even create those in crossplane in the most basic use case.

**Comment by ytsarev** [comment]
@autarchprinceps there are workarounds to this problem https://github.com/upbound/provider-terraform/tree/main/examples/importer

**Comment by danielloader** [comment]
This is a helpful work around but I do agree with the sentiment that data source type functionality is a very important last piece in the user journey for adoption. 

This week I found out the fun way that if you deploy an RDS instance with auto password enabled trying to get the password out of secrets manager to put in the connection secret to export from the composition (as far as I can see) is basically impossible.

Observe only resources that can select cloud resources by their tag or name, rather than their very fragile external ID, is quite an important tool to craft what is nearly always a slightly hybrid environment. It's basically impossible to assume you'll solely use Crossplane for orchestrating absolutely everything. 

I know it's been banded about a few times to do a cloud resource function for a composition to basically wrap AWS CLI or SDK to return values to be consumed but even that feels like a bit of a sticking plaster on the problem.

**Comment by jbw976** [comment]
> but you can't even lookup your subnets, vpcs, etc.?

A concept that may have been missed here is "cross resource references": https://docs.crossplane.io/latest/concepts/compositions/#cross-resource-references

Those have been the most common historical pattern for finding or referring to one resource from another one within Crossplane. For example, see the AWS `Subnet` type that can reference a `VPC` either directly by ID or more commonly by a selector when the ID isn't already known: 
https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.5.0/resources/ec2.aws.upbound.io/Subnet/v1beta1#doc:spec-forProvider-vpcIdSelector

Of course, that's not ideal for the observe only / importing use case, but it seemed like the basic "how does one even use Crossplane" was being called into question, so I wanted to ensure this fundamental concept wasn't being looked over 😇 

For the import / existing resources use case, beyond the potential core functionality that this issue is tracking, @LCaparelli also proposed an interesting functions based approach in https://github.com/crossplane/upjet/issues/408 and the related https://github.com/gympass/function-aws-importer function they have built. Note there's a timestamped link to the community meeting recording where this idea is presented, so watch that too 😎 

Also in the functions realm, functions can request "extra resources", that is essentially a generic replacement for cross resource references. This may be very interesting to you as well, so here are some helpful links:

* Discussed in the docs in this section: https://docs.crossplane.io/latest/concepts/composition-functions/#how-composition-functions-work 
* A specific function that provides this functionality: https://github.com/crossplane-contrib/function-extra-resources
* The design doc that covers this topic: https://github.com/crossplane/crossplane/blob/master/design/design-doc-composition-functions-extra-resources.md.

Hope that helps @autarchprinceps @danielloader 🙇‍♂️

**Comment by hhami-newday** [comment]
+1 on this concept being natively supported being important in my eyes for adoption

**Comment by cedricmckinnie** [comment]
Any thoughts on repurposing the hard work from the Terraformer project to scan the [cloud provider](https://github.com/GoogleCloudPlatform/terraformer/tree/master/providers) and instead of generating HCL code, simply generate the Crossplane resources?

The other half of the implementation would be designing the API that users can actually interact with. Take a look at the [Capabilities](https://github.com/GoogleCloudPlatform/terraformer/tree/master?tab=readme-ov-file#capabilities) section of the readme. It provides filtering functionality as input already and can output to json which seems like it could be fairly easily restructured into Crossplane objects.

Now that Crossplane has the Observe-only management policy feature, really all that's needed is the ID of the objects the import.

This would also give everyone in the Crossplane ecosystem the ability to plug their own provider in and define the data source logic. I've used Terraformer in the past and it worked _very_ well for adopting existing infrastructure.

As for the specifics of the implementation, I'll leave that to folks with more in-depth knowledge of the runtime but one possibility to trial this would be to transform Terraformer into a Crossplane Function package similar to existing ones like KCL etc. It would accept the args of the CLI as input and produce the objects upon rendering. Of course additional validation would make sense here but hopefully my point comes across clearly.

Generalized Example:

https://github.com/GoogleCloudPlatform/terraformer/tree/master?tab=readme-ov-file#resource-id

* User provides resource type and a filter as Crossplane Function input
```yaml
resources: subnets.ec2.aws.upbound.io
filters:
  vpc: myvpcid
  regions: us-east-1
```
* All subnets associated with the VPC are returned
```yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: subnet-1-name
  annotations:
    crossplane.io/external-name: subnet-id # <- insert subnet id here
spec:
  forProvider:
    region: us-east-1
  managementPolicies: ["Observe"]
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: subnet-2-name
  annotations:
    crossplane.io/external-name: subnet-2-id # <- insert subnet id here
spec:
  forProvider:
    region: us-east-1
  managementPolicies: ["Observe"]
```

**Comment by cedricmckinnie** [comment]
I'm just now seeing this proposal:

https://github.com/crossplane/crossplane/blob/main/design/design-doc-observe-only-resources.md#future-work

More specifically this statement appears to be perhaps a little outdated maybe?

> We will not support querying and filtering at managed resources level since it violates a fundamental principle with the managed resources, that is, having a one-to-one relationship between a managed resource and the external resource that it represents.

I'm not sure I agree that a query returning multiple resources is the problem. I think this is completely acceptable and necessary. The problem seems to be when a _plurality_ of data from this query misaligns with a _singular_ resource. I don't see why the user cannot query multiple items and pass them into a variable context (perhaps the Crossplane Context which can be namespaced). This would allow the user to then process the data from a generic "data source" variable context  and assign the result directly to a local function variable or to send it to the next function pipeline step. This seems very similar to something like [getCompositeResource](https://github.com/crossplane-contrib/function-go-templating/blob/main/example/functions/getCompositeResource) where data/objects can be accessed from a dedicated/reserved context. 

To alleviate concerns of the following criteria specified:

> * There are more than one matching resources
> * There are no matching resources
> * The matching resource may change in time, e.g., most-recent AMI

I believe that resource definitions already validate the schema so I'm not these criteria apply anymore.

IMO, `crossplane.io/external-name` seems to be the main point of focus. Example from my above comment:

```yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: subnet-1-name
  annotations:
    crossplane.io/external-name: subnet-id  # <- Ultimately, external-name decides how resources are imported.
spec:
  forProvider:
    region: us-east-1
  managementPolicies: ["Observe"]
```

1) `external-name` already accepts a singular string and not an array/map.

2) Missing/Empty value can be validated by the user since if it's passed into a context first and retrieved by the user for usage (a helper function could probably be easily added for convenience). 

3) If the underlying resource changes over time, the ID stays the same anyway so there should be no issue since this is just an Observer. If the ID changes in Terraform however, it either throws an error or terraform thinks that it has been removed and thus destroys/recreates the resource of interest. I don't see why this should be different.

4) Using most-recent AMI data source as an example feels like an outlier because the nature of this is provider-specific. I don't think it's possible to capture every use case generically but there should be a way for data source developers to implement this logic themselves with docs. IMO, AMI selection filtering should be offloaded to the user's discretion to be pinned just like it is for the [terraform data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami#example-usage) but with a disclaimer that it is intrinsically a data source with dynamic results.

Overall, querying multiple resources seems to be an issue of the past. It seems to be that this problem might be solvable by using OSS code that has already been implemented. My conviction here may be off-base but I'm fascinated by this problem and interested to hear the thoughts of others!

**Comment by cedricmckinnie** [comment]
I took a closer look at the AWS provider as an example and I think I can narrow down the scope more and express my proposal more clearly with pseudo-code. 

We design make a ResourceQuery object which as mentioned earlier, provides the API to retrieve the identifiers. Something like this:

```yaml
apiVersion: resourcequery.aws.foo.bar
kind: ResourceQuery
metadata:
    name: subnets-query
spec:
    resources: subnets.ec2.aws.foo.bar
    filters:
      vpc: myvpcid
      regions: us-east-1
```

Provider maintainers would need to enhance External Connectors to not only include Observe, Create, Update, Delete functions but also an additional function called Query. Provider maintainers would be responsible for filling in the provider-specific logic i.e. DescribeSubnets. This would basically just be the provider logic from Terraformer. This would mimic the Observe functionality but instead of mapping a single `external-name` to a single managed resource, it would use `resourcequery.spec.filter` to query all relevant objects and dump them into the function pipeline context using the ResourceQuery name to avoid collisions within the context. 

```go
func (e *external) Query(ctx context.Context, rq resourcequery.ResourceQuery) (managed.ExternalObservation, error) {
  // Query for objects based on the filter
  // Write results to an EnvironmentConfig object
  // Send errors to ResourceQuery events (or possibly EnvironmentConfig object status field if easier to access)
}
```

The user could then retrieve the queried data from the function context (generated EnvironmentConfigs) and feed that data into Observed Managed resource templates. 

Rough Example:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: consume-subnets
spec:
  mode: Pipeline
  pipeline:

    - step: environmentConfigs
      functionRef:
        name: function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: example-environment

    - step: template-observed-resources
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ subnets := index .context "apiextensions.crossplane.io/environment" "queries" "subnets-query" }}
            
            {{- range $i, $subnet := $params.subnets }}
            ---
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Subnet
            metadata:
              name: observed-subnet-{{ $i }}
              annotations: 
                crossplane.io/external-name: observed-subnet-{{ $i }}
              labels:
                vpcId: {{ $subnet.status.atProvider.vpcId }}
            spec:
              managementPolicies: ["Observed"]
            {{- end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready

```

Once the Observed Managed resources are Healthy they can then be referenced/selected by other Managed resources as usual now that they would be recognized by Crossplane i.e. `clusters.eks.aws.upbound.io.spec.forProvider.vpcConfig.subnetIdSelector`.

To debug, Query/Filtering errors could be surfaced in the ResourceQuery and users can view a snapshot of the data sources simply by using kubectl to list/get/describe the EnvironmentConfig objects generated by the ResourceQuery. Having a k8s-native way to see what the data source is querying seems like a big advantage.

If the ResourceQuery is deleted, the EnvironmentConfigs associated with it must be GC'ed as well.

Overall, query data should be nothing but ephemeral reference data for controllers that does not collide with actual Managed Resources. I believe this proposal:
* Provides a generic way to execute queries that delegate logic to provider plugins
* Avoids collision issues by using EnvironmentConfigs leaving the user to decide how Observed objects are generated to import/consume existing infrastructure. 
* Provides a way to surface errors, troubleshoot and easily iterate on query execution uninvasively.
* Integrates well with Compositions by providing a way to query and supply data to composition pipelines in order to populate other objects.
* Leverages mostly existing Crossplane functionality without introducing any new constructs except for the ResourceQuery API.
