### ISSUE TITLE
Inject caBundle into CompositeResourceDefinition for conversions

### ISSUE THREAD

**Issue by fhopfensperger** [crossplane/crossplane#4149]
Hi crossplane team,

### What problem are you facing?
As discussed with @ytsarev we are currently facing the issue, that we want convert XRDs from one to another version using conversions webhooks like defined here https://github.com/crossplane/crossplane/pull/3940. To get it running, we need to define a caBundle in the `spec.conversion.webhook.clientConfig.caBundle` field of the `CompositeResourceDefinition` according to https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#service-reference. As we currently have a big number of XRDs (stored inside a git repository, managed by different people) we would need to add the `caBundle` to every XRD manually and if the certificate changes we would need to change it in every XRD. 

There are multiple options how we could inject this needed information on the fly:

1. As CA Injector from cert-manager actually is made exactly for this purpose, we could add an annotation `cert-manager.io/inject-ca-from: example1-ns/webhook1-certificate<or-secret>` to the CRD and CA Injector would care about the `caBundle`. However, currently due to https://github.com/crossplane/crossplane/pull/3124 annotations of a XRD are not propagated to the rendered Claim/Composite CRDs

2. Implement a secret selector property in XRDs like `spec.conversion.webhook.secretSelector` and Crossplane core component would inject the secret into the rendered Claim/Composite CRDs. But this seems not that easy to get it running, as [extv1.CustomResourceConversion](https://github.com/crossplane/crossplane/blob/master/apis/apiextensions/v1/xrd_types.go#LL97C20-L97C44) is reusing the struct from upstream k8s 

### How could Crossplane help solve your problem?

- Define which annotations are propagated from XRD to CRD
- SecretSelector
- ... ?

**Comment by phisco** [comment]
Thanks @fhopfensperger, this sounds like a totally reasonable request!

I would discard the `secretSelector` option, not because we are reusing the upstream struct, we could definitely switch to our own struct with the added field, but because that would be a different API w.r.t. CRDs and handling secrets would add a layer of complexity which I don't think we need. 

You were suggesting to have some kind of filtering of the propagated annotations, that could definitely be done either by allowing users to specify all the exact keys or a set of regexes matching the keys they want to have propagated, e.g.:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
  annotations:
    "cert-manager.io/inject-ca-from": "example1-ns/webhook1-certificate"
spec:
  propagatedAnnotations:                               # <======= TODO: find a better name
  - "cert-manager.io/inject-ca-from"             # or "cert-manager.io/*" if we want to use regexes, maybe we could settle on prefixes too
  group: database.example.org
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  versions:
  ...
```
An empty list would mean no annotation will be propagated, which would not break the current behaviour.

But then, what if a user wanted an annotation to be present on the CRD, but not at all on the XRD? Maybe because, for example, whatever is consuming that annotation is blindly checking it on all resources having that configured. That would not be possible to do with this approach.

Another option solving the problem above would be to allow users to specify separately both the key and the value of the annotations they want to be set on the CRD, without needing to set it also on the XRD.
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
  annotations:
    "example.com/some-other-annotation": "not-propagated"
spec:
  annotations:                               # <======= TODO: find a better name
    "cert-manager.io/inject-ca-from": "example1-ns/webhook1-certificate"
  group: database.example.org
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  versions:
  ...
```
On one side this would require setting annotations two times if they wanted to have it on both the XRD and the created CRD, but on the other side this would allow covering also the use case above ("annotation on CRD, but not on XRD") and would be much more explicit.

Any thought on the considered approaches?

CC @ytsarev

**Comment by phisco** [comment]
Would be nice to have also label handled with the same approach.
Longer term we could think of having some kind of `template`/`crdTemplate` similar to what Deployments do with the `podTemplate`, which could solve this and other missing propagated fields issues we are seeing.

**Comment by fhopfensperger** [comment]
Thanks @phisco for taking care of this. I like both of your suggestions, and reading your thoughts I have another idea that might work.

What about adding additional metadata struct to `names` and `claimNames` this way we could actually control if these annotations/labels are only added to composite and/or to claim. It could look like this:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
  annotations:
    "example.com/some-other-annotation": "not-propagated"
spec:
  group: database.example.org
  names:
    metadata:
       labels: 
         example.io/key: value
       annotations: 
         cert-manager.io/inject-ca-from: example1-ns/webhook1-certificate
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    metadata:
       labels: 
         example.io/key: value
       annotations: 
         cert-manager.io/inject-ca-from: example1-ns/webhook1-certificate
    kind: PostgreSQLInstance
    plural: postgresqlinstances
...
```

**Comment by phisco** [comment]
Mmm, being that `names` is mirroring the [names](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/#CustomResourceDefinitionSpec) section of CRDs I think it would be surprising to have them defined in there.

Then I'm not sure we should provide a way to set default labels and annotations on claims too, that feels counterintuitive, would you have a specific use case for that?

**Comment by fhopfensperger** [comment]
Ah, I see, then maybe it doesn't make much sense to abuse the `names` section for this. I don't have a direct use case, but I thought I could keep it very flexible for upcoming cases. 

Visualizing the second approach of yours with `template`, it might look like this, and it follows the approach done for a `Deployment`:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
  annotations:
    "example.com/some-other-annotation": "not-propagated"
spec:
  template:
    metadata:
      labels: 
        example.io/key: value
      annotations: 
        cert-manager.io/inject-ca-from: example1-ns/webhook1-certificate
      # claimAnnotations:  # <-- for the feature if we really need to add things only to claim/composite
      #  cert-manager.io/inject-ca-from: example1-ns/webhook1-certificate
  group: database.example.org
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
...

**Comment by phisco** [comment]
I'd say the template approach should be something we evaluate for future iterations of the API and I was thinking about something like:
```yaml
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
  annotations:
    "example.com/some-other-annotation": "not-propagated"
spec:
  template:
    metadata:
      labels: 
        example.io/key: value
      annotations: 
        cert-manager.io/inject-ca-from: example1-ns/webhook1-certificate
      # claimAnnotations:  # <-- for the feature if we really need to add things only to claim/composite
      #  cert-manager.io/inject-ca-from: example1-ns/webhook1-certificate
    spec:
      group: database.example.org
      names:
        kind: XPostgreSQLInstance
        plural: xpostgresqlinstances
      ...
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
```
In which everything transparently passed to the underlying CRD should be defined below `spec.template.spec`, similarly to what already happens for Deployments.

Given that labels are already propagated at the moment and no one complained about that, I would just handle annotations here, keeping the door open for that later if we need to, so I would still go with my original proposal (`spec.annotations`), so:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
  annotations:
    "example.com/some-other-annotation": "not-propagated"
spec:
  annotations:                               # <======= TODO: find a better name
    "cert-manager.io/inject-ca-from": "example1-ns/webhook1-certificate"
  group: database.example.org
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  versions:
  ...
```
or maybe put it under `spec.metadata.annotations`:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
  annotations:
    "example.com/some-other-annotation": "not-propagated"
spec:
  metadata:
    annotations:                               # <======= TODO: find a better name
      "cert-manager.io/inject-ca-from": "example1-ns/webhook1-certificate"
  group: database.example.org
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  versions:
  ...
```

**Comment by fhopfensperger** [comment]
@phisco Both things would work for me.

Should I create a PR for it, or do you want to do it?

**Comment by phisco** [comment]
That would be awesome if you could work on it! Contributions are always welcome! Let me just ping @negz and @turkenh for an opinion on the API

**Comment by negz** [comment]
I know this is kind of a weird perspective given how similar an XRD's schema is to a CRD's, but I'm a little worried about strongly coupling ourselves (at the XRD API level) to the fact that XRDs are implemented by CRDs. For example I could imagine an XRD on a future kcp-aware version of Crossplane being rendered to an [APIResourceSchema](https://docs.kcp.io/kcp/v0.11/concepts/apis-in-kcp/#define-apiresourceschemas) rather than (directly) to a CRD.

I wonder, is there some way we can get the CRDs Crossplane is producing annotated without Crossplane core needing new functionality? I'm imagining a small, separate controller that:

* Looks for CRDs owned by an XRD
* Adds the appropriate annotation to them

**Comment by phisco** [comment]
> I appreciate the desire to come up with a generic solution with a flexible enough API, however wondering if we could rather go with (actually start with) a more pragmatic solution here and propagate whitelisted annotations from XRDs to CRDs, starting with the cert-manager one.

@turkenh Where should the whitelist be defined? At the XRD level? Or were you suggesting to hardcode it on our side directly?

**Comment by phisco** [comment]
@turkenh I feel having a separate field as I was suggesting in the xrd is not much effort and I don't see any drawback, it would be explicit and not surprising to users.

**Comment by turkenh** [comment]
> @turkenh I feel having a separate field as I was suggesting in the xrd is not much effort and I don't see any drawback, it would be explicit and not surprising to users.

Agreed that it does not require a lot of effort, but I would prefer to be cautious about extending the API unless we know that it is needed. I feel like the use case here is generic enough that we can make an exception without exposing it in the API.

I am not aware of any, but if there were some use cases where someone wants to propagate some "custom" annotations (e.g. specific to their company), then it would make more sense to discuss how to expose it in the API.

With that said, if we decide to proceed with extending the API, the following, @phisco proposed [above](https://github.com/crossplane/crossplane/issues/4149#issuecomment-1597322613) is the one that I liked most:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
  annotations:
    "example.com/some-other-annotation": "not-propagated"
spec:
  metadata:
    annotations:
      "cert-manager.io/inject-ca-from": "example1-ns/webhook1-certificate"
  group: database.example.org
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  versions:
  ...
```

But also wondering if there could be some cases where someone wants to annotate composite but not claim 🤔
