### ISSUE TITLE
Deletion from composition is not propagated to the composed objects

### ISSUE THREAD

**Issue by darkmuggle** [crossplane/crossplane#4162]
### What happened?

Composed objects where a new version of the composition removes a value did not remove it from the composed objects. Instead, the new composition merged with the existing. The effect is that if you want to delete the value, you have to manually patch it.

This was observed with both the Helm and Kubernetes providers. 

### How can we reproduce it?

Consider this composition: 
```
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kubeburnerservices.mcp.upbound.io 
spec:
  compositeTypeRef:
    apiVersion: mcp.upbound.io/v1alpha1
    kind: KubeBurnerService
  resources:
    - name: release-prometheus
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: prometheus
        spec:
          providerConfigRef:
            name: host-cluster
          forProvider:
            chart:
              name: kube-prometheus-stack
              repository: "https://prometheus-community.github.io/helm-charts"
            namespace: kube-burner
            wait: true
            values:
               foo: bar
```

Then update the `spec.resources[0].spec.forProvider` with:
```
values:
  bar: foo
```

On reconciliation, the composed object will have:
```
values:
   foo: bar
   bar: foo
```
              
### What environment did it happen in?
Crossplane version: 1.12.0
