### ISSUE TITLE
Crossplane pods crash when using `FromEnvironmentFieldPath` patch

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane/crossplane#4166]
### What happened?

Right after enabling environmentConfig alpha feature, pod start crashing when there's a `FromEnvironmentFieldPath` patch inside a Composition.

### How can we reproduce it?

One composition creates and populates the EnvironmentConfig as follows:

```yaml
    - name: env
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: EnvironmentConfig
        # metadata:
          # name: patched
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.labels.cluster-name
      - type: CombineFromComposite
        toFieldPath: metadata.name
        combine:
          strategy: string
          variables:
          - fromFieldPath: spec.resourceConfig.providerConfigName  # pre
          - fromFieldPath: spec.resourceConfig.region  # us-east-1
          - fromFieldPath: spec.parameters.clusterName  # test
          string:
            fmt: "%s-%s-%s"  # pre-us-east-1-test
      # Labels used later on to select which environmentConfig to read from
      - type: FromCompositeFieldPath
        fromFieldPath: spec.resourceConfig.region
        toFieldPath: metadata.labels.region
      - type: FromCompositeFieldPath
        fromFieldPath: spec.resourceConfig.providerConfigName
        toFieldPath: metadata.labels.providerConfigName
      # EnvironmentConfig data
      - fromFieldPath: status.accountId
        toFieldPath: data.accountId
        policy:
          fromFieldPath: Required
      - fromFieldPath: status.oidcIssuer  # filled in by EKS Cluster resource
        toFieldPath: data.oidcIssuer
        policy:
          fromFieldPath: Required
```

And another Composition trying to read from it as:

```yaml
  spec:
  environment:
    environmentConfigs:
      - selector:
          matchLabels:
          - key: clusterName
            type: FromCompositeFieldPath
            valueFromFieldPath: spec.parameters.clusterName
          - key: region
            type: FromCompositeFieldPath
            valueFromFieldPath: spec.resourceConfig.region
          - key: providerConfigName
            type: FromCompositeFieldPath
            valueFromFieldPath: spec.resourceConfig.providerConfigName
  patchSets:
    - name: common-patches
      patches:
        # Set the `cluster-name` metadata label
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: metadata.labels.cluster-name
        # Set the deletion policy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        # Pass parameters
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.clusterName
          toFieldPath: spec.parameters.clusterName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.component
          toFieldPath: spec.parameters.component
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.namespace
          toFieldPath: spec.parameters.serviceAccount.namespace
          policy: &required
            fromFieldPath: Required
        - type: FromEnvironmentFieldPath  # <-- OFFENDING PATCH
          fromFieldPath: oidcIssuer
          toFieldPath: spec.parameters.oidcIssuer
          policy: *required
        - type: FromCompositeFieldPath
          fromFieldPath: spec.compositionUpdatePolicy
          toFieldPath: spec.compositionUpdatePolicy
        - type: FromEnvironmentFieldPath  # <-- OFFENDING PATCH
          fromFieldPath: accountId
          toFieldPath: spec.parameters.accountId
          policy: *required
        # Pass resourceConfig
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.resourceConfig.region
  resources:
   [...]
```

### What environment did it happen in?
Crossplane version:  1.22.2-stable (Digest:sha256:9c6ad809512b8396e1e92a37de6ad9136b3219b15b752d42eb366b0fe6544869)

Logs:
```
crossplane-6f77cddc4b-mv56v crossplane 2023-06-09T14:52:42Z     INFO    crossplane      Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference  {"controller": "composite/bar.compositions.com", "object": {"name":"external-secrets-operator-nw-us-east-2-teide"}, "namespace": "", "name": "foo-pre", "reconcileID": "f4a98c1c-58f1-4ddc-b4a4-bee88b271683"}
crossplane-6f77cddc4b-mv56v crossplane panic: runtime error: invalid memory address or nil pointer dereference [recovered]
crossplane-6f77cddc4b-mv56v crossplane  panic: runtime error: invalid memory address or nil pointer dereference
crossplane-6f77cddc4b-mv56v crossplane [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1919875]
crossplane-6f77cddc4b-mv56v crossplane
crossplane-6f77cddc4b-mv56v crossplane goroutine 1795 [running]:
crossplane-6f77cddc4b-mv56v crossplane sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
crossplane-6f77cddc4b-mv56v crossplane  sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
crossplane-6f77cddc4b-mv56v crossplane panic({0x1e73420, 0x34207f0})
crossplane-6f77cddc4b-mv56v crossplane  runtime/panic.go:884 +0x213
crossplane-6f77cddc4b-mv56v crossplane github.com/crossplane/crossplane/internal/controller/apiextensions/composite/environment.(*APIEnvironmentSelector).buildEnvironmentConfigRefFromRef(...)
crossplane-6f77cddc4b-mv56v crossplane  github.com/crossplane/crossplane/internal/controller/apiextensions/composite/environment/selector.go:103
crossplane-6f77cddc4b-mv56v crossplane github.com/crossplane/crossplane/internal/controller/apiextensions/composite/environment.(*APIEnvironmentSelector).SelectEnvironment(0xc00a758ac0?, {0x247b1a8, 0xc00b413ef0}, {0x24987d8?, 0xc00a2fbd98?}, 0xc00b680fc0)
crossplane-6f77cddc4b-mv56v crossplane  github.com/crossplane/crossplane/internal/controller/apiextensions/composite/environment/selector.go:86 +0x215
crossplane-6f77cddc4b-mv56v crossplane github.com/crossplane/crossplane/internal/controller/apiextensions/composite.(*Reconciler).Reconcile(0xc00a229dc0, {0x247b1e0, 0xc00b413e60}, {{{0x0, 0x0}, {0xc00a953cb0, 0x2c}}})
crossplane-6f77cddc4b-mv56v crossplane  github.com/crossplane/crossplane/internal/controller/apiextensions/composite/reconciler.go:555 +0x3923
crossplane-6f77cddc4b-mv56v crossplane github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc00a7a2500, {0x247b1e0, 0xc00b413e60}, {{{0x0?, 0x0?}, {0xc00a953cb0?, 0x40dfe7?}}})
crossplane-6f77cddc4b-mv56v crossplane  github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230330081344-bc8be4cd89f3/pkg/ratelimiter/reconciler.go:54 +0x16b
crossplane-6f77cddc4b-mv56v crossplane sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x247b1e0?, {0x247b1e0?, 0xc00b413e60?}, {{{0x0?, 0x1d71e40?}, {0xc00a953cb0?, 0x0?}}})
crossplane-6f77cddc4b-mv56v crossplane  sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
crossplane-6f77cddc4b-mv56v crossplane sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00a309a40, {0x247b138, 0xc00a7a2550}, {0x1f1d000?, 0xc00a9317c0?})
crossplane-6f77cddc4b-mv56v crossplane  sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x35f
crossplane-6f77cddc4b-mv56v crossplane sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00a309a40, {0x247b138, 0xc00a7a2550})
crossplane-6f77cddc4b-mv56v crossplane  sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
crossplane-6f77cddc4b-mv56v crossplane sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
crossplane-6f77cddc4b-mv56v crossplane  sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
crossplane-6f77cddc4b-mv56v crossplane created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
crossplane-6f77cddc4b-mv56v crossplane  sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587

```

* Cloud provider or hardware configuration
AWS
* Kubernetes version (use `kubectl version`)
```
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.9-eks-0a21954", GitCommit:"eb82cd845d007ae98d215744675dcf7ff024a5a3", GitTreeState:"clean", BuildDate:"2023-04-15T00:37:59Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
EKS
* OS (e.g. from /etc/os-release)
AL2
* Kernel (e.g. `uname -a`)
5.10.178-162.673.amzn2.x86_64

**Comment by phisco** [comment]
Hi, can you try specifying the type of the environmentconfig selector explicitly?
```
  environment:
    environmentConfigs:
      - type: Selector          # <= here
         selector:
          matchLabels:
          - key: clusterName
            type: FromCompositeFieldPath
            valueFromFieldPath: spec.parameters.clusterName
          - key: region
            type: FromCompositeFieldPath
            valueFromFieldPath: spec.resourceConfig.region
          - key: providerConfigName
            type: FromCompositeFieldPath
            valueFromFieldPath: spec.resourceConfig.providerConfigName
```
