### ISSUE TITLE
XRC connection details: cannot establish control of existing connection secret

### ISSUE THREAD

**Issue by jaylevin** [crossplane/crossplane#4172]
### What happened?

After the XR and underlying composed resources all reach healthy/ready status, the XRC fails with this error:
```sh

2023-06-13T03:44:43Z	DEBUG	crossplane.events	cannot propagate connection details from composite: cannot establish control of existing connection secret	
{
    "type": "Warning",
    "object": {
        "kind": "ConfluentKafka",
        "namespace": "test",
        "name": "confluent-kafka",
        "uid": "0c42e53d-1fb2-4ce0-83b5-35b98eee44c6",
        "apiVersion": "confluent.mygroup.io/v1alpha1",
        "resourceVersion": "13678088"
    },
    "reason": "PropagateConnectionSecret"
}
```

The error doesn't make sense to me because the XRC `publishConnectionDetailsTo.name` is referring to a secret that does not exist in the secret store, so I'm not sure why it's trying to establish control of the XR/MR connection secret. Any help/pointers would be greatly appreciated.

### How can we reproduce it?
I'm following the [Vault as Secret Store](https://docs.crossplane.io/v1.10/guides/vault-as-secret-store/) on the crossplane website.

<details closed>
<summary>XRC</summary>
<br>

```yaml
apiVersion: confluent.mygroup.io/v1alpha1
kind: ConfluentKafka
metadata:
  name: confluent-kafka
  namespace: test
spec:
  parameters: {}
  publishConnectionDetailsTo:
    name: xrc-confluent-connection-details
    configRef:
      name: vault-default
```

</details>

<details closed>
<summary>composition.yaml</summary>
<br>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
...
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: vault-default
...
  resources:
    - name: api-key
      base:
        apiVersion: confluent.mygroup.io/v1alpha1
        kind: APIKey
      connectionDetails:
        - fromConnectionSecretKey: api_key_id
        - fromConnectionSecretKey: api_key_secret
        spec:
          publishConnectionDetailsTo:
            name: mr-connection-secret
            configRef:
              name: vault-default
          forProvider:
            ...
```
</details>

<details closed>
<summary>XRD</summary>
<br>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xconfluentkafkas.my-group.io
spec:
  group: confluent.my-group.io
  names:
    kind: XConfluentKafka
    plural: xconfluentkafkas
  claimNames:
    kind: ConfluentKafka
    plural: confluentkafkas
  connectionSecretKeys:
    - api_key_id
    - api_key_secret
```
</details>

After deploying these resources:
- All composed resources reach ready/synced status. The API Key MR generates the connection detail in Vault successfully.
- The XR reaches ready/synced status. The XR generates the connection detain in Vault succesfully.
- The XRC does not reach ready status. The events show `cannot propagate connection details from composite: cannot establish control of existing connection secret`. I'm unsure how to interpret this error because from my perspective, I have followed the [Vault as Secret Store](https://docs.crossplane.io/v1.10/guides/vault-as-secret-store/) guide. Was there something I missed or is this a bug?

### What environment did it happen in?
Crossplane version: v1.11.3
