### ISSUE TITLE
XFN doesn't let you make invalid resources valid

### ISSUE THREAD

**Issue by mikebryant** [crossplane/crossplane#4190]
### What happened?

We're trying to work around the lack of `initProvider` in the pagerduty provider, by setting up a composition function to add the `forProvider.layer` if it's new, or use the observed one if it's been changed in the PagerDuty UI

We got these logs:
```
2023-06-15T14:00:31Z	DEBUG	crossplane	composed resource "pagerdutyschedule": cannot use dry-run create to name composed resource: Schedule.schedule.pagerduty.crossplane.io "chapter-platform-test-7xl2d-tgfk2" is invalid: spec.forProvider.layer: Required value	{"controller": "defined/compositeresourcedefinition.apiextensions.crossplane.io", "controller": "composite/xpagerdutyteams.observability.nwboxed.com", "request": "/chapter-platform-test-7xl2d", "uid": "fb2bc076-7239-41b4-94af-f6eb0695d20e", "version": "758450644", "name": "chapter-platform-test-7xl2d"
```

And we observed in the EKS audit log: `[Schedule.schedule.pagerduty.crossplane.io](http://schedule.schedule.pagerduty.crossplane.io/) "chapter-platform-test-7xl2d-bqws9" is invalid: spec.forProvider.layer: Required value`

Did debug the function manually, and when run against a FunctionIO object, my function was adding the appropriate `forProvider.layer` section. Also verified this by adding the output to `results`

Looks like if the base resource isn't valid, it all breaks somewhere

### How can we reproduce it?

Composition:
```
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpagerdutyteams.observability.nwboxed.com
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: pagerduty-crossplane
    app.kubernetes.io/instance: pagerduty-crossplane
    app.kubernetes.io/part-of: pagerduty
spec:
  group: observability.nwboxed.com
  names:
    kind: XPagerDutyTeam
    plural: xpagerdutyteams
  claimNames:
    kind: PagerDutyTeam
    plural: pagerdutyteams
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            properties:
              name:
                description: The name of the team.
                type: string
            required:
            - name
            type: object
          status:
            properties:
              teamID:
                description: Team ID (For Referencing)
                type: string
            type: object
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpagerdutyteams.observability.nwboxed.com
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: pagerduty-crossplane
    app.kubernetes.io/instance: pagerduty-crossplane
    app.kubernetes.io/part-of: pagerduty
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: observability.nwboxed.com/v1
    kind: XPagerDutyTeam
  environment:
    environmentConfigs:
    - selector:
        matchLabels:
        - key: kind
          type: Value
          value: tag
        - key: provider
          type: Value
          value: pagerduty
        - key: tag
          type: Value
          value: managed-by-crossplane
      type: Selector
  functions:
  - name: default-layers
    config:
      apiVersion: unused/v1
      kind: Config
      spec:
        expression: >-
          (.desired.resources[]? | select(.name == "pagerdutyschedule") | .resource.spec.forProvider.layer) = (
            (.observed.resources[]? | select(.name == "pagerdutyschedule") | .resource.spec.forProvider.layer)
            //
            ([{
              "name": "Edit me",
              "rotationTurnLengthSeconds": 604800,
              "rotationVirtualStart": "2023-01-01T09:00:00+00:00",
              "start": "2023-01-01T09:00:00+00:00",
              users: ["P4137PH"],
            }])
          )
          | .results += [{"message": (.desired.resources[]? | select(.name == "pagerdutyschedule") | tostring), "severity": "Warning"}]
        expression2: >-
          .results += [{"message": (. | tostring), "severity": "Fatal"}]
    container:
      image: docker.io/mikebryant/crossplane-xfn-jq:0.0.2
    type: Container
  resources:
  - name: pagerdutyteam
    base:
      apiVersion: team.pagerduty.crossplane.io/v1alpha1
      kind: Team
      spec:
        deletionPolicy: Delete
    patches:
    - fromFieldPath: spec.name
      toFieldPath: spec.forProvider.name
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: status.teamID
  - name: pagerdutytagassignment
    base:
      apiVersion: tag.pagerduty.crossplane.io/v1alpha1
      kind: Assignment
      spec:
        deletionPolicy: Delete
        forProvider:
          entityType: teams
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: status.teamID
      policy:
        fromFieldPath: Required
      toFieldPath: spec.forProvider.entityId
    - type: FromEnvironmentFieldPath
      fromFieldPath: tagID
      policy:
        fromFieldPath: Required
      toFieldPath: spec.forProvider.tagId
  - name: pagerdutyschedule
    base:
      apiVersion: schedule.pagerduty.crossplane.io/v1alpha1
      kind: Schedule
      spec:
        deletionPolicy: Delete
        forProvider:
          description: Automated Schedule managed by Crossplane, except for the layers
          layer: []
          timeZone: Europe/London
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: status.teamID
      policy:
        fromFieldPath: Required
      toFieldPath: spec.forProvider.teams[0]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.name
      policy:
        fromFieldPath: Required
      toFieldPath: spec.forProvider.name
```

Function (at [docker.io/mikebryant/crossplane-xfn-jq:0.0.2](http://docker.io/mikebryant/crossplane-xfn-jq:0.0.2)):
```
#!/bin/bash

set -euo pipefail

set -x

INPUT=$(yq --output-format json)

EXPRESSION=$(jq -r '.config.spec.expression // ".results += [{\"message\": \".config.spec.expression is required\", \"severity\": \"Fatal\"}]"' <<< "${INPUT}")

jq "${EXPRESSION}" <<< "${INPUT}"

```

### What environment did it happen in?
Crossplane version: v1.12.2
