### ISSUE TITLE
Composition claims with additionalProperties Not syncing

### ISSUE THREAD

**Issue by bradkwadsworth-mw** [crossplane/crossplane#4193]
### What happened?
When creating a `CompositeResourceDefinition` with a field of `type: object` and `additionalProperties`, the deletion of created key values are not synced and are always recreated.

### How can we reproduce it?
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xprojects.gcp.platform.example.com
spec:
  group: gcp.platform.example.com
  names:
    kind: XProject
    plural: xprojects
  claimNames:
    kind: ProjectClaim
    plural: projectclaims
  defaultCompositionRef:
    name: xprojects.gcp.platform.example.com
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
......
                  labels:
                    type: object
                    additionalProperties:
                      type: string
                    description: A set of key/value label pairs to assign to the project.
.......
```
Initial manifest
```yaml
---
apiVersion: gcp.platform.example.com/v1alpha1
kind: ProjectClaim
metadata:
  name: foobar
  namespace: default
spec:
  parameters:
.....
    labels:
      foo: bar
      biz: baz
```
Created claim
```
apiVersion: gcp.platform.example.com/v1alpha1
kind: ProjectClaim
metadata:
  name: foobar
  namespace: default
spec:
  parameters:
.....
    labels:
      biz: baz
      foo: bar
.....
```
Delete the spec.parameters.labels.biz field.

The resource never updates and still shows
```
apiVersion: gcp.platform.example.com/v1alpha1
kind: ProjectClaim
metadata:
  name: foobar
  namespace: default
spec:
  parameters:
.....
    labels:
      biz: baz
      foo: bar
.....
```
### What environment did it happen in?
Crossplane version:  1.12.2
Kubernetes version: v1.26.3
