### ISSUE TITLE
XFN functions fail to run on GKE due to default AppArmour denying mount inside pod

### ISSUE THREAD

**Issue by haraldsk** [crossplane/crossplane#4228]
### What happened?

All composition functions on GKE 1.24 cluster running Crossplane 1.11.3 fails with the following log message in the crossplane container:

`sources: cannot run Composition Function pipeline: cannot run function "template-redacted-xyz": cannot run container: rpc error: code = Unknown desc = exit status 1: xfn: error: spark.Command.Run(): OCI runtime error: exit status 1`

After instrumenting the code custom debug code the failure was found while xfn is running the crun run command:

`crun --root=/xfn/runtime run  --bundle=/xfn/c/101205c0-0711-47fe-b26b-b1a79452dc40101205c0-0711-47fe-b26b-b1a79452dc40`

returns the following strderr: `set propagation for /: Permission denied`

This is due to the fact that Containerd on [GKE runs AppArmour](https://cloud.google.com/container-optimized-os/docs/how-to/secure-apparmor)  whichuses the [Docker Default security profile which denies mount inside a pod.](https://github.com/moby/moby/blob/master/profiles/apparmor/template.go#L42)

As a workaround setting the following setting in values.yaml i the Crossplane Helm chart.

```yaml
customAnnotations:
  "container.apparmor.security.beta.kubernetes.io/crossplane-xfn": "unconfined"
```

### How can we reproduce it?

Install XP 1.11.3 with the following Helm values, on GKE 1.24 - 1.27

```yaml
# crossplane helm chart
args:
  - "--debug"
  - "--enable-composition-functions"
  - "--enable-environment-configs"

# compostion-functions alpha feature
xfn:
  enabled: true
  args:
    - "--debug"
```

Run ANY composition function.

### What environment did it happen in?
Crossplane version:  Tested, 1.11.0, 1.11.3 
GKE 1.24 and 1.27
AKS also seems affected.
