### ISSUE TITLE
Unable to see the update of my composition reflected on my claim

### ISSUE THREAD

**Issue by ashishvaishno** [crossplane/crossplane#4229]
Hello All,

background : 
* I have deployed an existing composition to create a  policy(as an example)
* I deployed the claim and everything looked good to me
* Soon i started to realised, that i wanted to make some changes in my compostion
* Since the Composition Update Policy is set to Automatic, I was able to see that my claim now uses the latest version of the composition. 
* But now I do see the changes in my actual claim, not in my aws resource 😕 

Configuration
Composition Version 1 : 
```
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            - fromFieldPath: spec.resourceConfig.serviceName
            strategy: string
            string:
              fmt: "k8s-sa-policy-go-%s-main-%s"
```
Compostion Version 2 : 
```
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            - fromFieldPath: spec.resourceConfig.serviceName
            strategy: string
            string:
              fmt: "k8s-sa-policy-go-main-%s-%s"
```
Policy name created on aws       : k8s-sa-policy-go-**dev-main**-<service_name>
Expected Updated Policy name : k8s-sa-policy-go-**main-dev**-<service_name>

List of available composition revisions : 
```
NAME                                   REVISION   XR-KIND          XR-APIVERSION       AGE
dev.xs3withirsa.test.com-3bc98e5       1          XS3WithIRSA      test.com/v1alpha1   5d13h
dev.xs3withirsa.test.com-55e8258       2          XS3WithIRSA      test.com/v1alpha1   5d12h
dev.xs3withirsa.test.com-adb382b       3          XS3WithIRSA      test.com/v1alpha1   50m
```
Spec of my deployed claim : 
```
  Composition Ref:
    Name:  dev.xs3withirsa.test.com
  Composition Revision Ref:
    Name:  dev.xs3withirsa.test.com-adb382b
  Composition Selector:
    Match Labels:
      Environment:            dev
  Composition Update Policy:  Automatic
```
The upbound iam provider logs says everything is upto date : 
```
2023-06-21T10:10:16Z	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/iam.aws.upbound.io/v1beta1, kind=policy", "request": "/test-dev-5klrw-mmvtz", "uid": "fea5519f-8250-41d9-a514-46106cbb0a2f", "version": "1816580", "external-name": "k8s-sa-policy-go-dev-main-test", "requeue-after": "2023-06-21T10:20:16Z"}
```

I also get the same issue with IAMPolicyAttachment. The rename of role and policy doesnt reflect for IAMPolicyAttachment😕 

Crossplane version : 1.12.2
IAM provider version : xpkg.upbound.io/upbound/provider-aws-iam:v0.36.0
eks k8s version : 1.27

Regards
Ashish
