### ISSUE TITLE
Best way of providing multiple versions of custom resources

### ISSUE THREAD

**Issue by mithie** [crossplane/crossplane#4230]
### What problem are you facing?
This is more like a general question than a real feature request. In our project we will have to provide different versions of some of our XRDs over time. This in general means we would have to write a custom conversion webhook for different versions of our APIs. However, we're wondering if conversion webhooks are always the right way to go. 

We set up a multi-tenant Kubernetes environment for allowing multiple projects in our organization to deploy applications in their own dedicated namespaces. Since we are running on AWS, any kind of native AWS service required by a project will be provided as a custom Crossplane API that connects a tenant namespace on the cluster with the tenant's custom AWS account and allows to provision dedicated AWS resources in that account.

Let's assume now we have the following Tenant base CR modeling a tenant in a multi-tenant Kubernetes environment:

```yaml
apiVersion: my.example.com/v1alpha1
kind: Tenant
metadata:
  name: sample-tenant
spec:
  product: sample-product
  accountId: 111111111111
  namespace: sample_one
```

When applying this resource, then Crossplane will create a cross-account AWS connection between the tenant's AWS account and the AWS account the Kubernetes cluster resides in. Since tenants can have multiple namespaces on the cluster the relationship between an account and namespaces is a `1:n` relationship. In our current design this means that we would have to create a new CR for each new tenant namespace registered on the cluster. 

A simpler approach might be to have a list of accounts/namespaces belonging to a single tenant. This would also drastically reduce the amount of CRs with redundant information we would have to create otherwise.

An example of a new version of the Tenant resource might look like the following:

```yaml
apiVersion: my.example.com/v1beta1
kind: Tenant
metadata:
  name: new-tenant
spec:
  product: new-product
  accountIds:
    - accountId: 222222222222
      namespaces:
        - sample_two
        - sample_three
```

The problem now is that this resource would replace multiple single Tenant CRs which are already in place. Writing a conversion webhook for this special scenario probably wouldn't make too much sense since information would get lost between the conversion from v1beta1 to v1alpha1.

The following solution comes to my mind to solve this:

1. Create a complete new Crossplane Tenant component and name it differently. Both, the old and the new Tenant components could run in parallel.
2. Create a Kubernetes conversion webhook. The problem then would be that I'd have to make a conversion from an array to a single attribute and some information would get lost during conversion.
3. Write a wrapper Crossplane component that allows to create multiple Tenant resources for provided accountIds/namespaces.

### How could Crossplane help solve your problem?
* Provide a suggestion on how to deal with multiple versions of XRDs in the above mentioned scenario and in common
* If we go with the webhook approach would that be a viable solution?
* Could you provide some sort of examples for integrating conversion webhooks in a custom Crossplane component?

**Comment by sttts** [comment]
(2) is not "allowed" in kube. The traditional solution in native Kube resources is to add some way to represent also n account IDs in v1alpha1, around the lines of:

```yaml
apiVersion: my.example.com/v1alpha1
kind: Tenant
metadata:
  name: sample-tenant
spec:
  product: sample-product
  accountId: 111111111111
  namespace: sample_one
  moreNamespaces: []
  moreAccountIds:
    - accountId: 222222222222
      namespaces:
        - sample_two
        - sample_three
```

It makes v1alpha1 a little ugly, but 🤷.

In general, writing a webhook for that is doable, but quite a bit of work, plus operational overhead. The cluster might not start without the webhook or behave strangely.

A pragmatic alternatives is, if you have control over all clients: just add accountIDs as in your v1beta1 example beside the old fields, stop creation of old-style objects via admission, migrate all objects, remove old fields.
