### ISSUE TITLE
Deleting a Provider before its MRs results in stuck MRs

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4251]
### What happened?

While working on https://github.com/crossplane/crossplane/pull/4187 I was reminded that you must ensure all of a provider's MRs are completely deleted before uninstalling the provider. If you don't:

* Any MRs will be left in an orphaned, unreconciled, un-deletable state.
* The orphaned MRs will prevent the CRD that defines them being removed.
* The CRD that defines them will prevent the provider being reinstalled.

I believe this happens because:

* The `Provider.pkg` and its revision are deleted immediately, relying on Kubernetes garbage collection to delete the MR CRDs.
* An MR CRD can't be deleted while an MR (CR) exists. The CRD has `metadata.deletionTimestamp` set, but deletion is blocked by the `customresourcecleanup.apiextensions.k8s.io` finalizer.
* The `Provider.pkg` and its revisions being gone means the provider deployment no longer exists. This means you now can't delete the MR - deletion will be blocked by the `finalizer.managedresource.crossplane.io` finalizer.

I believe if you get into this state your only option is to do finalizer surgery on the MR(s) that are blocking the deletion (and to manually delete any corresponding external resources).

### How can we reproduce it?

1. Create a provider:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.0
  ignoreCrossplaneConstraints: true
```

2. Create an MR:

```yaml
apiVersion: nop.crossplane.io/v1alpha1
kind: NopResource
metadata:
  name: example-resource
spec:
 forProvider:
   conditionAfter:
   - conditionType: Ready
     conditionStatus: "False"
     conditionReason: "Creating"
     time: 0s
   - conditionType: Ready
     conditionStatus: "True"
     conditionReason: "Available"
     time: 10s
```

3. Delete the provider
4. Try to delete the MR

### What environment did it happen in?
Crossplane version: b65fa47e5f270b3054840cce1e0c4fcc9e96b7b7
