### ISSUE TITLE
Unable to patches from a field within the composed resource to a field within the XR 

### ISSUE THREAD

**Issue by ashishvaishno** [crossplane/crossplane#4260]
Hello,

* I have a central crossplane eks cluster where I am creating an IAM user and AccessKey in my destination account
* I want to share the accesskey and secret and create a k8s secret file in my destination k8s cluster so that the developer can access the credentials
* Below are my xrd and composition 
<details>
  <summary>XRD</summary>

  ### XRD
  ```
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiamusers.crossplane.test.com
spec:
  claimNames:
    kind: IAMUser
    plural: iamusers
  group: crossplane.test.com
  names:
    kind: XIAMUser
    plural: xiamusers
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: IAM User test
              properties:
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Orphan
                      type: string
                      default: "Orphan"
                    serviceName:
                      description: Name of the iam user
                      type: string
                    serviceNamespace:
                      description: Namespace
                      type: string
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - serviceName
                  - serviceNamespace
                  type: object
              required:
              - resourceConfig
              type: object
            status:
              description: IAM User test
              properties:
                encryptedSecret:
                  type: string
                createDate:
                  type: string
                encryptedSesSmtpPasswordV4:
                  type: string
                id:
                  type: string
                keyFingerprint:
                  type: string
                pgpKey:
                  type: string
                status:
                  type: string
                user:
                  type: string
              type: object
          type: object
  ```
</details>

<details>
  <summary>Composition</summary>

  ### Part of my composition
```
    - name: iam-user
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: User
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.serviceName
          toFieldPath: metadata.annotations[crossplane.io/external-name]
    - name: iam-user-accesskey
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: AccessKey
        spec:
          forProvider:
            userSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.serviceName
          toFieldPath: spec.writeConnectionSecretToRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.id
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.encryptedSecret
          toFieldPath: status.encryptedSecret
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.createDate
          toFieldPath: status.createDate
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.encryptedSesSmtpPasswordV4
          toFieldPath: status.encryptedSesSmtpPasswordV4
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.status
          toFieldPath: status.status
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.user
          toFieldPath: status.user
    - name: remote-secret
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          deletionPolicy: "Orphan"
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: ""
                namespace: ""
              data:
                access_key: ""
                access_key_secret: ""
      patches:
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            strategy: string
            string:
              fmt: "kubernetes-provider-config-%s"
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.serviceNamespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.serviceName
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: status.id
          toFieldPath: spec.forProvider.manifest.data.access_key
        - type: FromCompositeFieldPath
          fromFieldPath: status.encryptedSecret
          toFieldPath: spec.forProvider.manifest.data.access_key_secret
  ```
</details>

* I can only see [4 of the mentioned 6 status.atProvider](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/v0.36.0/resources/iam.aws.upbound.io/AccessKey/v1beta1#doc:status-atProvider)  (not counting the pgp ones 😉 )
```
Status:
  Conditions:
    Last Transition Time:  2023-06-23T07:51:53Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-06-23T07:52:22Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Create Date:             2023-06-23T07:52:01Z
  Id:                      XXXXXXXXX
  Status:                  Active
  User:                    xxxxxxxxxxx
```
* Locally the secret created has the Access key secret (using writeConnectionSecretToRef), but my remote k8s secret is empty. 
* May be I am missing some configuration 🤷‍♂️ 
* Please feel free to move this into a discussion(if this is not a bug 😄 )

Regards
Ashish
