### ISSUE TITLE
XRDs expect but don't enforce an OAPI spec field

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane#4268]
### What happened?
According to the Open API v3 spec, the child of `openAPIV3Schema.properties` can be any field, however Crossplane expects it to be `spec`[[ref](https://github.com/crossplane/crossplane/blob/104ea2d8566558a2c8baad5923eee446abb8625b/internal/xcrd/crd.go#L93C3-L93C12)].

Although `spec` is expected, there is no check or enforcement. As a result you can create an XRD with any value and the schema is just ignored in the resulting CRD.

Crossplane should reject an XRD without the expected `openAPIV3Schema.properties.spec` field.

### How can we reproduce it?
Create an XRD with any field inside `openAPIV3Schema.properties`.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtests.custom-api.example.org
spec:
  group: custom-api.example.org
  names:
    kind: xtest
    plural: xtests
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          banana:
            type: object
            properties:
              region:
                type: string
```

The XRD is created without any errors

```yaml
kubectl describe xrd xtests.custom-api.example.org                                                                                                                                                             
Name:         xtests.custom-api.example.org
# ---snip---
Spec:
  Default Composite Delete Policy:    Background
  Default Composition Update Policy:  Automatic
  Group:                              custom-api.example.org
  Names:
    Kind:    xtest
    Plural:  xtests
  Versions:
    Name:           v1alpha1
    Referenceable:  true
    Schema:
      openAPIV3Schema:
        Properties:
          Banana:
            Properties:
              Region:
                Type:  string
            Type:      object
        Type:          object
    Served:            true
Status:
  Conditions:
    Last Transition Time:  2023-06-26T19:42:07Z
    Reason:                WatchingCompositeResource
    Status:                True
    Type:                  Established
  Controllers:
    Composite Resource Claim Type:
      API Version:
      Kind:
    Composite Resource Type:
      API Version:  custom-api.example.org/v1alpha1
      Kind:         xtest
Events:
  Type     Reason              Age                From                                                             Message
  ----     ------              ----               ----                                                             -------
  Normal   EstablishComposite  75s                defined/compositeresourcedefinition.apiextensions.crossplane.io  waiting for composite resource CustomResourceDefinition to be established
  Warning  EstablishComposite  75s                defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot apply rendered composite resource CustomResourceDefinition: cannot update object: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "xtests.custom-api.example.org": the object has been modified; please apply your changes to the latest version and try again
  Warning  ApplyClusterRoles   75s                rbac/compositeresourcedefinition.apiextensions.crossplane.io     cannot apply ClusterRoles: cannot create object: clusterroles.rbac.authorization.k8s.io "crossplane:composite:xtests.custom-api.example.org:aggregate-to-browse" already exists
  Normal   RenderCRD           74s (x6 over 75s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Rendered composite resource CustomResourceDefinition
  Normal   EstablishComposite  74s (x5 over 75s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Applied composite resource CustomResourceDefinition
  Normal   EstablishComposite  74s (x4 over 75s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  (Re)started composite resource controller
  Normal   ApplyClusterRoles   74s (x3 over 75s)  rbac/compositeresourcedefinition.apiextensions.crossplane.io     Applied RBAC ClusterRoles
```

But the CRD doesn't contain the defined schema.

```yaml
$ kubectl describe customresourcedefinition xtests.custom-api.example.org                                                                                                                                        
Name:         xtests.custom-api.example.org
Spec:
  Conversion:
    Strategy:  None
  Group:       custom-api.example.org
  Names:
    Categories:
      composite
    Kind:       xtest
    List Kind:  xtestList
    Plural:     xtests
    Singular:   xtest
  Scope:        Cluster
  Versions:
    Name:         v1alpha1
    Schema:
      openAPIV3Schema:
        Properties:
          API Version:
            Type:  string
          Kind:
            Type:  string
          Metadata:
            Type:  object
          Spec:
            Properties:
              Claim Ref:
                Properties:
                  API Version:
                    Type:  string
                  Kind:
                    Type:  string
                  Name:
                    Type:  string
                  Namespace:
                    Type:  string
                Required:
                  apiVersion
                  kind
                  namespace
                  name
                Type:  object
              Composition Ref:
                Properties:
                  Name:
                    Type:  string
                Required:
                  name
                Type:  object
              Composition Revision Ref:
                Properties:
                  Name:
                    Type:  string
                Required:
                  name
                Type:  object
              Composition Revision Selector:
                Properties:
                  Match Labels:
                    Additional Properties:
                      Type:  string
                    Type:    object
                Required:
                  matchLabels
                Type:  object
              Composition Selector:
                Properties:
                  Match Labels:
                    Additional Properties:
                      Type:  string
                    Type:    object
                Required:
                  matchLabels
                Type:  object
              Composition Update Policy:
                Enum:
                  Automatic
                  Manual
                Type:  string
              Environment Config Refs:
                Items:
                  Properties:
                    API Version:
                      Type:  string
                    Kind:
                      Type:  string
                    Name:
                      Type:  string
                  Required:
                    apiVersion
                    kind
                  Type:  object
                Type:    array
              Publish Connection Details To:
                Properties:
                  Config Ref:
                    Default:
                      Name:  default
                    Properties:
                      Name:
                        Type:  string
                    Type:      object
                  Metadata:
                    Properties:
                      Annotations:
                        Additional Properties:
                          Type:  string
                        Type:    object
                      Labels:
                        Additional Properties:
                          Type:  string
                        Type:    object
                      Type:
                        Type:  string
                    Type:      object
                  Name:
                    Type:  string
                Required:
                  name
                Type:  object
              Resource Refs:
                Items:
                  Properties:
                    API Version:
                      Type:  string
                    Kind:
                      Type:  string
                    Name:
                      Type:  string
                  Required:
                    apiVersion
                    kind
                  Type:  object
                Type:    array
              Write Connection Secret To Ref:
                Properties:
                  Name:
                    Type:  string
                  Namespace:
                    Type:  string
                Required:
                  name
                  namespace
                Type:  object
            Type:      object
          Status:
            Properties:
              Conditions:
                Description:  Conditions of the resource.
                Items:
                  Properties:
                    Last Transition Time:
                      Format:  date-time
                      Type:    string
                    Message:
                      Type:  string
                    Reason:
                      Type:  string
                    Status:
                      Type:  string
                    Type:
                      Type:  string
                  Required:
                    lastTransitionTime
                    reason
                    status
                    type
                  Type:  object
                Type:    array
              Connection Details:
                Properties:
                  Last Published Time:
                    Format:  date-time
                    Type:    string
                Type:        object
            Type:            object
        Required:
          spec
        Type:  object
    Served:    true
    Storage:   true
    Subresources:
      Status:
# Snip
```

### What environment did it happen in?
Crossplane version: v1.12.2
