### ISSUE TITLE
Add support for Composition environment schema definition/validation

### ISSUE THREAD

**Issue by bobh66** [crossplane/crossplane#4275]
### What problem are you facing?
The Composition environment has no defined schema and can be used as a generic object/scratchpad.  While this flexibility is extremely useful it does have drawbacks:
- it is difficult to find typographical errors when referencing environment variables
- it is difficult to understand the environment structure of the composition without reading the entire composition

### How could Crossplane help solve your problem?
Allow users to define an environment schema within the Composition.  This would be useful for:
- documenting the expected environment structure
- validating that the generated environment is "correct" as defined by the schema
- validating environment patches are referencing correct attributes
- providing default values to the environment

**Comment by haarchri** [comment]
removed the comment and add a other issue https://github.com/crossplane/crossplane/issues/4344

**Comment by MisterMX** [comment]
I would propose to add an OpenAPI schema field `spec.environment.schema` to the composition that is parsed and validated against the merged environment configs at runtime:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  environment:
    schema:
      openAPIV3Schema:
        type: object
        properties:
          accountId:
            type: string
          region:
            type: string
        required:
          - accountId
          - region
```

Since Crossplane's `go.mod` already includes `k8s.io/kube-openapi` this could possible be implemented easily without any extra dependencies.

Having a simple parse & validate mechanic would would solve the issue of ensuring the structure of the environment *before* the first rendering. However, it would not handle the validation of patches from and to the environment. Still, it would be a good start.
