### ISSUE TITLE
Custom Composition Selectors

### ISSUE THREAD

**Issue by MisterMX** [crossplane/crossplane#4281]
### What problem are you facing?

Currently, Crossplane supports the user to choose a composition through a `spec.compositionSelector` in the XRC. This works fine as long as you know exactly which labels you need to specify which requires you to have deep platform insights to know what compositions exist and which one to choose.

However, in our scenario users don't have access to compositions or other kind of cluster-scoped resource. Naturally they don't know which composition to choose from. This requires the platform engineers to write a distinct section in the documentation to explain which labels to specify.

Since `spec.compositionSelector.matchLabels` is a schemaless `map[string]string` it allows users to enter any kind of value possibly bearing the risk of typos due to the lack of input validation (say, `stgae` instead of `stage`).

### How could Crossplane help solve your problem?

Crossplane should provide a way to make composition selection transparent to the user by letting the platform engineers choose the labels based on the claim.

XRDs could be extended with a `spec.customCompositionSelector` that accepts a set of field paths from which the label values are extracted:

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: tests.example.com
spec:
  # Overwrites `spec.compositionSelector` in the claim
  customCompositionSelector:
    matchLabels:
      - key: stage
        value:
          fromFieldPath: spec.stage
          policy:
            resolution: Optional
  versions:
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              stage:
                description: The environment in which the resource should be deployed.
                type: string
                enum:
                  - production
                  - testing
```
