### ISSUE TITLE
Improve out-of-the-box experience for openshift clusters

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/crossplane#4289]
### What problem are you facing?

As requested by @jeanduplessis-alt into https://crossplane.slack.com/archives/C01TRKD4623/p1688146928534739?thread_ts=1688139573.796699&cid=C01TRKD4623, here is a reminder to consider how to improve the out-of-the-box experience for users running on OpenShift

Openshift users have to cope with [SSC constraints on workloads deployed within openshift](https://docs.openshift.com/container-platform/4.5/authentication/managing-security-context-constraints.html), and their workload need to specify the following clauses in their spec

```
  securityContext: {}
  podSecurityContext: {}
```

This requires explicit configuration for standalone provider installation, as shared into https://github.com/crossplane/crossplane/issues/2080#issuecomment-762366239

However, the installation of upjet-based smaller providers requires an additional workaround to enable the familly provider package (which gets installed automatically by the package manager as a result of the smaller package expressing a dependency to the provider family) to get the controller config injected: 

<details>

 ```yaml
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  annotations:
    auth.upbound.io/group: gcp.upbound.io
    friendly-name.meta.crossplane.io: Provider GCP (sql)
    meta.crossplane.io/description: |
      Upbound's official Crossplane provider to manage Google Cloud Platform (GCP)
      sql services in Kubernetes.
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/readme: |
      Provider GCP is a Crossplane provider for [Google Cloud Platform](https://cloud.google.com/) developed and supported by Upbound.
      Available resources and their fields can be found in the [Upbound
      Marketplace](https://marketplace.upbound.io/providers/upbound/provider-gcp).
      If you encounter an issue please reach out on support@upbound.io email
      address. This is a subpackage for the sql API group.
    meta.crossplane.io/source: github.com/upbound/provider-gcp
  creationTimestamp: null
  labels:
    pkg.crossplane.io/provider-family: provider-family-gcp
  name: provider-gcp-sql
spec:
  controller: {}
  crossplane:
    version: '>=v1.12.1-0'
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-family-gcp
    version: '>= 0.0.0'
``` 

</details>

* explictly define a provider for [provider-family-gcp](http://xpkg.upbound.io/upbound/provider-family-gcp) with the controllerConfigRef (specifying ssc constraints)
* set skipDependencyResolution=true in the provider-gcp-sql to prevent package manager from creating the provider-family-gcp package without a controllerConfigRef

### How could Crossplane help solve your problem?

* Introduce additive controllerConfigs which gets merged (e.g. according to a priority field in their spec)
* Introduce a default controllerConfig. 
* Document to openshift users to declare a default controllerConfig 

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: openshift-ssc-controller-config
spec:
  args:
    - --debug
  podSecurityContext: {}
  securityContext: {}
```
* Document hint to flux users in openshift the workaround for empty helm value shared into https://github.com/fluxcd/flux2/issues/2435#issuecomment-1173746914
