### ISSUE TITLE
Proposal: Use `ImageConfig` to rewrite package OCI references

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane#4299]
Edit from @negz: see proposal at https://github.com/crossplane/crossplane/issues/4299#issuecomment-2719867673.

Original issue follows.

---

### What problem are you facing?

When we use a custom registry, the dependency resolution does not work since the full image URLs are hard-coded in the package metadata.

### How could Crossplane help solve your problem?

By providing a way to substitute the registry.

> [!NOTE]  
> Workaround available as described in https://github.com/crossplane/crossplane/issues/4299#issuecomment-1691379712

**Comment by jbw976** [comment]
Does the following described in #4116 help out here @muvaf?

> The crossplane container accepts a -r registry command line option to allow for a default registry to pull packages from. It defaults to index.docker.io but can be overridden to pull from a specific registry by default. That allows Provider and Configuration packages to specify only the repository and tag information for an image, and they are registry-independent.

**Comment by ron-st-g** [comment]
We started running into this problem when testing the installation of the AWS family providers.  Our company mandates that we only pull images and packages from our internal registry backed by Artifactory.  We added xpkg.upbound.io/upbound/ as a local cache and have been able to successfully pull the images.  The image path now looks like contain-image.mycompany.com/upbound/upbound/provider-family-aws:0.37.0.

What we notice is that the provider revisions for the smaller scoped providers never get to a healthy state because they are failing the dependency validation.  They are looking to see if "xpkg.upbound.io/upbound/provider-family-aws" is installed, and not detecting the provider-family-aws running off the image pulled from our cache.  

We can set 'skipDependencyResolution' to true on the smaller providers, which does allow them to flip to healthy.  However, it would be nice if we could set the repository path for the validation instead of just skipping it.

**Comment by negz** [comment]
> Does the following described in https://github.com/crossplane/crossplane/issues/4116 help out here @muvaf?

@jbw976 My guess is it doesn't - at least in and of itself. That would help if a package depended on `upbound/provider-family-aws:0.37.0`. However our packages depend on a "fully qualified" package, including the registry - e.g. `xpkg.upbound.io/upbound/provider-family-aws:0.37.0`.

Perhaps the solution is that our packages should instead depend on an unqualified package. Would it make sense to depend on `upbound/provider-family-aws:0.37.0`? Presumably then the `-r` flag would correctly fill in the registry to be whatever you needed?

**Comment by bobh66** [comment]
> Perhaps the solution is that our packages should instead depend on an unqualified package.

Would that also mean changing the default registry from `index.docker.io` to `xpkg.upbound.io`?

**Comment by negz** [comment]
@bobh66 Yeah, we'd probably have to. I think `xpkg.upbound.io` makes sense as a default. On the other hand that feels like a breaking change.

Slightly related: https://github.com/crossplane/crossplane/issues/3560

**Comment by muvaf** [comment]
Yes, the feature I'm asking for is overriding the registry. Though I don't have a great solution for it. Maybe separate the host into its own field, like `registry` & `path` so that we can configure an override for all `registry` fields? Not sure if it's worth it though.

Leaving it to the package authors to provide unqualified URLs and then letting folks override the default registry seems like the better option as it doesn't impact the folks who don't need to override it, which I believe the majority of our users. @negz I agree that it's a breaking change and I think it'd be surprising if an unqualified image path resolves to something other than DockerHub at this point. An option could be to have additional configuration parameter to replace the host part of all image URLs in `Provider` and `Configuration` packages that our package manager creates but that sounds a bit surprising.

**Comment by pedjak** [comment]
Perhaps we can implement support for [/etc/containers/registries.conf](https://www.mankier.com/5/containers-registries.conf) file, similar to podman/cri-o?

It would be actually nice that Crossplane uses k8s to pull images, so that users can apply the same registry mirroring/proxy configs.

**Comment by eperdeme** [comment]
> /etc/containers/registries.conf

Don't do this if using it to redirect to a different mirror.
It's confusing operationally if you do this as when you do describes/etc it shows the public/original container registry and teams then get confused. Also it breaks security tools as they then don't know the "real" internal source of the container.

**Comment by tkaesserfm** [comment]
For everyone looking for a workaround regarding the usage of private registries. What worked for us was:
- set `skipDependencyResolution` to `true` for the small providers (e.g provider-aws-upbound-s3)
- install `upbound-provider-family-aws` manually (best to have same versions)

and most importantly: 
you will need a subpath in your image-path to function as an "org" which is needed for the rbac-manager to properly create clusterroles. A path of the form: `${registry_fqdn}/upbound/${provider}` (999999999999.dkr.ecr.eu-west-1.amazonaws.com/upbound/provider-family-aws:v0.39.0) worked for us.

Thanks @haarchri for suggesting solution, code for reference: https://github.com/crossplane/crossplane/pull/4032/files#diff-c719fd6df8af496dfcd82b8b46322435db030498d7d192616a06be47091bf88eR273

**Comment by phisco** [comment]
what about adding a field to the `PackageSpec` and `PackageRevisionSpec`, something like:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-ref-aws
spec:
  package: xpkg.upbound.io/upbound/platform-ref-aws:v0.6.0
  dependencies:
    rewrite:
    - prefix: "xpkg.upbound.io"
       newPrefix: "my-awesom-registry.com"
```
where `xpkg.upbound.io` is a prefix we'll replace when going through the dependencies declared by the package.

Another option would be to go with a plain map, but we'd still have to go through all entries and check a dependency starts with the key, so no real added value using a map.

**Comment by pedjak** [comment]
> what about adding a field to the PackageSpec and PackageRevisionSpec, something like:

Does this mean that we would not be able to consume marketplace configurations/provider if our cluster is not able pull them from internet, and to solve this, we would need to provide our own configurations?

To me, packaging is orthogonal to image pulling (through original source or a mirror) and should be configured on either k8s level, or crossplane instance (as we already do that with `--registry` flag). If needed, it could be expanded to support more sophisticated resolving strategies, for example [containers-registries.conf](https://www.mankier.com/5/containers-registries.conf). In that way, user can put all relevant packages in a mirror accessible behind a firewall and still happily consume them in disconnected clusters.

**Comment by tkaesserfm** [comment]
@phisco the approach has a major weakness that if the dependency changes it's prefix it will break in a not so transparent way. For me personally it feels pretty natural to resolve dependencies manually (because you anyway need to know exactly what you're running) on a more secure system. 
@pedjak to solve this you can follow my advice from previous message. 
The only weakness i currently see with the approach of manually installing dependencies is that i think there is a lack of documentation that the registry requires at least some subpath in the registry-path because it uses it internally as a security mechanism.

**Comment by nashant** [comment]
Why not allow overriding the `dependencies.package` in the `provider`? Something like
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: private.registry/subpath/upbound/provider-aws-s3:v0.38.0
  dependencies:
  - name: xpkg.upbound.io/upbound/provider-family-aws
    package: private.registry/subpath/upbound/provider-family-aws:v0.38.0
```

**Comment by tkaesserfm** [comment]
What would be the advantage over current approach @nashant ? :thinking:

**Comment by phisco** [comment]
@pedjak, a package (Provider/Configuration/Functions) usually points to an image which we look into to get the meta information about the package itself, which can then potentially point to a separate image to actually run, e.g. a provider/function. Here we need to allow users working in constrained environments to read from different private registries (or paths or tags), instead of the hardcoded ones, potentially at any level in the dependency tree.

Configuring the hosts to map to a different registry would work for the images Crossplane actually runs, but unfortunately that wouldn't influence how Crossplane is accessing the image to read the metadata in the first place. So we still need a way to configure Crossplane to pull dependencies from a different source than the one hardcoded in the package provided.

The `--registry` flag currently allows changing the default registry when not specified, but only for images not specifying one, e.g. `ubuntu` or `crossplane/crossplane` should come from `my-awesome-registry.com` instead of the default `docker.io`. So, in order to do this you'd still need to configure a mapping between old and new images, either at Crossplane level or at each package level, [containers-registries.conf](https://www.mankier.com/5/containers-registries.conf) is definitely a possible format at both levels, however I never used that. Looking around it doesn't look as a widespread standard, it feels like it's mostly used by RedHat projects, am I correct @pedjak?

@tkaesserfm, I see your point, but skipping dependency  resolution is a workaround, it would be nice to provide an official solution. Would regexes and/or a more precise description of the old and new images help with updated dependencies?

@nashant this would suffer the same issue described by @tkaesserfm, as it would not take into account updated dependencies in the upstream package. Moreover you can already do something similar by just building your own package using the upstream image, defining just the dependencies you care about. Obviously you'd have to do the same for the dependencies of any nested package referenced.

**Comment by nashant** [comment]
@tkaesserfm thinking about it, probably none. If you've got a number of child providers then it's fewer lines to just manually add the family provider. I suppose it's just a matter of documentation then really

**Comment by negz** [comment]
I keep coming back to what I proposed earlier in the thread. Perhaps the solution is that our packages should be able depend on an "unqualified" package. For example take a dependency on `upbound/provider-family-aws:0.37.0` instead of `xpkg.upbound.io/provider-family-aws:0.37.0`?

Under this approach:
* We'd update providers that were part of families to use unqualified dependencies.
* Unqualified dependencies would be pulled from the same registry as the dependent.
* It would still be possible to depend on a "fully qualified" package. In this case the behaviour would be unchanged from today.

**Comment by pedjak** [comment]
> Configuring the hosts to map to a different registry would work for the images Crossplane actually runs, but unfortunately that wouldn't influence how Crossplane is accessing the image to read the metadata in the first place. So we still need a way to configure Crossplane to pull dependencies from a different source than the one hardcoded in the package provided.

Fully agree, but that kind of mapping/mirroring logic should be added to crossplane itself. If we implement support for [containers-registries.conf](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md), then our users could use the very same configuration from host (k8s node based on cri-o for example) so that both crossplane and the cluster use the very same resolving mechanism.

cri-o is using it and some of RedHat container related CLIs like podman/buildnah. We could chose something else as well, but I would avoid inventing our own format for that purpose, if possible.

**Comment by muvaf** [comment]
> Unqualified dependencies would be pulled from the same registry as the dependent.

@negz I think if we create `Provider` resource with fully qualified path, this seems like the best approach. My main concern with your proposal was to have an unqualified image path on a resource that somehow resolves to non-DockerHub registry, which would be surprising. But if the initial `Provider` has the registry and the dependent `Provider`s created by package manager has the `spec.package` containing fully qualified path with registry derived from that user-created root `Provider`, then I believe this is likely the best approach.

**Comment by negz** [comment]
We explored my partially qualified dependencies idea in https://github.com/crossplane/crossplane/pull/6014. Unfortunately we found that it'd be practically hard to implement. We'd need to:

* Update how Crossplane handles a partially qualified dependency (to inherit the omitted segments from its dependent)
* Update all affected packages to use partially qualified dependencies
* Update all affected packages to require at least the updated version of Crossplane

If we updated providers to use partially qualified dependencies without also updating them to require the updated version of Crossplane, older versions of Crossplane would treat the partially qualified dependencies as if they should be installed from the default registry. This would probably break people . A dependency that was previously `xpkg.upbound.io/foo/provider-bar` might now resolve to `mirror.example.org/foo/provider-bar`, which might not exist, in old versions of Crossplane.

We can't really require everyone to choose between updating to the latest version of Crossplane, or staying on older versions of providers. So I think the partially qualified idea is off the table.

**Comment by negz** [comment]
After chatting with @turkenh and @haarchri today, I'm leaning toward using ImageConfigs to rewrite packages.

https://docs.crossplane.io/v1.19/concepts/image-configs/

Given this Provider:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
```

This ImageConfig would cause the package manager to actually install `mirror.internal.example.com/upbound/provider-aws-ec2` instead of `xpkg.upbound.io/upbound/provider-aws-ec2`. This would be true whether the Provider was installed explicitly, or as a dependency of another package.

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: ImageConfig
metadata:
  name: mirror-provider-aws
spec:
  matchImages:
  - type: Prefix
    prefix: xpkg.crossplane.io/crossplane-contrib/provider-aws-
  rewritePrefix: mirror.internal.example.com/crossplane-contrib/provider-aws-
```

The full matched prefix (only) would be rewritten. So this ImageConfig would have the same result as the one above:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: ImageConfig
metadata:
  name: mirror-packages
spec:
  matchImages:
  - type: Prefix
    prefix: xpkg.crossplane.io
  - type: Prefix
    prefix: xpkg.upound.io
  rewritePrefix: mirror.internal.example.com
```

Given an unqualified package like this:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane-contrib/provider-aws-ec2
```

The package manager would first resolve the package to the default registry (e.g. `xpkg.crossplane.io`), then rewrite the package per any matching ImageConfigs.

Other ImageConfigs would match the rewritten package. So to configure registry authentication or cosign verification, you'd create a different ImageConfig with a `matchImages` entry matching `mirror.internal.example.com`.

In the past I've worried that an approach like this would be too "magic". It'd certainly be surprising to ask for `package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2` and actually get `package: mirror.internal.example.com/crossplane-contrib/provider-aws-ec2`.

I think we can do a few things to alleviate this concern:

* Record the actual package in a status field
* Record an event indicating an ImageConfig has rewritten the package
* Always use the actual package in package revisions

For example normally a package would look like this:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
status:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
```

However the above ImageConfig rewrites the package, it'd look like this:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
status:
  package: mirror.internal.example.com/crossplane-contrib/provider-aws-ec2
```

`kubectl describe provider.pkg provider-aws` would also show an event like:

```
Events:
  Type     Reason                Age      From                                    Message
  ----     ------                ----     ----                                    -------
  Normal   ImageConfigSelection  45s      packages/provider.pkg.crossplane.io     Rewrote package "xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2" to "mirror.internal.example.com/crossplane-contrib/provider-aws-ec2" per ImageConfig "mirror-provider-aws"
```

Only Crossplane creates package revisions, so their `spec.package` would always reflect the actual package (i.e. the OCI reference from the package's `status.package`.

**Comment by negz** [comment]
@turkenh would it make sense for packages to record all the ImageConfigs that apply to them in their status? Something like:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
status:
  package: mirror.internal.example.com/crossplane-contrib/provider-aws-ec2
  imageConfigs:
  - mirror-provider-aws
  - internal-mirror-credentials
```

I think this'd be nice to supplement events, given that they can expire after a while and only show up under `kubectl describe`, not e.g. `kubectl get -o yaml`.

**Comment by adamwg** [comment]
How will packages installed as dependencies by the package manager be named when their locations are rewritten by an `ImageConfig`?

If my configuration depends on `xpkg.crossplane.io/crossplane-contrib/function-auto-ready`, my compositions will reference it as `crossplane-contrib-function-auto-ready`, relying on the package manager's function naming logic. If I rewrite it to `mirror.internal.example.com/crossplane-images/crossplane-contrib/function-auto-ready` and the function ends up named `crossplane-images-crossplane-contrib-function-auto-ready` my compositions will be broken.

**Comment by haarchri** [comment]
I would expect we calculate the names from the original package

```
metadata:
  name: crossplane-contrib-provider-aws-ec2
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
status:
  package: mirror.internal.example.com/crossplane-contrib/provider-aws-ec2
```

and the status shows the "real" package source from which we installed

**Comment by negz** [comment]
@adamwg @haarchri This reminds me of https://github.com/crossplane/crossplane/issues/6018.

As a best practice I'd strongly suggest that if folks mirror a package, they mirror it to the same org and repo name. If they do that there won't be an issue.

That said, I think @haarchri is right that it should be okay if we use the original org/repo name rather than the actual one when we create packages for dependencies.

**Comment by turkenh** [comment]
> @turkenh would it make sense for packages to record all the ImageConfigs that apply to them in their status?

I think it makes sense, but a little incomplete, as it would be missing how each image config was used. May be we can extend it further a bit:

```yaml
  appliedImageConfigRefs:
  - name: mirror-provider-aws
    for: RewriteImage
  - name: internal-mirror-credentials
    for: PullSecretReference
  - name: verify-packages
    for: ImageVerification  
```

One image config could be used for multiple reasons so, below would also be a possibility

```yaml
  appliedImageConfigRefs:
  - name: upbound-official-images
    for: PullSecretReference
  - name: upbound-official-images
    for: ImageVerification 
```

`reason` could be another alternative to `for` if it looks a little odd:

```yaml
  appliedImageConfigRefs:
  - name: mirror-provider-aws
    reason: RewriteImage
```
