### ISSUE TITLE
provider unable to fetch package descriptor

### ISSUE THREAD

**Issue by dvgitit** [crossplane/crossplane#4329]
### What happened?

After installing trying to install the kubernetes or ansible provider. Both yield this error message:

```
kubectl get events
LAST SEEN   TYPE      REASON          OBJECT                                        MESSAGE
2m12s       Warning   UnpackPackage   provider/crossplanecontrib-provider-ansible   cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request failure: Get "https://index.docker.io/v2/": proxyconnect tcp: dial tcp: lookup myproxy.mydomain.org on x.x.x.x:53: server misbehaving: Get "https://index.docker.io/v2/": proxyconnect tcp: dial tcp: lookup mybproxy.mydomain.org on x.x.x.x:53: server misbehaving
```

It works at killercoda on in any environent with access to the public internet. But within the company network with a company proxy, the error above ocurrs. Unfortunately registry mirrors in place to not seem to be referenced by crossplane.

### How can we reproduce it?

controllerconfig.yaml:

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: my-proxies
spec:
  env:
    - name: NO_PROXY
      value: "..."
    - name: HTTP_PROXY
      value: "http://myproxy.mydomain.org:1234"
    - name: HTTPS_PROXY
      value: "http://myproxy.mydomain.org:1234"
```

```
kubectl apply -f controllerconfig.yaml
```

crossplane-values.yaml:

```
extraEnvVarsCrossplane:
  HTTP_PROXY: 'myproxy.mydomain.org:1234
  HTTPS_PROXY: 'http://myproxy.mydomain.org:1234'
  NO_PROXY: '...'
```

ansible-provider.yaml:

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplanecontrib-provider-ansible
spec:
  package: crossplanecontrib/provider-ansible:v0.5.0
  controllerConfigRef:
    name: my.proxies
```

```
helm install crossplane \
--namespace crossplane-system \
--create-namespace \
crossplane-stable/crossplane \
-f crossplane-values.yaml

kubectl apply -f controllerconfig.yaml

kubectl apply -f ansible-provider.yaml

kubectl crossplane install provider crossplanecontrib/provider-ansible:v0.5.0
```

### What environment did it happen in?
Crossplane version: `v0.5.0`

* Cloud provider or hardware configuration: VM on-premise
* Kubernetes version (use `kubectl version`)

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4+k3s1", GitCommit:"8d0255af07e95b841952563253d27b0d10bd72f0", GitTreeState:"clean", BuildDate:"2023-04-20T00:33:18Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.26) exceeds the supported minor version skew of +/-1
```

* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): `k3d, but problem occurs also with k3s and rke2`
* OS (e.g. from /etc/os-release): `Ubuntu 20,04`
* Kernel (e.g. `uname -a`)
 `Linux nexus-test-0 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Addendum k3d environment

```
docker run -itd --restart=unless-stopped --net=host -v /var/run/docker.sock:/var/run/docker.sock \
        -v $(pwd)/registries.yaml:/etc/registries.yaml cnrancher/autok3s:v0.8.0
id=$(docker ps --filter ancestor=cnrancher/autok3s:v0.8.0 --format '{{.ID}}')
docker exec $id autok3s create --provider k3d --name gitops --master 1 --worker 1 --registry /etc/registries.yaml --envs "HTTPS_PROXY=$HTTP_PROXY@agent:0" --envs "HTTP_PROXY=$HTTPS_PROXY@agent:0" --envs "NO_PROXY=$NO_PROXY@agent:0"
```
