### ISSUE TITLE
Extend regexp transform with replacement support

### ISSUE THREAD

**Issue by erikgb** [crossplane/crossplane#4341]
### What problem are you facing?

We want to use Crossplane to provision Kafka topics. Our current topic naming standard does not allow `-` as a separation character and specifies that `_` should be used instead. As Kubernetes does not allow the `_` character, we need to use the `crossplane.io/external-name` annotation, and that's fine. But we would prefer to include the topic name (transformed) in the topic managed resource name. Currently, this does not seem possible without entering composite function area - which we would prefer to avoid for a simple transform as this. Example: I would like a transform that allows me to transform `foo_bar_baz` to `foo-bar-baz`.

### How could Crossplane help solve your problem?

What I would like to see is an extension of the `Regexp` transform introduced in #3164. This feature currently only supports extraction using regexp, but I don't see why it cannot be extended to support replacement too.

By adding a new optional field to the `Regexp` transform, my use case could be solved as simple as:
````yaml
- type: string
  string:
     type: Regexp
     regexp:
      match: '_'
      replacement: '-'  # Optional replacement for matching regexp.
````

Since it does not makes sense to specify both the `group ` (existing) and `replacement` (new) fields, I suggest adding a simple [CEL validation](https://kubernetes.io/docs/reference/using-api/cel/) to the `regexp` transform element. This CEL validation could be as simple as `!has(self.group) || !has(self.replacement)`.

Related PRs/issues: #4051 #3759 #3026

**Comment by phisco** [comment]
Just adding a breadcrumb to https://github.com/crossplane/crossplane/issues/4084 about the CEL validation. Other than that, I agree it could be a useful addition, thanks @erikgb 🙏

**Comment by fhopfensperger** [comment]
/fresh Is there any possibility to replace special chars?
For example to get rid of the `&` 
```
metadata:
  name: some-object
  annotations:
    my-annotation: "with&special&char"
```
