### ISSUE TITLE
enhance schema-aware composition validation to handling a scheme-less resource

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#4344]
### What happened?
during enhancement of upbound/platform-ref-aws we found the following issue: https://github.com/upbound/platform-ref-aws/pull/110#discussion_r1265931165 when crossplane is started with the following arg `--enable-composition-webhook-schema-validation`

```
compositeresourcedefinition.apiextensions.crossplane.io/xeks.aws.platformref.upbound.io unchanged
The Composition "xeks.aws.platformref.upbound.io" is invalid:
* spec.resources[13].patches[1].toFieldPath: Invalid value: "data.oidcHost": field path "data.oidcHost" has an unsupported type ""
* spec.resources[13].patches[2].toFieldPath: Invalid value: "data.accountId": field path "data.accountId" has an unsupported type ""
* spec.resources[13].patches[3].toFieldPath: Invalid value: "data.oidcArn": field path "data.oidcArn" has an unsupported type ""
```

### How can we reproduce it?

use a composition to create a environmentConfig for example:

```
    - base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: EnvironmentConfig
      name: irsa-environmentconfig
      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.labels[clusterRef]
      - fromFieldPath: status.eks.oidcUri
        toFieldPath: data.oidcHost
      - fromFieldPath: status.eks.accountId
        toFieldPath: data.accountId
      - type: CombineFromComposite
        toFieldPath: data.oidcArn
       policy:
          fromFieldPath: Required
        combine:
          variables:
            - fromFieldPath: status.eks.accountId
            - fromFieldPath: status.eks.oidcUri
          strategy: string
          string:
            fmt: 'arn:aws:iam::%s:oidc-provider/%s'
      readinessChecks:
        - type: None
```

### What environment did it happen in?
Crossplane version: v1.12.2
