### ISSUE TITLE
Support using jq for highly-expressive composition transformations

### ISSUE THREAD

**Issue by jutley** [crossplane/crossplane#4351]
### What problem are you facing?

I frequently find that the transformations offered by Crossplane are too crude for use cases that seem rather simple. The example I am running into now is that I would like to pass labels with a specific prefix onto the AWS resources created by a transformation. Using the prefix `example.com`, we may want to turn the following Kubernetes resource labels into the following AWS tags:

```yaml
# Kubernetes labels
example.com/foo: foo
example.com/bar: bar
something: else  # just to illustrate filtering
```

```yaml
# AWS tags
- key: example.com/foo
  value: foo
- key: example.com/bar
  value: bar
```

### How could Crossplane help solve your problem?

I would love to see Crossplane adopt some mechanism for highly-expressive transformations. I am particularly fond of jq, which has an [implementation written in golang](https://github.com/itchyny/gojq) – perfect for Crossplane.

For this use case, my patch may look like this:

```yaml
patches:
  - type: FromCompositeFieldPath
    fromFieldPath: metadata.labels
    toFieldPath: spec.forProvider.tags
    transforms:
      - type: jq
        jq:
          jqExpression: 'to_entries | map(select(.key | startswith("example.com/")))'
```

This is a rather simple expression and very effectively handles our use case.

We could alternatively build out functionality like this using a Composition Function, but I think this proposal provides a way that users could get a lot of power out of the box without needing to learn how Composition Functions work.
