### ISSUE TITLE
Patching from environment to Composite resource status not working

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#4393]
### What happened?

I noticed some inconsistencies around how patches of type ToComposite behave with environmentConfigs enabled.
In the example below I would have expected to be able to patch with a `ToCompositeFieldPath` patch defined under `spec.environment.patches` the composite resource's status with a value coming from the environment. This is unexpected as it looks like it works for annotations and labels, but not for fields in the status, but works for patches coming from resources.

So, specifically in the example below I would have expected to see:
- `status.valueFromEnv` to be set on both the SQLInstance and XSQLInstance resources, as it's happening for `status.valueFromNopResource` set with a `ToCompositeFieldPath` from a resource.

### How can we reproduce it?

Create new kind cluster:
```shell
kind create cluster
```

Deploy Crossplane 1.12.2:
```shell
helm upgrade --install crossplane --namespace crossplane-system --create-namespace --set args={"--enable-environment-configs"} --version 1.12.2 crossplane-stable/crossplane
```

Deploy provider nop, composition and compositeResourceDefinition:
```yaml
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.0
  ignoreCrossplaneConstraints: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: nop.sqlinstances.example.org
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XSQLInstance
  environment:
    environmentConfigs:
      - ref:
          name: example-environment-1
        type: Reference
    patches:
      - type: ToCompositeFieldPath
        fromFieldPath: complex.c.f
        toFieldPath: status.valueFromEnv                                       # <= this doesn't work
      - type: ToCompositeFieldPath
        fromFieldPath: complex.c.f
        toFieldPath: metadata.annotations[valueFromEnv]               # <= this works
      - type: ToCompositeFieldPath
        fromFieldPath: complex.c.f
        toFieldPath: metadata.labels[valueFromEnv]                     # <= this works
  resources:
    - name: nop
      base:
        apiVersion: nop.crossplane.io/v1alpha1
        kind: NopResource
        spec:
          forProvider:
            fields:
              fromNopResource: "fromNopResource"
            conditionAfter:
              - conditionType: Ready
                conditionStatus: "False"
                time: 0s
              - conditionType: Ready
                conditionStatus: "True"
                time: 10s
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: spec.forProvider.fields.fromNopResource
          toFieldPath: status.valueFromNopResource                   # <= this works
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsqlinstances.example.org
spec:
  group: example.org
  names:
    kind: XSQLInstance
    plural: xsqlinstances
  claimNames:
    kind: SQLInstance
    plural: sqlinstances
  defaultCompositionRef:
    name: nop.sqlinstances.example.org
  defaultCompositeDeletePolicy: Background
  defaultCompositionUpdatePolicy: Automatic
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    storageGB:
                      type: integer
                  required:
                    - storageGB
              required:
                - parameters
            status:
              type: object
              properties:
                address:
                  description: Address of this MySQL server.
                  type: string
                valueFromEnv:
                  description: ValueFromEnv is the value of the environment variable.
                  type: string
                valueFromNopResource:
                  description: valueFromNopResource is the value of field in the nop resource.
                  type: string
```

Deploy environmentConfig:
```yaml
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: example-environment-1
data:
  complex:
    a: b
    c:
      d: e
      f: "1"
```

Deploy claim:
```yaml
---
apiVersion: example.org/v1alpha1
kind: SQLInstance
metadata:
  name: example
  namespace: default
  labels:
    stage: prod
spec:
  parameters:
    storageGB: 10
```

Get all related resources:
```shell
kubectl get sqlinstances.example.org,xsqlinstances.example.org,nopresources.nop.crossplane.io -o yaml
```
Resulting in:
```yaml
apiVersion: v1
items:
- apiVersion: example.org/v1alpha1
  kind: SQLInstance
  metadata:    # no valueFromEnv, nor valueFromNopResource annotation, nor label
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"example.org/v1alpha1","kind":"SQLInstance","metadata":{"annotations":{},"labels":{"stage":"prod"},"name":"example","namespace":"default"},"spec":{"parameters":{"storageGB":10}}}
     ...
  status:                                                                    # no valueFromEnv is set
    valueFromNopResource: fromNopResource   # This is propagated all the way from the underlying nop resource 
- apiVersion: example.org/v1alpha1
  kind: XSQLInstance
  metadata:
    ...
    annotations:
      valueFromEnv: "1"               # properly propagated
      valueFromNopResource: fromNopResource
      ...
    labels:
      ...
      valueFromEnv: "1"                  # properly propagated
      valueFromNopResource: fromNopResource
    name: example-m4xgs
  spec:
    ...
    environmentConfigRefs:
    - apiVersion: apiextensions.crossplane.io/v1alpha1
      kind: EnvironmentConfig
      name: example-environment-1
    parameters:
      storageGB: 10
  status:         # no valueFromEnv here
    ...
    valueFromNopResource: fromNopResource
- apiVersion: nop.crossplane.io/v1alpha1
  kind: NopResource
  metadata:
    ...
  spec:
    ...
    forProvider:
      ...
      fields:
        fromNopResource: fromNopResource
    providerConfigRef:
      name: default
  status:
    ...
kind: List
metadata:
  resourceVersion: ""
```

### What environment did it happen in?
Crossplane version: 1.12.2
