### ISSUE TITLE
packagePullSecrets is using the wrong secret + client rate limiter Wait returned an error

### ISSUE THREAD

**Issue by jtucci** [crossplane/crossplane#4452]
### What happened?

I changed the image tag of a configuration and deployed the resource into my cluster. I expected this to pull the new image in and create a new revision. 

Instead, no new revision was created and the configuration began to emit the following events. 

```
cannot unpack package: failed to fetch package digest from remote: Get "https://api.example.com.ondemand.com:443/api/v1/namespaces/crossplane-system/secrets/repository-1.example.com": context deadline exceeded

cannot unpack package: failed to fetch package digest from remote: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
```

I had no issue pulling the image locally using the same credentials set for packagePullSecrets

the configuration resource is 

```yml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: crossplane-configurations
    kustomize.toolkit.fluxcd.io/namespace: flux-system
status:
  conditions:
    - lastTransitionTime: '2023-07-14T21:33:36Z'
      reason: HealthyPackageRevision
      status: 'True'
      type: Healthy
    - lastTransitionTime: '2023-07-05T16:24:05Z'
      reason: ActivePackageRevision
      status: 'True'
      type: Installed
spec:
  ignoreCrossplaneConstraints: false
  package: >-
    repository-2.example.com/crossplane-compositions/redis:9e8dd226f4e81bf37b91609e886772262f9f546a
  packagePullPolicy: IfNotPresent
  packagePullSecrets:
    - name: repository-2.example.com
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false

```

This didn't make sense to me that the deadline event was referencing `repository-1.example.com` which is not the package pull secret specified in the configuration.  Does anyone have insight whats going on here?

This issue has randomly happed before in the past but I have been unable to consistently reproduce it. 

### What environment did it happen in?
Crossplane version: 1.12.2
k8s Version: 1.26.4
