### ISSUE TITLE
Finalizers on child claims of a composite are not being removed

### ISSUE THREAD

**Issue by darkmuggle** [crossplane/crossplane#4466]
### What happened?

I have a composition (call it "root") that XRs (call those "children"). I can create a claim on the root composition just fine, however, if I delete that claim, orphaned objects remain indefinitely.

I spent the better part of a day debugging and narrowed the problem down to Crossplane _not_ removing the finalizers on child claims. The objects are being deleted, but since the finalizer is not being removed, the objects remain. 

If I use a foreground delete, then the root claim is never deleted (which I guess is slightly better), but requires a human to get involved.

This bug is _serious_ IMO, as it can lead to real cloud resources being orphaned (as hit by the Upbound Orchestration team). 

Putting Crossplane into debug mode shows that the deletion of the claim is called:
```
2023-08-07T22:01:32Z    DEBUG    crossplane    Successfully deleted composite resource    {"controller": "defined/compositeresourcedefinition.apiextensions.cros
splane.io", "controller": "composite/kubecontrolplanes.mcp.upbound.io", "request": "/639b7d40-8d70-4d97-829c-4ca328b1bfc3", "uid": "6393834b-b985-448e-9ee6-f17f
3f9f1b47", "version": "18294", "name": "639b7d40-8d70-4d97-829c-4ca328b1bfc3", "deletion-timestamp": "2023-08-07 22:00:43 +0000 UTC"}
```

But the object remains because the finalizer is still there:
```
apiVersion: mcp.upbound.io/v1alpha1
kind: KubeControlPlane
metadata:
  annotations:
    crossplane.io/composition-resource-name: kube-control-plane
  creationTimestamp: "2023-08-07T21:58:10Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-08-07T22:00:43Z"
  finalizers:
  - kubernetes.crossplane.io/referred-by-object-d748a955-28c4-4b32-9e78-68718a0bb854
  generateName: 639b7d40-8d70-4d97-829c-4ca328b1bfc3-
```

If I remove the finalizer on the claim, it deletes _almost_ object in the claim, but some still remain:
```
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: kubernetes-providerconfig-tenant
    crossplane.io/external-create-pending: "2023-08-07T21:58:11Z"
    crossplane.io/external-create-succeeded: "2023-08-07T21:58:11Z"
    crossplane.io/external-name: 639b7d40-8d70-4d97-829c-4ca328b1bfc3-k4wmz
  creationTimestamp: "2023-08-07T21:58:11Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-08-07T22:06:16Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
```

### How can we reproduce it?

TBD -- I'll see about getting a test case. 

### What environment did it happen in?
UXP 1.12.2
Upbound Cloud
