### ISSUE TITLE
Deploying crossplane helm chart with GitOps shows out of sync

### ISSUE THREAD

**Issue by csantanapr** [crossplane/crossplane#4509]
### What happened?

When deploying crossplane helm chart with argocd it always shows out of sync for 2 Deployment (crossplane, crossplane-rbac-manager)

![image](https://github.com/crossplane/crossplane/assets/1094878/fc19ef85-185c-49ff-80f3-6d71a3033160)

The out of sync is on `env.valueFrom.resourceFieldRef.divisor`
In the helm chart the divisor is not set, and kubernetes mutates the Deployment to "0" which is the same as 1 or "1"

I proposed we set the `divisor` in the helm char to 1

```yaml
- env:
  - name: GOMAXPROCS
    valueFrom:
      resourceFieldRef:
        containerName: nginx
        divisor: "0"
        resource: limits.cpu
- name: GOMEMLIMIT
  valueFrom:
    resourceFieldRef:
      containerName: nginx
      divisor: "0"
      resource: limits.memory
```

### How can we reproduce it?
To reproduce deploy ArgoCD Application using crossplane chart
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-ex-crossplane-crossplane
  namespace: argocd
spec:
  destination:
    name: ex-crossplane
    namespace: crossplane-system
  project: default
  sources:
  - chart: crossplane
    helm:
      releaseName: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.13.2
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
```

### What environment did it happen in?
Crossplane version: 1.13.2

### References
- https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/resource/helpers.go#L343-L380
- [resource.Quantity](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2028-L2030)

**Comment by csantanapr** [comment]
workaround is to use ignoreDifferences
```yaml
      ignoreDifferences:
        - kind: Deployment
          jsonPointers:
            - /spec/template/containers/*/env/*/envFrom.resourceFieldRef.divisor
            - /spec/template/initContainers/*/env/*/envFrom.resourceFieldRef.divisor
```

**Comment by phisco** [comment]
Sounds more like an issue with ArgoCD rather than with Crossplane, we are just relying on the default value. However if explicitly setting it is enough to fix the issue, we can definitely do that. Feel free to open a PR, @csantana 🙏

**Comment by felixlut** [comment]
In my org we added the following lines to our ArgoCD application to have it be ignored, as per [their docs](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/):
```yaml
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions: 
      - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
      - .spec.template.spec.initContainers[].env[].valueFrom.resourceFieldRef.divisor
```
