### ISSUE TITLE
Feature: Crossplane packages should support upgrading dependencies

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#4511]
### What problem are you facing?

Given a starting configuration of 

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-scratch
spec:
  crossplane:
    version: ">=v1.12.2-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-gcp
      version: ">=v0.33.1"
``` 

If you update the dependencies on the Configuration and apply it:

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-scratch
spec:
  crossplane:
    version: ">=v1.12.2-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-gcp
      version: ">=v0.35.1"
``` 

The configuration will be unhealthy and generate events  `cannot resolve package dependencies: incompatible dependencies: [xpkg.upbound.io/upbound/provider-gcp]`. 

### How could Crossplane help solve your problem?

Configuration packages should have an option to upgrade dependent packages.

**Comment by abdulhaseeb3** [comment]
Hey
So we recently faced the same issue, it would be great to see this issue addressed.

**Comment by negz** [comment]
This is most important for configurations, but for the record we should make all types of package support upgrading their dependencies.

**Comment by ezgidemirel** [comment]
Hi all, I started working on this issue and want to discuss my initial thoughts and assumptions with you to shape the design:

1) Since this change would introduce a new behavior and could potentially lead to unexpected issues in user environments, I plan to implement it behind a feature flag. I don't think there are critical use cases for more granular control, so I recommend using a global flag in Crossplane rather than adding a spec field to the package resources. 
2) With the recent [change](https://github.com/crossplane/crossplane/pull/5965), Crossplane started to support using digests while installing packages. This new functionality introduces a new complexity in constraint checking. For example, if we install a configuration with a function dependency that uses a digest value corresponding to version `v0.2.0` and then attempt to install another package with a dependency on the same function with a `>=v0.1.0` constraint, the package manager must recognize that the digest version satisfies the new constraint. Given this complexity, I suggest to delay supporting this feature in alpha and treat digests and semantic versions as incompatible for now. Therefore, upgrading a package with digest to a package with semver will not be supported initially.  
3) Today, Crossplane (package manager) allows downgrading packages if `spec.package` is updated. Even though dependency version downgrades are slightly different (because it's implicit) I suggest to continue this behaviour and automatically downgrade a dependency if new installation attempt requires it. This support is especially important because package manager's dependency resolver works iteratively and installs the latest possible version which satisfies a single constraint and tries to resolve the next one afterwards. 
4) Currently, we cannot differentiate between a package installed manually and one installed as a dependency. If we want to avoid upgrading manually installed packages, we'll need to store this information in a place like the lock object or package CRs. For the alpha feature, I suggest to start with updating package versions without any restrictions and collect some feedback from users. If changing manually installed packages' versions is something we want to prevent, we can revisit it while promoting this feature to beta.

**Comment by negz** [comment]
> Given this complexity, I suggest to delay supporting this feature in alpha and treat digests and semantic versions as incompatible for now. Therefore, upgrading a package with digest to a package with semver will not be supported initially.

@ezgidemirel Can you help me understand this part?

* What would happen if I upgraded a package, and one of its dependencies was using a digest version?
* Would it be possible to upgrade packages on a control plane that used digests? For example would it be possible to upgrade a package with no digest-based dependencies on a control plane where other unrelated packages were installed using digests?

**Comment by negz** [comment]
@ezgidemirel Just thinking out loud (not sure this is a good idea) - could we annotate digest based packages with their version?

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  annotations:
    pkg.crossplane.io/pkg-version: v0.9.0
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws@sha256:hashhashash
```

This would just be an "honor system" approach. That is, if you tell Crossplane the digest is v0.9.0 it'll take your word for it and treat the package as v0.9.0.

This approach would at least let the dependency solver know whether a dependency was already satisfied by a digest-based package. I don't think it'd make sense to try to actually upgrade or downgrade digest based packages though. In my mind using a digest is like "pinning" a package to a specific version.

**Comment by ezgidemirel** [comment]
> * What would happen if I upgraded a package, and one of its dependencies was using a digest version?

If there is no other package depending on the same dependency with digest, package manager will update the version to the digest. If there are other packages depending on the same package with a constraint (either semver or a digest) then package manager will give an error. 

> * Would it be possible to upgrade packages on a control plane that used digests? For example would it be possible to upgrade a package with no digest-based dependencies on a control plane where other unrelated packages were installed using digests?
Yes. If there is no related dependency, we should be able to upgrade.

**Comment by ezgidemirel** [comment]
> This would just be an "honor system" approach. That is, if you tell Crossplane the digest is v0.9.0 it'll take your word for it and treat the package as v0.9.0.

@negz I agree that we need an interface to help dependency solver to proceed installations of packages with the same dependencies but using semvers instead of digests. But annotating with the exact tag doesn't feel like the right approach to me. Maybe we can set a semver range like: 

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  annotations:
    pkg.crossplane.io/version-range: >=v0.9.0
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws@sha256:hashhashash
```

This way if confA installs funcX with digest and confB tries to install funcX with range `>=v0.0.0`, we should be able to proceed with confB's installation. 

But, if we first install confB, funcX will be installed with the latest semver (let's say `v0.10.0`) and if we want to install confA afterwards, we cannot proceed with the installation. Because, there won't be a package to annotate.

So instead, we can fetch all the tags, verify their digests, and if we find a matching one that meets our semver constraints, we can move forward with the installation. If that digest is not tagged and pushed, we can simply give an error.
