### ISSUE TITLE
Providers take exclusive Ownership of Existing K8s Serviceaccounts

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#4552]
### Context 

There are times Crossplane users need to customize the Kubernetes service accounts that providers run under.  Some security policies require all pods to run with annotated service accounts. Another example is [AWS IAM policies](https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html) which can be matched to a combination Kubernetes Service Account and namespace.

In the case of labels and annotations, the ControllerConfig will add its labels and annotations to the ServiceAccount.

### What happened?

- When existing k8s service accounts are used in a `ControllerConfig` `serviceAccountName` setting, the Provider will take exclusive ownership of the resource. 
- If a service account is shared among multiple providers (as in the case of family providers sharing a single service account), only one ownerReference will be written.
- The single ownerReference causes the `ClusterRoleBindings` that are generated to only support one of the providers.
- When deleting a Provider, the serviceAccount will be deleted

### How can we reproduce it?

Create service accounts:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-aws-ec2
  namespace: upbound-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-aws-iam
  namespace: upbound-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-aws
  namespace: upbound-system
  annotations:
    a: b
    c: d
  labels:
    one: two
    three: four
```

Next create ControllerConfigs, note the `provider-aws` will be shared among family providers:

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: controllerconfig-aws-iam
spec:
  serviceAccountName: provider-aws-iam
  args:
    - --enable-management-policies 
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: controllerconfig-aws-ec2
spec:
  serviceAccountName: provider-aws-ec2
  args:
    - --enable-management-policies 
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: controllerconfig-aws
spec:
  serviceAccountName: provider-aws
  args:
    - --enable-management-policies
 ```

Finally install the providers. Note that the s3, eks and rds family providers are set to use the same `serviceAccountName`:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:v0.39.0
  controllerConfigRef:
    name: controllerconfig-aws-iam
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v0.39.0
  controllerConfigRef:
    name: controllerconfig-aws-ec2
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:v0.39.0
  controllerConfigRef:
    name: controllerconfig-aws
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-eks
spec:
  package: xpkg.upbound.io/upbound/provider-aws-eks:v0.39.0
  controllerConfigRef:
    name: controllerconfig-aws
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-rds
spec:
  package: xpkg.upbound.io/upbound/provider-aws-rds:v0.39.0
  controllerConfigRef:
```

Once the providers are healthy, we can look at the Service accounts:

 `provider-aws-iam` has a single owner  and `"controller": true,` even though the account was created outside of the Crossplane package manager.

```console
kubectl get sa -n upbound-system provider-aws-iam -o jsonpath='{.metadata.ownerReferences}' | jq
[
  {
    "apiVersion": "pkg.crossplane.io/v1",
    "blockOwnerDeletion": true,
    "controller": true,
    "kind": "ProviderRevision",
    "name": "provider-aws-iam-e4667f1b5f01",
    "uid": "3e04dfd7-d9f5-4e99-9b28-db539956ca6f"
  }
]
```

For the shared `provider-aws` only one of the three controllers is listed as an `ownerReference`. T

```console
kubectl get sa -n upbound-system provider-aws -o jsonpath='{.metadata.ownerReferences}' | jq 
[
  {
    "apiVersion": "pkg.crossplane.io/v1",
    "blockOwnerDeletion": true,
    "controller": true,
    "kind": "ProviderRevision",
    "name": "provider-aws-s3-e6123c010ecc",
    "uid": "61f520b6-a9df-4b1a-9a45-8191c1a3f7b0"
  }
]
```

This lack of additional owners causes the `ClusterRoleBinding` for the eks family provider to not have a subjet k8s service account:

```
kubectl get clusterrolebinding crossplane:provider:provider-aws-eks-b731c789c55c:system    -o yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2023-08-31T20:26:27Z"
  name: crossplane:provider:provider-aws-eks-b731c789c55c:system
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ProviderRevision
    name: provider-aws-eks-b731c789c55c
    uid: 1e6ec2bc-b24e-46ce-b85f-1cd0c411e6f2
  resourceVersion: "2697"
  uid: 85060c1c-4bdf-45e1-bfcc-3797a32feb3f
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:provider:provider-aws-eks-b731c789c55c:system
```

If we delete the provider-aws-iam package, the linked serviceAccount will be deleted:

```console
kubectl delete provider.pkg provider-aws-iam
provider.pkg.crossplane.io "provider-aws-iam" deleted

kubectl get sa -n upbound-system provider-aws-iam 
Error from server (NotFound): serviceaccounts "provider-aws-iam" not found
```

### What environment did it happen in?
Crossplane version: UXP v1.13.2

 hardware configuration
* Kubernetes version: v1.27.1
* Kubernetes distribution: Kind
