### ISSUE TITLE
Make Patch & Transform and Functions in a Composition mutually exclusive

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4558]
### What problem are you facing?

In the [beta Fuctions design](https://github.com/crossplane/crossplane/blob/863ff6c2f53af47424dab941dbef83ca12e7d74f/design/design-doc-composition-functions.md) (and previously, in the alpha design) we support using contemporary Patch & Transform style Composition together with Functions. When you specify both `spec.resources` and `spec.pipeline` in a Composition Crossplane will first process the array of resource templates. Before applying them, they're passed to the Function pipeline for processing.

The benefits of this approach are:
* Folks can adopt Functions with strictly additive updates to their existing Compositions
* You can use mostly P&T, "decorated" with small Functions - e.g. to validate your P&T resources

There are however a few drawbacks:
* It makes the Composition logic quite complex, which is likely to lead to bugs
* Some of the interactions between the P&T logic and the Function pipeline are unintuitive / hard to reason about

I also personally believe that long term we should have as little Composition logic built in to Crossplane as possible. When we think about developer experience, we often wish there was a CLI that could render a Composition client-side to give you an idea of how it might work. If _all_ Composition logic was captured in Functions, versioned and released separately from Crossplane, it would be possible for a CLI to pull down all the Functions used by a Composition and render it without having to share much code with Crossplane. So - long term I think will we want to discourage the use of P&T and encourage use of Functions.

### How could Crossplane help solve your problem?

I think Composition would be simpler and more predictable if you weren't able to use the "native" P&T resources array together with Functions. I say "native" because I _do_ think that P&T should be implemented as a Function. That way the complexity of P&T runs _inside_ the Function pipeline - it's not a special, separate stage before it.

**Comment by negz** [comment]
Note the idea of P&T-as-a-Function is captured [in the beta design](https://github.com/crossplane/crossplane/blob/863ff6c2f53af47424dab941dbef83ca12e7d74f/design/design-doc-composition-functions.md#patch-and-transform-as-a-function). If P&T were implemented as a Function I think the API would look like this:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: AcmeCoDatabase
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: patch-and-transform
    input:
      apiVersion: apiextensions.crossplane.io/v1
      kind: Resources
      resources:
      - name: cloudsqlinstance
        base:
          apiVersion: database.gcp.crossplane.io/v1beta1
          kind: CloudSQLInstance
          spec:
            forProvider:
              databaseVersion: POSTGRES_9_6
              region: us-central1
              settings:
                tier: db-custom-1-3840
                dataDiskType: PD_SSD
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.settings.dataDiskSizeGb
```

Note that the only change API-wise is that `resources` becomes nested under `pipeline` (with a bit of boilerplate around it).

By making this change:
* P&T Functionality can be developed, released, and versioned separately from Crossplane
* Folks with niche P&T needs (like extra transforms) can more easily fork the Function
* The Composition logic in Crossplane becomes much simpler (and thus more resilient to bugs)

One key downside of this approach would be losing validation of the `resources` array, given that `input` is just an opaque object to the API server. Perhaps we could address this by making it possible for a Function to add a validation webhook for its input type.
