### ISSUE TITLE
Clear Ownership of Fields Between Claim and Composite

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4581]
### What happened?

Claims are namespaced resources that (create and) bind to cluster-scoped Composite resources by propagating the spec provided by the user. Being created by the same schema defined in the CompositeResourceDefinition (XRD), they contain the same fields under spec and status in addition to the ones [dedicated](https://github.com/crossplane/crossplane/blob/226b81f575f2cf68986da827e87b5ba34aa5121f/internal/xcrd/schemas.go#L70) to each type. 

Today, in the claim controller, we merge the spec/status of the claim instead of clear ownership:

- Claim → composite: We [merge](https://github.com/crossplane/crossplane/blob/a888ea7657f12d2dd9effa5ef8da8b17b0bea404/internal/controller/apiextensions/claim/configurator.go#L234) the spec of the claim with the spec of the composite. (causing https://github.com/crossplane/crossplane/issues/3421)
- Claim → Composite: We [add](https://github.com/crossplane/crossplane/blob/a888ea7657f12d2dd9effa5ef8da8b17b0bea404/internal/controller/apiextensions/claim/configurator.go#L97-L98) (i.e. merge) to the existing labels/annotations on composites instead of overwriting with what is in the claim. (causing https://github.com/crossplane/crossplane/issues/4315)
- Composite → Claim: We [merge](https://github.com/crossplane/crossplane/blob/a888ea7657f12d2dd9effa5ef8da8b17b0bea404/internal/controller/apiextensions/claim/configurator.go#L192) the status of the claim with the status of the composite. (causing https://github.com/crossplane/crossplane/issues/3542)

### How can we reproduce it?

See reproduction steps under the corresponding directory at: https://github.com/turkenh/xp-ssa-experiments

### How could Crossplane help solve your problem?

I propose we define and stick to clear ownership of fields between claims and composites without no merging:

- Spec goes from claim to composite.
- Status goes from composite to claim.
- Annotation/Labels go from claim to composite.

The last one could be a bit controversial, and we may want to enable some ways to enable propagating metadata back (as requested in https://github.com/crossplane/crossplane/issues/3180) /cc @phisco 

This would also enable switching to [Server Side Apply](https://github.com/crossplane/crossplane/issues/4047) in the claim controller, instead of the Patching applicator. /cc @pedjak

**Comment by negz** [comment]
I chatted with @turkenh and I'm going to take a pass at this in https://github.com/crossplane/crossplane/pull/4500.

**Comment by pedjak** [comment]
My understanding is that XR `.spec` is kept in sync (not merged) with claim's `.spec`, see [this line](https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/claim/configurator.go#L131). This happens on every claim reconciliation, so that later [merge](https://github.com/crossplane/crossplane/blob/a888ea7657f12d2dd9effa5ef8da8b17b0bea404/internal/controller/apiextensions/claim/configurator.go#L234) of claim `.spec` with XR `.spec` is no-op. Is my observation correct?

**Comment by turkenh** [comment]
> so that later merge of claim .spec with XR .spec is no-op.
Once you merge claim spec with XR spec, you bring whatever in claim back to XR, so, it wouldn't be a no-op if XP spec is different than claim somehow (e.g. P&T patched to XR spec, or some manual changes done)

Let me try to explain with an example:

1. You created the following claim:

```yaml
apiVersion: example.io/v1alpha1
kind: AcmeDatabase
metadata:
  ..
spec:
  parameters:
    tags:
      foo: bar
```

which created 

```yaml
apiVersion: example.io/v1alpha1
kind: XAcmeDatabase
metadata:
  ..
spec:
  parameters:
    tags:
      foo: bar
```

2. You manually changed the composite (or have a composition writing back to the XR) and added another tag:

```yaml
apiVersion: example.io/v1alpha1
kind: XAcmeDatabase
metadata:
  ..
spec:
  parameters:
    tags:
      foo: bar
      new_tag: test
```

3. What you would see after the claim reconciler does its job is (new label propagated back to claim because of that [merge](https://github.com/crossplane/crossplane/blob/a888ea7657f12d2dd9effa5ef8da8b17b0bea404/internal/controller/apiextensions/claim/configurator.go#L234)):

```yaml
apiVersion: example.io/v1alpha1
kind: AcmeDatabase
metadata:
  ..
spec:
  parameters:
    tags:
      foo: bar
      new_tag: test
```

This issue proposes this not to happen and the claim spec to be authoritative overriding the manual change on XR.
