### ISSUE TITLE
Rename `environment.environmentConfigs` to `environment.configs`

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4591]
### What problem are you facing?

Currently, the field keeping the references to environment configs is named `environmentConfigs`:

```yaml
spec:
  environment:
    environmentConfigs:
    - type: Reference
      ref:
        name: example-environment
    - type: Selector
      selector:
        matchLabels:
      # Removed for brevity
```

Given that the parent field is `environment`, repeating once again it as the prefix in `envrionmentConfigs` feels redundant, affecting readability.

### How could Crossplane help solve your problem?

Given that Environment API is still alpha, we could rename `environmentConfigs` to `configs`, improving the readability.
