### ISSUE TITLE
Error when upgrading crossplane from v1.12.2 to v1.13.2 when using customAnnotation 

### ISSUE THREAD

**Issue by jtucci** [crossplane/crossplane#4593]
### What happened?
I attempted to upgrade crossplane from v1.12.2 to v1.13.2. The release was installed via HelmRelease. It appears that if the previous release was using customAnnotations value to allow xfn to run, upgrading crossplane will fail because of duplicate annotation keys. 

The rendered Helm Release I was using pre upgrade was 
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: crossplane
      version: 1.12.2
  install:
    crds: Create
    createNamespace: true
    remediation:
      retries: 5
  interval: 24h0m0s
  releaseName: crossplane
  serviceAccountName: kustomize-controller
  targetNamespace: crossplane-system
  test:
    enable: false
  timeout: 20m0s
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 5
      strategy: rollback
  values:
    args:
    - --debug
    - --enable-environment-configs
    - --enable-composition-functions
    - --enable-external-secret-stores
    customAnnotations:
      container.apparmor.security.beta.kubernetes.io/crossplane-xfn: unconfined
    metrics:
      enabled: true
    resourcesRBACManager:
      limits:
        cpu: 100m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 256Mi
    xfn:
      args:
      - --debug
      enabled: true
```

Upgrading to 1.23.2 results in the following failure 

```
Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 36: mapping key "container.apparmor.security.beta.kubernetes.io/crossplane-xfn" already defined at line 35 Last Helm logs: preparing upgrade for crossplane resetting values to the chart's original version
```

I believe this is do to a change in the helm chart, specifically this section:
```
      {{- if .Values.xfn.enabled }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}-xfn: unconfined
      {{- end }}
```
For anyone who manually set this value to get their XFN to work (like I did), this change causes the upgrade to fail. 

The associated release note was `Fix composition functions to be able to run with unconfined AppArmor profile.`

I think the release notes should be documented to clearly state this potentially breaking change. It took some diggging to understand why my upgrade had failed.
