### ISSUE TITLE
Claim name can be max 57 chars long

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4645]
### What happened?

If a claim name is longer than 63 characters, the corresponding XR cannot be created during the claim reconcile loop.

### How can we reproduce it?

* install provider nop

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.0
  ignoreCrossplaneConstraints: true
```

* add XRD

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnopresources.nop.example.org
spec:
  group: nop.example.org
  names:
    kind: XNopResource
    plural: xnopresources
  claimNames:
    kind: NopResource
    plural: nopresources
  connectionSecretKeys:
  - test
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            coolField:
              type: string
          required:
          - coolField
```

* add composition

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  resources:
  - name: nop-resource-1
    base:
     apiVersion: nop.crossplane.io/v1alpha1
     kind: NopResource
     spec:
      forProvider:
        conditionAfter:
        - conditionType: Ready
          conditionStatus: "False"
          time: 0s
        - conditionType: Ready
          conditionStatus: "True"
          time: 10s
```

* try to create the following claim

```yaml
apiVersion: nop.example.org/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: res-1234567890-1234567890-1234567890-1234567890-1234567890-12345
spec:
  coolField: "I'm cool!"
```

The claim gets created, but remains unsynced due to:

```yaml
status:
  conditions:
  - lastTransitionTime: "2023-09-19T18:31:45Z"
    message: 'cannot configure composite resource: cannot use dry-run create to name
      composite resource: XNopResource.nop.example.org "res-1234567890-1234567890-1234567890-1234567890-1234567890d5df8"
      is invalid: metadata.labels: Invalid value: "res-1234567890-1234567890-1234567890-1234567890-1234567890-12345":
      must be no more than 63 characters'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### What environment did it happen in?

All supported Crossplane versions are affected.

### How could Crossplane help solve your problem?

As could be seen above, the root cause is that [labels cannot be longer than 63 chars](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) and XR created during claim reconciliation gets equipped  with the following labels, as [documented](https://docs.crossplane.io/master/concepts/composite-resources/#composite-resource-labels):

* `crossplane.io/claim-name`
* `crossplane.io/claim-namespace`

Furthermore, the composite controller attaches XR name via `crossplane.io/composite` label as well to the same XR resource. Given that XR names are derived from the claim name by appending it with 6 char suffix, the actual claim name cannot be longer than 57 chars.

There are two possible paths for solving the issue:
1. validate claim name at the creation time and refuse it if longer than 57 chars
2. deprecate usage of the above labels and migrate to annotations for the same purpose, because such limits do not exists for annotation values

If the migration to annotations is feasible, consider:
* collapsing `crossplane.io/claim-*` into single `crossplane.io/claim-ref` annotation containing JSON representation of XR `.spec.claimRef`
* avoiding `crossplane.io/claim-*` annotations on XR, given that the reference already exists under `.spec.claimRef`
