### ISSUE TITLE
cannot add composite resource finalizer

### ISSUE THREAD

**Issue by richardvflux** [crossplane/crossplane#4649]
### What happened?

I am simply adding a new XRD. 

````
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xssmaccessdeployments.fluxfederation.com
  annotations:
    "helm.sh/hook-weight": "5"
spec:
  group: fluxfederation.com
  names:
    kind: XSsmAccessDeployment
    plural: xssmaccessdeployments
  claimNames:
    kind: SsmAccessDeployment
    plural: ssmaccessdeployments
    categories:
      - all
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                deploymentNameSpace:
                  type: string
                clusterName:
                  type: string
              required:
                - deploymentName
                - deploymentNameSpace
````

### How can we reproduce it?

The crossplane pod gets this in its logs 

````
2023-09-21T04:43:01Z	DEBUG	crossplane	cannot add composite resource claim finalizer	{"controller": "offered/compositeresourcedefinition.apiextensions.crossplane.io", "request": {"name":"xssmaccessdeployments.fluxfederation.com"}, "uid": "2821b812-3232-4db0-8e44-82a3ee108ed4", "version": "2878507", "name": "xssmaccessdeployments.fluxfederation.com", "error": "cannot update object: Internal error occurred: failed calling webhook \"compositeresourcedefinitions.apiextensions.crossplane.io\": failed to call webhook: Post \"https://crossplane-webhooks.crossplane-system.svc:9443/validate-apiextensions-crossplane-io-v1-compositeresourcedefinition?timeout=10s\": context deadline exceeded"}
````

On examination, only the rbac controller has access to the `compositeresourcedefinitions` finalizer field (it has an update verb on that field), the crossplane pod does not. 

### What environment did it happen in?
Crossplane version:  1.13.2

````
helm upgrade --install crossplane https://charts.crossplane.io/stable/crossplane-1.13.2.tgz -n crossplane-system
````

* Cloud provider: AWS
* Kubernetes version: 1.27.4 (server)
* Kubernetes distribution: EKS, managed servers
