### ISSUE TITLE
ProviderConfigUsage does not work when deletion policy is set to Foreground

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4661]
### What happened?

While testing my [function tee prototype](https://github.com/crossplane/crossplane/discussions/4639#discussioncomment-7079961) with a claim using `compositeDeletePolicy: Foreground`, I noticed that `ProviderConfigUsage` does not work as expected. 

So, my function outputs a provider kubernetes `ProviderConfig` resource (with InjectedIdentity) and an `Object` wrapping a ConfigMap and using that `ProviderConfig`. When I delete my claim, I noticed that the `Object` resource is orphaned since the `ProviderConfig` was deleted before the `Object` itself. I verified that the `ProviderConfig` resource had the `in-use.crossplane.io` finalizer and the corresponding `ProviderConfigUsage` resource existed.

After some investigation and thought, I believe this is a bug with the current implementation of `ProviderConfigUsage` when it is used with deletion policy Foreground. The issue is, with this mode of deletion propagation, resources are being deleted starting from the bottom of the tree and hence `ProviderConfigUsage` being owned by the `Object` is deleted before the actual `Object` is deleted. This removes the blockage on `ProviderConfig` and it got deleted without waiting the deletion of the `Object`. 

@bobh66 I am wondering if you had encountered something like this before? 

### How can we reproduce it?

```bash
kubectl apply -f setup.yaml
kubectl apply -f claim.yaml
# wait until claim is ready
kubectl delete -f claim.yaml

```
<details>
<summary>setup.yaml</summary>

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.0
  ignoreCrossplaneConstraints: true
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-dummy
spec:
  # NOTE(negz): This is currently manually pushed. See README.md at
  # https://github.com/crossplane-contrib/function-dummy.
  package: xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-tee
spec:
  package: turkenh/function-tee:v0.1.0
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnopresources.nop.example.org
spec:
  group: nop.example.org
  names:
    kind: XNopResource
    plural: xnopresources
  claimNames:
    kind: NopResource
    plural: nopresources
  connectionSecretKeys:
  - test
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            coolField:
              type: string
          required:
          - coolField
        status:
          type: object
          properties:
            coolerField:
              type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: be-a-dummy
    functionRef:
      name: function-dummy
    input:
      apiVersion: dummy.fn.crossplane.io/v1beta1
      kind: Response
      # This is a YAML-serialized RunFunctionResponse. function-dummy will
      # overlay the desired state on any that was passed into it.
      response:
        desired:
          composite:
            resource:
              status:
                coolerField: "I'M COOLER!"
          resources:
            nop-resource-1:
              resource:
                apiVersion: nop.crossplane.io/v1alpha1
                kind: NopResource
                spec:
                  forProvider:
                    conditionAfter:
                    - conditionType: Ready
                      conditionStatus: "False"
                      time: 0s
                    - conditionType: Ready
                      conditionStatus: "True"
                      time: 10s
              ready: READY_TRUE
        results:
         - severity: SEVERITY_NORMAL
           message: "I am doing a compose!"
  - step: tee
    functionRef:
      name: function-tee
```

</details>

<details>
<summary>claim.yaml</summary>

```
apiVersion: nop.example.org/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: apiextensions-composition-functions
spec:
  coolField: "I'm cool!"
  # This is necessary to ensure the claim's MRs are actually gone before we
  # delete the Provider - https://github.com/crossplane/crossplane/issues/4251
  compositeDeletePolicy: Foreground
```

</details>

### What environment did it happen in?
Crossplane version: v1.14.0-rc.0.369.g293439e0

**Comment by bobh66** [comment]
@dukanto This is the scenario that the `Usage` resource in 1.14 is intended to address.  You would need to define a `Usage` of the `ProviderConfig` by the `ResourceGroup` in order to block deletion of the `ProviderConfig` until the `ResourceGroup` has been deleted.

**Comment by stevendborrelli** [comment]
I'm going to chime in here, I don't understand why we need a `Usage`  type when providerConfigUsages are present. We'd have to create a bunch of `Usages` for every single resource.

**Comment by bobh66** [comment]
`ProviderConfigUsage` is only for `ProviderConfig` whereas the `Usage` type is generic across all resources and across `Providers` and Composites. 

I think the issue in this case is that the `ProviderConfigUsage` resources don't have a finalizer on them so when the delete request happens they just get deleted without any concern for the fact that they are still in use.  They don't block deletion of the `ProviderConfig`.

If we were to put a finalizer on the `ProviderConfigUsage` it would serve the same purpose for `ProviderConfig` as the `Usage` does for more generic use cases and eliminate the need to create a `Usage` on the `ProviderConfig`.

**Comment by bobh66** [comment]
The `ProviderConfig` reconciler will block deletion of the `ProviderConfig` as long as it has `ProviderConfigUsage` resources associated with it, but since nothing is preventing the deletion of the `ProviderConfigUsage` resource on a cascading delete, eventually the `ProviderConfig` will have no more PCUs pointing at it and it will be deleted.

**Comment by bobh66** [comment]
Since the `ProviderConfigUsage` is owned by the Managed Resource, and does not have a finalizer, it is deleted immediately when the MR is marked deleted.  This opens up a window where the MR exists but the `ProviderConfig` has no knowledge of it so the `ProviderConfig` could be deleted while the MR is still trying to delete the external resource.

I think it would be better to put a finalizer on the `ProviderConfigUsage` and have crossplane-runtime delete either the PCU or it's finalizer or both after a successfull call to the `Delete` method.

**Comment by bobh66** [comment]
I think we can solve this by adding a finalizer to the `ProviderConfigUsage` in the `Track` function here:

https://github.com/crossplane/crossplane-runtime/blob/master/pkg/resource/providerconfig.go#L151

and check for the presence of the finalizer and delete it from the `ProviderConfigUsage` when we remove the finalizer from the MR here:

https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reconciler/managed/reconciler.go#L992

That will keep the `ProviderConfigUsage` in place until the MR is actually deleted, so the `ProviderConfig` should also be preserved until all associated MRs are gone.

I'll push a PR for review.

**Comment by bobh66** [comment]
Adding the finalizer in the `Track()` function is trivial.  Removing the finalizer after the `Delete()` call is a bit more complicated.

Ideally we would remove the finalizer in the managed `Reconciler()` after the external `Delete()` call and removing the finalizer from the MR.  However the managed reconciler does not have a `ProviderConfigUsageTracker` and since the `ProviderConfigUsage` group is specific to the MR provider group we would have to derive the `ProviderConfigUsage` GV from the `ProviderConfig` GVK in order to fetch it and remove the finalizer.

The only alternative I can think of is to add an `UnTrack()` function to the `ProviderConfigUsageTracker` and have the provider call `UnTrack` in the `Delete` function, but that would be a lot of work and coordination.

@negz @turkenh any thoughts?

**Comment by bobh66** [comment]
Another thought - add a `TrackWithFinalizer` method to the existing `ProviderConfigUsageTracker` that calls the existing `Track` method and then adds the finalizer, and then the providers could be updated as needed to call `TrackWithFinalizer` instead of `Track`, and `UnTrack` in the `Delete` method.  It's still extra work in the providers but it keeps the managed reconciler clean.

**Comment by avarei** [comment]
the reconciler of ProviderConfig also watches ProviderConfigUsages. My understanding is that there is no reconciler specifically for ProviderConfigUsages. So maybe the removal of the finalizer could be handled by the ProviderConfig reconciler?

the finalizer could be added here:
https://github.com/crossplane/crossplane-runtime/blob/2b288ff362cbb55d8b5b4402bff7fd4faa5fcf45/pkg/reconciler/providerconfig/reconciler.go#L175
and removed here when the referenced resource is removed.
https://github.com/crossplane/crossplane-runtime/blob/2b288ff362cbb55d8b5b4402bff7fd4faa5fcf45/pkg/reconciler/providerconfig/reconciler.go#L192

this way, there would be no changes for the implementation on the provider side

**Comment by avarei** [comment]
I created a very rough poc implementation of the of the the idea I suggested.
It technically works but at the moment I think it slows down deletion of resources significantly.

I changed the providerConfigUsage creation to add a finalizer and I set ownerReferences.blockOwnerDeletion to false to allow the MR to be deleted independently of the PCU and added logic to remove the finalizer in the providerConfig reconciler.

https://github.com/crossplane/crossplane-runtime/compare/main...avarei:crossplane-runtime:poc/provider-config-usage-finalizer

I'd be interested in some feedback. Do you think I should refine this approach and create a MR, or do you favor the approach @bobh66 suggested which feels cleaner, but would need a bit of work by the providers to implement. 

I'd also be happy contribute towards eigther.

**Comment by bobh66** [comment]
I'm not opposed to decoupling the two delete processes as long as the delayed PCU delete handling doesn't block the MR deletion.  The PCU will have an invalid `ownerReference` as soon the MR gets deleted and I think the GC might remove it from the PCU?

The reconciler should clean up any "dangling" PCUs before processing a delete of the `ProviderConfig` so I wouldn't expect them to block deletion of the PC.

@turkenh @negz thoughts?

**Comment by avarei** [comment]
Maybe crossplane v2 provides the opportunity to add providerConfigUsage finalisers to the provider framework?

**Comment by knhsll** [comment]
> Maybe crossplane v2 provides the opportunity to add providerConfigUsage finalisers to the provider framework?

+1, we also need providerConfigUsage finalizers for our project

**Comment by tvandinther** [comment]
This issue also surfaces now more prominently with Crossplane V2 due to the introduction of namespaced managed resources. If a namespace is deleted and put into `Terminating` state, deletion events will be sent to all of the namespaced resources, which of course includes the `ProviderConfigUsage` which has nothing preventing its deletion.

However, now that the namespace is in `Terminating` state, Crossplane can no longer recreate the `ProviderConfigUsage` when trying to reconcile the delete event (to actually delete the external resource). As a result, the runtime produces an error and the namespace deletion becomes stuck.

I believe that the solution to this is for the Crossplane runtime to manage a finalizer on the `ProviderConfigUsage` which is removed when the referenced managed resource has been deleted.

**Comment by bobh66** [comment]
The complexity in the "ideal" solution is caused by the fact that crossplane-runtime provides a `ProviderConfigUsageTracker` which is consumed by the _providers_ calling `Track()` to create the `ProvidereConfigUsage`, and which could easily add the finalizer, but there is no corresponding `UnTrack` mechanism defined or called by the providers.  crossplane-runtime has no access to the `ProviderConfig` in the MR reconciler, which would be the ideal place to call `UnTrack`, but instead it would be up to every provider to call `UnTrack` to remove the finalizer.  And of course the finalizer cannot be added until the code to remove it has also been added, so that needs to be coordinated with a flag to know which MRs have been updated and which have not.

**Comment by tvandinther** [comment]
I can't advise on the way this should be implemented but I do believe that this is functionality that Crossplane should cover and I categorise it as a bug which prevents proper cleanup with Kubernetes garbage collection.

While waiting for the fix, I patched the issue by deploying a custom controller to explicitly manage finalizers on `ProviderConfigUsage` so that namespaces containing namespaced resources can actually be deleted using a cascading delete.

**Comment by jeanduplessis** [comment]
We'll be looking to address this issue in the XP v2.2 release timeframe.

**Comment by negz** [comment]
@jbw976 Heads up, I removed this from parent issue https://github.com/crossplane/crossplane/issues/6001. I don't think they're related. LMK if I've missed something though.

**Comment by jeanduplessis** [comment]
Capturing some context from an offline conversation... 

Converging on `Usage` instead of maintaining two different solutions for similar problems might be feasible.

Considerations for convergence approach:
- `ProviderConfigUsage` predates `Usage` and uses a different mechanism. It appears to have a more straightforward approach to the problem (e.g., no webhooks like Usages) for the specific use case, which works for standard scenarios but falls apart when non-default deletion policy foreground is used.
- Before replacing `ProviderConfigUsage` with `Usage`, ensure full understanding of how it works today and what replacement implications exist (e.g., to confirm all use cases will be covered).

Two immediate concerns to address:
1. Scale testing: `Usages` are based on webhooks and `ProviderConfigUsages` are created per MR, meaning reliance on `Usages` would occur at a higher scale. Potential issues at high scale should be tested.
2. User experience: Currently when users list `Usage` resources, they see a small list that they explicitly created. After this change, they would see (number-of-MRs) + their own explicit `Usages`. This could cause confusion and it would be beneficial to find a way to differentiate between them, if possible.

**Comment by bobh66** [comment]
Maybe create a new `ProviderConfigUsage` under the `protection` API group that is used for `ProviderConfigs` - it can use all of the same logic as the `Usage` but only apply to `ProviderConfigs` to maintain the separation expected by the users.

**Comment by bobh66** [comment]
Just putting this here as an example of one possible implementation for my own benefit:

```yaml
apiVersion: protection.crossplane.io/v1alpha1
kind: ProviderConfigUsage
metadata:
  name: myhelmrelease-uses-myhelmproviderconfig
spec:
  by:
    apiVersion: helm.crossplane.io/v1beta1
    kind: Release
    resourceRef:
      name: myhelmrelease
  of:
    apiVersion: helm.crossplane.io/v1beta1
    kind: ProviderConfig
    resourceRef:
      name: myhelmproviderconfig
  replayDeletion: true
```

This prevents the `ProviderConfig` from being deleted as long as the resource that is using it exists.

This could also be implemented in crossplane-runtime and use the same API group as the provider as is done now with the existing `ProviderConfigUsage` if that makes more sense.
