### ISSUE TITLE
Throw an error/message when OCI-Registiry is not reachable

### ISSUE THREAD

**Issue by ra0e** [crossplane/crossplane#4682]
### What problem are you facing?
After some changes on Compositions, I wanted to test them on our dev cluster. Therefore, I changed the package reference to the according MR. However, I did a copy & paste mistake. 

Changing the package reference to my newly build package

```
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-dev
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  ignoreCrossplaneConstraints: true
  skipDependencyResolution: true
  package: 5893.dkr.ecr.eu-central-1.amazonaws.com/cp/sop:mr-345
  commonLabels:
    version: mr-345

```

However, nothing happened. When I described the resource 
`kubectl get configuration crossplane-dev -o yam` 

I got 

```
spec:
  commonLabels:
    version: mr-345
  ignoreCrossplaneConstraints: true
  package: 5893.dkr.ecr.eu-central-1.amazonaws.com/cp/sop:mr-345
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: true
status:
  conditions:
  - lastTransitionTime: "2023-09-21T13:19:22Z"
    reason: HealthyPackageRevision
    status: "True"
    type: Healthy
  - lastTransitionTime: "2023-02-22T08:18:17Z"
    reason: ActivePackageRevision
    status: "True"
    type: Installed
  currentIdentifier: 9103.dkr.ecr.eu-central-1.amazonaws.com/cp/sop:mr-123
  currentRevision: crossplane-dev-a9c96c1cbc8a
```

Notice that there is a **difference** in between `spec.package: 5893.dkr.ecr.eu-central-1.amazonaws.com/cp/sop:mr-345` and `currentIdentifier: 9103.dkr.ecr.eu-central-1.amazonaws.com/cp/sop:mr-123`

I did not understand why Crossplane still uses  `mr-123`. It turns out that I used an account `(5893)` which has no rights to pull the package from the ECR. After using the right account, `(9103)` it worked. 

### How could Crossplane help solve your problem?
If it is possible, throw an event or message that the given ECR is not accessible by Crossplane. I think, it would make debugging much more straight forward.
