### ISSUE TITLE
Silent failure from composition when child resource spec is invalid

### ISSUE THREAD

**Issue by amanfredi** [crossplane/crossplane#4689]
### What happened?

I have been working on creating a Composition involving several resources from the AWS provider. The behavior I'm seeing is that if the spec of one of my sub-resources is structurally invalid, the composition fails to render but with no error events produced.

For example, I tried to create a Route53 Record with the following syntax:
```
apiVersion: route53.aws.upbound.io/v1beta1
kind: Record
metadata:
  name: test-record
spec:
  providerConfigRef:
    name: my-provider-config
  forProvider:
    alias:
      evaluateTargetHealth: false
      name: some-domain.cloudfront.net
      zoneId: Z2FDTNDATAQYW2 # magic zoneId for alias to CloudFront Distributions
    name: test-1
    type: A
    zoneIdRef:
      name: example.io
    region: us-east-1
```
This is invalid because per the Record spec, `alias` is expected to be an array and not an object.
When applying the yaml with kubectl, you receive the following error:
```Error from server (BadRequest): error when creating "test-record.yaml": Record in version "v1beta1" cannot be handled as a Record: strict decoding error: unknown field "spec.forProvider.alias.evaluateTargetHealth", unknown field "spec.forProvider.alias.name", unknown field "spec.forProvider.alias.zoneId"```

However, when created as part of a Composition, the creation of the Record fails silently, and the Composite Resource never becomes ready.

### What environment did it happen in?
Crossplane version: 1.13
upbound/provider-family-aws v0.40.0
