### ISSUE TITLE
Set `spec.compositeDeletePolicy` default value on claim CRD

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4691]
### What problem are you facing?

If claim's `spec.compositeDeletePolicy` is not set, at reconcile the controller is going [to set](https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/claim/api.go#L156-L166) it to the value read from `spec.defaultCompositionDeletePolicy` found in `CompositeResourceDefinition`. As the consequence, the claim is going to be modified in the backend, leading to one additional no-op reconcile round.

### How could Crossplane help solve your problem?

Claim CRD should be generated so that the default value is specified for `spec.compositeDeletePolicy`:

```yaml
spec:
  properties:
    compositeDeletePolicy:
      default: Background
      enum:
      - Background
      - Foreground
      type: string
```
