### ISSUE TITLE
Declare `status.conditions` on resources as associative list

### ISSUE THREAD

**Issue by pedjak** [crossplane/crossplane#4692]
### What problem are you facing?

Currently `status.conditions` is declared as atomic list, forcing us to provide always the whole list during updates. If we want to achieve no-op update, in cases when nothing changes, then the list must be in the same order, as the previous order.

### How could Crossplane help solve your problem?

We should declare ``status.conditions` as an associate list. The schema defined in CRDs should include the following snippet:

```yaml
properties:
  conditions:
  .
  .
    type: array
    x-kubernetes-list-map-keys:
    - type
    x-kubernetes-list-type: map
```

This change enables the following improvements:
* support for partial updates ([server-side apply](https://github.com/crossplane/crossplane/issues/4047)), lowering chances for conflicts
* owning of individual conditions
* reduced number of resource changes because no-op updates can be detected, leading to less reconciliations
