### ISSUE TITLE
Implement beta support for `RuntimeConfig`

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4699]
### What problem are you facing?

We marked `ControllerConfig` deprecated in v1.11 but we haven't yet implemented a replacement. We have a design for a replacement that was merged in https://github.com/crossplane/crossplane/pull/4322. The idea is that we'd implement a new type called `RuntimeConfig`. This would be a successor to `ControllerConfig` - it's pretty similar but a bit more flexible.

### How could Crossplane help solve your problem?

I think we should implement this and ship `RuntimeConfig` at `v1beta1`. It's essentially the beta iteration of `ControllerConfig` - we just changed the name because it will be used for Functions too, and a Function is not a (Kubernetes) controller.

**Comment by negz** [comment]
I suspect the hardest thing about building `RuntimeConfig` will be figuring out removal of the `ControllerConfig` type and the related migration [^1]. We could probably decouple these though - i.e. add support for `RuntimeConfig` (while still supporting `ControllerConfig`), then later figure out migration tooling and eventually removal.

[^1]: Normally we wouldn't build migration tooling for an alpha API, but `ControllerConfig` is a special case since it predates Crossplane feature flags, is on by default, and is thus very widely used.

**Comment by turkenh** [comment]
> I think we should implement this and ship RuntimeConfig at v1beta1. It's essentially the beta iteration of ControllerConfig - we just changed the name because it will be used for Functions too, and a Function is not a (Kubernetes) controller.

This contradicts what is proposed in the design: https://github.com/crossplane/crossplane/blob/master/design/one-pager-package-runtime-config.md#migration-from-controllerconfig

Basically, this would mean we skip the step 1 there and start with step 2:

> 2. When the feature is promoted to beta, DeploymentRuntimeConfig support will be on by default, with ControllerConfig support off by default. It will still be possible to specify --enable-runtime-config=false to force support for ControllerConfig.

Is this what we should plan for? My concern is potential confusion due to disabling support for ControllerConfig while we introduce its alternative (unless we automate this). I think, we can keep both on and use whichever is provided over API instead (error out if both are provided). The challenge is properly handling the defaulting (e.g. using default DeploymentRuntimeConfig if not provided) and what to do when both are provided etc.

**Comment by negz** [comment]
@turkenh I'm happy for us to ignore what I wrote in the design. My thinking has changed a little since then.

> I think, we can keep both on and use whichever is provided over API instead (error out if both are provided).

Yeah, agreed.

**Comment by turkenh** [comment]
During the implementation, I realized one caveat with the [proposed](https://github.com/crossplane/crossplane/blob/master/design/one-pager-package-runtime-config.md#proposal) defaulting mechanism, i.e. automatically setting a default runtime config. In the design, we propose to get a `DeploymentRuntimeConfig` named `default` created by the init container and used by all providers/functions unless user overrides it with another one, for the following benefits:

> - The default configuration is no longer [hardcoded](https://github.com/crossplane/crossplane/blob/v1.12.2/internal/controller/pkg/revision/deployment.go#L60) into the package manager.
> - Administrators can override the configuration all runtimes use by default.

The problem with this approach is, users wanting to make some unrelated configuration or just to override a single value would still need to provide all the values from the `default` `DeploymentRuntimeConfig`, otherwise they will lose the defaults. Even they do this once in the beginning, they won't get the improvements/updates on the default values at later versions. This causes a worse user experience than `ControllerConfig`s. As an example, imagine you want to configure IRSA for provider-aws. Today, it is [doable](https://github.com/upbound/provider-aws/blob/main/docs/family/Configuration.md#create-a-controllerconfig) with the following `ControllerConfig` today:

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: irsa-controllerconfig
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/eks-test-role
spec: {}
```

However, in the proposed solution, user would need to provide the following assuming they don't want to lose the defaults. Additionally, they would need to manually maintain the defaults here to get latest updates in Crossplane in case we make some improvements there.

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-controllerconfig
spec:
  deploymentTemplate:
    metadata:
      labels:
        example: label
    spec:
      replicas: 1
      template:
        metadata:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/eks-test-role  # <--
        securityContext:
          runAsNonRoot: true
          runAsUser: 2000
          runAsGroup: 2000
        containers:
        - name: package-runtime
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
            runAsGroup: 2000
            privileged: false
            allowPrivilegeEscalation: false
          ports:
          - name: metrics
            containerPort: 8080
    serviceTemplate:
      metadata: {}
    serviceAccountTemplate:
      metadata: {}
```
