### ISSUE TITLE
TrimPrefix and TrimSuffix transform not working in 1.13?

### ISSUE THREAD

**Issue by tspearconquest** [crossplane/crossplane#4722]
Hello, I have a composition applying the below patch set:

```
    - name: patch-status
      patches:
        - fromFieldPath: "status.atProvider.manifest.status.helmChart"
          toFieldPath: "status.app.helm.release.chart.ref.name"
          transforms:
            - type: string
              string:
                type: TrimPrefix
                trim: "[/]"
        - fromFieldPath: "status.atProvider.manifest.status.helmChart"
          toFieldPath: "status.app.helm.release.chart.ref.namespace"
          transforms:
            - type: string
              string:
                type: TrimSuffix
                trim: "[/]"
```

The resulting composite ends up with this in the status though:

```
status:
  app:
    helm:
      release:
        chart:
          ref:
            namespace: <appname>/<appname>-<appname>-<org>-<env>-<region>-01
```

No `name` field, and the namespace is not trimmed. Any ideas what I'm doing wrong?

### Repro scenario

A full repro scenario can be found in the following gist:
https://gist.github.com/jbw976/4d145d97c1de7f3fa57a7bca437bbe4b

**Comment by tspearconquest** [comment]
Not stale.

**Comment by tspearconquest** [comment]
Not stale

**Comment by jbw976** [comment]
Thanks @tspearconquest - a couple quick questions for some more data here:

* is this happening on Crossplane v1.15 also?
* have you tried this same scenario with with [functions](https://docs.crossplane.io/latest/concepts/composition-functions/) specifically https://github.com/crossplane-contrib/function-patch-and-transform? 
* the sample snippet in this issue is definitely helpful, would you by any chance have a full repro scenario available, to make it easier for someone to look more deeply into this scenario?

**Comment by tspearconquest** [comment]
Thanks, I'll have to get back to you on your first two questions, as we haven't upgraded or adopted the new features yet.

For the full repro, I'll work on this and share as soon as I can.

**Comment by Speeddymon** [comment]
```
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: helm-release-template
spec:
  compositeTypeRef:
    apiVersion: gitops.customapi.internal/v1alpha1
    kind: XHelmRelease
  patchSets:
    - name: patch-status
      patches:
        # Copy status.atProvider from the downstream resource to the Composite
        - fromFieldPath: "status.atProvider.manifest.status.helmChart"
        # Set custom status fields on the composite
        - fromFieldPath: "status.atProvider.manifest.status.helmChart"
          toFieldPath: "status.app.helm.release.chart.ref.name"
          transforms:
            - type: string
              string:
                type: TrimPrefix
                trim: "[/]"
        - fromFieldPath: "status.atProvider.manifest.status.helmChart"
          toFieldPath: "status.app.helm.release.chart.ref.namespace"
          transforms:
            - type: string
              string:
                type: TrimSuffix
                trim: "[/]"
  resources:
    - name: application-deployment
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: helm.toolkit.fluxcd.io/v2beta1
              kind: HelmRelease
              spec:
                install:
                  createNamespace: true
                interval: 1m0s
          providerConfigRef:
            name: kubernetes
```

The Composite's `status.atProvider` field gets populated with the downstream resource `atProvider` data properly, but the Composite's `status.app` field looks as shown in the OP. The expected `status.app` should look as below:

```
status:
  app:
    helm:
      release:
        chart:
          ref:
            name: <appname>-<appname>-<org>-<env>-<region>-01
            namespace: <appname>
```

The XRD is essentially a Flux HelmRelease wrapped in an Object resource from the Crossplane kubernetes provider, with some internally used fields that we use to automate populating some values in the downstream resource.

```
 ## Defines a helm release
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xhelmreleases.gitops.customapi.internal
spec:
  defaultCompositionRef:
    name: helm-release-template
  group: gitops.customapi.internal
  names:
    kind: XHelmRelease
    plural: xhelmreleases
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              app:
                description: >-
                  `app` contains machine-readable properties that will be used to give azure resources names.
                type: object
                properties:
                  customer:
                    description: Customer of the service. Minimum 3 characters, maximum 5 characters, only alphanumeric characters and the dash character are allowed.
                    type: string
                    minLength: 3
                    maxLength: 5
                    pattern: "^[a-zA-Z0-9-]+$"
                  instance:
                    description: >-
                      `instance` contains machine-readable properties that will be used to define the app's location and instance number
                    type: object
                    properties:
                      environment:
                        description: The name of the type of environment that a given resource belongs to. i.e. dev or prod
                        type: string
                        minLength: 3
                        pattern: "^[a-zA-Z0-9]+$"
                      helm:
                        description: >-
                          `helm` contains machine-readable properties that will be used to define a helm repo, chart, or release.
                        type: object
                        properties:
                          chart:
                            description: >-
                              `chart` contains machine-readable properties that will be used to define a helm chart from a git or helm repo.
                            type: object
                            properties:
                              path:
                                description: The path to the helm files within the referenced source. If referencing a HelmRepository source, then this should be the chart name.
                                type: string
                                minLength: 1
                              source:
                                default:
                                  ref:
                                    kind: "GitRepository"
                                description: >-
                                  `source` contains machine-readable properties that will be used to define the source of a helm chart as either a git or helm repo.
                                type: object
                                properties:
                                  reconcileInterval:
                                    description: The interval for reconciling the generated chart with the source repo. Must be specified in Go recognized duration string format, e.g. 1h, 10m, or 1h30m. Will not accept durations which include the seconds value; only hours and minutes are accepted.
                                    type: string
                                    minLength: 2
                                    maxLength: 7
                                    pattern: "^[0-9]+[hm]|[0-9]+h[0-9]+m$"
                                  ref:
                                    description: The source to reference as an (optional) apiVersion, (optional) kind, (required) name and an (optional) namespace.
                                    type: object
                                    properties:
                                      apiVersion:
                                        type: string
                                        maxLength: 63
                                        ## To be improved
                                        pattern: "[/]"
                                        ##
                                      kind:
                                        description: Defaults to GitRepository. Valid values are GitRepository and HelmRepository.
                                        enum:
                                          - GitRepository
                                          - HelmRepository
                                        type: string
                                        minLength: 13
                                        maxLength: 14
                                      name:
                                        description: The in-cluster flux resource name of the git or helm source for the chart being generated. If using this resource in a composition, this field MAY be left undefined because the name MAY be generated in the composition; and the status field of the composition MAY provide the generated name for cross-resource referencing. If this resource is being deployed in a standalone fashion, separately from a composition, then this field is required.
                                        type: string
                                        minLength: 1
                                        maxLength: 63
                                        pattern: "^[a-zA-Z0-9_-]$"
                                      namespace:
                                        type: string
                                        maxLength: 63
                                        pattern: "^[a-zA-Z0-9_-]$"
                                    required:
                                      - name
                                required:
                                  - ref
                              version:
                                description: Version string in a format accepted by a Flux HelmRelease resource.
                                type: string
                            required:
                              - path
                              - source
                              - version
                          release:
                            description: >-
                              `release` contains machine-readable properties that will be used to define a helm release.
                            type: object
                            properties:
                              chart:
                                description: >-
                                  `chart` contains machine-readable properties that will be used to define a helm chart for the release from a git or helm repo.
                                type: object
                                properties:
                                  createNamespace:
                                    description: A boolean value to determine whether to create a namespace for the app
                                    type: boolean
                                  path:
                                    description: The path to the helm files within the referenced source.
                                    type: string
                                  source:
                                    default:
                                      ref:
                                        kind: "GitRepository"
                                    description: >-
                                      `source` contains machine-readable properties that will be used to define the source of a helm chart as either a git or helm repo.
                                    type: object
                                    properties:
                                      reconcileInterval:
                                        description: The interval for reconciling the generated chart with the source repo.
                                        type: string
                                      ref:
                                        description: The source to reference as an (optional) apiVersion, (optional) kind, (required) name and an (optional) namespace.
                                        type: object
                                        properties:
                                          apiVersion:
                                            type: string
                                            maxLength: 63
                                            ## To be improved
                                            pattern: "[/]"
                                            ##
                                          kind:
                                            description: Defaults to GitRepository. Valid values are GitRepository and HelmRepository.
                                            enum:
                                              - GitRepository
                                              - HelmRepository
                                            type: string
                                            minLength: 13
                                            maxLength: 14
                                          name:
                                            description: The in-cluster flux resource name of the git or helm source for the chart being generated. If using this resource in a composition, this field MAY be left undefined because the name MAY be generated in the composition; and the status field of the composition MAY provide the generated name for cross-resource referencing. If this resource is being deployed in a standalone fashion, separately from a composition, then this field is required.
                                            type: string
                                            minLength: 1
                                            maxLength: 63
                                            pattern: "^[a-zA-Z0-9_-]$"
                                          namespace:
                                            type: string
                                            maxLength: 63
                                            pattern: "^[a-zA-Z0-9_-]$"
                                        required:
                                          - name
                                    required:
                                      - ref
                                  version:
                                    description: Version string in a format accepted by a Flux HelmRelease resource.
                                    type: string
                                required:
                                  - path
                                  - source
                                  - version
                              values:
                                description: >-
                                  `values` contains machine-readable properties that will be used to define parameters used in the deployment of the helm release.
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                            required:
                              - chart
                          repo:
                            description: >-
                              `repo` contains machine-readable properties that will be used to define a helm chart repo.
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                        required:
                          - release
                        x-kubernetes-preserve-unknown-fields: true
                      location:
                        description: The location where this app is hosted; usually a region or datacenter name
                        type: string
                      number:
                        description: The instance number
                        type: string
                      repo:
                        description: >-
                          `repo` contains machine-readable properties that will be used to connect your repo with your cluster
                        type: object
                        properties:
                          ignore:
                            description: >-
                              Ignore overrides the set of excluded patterns in the .sourceignore format
                              (which is the same as .gitignore). If not provided, a default will be used.
                            type: string
                          ref:
                            description: Reference specifies the Git reference to resolve and monitor for changes, defaults to the 'master' branch.
                            type: object
                            properties:
                              branch:
                                description: Branch to check out, defaults to 'master' if no other field is defined.
                                type: string
                              commit:
                                description: |-
                                  Commit SHA to check out, takes precedence over all reference fields.
                                   This can be combined with Branch to shallow clone the branch, in which the
                                  commit is expected to exist.
                                type: string
                              name:
                                description: |-
                                  Name of the reference to check out; takes precedence over Branch, Tag and
                                  SemVer.
                                   It must be a valid Git reference:
                                  https://git-scm.com/docs/git-check-ref-format#_description Examples:
                                  "refs/heads/main", "refs/tags/v0.1.0", "refs/pull/420/head",
                                  "refs/merge-requests/1/head"
                                type: string
                              semver:
                                description: SemVer tag expression to check out, takes precedence over Tag.
                                type: string
                              tag:
                                description: Tag to check out, takes precedence over Branch.
                                type: string
                            oneOf:
                              - required:
                                  - branch
                              - required:
                                  - commit
                              - required:
                                  - name
                              - required:
                                  - semver
                              - required:
                                  - tag
                          url:
                            description: URL specifies the Git repository URL, it can be an HTTP/S or SSH address.
                            type: string
                        required:
                          - url
                    required:
                      - environment
                      - helm
                      - location
                      - number
                  name:
                    description: Name of the application/team the Azure resource belongs to. Will be used in the resource name.
                    type: string
                required:
                  - customer
                  - instance
                  - name
              aws:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              azure:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            required:
              - app
          status:
            description: >
              A Status represents the observed states
            type: object
            properties:
              app:
                description: >
                  Freeform field containing information about needed app fields
                type: object
                x-kubernetes-preserve-unknown-fields: true
              atProvider:
                description: >
                  Freeform field containing information about the generated resource
                type: object
                x-kubernetes-preserve-unknown-fields: true
              aws:
                description: >
                  Freeform field containing information about needed aws fields
                type: object
                x-kubernetes-preserve-unknown-fields: true
              azure:
                description: >
                  Freeform field containing information about needed azure fields
                type: object
                x-kubernetes-preserve-unknown-fields: true
            x-kubernetes-preserve-unknown-fields: true
    served: true
    referenceable: true
  claimNames:
    kind: XHelmReleaseClaim
    plural: xhelmreleaseclaims
```
