### ISSUE TITLE
ToCompositeFieldPath doesn't export an output to the status section

### ISSUE THREAD

**Issue by nello1992** [crossplane/crossplane#4727]
### What happened?
I'm deploying an eks cluster using a Composition that includes all required resources, including those required to setup OIDC Provider. I create an IRSA and then I need to export its ARN (from status.atProvider.arn) because I need it as input to a Terraform Workspace resource. All these resources for testing purpose are all included in the same Composition.

The problem is that the status.atProvider.arn related to AWS Role resource doesn't get exported into the XR status section, consequently it produces an error while instantiating the Workspace resource. (elsewhere the status is updated correctly)

These are involved resources:

XRD

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: test.services.clusters.test.com
  namespace: crossplane-system
spec:
  group: services.clusters.test.com
  names:
    kind: XTest
    plural: xtests
  claimNames:
    kind: TestInstance
    plural: testinstances
  defaultCompositeDeletePolicy: Foreground
  defaultCompositionUpdatePolicy: Automatic
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:

            . . .
          
          status:
            type: object
            properties:
              awsConfig:
                type: object
                description: AWS specific configuration
                properties:
                  irsaRoleArn: 
                    type: string
                    description: ARN of the IRSA role
                    default: None

```

Composition
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test.services.clusters.test.com
  namespace: crossplane-system
  labels:
    crossplane.io/xrd: xtest.services.clusters.test.com
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: services.clusters.test.com/v1
    kind: XTest
  writeConnectionSecretsToNamespace: crossplane-system

  resources:
  - base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: Role
      spec:
        forProvider:
          description: "IRSA"
    patches:
     . . .
        strategy: string
        string: 
          fmt: |
            . . .
      toFieldPath: spec.forProvider.assumeRolePolicy 
    - fromFieldPath: spec.clusterInfo.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-irsa-role"
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.awsConfig.irsaRoleArn

  - base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: RolePolicyAttachment
      spec:
        forProvider:
          policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    patches:
    - fromFieldPath: spec.clusterInfo.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-ecr-ro-policy" 
    - fromFieldPath: spec.clusterInfo.id
      toFieldPath: spec.forProvider.roleRef.name
      transforms:
        - type: string
          string:
            fmt: "%s-irsa-role"

  . . .
  
  
  - base:
      apiVersion: tf.upbound.io/v1beta1
      kind: Workspace
      spec:
        forProvider:
          source: Inline
    patches: 
      ...
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: status.awsConfig.irsaRoleArn
          strategy: string
          string:
            fmt: |
              ...
        toFieldPath: spec.forProvider.module`
```

XR
```
...
Status:
  Conditions:
    Last Transition Time:  2023-10-04T13:25:00Z
    Message:               cannot compose resources: cannot apply composed resource: cannot create object: Workspace.tf.upbound.io "test" is invalid: spec.forProvider.module: Required value
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
```

### How can we reproduce it?
Create a generic resource like AWS Role that exports a field from its status up to its XR and use this value as input to a Workspace Resource using "combine" patch to define the "module" section. Both in the same Composition.

### What environment did it happen in?
Crossplane version:  1.14.0-rc.0.381.g89b5fe53

**Comment by phisco** [comment]
Did you try setting the policy to required for the CombineFromComposite patch on the Workspace?
```yaml
  - base:
      apiVersion: tf.upbound.io/v1beta1
      kind: Workspace
      spec:
        forProvider:
          source: Inline
    patches: 
      ...
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: status.awsConfig.irsaRoleArn
          strategy: string
          policy:
            fromFiledPath: Required
          string:
            fmt: |
              ...
        toFieldPath: spec.forProvider.module
```
