### ISSUE TITLE
Proposal: Operation Functions

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4729]
### What problem are you facing?

During the design of Composition Functions ([design doc](https://github.com/crossplane/crossplane/blob/579702198282bbbf6a98761c919875769dee61a4/design/design-doc-composition-functions.md)) we observed that the Function pipeline model could be a good way to model "day two operations". Things like upgrading and autoscaling resources.

We decided that the Composition logic probably wasn't the best place to encode day two operations. Mostly because we wanted to keep it focused on one responsibility - composing many (API) resources from one. I do think though that the Functions model, broadly, makes sense for day two operations. This is because day two operations is a very open ended problem space. Imagine for example code that can handle upgrading a database instance, when there might be 10+ different implementations of a database instance (RDS, CloudSQL, etc etc). I don't think we - the Crossplane maintainers - can build this logic for folks. Instead I think we could give folks a place to hook in such logic, and tools to make building the logic as simple as possible.

### How could Crossplane help solve your problem?

This is super vague, but I could imagine introducing a new variant of the Function package. Something like this:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-upgrade-rds-instance
spec:
  type: Operation # As opposed to "Composition"
  package: xpkg.upbound.io/crossplane-contrib/upgrade-rds-instance:v0.1.0
```

I imagine an "Operation Function" would be built, deployed, and run almost identically to a Composition Function. The `type` field would signify that it spoke a different gRPC API than a Composition Function.

The question then is what calls a pipeline of Operation Functions? Maybe you have something that looks very similar to a Composition:

```yaml
apiVersion: daytwo.crossplane.io/v1alpha1
kind: Operations
metadata:
  name: upgrade-my-database
spec:
  triggers:
  - type: Cron
    crontab: 5 4 * * *
  pipeline:
  - step: backup
    functionRef:
      name: function-backup-rds-instance
  - step: upgrade
    functionRef:
      name: function-upgrade-rds-instance
```

You could then associate "operations" with an XR (or MR?) by reference or label, similar to how you associate a Composition.

**Comment by blakeromano** [comment]
High level thoughts on this....

Composition Functions now that are apart of compositions allow you to update any resource like the MR/XR etc;... I see Crossplane Functions almost as an extension of a normal Kubernetes Operator in a certain way. You are examining current state and desired state and updating various things based on that. My thought would be that for example let's say I want to on a DB XR do a backup every hour. I can update status to have a `lastBackupTime` param and during reconciliation check that and if I am due for a snapshot, I can start a DB Snapshot with an ID, track the status of that snapshot in the status of the XR, and update `lastBackupTime` in the status of the XR when done.

This is the typical pattern that Kubernetes Operators follow and I am not super convinced that there is a strong need to have functions outside of the Composition. I think with maybe better documentation or standards (with SDKs and XRDs) that having data within the `status` of an XR that this is totally possible in Crossplane Functions now and really am not convinced that a new type of function is needed.

**Comment by negz** [comment]
@blakeromano I think there's two issues (at least) with that.

First, composition functions aren't always going to be an ideal 'trigger' for day two things. Imagine you want to make sure all RDS instances are backed up. Do you update every Composition that produces an RDS instance to do this? What if you were using third party Compositions (e.g. from https://marketplace.upbound.io)? I think it would it be more convenient to be able to configure a policy like "for every RDS instance, whatever XR (or lack thereof) created it, whenever it changes, run this function to make sure it's backed up".

Second, it overloads _composition_ functions to do things that are not composition. I think of composition as the process of composing an XR of other resources (e.g. MRs). I'm not sure day two operations on those resources will always/often be related to the act of composing. Apart from just being a philosophical/concept thing this could have practical issues. Consider composition not working because some nice-to-have day two thing is broken, or the potential increase in complexity of a `RunFunctionRequest` and `RunFunctionResponse` schema that begins to attempt to have all the inputs needed to handle both composition and whatever day two things we come up with.

**Comment by negz** [comment]
A manual trigger would also be interesting. So so far we have the following possible triggers:

* Cron schedule
* Manual
* XR/MR watch (created, updated, deleted)

I wonder if we should treat day two operations similar to a Kubernetes `Job`.

So imagine creating this manifest just ran the pipeline of functions one time:

```yaml
apiVersion: daytwo.crossplane.io/v1alpha1
kind: Operation
metadata:
  name: upgrade-my-database
spec:
  pipeline:
  - step: backup
    functionRef:
      name: function-backup-rds-instance
  - step: verify
    functionRef:
      name: function-verify-rds-instance-backup
```

Then you could have `CronOperation`, `WatchOperation` etc abstractions on top to 'trigger' the operation (pipeline) by creating an `Operation`.
