### ISSUE TITLE
Make the Composition environment "dumber" 😉 

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4738]
### What problem are you facing?

To restate the problem(s) we're solving with the Composition environment, I think:

* We want some way to persist temporary state ("variables") during the Composition process.
* With Functions, this means all Functions in a pipeline must share that persisted state.
* We want some way to "bootstrap" the initial state of the environment.

While stating the above I don't want to lose track of the [original goals](https://github.com/crossplane/crossplane/blob/579702198282bbbf6a98761c919875769dee61a4/design/one-pager-composition-environment.md#goals) of the EnvironmentConfig feature, which were to:

> 1. Allow the creation of generic compositions that render composed resources based on the environment they are executed in.
> 1. Allows users to define this environment in Crossplane native way.
> 1. Prevent escalation of privileges by disallowing users to read out fields from objects they shouldn't have access to.

As discussed at length in https://github.com/crossplane/crossplane/issues/4583, another part of the problem we're facing is how to do all of this without it being so complex that it's difficult or error prone to use.

### How could Crossplane help solve your problem?

Thanks to the conversations in https://github.com/crossplane/crossplane/pull/4632 I'm intrigued by the idea of modeling the Composition environment more closely on UNIX environment variables.

What would happen if we made the following simplifications:

* The `RunFunctionRequest` and `RunFunctionResponse` messages get a `map<string, bytes> environment = 5;` field.
* The `data` field of `EnvironmentConfig` becomes a `map[string][]byte`. [^1]
* We mirror the container's `env` and `envFrom` APIs and semantics in a Composition.

So a Composition might look like this:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: environmental
spec:
  mode: Pipeline
  env:
  - name: my-env-var
    value: "Hello from the environment"
  - name: my-special-var
    valueFrom:
      envConfigKeyRef:
        name: special-config
        key: specialvar
  envFrom:
  - envConfigRef:
      name: special-config
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input: {}  # Omitted for brevity.
```

I think there are some benefits to this approach:

* The API and merge semantics[^2] are familiar to anyone who has used env vars in Kubernetes.
* A flat map of keys to opaque values disincentivizes merging complex objects into the environment at arbitrary depths...
* ...which makes it easier to mentally model how the environment will be merged.
* There's no need for a schema, as proposed in https://github.com/crossplane/crossplane/issues/4275

There are downsides too:

* It's less friendly to structured data. If you want to store an object you'll need to serialize it to a string.
* I think this rules out https://github.com/crossplane/crossplane/issues/4583, or at least rules out injecting an entire resource as part of the environment.
* It could be confusing that these aren't literally set as environment variables inside the Function containers. [^3]
* The API doesn't have any way to match an EnvConfig via labels.
* The API doesn't have any way to derive which EnvConfig to match from XR fields.

[^1]: This would make `EnvironmentConfig` effectively a `ConfigMap`. If I recall correctly the initial motivation for `EnvironmentConfig` being its own type rather than a `ConfigMap` was just for RBAC purposes, so that Crossplane wouldn't need RBAC access to read arbitrary `ConfigMaps`. I could be convinced we should just use `ConfigMaps` - the RBAC ship has mostly already sailed with `Secrets`.
[^2]: Keys in `env` trump keys from `envFrom`. Otherwise, last seen key wins.
[^3]: Maybe this is an argument for using a different name than "environment" - e.g. "context"?
