### ISSUE TITLE
Allow a Function to request "extra" observed resources

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#4739]
### What problem are you facing?

Sometimes when "doing Composition" you need to load data from a resource that isn't the claim, XR, or a composed resource. Examples include:

* Deriving a composed resource field from a property of some unrelated resource - for example setting the `spec.forProvider.vpcID` field of a composed resource to the ARN of an AWS VPC MR that isn't part of the XR.
* Loading `EnvironmentConfig` resources, to setup the Composition environment, per https://github.com/crossplane/crossplane/pull/4632#discussion_r1346177527.

We've sketched out some potential ways to extend the `Composition` type to include the ability to express a set of extra resources that the Composition needs (e.g. in https://github.com/crossplane/crossplane/issues/4583), but the APIs for doing so get convoluted pretty quickly. This is largely because we want to support:

* Arbitrary types of resources.
* Referencing and/or selecting resources.
* Deriving what exactly to select or reference from fields of the XR.

With https://github.com/crossplane/crossplane/pull/4632#discussion_r1346177527 we started discussing more seriously whether a Function should be able (or encouraged) to communicate directly with the API server in order to load extra resources. We're reluctant to do this because it provides a "backdoor" through which Functions can load and mutate Kubernetes resources without Crossplane knowing about it. Crossplane controlling all the inputs to, and being able to track all the outputs from a Function enables powerful tools like `xrender`, per https://github.com/crossplane/crossplane/issues/4723.

### How could Crossplane help solve your problem?

An interesting middle ground would be to allow a Function to ask Crossplane to provide it with extra observed resources. Observed resources that the Function doesn't _compose_ - that aren't children of the XR - but are useful to the Function pipeline for some reason. This would allow Functions to load extra resources in a fashion that was still tracked/brokered by Crossplane.

You could imagine an API like this:

```protobuf
message RunFunctionResponse {
  // Existing fields omitted for brevity.

  // Extra resources that should be supplied to all subsequent Functions in
  // the pipeline. The map key uniquely identifies the group of resources.
  map<string, ResourceSelector> extra_resources = 42;
}

message ResourceSelector {
  string api_version = 1;
  string kind = 2;
  map<string, string> match_labels = 3; // Optional. Matches all resources if omitted.
}

// We probably need distinct DesiredState and ObservedState messages,
// since Functions can't return desired state for extra resources.
message ObservedState {
  Resource composite = 1;

  // The 'resources' field becomes 'composed' to more clearly
  // distinguish it from 'extra' resources.
  map<string, Resource> composed = 2;

  // Note that extra resources is a map to Resources, plural.
  // The map key corresponds to the key in a RunFunctionResponse's
  // extra_resources field.
  map<string, Resources> extra = 3;
}

// Resources just exists because you can't have map<string, repeated Resource>.
message Resources {
  repeated Resource resources = 1;
}
```

Whenever a Function returned a `RunFunctionResponse` with `extra_resources`, Crossplane would list those resources and pass them in to any subsequent Functions in the pipeline as the `extra` field of their `ObservedState`.

I think this would allow us to move selecting and merging `EnvironmentConfig` resources entirely into the Composition Function pipeline. For example[^1]:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: extra
spec:
  mode: Pipeline
  pipeline:
  # This helper Function just sets extra_resources in its output.
  - step: get-env-configs
    functionRef:
      name: function-select-extra-resources
    input:
      apiVersion: extra.fn.crossplane.io/v1beta1
      kind: ExtraResourceSelectors
      selectors:
      - key: env-configs
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: EnvironmentConfig
        matchLabels:
          region: au-west
  # This helper Function sets explicit (or "default") env vars.
  # It can also load env vars from an extra resources key, which
  # must contain zero or more EnvironmentConfig resources.
  - step: set-default-environment-vars
    functionRef:
      name: function-set-environment
    input:
      apiVersion: environment.fn.crossplane.io/v1beta1
      kind: Variables
      variables:
      - name: some-var
        value: some-value
      variablesFromEnvConfigs:
        extraResourcesKey: env-configs
```

I believe this would be compatible with `xrender`. You'd need to pass it in any "extra" resources similarly to how you pass in observed resources today using the `--observed-resources` flag. So something like:

```shell
$ xrender xr.yaml composition.yaml functions.yaml --extra-resources=env-configs=envconfigs.yaml
```

Note the `key=filename.yaml` style.

[^1]: This example assumes a "flat" environment as proposed in https://github.com/crossplane/crossplane/issues/4738, but I think it would work if the environment continued to be a complex JSON object.

**Comment by negz** [comment]
Some miscellaneous notes:

* I intentionally omitted references, hoping selectors would be enough, as a simplification. Is it reasonable to expect that if you wanted to reference a specific thing by name, perhaps you could add a unique label to it and select on that?

* I think this design satisfies the property of being able to derive a selector from some field of the XR, since a Function could use the observed XR to build the `extra_resources` selectors it returns.

* RBAC is a concern with this design. Crossplane has pretty broad access, and this allows a Composition Function to ask to be provided anything Crossplane can read. I'm not sure this is much worse than the current state though, where a Composition Function (or even native P&T) could ask Crossplane to compose an observe-only resource in order to read it.

**Comment by phisco** [comment]
This feels like a function focused variation of the various proposals in #4583. Outputting raw resources instead of a predigested environment was considered and discarded as the abstraction of a simpler environment was considered more desirable.

Feels like this should converge into the conversation in #4583, trying to answer the question "how do we pass arbitrary resources to the composition machinery?" instead of just "how do we pass arbitrary resources to the functions pipeline?"

> RBAC is a concern with this design. Crossplane has pretty broad access, and this allows a Composition Function to ask to be provided anything Crossplane can read. I'm not sure this is much worse than the current state though, where a Composition Function (or even native P&T) could ask Crossplane to compose an observe-only resource in order to read it.

The RBAC issue has been solved for Providers and could be leveraged by Functions without much effort, as @turkenh was mentioning [here](https://github.com/crossplane/crossplane/pull/4632#discussion_r1347331332).

**Comment by negz** [comment]
> This feels like a function focused variation of the various proposals in https://github.com/crossplane/crossplane/issues/4583.

It is. I intentionally wanted to decouple this from that quite long issue, and in particular from the idea of using the environment as a way to inject extra observed resources.

> Feels like this should converge into the conversation in https://github.com/crossplane/crossplane/issues/4583, trying to answer the question "how do we pass arbitrary resources to the composition machinery?" instead of just "how do we pass arbitrary resources to the functions pipeline?

These questions are one and the same. I feel very strongly that the future of Composition is the Functions pipeline. I don't think we should be constrained by trying to support adding new functionality to native P&T.

> The RBAC issue has been solved for Providers and could be leveraged by Functions without much effort

I'm talking about a different RBAC concern here. What @turkenh mentioned covers the fact that a Function (or Provider) package could ask for RBAC access to talk to the API server directly. The RBAC concern I'm highlighting here is that under _this_ design Functions would not talk to the API server directly, but rather defer that to Crossplane. Thus they effectively get Crossplane's broad access.

**Comment by phisco** [comment]
> I'm talking about a different RBAC concern here. What @turkenh mentioned covers the fact that a Function (or Provider) package could ask for RBAC access to talk to the API server directly. The RBAC concern I'm highlighting here is that under this design Functions would not talk to the API server directly, but rather defer that to Crossplane. Thus they effectively get Crossplane's broad access.

Indeed, I precisely meant it wouldn't be a problem if we were to allow functions to directly interact with the API server instead of relying on the wide permissions of Crossplane itself, as we already do for providers.

**Comment by negz** [comment]
> I precisely meant it wouldn't be a problem if we were to allow functions to directly interact with the API server instead of relying on the wide permissions of Crossplane itself, as we already do for providers.

Right now I feel strongly that we must not rely on allowing Functions to talk directly with the API server. It breaks a very useful contract we have today (as described in https://github.com/crossplane/crossplane/issues/4723). Breaking that contract would affect our ability to build tooling like `xrender`, and limits potential tenancy options for Functions as well.

I agree with the assertion you've made elsewhere that trying to _stop_ people from writing Functions that talk to the API server is probably a losing game, but I don't think that means we should lean into it. So, I think we need a solution for loading "extra" resources that we _would_ bless/support.

**Comment by gotwarlost** [comment]
I came here looking exactly for this :) I'm trying to port a P&T style composition to a function composition and the first thing that the P&T composition does is to patch from an arbitrary related resource. Is my understanding correct that as things stand - given that functions and P&T are mutually exclusive - that it is impossible to get this functionality if using a function composition?

**Comment by negz** [comment]
Some prior art: it looks like the "customize hook" in Metacontroller works pretty much exactly like what I've described here. https://metacontroller.github.io/metacontroller/api/customize.html#customize-hook

**Comment by negz** [comment]
Adding v1.15 - I don't think we'll figure this out in time for v1.14.

**Comment by negz** [comment]
I've put this into "must haves" for functions to GA, but only because it _might_ require breaking API changes. If it doesn't require breaking API changes, I think it can slip and happen after GA.

**Comment by phisco** [comment]
This grew on me and I think it's the way to go 👍

**Comment by phisco** [comment]
A good point from @sttts, it could be worth adding an allow list to Compositions to control what Functions can request, e.g. the example above would be:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: extra
spec:
  mode: Pipeline
  allowedRequests:
    selectors:
    - key: env-configs
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: EnvironmentConfig
        # could be left empty to allow any match or further specified to mirror the one below
        # matchLabels: {}
  pipeline:
  # This helper Function just sets extra_resources in its output.
  - step: get-env-configs
    functionRef:
      name: function-select-extra-resources
    input:
      apiVersion: extra.fn.crossplane.io/v1beta1
      kind: ExtraResourceSelectors
      selectors:
      - key: env-configs
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: EnvironmentConfig
        matchLabels:
          region: au-west
  # This helper Function sets explicit (or "default") env vars.
  # It can also load env vars from an extra resources key, which
  # must contain zero or more EnvironmentConfig resources.
  - step: set-default-environment-vars
    functionRef:
      name: function-set-environment
    input:
      apiVersion: environment.fn.crossplane.io/v1beta1
      kind: Variables
      variables:
      - name: some-var
        value: some-value
      variablesFromEnvConfigs:
        extraResourcesKey: env-configs
```

**Comment by sttts** [comment]
The important bit here would be the inversion of control. This `allowedRequests` list defines a range of objects that the function can request. A request of a function would go through a GRPC interface, like a client if you want, that we pass to the function code as a stub. The function is free to request any object through it. The compositor would check that the request is within the range defined in `allowedRequests`.

**Comment by sttts** [comment]
I would like have moved the `allowedRequests` into the `steps` aka the invocation of the function.

**Comment by sttts** [comment]
Also to make this approach compatible with realtime compositions, I would add a new section to the response called `watches`. A function could return that list to define when it is triggered again for recomputation of a composite:
```yaml
watches:
- group:
  version:
  kind:
  labelSelector: # optional
  name: # optional
```
Maybe these watches must be within the `allowedRequests` to be accepted.
