### ISSUE TITLE
`crossplane xpkg build` with malformed examples fails with ineffective error message

### ISSUE THREAD

**Issue by maximilianbraun** [crossplane/crossplane#4776]
Hey! First of all thanks for the efforts put into developer experience, its great to see those developments, highly appreciated.

### What happened?

I yesterday played around with the current `xpkg build` from master it in a provider which is currently distributed in the classic 2-images way. What I noticed is that the error messages of the yaml parser (in the case where an example is malformed) are not particularly helpful [1]. In case it fails to parse a document you don't get any hint which of the files / docs are the problem. I haven't found an issue in `up`.  

I would like to see a hint in which file the erroneous document is to find.

[1]: 
```
crossplane: error: xpkg.buildCmd.Run(): failed to build package: failed to parse examples: error converting YAML to JSON: yaml: line 1: did not find expected node content
```

### How can we reproduce it?
Run `crossplane xpkg build` with a malformed yaml, e.g. add a document like this somewhere into the examples.

```yaml
---
# foo bar
# bar baz
---
```

### What environment did it happen in?
Crossplane version: 
master@a6c639ed33a7ca7f57eed0d8d227cf32cc605479.

**Comment by cychiang** [comment]
Hi @maximilianbraun, 

I spent some time to dig into this issue, and I found that it's a bit tricky. Somehow it also related to how [fsreader](https://github.com/crossplane/crossplane-runtime/blob/main/pkg/parser/fsreader.go#L118) been implemented.

Consider we have a folder with following files:
- `malformed.yaml`
- `provider.yaml`
- `composition.yaml`

Assume `provider.yaml` and `composition.yaml` are correct yaml format but not `malformed.yaml`

Take this as an example for `malformed.yaml`
```yaml
---
# foo bar
# bar baz
---
```

It failed as you mentioned in the description. However, when I try to look into a file then it will show you a wrong file because of the [writeBreak](https://github.com/crossplane/crossplane-runtime/blob/main/pkg/parser/fsreader.go#L130)

It seems that the `fsreader` is trying to parser a composed yaml file which has many yaml resources in it. So, it will try to add a `...` when it's end of the file. But in the other hand, somehow this `...` been pass into next file when a reader trying to read the next file. 

If you remove `---` in the `malformed.yaml` then it won't show the error, and it also work if you put a validate yaml block after it. Like this:
```
---
# foo bar
# bar baz
---
apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: MSSQLConnectionSecret
    connectionSecretRef:
      namespace: default
      name: db-conn
```

But it failed when add an extra `---` at the end of the file like: 
```
---
# foo bar
# bar baz
---
apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: MSSQLConnectionSecret
    connectionSecretRef:
      namespace: default
      name: db-conn
---
```
I guess, the root cause of it is between the `fsreader` from crossplane-runtime and `yamlreader` from yaml decoder. 

Back to the topic, [here](https://github.com/crossplane/crossplane/compare/main...cychiang:crossplane:feat-add-file-path-when-failed-to-parse-k8s-yaml#diff-10062ee39052526698e730181153b899f4177474c90393d35ebcee2c418904b3R73) is the change I did to show the file info when failed to parse a yaml block into k8syaml, but at the moment, it pointed to the wrong file, because `...` been pass to the next file as a starting point.
