### ISSUE TITLE
support for templated resources in composition

### ISSUE THREAD

**Issue by raffaelespazzoli** [crossplane/crossplane#4779]
### What problem are you facing?

I'd like more flexibility when "composing" a Composition, by have the power of go templates at my disposal, pretty much as one has when creating a helm chart.
Simple filed substitutions from the Composite and support for loops are the major lacking feature that are preventing wide adoption of Crossplane at my organization.

### How could Crossplane help solve your problem?

Let's make an example, let's say that in AWS I want to create one subnet per AZ starting from this composite

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xrosas.crossplane.redhat-cop.com
spec:
  group: crossplane.redhat-cop.com
  defaultCompositeDeletePolicy: Foreground
  defaultCompositionUpdatePolicy: Automatic
  names:
    kind: xRosa
    plural: xrosas
  claimNames:
    kind: Rosa
    plural: rosas    
  versions:
  - name: v1alpha1
    served: true
    referenceable: true  
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                description: "AWS region"
                type: string
              availabilityZones:
                 type: arrays
                 items: 
                   type: string                    
            required: 
              - region
          status:
            description: A Status represents the observed state
            properties:
              subnets:
                description: Freeform field containing status information for the subnets
                type: object
                x-kubernetes-preserve-unknown-fields: true
```
the composition could look like this:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mycomp
spec:
  compositeTypeRef:
    apiVersion: crossplane.redhat-cop.com/v1alpha1
    kind: xMycomp
  resources:
  {{ $composite:= . }}
  {{ range .spec.availabilityZones }}
  - name: public-subnet-{{ . }}
    base: 
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: public-{{ . }}
      spec:
        forProvider:
          region: {{ $composite.region }}
          tags:
            Name: replace          
          vpcIdSelector:
            matchControllerRef: true
          availabilityZone: {{ . }}
```
so the root of the parameters merged with the template in this example if the Composite, or like in Helm one could model the values (the Composite in this case) and some pieces of context to be passed to the template.

**Comment by ezgidemirel** [comment]
Hello @raffaelespazzoli, thanks for opening this issue and sharing your use case. We're currently working on a go-template composition function that will support the mentioned functionalities above. The initial version of this function will be available around the v1.14 release. We're planning to open a one-pager to discuss the design details like how we can provide templates as inputs, how we can access values, and how we can construct connection details. I'll link the one-pager PR in this issue once it's available.

**Comment by ezgidemirel** [comment]
The composition file will be similar to below:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mycomp
spec:
  compositeTypeRef:
    apiVersion: crossplane.redhat-cop.com/v1alpha1
    kind: xMycomp
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-template-go
      input:
        apiVersion: gotemplate.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline  # Or Remote, if you want to pull templates from git.
        inline: |
          {{- range $i, $e := .observed.composite.resource.spec.availabilityZones }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata:
            name: public-{{ $e }}
          spec:
            forProvider:
              region: {{ $.observed.composite.resource.spec.region }}
              tags:
                Name: replace
              vpcIdSelector:
                matchControllerRef: true
              availabilityZone: {{ $e }}
          {{- end }}

```
And the composed resources will be like: 
```
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/composition-resource-name: public-eu-central-1a
  generateName: test-
  labels:
    crossplane.io/composite: test
  name: public-eu-central-1a
  ownerReferences:
  - apiVersion: crossplane.redhat-cop.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rosa
    name: test
    uid: ""
spec:
  forProvider:
    availabilityZone: eu-central-1a
    region: eu-central-1
    tags:
      Name: replace
    vpcIdSelector:
      matchControllerRef: true
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/composition-resource-name: public-eu-central-1b
  generateName: test-
  labels:
    crossplane.io/composite: test
  name: public-eu-central-1b
  ownerReferences:
  - apiVersion: crossplane.redhat-cop.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rosa
    name: test
    uid: ""
spec:
  forProvider:
    availabilityZone: eu-central-1b
    region: eu-central-1
    tags:
      Name: replace
    vpcIdSelector:
      matchControllerRef: true
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/composition-resource-name: public-eu-central-1c
  generateName: test-
  labels:
    crossplane.io/composite: test
  name: public-eu-central-1c
  ownerReferences:
  - apiVersion: crossplane.redhat-cop.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rosa
    name: test
    uid: ""
spec:
  forProvider:
    availabilityZone: eu-central-1c
    region: eu-central-1
    tags:
      Name: replace
    vpcIdSelector:
      matchControllerRef: true

```
