### ISSUE TITLE
CombineFromComposite loop support

### ISSUE THREAD

**Issue by clayrisser** [crossplane/crossplane#4800]
### What problem are you facing?
I am trying to template an AWS policy using `CombineFromComposite` and need the ability to loop 

```yaml
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.assumeRolePolicy
          combine:
            variables:
            - fromFieldPath: status.awsAccountID
            - fromFieldPath: status.eksOIDC
            - fromFieldPath: status.eksOIDC
            - fromFieldPath: status.eksOIDC
            - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            - fromFieldPath: spec.serviceAccountName
            - fromFieldPath: spec.delegateNamespaces
            strategy: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::%s:oidc-provider/%s"
                      },
                      "Action": "sts:AssumeRoleWithWebIdentity",
                      "Condition": {
                        "StringEquals": {
                          "%s:aud": "{{ .Values.audience }}",
                          "%s:sub": "system:serviceaccount:%s:%s"
                        }
                      }
                    }
                    ...ADD MORE STATEMENTS HERE FROM spec.delegateNamespaces USING  A LOOP
                  ]
                }
```

### How could Crossplane help solve your problem?
Crossplane could add the ability to template a string value with loop and conditional logic support.
