### ISSUE TITLE
DeploymentRuntimeConfig `deploymentTemplate.spec.template.spec.serviceAccountName` is ignored

### ISSUE THREAD

**Issue by mproffitt** [crossplane/crossplane#4908]
### What happened?

When creating a DeploymentRuntimeConfig, the field `deploymentTemplate.spec.template.spec.serviceAccountName` is ignored by the controller in favour of the `serviceAccountTemplate` field.

If the `serviceAccountTemplate` is not set, or empty, the expected behaviour should be that `deploymentTemplate.spec.template.spec.serviceAccountName` is applied. However the behaviour appears to be that this field is ignored in all instances and a new, dynamic service account is created to be used by the runtime.

Where both `serviceAccountTemplate` and `deploymentTemplate.spec.template.spec.serviceAccountName` are given, my opinion would be that `deploymentTemplate.spec.template.spec.serviceAccountName` takes precedence as this is explicitly stating that "I want this account to be used with this deployment" however again in this instance `serviceAccountTemplate` takes precedence here.

If the name given to `serviceAccountTemplate` is the name of a service account that exists in the cluster, crossplane adopts this service account and applies it to the `Deployment`, creating the relevant `ClusterRoleBindings` for it.

Whilst I don't have a strong opinion on how this is resolved, the unused existence of `deploymentTemplate.spec.template.spec.serviceAccountName` leads to a level of confusion when the referenced service account is not adopted by the deployment and instead a new account is created.

Towards this I see at least 3 options

1. Always use `deploymentTemplate.spec.template.spec.serviceAccountName` if it is provided and fail the apply if the SA doesn't exist
2. Use `deploymentTemplate.spec.template.spec.serviceAccountName` irrespective of `serviceAccountTemplate` if it coheres to a valid service account in the `crossplane` install namespace. This implies ignoring `serviceAccountTemplate` if `deploymentTemplate...serviceAccountName` is set
3. Deprecate `deploymentTemplate.spec.template.spec.serviceAccountName` in favour of `serviceAccountTemplate` and make it clear through documentation that setting this field has no effect

Associated slack thread: https://crossplane.slack.com/archives/CEG3T90A1/p1698071278410109

### How can we reproduce it?

Apply the following resources:

```yaml
---
# Create the service account to be used for AWS providers
apiVersion: v1
kind: ServiceAccount
metadata:
  name: upbound-provider-aws
  namespace: crossplane

---
# DeploymentRuntimeConfig for AWS resources
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-family
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: upbound-provider-aws
          containers:
            - name: package-runtime
              args:
                - --debug
                - --enable-management-policies
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-aws
  namespace: crossplane
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v0.42.0
  runtimeConfigRef:
    name: aws-family
```

Check the SAs
```bash
$ k get sa -n crossplane
NAME                                       SECRETS   AGE
crossplane                                 0         5m2s
default                                    0         5m2s
rbac-manager                               0         5m2s
upbound-provider-aws                       0         4m43s
upbound-provider-family-aws-ab7dbb587523   0         4m35s
```

This last SA: `upbound-provider-family-aws-ab7dbb587523` should not exist.

Check the deployment:

```bash
$ k get deploy upbound-provider-family-aws-ab7dbb587523 -o yaml | yq '.spec.template.spec.serviceAccount*'
upbound-provider-family-aws-ab7dbb587523
upbound-provider-family-aws-ab7dbb587523
```

I would expect these to both read `upbound-provider-aws`

### What environment did it happen in?
Cluster type: `kind v0.20.0 go1.21.1 linux/amd64`
Crossplane version: `crossplane:v1.15.0-rc.0.3.g35b34e85`

```nohighlight
$ helm install crossplane --namespace crossplane --create-namespace crossplane-master/crossplane --devel

NAME: crossplane
LAST DEPLOYED: Thu Oct 26 18:01:12 2023
NAMESPACE: crossplane
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Release: crossplane

Chart Name: crossplane
Chart Description: Crossplane is an open source Kubernetes add-on that enables platform teams to assemble infrastructure from multiple vendors, and expose higher level self-service APIs for application teams to consume.
Chart Version: 1.15.0-rc.0.3.g35b34e85
Chart Application Version: 1.15.0-rc.0.3.g35b34e85

Kube Version: v1.27.3
```
