### ISSUE TITLE
Can not sync status from managed resource to xr or claim when it in delete.

### ISSUE THREAD

**Issue by wuyexixi** [crossplane/crossplane#4948]
### What happened?
I use the ToCompositeFieldPath to sync status from the managed resource (k8s provider object) to claim, it is working fine in creation, but nothing sync in deletion, since k8s provider object has synced all external resource status to its status.atProvider.manifest.status as shown in below:

Object status:
```yaml
    status:
          conditions:
          - lastTransitionTime: "2023-11-02T07:50:23Z"
            message: Finalizer added
            reason: "NO"
            status: "True"
            type: Create
          - lastTransitionTime: "2023-11-02T07:51:24Z"
            message: Sub resource 1 about to delete.
            reason: "NO"
            status: "True"
            type: Delete
          - lastTransitionTime: "2023-11-02T07:51:34Z"
            message: Sub resource 2 about to delete.
            reason: "NO"
            status: "True"
            type: Delete
          - lastTransitionTime: "2023-11-02T07:51:44Z"
            message: Sub resource 3 about to delete.
            reason: "NO"
            status: "True"
            type: Delete
          size: 0
    conditions:
    - lastTransitionTime: "2023-11-02T07:53:41Z"
      reason: Deleting
      status: "False"
      type: Ready
    - lastTransitionTime: "2023-11-02T07:50:23Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
```

XR status
```yaml
status:
    conditions:
    - lastTransitionTime: "2023-11-02T07:50:23Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2023-11-02T07:51:24Z"
      reason: Deleting
      status: "False"
      type: Ready
    managedResource:
      status:
        conditions:
        - lastTransitionTime: "2023-11-02T07:50:23Z"
          message: Finalizer added
          reason: "NO"
          status: "True"
          type: Create
```
Claim status
```yaml
status:
    conditions:
    - lastTransitionTime: "2023-11-02T07:50:24Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2023-11-02T07:50:24Z"
      reason: Available
      status: "True"
      type: Ready
    managedResource:
      status:
        conditions:
        - lastTransitionTime: "2023-11-02T07:50:23Z"
          message: Finalizer added
          reason: "NO"
          status: "True"
          type: Create
```

### How can we reproduce it?
Composition
```yaml
patches
- type: ToCompositeFieldPath
        fromFieldPath: "status.atProvider.manifest.status"
        toFieldPath: "status.managedResource.status"
```

### What environment did it happen in?
Crossplane version:  1.12.1
