### ISSUE TITLE
Claim optional parameter without default value still present in composite after removal from claim instance

### ISSUE THREAD

**Issue by mleahu** [crossplane/crossplane#4982]
### What happened?
When an optional parameter without default value is removed from the claim and the claim is applied again, that optional parameter is still present in the composite. The expectation is that the optional parameter is removed from composite when it is removed from the claim.

### How can we reproduce it?
Apply the definition and composition below in the cluster. Provider kubernetes is used to create config maps in the cluster.
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdishinstances.tde.abcd.com
spec:
  group: tde.abcd.com
  names:
    kind: XDishInstance
    plural: xdishinstances
  claimNames:
    kind: DishInstance
    plural: dishinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dishParameters:
                  type: object
                  properties:
                    requiredStyle:
                      type: string
                    optionalSize:
                      type: string
                      enum: [claim_small, default_size_in_definition, claim_big]
                  required:
                    - requiredStyle
              required:
                - dishParameters
``` 
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdishinstances.xr.tde.abcd.com
  labels:
    crossplane.io/xrd: xdishinstances.tde.abcd.com
spec:
  compositeTypeRef:
    apiVersion: tde.abcd.com/v1alpha1
    kind: XDishInstance
  resources:
    - name: config-map
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                namespace: default
              data:
                style: default_style_in_composition
                size: default_size_in_composition
          providerConfigRef:
            name: providerconfig-k8s
      patches:
        - fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-dish"
        - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: metadata.namespace

        - fromFieldPath: spec.dishParameters.requiredStyle
          toFieldPath: spec.forProvider.manifest.data[style]
        - fromFieldPath: spec.dishParameters.optionalSize
          toFieldPath: spec.forProvider.manifest.data[size]
```

Apply the following claim 3 times by uncommenting each time the section in the comments where CLAIM PARAMETERS BEGIN/END is mentioned.
```yaml
apiVersion: tde.abcd.com/v1alpha1
kind: DishInstance
metadata:
  name: mydish
spec:

  # TESTED WITH CROSSPLANE 1.12.1 and 1.14.0

  # 1. Claim a dish with only the requiredStyle set in the claim
  # ----- CLAIM PARAMETERS BEGIN --------------
  # dishParameters:
  #   requiredStyle: french_style_from_claim
  # ----- CLAIM PARAMETERS END --------------
  #
  #  Claim parameters in main composite
  # $ k get xdishinstances.tde.abcd.com -o=jsonpath="{.items[*].spec.dishParameters}"
  # {"requiredStyle":"french_style_from_claim"}
  #
  # Check the config map values:
  # $ k get cm mydish-dish -o=jsonpath="{.data}" | jq .
  # {
  #   "size": "default_size_in_composition",
  #   "style": "french_style_from_claim"
  # }
  #
  # 2. Update the claim with a value for the optional parameter too
  # ----- CLAIM PARAMETERS BEGIN --------------
  # dishParameters:
  #   requiredStyle: french_style_from_claim
  #   optionalSize: claim_small
  # ----- CLAIM PARAMETERS END --------------
  #
  #  Claim parameters in main composite
  # $ k get xdishinstances.tde.abcd.com -o=jsonpath="{.items[*].spec.dishParameters}" | jq .
  # {
  #   "optionalSize": "claim_small",
  #   "requiredStyle": "french_style_from_claim"
  # }
  #
  # Check the config map values:
  # $ k get cm mydish-dish -o=jsonpath="{.data}" | jq .
  # {
  #   "size": "claim_small",
  #   "style": "french_style_from_claim"
  # }

  # 3. REMOVE the optional parameter from the claim
  # ----- CLAIM PARAMETERS BEGIN --------------
  # dishParameters:
  #   requiredStyle: french_style_from_claim
  # ----- CLAIM PARAMETERS END --------------
  #
  # Claim parameters in main composite
  # !!! EXPECTATION IS THAT ONLY PARAMETERS FROM CLAIM ARE PRESENT, SO optionalSize SHOULD NOT BE PRESENT !!!
  # $ k get xdishinstances.tde.abcd.com -o=jsonpath="{.items[*].spec.dishParameters}" | jq .
  # {
  #   "optionalSize": "claim_small",
  #   "requiredStyle": "french_style_from_claim"
  # }
  #
  # Check the config map values:
  # !!! EXPECTATION IS THAT size PARAMETER IN CONFIG MAP HAS THE DEFAULT VALUE FROM COMPOSITION default_size_in_composition !!!
  #  $ k get cm mydish-dish -o=jsonpath="{.data}" | jq .
  # {
  #   "size": "claim_small",
  #   "style": "french_style_from_claim"
  # }
```
Observe step 3 where the removal of the parameter from the claim is not reflected in the composite and config map contents.

### What environment did it happen in?
Crossplane version: 1.12.1, 1.14.0

* Cloud provider: AWS
* Kubernetes version:
```
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.15-eks-4f4795d
```
* Kubernetes distribution: EKS 
* OS: Ubuntu 22.04.3 LTS
* Kernel: `Linux 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
