### ISSUE TITLE
Define standards for function authors to publish details of expected XR patches

### ISSUE THREAD

**Issue by mproffitt** [crossplane/crossplane#4983]
### What problem are you facing?

As an outcome of https://github.com/crossplane/crossplane/issues/4968, it was highlighted that there is a potential gap in how crossplane is able to handle XR patches when being patched from inside a composition function other than `crossplane-contrib/function-patch-and-transform`

At present, there is no standard defined mechanism for function authors to publish how their function expects to modify the XR, in a way that can be consumed by authors of XRD specifications which can lead to incompatibilities between function behaviour and XRD expectations.

In worst case scenarios, this impacts crossplanes capability of maintaining a `Ready` state on the XR due to an executed race condition between the reconcilers from the claim controller and the composite controller.

To better describe this, consider the XRD examples given in the original issue in that the XRD expected:

```yaml
  subnets:
    type: array
    items:
      type: object
      additionalProperties: true
```

whilst the function output matched the spec of (simplified):

```yaml
  subnets:
    type: array
    items:
      type: object
      additionalProperties: true
      properties:
        id:
          description: The ID for this subnet
          type: string
        tags:
          type: object
          additionalProperties:
            type: string
      required:
      - id
```

Here, the function is outputting additional nested objects that cannot be applied correctly due to the existence of the undefined child object `tags`. This leads to data-loss in the XR when the claim is re-applied by the claim controller reconciler as it does not understand the existence of the `tags` field according to the XRD specification.

As the creation, publication and use of composition functions grows, this problem is liable to grow with it. Without a defined standard mechanism by which function authors can publish details of their expectations for the XRD, it would be a fair assumption that each function author may publish details in different ways or not at all, leaving those writing the XRDs unsure of how to integrate that feature.

### How could Crossplane help solve your problem?

Crossplane can help solve this issue in a number of ways.

1. Define standards around how function authors should publish details of any output and/or patching it may be carrying out.
    
    This can be as simple as extending the `go generate` step to include patch and output specifications that can can be consumed by the authors of XRDs.
    
    For example, if a function is going to create the subnets patch, then it may contain a directory `package/patch` containing the OpenAPI spec of any patches it is going to apply.

    This would have the added benefit of allowing XRD authors to develop tooling for building XRDs using valid published OpenApiV3 schemas, ensuring their XRD complies with the behaviour of the function.
    
2. `[optional]` If a function defines a specification for a patch, this could be validated by the function runtime to ensure the patch matches the definition before it is sent back over `gRPC` If the patch does not match the specification, the function runtime should log this error and potentially block the application of the patch to the `DesiredComposite` resource.

3. `[optional]` When a function returns, if the spec of the function return does not match the spec of the XRD at that location, it would be helpful if crossplane could emit either an error or warning event that the patch is incompatible with the XRD, additionally dropping the patch to prevent placing the XR into an invalid state such as that witnessed in https://github.com/crossplane/crossplane/issues/4968, further raising the profile of the incompatibility between function behaviour and XRD expectations.
