### ISSUE TITLE
Imported S3 Resource Tags Are Overwritten

### ISSUE THREAD

**Issue by humoflife** [crossplane/crossplane#4990]
### What happened?

When following the section under “Import resources manually” in Crossplane's documentation to import an existing S3 bucket into Crossplane (https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/), the tags on the bucket got overwritten. This is unexpected. Testing the same import with a KMS key in the same way did not result in Crossplane overwriting the tags.

### How can we reproduce it?

Follow the "Import resources manually" documentation at https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/.

### What environment did it happen in?
Crossplane version: 1.13.2

**Comment by haarchri** [comment]
Which provider ?

**Comment by humoflife** [comment]
On resource import, provider-aws-s3 overwrites the tags of a bucket, provider-aws-kms does not overwrite the tags of a key.

**Comment by simplyanks80** [comment]
@humoflife what version of the provider was this observed in?

**Comment by humoflife** [comment]
0.42, also now verifying with v0.44.

**Comment by humoflife** [comment]
provider-aws-s3 v0.44 also unexpectedly overwrites the tags.

**Comment by haarchri** [comment]
Can you add full manifest and the manifest after import  and screenshot from the bucket tags ?

**Comment by turkenf** [comment]
I can reproduce this with version 0.45.0:

*1.* In the AWS console, I created a bucket named `tag-test-aws-s3bucket` with the tags seen in the screenshot below.

![Screenshot 2023-12-05 at 14 35 27](https://github.com/crossplane/crossplane/assets/103541666/400cc780-6011-4a91-828f-762b6b8858ed)

*2.*  I imported the resource with the following manifest:
```
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: tag-test-aws-s3bucket
  labels:
    testing.upbound.io/example-name: s3
  name: tag-test
spec:
  forProvider:
    region: us-west-1
```
*3.* Screenshot in the console after import:

![Screenshot 2023-12-05 at 14 38 02](https://github.com/crossplane/crossplane/assets/103541666/41bea07a-d7e1-45d3-8933-2b32b968e87c)
 
- and the `get -o yaml` output from the bucket: [logs.txt](https://github.com/crossplane/crossplane/files/13559641/logs.txt)

**Comment by haarchri** [comment]
so we adding our default tags:

```
    tags:
      crossplane-kind: bucket.s3.aws.upbound.io
      crossplane-name: tag-test
      crossplane-providerconfig: default
```
