### ISSUE TITLE
x-kubernetes-validations not supported if outside `spec`

### ISSUE THREAD

**Issue by prfj** [crossplane/crossplane#4993]
### What happened?

In https://github.com/crossplane/crossplane/issues/3604 crossplane XRD started to support x-kubernetes-validations however just inside `spec` block, for example to apply rules in metadata.name or labels, or lower level its not working

### How can we reproduce it?

apply a CustomResourceDefinition (CRD) with x-kubernetes-validations outside spec, it will work

```
  versions:
    - name: v1alpha1
      referenceable: true
      served: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          x-kubernetes-validations:
            - rule: "self.metadata.name == (self.spec.myparameter1 + '-' + self.spec.myparameter2)"
              message: "metadata.name must be spec.myparameter1-spec.myparameter2"
          properties:
            spec:
              type: object
              ...
```
if we apply this rule on a CompositeResourceDefinition (XRD) it is ignored

### What environment did it happen in?
Crossplane version: 1.14
Kubernetes: v1.27.3
