### ISSUE TITLE
Annotations are not being added when using DeploymentRuntimeConfig

### ISSUE THREAD

**Issue by denzhel** [crossplane/crossplane#4998]
### What happened?
AWS IAM role annotations are not being added to the service account when using DeploymentRuntimeConfig.
It does work with ControllerConfig.

Since the IAM role is not being attached to the service account, I can no longer assume roles.

#### What works:
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: dev-eu-central-1-crossplane
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1234567:role/dev-eu-central-1-crossplane-aws-provider
```
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:v0.43.1
  controllerConfigRef:
    name: dev-eu-central-1-crossplane
```
```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: dev-eu-central-1-this-account
spec:
  credentials:
    source: IRSA
```
```
eks_dev-eu-central-1 ➜  crossplane k describe sa provider-aws-s3-c12705275836
Name:                provider-aws-s3-c12705275836
Namespace:           crossplane
Labels:              <none>
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::1234567:role/dev-eu-central-1-crossplane-aws-provider
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```
#### What does not work:
```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: dev-eu-central-1-crossplane
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::208463348169:role/dev-eu-central-1-crossplane-aws-provider
```
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:v0.43.1
  runtimeConfigRef:
    name: dev-eu-central-1-crossplane
```
```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: dev-eu-central-1-this-account
spec:
  credentials:
    source: IRSA
```
```
eks_dev-eu-central-1 ➜  crossplane k describe sa provider-aws-s3-c12705275836
Name:                provider-aws-s3-c12705275836
Namespace:           crossplane
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```

### What environment did it happen in?
Crossplane version: 1.14
Cloud provider: AWS
Kubernetes version: Server Version: v1.26.10-eks-4f4795d

**Comment by turkenh** [comment]
With `DeploymentRuntimeConfig`, we have dedicated fields to configure metadata of runtime resources (`Deployment`, `ServiceAccount` and `Service`), see https://docs.crossplane.io/v1.14/concepts/providers/#configuring-metadata-of-runtime-resources

The following is the new way to go: 

```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: my-runtime-config
spec:
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::1234567:role/dev-eu-central-1-crossplane-aws-provider
```
