### ISSUE TITLE
crossplane beta render  is failing in the ci pipeline

### ISSUE THREAD

**Issue by katikireddy622** [crossplane/crossplane#4999]
### What happened?
I have rendered the composite resources locally using the crossplane beta render command but when I add that to the gitlab ci pipeline, I am getting the following errors: 

```
$ crossplane beta render tests/unit/xr.yaml package/composition_v1alpha1.yaml tests/unit/functions.yaml
crossplane: error: cannot render composite resource: cannot run pipeline step "patch-and-transform": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:41489: connect: connection refused"
```

### How can we reproduce it?

my gitlab ci job 

```
rendercomposition:
  stage: test
  image: $DOCKER_CROSSPLANE_CLI
  tags:
    - docker+machine
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - crossplane beta render tests/unit/xr.yaml package/composition_v1alpha1.yaml tests/unit/functions.yaml

```

### What environment did it happen in?
Crossplane version:  v1.14.0
