### ISSUE TITLE
Changing a provider's `runtimeConfigRef` doesn't create a new `ProviderRevision`

### ISSUE THREAD

**Issue by Kidswiss** [crossplane/crossplane#5068]
### What happened?
While debugging some issues, I found that changing a provider's `runtimeConfigRef` doesn't spawn a new `ProviderRevision`. This seems like a counterintuitive behavior to me.

While chatting with @phisco we both agreed that this would probably be considered a bug, or at least a sensible behavior.

### How can we reproduce it?
1. Apply a provider package
1. Wait for it to be ready
1. Change its `runtimeConfigRef`
1. No new `ProviderRevision` is created

### What environment did it happen in?
Crossplane version: 1.14.1

**Comment by Kidswiss** [comment]
Okay, if found a few more issues here.

Example:
* Migrating the providers from the controllerConfig to the runtimeConfig. 
* Remove the controllerConfigRef in the provider and the controllerConfig itself from the cluster.
* Add a runtimeConfig and add the ref to the provider.
* Apply everything.
* The provider gets unhealthy, because the currently active revision is neither updated with the new refs, nor replaced with another revision.
* Manual deletion of the revision is necessary.

**Comment by Kidswiss** [comment]
I just tried to reproduce it again with plain k8s. It still breaks, but differently. My other description was observed on OpenShift. On OpenShift no new revision was spawned for me, with the same events (cannot get referenced controller config). One other difference is that my first report is based on Crossplane 1.14.1 and this test on 1.14.3, so maybe some things were already fixed.

provider-controller-conf.yaml:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: "crossplanecontrib/provider-kubernetes:main"
  controllerConfigRef:
    name: kubernetes
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: kubernetes
  name: kubernetes
spec:
  serviceAccountName: provider-kubernetes
```

provider-runtime-conf.yaml:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: provider-kubernetes
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.9.0
  runtimeConfigRef:
    name: provider-kubernetes
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              securityContext: {}
          securityContext: {}
          serviceAccountName: provider-kubernetes
```

```
kubectl apply -f provider-controller-conf.yaml
# wait until its ready

kubectl delete controllerconfigs.pkg.crossplane.io kubernetes
kubectl apply -f provider-runtime-conf.yaml 
```

Inspect the revisions, first the old one:
```
  Warning  SyncPackage        10s (x16 over 6m39s)   packages/providerrevision.pkg.crossplane.io  cannot prepare runtime manifest builder options: cannot get referenced controller config: ControllerConfig.pkg.crossplane.io "kubernetes" not found
```

And the new one:
```
  Warning  SyncPackage      54s (x11 over 6m53s)   packages/providerrevision.pkg.crossplane.io  cannot establish control of object: providerconfigusages.kubernetes.crossplane.io is already controlled by ProviderRevision provider-kubernetes-25f96d7ba8c1 (UID 4b84daf4-6ff5-4f6b-a9f4-8f0c522b48bf)
```
