### ISSUE TITLE
Allow CompositeResourceDefinition to be Unstructured

### ISSUE THREAD

**Issue by ra-grover** [crossplane/crossplane#5070]
### What problem are you facing?

We want to provide a namespaced access to Crossplane resources, for example a S3 bucket. To enable that we are leveraging CompositeResourceDefinitions and Compositions to create a namespaced claim, and then creating a new `CompositeResourceDefinitions` which looks exactly like native `s3.aws.crossplane.io.Bucket` crossplane definition, this is causing duplication. In case Crossplane providers upgrade `Bucket`'s definition to add more fields, we will have to change it in our `CompositeResourceDefinitions` to make it available on our platform.

### How could Crossplane help solve your problem?

 Is there a way through which we can create Unstructured `CompositeResourceDefinitions` which can be schema-less, providing the ability to use any fields, and then whatever fields are being supplied on CompositeResources can be used in Compositions. For example, an Unstructured `CompositeResourceDefinition` like below.
```
# Fields Removed for brevity
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
spec:
  claimNames:
    kind: RagS3
    plural: rags3s
  group: ragrover.io
  names:
    kind: xRagS3
    plural: xrags3s
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Sample Desc
              type: object
              x-kubernetes-preserve-unknown-fields: true
```

Now I can use this in my Composition like this:
```
- name: s3-bucket
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec ##whole spec gets used in the spec.forProvider of the bucket.
          toFieldPath: spec.forProvider
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          providerConfigRef:
            name: crossplane-provider-config
          forProvider:
```

And now just create:
```
apiVersion: ragrover.io/v1alpha1
kind: RagS3
metadata: 
  name: hello-delete-me-2
  namespace: runtime-tools
spec:
  locationConstraint: us-east-1
 #More s3 bucket fields that I want to supply
```

I tried it through this way, but `x-kubernetes-preserve-unknown-fields` is not being propagated to `CustomResourceDefinition` for Composite resource.
