### ISSUE TITLE
providers `revisionActivationPolicy: Manual` not possible in `v1.14.x` cannot establish control of object: cannot get webhook tls secret

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#5082]
### What happened?

It seems that the migration process from monolithic to official family providers (https://docs.upbound.io/providers/migration/#manual-migration)  is encountering issues with Crossplane version 1.14. Specifically, all providers, including the family providers, are getting stuck while waiting for TLS certificates. If you attempt to remove the monolithic provider during this phase, it results in the removal of all CRDs and managed resources associated with the monolithic provider.
Examples with `v1.13.2` and `v1.14.2`

create first the monolith provider:
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.45.0
```

create first family provider:
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v0.45.0
  revisionActivationPolicy: Manual
```

create one scoped provider:
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v0.45.0
  revisionActivationPolicy: Manual
```

**v1.13.2:**

```
kubectl get providers
NAME                  INSTALLED   HEALTHY   PACKAGE                                               AGE
provider-aws          True        True      xpkg.upbound.io/upbound/provider-aws:v0.45.0          13m
provider-aws-ec2      False       True      xpkg.upbound.io/upbound/provider-aws-ec2:v0.45.0      78s
provider-family-aws   False       True      xpkg.upbound.io/upbound/provider-family-aws:v0.45.0   10m
```

```
kubectl get pkgrev
NAME                                                                  HEALTHY   REVISION   IMAGE                                                 STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/provider-aws-85e8d6446b52          True      1          xpkg.upbound.io/upbound/provider-aws:v0.45.0          Active                               14m
providerrevision.pkg.crossplane.io/provider-aws-ec2-f90d25cd37c7      True      1          xpkg.upbound.io/upbound/provider-aws-ec2:v0.45.0               1           1               92s
providerrevision.pkg.crossplane.io/provider-family-aws-a48d4ad1d73a   True      1          xpkg.upbound.io/upbound/provider-family-aws:v0.45.0                                        9m56s
```

```
kubectl get providerrevision.pkg.crossplane.io/provider-family-aws-a48d4ad1d73a -o yaml
apiVersion: pkg.crossplane.io/v1
kind: ProviderRevision
metadata:
  annotations:
    auth.upbound.io/group: aws.upbound.io
    friendly-name.meta.crossplane.io: Provider AWS (config)
    meta.crossplane.io/description: |
      Upbound's official Crossplane provider to manage Amazon Web Services (AWS)
      config services in Kubernetes.
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/readme: |
      Provider AWS is a Crossplane provider for [Amazon Web Services
      (AWS)](https://aws.amazon.com/) developed and supported by Upbound.
      Available resources and their fields can be found in the [Upbound
      Marketplace](https://marketplace.upbound.io/providers/upbound/provider-aws).
      If you encounter an issue please reach out on support@upbound.io email
      address. This is a subpackage for the config API group.
    meta.crossplane.io/source: github.com/upbound/provider-aws
  creationTimestamp: "2023-12-01T12:02:15Z"
  finalizers:
  - revision.pkg.crossplane.io
  generation: 1
  labels:
    pkg.crossplane.io/package: provider-family-aws
    pkg.crossplane.io/provider-family: provider-family-aws
  name: provider-family-aws-a48d4ad1d73a
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Provider
    name: provider-family-aws
    uid: 050100b4-528b-4fa7-a54d-a8919bb58a62
  resourceVersion: "4278"
  uid: 41dc46bf-9cc2-407e-8e35-2811d17f6988
spec:
  desiredState: ""
  ignoreCrossplaneConstraints: false
  image: xpkg.upbound.io/upbound/provider-family-aws:v0.45.0
  packagePullPolicy: IfNotPresent
  revision: 1
  skipDependencyResolution: false
  webhookTLSSecretName: webhook-tls-secret
status:
  conditions:
  - lastTransitionTime: "2023-12-01T12:02:24Z"
    reason: HealthyPackageRevision
    status: "True"
    type: Healthy
  controllerRef:
    name: ""
  objectRefs:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: storeconfigs.aws.upbound.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: providerconfigusages.aws.upbound.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: providerconfigs.aws.upbound.io
```

check if the ownerReference is updated with both revisions:
one example:

```
kubectl get crds storeconfigs.aws.upbound.io -o yaml 
[...]
  name: storeconfigs.aws.upbound.io
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ProviderRevision
    name: provider-aws-85e8d6446b52
    uid: 18d13da6-dba8-4798-a7b2-839c9c1b000b
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: false
    kind: Provider
    name: provider-aws
    uid: efef55fa-7c8e-46a1-8b18-e2d3e703a126
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: false
    kind: Provider
    name: provider-family-aws
    uid: 050100b4-528b-4fa7-a54d-a8919bb58a62
  - apiVersion: pkg.crossplane.io/v1
    kind: ProviderRevision
    name: provider-family-aws-a48d4ad1d73a
    uid: 41dc46bf-9cc2-407e-8e35-2811d17f6988
[...]
```

**v1.14.2:**

```
kubectl get providers
NAME                  INSTALLED   HEALTHY   PACKAGE                                               AGE
provider-aws          True        True      xpkg.upbound.io/upbound/provider-aws:v0.45.0          6m27s
provider-aws-ec2      False       False   xpkg.upbound.io/upbound/provider-aws-ec2:v0.45.0      15s
provider-family-aws   False       False     xpkg.upbound.io/upbound/provider-family-aws:v0.45.0   21s
```

```
kubectl get pkgrev
NAME                                                                  HEALTHY   REVISION   IMAGE                                                 STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/provider-aws-85e8d6446b52          True      1          xpkg.upbound.io/upbound/provider-aws:v0.45.0          Active                               6m42s
providerrevision.pkg.crossplane.io/provider-aws-ec2-f90d25cd37c7      False     1          xpkg.upbound.io/upbound/provider-aws-ec2:v0.45.0               1           1               30s
providerrevision.pkg.crossplane.io/provider-family-aws-a48d4ad1d73a   False     1          xpkg.upbound.io/upbound/provider-family-aws:v0.45.0                                        34s
```

```
 kubectl describe providerrevision.pkg.crossplane.io/provider-family-aws-a48d4ad1d73a
Name:         provider-family-aws-a48d4ad1d73a
Namespace:    
Labels:       pkg.crossplane.io/package=provider-family-aws
              pkg.crossplane.io/provider-family=provider-family-aws
Annotations:  auth.upbound.io/group: aws.upbound.io
              friendly-name.meta.crossplane.io: Provider AWS (config)
              meta.crossplane.io/description:
                Upbound's official Crossplane provider to manage Amazon Web Services (AWS)
                config services in Kubernetes.
              meta.crossplane.io/maintainer: Upbound <support@upbound.io>
              meta.crossplane.io/readme:
                Provider AWS is a Crossplane provider for [Amazon Web Services
                (AWS)](https://aws.amazon.com/) developed and supported by Upbound.
                Available resources and their fields can be found in the [Upbound
                Marketplace](https://marketplace.upbound.io/providers/upbound/provider-aws).
                If you encounter an issue please reach out on support@upbound.io email
                address. This is a subpackage for the config API group.
              meta.crossplane.io/source: github.com/upbound/provider-aws
API Version:  pkg.crossplane.io/v1
Kind:         ProviderRevision
Metadata:
  Creation Timestamp:  2023-12-01T12:21:11Z
  Finalizers:
    revision.pkg.crossplane.io
  Generation:  2
  Owner References:
    API Version:           pkg.crossplane.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Provider
    Name:                  provider-family-aws
    UID:                   813e1c1f-3274-4e1d-9baa-18c328ff239f
  Resource Version:        4795
  UID:                     fc2de286-3eb8-4027-aacf-5c636ecc2f15
Spec:
  Desired State:                  ""
  Ignore Crossplane Constraints:  false
  Image:                          xpkg.upbound.io/upbound/provider-family-aws:v0.45.0
  Package Pull Policy:            IfNotPresent
  Revision:                       1
  Runtime Config Ref:
    API Version:               pkg.crossplane.io/v1beta1
    Kind:                      DeploymentRuntimeConfig
    Name:                      default
  Skip Dependency Resolution:  false
  Tls Client Secret Name:      provider-family-aws-tls-client
  Tls Server Secret Name:      provider-family-aws-tls-server
Status:
  Conditions:
    Last Transition Time:  2023-12-01T12:21:18Z
    Message:               cannot establish control of object: cannot get webhook tls secret: secrets "provider-family-aws-tls-server" not found
    Reason:                UnhealthyPackageRevision
    Status:                False
    Type:                  Healthy
Events:
  Type     Reason           Age                 From                                         Message
  ----     ------           ----                ----                                         -------
  Normal   BindClusterRole  13s (x6 over 100s)  rbac/providerrevision.pkg.crossplane.io      Bound system ClusterRole "crossplane:provider:provider-family-aws-a48d4ad1d73a:system" to provider ServiceAccount(s):
  Warning  SyncPackage      10s (x8 over 93s)   packages/providerrevision.pkg.crossplane.io  cannot establish control of object: cannot get webhook tls secret: secrets "provider-family-aws-tls-server" not found
```

```
kubectl get crds storeconfigs.aws.upbound.io -o yaml 
[...]
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ProviderRevision
    name: provider-aws-85e8d6446b52
    uid: c1bf9988-91f0-4226-8514-c848dfefbeb1
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: false
    kind: Provider
    name: provider-aws
    uid: ad9b8498-0358-498e-8d4c-b27a2d9ea17c
[...]
```

### What environment did it happen in?
Crossplane version: v1.14.2
