### ISSUE TITLE
Multiple owenerships for single external resource

### ISSUE THREAD

**Issue by katikireddy622** [crossplane/crossplane#5093]
### What happened?

We have created a composition on top of Kafka Topic and Acls. 1 claim creates 1 Topic and 3 Acls. so the problem here is when we apply the same claim in 2 different namespaces. we see that both claims and managed resources are created and in sync, ready state. But, the external resource is only one. so the question here is why does crossplane accepting multiple ownerships for single external resource?

### How can we reproduce it?

I don't want to give the complex code, I want to keep the things simple, we will try to apply the same Topic ( directly implementing native crd) in two different namespaces. 
**Note:** Before this you need to have kafka topic provider installed. 

**Topic 1** in kr3ebooks namespace
```
apiVersion: topic.kafka.crossplane.io/v1alpha1
kind: Topic
metadata:
  annotations:
    crossplane.io/composition-resource-name: topic
    crossplane.io/external-name: a.a.katikireddy622
  generation: 3
  labels:
    crossplane.io/claim-name: service-a-topic
    crossplane.io/claim-namespace: kr3ebooks
  name: kr3ebooks-service-a-topic
spec:
  deletionPolicy: Delete
  forProvider:
    config:
      cleanup.policy: compact
      compression.type: producer
      delete.retention.ms: "86400000"
      file.delete.delay.ms: "60000"
      flush.messages: "9223372036854775807"
      flush.ms: "9223372036854775807"
      follower.replication.throttled.replicas: ""
      index.interval.bytes: "4096"
      leader.replication.throttled.replicas: ""
      max.compaction.lag.ms: "9223372036854775807"
      max.message.bytes: "1048588"
      message.downconversion.enable: "true"
      message.format.version: 2.8-IV1
      message.timestamp.difference.max.ms: "9223372036854775807"
      message.timestamp.type: CreateTime
      min.cleanable.dirty.ratio: "0.5"
      min.compaction.lag.ms: "0"
      min.insync.replicas: "2"
      preallocate: "false"
      retention.bytes: "-1"
      retention.ms: "84000"
      segment.bytes: "1073741824"
      segment.index.bytes: "10485760"
      segment.jitter.ms: "0"
      segment.ms: "604800000"
      unclean.leader.election.enable: "true"
    partitions: 1
    replicationFactor: 1
  providerConfigRef:
    name: crossplane-provider-kafka
```

**Topic 2** in katikireddy622 namespace
```
apiVersion: topic.kafka.crossplane.io/v1alpha1
kind: Topic
metadata:
  annotations:
    crossplane.io/composition-resource-name: topic
    crossplane.io/external-name: a.a.katikireddy622
  generation: 3
  labels:
    crossplane.io/claim-name: service-a-topic
    crossplane.io/claim-namespace: katikireddy622
  name: katikireddy622-service-a-topic
spec:
  deletionPolicy: Delete
  forProvider:
    config:
      cleanup.policy: compact
      compression.type: producer
      delete.retention.ms: "86400000"
      file.delete.delay.ms: "60000"
      flush.messages: "9223372036854775807"
      flush.ms: "9223372036854775807"
      follower.replication.throttled.replicas: ""
      index.interval.bytes: "4096"
      leader.replication.throttled.replicas: ""
      max.compaction.lag.ms: "9223372036854775807"
      max.message.bytes: "1048588"
      message.downconversion.enable: "true"
      message.format.version: 2.8-IV1
      message.timestamp.difference.max.ms: "9223372036854775807"
      message.timestamp.type: CreateTime
      min.cleanable.dirty.ratio: "0.5"
      min.compaction.lag.ms: "0"
      min.insync.replicas: "2"
      preallocate: "false"
      retention.bytes: "-1"
      retention.ms: "84000"
      segment.bytes: "1073741824"
      segment.index.bytes: "10485760"
      segment.jitter.ms: "0"
      segment.ms: "604800000"
      unclean.leader.election.enable: "true"
    partitions: 1
    replicationFactor: 1
  providerConfigRef:
    name: crossplane-provider-kafka
```
**ProviderConfig**
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-kafka
spec:
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/crossplane-contrib/provider-kafka:v0.4.3
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: crossplane-provider-kafka
  skipDependencyResolution: false
```

**DeploymentRuntimeConfig**
```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: crossplane-provider-kafka
spec:
  deploymentTemplate:
    spec:
      selector: {}
      strategy: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              limits:
                cpu: 1
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 64Mi
          serviceAccountName: crossplane
```

### What environment did it happen in?
Crossplane version: 
1.14.3

EKS
v1.26.3

**Comment by phisco** [comment]
Is the Composition using functions (`mode: Pipeline`)?

**Comment by katikireddy622** [comment]
> Is the Composition using functions (`mode: Pipeline`)?

Yes, 

```
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
```

and we are using `xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.2.1` as a function image
