### ISSUE TITLE
`oneOf` is propagated incorrectly to the generated CRD

### ISSUE THREAD

**Issue by vedantthapa** [crossplane/crossplane#5097]
### What happened?

I was exploring the `oneOf`  validation and for some reason it works on the field within an openAPIV3Schema `spec` (`notebookConfig` in the example) but not on the `spec` field itself.

In the following example, notice how `kubectl apply` successfully creates `test2`, when instead it should've raised an error similar to `test1`

I posted this on [slack](https://crossplane.slack.com/archives/CEG3T90A1/p1701962490139389) and @phisco pointed out that the `oneOf` validation in the XRD was not being propagated down to it's CRD.

### How can we reproduce it?

Here's an example of my XRD:
```yaml
# xtest.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtest.example.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: example.io
  names:
    kind: XTest
    plural: xtest
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                projectName:
                  type: string
                notebookConfig:
                  type: object
                  properties:
                    idleShutdownTimeout:
                      type: number
                    machineType:
                      type: string
                  oneOf:
                    - required: ["idleShutdownTimeout"]
                    - required: ["machineType"]
              oneOf:
                - required: ["projectId"]
                - required: ["projectName"]
```
and the XRs
```yaml
# test.yaml
apiVersion: example.io/v1beta1
kind: XTest
metadata:
  name: test1
spec:
  notebookConfig: {}
---
apiVersion: example.io/v1beta1
kind: XTest
metadata:
  name: test2
spec: {}
```
`kubectl apply` then produces the following:
```sh
> kubectl apply -f test.yaml
xtest.example.io/test2 created
The XTest "test1" is invalid:
* <nil>: Invalid value: "": "spec.notebookConfig" must validate one and only one schema (oneOf). Found none valid
* spec.notebookConfig.idleShutdownTimeout: Required value
```

### What environment did it happen in?
Crossplane version: `v1.14.3`
Kubernetes version: 
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.5-gke.200
```

**Comment by phisco** [comment]
This could be considered by design maybe, as we always expect CRDs defined by XRDs to have a status and a spec, and probably have other assumptions too. It would be better to enforce these assumptions and add some validation. WDYT @turkenh @negz?

**Comment by negz** [comment]
> This could be considered by design maybe, as we always expect CRDs defined by XRDs to have a status and a spec, and probably have other assumptions too.

@phisco I'm not following how this is related to `oneOf` not being propagated. 🤔

**Comment by phisco** [comment]
@negz, it's only `OneOf`s at the "root" level that are not propagated, other more internal ones are propagated transparently. As in the example, one can not define that either one of two fields is required, if those fields are at the same level of the `spec` we are going to add later.

**Comment by LCaparelli** [comment]
Just chiming in, we also would like this to be supported.

FWIW, we're working around this for now using [CEL validation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules) rules (which might be for the best, the error message the API Server throws is super cryptic when using `oneOf`):

```yaml
spec:
  versions:
  - schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              acceleratorName:
                type: string
              listenerArn:
                type: string
            x-kubernetes-validations:
            # hasNameOnly || hasArnOnly; must have one, and only one.
            - rule: "(has(self.acceleratorName) && !has(self.listenerArn)) || (!has(self.acceleratorName) && has(self.listenerArn))"
              message: .spec.acceleratorName and .spec.listenerName are mutually exclusive, and exactly one of them is required.
```
