### ISSUE TITLE
Automatically uninstall provider-family if no other Provider is installed

### ISSUE THREAD

**Issue by maximiliantech** [crossplane/crossplane#5102]
### What problem are you facing?
I am applying the following manifest to my Kubernetes cluster (with Crossplane installed):

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-amplify
spec:
  package: xpkg.upbound.io/upbound/provider-aws-amplify:v0.45.0
EOF
```
It will automatically install the Amplify Provider along with its AWS provider-family Provider resource, see:

![Screenshot 2023-12-08 at 15 27 52](https://github.com/crossplane/crossplane/assets/74709975/a6fff899-2577-45d0-9c59-2722163c80cd)

When deleting the Amplify Provider, the AWS provider-family resource will stay untouched.
As a user, I have to keep track manually, if the provider-family still exists in my cluster and and delete it.

### How could Crossplane help solve your problem?

Regardless of the specific Crossplane Provider family, I would like to see, that a provider-family Provider resource gets deleted automatically, if no other Provider resource is depended on it and no other resources such as ProviderConfigs are configured.
