### ISSUE TITLE
Unable to patch a to field more than 1X

### ISSUE THREAD

**Issue by davejhahn** [crossplane/crossplane#5120]
### What happened?

Background what I am trying to do, since there may be another solution....

The external names are important for me and I need to be able to control them.  Ideally what I would like to do is automatically generate most of the name based on EnvironmentConfig and only have one component provided by the user in the xr.

The CombineFromEnvironment patch only works against environment, so I can't, in a single patch, combine both EnvironmentConfig and Composite values. 

My thought is that I could combine the environment config values, patch crossplane.io/external-name, then use a second patch, CombineFromComposite, to combine what I had already patched and add the user provided value.

Something like this:

```
        - type: CombineFromEnvironment
          combine:
            strategy: string
            variables:
            - fromFieldPath: org.identifier
            - fromFieldPath: productsub.identifier
            - fromFieldPath: env.code
            - fromFieldPath: location.short
            - fromFieldPath: product.identifier
            string: 
              fmt: "%s%sxx%s%s%s"
          toFieldPath: metadata.annotations[crossplane.io/external-name]

        - type: CombineFromComposite
          combine:
            strategy: string
            variables:
            - fromFieldPath: metadata.annotations[crossplane.io/external-name]
            - fromFieldPath: spec.identifier            
            string: 
              fmt: "%s%s"
          toFieldPath: metadata.annotations[crossplane.io/external-name]
```

So this is a workaround since I am not aware of a patch that allows both composite and environment, to patch based on one type, then use that result and patch based on the second type.

The external name gets named based on the first patch with the correct values but it seems that the second patch does nothing.   

### How can we reproduce it?

Example above.

Ideally there would be a patch that can pull from composite and environment, but assuming that is a feature not available. 

Not sure if write a patch > 1 time is supported?   Any other suggestions in how to approach this?  This is a blocker in moving forward because it is a design consideration if we need to pass the names in, e.g. generate via helm and pass in vs. just passing in one component of the name.  

### What environment did it happen in?
Crossplane version: 0.21.0

**Comment by bobh66** [comment]
I think the way to do this is to patch the Composite spec information that you need into the Composition environment using 
```
environment:
  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: spec.identifier
    toFieldPath: data.identifier
```
and then use CombineFromEnvironment to format your external-names the way you want them with `data.identifier` containing the Composite spec input.
