### ISSUE TITLE
`crossplane beta render` does not render XR status

### ISSUE THREAD

**Issue by ytsarev** [crossplane/crossplane#5124]
### What happened?

`crossplane beta render` does not reflect any updates to the associated XR status.

It is not possible to observe any effects of `ToCompositeFieldPath` patches to XR status similar to

```
 - fromFieldPath: metadata.annotations[crossplane.io/external-name]
   toFieldPath: status.subnetIds[0]
   type: ToCompositeFieldPath
```

The situation is worse in case of bi-directional patching with the policy `fromFieldPath: required` ,e.g

```
- type: FromCompositeFieldPath
  fromFieldPath: status.eks.clusterSecurityGroupId
  toFieldPath: spec.forProvider.resourceId
  policy:
    fromFieldPath: Required
```

In this case the associated MR will never be rendered at all because of non-updated XR status

### How can we reproduce it?

Clone https://github.com/upbound/configuration-aws-network 

Run

```
crossplane beta render examples/network-xr.yaml apis/basic/composition.yaml examples/function/function.yaml 
```

Observe that XR status is empty in the render output

```
---
apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: ref-aws-network
```

### What environment did it happen in?
Crossplane CLI version: 
```
crossplane -v
v1.14.4
```

**Comment by haarchri** [comment]
From my perspective, currently the render command fails to generate external names as defined by crossplane.io/external-name, especially when CloudProvider specifies the identifier.

Consequently, the status remains unpopulated. A temporary solution is to manually set the status in the XR to test all necessary fields derived from the status. Does this approach sound feasible? For reference, you can examine this demonstration PR: https://github.com/upbound/configuration-aws-network/pull/8/files

**Comment by turkenh** [comment]
> A temporary solution is to manually set the status in the XR to test all necessary fields derived from the status.

Or another alternative could be, passing that resource as an [observed resource](https://github.com/crossplane/crossplane/blob/095e01a8584605cf9d8740551f8c951ee54ac157/cmd/crank/beta/render/cmd.go#L48) with some mocked external name?

**Comment by ytsarev** [comment]
@haarchri @turkenh thanks for the hints, I made some tests.

Added samples with observed mocks https://github.com/upbound/configuration-aws-network/pull/9/files

It actually looks manageable

```
crossplane beta render examples/network-xr.yaml apis/basic/composition.yaml examples/function/function.yaml -r -o examples/observed.yaml
---
apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: ref-aws-network
status:
  cidrBlock: 192.168.0.0/18
  subnetIds:
  - subnetPublicAextnameTest
  test: subnet-id-test
---
```

But there are confusing parts like

https://github.com/upbound/configuration-aws-network/pull/9/files#diff-f87705a2130dede4d49218c4c540823200ada4c33e4bf77dfc142918c66217bdR7

it is what probably initially led me to impression that observed mocks are not working for xr status at all
