### ISSUE TITLE
Azure Gov CannotObserveExternalResource

### ISSUE THREAD

**Issue by mkm29** [crossplane/crossplane#5126]
### What happened?

I am attempting to use crossplane to manage cloud resources in Azure US Government. 

### How can we reproduce it?

I am following this [guide](https://docs.crossplane.io/latest/getting-started/provider-azure/). To test I just am trying to create a ResourceGroup:

```yaml
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: crossplane-test-rg
spec:
  deletionPolicy: Delete
  forProvider:
    location: US Gov Virginia
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: v1.14.3

Furthermore, I add this environment variable to the crossplane deployment:

`AZURE_ENVIRONMENT: AzureUSGovernmentCloud`

All pods are running:

```console
➜  k get po -n crossplane-system              
NAME                                                          READY   STATUS    RESTARTS   AGE
crossplane-58dc5885d4-s9sh6                                   1/1     Running   0          43h
crossplane-rbac-manager-5896c58bb7-c5v5v                      1/1     Running   0          45h
provider-azure-network-b0d76ab3ffc7-5ff9b8c657-56xkl          1/1     Running   0          10m
upbound-provider-family-azure-637b77277dbe-57945468f4-2fhzs   1/1     Running   0
```

### Error(s):

```console
Warning  CannotObserveExternalResource  31s (x14 over 13m)  managed/azure.upbound.io/v1beta1, kind=resourcegroup  (combined from similar events): cannot run refresh: refresh failed: building account: could not acquire access token to parse claims: clientCredentialsToken: received HTTP status 400 with response: {"error":"invalid_request","error_description":"AADSTS900382: Confidential Client is not supported in Cross Cloud request. Trace ID: 07ef7fb4-36dc-406d-af1e-823465982700 Correlation ID: e3790a31-9bcc-454f-ad8b-afd96bfed1c1 Timestamp: 2023-12-13 17:15:23Z","error_codes":[900382],"timestamp":"2023-12-13 17:15:23Z","trace_id":"07ef7fb4-36dc-406d-af1e-823465982700","correlation_id":"e3790a31-9bcc-454f-ad8b-afd96bfed1c1"}:
```

All of the endpoints are contained in the secret so I am not sure why this is happening.

```yaml
{
  "clientId": "<REDACTED>",
  "clientSecret": "<REDACTED>",
  "subscriptionId": "<REDACTED>",
  "tenantId": "<REDACTED>",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.us",
  "resourceManagerEndpointUrl": "https://management.usgovcloudapi.net/",
  "activeDirectoryGraphResourceId": "https://graph.windows.net/",
  "sqlManagementEndpointUrl": "https://management.core.usgovcloudapi.net:8443/",
  "galleryEndpointUrl": "https://gallery.usgovcloudapi.net/",
  "managementEndpointUrl": "https://management.core.usgovcloudapi.net/"
}
```
