### ISSUE TITLE
Environment Selector Not Matching

### ISSUE THREAD

**Issue by davejhahn** [crossplane/crossplane#5225]
### What happened?

I have several environment configs with a composition that has 3 "Reference" types and then a "Selector" type that has three matching labels, each using "FromCompositeFieldPath".

I am missing values that would be obtained from one or more of the configs defined in the selector.  

When I do a kubectl describe on the composite resource it only shows the "Reference" types, so I know it is not matching.

The environment in the composition looks like:

```
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: global
      - type: Reference
        ref:
          name: organization
      - type: Reference
        ref:
          name: resource-xkeyvault          
      - type: Selector
        selector:
          mode: Single
          matchLabels:
            - key: environment
              type: FromCompositeFieldPath
              valueFromFieldPath: spec.config.environment
            - key: product
              type: FromCompositeFieldPath
              valueFromFieldPath: spec.config.product
            - key: productsubscription
              type: FromCompositeFieldPath
              valueFromFieldPath: spec.config.productSubscription
```

Below is one of the environmentconfigs:

```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: environment-development
  labels:
    environment: Development
data:
  name:
    short: d
    long: Development
```

Then in the XR, I am specifying the values in the expected paths as below for the three valueFromFieldPath locations, below has product and productSubscription obfuscated (but they are definitely set and deployed):

```
apiVersion: iac.alegeus.com/v1alpha1
kind: xKeyVault
metadata: 
  name: xkeyvaulttest
spec:
  compositionRef:
    name: xkeyvault
  config:
    environment: Development
    product: xxxxx
    productSubscription: xxxxx
```

I am not able to understand why it not matching.

- Label is set on the EnvironmentConfigs and deployed
- The XR has the expected value 
- The Composition has the selector with the correct label and XR path

### How can we reproduce it?

- Add an environment config with a label
- Add a value to an XR
- Deploy a composition with a FromCompositeFieldPath selector pulling from the above     XR
- Deploy XR

Really puzzled, unless I'm just doing something wrong, which is the most likely scenario!

Thanks.

### What environment did it happen in?
Crossplane version:  0.21.0
