### ISSUE TITLE
Allow installing the same composition function multiple times

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane/crossplane#5263]
### What problem are you facing?

I'm using [function-go-templating](https://github.com/crossplane-contrib/function-go-templating) with Filesystem templates mounted from a configMap. My idea is to have a deploymentRuntimeConfig such as:

```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: tls-certificate-composition
  # DeploymentRuntimeConfig is not namespaced, but this is required by
  # kustomize to properly inject the generated ConfigMap
  namespace: crossplane-system
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            # args:
            # - --debug
            volumeMounts:
            - mountPath: /templates
              name: templates
              readOnly: true
          volumes:
          - name: templates
            projected:
              sources:
              - configMap:
                  name: helpers
              - configMap:
                  name: tls-certificate-composition
```

where the last line will change depending on the composition.

When I apply more than 1 compositions like this (with different values for the mounted per-composition configmap) I get the following error in all my composition functions (note all are affected):

```
❯ kubectl get functions.pkg.crossplane.io
NAME                             INSTALLED   HEALTHY   PACKAGE                                                            AGE
function-auto-ready              True        Unknown   xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1      54m
networking-cluster-provisioner   True        Unknown   xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.4.1   77m
tls-certificate-composition      True        Unknown   xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.4.1   77m

❯ kubectl describe functions.pkg.crossplane.io function-auto-ready | grep -i message
    Message:               cannot resolve package dependencies: cannot initialize dependency graph from the packages in the lock: node xpkg.upbound.io/crossplane-contrib/function-go-templating already exists

❯ kubectl get -oyaml locks.pkg.crossplane.io lock | tail -10
- dependencies: []
  name: networking-cluster-provisioner-eff9a0400879
  source: xpkg.upbound.io/crossplane-contrib/function-go-templating
  type: Function
  version: v0.4.1
- dependencies: []
  name: tls-certificate-composition-eff9a0400879
  source: xpkg.upbound.io/crossplane-contrib/function-go-templating
  type: Function
  version: v0.4.1
```

Which means I cannot have the same composition function installed more than once (with different settings).

### How could Crossplane help solve your problem?

Allow installing the same function more than once (with different configurations)

**Comment by negz** [comment]
It's already possible today to _use_ the same function multiple times. You install it, then "call" (use) it from as many Compositions with as many different inputs as you like.

What's not possible is to _install_ the same function multiple times. It seems like the issue here is to use a filesystem volume of templates you must install N different copies of function-go-templating.

My initial thought is that we should focus on finding alternatives to load templates in function-go-templating, not on trying to make it possible to install a function several different times.

**Comment by haarchri** [comment]
Easy Version: When installing multiple functions today, we encounter an issue:

```
  conditions:
  - lastTransitionTime: "2024-01-25T23:19:13Z"
    message: 'cannot establish control of object: gotemplates.gotemplating.fn.crossplane.io
      is already controlled by FunctionRevision xxx-3ecf6c6da7a0 (UID
      e1913b49-3226-4b2f-89f4-4010b41519ef)'
    reason: UnhealthyPackageRevision
    status: "False"
    type: Healthy
```

The problem arises because the CRD is included in the xpkg package. We have crossplane.yaml in the package folder (https://github.com/crossplane-contrib/function-go-templating/tree/main/package)  and the CRD in a sub-folder. Currently, we don't ignore these CRDs (https://github.com/crossplane-contrib/function-go-templating/blob/main/.github/workflows/ci.yml#L116), leading to their installation in the cluster:

```
kubectl get crds | grep "gotemplates.gotemplating.fn.crossplane.io"
gotemplates.gotemplating.fn.crossplane.io                                  2024-01-26T09:25:55Z
```

To solve this, we can either separate crossplane.yaml into a different folder as shown in https://github.com/crossplane-contrib/function-go-templating/pull/64, or we need to use `--ignore` for the CRD, which is challenging because the CRD names can vary across different folders.
