### ISSUE TITLE
Proposal: Introduction of `skipDependencyResolution` Field for dependsOn in `Configurations`

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#5279]
### What problem are you facing?

This proposal suggests introducing a `skipDependencyResolution` field for the `dependsOn` attribute within configurations. In current practice, dependency resolution can be skipped only at a global configuration level. However, this often does not suffice for the nuanced needs of complex platform projects, especially in large companies where fulfilling all dependencies in a configuration can be challenging (Security, External Registries, same APIs Inhouse with additional features). The proposed feature aims to provide more granular control over dependency resolution within individual configurations.

Many companies, especially those with large platform projects, frequently encounter difficulties in managing dependencies within their configurations. The current approach allows for skipping dependency resolution for the entire configuration, which is often a blunt tool for what requires a more precise solution. https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Configuration/v1@v1.14.5#spec-skipDependencyResolution

### How could Crossplane help solve your problem?

The proposed solution is to introduce a new field, `skipDependencyResolution`, that can be used within the `dependsOn` attribute in configuration. This field would allow platform builders to specify if dependency resolution should be skipped for particular dependencies, rather than applying this skip to the entire configuration.

```
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: test-configuration
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
      version: "v0.5.0"
      skipDependencyResolution: true
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
      version: "v0.5.0"
      skipDependencyResolution: true
    - provider: xpkg.upbound.io/upbound/provider-aws-sqs
      version: "v0.47.1"
    - provider: xpkg.upbound.io/upbound/provider-aws-cloudwatchevents
      version: "v0.47.1"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: "v0.16.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: "v0.10.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: "v0.47.1"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      version: "v0.47.1"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: "v0.47.1"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      version: "v0.2.1"
```

The primary benefit of this feature is the increased control it offers platform builders over their configurations. By allowing dependency resolution to be skipped on a per-dependency basis, teams can manage their configurations more effectively, especially in scenarios where certain dependencies are known to be unnecessary or problematic. This flexibility is particularly valuable in large-scale platform projects where managing a vast number of dependencies can be challenging.

### Implementation Considerations

- This change should be backward compatible, not affecting existing configurations that do not use the new field.
- Care must be taken to ensure that the introduction of this field does not introduce unexpected behavior in dependency resolution in package manager
- Documentation and examples should be updated to reflect this new feature.

**Comment by negz** [comment]
> By allowing dependency resolution to be skipped on a per-dependency basis, teams can manage their configurations more effectively, especially in scenarios where certain dependencies are known to be unnecessary or problematic.

Can you give some examples of a dependency being unnecessary or problematic? If a dependency was unnecessary, wouldn't you just not list it as a dependency of the configuration?

```yaml
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
      version: "v0.5.0"
      skipDependencyResolution: true
```

Does this then become information purely for human consumption? Should I read it as:

* This package depends on `configuration-aws-eks-karpenter`...
* ...but the package manager should ignore this dependency.

If so, I would suggest `skipDependencyResolution` is probably not the most intuitive name for the field in this context.
