### ISSUE TITLE
Proposal: Nest "Crossplane machinery" under `spec.crossplane` and `status.crossplane`

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5288]
### What problem are you facing?

Most people use Crossplane to build platform APIs. Claims are the platform's user-facing APIs. Using an XRD you can design your own claim schema. Ideally the fact that these user-facing platform APIs are powered by Crossplane would be an implementation detail that the platform's users could ignore. [^1]

I think this is weakened by all the "Crossplane machinery" fields that clutter a claim API's top level. At the time of writing Crossplane injects [the following fields](https://github.com/crossplane/crossplane/blob/v1.14.5/internal/xcrd/schemas.go) into every claim:

* `spec.compositionRef`
* `spec.compositionSelector`
* `spec.compositionRevisionRef`
* `spec.compositionRevisionSelector`
* `spec.compositionUpdatePolicy`
* `spec.compositeDeletePolicy`
* `spec.resourceRef`
* `spec.publishConnectionDetailsTo`
* `spec.writeConnectionSecretToRef`
* `status.conditions`
* `status.connectionDetails.lastPublishedTime`

Consider a claim that only has four or five platform-specific fields at the top level. It would be easy for these fields to get lost amidst all the Crossplane machinery. It's also not clear to an uninitiated user which fields are meaningful to them and which fields are Crossplane machinery that they can just ignore.

XRs have a similar problem - they have roughly the same set of machinery fields as claims. It's a little less bad because XRs are not platform-user-facing. We expect that XRs will more often be read by folks familiar with Crossplane. Still, when an XR has a mix of machinery and platform-specific fields at the top level it could be tough for even someone familiar with Crossplane to distinguish them at a glance.

MRs are probably the least bad of all the Crossplane resources that have a mix of Crossplane machinery and platform related fields. An MR has a lot of Crossplane machinery at the top level, but everything specific to the platform is nested under `spec.forProvider` and `status.atProvider`.

A lot of our example XRDs put platform-specific fields under `spec.parameters` by convention. I think this is better than mixing platform-specific fields in with Crossplane machinery at the top-level, but it's backwards. It's the Crossplane machinery that should be nested away, putting the platform-specific fields front and center.

### How could Crossplane help solve your problem?

I think claims and XRs should put platform-specific fields front and center, and "hide" all their Crossplane machinery under top-level fields like `spec.crossplane` and `status.crossplane`.

So instead of:

```yaml
apiVersion: example.org/v1
kind: Widget
metadata:
  namespace: default
  name: my-cool-claim
spec:
  compositionSelector:
    color: purple
  compositionRef:
    name: purple-composition
  compositionRevisionRef:
    name: purple-composition-hashhash
  compositionDeletePolicy: Background
  resourceRef:
    apiVersion: XWidget
    kind: example.org/v1
    name: my-cool-claim-hashash
  size: small
  region: us-east
```

You would have:

```yaml
apiVersion: example.org/v1
kind: Widget
metadata:
  namespace: default
  name: my-cool-claim
spec:
  size: small
  region: us-east
  crossplane:
    compositionSelector:
      color: purple
    compositionRef:
      name: purple-composition
    compositionRevisionRef:
      name: purple-composition-hashhash
    compositionDeletePolicy: Background
    resourceRef:
      apiVersion: XWidget
      kind: example.org/v1
      name: my-cool-claim-hashash
```  

This way you could imagine UIs and tools potentially collapsing all the Crossplane stuff by default.

I think ideally we'd make the same change for MRs for consistency sake. Keep `spec.forProvider` etc, but add `spec.crossplane`.

[^1]: I personally am ambivalent about whether Crossplane should completely "hide how the sausage is made" from platform users. I think in many cases it makes sense to allow them to dig down into XRs and MRs to help diagnose their own issues. Not every platform team is staffed to offer and support completely opaque abstractions to their users ala AWS. Either way, _in the happy path_ it should be possible for a platform user to be completely ignorant of Crossplane.
