### ISSUE TITLE
Crossplane fails to synchronize claims with XRs

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane/crossplane#5400]
### What happened?

From time to time I see that claims and XRs loose sync such as here (see second resource):

```
❯ kubectl get xirsas
NAME                                           API                           SYNCED   READY   COMPOSITION                                         AGE
acm-pca-issuer-nw-eu-west-3-main               infra.nexthink.com/v1alpha3   True     True    custom.policy.xirsas.infra.nexthink.com             9m30s
acm-pca-issuer-nw-us-east-2-main               infra.nexthink.com/v1alpha3                    custom.policy.xirsas.infra.nexthink.com             9m31s
collector-traffic-nw-eu-west-3-main            infra.nexthink.com/v1alpha3   True     True    custom.auth.xirsas.infra.nexthink.com               22h
[...]
```

And this does not change until I do a rollout restart of crossplane deployment. Logs in crossplane deployment look to be on a loop continuously prompting logs such these:

```
crossplane-7c898b5fdf-rf7mg universal-crossplane {"level":"info","ts":"2024-02-16T10:15:46Z","logger":"crossplane","msg":"Enqueueing composite resource because managed resource changed","controller":"defined/compositeresourcedefinition.apiextensions.crossplane.io","request":{"name":"xcertmanagers.infra.nexthink.com"},"uid":"c3eb8136-bcc4-4c98-8832-d782e62cb2b2","version":"168408426","name":"xcertmanagers.infra.nexthink.com","name":"cert-manager-nw-eu-west-3-main","mrGVK":"infra.nexthink.com/v1alpha1, Kind=XAcmPcaIssuer","mrName":"pca-plugin-nw-eu-west-3-main"}
crossplane-7c898b5fdf-rf7mg universal-crossplane {"level":"info","ts":"2024-02-16T10:15:46Z","logger":"crossplane","msg":"Enqueueing composite resource because managed resource changed","controller":"defined/compositeresourcedefinition.apiextensions.crossplane.io","request":{"name":"xcertmanagers.infra.nexthink.com"},"uid":"c3eb8136-bcc4-4c98-8832-d782e62cb2b2","version":"168408426","name":"xcertmanagers.infra.nexthink.com","name":"cert-manager-nw-eu-west-3-main","mrGVK":"infra.nexthink.com/v1alpha1, Kind=XAcmPcaIssuer","mrName":"pca-plugin-nw-eu-west-3-main"}
crossplane-7c898b5fdf-rf7mg universal-crossplane {"level":"info","ts":"2024-02-16T10:15:46Z","logger":"crossplane","msg":"Enqueueing composite resource because managed resource changed","controller":"defined/compositeresourcedefinition.apiextensions.crossplane.io","request":{"name":"xcertmanagers.infra.nexthink.com"},"uid":"c3eb8136-bcc4-4c98-8832-d782e62cb2b2","version":"168408426","name":"xcertmanagers.infra.nexthink.com","name":"cert-manager-nw-eu-west-3-main","mrGVK":"infra.nexthink.com/v1alpha1, Kind=XAcmPcaIssuer","mrName":"pca-plugin-nw-eu-west-3-main"}
crossplane-7c898b5fdf-rf7mg universal-crossplane {"level":"info","ts":"2024-02-16T10:15:46Z","logger":"crossplane","msg":"Enqueueing composite resource because managed resource changed","controller":"defined/compositeresourcedefinition.apiextensions.crossplane.io","request":{"name":"xcertmanagers.infra.nexthink.com"},"uid":"c3eb8136-bcc4-4c98-8832-d782e62cb2b2","version":"168408426","name":"xcertmanagers.infra.nexthink.com","name":"cert-manager-nw-eu-west-3-main","mrGVK":"infra.nexthink.com/v1alpha1, Kind=XAcmPcaIssuer","mrName":"pca-plugin-nw-eu-west-3-main"}
```

### What environment did it happen in?
Crossplane version: universal-crossplane-1.14.5-up.1

EKS v1.27.9-eks-5e0fdde

## Relevant PRs

* https://github.com/crossplane/crossplane/pull/5422
* https://github.com/crossplane/crossplane/pull/5437
* https://github.com/crossplane/crossplane/pull/5468

**Comment by fernandezcuesta** [comment]
As suggested by @haarchri I set `--enable-composition-webhook-schema-validation=false` but unfortunately didn't help.

**Comment by haarchri** [comment]
do you using real-time compositions ?

**Comment by fernandezcuesta** [comment]
looks like:

```
      containers:
      - args:
        - core
        - start
        - --enable-composition-functions
        - --enable-environment-configs
        - --enable-realtime-compositions
        - --enable-usages
        - --enable-composition-webhook-schema-validation=false
```

**Comment by haarchri** [comment]
think its related to: https://github.com/crossplane/crossplane/issues/5151

**Comment by jbw976** [comment]
@haarchri were you able to confirm positively that this behavior is related to realtime compositions? i.e. it only manifests when `--enable-realtime-compositions` is set? 🤔

**Comment by haarchri** [comment]
Yes and i can reproduce this issue with enabled Realtime compositions - currently debugging it

**Comment by jbw976** [comment]
Awesome dude! thanks for confirming - tracking this as part of the maturing realtime compositions epic:

* https://github.com/crossplane/crossplane/issues/4828

**Comment by haarchri** [comment]
```
NAME                          SYNCED   READY   COMPOSITION                                             AGE
realtime-composition1-dshdn   True     True    xnopresources.realtime-compositions.e2e.crossplane.io   45s
realtime-composition2-4pbd5   True     True    xnopresources.realtime-compositions.e2e.crossplane.io   45s
realtime-composition3-r8zbk   True     True    xnopresources.realtime-compositions.e2e.crossplane.io   44s
realtime-composition4-58f9w                                                                            14s
realtime-composition5-9p5cn                                                                            14s
realtime-composition6-vnsgs                                                                            14s
```

problem starts around here: https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/definition/reconciler.go#L474 

and then we hit the following:
https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/composite/reconciler.go#L712

**Comment by haarchri** [comment]
think we can hit this issue also without real-time compositions - here is no feature flag block around https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/definition/reconciler.go#L475-L481

**Comment by jbw976** [comment]
> think we can hit this issue also without real-time compositions

So we do think this is something that is hitting mainstream scenarios in v1.15? Is there reason to believe that we should backport any of these PRs for a v1.15 patch release?

* https://github.com/crossplane/crossplane/pull/5437
* https://github.com/crossplane/crossplane/pull/5422

/cc @haarchri @sttts @phisco

**Comment by haarchri** [comment]
To replicate the issue, first install Crossplane version 1.15.0 and run with `--enable-realtime-compositions` 
Then, follow these steps:

```
kubectl apply -f test/e2e/manifests/apiextensions/composition/realtime-compositions/setup
```

```
for i in {1..3}; do
  kubectl apply -f - <<EOF
apiVersion: realtime-compositions.e2e.crossplane.io/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: realtime-composition$i
  labels:
    realtime-compositions: "true"
spec:
  coolField: "I'm cool!"
  compositeDeletePolicy: Foreground
EOF
done
```

Wait all Claim, XR and managed resources ready
Stop crossplane

Start crossplane
```
for i in {1..6}; do
  kubectl apply -f - <<EOF
apiVersion: realtime-compositions.e2e.crossplane.io/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: realtime-composition$i
  labels:
    realtime-compositions: "true"
spec:
  coolField: "I'm cool!"
  compositeDeletePolicy: Foreground
EOF
done
```

If the issue doesn't occur, restart Crossplane and create more claims than you did previously. You will then observe the error "cannot list in CompositionRevision handler" in the logs.

**Comment by haarchri** [comment]
i did a long debug session with @sttts and i cannot reproduce the issue based on this PR https://github.com/crossplane/crossplane/pull/5422 - so i have a good feeling that we fixed the issue

**Comment by stevendborrelli** [comment]
I can confirm that this issue exists in 1.17.  Enabling realtime compositions causes Composite selection to hang. As soon as I disable the feature, the composite resources are created.

```yaml
   spec:
      containers:
        - args:
            - core
            - start
            - --enable-realtime-compositions
```


```
kubectl get composite 
NAME                        SYNCED   READY   COMPOSITION   AGE
configuration-aws-network                                  2m9s
```

**Comment by negz** [comment]
> Enabling realtime compositions causes Composite selection to hang

@stevendborrelli do you mean composition selection? i.e. The XR never selects a composition?

Are you able to reproduce this reliably? I can't reproduce it using [these manifests]( https://github.com/crossplane/crossplane/tree/b0cc38c104eb4f776a9ec3b7a131e457ea529372/test/e2e/manifests/apiextensions/composition/realtime-compositions).

**Comment by stevendborrelli** [comment]
@negz yes, I can reproduce it:

add `- --enable-realtime-compositions` to crossplane deployment args


Install configuration-aws-network from the marketplace: https://marketplace.upbound.io/configurations/upbound/configuration-aws-network/v0.24.0 

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-aws-network
spec:
  package: xpkg.upbound.io/upbound/configuration-aws-network:v0.24.0
```


Apply a sample XR: https://github.com/upbound/configuration-aws-network/blob/main/examples/xnetworks/configuration-aws-network.yaml:

```yaml
apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: configuration-aws-network
spec:
  parameters:
    id: configuration-aws-network
    region: us-west-2
    vpcCidrBlock: 192.168.0.0/16
    subnets:
      - availabilityZone: us-west-2a
        type: public
        cidrBlock: 192.168.0.0/18
      - availabilityZone: us-west-2b
        type: public
        cidrBlock: 192.168.64.0/18
      - availabilityZone: us-west-2a
        type: private
        cidrBlock: 192.168.128.0/18
      - availabilityZone: us-west-2b
        type: private
        cidrBlock: 192.168.192.0/18

```

The composite will not have any events on it:

```shell
$ kubectl get composite 
NAME                                                         SYNCED   READY   COMPOSITION   AGE
xnetwork.aws.platform.upbound.io/configuration-aws-network                                  16s
```

```shell
$ kubectl describe xnetwork.aws.platform.upbound.io/configuration-aws-network 
Name:         configuration-aws-network
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  aws.platform.upbound.io/v1alpha1
Kind:         XNetwork
Metadata:
  Creation Timestamp:  2025-04-23T13:40:10Z
  Generation:          1
  Resource Version:    2135594
  UID:                 0a1886dc-39ac-4206-a3f1-875eaf6e1935
Spec:
  Composition Update Policy:  Automatic
  Parameters:
    Deletion Policy:       Delete
    Id:                    configuration-aws-network
    Provider Config Name:  default
    Region:                us-west-2
    Subnets:
      Availability Zone:  us-west-2a
      Cidr Block:         192.168.0.0/18
      Type:               public
      Availability Zone:  us-west-2b
      Cidr Block:         192.168.64.0/18
      Type:               public
      Availability Zone:  us-west-2a
      Cidr Block:         192.168.128.0/18
      Type:               private
      Availability Zone:  us-west-2b
      Cidr Block:         192.168.192.0/18
      Type:               private
    Vpc Cidr Block:       192.168.0.0/16
Events:                   <none>
```
