### ISSUE TITLE
Function spec.package does not use cluster local image cache

### ISSUE THREAD

**Issue by smoehrle** [crossplane/crossplane#5404]
### What happened?
I was playing around with crossplane functions when I stumbled across the following issue. Installed functions do not use the local container image cache and also do not honor local registry settings.

Heres what I did:
- Write a demo function [based on the docu](https://docs.crossplane.io/latest/concepts/composition-functions/#write-a-composition-function])
- Load it into my local cluster 
- Try to install the function
    - Expectation: the function is installed and running because the default pull policy is "IfNotPresent"
    - Actual: Does not work because crossplane tries to make calls to the registry which fail
- In a second attempt I set up a [kind local registry](https://kind.sigs.k8s.io/docs/user/local-registry/). I verified the registry with `docker exec kind-worker crictl pull localhost:5000/function-demo:v0.1.0`. I could access and pull from the registry. 
- Crossplane was still not able to install the function.

### How can we reproduce it?
- Setup kind-cluster
- Install crossplane
- Build and load function image into kind:
    ```
    crossplane xpkg build --package-root=package --embed-runtime-image=${runtime} --package-file=function-amd64.xpkg
    output=$(docker load -i function-amd64.xpkg)
    sha_value=$(echo "$output" | grep -oP 'sha256:\K[a-f0-9]{64}')
    docker tag $sha_value localhost:5000/function-demo:v0.1.0
    kind load docker-image localhost:5000/function-demo:v0.1.0
    ```
- Try to load function:
    ```
    apiVersion: pkg.crossplane.io/v1beta1
    kind: Function
    metadata:
      name: function-xusers
    spec:
      # IfNotPresent is also the default
      packagePullPolicy: IfNotPresent
      package: localhost:5000/function-demo:v0.1.0
    ```
- Function will not be installed due to failing requests to the registry even though the image is present

### What environment did it happen in?
Crossplane version: 1.15.0
Kubernetes version: Client Version: v1.29.2; Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3; Server Version: v1.29.2
kind version 0.22.0
