### ISSUE TITLE
spec.initProvider: field not declared in schema error after switching Composition to Pipeline mode (Patch and Transform)

### ISSUE THREAD

**Issue by mlubanski** [crossplane/crossplane#5418]
### What happened?

I upgraded crossplane to `1.15` (from `1.14.x`)
I transformed Composition to use patch-and-transform functions via `crossplane beta convert pipeline-composition`

In Composition I am setting on `RDSInstance` patch `toFieldPath: spec.initProvider.engineVersion`

Before upgrading crossplane and changing composition to Pipeline mode (Patch And Transform) everything was working as expected, after above operations I am getting below error

```
Warning  ComposeResources  110s (x7644 over 16h)  defined/compositeresourcedefinition.apiextensions.crosspla │
│ ne.io  (combined from similar events): cannot compose resources: cannot apply composed resource "rds": failed  │
│ to create typed patch object (/mysql-1-dxkpn-c78xt; database.aws.crossplane.io/v1beta1, Kind=RDSInstance): .sp │
│ ec.initProvider: field not declared in schema
```

Expected behaviour: 
After switching Composition to Pipeline mode setting `ManagedResource` properties via `spec.initProvider` should work

### How can we reproduce it?

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xmysqlinstances.rds.aws.crossplane.sinch.com
  name: mysqlinstances.rds.aws.crossplane.sinch.com-v1alpha1
spec:
  compositeTypeRef:
    apiVersion: rds.aws.crossplane.sinch.com/v1alpha1
    kind: XMySQLInstance
  environment:
    environmentConfigs:
    - ref:
        name: mysqlinstance
      type: Reference
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      environment: null
      kind: Resources
      patchSets: []
      resources:
      - base:
          apiVersion: database.aws.crossplane.io/v1beta1
          kind: RDSInstance
          spec:
            forProvider:
              caCertificateIdentifier: rds-ca-rsa2048-g1
              engine: mysql
              masterUsername: root
              publiclyAccessible: false
            managementPolicies:
            - '*'
            providerConfigRef:
              name: crossplane-provider-aws
            publishConnectionDetailsTo:
              configRef:
                name: default
        name: rds
        patches:
        - fromFieldPath: spec.parameters.majorEngineVersion
          toFieldPath: spec.initProvider.engineVersion
          transforms:
          - map:
              "5.7": 5.7.42
              "8.0": 8.0.33
            type: map
          type: FromCompositeFieldPath
    ....
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmysqlinstances.rds.aws.crossplane.sinch.com
spec:
  group: rds.aws.crossplane.sinch.com
  claimNames:
    kind: MySQLInstance
    plural: mysqlinstances
  names:
    kind: XMySQLInstance
    plural: xmysqlinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: (Required)
                properties:
                  majorEngineVersion:
                    type: string
                    description: |
                      Major engine version (e.g. 5.7, 8.0) based on which recommended engineVersion is defined by Operations
                      in Composition Default value: 8.0"
                    default: "8.0"
                    enum: ["5.7", "8.0"]  
```

### What environment did it happen in?

crossplane: `v1.15.0`
aws-provider: `crossplane-contrib/provider-aws:v0.46.0`
kubernetes: `1.26.x`
Kubernetes distribution: `local/kind`
