### ISSUE TITLE
`beta convert pipeline-composition` doesn't handle `mergeOptions`

### ISSUE THREAD

**Issue by mlubanski** [crossplane/crossplane#5421]
### What happened?

I upgraded crossplane to `1.15` (from `1.14.x`)
I transformed Composition to use patch-and-transform functions via `crossplane beta convert pipeline-composition`

In Composition I am trying to append list of strings to  

```
        # adding ns specific SG which allow connectivity to app from DataCenter or AWS EC2 Instance
        - fromFieldPath: metadata.annotations[mysqlinstance.crossplane.sinch.com/namespaceSG]
          policy:
            mergeOptions:
              appendSlice: true
          toFieldPath: spec.forProvider.vpcSecurityGroupIds[0]
          type: FromCompositeFieldPath
         # adding environment specific SG (e.g. which allow connectivity from BastionHost)
        - fromFieldPath: mysqlinstance.envConfig.additionalSecurityGroups
          policy:
            mergeOptions:
              appendSlice: true
          toFieldPath: spec.forProvider.vpcSecurityGroupIds
          type: FromEnvironmentFieldPath
```

Before upgrading crossplane and changing composition to Pipeline mode (Patch And Transform) everything was working as expected, after above operations second patch is overriding first element in an array set by previous patch

Expected behaviour: 
It should append to the existing list new values (instead replacing previous elements)

### How can we reproduce it?

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xmysqlinstances.rds.aws.crossplane.sinch.com
  name: mysqlinstances.rds.aws.crossplane.sinch.com-v1alpha1
spec:
  compositeTypeRef:
    apiVersion: rds.aws.crossplane.sinch.com/v1alpha1
    kind: XMySQLInstance
  environment:
    environmentConfigs:
    - ref:
        name: mysqlinstance
      type: Reference
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      environment: null
      kind: Resources
      patchSets: []
      resources:
      - base:
          apiVersion: database.aws.crossplane.io/v1beta1
          kind: RDSInstance
          spec:
            forProvider:
              caCertificateIdentifier: rds-ca-rsa2048-g1
              engine: mysql
              masterUsername: root
              publiclyAccessible: false
            managementPolicies:
            - '*'
            providerConfigRef:
              name: crossplane-provider-aws
            publishConnectionDetailsTo:
              configRef:
                name: default
        name: rds
        patches:
        # adding ns specific SG which allow connectivity to app from DataCenter or AWS EC2 Instance
        - fromFieldPath: metadata.annotations[mysqlinstance.crossplane.sinch.com/namespaceSG]
          policy:
            mergeOptions:
              appendSlice: true
          toFieldPath: spec.forProvider.vpcSecurityGroupIds[0]
          type: FromCompositeFieldPath
        # adding environment specific SG (e.g. which allow connectivity from BastionHost)
        - fromFieldPath: mysqlinstance.envConfig.additionalSecurityGroups
          policy:
            mergeOptions:
              appendSlice: true
          toFieldPath: spec.forProvider.vpcSecurityGroupIds
          type: FromEnvironmentFieldPath
    ....
---
apiVersion: apiextensions.crossplane.io/v1alpha1
data:
  mysqlinstance:
    envConfig:
      additionalSecurityGroups:
      - sg-06d7ecbe89aabc75a
      - sg-048580a25883584ad
kind: EnvironmentConfig
metadata:
  name: mysqlinstance
---
apiVersion: rds.aws.crossplane.sinch.com/v1alpha1
kind: MySQLInstance
metadata:
  annotations:
    mysqlinstance.crossplane.sinch.com/namespaceSG: sg-xxx
  name: mysql-7
  namespace: ns-with-custom-sg
spec:
  parameters: {}
```

### What environment did it happen in?

crossplane: `v1.15.0`
aws-provider: `crossplane-contrib/provider-aws:v0.46.0`
kubernetes: `1.26.x`
Kubernetes distribution: `local/kind`
