### ISSUE TITLE
Multiple claims on a single composite resource

### ISSUE THREAD

**Issue by danielloader** [crossplane/crossplane#5423]
### What happened?

I've been reading around and I've been unsure if this a bug or intentional, it's not documented clearly anywhere so tentatively raising it as a bug report.

Sources:
- https://github.com/crossplane/crossplane/issues/4277#issuecomment-1653714961
- https://docs.crossplane.io/latest/concepts/claims/#claiming-existing-composite-resources

#### Summary

I'm unable to make multiple claims on the same CompositeResource object, whichever Claim object grabs it first wins.

#### Details

I've managed a single XRC claiming a single XR and that works well, but if I add a second XRC it complains (and rightly) that the XR already has a claim on it, which if you check the XR object both of these labels get populated to identify the claimant object.

- `crossplane.io/claim-name`
- `crossplane.io/claim-namespace`

This all looks intentional, but I'm wondering if I'm just missing something to allow multiple claims to reference the same composite resource?

It would be very useful to be able to provision some big time consuming infrastructure at the cluster level via XRs (think RDS), or even quick resources you might want to share cluster wide (think S3 buckets). 

It'll be good to just get clarification on what the intended design and implementation is here. 

Claims aren't nearly as valuable if you're forced into a 1:1 relationship between claims and composite resources and they just act as a glorified secrets reflector (for a single claim/namespace).

### How can we reproduce it?

Create a `Composition` and `CompositeResourceDefinition`, then create a `CompositeResource` and try to make multiple claims using the `spec.resourceRef` capabilities to nominate an existing composite resource.

### What environment did it happen in?
Crossplane version: 1.15
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0-eks-c417bb3
MacOS 14.2.1

**Comment by bobh66** [comment]
Claim-Composite is a 1-to-1 relationship today.  What is the scenario that you are thinking about to make multiple claims point at a single composite?

**Comment by bobh66** [comment]
I think you might be able to do something like this using `EnvironmentConfig` - create your "infra" composite so that it creates an `EnvironmentConfig` resource and publishes the name/namespace of it's Connection Secret to the `EnvironmentConfig`.  Then in your "consumer" composite(s) select that `EnvironmentConfig` by name or labels, retrieve the ConnectionSecret information using an Observe-only provider-kubernetes `Object`, and create a new Secret in the target namespace using a second provider-kubernetes `Object`.

Another option would be to use a Composition Function with the new "resource retrieval" functionality - the consuming Composite would need to know the name of the infra Composite, but then the Composition Function could request that Crossplane retrieve the infra composite and it's connection secret and then publish that into a Secret using the `Object`.

**Comment by danielloader** [comment]
These are some interesting ideas, and possibly worth pursuing - the first one I can effectively do with kyverno using the generation functionality and sync the secrets I guess - but it's nice to know a native crossplane solution.

The second option is interesting, is there a function already that operates like a Terraform Data source object to do cross composition lookups, because as you say just reaching into a composite resource and grabbing some fields to use in a new composition would be extremely powerful and be somewhat of a general purpose solution for any of these problems.

For example - I could populate the EKS cluster with an observe only EKS cluster resource (as part of a composition) that I could reference fields from the status - AWS region, VPC ID etc. 

Currently I can only reference a cluster like that in MRs that support a clusterNameRef type field (see PodIdentityAssociation), and only then it's getting just the name (raised an issue [here](https://github.com/upbound/provider-aws/issues/1168)).

I think the pattern of being able to reach into existing composite resources, and access the fields on the underlying managed resources would be extremely useful.

I could for example:

- Provision an S3 bucket at the cluster level as a cluster admin.
- Via a second composite resource, carve out a prefix from that bucket by name, create the associated IAM policy/role, and attach a PodIdentityAssociation resource so pods can use that prefix scoped access.

Currently it's proving really difficult to slice and dice up a bucket so namespace/service account scoped PodIdentityAssociation objects can dish out those permissions to pods.

So much so up until you replied I was just going to suck up s3 buckets per claim (per application per namespace) simply because cohabitating was so difficult.

**Comment by danielloader** [comment]
That's true, though I'm more concerned with AWS quotas (albeit a soft limit) on buckets (100 per account) - and I'm building a SaaS product which might end up with (hopefully) many more than 100 accounts.

I was already using the EnvironmentConfig to pass through some things between compositions, to the `function-go-templating` function - namely the AWS_REGION and EKS_CLUSTER_NAME which were handy in other compositions.

Just so I'm clarifying, the second option above talked about "extra resources" functionality. Is that part of the `function-environment-config` function, or is that yet to be implemented?

The example in the design doc [here](https://github.com/crossplane/crossplane/blob/master/design/design-doc-composition-functions-extra-resources.md#q6-how-can-composition-authors-specify-what-resources-functions-can-request) looks promising but it seemed to have been descoped for now?

Likewise this syntax is promising.

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: nop.sqlinstances.example.org
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XSQLInstance
  mode: Pipeline
  pipeline:
  - name: envconfigs
    functionRef:
      name: function-environment-configs
    input:
      apiVersion: extra.fn.crossplane.io/v1beta1
      kind: ExtraResourceSelectors
      extraResourceSelectors:
        environmentConfigs:
        - ref:
            name: example-environment-1
        - type: Selector
          selector:
            mode: Multiple
            sortByFieldPath: data.priority
            matchLabels:
              - type: FromCompositeFieldPath
                key: stage
                valueFromFieldPath: metadata.labels[stage]
  - name: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: nop
          base:
            apiVersion: nop.crossplane.io/v1alpha1
            kind: NopResource
            spec:
              forProvider:
                conditionAfter:
                  - conditionType: Ready
                    conditionStatus: "False"
                    time: 0s
                  - conditionType: Ready
                    conditionStatus: "True"
                    time: 1s
          patches:
            - type: FromEnvironmentFieldPath
              fromFieldPath: complex.c.f
              toFieldPath: metadata.annotations[valueFromEnv]
```

I appreciate this is timely and cutting edge so the implementations and documentation is new and rough, but getting to grip with what is and isn't available in this respect - and by this I explicitly mean the capacity to lookup external resources and then interact with them in the next pipeline step as if they were part of the composition.
