### ISSUE TITLE
Functions can't modify XR `metadata` or `spec`

### ISSUE THREAD

**Issue by mlubanski** [crossplane/crossplane#5434]
### What happened?
I upgraded crossplane to `1.15` (from `1.14.x`)
I transformed Composition to use patch-and-transform functions via `crossplane beta convert pipeline-composition`

In Composition I am trying to set an annotation on CompositeResource based on ManagedResource status
```yaml
...
        - fromFieldPath: status.atProvider.securityGroupID
          toFieldPath: metadata.annotations[mysqlinstance.crossplane.sinch.com/sg]
          type: ToCompositeFieldPath
```

ManagedResource and CompositeResource are healthy but annotation was not added

Before upgrading crossplane and changing composition to Pipeline mode (Patch And Transform) everything was working as expected, after above operations annotation is not added to CompositeResource anymore

Expected behaviour: 
`mysqlinstance.crossplane.sinch.com/sg` annotation on CompositeResource should be added

### How can we reproduce it?

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  creationTimestamp: "2024-02-21T14:33:56Z"
  labels:
    crossplane.io/xrd: xmysqlinstances.rds.aws.crossplane.sinch.com
  name: mysqlinstances.rds.aws.crossplane.sinch.com-v1alpha1
spec:
  compositeTypeRef:
    apiVersion: rds.aws.crossplane.sinch.com/v1alpha1
    kind: XMySQLInstance
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  mode: Pipeline
  pipeline:  
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      environment: null
      kind: Resources
      patchSets: []
      resources:
      - base:
          apiVersion: ec2.aws.crossplane.io/v1beta1
          kind: SecurityGroup
          spec:
            forProvider:
              description: Security group for database
              egress:
              - fromPort: -1
                ipProtocol: "-1"
                ipRanges:
                - cidrIp: 0.0.0.0/0
                toPort: -1
              ingress:
              - fromPort: 3306
                ipProtocol: tcp
                toPort: 3306
                userIdGroupPairs:
                - description: Access from the k8s cluster
            providerConfigRef:
              name: crossplane-provider-aws
        name: securitygroup
        patches:
        - fromFieldPath: metadata.annotations[core.crossplane.sinch.com/awsClusterSecurityGroup]
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.ingress[0].userIdGroupPairs[0].groupId
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.annotations[core.crossplane.sinch.com/awsRegion]
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.annotations[core.crossplane.sinch.com/awsVpcId]
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.vpcId
          type: FromCompositeFieldPath
        - fromFieldPath: status.atProvider.securityGroupID
          toFieldPath: metadata.annotations[mysqlinstance.crossplane.sinch.com/sg]
          type: ToCompositeFieldPath
```

### What environment did it happen in?
Crossplane version: 

crossplane: `v1.15.0`
aws-provider: `crossplane-contrib/provider-aws:v0.46.0`
kubernetes: `1.26.x`
patch-and-transform function: `xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.0.0-20240222194345-0193c1d1fc74`
Kubernetes distribution: `local/kind`

**Comment by bobh66** [comment]
I think this is related to this thread in Slack:  https://crossplane.slack.com/archives/CEG3T90A1/p1708724436065099

It seems like missing functionality to me - if we want Function P&T to be equivalent to P&T then we need to support altering the `composite.metadata` from functions.  The next question becomes do we support altering all of `metadata` like we do today in traditional P&T or do we restrict it to `annotations`, which I think would cover most cases.  @negz @phisco ?

**Comment by bobh66** [comment]
https://github.com/crossplane/crossplane/blob/3eee5e824bb25256beb38d86a7cd970f94e3d3d2/internal/controller/apiextensions/composite/composition_functions.go#L477

**Comment by bobh66** [comment]
I don't see anything in #4581 that would allow functions to modify composite `metadata.annotations` - it only references claim/composite annotation handling.

Storing data in the composite `metadata.annotations` is a widespread pattern in traditional patch and transform.

If functions are not allowed to mutate the composite `metadata.anntotations` then many existing P&T compositions cannot be migrated to functions without considerable rework of both the composite definition and the composition patches.

I think it's important to preserve existing P&T functionality to ease the transition to functions, so it makes sense to allow functions to mutate the composite `metadata.annotations`.

**Comment by mlubanski** [comment]
Hey @negz , yes we are using it as a storage in order to patch composed resources (passing one resource status field as an input to another resource)

I just tried use environments (together with `function-path-and-transform`) and it is not working either

in `SecurityGroup` resource I have below patch:

```yaml
        - fromFieldPath: status.atProvider.securityGroupID
          toFieldPath: status_securityGroup_Id
          type: ToEnvironmentFieldPath
```

than on `RDSInstance` I would like to use that SG:

```yaml
        - fromFieldPath: status_securityGroup_Id
          toFieldPath: spec.forProvider.vpcSecurityGroupIds[0]
          type: FromEnvironmentFieldPath
```

Than I am getting below error:
```
│   Warning  ComposeResources         2m54s (x3 over 2m57s)  defined/compositeresourcedefinition.apiextensions.crossp │
│ lane.io  cannot compose resources: cannot apply composed resource "rds": failed to create typed patch object (/mysq │
│ l-1-8zzjw-6zw4m; rds.aws.upbound.io/v1beta2, Kind=Instance): .spec.forProvider.vpcSecurityGroupIds: element 0: asso │
│ ciative list without keys has an element that's an explicit null
```
setting `policy.toFieldPath: Optional` didn't help

I could try to store it instead in CompositeResource.status property but it requires more efford and I would need to add this property to XRD which doesn't seem to me a good option as I don't want to expose it to the Claim as this is strictly internal configuration users shouldn't be aware of

I would be happy to use EnvironmentConfig if above case would work and if visibility/debugging goanna be improved (e.g. with old approach I could see if annotation was added, today with EnvironmentConfig it is stored in-memory so it is hard to investigate if things get's wrong)

Please let me know what is your recommendation we should follow

**Comment by bobh66** [comment]
> Storage to patch data between composed resources (without using the alpha environment)

I assume this is the major scenario especially since this is how the examples in the documentation are written.

I wonder if it's not actually a problem though _within_ function-patch-and-transform and it's only a problem when the data is needed outside of the function?  As long as the function executes the patches properly on every reconciliation, the internal copy of `observed.composite.resource.metadata.annotations` would be updated appropriately, making the data available to any `FromCompositeFieldPath` patches that reference it.  The annotations would not be stored in the composite, but since they are reconstructed on every reconciliation it should still "work".  The one remaining downside is that it makes debugging harder because it's not possible to examine the function-patch-and-transform stored state, the way it is in traditional P&T.  So if the user is relying on the composite annotations being updated, it's a reversion from traditional P&T, but it might not affect the results of the P&T sequences.

**Comment by negz** [comment]
```
cannot apply composed resource "rds": failed to create typed patch object (/mysq │
│ l-1-8zzjw-6zw4m; rds.aws.upbound.io/v1beta2, Kind=Instance): .spec.forProvider.vpcSecurityGroupIds: element 0: asso │
│ ciative list without keys has an element that's an explicit null
```

This error looks like it's coming from the Kubernetes API server. I haven't seen it before, but my _guess_ is that at some point during the composition process:

1. `status_securityGroup_Id` isn't yet populated in the environment.
2. The `FromEnvironmentFieldPath` is returning `null`

Resulting in us trying to server-side apply an invalid resource, like:

```yaml
spec:
  forProvider:
    vpcSecurityGroupIds:
    - null
```


This seems like it could be a bug somewhere - in `FromEnvironmentFieldPath`? An optional patch from a field path that doesn't exist should be skipped, not return a null value.
