### ISSUE TITLE
Compositions Prune Unknown Fields

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/crossplane#5440]
### What happened?

When compositions applies/renders manifests, unknown fields are pruned. If the user would try to apply the same manifest to the cluster manually, it would be rejected by the API server. 

For example the AWS [SecurityGroup](https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.1.0/resources/ec2.aws.upbound.io/SecurityGroup/v1beta1) does not support `ingress` and `egress` fields:

```yaml
spec:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        metadata:
          labels:
            name: uxp-prod-sg
          forProvider:
            region: us-west-1
            groupName: "uxp-prod-sg"
            description: "uxp-prod-sg"
            ingress:
              - fromPort: 80
                toPort: 80
                ipProtocol: "tcp"
                cidrBlocks:
                  - "0.0.0.0/0"
            egress:
              - fromPort: 0
                toPort: 0
                ipProtocol: "-1"
                cidrBlocks:
                  - "0.0.0.0/0"
            vpcIdSelector:
              matchControllerRef: true
```

The generated composition (which provisions successfully) does not have the fields present: 

```yaml
spec:
  deletionPolicy: Delete
  forProvider:
    description: uxp-prod-sg
    region: us-west-1
    tags:
      crossplane-kind: securitygroup.ec2.aws.upbound.io
      crossplane-name: borrelli-test-h6n6s
      crossplane-providerconfig: default
    vpcId: vpc-0312d549ce7d9392c
    vpcIdRef:
      name: borrelli-test-mqmnz
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
```

### How can we reproduce it?

<details>
<summary>Composition</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositeec2instances.aws.test.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: aws.test.org/v1alpha1
    kind: CompositeEC2Instance
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        metadata:
        spec:
          forProvider:
            region: us-west-1
            cidrBlock: 172.16.0.0/16
            tags:
              Name: FieldTestVPC
          providerConfigRef:
            name: default
    - name: subnet
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            region: us-west-1
            availabilityZone: us-west-1b
            vpcIdSelector:
              matchControllerRef: true
            cidrBlock: 172.16.10.0/24
    - name: ec2securitygroup
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        metadata:
          labels:
            name: uxp-prod-sg
        spec:
          forProvider:
            region: us-west-1
            groupName: "uxp-prod-sg"
            description: "uxp-prod-sg"
            ingress:
              - fromPort: 80
                toPort: 80
                ipProtocol: "tcp"
                cidrBlocks:
                  - "0.0.0.0/0"
            egress:
              - fromPort: 0
                toPort: 0
                ipProtocol: "-1"
                cidrBlocks:
                  - "0.0.0.0/0"
            vpcIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
    - name: ec2instance
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            instanceType: t2.micro
            region: us-west-1
            ami: ami-0c02fb55956c7d316 # Example AMI for Amazon Linux 2 in us-east-1
            subnetIdSelector:
              matchControllerRef: true
            keyName: ""
            securityGroupsSelector:
              matchControllerRef: true 
            rootBlockDevice:
              - encrypted: true # Enable by default
            vpcSecurityGroupIdSelector:
              matchControllerRef: true
              matchLabels:
                name: uxp-prod-sg
              policy:
                resolution: Required
                resolve: Always  
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.parameters.size"
          toFieldPath: "spec.forProvider.instanceType"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.ami"
          toFieldPath: "spec.forProvider.ami"
        - fromFieldPath: "spec.parameters.keyName"
          toFieldPath: "spec.forProvider.keyName"
```
</details>
<details>
<summary>XRD</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeec2instances.aws.test.org
spec:
  group: aws.test.org
  names:
    kind: CompositeEC2Instance
    plural: compositeec2instances
  claimNames:
    kind: EC2Instance
    plural: ec2instances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  size:
                    type: string
                    enum: ["t2.micro", "t2.small", "t2.medium"]
                  region:
                    type: string
                  ami:
                    type: string
                  keyName:
                    type: string
            required: ["parameters"]
```

</details>

<details>
<summary>XR</summary>

```yaml
apiVersion: aws.test.org/v1alpha1
kind: CompositeEC2Instance
metadata:
  name: borrelli-test
spec:
  parameters:
    ami: ami-03c951bbe993ea087
    keyName: test
    region: us-west-1
    size: t2.micro
```

</details>

### What environment did it happen in?

* Crossplane 1.13.2 and 1.14.5
* Official provider-aws 1.1.0
* Cloud provider or hardware configuration: kind
* Kubernetes version (use `kubectl version`): 1.27
