### ISSUE TITLE
Avoid validating templates in DeploymentRuntimeConfig for required fields

### ISSUE THREAD

**Issue by cristicalin** [crossplane/crossplane#5442]
### What problem are you facing?

I need to deploy my crossplane control plane, providers and functions on a specific subset of nodes. For this I need to be able to set `toleration` and `nodeSelector` fields of the deployment. This could have been done with `ControllerConfig` for providers previously but with the `DeploymentRuntimeConfig` I cannot just override the fields I need, crossplane is asking for additional details like `selector` and `containers` which would be difficult to keep in sync with the evolution of providers and functions across releases.

My example `DeploymentRuntimeConfig`:

```yaml
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-40'
  name: {{ $functionName }}-config
spec:
  deploymentTemplate:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: {{ $.Release.Name }}:apps/Deployment/{{ $functionName }}
    spec:
      template:
        spec:
          nodeSelector:
            NodePurpose: system
          securityContext:
            fsGroup: 2000
          tolerations:
            - effect: NoSchedule
              key: NodePurpose
              operator: Equal
              value: system
            - effect: NoSchedule
              key: CriticalAddonsOnly
              operator: Exists
```

This results in an error when applied:

```
DeploymentRuntimeConfig.pkg.crossplane.io "function-auto-ready-config" is invalid: [spec.deploymentTemplate.spec.template.spec.containers: Required value, spec.deploymentTemplate.spec.selector: Required value]
```

Looking at the definition of the `deploymentTemplate` it seems to have e been copied from kubernetes deployment including the mandatory fields which makes the `container` and `selector` fields mandatory even though it's not what I need to override: https://docs.crossplane.io/v1.15/api/#DeploymentRuntimeConfig-spec-deploymentTemplate-spec-template-spec-containers

### How could Crossplane help solve your problem?

Please make the behaviour of the `deploymentTemplate`, `serviceAccountTemplate` and `serviceTemplate` to be a mergeOverwrite on top of the base kubernetes objects rather than a replacement of the objects that would otherwise be created by default and make all fields optional so we can override just what we need from those objects.

Looking at the code: https://github.com/crossplane/crossplane/blob/master/apis/pkg/v1beta1/deployment_runtime_config_types.go, it seems that crossplane is directly importing `k8s.io/api/apps/v1` this means that crossplane brings in any mandatory field requirements and the behaviour is full overwrite: https://github.com/crossplane/crossplane/blob/master/internal/controller/pkg/revision/runtime_defaults.go#L43C1-L63C1

It would be nicer to have some import mechanism that makes all the fields optional and then do a more controlled merge of the options so we have granular control of how the components are deployed.
