### ISSUE TITLE
Set ownerReferences on CRDs created by crossplane-init container

### ISSUE THREAD

**Issue by morey-tech** [crossplane/crossplane#5446]
### What problem are you facing?

The crossplane-init container installs the Crossplane Custom Resource Definitions into the Kubernetes cluster. When managing Crossplane with GitOps, this pattern makes it difficult to track the CRD resources as a part of the deployment. They get created in the cluster but can't be linked back to the crossplane deployment.

### How could Crossplane help solve your problem?

GitOps tools, like Argo CD, use the `metadata.ownerReference` field on resources to determine how (and when) to display resources in the UI. If the `ownerReferences` is added to the CRDs, tooling can link them back to the resource that created them.
```
metadata:
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: crossplane
      uid: 49e289db-c0e3-4cc4-973b-00df27b9b5f7
```

The open question here is how to handle retrieving the UID of the deployment from the init container. If the service account for the deployment (and therefore pods) is given permission, the init container can use `kubectl` to retrieve it.
```
export DEPLOY_UID=$(kubectl get deployment crossplane -o=jsonpath='{.metadata.uid}')
 ```
