### ISSUE TITLE
Defaults in XRD are not copied to claim when they are nested in a object

### ISSUE THREAD

**Issue by AtzeDeVries** [crossplane/crossplane#5448]
### What happened?
Defaults set in a XRD that are nested in a map are not copied to the claim. This happens when
the claim does not have the root key of the map in which the default is set. See example for further details. 
We expect the defaults to be copied or merged independed of the structure of the claim. 

### How can we reproduce it?

Define the following fictional XRD
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.custom-api.example.org
spec:
  group: custom-api.example.org
  names:
    kind: xDatabase
    plural: xdatabases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string 
              size:
                type: string  
              name:
                type: string
                default: db
              labels:
                type: object
                properties:
                  field: 
                    type: string 
                    default: left 
                  available:
                    type: boolean 
                    default: true
```

then inject the following two claims

```yaml
---
apiVersion: custom-api.example.org/v1alpha1
kind: xDatabase
metadata:
  name: test-1
spec: {}
---
apiVersion: custom-api.example.org/v1alpha1
kind: xDatabase
metadata:
  name: test-2
spec:
  labels: {}
```

The result is that the defaults under `.labels` are not set in `test-1` but are set in `test-2`. 
When retrieving the object from k8s we see:

```yaml
apiVersion: custom-api.example.org/v1alpha1
kind: xDatabase
metadata:
  # some cleanup for readability
  name: test-1
spec:
  name: db
status:
  conditions:
  # cleanup
```

```yaml
apiVersion: custom-api.example.org/v1alpha1
kind: xDatabase
metadata:
  # some cleanup for readability
  name: test-2
spec:
  name: db
  labels:
    available: true
    field: left
status:
  conditions:
  # cleanup
```

### What environment did it happen in?
Crossplane version: 1.32.2

**Comment by haarchri** [comment]
did you tried to set it like this? 

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.custom-api.example.org
spec:
  group: custom-api.example.org
  names:
    kind: xDatabase
    plural: xdatabases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string 
              size:
                type: string  
              name:
                type: string
                default: db
              labels:
                type: object
                default:
                  field: left
                  available: true
                properties:
                  field: 
                    type: string 
                    default: left 
                  available:
                    type: boolean 
                    default: true
```

**Comment by phisco** [comment]
This too should be enough iirc
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.custom-api.example.org
spec:
  group: custom-api.example.org
  names:
    kind: xDatabase
    plural: xdatabases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string 
              size:
                type: string  
              name:
                type: string
                default: db
              labels:
                type: object
                default: {}        # <- this
                properties:
                  field: 
                    type: string 
                    default: left 
                  available:
                    type: boolean 
                    default: true
```
