### ISSUE TITLE
Crossplane is unable to import CachePolicy (cloudfront.aws.upbound.io/v1beta1)

### ISSUE THREAD

**Issue by BartoszZawadzki** [crossplane/crossplane#5483]
### What happened?
I'm trying to import `CachePolicy` (`cloudfront.aws.upbound.io/v1beta1`) using https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/#import-resources-automatically.

Import fails with:
```
  Warning  CannotObserveExternalResource  28s (x20 over 12m)  managed/cloudfront.aws.upbound.io/v1beta1, kind=cachepolicy  external resource does not exist
```

The resource does exist in AWS and I can view it using the following command:
```
aws cloudfront get-cache-policy --id ea5c7eca-c742-4544-b019-7da04075XXXX
```

### How can we reproduce it?
Create a CachePolicy outside of crossplane (either manually or via terraform) and then try to import it using id parameter:
```
---
apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: CachePolicy
metadata:
  labels:
    crossplane.io/external-name: "ea5c7eca-c742-4544-b019-7da04075XXXX"
  name: foo-cachepolicy-zero-ttl-no-cache
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-west-1
  managementPolicies: [ "Observe" ]
```

### What environment did it happen in?
Crossplane version: `v1.15.0`

* Cloud provider or hardware configuration `AWS`
* Kubernetes version (use `kubectl version`) `v1.23.17`
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) Kubernetes cluster created and managed by `kops`
