### ISSUE TITLE
Support for multiple maintainable Composition revisions

### ISSUE THREAD

**Issue by dee-kryvenko** [crossplane/crossplane#5489]
### What problem are you facing?

Currently, Composition Revisions implementation seems to be a forward-only. To produce a revision, one must update a parent Composition. This does not allow for maintaining multiple branches of code for the same composition simultaneously.

Alternatively, one might want to try to use different distinct compositions for that purpose. In that case, user will loose label selector functionality as switching between different distinct compositions is only possible by updating composition ref explicitly on a claim, or composed resource if it was created with no claim.

For better understanding of the context, consider rules of SemVer which is widely adopted in terraform world. SemVer consists of 3 bits: MAJOR.MINOR.PATCH. Bumping a PATCH version usually means a very minor bugfix that would not change any of the behavior. Bumping MINOR means there is significant change to the behavior, such as new functionality, but generally the change is backward compatible and on the same input it will still produce the same result. Bumping MAJOR means there is a breaking change, and users must read upgrading notes because likely there is a change to the input and/or potentially destructive behavior on the old input. I am not necessarily make a case for MINOR and PATCH distinction, there usually is very little on the rapid release cycles, but Crossplane should definitely support distinction between MAJOR and MINOR. The catch is - upon releasing a new MAJOR, there usually is a need to maintain the old MAJOR for a while. Sometimes - for a long while. SemVer users usually do something like `~> X.Y` which literally means `>= X.Y, <X+1`.

### How could Crossplane help solve your problem?

This equivalent functionality is what we need in Crossplane. A sample claim may look something like:

```yaml
spec:
  compositionSelector:
    matchLabels:
      crossplane.example.com/generation: v1
      crossplane.example.com/channel: stable
```

In this case, the `crossplane.example.com/channel` would be an equivalent of MINOR SemVer, and it is totally ok to be a forward-only i.e. existing Composition Revisions completely support that scenario. For `crossplane.example.com/generation` however is not, because the need is basically to maintain multiple active generations while each might have its own channels within. I think the simplest solution would be to maintain multiple distinct compositions with distinct names, and allow claim/composed resources to update the ref based on a change in a selector.

Which BTW also is making a case to classify current behavior as a bug, and not a feature request. Basically, consider I update my claim label selector to `crossplane.example.com/generation: v2`. Composition ref will not be currently updated automatically, because there is no Composition Revision for that specific Composition in existence with a label value `v2`, but overall resource will still considered to be healthy, even though currently selected composition ref no longer match the selector and selector by the current logic is pointing to the void. At the very minimum, in my opinion, this should have made resource not healthy and produced a condition and event clearly indicating that this happened.

**Comment by bobh66** [comment]
There is a functional difference between _Composition Selection_ and _Composition Revision Selection_.  _Composition Selection_ is performed once at creation to populate `compositionRef` and then any subsequent changes to the `compositionSelector.matchLabels` are ignored as long as `compositionRef` is populated.  _Composition Selection_ must be re-triggered manually by removing the existing `compositionRef`.  This is a feature not a bug.

_Composition Revision Selection_ has two modes, `Manual` and `Automatic` where `Automatic` updates the `compositionRevisionRef` to the latest available `CompositionRevision` _automatically_, and `Manual` requires the user to update the `composiitonRevisionRef` explicitly when they want it to change.  They can go backward or forward as needed.

Composition Functions also provide another way of handling this outside of the traditional Composition realm, for example  the Claim/Composite can specify a semVer value to be passed into a Composition Function which can then implement the appropriate resource logic.  The user has a lot more control over what logic is executed and can essentially bypass _Composition Selection_ and _Composition Revision Selection_ entirely.  That may be more appropriate for complex lifecycle management scenarios, and has the additional benefit of being completely decoupled from the Crossplane release cycle.  If you have a Composition Function that implements the `v1` and `v2` Compositions, you could switch between them via claim input changes without ever needing to retrigger `Composition Selection`.

I think Composition lifecycle management is probably a topic that deserves some discussion and documentation of recommended practices.

**Comment by dee-kryvenko** [comment]
@bobh66 yes, I understand how it works **at the moment**, thank you very much ;)

And no, if I do versioning in the function, I have to change the composition in order for new version to even be available, which defeats the whole purpose of versioning as it gives no guarantees that the logic of the old version remains unaltered. This defies all logic and reason that separates implementation and metadata.

**Comment by bobh66** [comment]
Why does the Composition have to change for the new version to be available from the Function?   The Function can be updated to provide new versions, and the claim can request those new versions, without changing the Composition that calls the Function.

**Comment by dee-kryvenko** [comment]
Because I thought you meant the function input, something like if-else branching in the input to Go template function. Apparently not. Well if I get your point correct this time, it sounds overly excessive. Functions (aka source code that runs in a function container) becomes aware of the implementation instead of being a reusable helper or abstraction. I'm not sure why would I want to do it in a function and why Crossplane would not provide a scalable versioning API.

Imagine Kubernetes deployment or a statefulset did nothing when I change node selector. That'd be so much fun.

I'm trying to understand why are you opposing me. Do you not agree with the solution I proposed? That I can understand, and I'm not insisting on it. There are alternative ways. For example, maybe we need to extend Composition Revision API to be able to produce a revision from multiple compositions. So, we would have 3 CRDs - something like Composition Source -> Composition -> Composition Revision. Or maybe there are other and better ways. 

Or is that you do not agree with the problem statement? I dunno what to tell you then, maybe you just didn't try to run a massive scale operations using this tool yet, and in your environment you can afford forward-only approach?

**Comment by truongnht** [comment]
@dee-kryvenko today I got into exactly same problem. The fact that we are making from ArgoCD makes it worse (for manual fiddling).

**Comment by bobh66** [comment]
It sounds like the request is to allow Composition Selection to react to the updated `compositionSelector.matchLabels` and select a different Composition/CompositionRevision.  If I put this in terms of other Policies that Crossplane uses, it might be "CompositionSelectionUpdatePolicy" with values of "Manual" (the default and current operation) and "Automatic" (changes to `compositionSelector.matchLabels` automatically trigger a re-selection and potentially update `compositionRef.name` and `compositionRevisionRef.name`.

Is that correct?

**Comment by truongnht** [comment]
so, in our repo, we have the following claim
```
{{- if .Values.trivyOperator.serviceAccount.create -}}
apiVersion: iam.crossplane.hsp.io/v1alpha1
kind: IAMRole
metadata:
  name: {{ .Values.trivyOperator.serviceAccount.roleName }}
  namespace:  {{ .Values.trivyOperator.destination.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  compositionSelector:
    matchLabels:
      hsp.io/composition-function: "true"
      {{- if .Values.trivyOperator.podIdentity.enabled }}
      hsp.io/iam-role-strategy: "pod-identity"
      {{- else }}
      hsp.io/iam-role-strategy: "irsa"
      {{- end }}
  parameters:
    serviceAccount:
      name: trivy-operator # default value of of trivy-operator helm chart
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
{{- end -}}
```
dependent on the toggle boolean (`podIdentity.enabled` - for now for testing, later on we will replace with system capability (e.g querying to check if pod identity api is supported)) we either select irsa composition or pod identity one. 

But the result is: once the claim selects a compositionRef, changing the selector does not work at all. 

@dee-kryvenko, sorry for hijacking your session, and would love to hear @bobh66 opinion
