### ISSUE TITLE
crossplane beta validate does not work with Configurations using composition function dependencies

### ISSUE THREAD

**Issue by thoec** [crossplane/crossplane#5491]
### What happened?
From https://crossplane.slack.com/archives/CEG3T90A1/p1709804398127329

When loading a Configuration as part of trying to use `crossplane beta validate` to validate my composition(s) `crossplane beta validate` fails with the following error:
```
crossplane beta render test/xr.yaml configuration/apis/cluster/eks/composition.yaml test/functions.yaml --include-full-xr | crossplane beta validate bootstrap/configuration.yaml - --verbose --clean-cache
package schemas does not exist, downloading:  xpkg.upbound.io/upbound/provider-aws-eks:v1.1.0
package schemas does not exist, downloading:  xpkg.upbound.io/upbound/provider-aws-iam:v1.1.0
package schemas does not exist, downloading:  :v0.3.0
crossplane: error: cannot download and load cache: cannot cache package dependencies: cannot download package :v0.3.0: cannot get config: parsing reference ":v0.3.0": could not parse reference: :v0.3.0
```
My [Configuration.meta.pkg.crossplane.io/v1](http://configuration.meta.pkg.crossplane.io/v1) spec looks like this:
```
spec:
  crossplane:
    version: ">=v1.15.0-0"
  dependsOn:
    - provider: "xpkg.upbound.io/crossplane-contrib/provider-kubernetes"
      version: "v0.12.1"
    - provider: "xpkg.upbound.io/upbound/provider-aws-ec2"
      version: "v1.1.0"
    - provider: "xpkg.upbound.io/upbound/provider-aws-eks"
      version: "v1.1.0"
    - provider: "xpkg.upbound.io/upbound/provider-aws-iam"
      version: "v1.1.0"
    - function: "xpkg.upbound.io/crossplane-contrib/function-patch-and-transform"
      version: "v0.3.0"
    - function: "xpkg.upbound.io/crossplane-contrib/function-go-templating"
      version: "v0.4.1"
    - function: "xpkg.upbound.io/crossplane-contrib/function-auto-ready"
      version: "v0.2.1"
```
When I comment out the three functions above the validation works as intended.

Looking at the code (`addDependencies()` in `manager.go`) it looks like function package deps are not handled, I guess they should just be ignored in this case? The package (function) image in that case ends up as the empty string with a tag.

### How can we reproduce it?
See above.

Validate against the dependent schemas of a Configuration packages. Downloading the composition functions will fail.

### What environment did it happen in?
Crossplane version: 1.15
