### ISSUE TITLE
Composition update weird behaviour

### ISSUE THREAD

**Issue by daniel-maganto** [crossplane/crossplane#5519]
### What happened?
I detected a weird issue when I tried to update a composition or when I installed it from scratch. For instance:
If I updated from previous versions (non functions usage), some fields appears has "rendered" in the cluster like this:
```yaml
          - base:
              apiVersion: iam.aws.upbound.io/v1beta1
              kind: Role
              spec:
                deletionPolicy: Orphan
                forProvider:
                  assumeRolePolicy: |
        # Removed for Brevity
                  inlinePolicy:
                    - {}
            name: executionRole
```
But if I apply from scratch in a brand new Crossplane installation, it appears like this:
```yaml
      - base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Role
          spec:
            deletionPolicy: Orphan
            forProvider:
              assumeRolePolicy: |
        # Removed for Brevity
              inlinePolicy:
              - name: null
                policy: null
              permissionsBoundary: null 
        name: executionRole
```
in both cases, the original composition is this one, but in prior versions the composition was like in the first case:
```yaml
      - base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Role
          spec:
            deletionPolicy: Orphan
            forProvider:
              assumeRolePolicy: |
        # Removed for Brevity
              inlinePolicy:
              - name:
                policy:
              permissionsBoundary:
```

### How can we reproduce it?
I would say if you install a composition with some configuration, and later update it you will get the same error. If needed I can send a simplified composition for testing.

### What environment did it happen in?
Crossplane version:  1.15.1
Kubernetes version: v1.28.6-eks-508b6b3
Kubernetes distribution: AWS EKS
