### ISSUE TITLE
Composition doesn't remove optional properties from mrs when they are removed from xr

### ISSUE THREAD

**Issue by jankaacc** [crossplane/crossplane#5525]
### What happened?
we did updated to 1.15.0 with server side apply flag, everything works nicley, xrs are well synced but removal of optional property is not synced to underlying composition

### How can we reproduce it?

we have our claim with some optional properties. If I have some optional property on claim:

```
apiVersion: my.api
kind: myKind
...
spec:
 optional: smt
 mandatory: smt
```

then XR

```
apiVersion: my.api
kind: xMyKind
...
spec:
 optional: smt
 mandatory: smt
```

I am removing optional, now after 1.15.0 everything is nicley synced on XR:

```
apiVersion: my.api
kind: xMyKind
...
spec:
 mandatory: smt
```

but in my composition lets say I am forwarding spec.optional to some MR: 

```
    - name: my-mr
      base:
        apiVersion: apr.version/v1alpha1
        kind: someMR
        spec:
          forProvider:
            mandatory:  # patched
            optional:  # patched
      patches:
        - fromFieldPath: spec.mandatory
          toFieldPath: spec.mandatory
        - fromFieldPath: spec.optional
          toFieldPath: spec.optional
```

now If I am removing optional from claim it is reomved from xr but it is not removed from mr .

we have solution for this, just adding default values in the composition: 

  ```
  - name: my-mr
      base:
        apiVersion: apr.version/v1alpha1
        kind: someMR
        spec:
          forProvider:
            mandatory:  # patched
            optional: "default"
      patches:
        - fromFieldPath: spec.mandatory
          toFieldPath: spec.mandatory
        - fromFieldPath: spec.optional
          toFieldPath: spec.optional
```

so it can be done like this at least in our case but I guess problem exists

### What environment did it happen in?
Crossplane version: 

Corssplane 1.15.0
