### ISSUE TITLE
Filter and data source

### ISSUE THREAD

**Issue by diegoavitorino** [crossplane/crossplane#5538]
Hi, I'm trying to get resources like data source from Terraform:

```
data "aws_vpc" "selected" {
  tags = {
    AWS_Solutions = "LandingZoneStackSet"
  }
}

data "aws_subnets" "private" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.selected.id]
  }
  
  tags = {
    Network = "Private"
  }
}
```

Could you help me with this solution on the crossplane?

I could get VPC as bellow, but filter subnet groups by tag not yet.
```
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  labels:
    app: crossplanelab
  annotations:
    "crossplane.io/external-name": "vpc-id123123123"
  name: default
spec:
  managementPolicies: ["Observe"]
  forProvider: 
    region: sa-east-1
---
apiVersion: rds.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  labels:
    app: crossplanelab
  annotations:
    "crossplane.io/external-name": "*"
  name: default
spec:
  filters:
    - Name=tag:Network,Values=Private 
  managementPolicies: ["Observe"]
  forProvider: 
    region: sa-east-1
```
```    
  unknown field "spec.filters"
```
