### ISSUE TITLE
Cannot use ToAdler32 as string convertion

### ISSUE THREAD

**Issue by eskabetxe** [crossplane/crossplane#5559]
### What happened?
In crossplane 1.14 was introduced the String Conversion ToAdler32 but cannot be used as is not defined on CRDs

### How can we reproduce it?
Try to convert any value with ToAddler32
```
transforms:
      - type: string
        string:
          type: Convert
          convert: "ToAdler32"
```

### What environment did it happen in?
Crossplane version: 1.14, 1.15
