### ISSUE TITLE
Crossplane function -  Cannot resolve package dependencies: cannot initialize dependency graph from the packages in the lock

### ISSUE THREAD

**Issue by btwseeu78** [crossplane/crossplane#5564]
### What happened?

Recently while installing function i came to know about this weird problem,
and i believe it should not be working like this,
so, to give details -
I already have one function "function-patch-and-transform" installed .
I again installed the same function(diff function metadata.name)  with another function(this is fresh function).
now when i install them i see the fresh function is not healthy and the reason is the first function is duplicate, i don't think they should be related at all. some more details from status.
```
Spec:
  Ignore Crossplane Constraints:  false
  Package:                        xpkg.upbound.io/crossplane-contrib/function-sequencer:v0.1.2
  Package Pull Policy:            IfNotPresent
  Revision Activation Policy:     Automatic
  Revision History Limit:         1
  Runtime Config Ref:
    API Version:               pkg.crossplane.io/v1beta1
    Kind:                      DeploymentRuntimeConfig
    Name:                      default
  Skip Dependency Resolution:  false
Status:
  Conditions:
    Last Transition Time:  2024-04-09T11:18:19Z
    Message:               cannot resolve package dependencies: cannot initialize dependency graph from the packages in the lock: node xpkg.upbound.io/crossplane-contrib/function-patch-and-transform already exists
    Reason:                UnknownPackageRevisionHealth
    Status:                Unknown
    Type:                  Healthy
    Last Transition Time:  2024-04-09T11:18:14Z
    Reason:                ActivePackageRevision
    Status:                True
    Type:                  Installed
  Current Identifier:      xpkg.upbound.io/crossplane-contrib/function-sequencer:v0.1.2
  Current Revision:        function-sequencer-c3d57e50b393
```

### How can we reproduce it?
1. Install Crossplane function patch-and-transform.
2. Install another function(new function) as well as another function which refers patch-and-transform.

### What environment did it happen in?
Crossplane version:  v1.15.1(xpkg.upbound.io/crossplane/crossplane)

## Env:
cluster - kind
K8sVersionPrefix - 1.29.

Details to reproduce :- 
1. Install patch-and-transform (official Doc)
2. Install this manifest 

```
---
# Source: crossplane-function/templates/deployment-runtime-config.yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: patch-and-transform-beta
spec:
  serviceAccountTemplate:
    metadata:
      name: patch-and-transform-beta
  deploymentTemplate:
    spec:
      selector:
        matchLabels:
          pkg.crossplane.io/function: patch-and-transform-beta
      replicas: 2
      template:
        spec:
          containers:
          - name: package-runtime
            image: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0
            args:
            - --d
...
---
# Source: crossplane-function/templates/deployment-runtime-config.yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-sequencer
spec:
  deploymentTemplate:
    spec:
      selector:
        matchLabels:
          pkg.crossplane.io/function: function-sequencer
      replicas: 1
      template:
        spec:
          containers:
          - name: package-runtime
            image: xpkg.upbound.io/crossplane-contrib/function-sequencer:v0.1.2
...
---
# Source: crossplane-function/templates/function.yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: patch-and-transform-beta
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: patch-and-transform-beta
...
---
# Source: crossplane-function/templates/function.yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-sequencer
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-sequencer:v0.1.2
...
```
Slack Conversations realted to this : https://crossplane.slack.com/archives/CEG3T90A1/p1712662410221119

**Comment by jbw976** [comment]
Thanks for opening this issue and providing more context @btwseeu78!

I'd love to understand your scenario a bit better - is there a reason you're hoping to have more than 1 version of `function-patch-and-transform` installed in the control plane? what does your ideal outcome look like if your scenario worked as intended? 🤔 

I think in general it's not supported to install 2 copies of the same function right now - I can essentially reproduce this same scenario just installing `function-patch-and-transform` twice, without `function-sequencer`. I think for `function-sequencer`, you're getting the error message about `function-patch-and-transform` in the lock file, which is a bit misleading, because the lock file as a whole is in an unsupported state due to the duplicated functions, and therefore the package manager can't even try to think about `function-sequencer`'s dependencies (of which there are actually [none](https://github.com/crossplane-contrib/function-sequencer/blob/main/package/crossplane.yaml)). I think this is what's happening here 😇 

Here's a repro of this scenario with just 2 `function-patch-and-transform`:
```
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0
```
```
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform-2
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0
```
