### ISSUE TITLE
keepMapValues: true merge option is not considered with CombineFromComposite patch when transforming json string to object

### ISSUE THREAD

**Issue by fcke** [crossplane/crossplane#5572]
### Problem statement
The ```keepMapValues: true``` merge option does not have effect when it is used in a CombineFromComposite patch along with the ```transforms``` operation.
### What happened?
I have the following patch:
```
   - type: CombineFromComposite
     combine:
       strategy: string
       string:
         fmt: '{"%s-%s":{"url":"http://%s.4.48:8080","tls":"DISABLE","tlsSecret":null,"protocol":"h2c"}}'
       variables:
         - fromFieldPath: spec.parameters.valueString1
         - fromFieldPath: spec.parameters.valueString2
         - fromFieldPath: spec.parameters.baseCidrOctets
     toFieldPath: spec.forProvider.manifest.spec.values.chartValues.global.externalServices
     policy:
       mergeOptions:
         keepMapValues: true
     transforms:
     - type: convert
       convert:
         toType: object
         format: json 
```
The patch works fine when I do not have anything under ```spec.forProvider.manifest.spec.values.chartValues.global.externalServices```. However, when there is already an existing sub-tree, it is overwritten with the newly created json-transformed-to-object value despite of the ```keepMapValues: true``` merge option.

Resource, before patch:
```
  externalServices:
     zService:
       ip: zservice.svc.cluster.local
       ports:
         cm: 8080
         fm_alarm: 8079
         fm_log: 8078
         pm: 8079
```
After patch:
```
  externalServices:
     valueString1-valueString2:
       ip: 1.2.4.48:8080
       tls: DISABLE
       tlsSecret: null
       protocol: h2c
```
However, when I have two separate patch, one for the combine and another one for the transform, the ```keepMapValues: true``` has the expected effect and the newly created object is merged.
So, when I have the following patch added to another resource, just to create the proper string which I can use in the original resource for patching (really ugly, but do not know any better way currently...):
```
  - type: CombineFromComposite
    combine:
      strategy: string
      string:
        fmt: '{"%s-%s":{"url":"http://%s.4.48:8080","tls":"DISABLE","tlsSecret":null,"protocol":"h2c"}}'
      variables:
         - fromFieldPath: spec.parameters.valueString1
         - fromFieldPath: spec.parameters.valueString2
         - fromFieldPath: spec.parameters.baseCidrOctets
    toFieldPath: metadata.annotations.externalServiceNew
  - type: ToCompositeFieldPath
    fromFieldPath: metadata.annotations.externalServiceNew
    toFieldPath: metadata.annotations.externalServiceNew
```
And I use the transform to patch the target resource (note: ```fromFieldPath: Required``` is there to prevent creation of the resource before the formatted string is available as I need the changes to the ```externalServices``` when this resource is created):
```
  - type: FromCompositeFieldPath
    fromFieldPath: metadata.annotations.externalServiceNrf
    toFieldPath: spec.forProvider.manifest.spec.values.chartValues.global.externalServices
    policy:
      fromFieldPath: Required
      mergeOptions:
        keepMapValues: true
    transforms:
    - type: convert
      convert:
        toType: object
        format: json
```
Everything works flawlessly.

Example:
Resource, before patch:
```
  externalServices:
    zService:
      ip: zservice.svc.cluster.local
        ports:
          cm: 8080
          fm_alarm: 8079
          fm_log: 8078
          pm: 8079
```
After patch:
```
  externalServices:
     valueString1-valueString2:
       ip: 1.2.4.48:8080
       tls: DISABLE
       tlsSecret: null
       protocol: h2c
     zService:
       ip: zservice.svc.cluster.local
       ports:
         cm: 8080
         fm_alarm: 8079
         fm_log: 8078
         pm: 8079
```
### What environment did it happen in?
Crossplane version: 1.15.0
Cloud provider: AWS EKS
Kuberetes: 1.29
