### ISSUE TITLE
Error while creating compositions using Pipeline mode

### ISSUE THREAD

**Issue by siddharthdeshmukh** [crossplane/crossplane#5635]
### What happened?

Error installing composition that uses Pipeline mode. 
```
cannot establish control of object: admission webhook "compositions.apiextensions.crossplane.io" denied the request:  Composition.apiextensions.crossplane.io
        "roles.aws.kubernetes.example.net" is invalid: spec.resources:
        Required value: an array of resources is required in Resources mode (the
        default if no mode is specified
```

### How can we reproduce it?

Create composition and configuration
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: roles.aws.kubernetes.example.net
spec:
  writeConnectionSecretsToNamespace: platform-provisioning
  compositeTypeRef:
    apiVersion: aws.kubernetes.example.net/v1alpha1
    kind: XRole
  mode: Pipeline
  pipeline:
  - step: crossplane-function
    functionRef:
      name: crossplane-function
    input:
      apiVersion: function.aws.kubernetes.example.net/v1alpha1
      kind: Input
      spec:
        action: create-role
```
```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: iam-role-example
spec:
  crossplane:
    version: ">=v1.13"
  dependsOn:
  - provider: crossplane-upbound-aws-provider
    version: ">=v0.22.0"
```
Build package using `crossplane xpkg build` and push the package to registry and install the Configuration in cluster

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: iam-role-compositions
spec:
  commonLabels:
    kubernetes.klarna.net/composition-name: iam-role-compositions
    kubernetes.klarna.net/provider: aws
    kubernetes.klarna.net/version: v1.0.0-rc1
  ignoreCrossplaneConstraints: false
  package: <package>
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: true
```
Check configurationrevision and it is unhealthy.
If I just apply like `kubectl apply -f compositions.yaml` it works.

### What environment did it happen in?
Crossplane version:  v1.15.0

Beta features flags are enabled
```
2024-04-29T09:35:33Z    INFO    crossplane    Beta feature enabled    {"flag": "EnableBetaCompositionFunctions"}
2024-04-29T09:35:33Z    INFO    crossplane    Beta feature enabled    {"flag": "EnableBetaCompositionFunctionsExtraResources"}
2024-04-29T09:35:33Z    INFO    crossplane    Beta feature enabled    {"flag": "EnableBetaCompositionWebhookSchemaValidation"}
2024-04-29T09:35:33Z    INFO    crossplane    Beta feature enabled    {"flag": "EnableBetaDeploymentRuntimeConfigs"}
```

kubernetes version: 1.28
