### ISSUE TITLE
Proposal: New `Healthy` condition for claims and XRs

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5643]
### Executive summary

I propose we add a new `Healthy` status condition to claims and XRs. This condition would indicate whether the resource _and all of its child resources_ were healthy - i.e. weren't currently encountering any errors.

This would make it possible to quickly determine whether a claim isn't ready because it's hitting an error, or because it just needs more time to become ready.

Importantly, the new condition wouldn't include the specific error(s) child resources were encountering. It would only indicate that there were or weren't errors.

### What problem are you facing?

Claims, XRs, and MRs have the following status conditions:

* `Ready` - Indicates that Crossplane believes the resource is ready to use
* `Synced` - Indicate that Crossplane successfully synced the resource on the last reconcile

`Ready` _doesn't_ mean "Crossplane is successfully reconciling this resource". It means "the thing this resource represents appears to be ready to use". For example if a claim represents a database, the `Ready` condition indicates that Crossplane believes the database is ready to use. It's ready for some application to connect to it and store data.

`Ready` is cumulative. A claim is only `Ready` when its underlying XR is `Ready`. The XR is only `Ready` when all its composed resources are `Ready`.

`Synced` _does_ mean "Crossplane is successfully reconciling this resource". It isn't cumulative, though. It only means "_this controller_ reconciled its most recent desired state successfully". For example an XR could reconcile its desired state by creating three misconfigured composed resources that would never become `Synced` or `Ready`. The XR is still `Synced` though, 
because its controller did its job. It successfully synced its desired state by creating composed resources.

I think these two conditions make sense. For example:

* A resource could be `Synced` because Crossplane has successfully applied its desired state, but not yet `Ready` to use.
* A resource could be `Ready` to use (as far as Crossplane knows), but no longer `Synced` because Crossplane is hitting an error.

There's an information gap though. Today if you look at a newly created claim you'll likely see:

* `Synced: True` - The claim successfully created and is syncing with an XR
* `Ready: False` - The conceptual resource the claim represents (e.g. a database) isn't ready to use yet

It's possible the XR controller, and all composed resource controllers are working fine but some MR isn't ready to use yet - e.g. the RDS API is reporting that a composed RDS instance isn't ready to use. It's also possible that one of the controllers is stuck due to an error.

Today there's no way to distinguish between these two cases without inspecting the next layer down.

Folks have been feeling the pain of this gap for some time, but I've been reluctant to address it because the proposed solution has always been "take the errors from lower level controllers and propagate them to the higher level controllers" - for example https://github.com/crossplane/crossplane/issues/3262.

@vfarcic explains why that isn't a great solution in https://www.youtube.com/watch?v=xAl3TAfFE_M. Claims, XRs, and MRs are all different layers of abstraction, with different intended audiences. An error that makes sense at one layer probably won't make sense at a higher layer of abstraction.

Consider for example an XR error due to an invalid Composition. I don't think it makes sense to copy that error verbatim to the claim. Assuming the claim author isn't writing their own Composition, the error isn't actionable for them.

One way to address this is to build a presentation layer that allows Composition authors to choose which errors were surfaced to the claim and how. That's what we're working on in https://github.com/crossplane/crossplane/issues/5402.

The downside of the presentation layer approach is that the information gap still exists by default. If the Composition author doesn't actively "present" errors to the claim, there's still no way to distinguish between a claim that's not ready due to an error, or a claim that's not ready because the cloud provider is still working on creating one of the composed resources.

### How could Crossplane help solve your problem?

I propose we add a new `Healthy` status condition to claims and XRs.

A claim would be `Healthy` only when:

* The claim controller was `Synced`
* The underlying XR controller was `Synced` and `Healthy`

An XR would be `Healthy` only when:

* The XR controller was `Synced`
* All composed resources were `Synced`, and if applicable (e.g. the composed resource is an XR) `Healthy`

The `Healthy` condition would in effect be a cumulative version of the `Synced` condition. I'm proposing a new condition instead of proposing that we change the meaning of the `Synced` condition because changing the meaning would be a significant behavior change.

Importantly, I'm _not_ proposing that we copy error messages from child to parent resources. For example if a claim wasn't `Healthy` I'd expect the status condition message to say something generic like "N/M composed resources are not synced" or just "Some resources encountered errors".

Under this proposal a claim status might look like this:

```yaml
status:
  conditions:
  - type: "Ready"
    status: "False"
    reason: "BindCompositeResource"
    message: "The composite resource is not yet ready"
  - type: "Healthy"
    status: "False"
    reason: "UnhealthyCompositeResource"
    message: "The composite resource is not healthy"
  - type: "Synced"
    status: "True"
    reason: "ReconcileSuccess"
```

An XR status might look like this:

```yaml
status:
  conditions:
  - type: "Ready"
    status: "False"
    reason: "Creating"
    message: "Unready resources: some-composed-resource, another-composed-resource"
  - type: "Healthy"
    status: "False"
    reason: "UnhealthyComposedResources"
    message: "Unhealthy resources: some-composed-resource"
  - type: "Synced"
    status: "True"
    reason: "ReconcileSuccess"
```

**Comment by negz** [comment]
CC @dalton-hill-0 @TerjeLafton @jbw976 - Just an FYI as this is tangentially related to designs you've all been working on.

**Comment by birapjr** [comment]
Hi @negz Very good feature. It will help a lot to a fast investigation on issues. We can see a bit of the Health status via crossplane beta trace cli command, but its not clear when you get status only of one resource.

**Comment by dariozachow** [comment]
I think this would be very helpful, struggling with this atm.

**Comment by negz** [comment]
If anyone from the community wants to give this a shot, I'd be supportive.

I think it would require a little experience with Crossplane though, and the update needs to be made in a few places (crossplane-runtime, providers, core, etc).

**Comment by dalton-hill-0** [comment]
Would composition functions be able to set/override the message for the `Healthy` condition?

**Comment by negz** [comment]
> Would composition functions be able to set/override the message for the Healthy condition?

@dalton-hill-0 I'm not sure. When would a function want to do that?

For an XR I imagine the messages would be one of the following when the XR wasn't `Healthy`:

* `The composite resource is not synced`
* `Unhealthy composed resources: resource-a, resource-b`

With sync issues trumping composed resource issues if both were true (since the XR not being synced means it might not have the latest composed resource status).

A function could indirectly influence `Healthy` by returning a fatal result. That would set the `Synced` message, and the `Healthy` message would basically be "I'm not synced - go look at the Synced condition".

**Comment by patpicos** [comment]
Would this be accomplished with upstream crossplane or something like `function-auto-healthy` (similar to function-auto-ready) with a new transition?
Overall, i am really liking the idea of a state of `Healthy` so that we can use it to bubble up statuses in ArgoCD.

My example, as you mentioned, READY is cumulative and seen below. SYNCED is not cumulative, therefore i have no way of marking the composite as un-healthy using ArgoCD Health-Checks.
```
crossplane beta trace xisvcontinuousdeployment.onboarding.gitops.k8s.dish.io/xyz-dev-9fgb8 -o wide
NAME                                                                                                 RESOURCE                                                                     SYNCED   READY   STATUS
XIsvContinuousDeployment/xyz-dev-9fgb8                                                                                                                                            True     True    Available
├─ XLdapGroupLink/xyz-dev-9fgb8-developer-gitlab-lgl                                                 xyz-dev-9fgb8-developer-gitlab-lgl                                           True     True    Available
│  └─ DisposableRequest/xyz-dev-9fgb8-developer-gitlab-lgl-5g-dish-caf-xyz-developers-gitlab-lgl     xyz-dev-9fgb8-developer-gitlab-lgl-5g-dish-caf-xyz-developers-gitlab-lgl     True     True    Available
├─ XLdapGroupLink/xyz-dev-9fgb8-maintainer-gitlab-lgl                                                xyz-dev-9fgb8-maintainer-gitlab-lgl                                          True     True    Available
│  └─ DisposableRequest/xyz-dev-9fgb8-maintainer-gitlab-lgl-5g-dish-caf-xyz-maintainers-gitlab-lgl   xyz-dev-9fgb8-maintainer-gitlab-lgl-5g-dish-caf-xyz-maintainers-gitlab-lgl   True     True    Available
├─ AccessToken/xyz-dev-9fgb8-gitops-grp-accesstoken                                                  xyz-dev-9fgb8-gitops-grp-accesstoken                                         True     True    Available
├─ Group/xyz-dev-9fgb8-gitops-grp                                                                    xyz-dev-9fgb8-gitops-grp                                                     True     True    Available
├─ XGroup/xyz-dev-9fgb8-cag-isv-xyz-dev-isvuser-ldap                                                 xyz-dev-9fgb8-cag-isv-xyz-dev-isvuser-ldap                                   True     True    Available
│  └─ DisposableRequest/cag-isv-xyz-dev-isvuser-ldap                                                 cag-isv-xyz-dev-isvuser-ldap                                                 True     True    Available
├─ XGroup/xyz-dev-9fgb8-cag-isv-xyz-dev-readonly-ldap                                                xyz-dev-9fgb8-cag-isv-xyz-dev-readonly-ldap                                  True     True    Available
│  └─ DisposableRequest/cag-isv-xyz-dev-readonly-ldap                                                cag-isv-xyz-dev-readonly-ldap                                                True     True    Available
├─ Project/xyz-argocd-prj-dev                                                                        xyz-argocd-prj-dev                                                           False    True    ReconcileError: `spec.managementPolicies` is set to a non-default value but the feature is not enabled: [Create LateInitialize Observe]
├─ Project/xyz-dev-9fgb8-xyz-dev-gitlab-prj                                                          xyz-dev-9fgb8-xyz-dev-gitlab-prj                                             True     True    Available
├─ Repository/xyz-dev-9fgb8-argocd-repo-git                                                          xyz-dev-9fgb8-argocd-repo-git                                                False    True    ReconcileError: `spec.managementPolicies` is set to a non-default value but the feature is not enabled: [Create LateInitialize Observe]
└─ Repository/xyz-dev-9fgb8-argocd-repo-helm                                                         xyz-dev-9fgb8-argocd-repo-helm                                               False    True    ReconcileError: `spec.managementPolicies` is set to a non-default value but the feature is not enabled: [Create LateInitialize Observe]
```

Having this would allow the status to bubble up from managed resource to composite to claim and to the app, unlike the screenshot below.
![image](https://github.com/user-attachments/assets/90d51208-f28b-4e15-9b39-0c847274108a)

**Comment by dalton-hill-0** [comment]
@patpicos 

My understanding is that the `Healthy` status will be handled by crossplane itself and not a function like `function-auto-healthy`. If you want to bubble up status from an MR to the composite and claim, you can accomplish this with [function-status-transformer](https://github.com/crossplane-contrib/function-status-transformer). I still need to cut a release for this, but that may be what you want.

**Comment by negz** [comment]
I was thinking of building this into Crossplane, but a `function-auto-healthy` could be a good way to prototype and play with the idea.

**Comment by bobh66** [comment]
I like the idea of implementing this as a function so that it does not affect anyone who doesn't want/need the functionality.

**Comment by patpicos** [comment]
> XR status might look like this:
while i dont have a crossplane v1.17.0 handy, I looked at `function-status-transformer` and I'm wondering if this step would accomplish this proposal using @dalton-hill-0 function. 

```yaml
  - step: healthy-handler
    functionRef:
      name: function-status-transformer
    input:
      apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      statusConditionHooks:
      - matchers:
        - resources:
          - key: "*"    # All Managed Resources need to roll up
          conditions:
          - type: Synced
            status: "True"
        - resources:
          - "*"         # All Managed Resources need to roll up
          conditions:
          - type: Ready
            status: "True"
        createEvents:
        - target: CompositeAndClaim
          event:
            type: Healthy
            reason: ""
            message: "All managed resources are synced and ready. Overall Status: Healthy"
```


then, in ArgoCD, a health-check for our custom XRDs would have something like this
```lua
for i, condition in ipairs(obj.status.conditions) do
  if condition.type == "LastAsyncOperation" then
    if condition.status == "False" then
      health_status.status = "Degraded"
      health_status.message = condition.message
      return health_status
    end
  end

  if condition.type == "Synced" then
    if condition.status == "False" then
      health_status.status = "Degraded"
      health_status.message = condition.message
      return health_status
    end
  end

-- Disabled this check because it is misleading and we want to wait for the Healthy condition to show up before marking the Composite/Claim as healthy
  -- if condition.type == "Ready" then
  --   if condition.status == "True" then
  --     health_status.status = "Healthy"
  --     health_status.message = "Resource is up-to-date."
  --     return health_status
  --   end
  -- end

  if condition.type == "Healthy" then
    if condition.status == "True" then
      health_status.status = "Healthy"
      health_status.message = "Resource is healthy"
      return health_status
    end
  end

end

return health_status
```

**WARNING**: This is all pseudo-coding/untested. Trying to gauge if this would be on the right track

**Comment by dalton-hill-0** [comment]
@patpicos 

> Question: does the function REQUIRE 1.17? or would 1.16 work?

1.17 is required. If you add this function to your pipeline before 1.17, nothing will break, but you will not see the events or conditions either.

The function-status-transformer pseudo code above is on the right track. Here
are a couple of changes you may want/need to make (see comments in code).
```yaml
  - step: healthy-handler
    functionRef:
      name: function-status-transformer
    input:
      apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      statusConditionHooks:
      - matchers:
	# By default the matching logic is AllResourcesMatchAllConditions, but
	# you can specify it again for sake of readability
        - type: AllResourcesMatchAllConditions
	  resources:
	  # change key -> name (recent change)
	  # change regex to .* instead of *
	  - name: ".*"
	  # You can combine the conditions in a single matcher.
          conditions:
          - type: Synced
            status: "True"
          - type: Ready
            status: "True"
	# Need to use setConditions instead of createEvents if you are trying to
	# set conditions on your composite and claim.
        setConditions:
        - target: CompositeAndClaim
          condition:
	    # The type "Healthy" is reserved for the Crossplane system, in case
	    # it is implemented in the future from within Crossplane itself.
	    # Use something similar instead.
            type: ResourcesHealthy
            status: "True"
            reason: Available
            message: "All managed resources are synced and ready. Overall Status: Healthy"
```

As for the Go code, it depends on what `obj` is. If `obj` represents a managed
resource, it will not receive the conditions set by
`function-status-transformer`. `function-status-transformer` only sets
conditions on the composite and the claim. If we assume that `obj` represents
the composite or claim, then it will only have access to the following
conditions.
- `Synced` - A Crossplane system condition.
- `Ready` - A Crossplane system condition.
- Any custom condition type you set with `function-status-transformer`.
