### ISSUE TITLE
Condition message when a package has invalid dependencies is confusing

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5645]
### What happened?

As @sttts pointed out in https://github.com/crossplane/crossplane/pull/5314, the message for the condition when a package has invalid dependencies isn't especially helpful:

```
reason: UnknownPackageRevisionHealth
message: cannot resolve package dependencies: incompatible dependencies: [xpkg.upbound.io/crossplane-contrib/provider-kubernetes]
```

What is incompatible about the dependency? What can the user do to fix it? 

### How can we reproduce it?

```
# install crossplane
helm install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane

# install an older version of provider-kubernetes and function-patch-and-transform
crossplane xpkg install provider xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.12.1
crossplane xpkg install function xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0

# install a configuration package that has dependency version constraints on a newer versions of those packages
crossplane xpkg install configuration xpkg.upbound.io/jaredorg/config-xpkg:v0.1.1
```

We can see the incompatible dependencies condition with:
```
❯ k get Configuration/jaredorg-config-xpkg -o json | jq '.status.conditions[] | select(.reason=="UnknownPackageRevisionHealth")'
{
  "lastTransitionTime": "2024-05-02T10:30:28Z",
  "message": "cannot resolve package dependencies: incompatible dependencies: [xpkg.upbound.io/crossplane-contrib/provider-kubernetes xpkg.upbound.io/crossplane-contrib/function-patch-and-transform]",
  "reason": "UnknownPackageRevisionHealth",
  "status": "Unknown",
  "type": "Healthy"
}
```

For reference, the dependencies in `jaredorg/config-xpkg` are expressed as:
```
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.13.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.5.0"
```

### What environment did it happen in?
Crossplane version: v1.15.2
