### ISSUE TITLE
[Feature Request] Crossplane CLI should support a standardized testing model for compositions

### ISSUE THREAD

**Issue by lindblombr** [crossplane/crossplane#5710]
#### Introduction

`crossplane beta render` is super useful for _seeing_ the resulting output of a composition given an input XR and optional input XRs and context.  This is infinitely useful for initial shift-left testing of compositions during development.

Currently, we need to duct-tape together various tools in order to provide something approximating unit tests that are automated, easy to interpret, and are useful to demonstrating composition fitness.

In order to facilitate this, we've implemented some simple shell scripting that allows us to define a test directory structure like so

```
tests/
  - <composition_base_file_name>
    - functions.yaml   # functions to be included during test
    - <test-suite-directory>/
      - _n_-xr.yaml    # test case represented as an input XR
      - _n_-xr.assertions.yaml   # assertions to be applied against the resultant `crossplane beta render...` output of _n_-xr.yaml
      - observed.yaml  # optional observation input to use with `crossplane beta render...`
      - environment.yaml # optional EnvironmentConfigs to use with `crossplane beta render...` and `function-environment-config`
    - <test-suite-directory-2>/
      ...
```

The tool then iterates through the `tests/` directory tree and for each `<composition_base_file_name>`, finds a corresponding `<composition_base_file_name>.yaml` within a top-level `resources/` directory.  If the file is found, we then orchestrate the execution of `crossplane beta render...` based on the test suite sub-directories present under the `<composition_base_file_name>` directory.

The orchestration involves _injection_ of `function-unit-test` as an additional function step with the contents of `_n_-xr.assertions.yaml` used as the desired assertions to check.  If `observed.yaml` is present in the suite directory, we include it in the `crossplane beta render...` command arguments.  Same is true for the optional `environment.yaml`.  We then capture return codes and report back the overall status.

#### Current Gaps

1. This approach provides us with a test framework for implementing assertion-based testing of compositions within a given repository.  What we've found in this approach that, I think, represents an easily-filled gap with the crossplane cli, is lack of an assertion mechanism that we can apply to the output of `crossplane beta render...`.  

2. Invoking `crossplane beta render test-xr.yaml ... | crossplane beta test -f test-xr-assertions.yaml` is pretty slow if you want to iterate through a number of test cases.  Having a robust suite of test cases is a requirement for producing high-quality APIs for our end users to consume and being able to rapidly validate all of those test cases is really nice to have for composition developers to get their jobs done more quickly.  Secondarily, with a simple UNIX-philosphy-like pipeline-of-commands approach, the wheel -- with respect to composition testing -- will be re-invented over and over again, leading different teams to design different testing frameworks that miss out on the community's shared knowledge of what testing involves.

Now, I'm not claiming to be the expert on composition testing, but myself and my team have learned a lot about testing compositions during development and feel that we have a decent handle on the concerns that are involved.  Working with the Crossplane community to articulate a test framework design for composition development can be a huge benefit to the community overall, taking the guesswork out of testing for many teams.  

### How could Crossplane help solve your problem?
1. Given lack of simple support for assertions that are not directly coupled to the Composition implementation i.e. function-unit-test, a simple tool that incorporates CEL, similar to `function-unit-test`, but as a crossplane cli subcommand would allow us to run this as a pipeline, i.e.

```
$ crossplane beta render test-xr.yaml ... | crossplane beta test -f test-xr-assertions.yaml
```
allowing for seamless offline unit testing of compositions without having to _modify_ the composition during testing.  

2. Given these concerns -- test execution "slowness" coupled with the open-ended approach of a simple pipeline-of-commands approach, I'd like to propose a second possible Crossplane command extension, `crossplane test-runner`.

`crossplane test-runner` will take as input a test framework file.  The test framework file would represent a TestFramework object which would describe the

1. A list of compositions
2. For each composition, a list of required functions
3. For each composition, a list of suites
4. For each suite, optional additional context via fileRef or inline
5. For each suite, optional additional observed data via fileRef or inline
6. For each suite, a list of input XR and XR assertions via fileRefs or inline

`test-runner` would then consume the the TestFramework input file and orchestrate the execution of  the tests, composing `crossplane beta render` against the input specified in the TestFramework input. 

Example framework definition

```
apiVersion: crossplane.io/v1alpha1
kind: TestFramework
spec:
  compositions:
  - fileRef: resources/my-composition.yaml
    functions:
      - docker-upstream.apple.com/crossplane-contrib/function-go-templating:v0.4.1
      - docker-upstream.apple.com/crossplane-contrib/function-auto-ready:v0.2.1
    suites:
      - id: suite-1
        # no observed data means initial reconciliation
        context:
          ...
        extraResources:
          ...
        tests:
          - xr: tests/my-composition/suite-1/1-xr.yaml
             assertions: tests/my-composition/suite-1/1-xr-assertions.yaml
          - xr: tests/my-composition/suite-1/2-xr.yaml
             assertions: tests/my-composition/suite-1/2-xr-assertions.yaml
      - id: suite-2
        # incorporate observed status i.e. pretend like this is a later reconciliation
        observed:
          fileRef: tests/my-composition/suite-2/observed.yaml
        context:
          ...
        extraResources:
          ...
        tests:
          - xr: tests/my-composition/suite-2/1-xr.yaml
             assertions: tests/my-composition/suite-2/1-xr-assertions.yaml
          - xr: tests/my-composition/suite-2/2-xr.yaml
             assertions: tests/my-composition/suite-2/2-xr-assertions.yaml
```    

The model describe above would allow a composition author to model the entire lifecycle of an XRs reconciliation against a given composition and apply assertions to each stage of reconciliation from the initial no-observation reconciliation to subsequent reconciliations containing required data.  To run an entire set of unit tests against multiple compositions and multiple XR input use cases for each composition, would simply require the execution of `crossplane test-runner -f test-framework-input.yaml`, causing the expected tests and test cases to be run. 

In the above example, we can allow the _explicit_ definition of xr/assertion tuples OR we can allow them to be discovered implicitly by looking for files matching an expected convention.  This allows folks to skip pain-staking implementation of a TestFramework definition OR to fully control the TestFramework definition, depending on their likes/dislikes.

`crossplane test-runner` can be made to support different output "drivers" to facilitate integration with existing tools that understand test framework output, likely facilitating easier integration with IDEs and other tooling.

I am happy to contribute and collaborate on design and implementation to this if the community feels it would be useful.
