### ISSUE TITLE
Functions Should Support Pulling from Non-HTTPS Endpoints

### ISSUE THREAD

**Issue by blakeromano** [crossplane/crossplane#5798]
### What problem are you facing?

I want to be able to run my Crossplane Composition Function in local testing with `idpbuilder` from CNOE. Where we use a gitea registry locally it is exposed on `gitea.cnoe.localtest.me:8443` and when I try and create a function resource like 

```yaml
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: xfn
spec:
  package: gitea.cnoe.localtest.me:8443/giteaadmin/xfn:latest
  ignoreCrossplaneConstraints: true
  skipDependencyResolution: true
```

The following error is emitted:

```yaml
  status:
    conditions:
    - lastTransitionTime: "2024-06-23T17:43:42Z"
      message: 'cannot unpack package: failed to fetch package digest from remote:
        failed to fetch package descriptor with a GET request after a previous HEAD
        request failure: Get "https://gitea.cnoe.localtest.me:8443/v2/": dial tcp
        [::1]:8443: connect: connection refused: Get "https://gitea.cnoe.localtest.me:8443/v2/":
        dial tcp [::1]:8443: connect: connection refused'
      reason: UnpackingPackage
      status: "False"
      type: Installed
```

I am assuming fue to it is requiring 443 or because of the issue here https://github.com/crossplane/crossplane/issues/5581? 

If this would be solved by #5581 feel free to close as a duplicate.

### How could Crossplane help solve your problem?

By fixing this issue it will help improve developer experience when writing composition functions.
