### ISSUE TITLE
missing family dependency for custom provider

### ISSUE THREAD

**Issue by erolg** [crossplane/crossplane#5799]
### What happened?

When I attempting to install a custom provider that depends on a custom family package, Crossplane encounters an error message stating "`cannot resolve package dependencies: missing dependencies: [registry.corp.com/....]`".

If I manually install the family package, it deploys successfully.

I suspect that this error is because I did not give a pull secret to the dependency image, because if I deploy it as a separate package, I can easily deploy it.  Is it true? If I need to give image a separate pull secret to the dependency packages, how can I do this?

Expected behavior: Crossplane should successfully install the custom provider after locating and resolving all required dependencies, including the family package.

### How can we reproduce it?

1. Install a Crossplane
2. Attempt to install a custom provider manifest that depends on a family package :
````yaml
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-x-foo
  namespace: crossplane-system
spec:
  package: registry.corp.com/provider-x/foo/xpkg:0.1.0
  packagePullSecrets:
    - name: registry-secret
````

foo package's crossplane.yaml:
````yaml
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-x-foo
labels:
    pkg.crossplane.io/provider-family: provider-family-x
spec:
  controller: {}
  crossplane:
    version: '>=v1.12.1-0'
  dependsOn:
  - provider: registry.corp.com/provider-x/family/xpkg
    version: ">=v0.0.0"
````

family package's crossplane.yaml:
````yaml
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-family-x
labels:
    pkg.crossplane.io/provider-family: provider-family-x
````

3. Observe the error message "cannot resolve package dependencies: missing dependencies: [registry.corp.com/provider-x/family/xpkg]".

4. If I try install the family package manually, it successfully deployed with the following:

````yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-x
  namespace: crossplane-system
spec:
  package: registry.corp.com/provider-x/family/xpkg:0.1.0
  packagePullSecrets:
    - name: registry-secret
````

### What environment did it happen in?

Crossplane version: 1.16
