### ISSUE TITLE
Readiness check customization/disable for go templating

### ISSUE THREAD

**Issue by l-rossetti** [crossplane/crossplane#5800]
### What problem are you facing?
I would like to disable readiness checks for ProviderConfig(s) created by a composition, when using go templating function instead of patch and transform

### How could Crossplane help solve your problem?
Crossplane could support an annotation on the resources to disable readiness checks or to customize them, similarly to what is supported by patch and transform

**Comment by bobh66** [comment]
`function-go-templating` has an annotation to override resource readiness as described here:  https://github.com/crossplane-contrib/function-go-templating/?tab=readme-ov-file#using-this-function

```
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: bucket
    gotemplating.fn.crossplane.io/ready: "True"
spec: {}
```
Does this do what you need?
