### ISSUE TITLE
Allow dynamic defaultCompositionRef and enforcedCompositionRefs

### ISSUE THREAD

**Issue by Avarei** [crossplane/crossplane#5806]
### What problem are you facing?

I would like to deploy a Configuration containing XRDs and Compositions to various different environments. But most environments differ in some ways. (e.g. a XRD for provisioning VMs that has different compositions for AWS, Azure and GCloud)
I would like to be able to use the same XRD for all Environments. At the same time I don't want to ask the Consumer which requests the XR/XRC to select the appropriate Composition in most cases.

So a way to select the appropriate Composition based on the Current environment would be helpful.

### How could Crossplane help solve your problem?

There are several ways I see how this could be solved.

1. Using EnvironmentConfig
This would allow using the current environmentConfigs as a reference on which compositionfunction should be used. though it would be weakly typed.
Here is what a XRD could look like
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvirtualmachine.custom-api.example.org
spec:
  defaultCompositionRef: 
    environmentConfigRef:
      name: cloud-environment
      key: xrd-virtualmachine
```
the referenced environmentconfig could look like this:
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: cloud-environment
data:
  xrd-virtualmachine: xvirtualmachine-azure
```
This would be easy to set seperately on each environment.

2. Adding Paramters to set compositionRefs on Configuration.
3. Create a new resource like CompositionSelector that can be referenced by XRD.spec.defaultCompositionRef.compositionSelectorRef.
This type could allow matchLabels in addition to matchName.
