### ISSUE TITLE
Proposal: Write a generic function to surface composed resource errors on the claim

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5807]
### What problem are you facing?

With https://github.com/crossplane/crossplane/issues/5402 merged, it'll be possible for functions to:

* Read the status conditions of composed resources
* Write custom status conditions and events to claims (and XRs)

This means you could write a function that translates composed resource errors, presenting more user friendly versions on the claim. Currently you'd need to write a function in Go or Python. Using an open-ended function like function-kcl, function-cue, or function-pkl might work too once they've been updated to the latest function-sdk-go.

For others, a generic function dedicated to error translation/presentation could be useful.

### How could Crossplane help solve your problem?

Build a generic function that exposes the new functionality. Here's a sketch of a potential direction:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: NoSQL
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
    # Omitted for brevity
  - step: claim-status
    functionRef:
      name: function-result-extractor
    input:
      apiVersion: extractor.fn.crossplane.io/v1alpha1
      kind: Results
      results:
      - result:
          target: Claim
          severity: Warning
          message: Internal database error: ${error}
          status:
            type: DatabaseReady
            condition: "False"
            reason: InternalError
        triggers:
        - resourceName: rdsinstance
          type: StatusCondition
          status:
            type: Synced
            condition: "False"
            message: "Some AWS error: (?P<error>)"
```

The idea is you configure an array of results. Each result takes a series of triggers. If all triggers are true, the result is emitted. Each trigger uses regular expressions to match status conditions of composed resources.

**Comment by negz** [comment]
CC @dalton-hill-0.

**Comment by dalton-hill-0** [comment]
@negz 

I'm starting to look into this. I made a few changes and added some fields to your sketch above. Let me know what you think. In the meantime I'll start tinkering around with what I have.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: NoSQL
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
    # Omitted for brevity
  - step: claim-status
    functionRef:
      name: managed-resource-hook
    input:
      apiVersion: managed-resource-hook.fn.crossplane.io/v1alpha1
      kind: ManagedResourceHook
      lifecycleHooks:
        # Not using a map here so that the resourceName can be a wildcard. For
        # example, if you had rdsinstance-a, rdsinstance-b, you could have a
        # resourceName of "rdsinstance-\w+" and the same hook could work for both
        # resources.
        - resourceName: "rdsinstance"
          # There is a desired resource but no observed resource.
          onCreate:
            # For usage, see setConditions field for onMatches.
            setConditions: []
          # There is no desired resource but an observed resource still exists.
          onDelete:
            setConditions: []
          # The desired resource does not match the observed resource.
          onUpdate:
            setConditions: []
            # Fields that will determine equality between observed and desired MR.
            # This will allow us to ignore defaulted fields that are not cared
            # about such as time stamps..
            equalityFields:
              - "spec.some.field.to.compare"
          # There is no desired resource and no observed resource. Useful if you
          # have a resource that can be turned on/off.
          onNone:
            setConditions: []
      statusConditionHooks:
        - matchConditions:
            # NOTE: matchConditions to be "AND-ed" together. This will allow use
            # of regex matchers spanning multiple resources.
            # NOTE: If any field in the condition is not specified, it should be treated
            # as a wildcard.
            - resourceName: "rdsinstance"
              type: Synced
              condition: "False"
              message: "Some AWS error: (?P<error>)"
          setConditions:
            - type: DatabaseReady
              condition: "False"
              reason: InternalError
              message: "Internal database error: {{ .error }}"
              target: ConditionAndClaim
              # If true, will override a condition if it is already set.
              force: true
```
