### ISSUE TITLE
Unhelpful Error message when Composition Function with Extra Resources errors

### ISSUE THREAD

**Issue by Avarei** [crossplane/crossplane#5824]
### What happened?

I am developing a Composition which uses Extra Resources. My template works fine in the first iteration where I request ExtraResources. In the Second Iteration the Template errors due to some issue.
Crossplane does not publish the error from the Composition function but instead only says:
`crossplane: error: cannot render composite resource: requirements didn't stabilize after the maximum number of iterations (5)`

I think the reason Crossplane acts the way it does is due to the CompositionFunction keeps switching between requesting ExtraResources and erroring (and therefore not requesting ExtraResources). 

I think this should be handled more gracefully by crossplane. 

### How can we reproduce it?

https://gist.github.com/Avarei/c08da88a39142ef156264229f72d4d32

composition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bad-error-example
spec:
  compositeTypeRef:
    apiVersion: example/v1
    kind: xFoo
  mode: Pipeline
  pipeline:
    - step: template
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: ExtraResources
            requirements:
              icecream:
                apiVersion: example/v1
                kind: Example
                matchLabels: {}
            ---
            {{- if $.extraResources.icecream }}
            {{- fail "i want to fail" }}
            {{- end }}
```

extra.yaml
```yaml
---
apiVersion: example/v1
kind: Example
metadata:
  name: foo
```

function.yaml
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: ghcr.io/avarei/function-go-templating:extra-resources-2
```

xr.yaml
```yaml
apiVersion: example/v1
kind: xFoo
metadata:
  name: myfoo
```

with all the files present run

```sh
crossplane beta render --extra-resources=extra.yaml xr.yaml composition.yaml function.yaml
```

### What environment did it happen in?
Crossplane version: v1.16.0
