### ISSUE TITLE
Not able to patch a value with a period "." in its name

### ISSUE THREAD

**Issue by anjuchaurasiya** [crossplane/crossplane#5825]
### How can we reproduce it?

```
- name: grafana-crossplane-release
  base:
    apiVersion: helm.crossplane.io/v1beta1
    kind: Release
    metadata:
      name: grafana-crossplane
    spec:
      forProvider:
        chart:
          name: grafanaChartName
          repository: "bitnami"
          version: "0.1.0"   
        values:
          grafana:
            grafana.ini:
              server:
                domain: grafana-crossplane-poc.example.com
                root_url: https://grafana-crossplane-poc.example.com 
              auth.generic_oauth:
                api_url: https://<id-crossplane-poc.example.com>/realms/poc/*
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                kubernetes.io/tls-acme: "true"
                nginx.ingress.kubernetes.io/backend-protocol: HTTP
                cert-manager.io/cluster-issuer: letsencrypt-prod
              path: /
              tls:
                - hosts:
                    - grafana-crossplane-poc.example.com
                  secretName: grafana-crossplane-poc.example.com-tls
              #replace "example.org" with poc tenant DNS
              hosts:
                - grafana-crossplane-poc.example.com
      providerConfigRef:
        name: provider-helm
  patches:
    - type: PatchSet
      patchSetName: config
    - fromFieldPath: "spec.grafanaChartName"
      toFieldPath: "spec.forProvider.chart.name"
    - fromFieldPath: "spec.grafanaVersion"
      toFieldPath: "spec.forProvider.chart.version"
    - fromFieldPath: "spec.grafanaRepository"
      toFieldPath: "spec.forProvider.chart.repository"
    - fromFieldPath: "spec.keycloakHostname"
      toFieldPath: 'spec.forProvider.values.grafana.["grafana.ini"].["auth.generic_oauth"].api_url'
      transforms: 
        - type: string 
          string: 
            type: Format
            fmt: https://%s/realms/poc/*
```

### What environment did it happen in?
Crossplane version:  
xpkg.upbound.io/crossplane/crossplane:v1.15.2
