### ISSUE TITLE
DeploymentRuntimeConfig fails to completely update SecurityContext of the Deployment

### ISSUE THREAD

**Issue by gbvanrenswoude** [crossplane/crossplane#5827]
When running Crossplane providers on something opiniated about SecurityContext like the OpenShift distro for example, you need to leave the SecurityContext empty for said distro to do it's thing with it. 

Using the DeploymentRuntimeConfig:
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-config
  namespace: crossplane-system
spec:
  deploymentTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: aws-config
        app.kubernetes.io/version: 1.0.0
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: aws-config
          app.kubernetes.io/version: 1.0.0
      template:
        spec:
          securityContext: {}
          containers:
            - imagePullPolicy: IfNotPresent
              name: package-runtime
          securityContext: {}
```
on a Provider:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  ignoreCrossplaneConstraints: true
  package: xpkg.upbound.io/upbound/provider-aws-s3:v1.1.0
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: aws-config
  skipDependencyResolution: true
```
results in the provider Pod still having
```yaml
  securityContext:
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 2000
```
in the yaml realized in `etcd`, resulting in launch failure if you would launch on for example OpenShift. How can I leverage the DeploymentRuntimeConfig to set the securityContext of the Pod correctly? ControllerConfig deprecation is coming up but the DeploymentRuntimeConfig does not fill it's functionality in this regard.

I might be wrong but I think the relevant piece of code handling this is https://github.com/crossplane/crossplane/blob/master/internal/controller/pkg/revision/runtime.go#L182

The issue is you can't really specify the uid and guid as anything else as an int based on the OAS3, or it will be omitted from being in etcd. So, the code will always either find an int value, or use 2000, which is not the wrong way to go about it, there is simply just no real way of "unspecifying" it.

**Comment by gbvanrenswoude** [comment]
Workaround: ```kubectl patch deployment function-auto-ready-uuid -n crossplane-system --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/securityContext", "value": {}}]'```

**Comment by bobh66** [comment]
This works for us on OpenShift:
```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-auto-ready
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            securityContext: {}
          securityContext: {}
```
