### ISSUE TITLE
Support passing web identity credentials to Composition Functions

### ISSUE THREAD

**Issue by LCaparelli** [crossplane/crossplane#5830]
### What problem are you facing?

Composition Functions that require to authenticate via web identity credentials are left to their own devices on how to do that. It would be nice if Crossplane provided a mechanism to inject these credentials somehow, like ProviderConfigs do.

For example, https://github.com/crossplane-contrib/provider-upjet-aws installs a ProviderConfig that even allows for role chaining, especially useful for cross-account scenarios (think Crossplane managing several other clusters and cloud accounts in a hub-spoke architecture).

```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
spec:
  assumeRoleChain:
  - roleARN: arn:aws:iam::000000000000:role/some-role-at-destination-account
  credentials:
    source: WebIdentity
    webIdentity:
      roleARN: arn:aws:iam::111111111111:role/some-role-at-origin-account
```

I believe Secrets (already implemented by #3718) are not an option here because creds are generated only when the role is assumed, and each reconciliation may need to authenticate to a different account.

### How could Crossplane help solve your problem?

Provide a way for composition functions to easily authenticate via web identity tokens, with the option to chain roles to facilitate cross-account authentication. 

It's important that the solution allows for the authentication to change from one call to the function to another, because we might be reconciling an XR that composes a managed resource from account A at one call, then another from account B on the next call, all being rendered by the same `Composition`.

**Comment by LCaparelli** [comment]
My initial instinct was to create a `FunctionConfig` resource that the function would consult at runtime. It would have a couple of fixed fields, like `spec.credentials`, but the core configuration would be free-form, imitating what has been previously done with `ProviderConfig` and similar `*Class` resources (eg, `IngressClass`).

But with `ProviderConfig`, the field that controls which one will be used is part of the rendered managed resource (`spec.providerConfigRef`). This means we can use the composition itself to decide which `ProviderConfig` to use dynamically (eg, using a `match` transform to decide which account to store DNS records in based on their name; "foo.bar" goes to account A, uses `ProviderConfig` `a-account`).

We're not so lucky with functions, in the sense that we can't use patch-and-transform logic to decide this there. With this approach, we would probably need to also define a way to determine which `FunctionConfig` to use **dynamically**. Maybe something like:

```yaml
  - step: some-step
    functionRef:
      name: function-foo
    functionConfigRef:
      # for trivial use-cases, where the same config will be used in all calls
      #  type: name
      #  name: foo-config
      type: match
      match:
        fromFieldPath: spec.recordName
        fallbackTo: Value
        fallbackValue: default
        patterns:
        - regexp: "(.*).foo.bar"
          result: domains-account
          type: regexp
        - regexp: "(.*).legacy.domain"
          result: legacy-account
          type: regexp
```

And propagate the resulting ref into the function's request.
