### ISSUE TITLE
`crossplane xpkg build` seems not checking the file name

### ISSUE THREAD

**Issue by cychiang** [crossplane/crossplane#5836]
### What happened?

According to [this](https://docs.crossplane.io/latest/concepts/packages/#create-a-configuration) docs, to create a Crossplane package, it needs to place `crossplane.yaml` in the root folder.

However, it seems not the case because you can name the YAML file in any name as long as there is only one `Configuration` file in the folder.

### How can we reproduce it?

For example:

```
├── v1
    └── test.yaml
```
where `test.yaml` is:
```
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: v1
spec:
  dependsOn:
    - ...
  crossplane:
    version: ...
```
From above setup, you can generate package successfully with `crossplane xpkg build --package-root=v1`. 

So the requirements to generate a Crossplane package seems to me like:
- Create a folder as a root folder, and put a YAML file that follow the `Configuration` schema from `meta.pkg.crossplane.io/v1alpha1`
- Create subfolder in the root folder with any name, and put any additional YAML files for the configuration
- There is no restriction on the YAML file name
- Run build command, and it will generate `xpkg` image. 

### What environment did it happen in?
Crossplane version: Client Version: v1.16.0
