### ISSUE TITLE
On update connection details secret keys are merged with existing secret keys

### ISSUE THREAD

**Issue by tenitski** [crossplane/crossplane#5842]
### What happened?

When a secret with connection details is updated, new secret keys are merged with any existing secret keys, instead of replacing them.

This causes the following effects:
- if connection details key was removed from a composition, it is still left behind in the connection details secret;
- if a secret key was renamed in a composition, the old secret key with the old value is still left in the secret.

The problem with the current implementation is the unexpected behavior: 
user is expecting that if a secret key is not referenced anymore, the value is gone and an application can fall back on ENV defaults. However an application gets out-of-date connection details value instead.

### How can we reproduce it?

Create resource with

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
...
spec:
  mode: Pipeline
  ...
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            data:
              WHATEVER: "{{ printf "111" | b64enc}}"
    - step: ready
      functionRef:
        name: function-auto-ready
```

Connection details secret:
```
apiVersion: v1
kind: Secret
data:
  WHATEVER: MTEx
```

Update and apply the composition (or desired state if some logic, broken in both scenarios):

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
...
spec:
  mode: Pipeline
  ...
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            data:
              WHATEVER_NEW: "{{ printf "222" | b64enc}}"
    - step: ready
      functionRef:
        name: function-auto-ready
```

Connection details secret:
```
apiVersion: v1
kind: Secret
data:
  WHATEVER: MTEx
  WHATEVER_NEW: MjIy
```

### What environment did it happen in?
Crossplane version: 1.16.0
