### ISSUE TITLE
ManagedResource duplication after enabling --enable-ssa-claims flag in Crossplane v1.15.0

### ISSUE THREAD

**Issue by drengskapr** [crossplane/crossplane#5862]
### What happened?

Hello there! Last week I was fixing the problem with Claim annotation changes which were not reflected in the corresponding XR like [this one](https://github.com/crossplane/crossplane/issues/4315). Flag `--enable-ssa-claims` helped me to fix stale annotations. After solving the problem I disabled the `--enable-ssa-claims`.

Today I noticed that all my `ManagedResources` (MR) got duplicated within my control plane k8s cluster (but not actual resources in the cloud). I tried to delete the duplicate `MR` in one of my dev envs but this caused the deletion of the actual resource in the cloud. Deletion of the original `MR` gave the same result. Later I found related [issue](https://github.com/crossplane/crossplane/issues/5498) which is precisely my situation. It says that this bug is fixed in Crossplane v1.16.

The question is: if I upgrade to v1.16 and enable `--enable-ssa-claims` again will duplicated `ManagedResources` disappear? Or I need some manual actions? If so then what you advice me to do? I want to get rid of duplicates and retain my actual resources in the cloud (production is affected and if I lose anything there that will be a disaster).

P.S. I use native patch & transform.

### How can we reproduce it?

Create a `Composition`:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-postgres-database
spec:
  compositeTypeRef:
    apiVersion: gcp.mycompany.com/v1
    kind: XPGDatabase
  patchSets:
    - name: provider-config-patch
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: spec.providerConfigRef.name
        toFieldPath: spec.providerConfigRef.name
  resources:
    - name: PostgresDatabase
      base:
        apiVersion: sql.gcp.upbound.io/v1beta1
        kind: Database
        spec:
          forProvider:
            project: default
            instance: default
            charset: UTF8
            collation: en_US.UTF8
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: spec.databaseName
        toFieldPath: metadata.annotations[crossplane.io/external-name]
      - type: FromCompositeFieldPath
        fromFieldPath: spec.projectId
        toFieldPath: spec.forProvider.project
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parentClusterName
        toFieldPath: spec.forProvider.instance
      - type: PatchSet
        patchSetName: provider-config-patch
```

create an `XRD`:

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xpgdatabases.gcp.mycompany.com
spec:
  group: gcp.mycompany.com
  names:
    kind: XPGDatabase
    plural: xpgdatabases
  claimNames:
    kind: PGDatabase
    plural: pgdatabases
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              databaseName:
                type: string
              projectId:
                type: string
              parentClusterName:
                type: string
              providerConfigRef:
                type: object
                properties:
                  name:
                    type: string
                required:
                  - name
            required:
              - databaseName
              - projectId
              - parentClusterName
              - providerConfigRef
```
and create a `Claim`:

```
apiVersion: gcp.mycompany.com/v1
kind: PGDatabase
metadata:
  name: dev4-backend-db
spec:
  databaseName: backend
  projectId: project-dev4-001
  parentClusterName: dev4-postgres-cluster
  providerConfigRef:
    name: gcp-main-config
```
Check created database:

```
kubectl -n env-dev4 get databases
NAME                           SYNCED   READY   EXTERNAL-NAME   AGE
dev4-backend-db-78tmm-d2gnz    True     True    backend         125d
```

Enable the `--enable-ssa-claims` flag, check created database again:

```
NAME                           SYNCED   READY   EXTERNAL-NAME   AGE
dev4-backend-db-78tmm-d2gnz    True     True    backend         125d
dev4-backend-db-78tmm-7k9hm    True     True    backend         6d5h  # a duplicate
```

### What environment did it happen in?
Crossplane version:  1.15.0
Kubernetes version: 1.28.5-gke.1217000
Kubernetes distribution: GKE
Crossplane provider: upbound/provider-family-gcp v1.2.0
