### ISSUE TITLE
Fix creationTimestamp handling in crossplane beta render  command

### ISSUE THREAD

**Issue by kahirokunn** [crossplane/crossplane#5871]
### What problem are you facing?

When using the `crossplane beta render` command with a custom resource (XR) that includes a `creationTimestamp`, the command ignores the specified timestamp and generates a new one. This behavior causes issues when trying to implement snapshot tests for compositions that rely on the `creationTimestamp`.

Specifically, I have a composition that includes the following code:

```
{{- $creationTimestamp := date "20060102150405" .observed.composite.resource.metadata.creationTimestamp | replace ":" "" -}}
```

The intention is to use the `creationTimestamp` in further processing within the composition. However, because the `beta render` command regenerates this timestamp, it becomes impossible to create consistent snapshot tests, as the output changes on each run.

For example, given an XR like this:

```yaml
apiVersion: hoge.crossplane.io/v1beta1
kind: XHoge
metadata:
  name: sample1
  namespace: default
  labels:
    crossplane.io/claim-name: sample1
    crossplane.io/claim-namespace: default
  creationTimestamp: "2028-08-08T08:08:08Z"
spec: {}
```

The `creationTimestamp` specified in the XR is ignored when running `crossplane beta render xr.yaml composition.yaml functions.yaml`.

### How could Crossplane help solve your problem?

To address this issue, I propose one of the following solutions:

1. Add an option to the `crossplane beta render` command that allows users to fix or preserve the `creationTimestamp`. This could be implemented as a flag, such as `--preserve-creation-timestamp` or `--fixed-creation-timestamp=<value>`.

2. Modify the `beta render` command to respect the `creationTimestamp` if it's already present in the input YAML file. This would allow users to specify a fixed timestamp in their XR for testing purposes.

Either of these solutions would enable consistent snapshot testing for compositions that depend on the `creationTimestamp`. It would also provide more flexibility for users who need to work with fixed timestamps in their development and testing workflows.

This enhancement would greatly improve the testability of Crossplane compositions and make it easier for developers to create reliable, repeatable tests for their custom resources and compositions.
