### ISSUE TITLE
Resource refs not updated for broken compositions

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane/crossplane#5910]
### What happened?
On a clean cluster, I tried to deploy both a provider + providerConfig tuple in a composite resource.
With `function-patch-and-transform` this works as expected, eventually both are created.
With `function-go-template` I found the following error:

```
cannot compose resources: cannot get existing composed resources: cannot get composed resource: providerconfigs.aws.upbound.io "go" is forbidden: User "system:serviceaccount:crossplane-system:crossplane" cannot get resource "providerconfigs" in API group "aws.upbound.io" at the cluster scope
``` 

> With `function-sequencer` or implicit dependencies I could workaround this, but wondering it this is expected behavior.

Afterwards I deleted the ProviderConfig code from the composition, applied and got a new composition revision. Double-checked that the new revision got applied (event is created and composition revision ref updated).

**However** the reference refs stay as before, resulting in the same locking state.

```
  Resource Refs:
    API Version:  aws.upbound.io/v1beta1
    Kind:         ProviderConfig
    Name:         go
    API Version:  pkg.crossplane.io/v1
    Kind:         Provider
    Name:         provider-aws-eks
Status:
  Conditions:
    Last Transition Time:  2024-08-21T22:14:34Z
    Message:               cannot compose resources: cannot get existing composed resources: cannot get composed resource: providerconfigs.aws.upbound.io "go" is forbidden: User "system:serviceaccount:crossplane-system:crossplane" cannot get resource "providerconfigs" in API group "aws.upbound.io" at the cluster scope
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
```

### How can we reproduce it?

On a clean cluster (no providers installed):

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    channel: manual
    crossplane.io/xrd: xgotests.foo.bar
    service: gotest
  name: xgotests.foo.bar
spec:
  compositeTypeRef:
    apiVersion: foo.bar/v1alpha1
    kind: XGotest
  mode: Pipeline
  pipeline:
  - step: go-templating
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |-
          ---
          apiVersion: pkg.crossplane.io/v1
          kind: Provider
          metadata:
            name: provider-aws-eks
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: provider
          spec:
            package: xpkg.upbound.io/upbound/provider-aws-eks:v1.8.0
          ---
          apiVersion: aws.upbound.io/v1beta1
          kind: ProviderConfig
          metadata:
            name: go
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: provider-config
          spec:
            credentials:
              source: IRSA
  - functionRef:
      name: function-auto-ready
    step: ready
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.5.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1
---
apiVersion: foo.bar/v1alpha1
kind: Gotest
metadata:
  name: test
spec: {}

```

### What environment did it happen in?
Crossplane version: v1.16.0
function-go-templating:v0.5.0
