### ISSUE TITLE
ManagementPolicy Late Initialize W/Provider Pod Restart Triggers Unexpected Behaviors

### ISSUE THREAD

**Issue by blakeromano** [crossplane/crossplane#5918]
### What happened?

There has been a handful of issues with `LateInitalize` Management Policy which is ideal when using `initProvider` because you can run into infinite reconciliation loops with LateInitialize on when you have something in `initProvider` where the lateinit puts it in the forProvider section and then Crossplane providers can get into an infinite reconciliation loop.

I can easily reproduce an issue where when a Provider within the AWS Family is terminated (by normal pod eviction or by a manual deletion) resources with late initalize not added, essentially lose track of current state due to the loss of `external-name` annotation on the resource.

### How can we reproduce it?

Standup Crossplane using an ArgoCD Application:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://charts.crossplane.io/stable'
      targetRevision: 1.16.0
      helm:
        releaseName: crossplane
        values: |
          args:
            - "--enable-environment-configs"
      chart: crossplane
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

Spin up the family provider and cloudfront provider for AWS (also create a secret with AWS credentials
```yaml
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v1.11.0
  controllerConfigRef:
    name: aws-config
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
spec:
  args:
    - --debug
  podSecurityContext:
    fsGroup: 2000
  credentials:
    secretRef:
      key: creds
      name: aws-secret
      namespace: crossplane-system
    source: Secret
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudfront
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudfront:v1.11.0
  controllerConfigRef:
    name: aws-config
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  namespace: crossplane-system
spec:
  credentials:
    secretRef:
      key: creds
      name: aws-secret
      namespace: crossplane-system
    source: Secret
```

Create a resource like the following:
```yaml
apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: Distribution
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/distribution
  labels:
    testing.upbound.io/example-name: distribution
  name: example-distribution
spec:
  providerConfigRef:
    name: aws-provider
  managementPolicies:
    - Create
    - Update
    - Delete
    - Observe
  initProvider:
    webAclId: ""
  forProvider:
    comment: Some comment
    defaultCacheBehavior:
      - allowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
        cachedMethods:
          - GET
          - HEAD
        defaultTtl: 3600
        forwardedValues:
          - cookies:
              - forward: none
            queryString: false
        maxTtl: 86400
        minTtl: 0
        targetOriginId: customOrigin
        viewerProtocolPolicy: allow-all
    defaultRootObject: index.html
    enabled: true
    isIpv6Enabled: true
    orderedCacheBehavior:
      - allowedMethods:
          - GET
          - HEAD
          - OPTIONS
        cachedMethods:
          - GET
          - HEAD
          - OPTIONS
        compress: true
        defaultTtl: 86400
        forwardedValues:
          - cookies:
              - forward: none
            headers:
              - Origin
            queryString: false
        maxTtl: 31536000
        minTtl: 0
        pathPattern: /content/immutable/*
        targetOriginId: customOrigin
        viewerProtocolPolicy: redirect-to-https
      - allowedMethods:
          - GET
          - HEAD
          - OPTIONS
        cachedMethods:
          - GET
          - HEAD
        compress: true
        defaultTtl: 3600
        forwardedValues:
          - cookies:
              - forward: none
            queryString: false
        maxTtl: 86400
        minTtl: 0
        pathPattern: /content/*
        targetOriginId: customOrigin
        viewerProtocolPolicy: redirect-to-https
    origin:
      - customOriginConfig:
          - httpPort: 80
            httpsPort: 443
            originKeepaliveTimeout: 5
            originProtocolPolicy: https-only
            originReadTimeout: 10
            originSslProtocols:
              - TLSv1.2
        domainName: app.my.cloud
        originId: customOrigin
    priceClass: PriceClass_200
    region: us-east-1
    restrictions:
      - geoRestriction:
          - locations:
              - US
              - CA
              - GB
              - DE
            restrictionType: whitelist
    tags:
      Environment: production
    viewerCertificate:
      - cloudfrontDefaultCertificate: true
```

Wait for the resource to be ready, created and fully synced.

Delete the Cloudfront provider pod. `kubectl delete pod <pod_name>`

Notice the conditions on distribution go to:
```yaml
  Conditions:
    Last Transition Time:  2024-08-28T14:54:30Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2024-08-28T15:01:36Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-08-28T14:59:18Z
    Reason:                Success
    Status:                True
    Type:                  LastAsyncOperation
```

It will also go to try and create a new distribution.

### What environment did it happen in?
Crossplane version: 1.16
AWS Provider Version: 1.11.0
Kubernetes Version: 1.29
Kubernetes Distribution: Can Reproduce using Kind or EKS

### More Details

This seems to be related to other issues that have already been reported like:
* https://github.com/crossplane-contrib/provider-upjet-azure/issues/802

I am attaching logs I was able to grab from the cloudfront provider pod with debug logging as well as a redacted version of the resource when on a watch command.

[out.log](https://github.com/user-attachments/files/16788738/out.log)
[resource.txt](https://github.com/user-attachments/files/16788740/resource.txt)

**Comment by blakeromano** [comment]
I can agree with your assessment on it being only for asynchronous resources.

I tested a bucket defined as:
```yaml
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: example-123-bucket
spec:
  forProvider:
    objectLockEnabled: true
    region: us-east-2
    tags:
      Name: SampleBucket
  initProvider:
    tags:
      foo: bar
  managementPolicies:
    - Create
    - Update
    - Delete
    - Observe
  providerConfigRef:
    name: aws-provider
```

And tried deleting the provider pod and did not see the same behavior as cloudfront distributions (which are an async resource).

I do wonder if this should be apart of a bigger thought on how we do asynchronous reconciliation in Crossplane as a whole as I know I have observed other bugs that happen due to the current implementation of Crossplane's asynchronous reconciliation method in the crossplane runtime with upjet.

I do feel this is a fairly high priority bug for management policies and should block https://github.com/crossplane/crossplane/issues/4952

**Comment by lsviben** [comment]
> I do wonder if this should be apart of a bigger thought on how we do asynchronous reconciliation in Crossplane as a whole as I know I have observed other bugs that happen due to the current implementation of Crossplane's asynchronous reconciliation method in the crossplane runtime with upjet.
> 
> I do feel this is a fairly high priority bug for management policies and should block #4952

Yes, this is definately something that should be fixed as part of a bigger thought on how we do upjet asynchronous reconciliation. The current approach where it "lies" to the crossplane-runtime reconciler about LateInitialization to get an update clashes directly with the management policies. 

You mentioned noticing some other bugs tied to asynchronous reconciliation, do you have some more info?

**Comment by mergenci** [comment]
@lsviben, the topic that crossplane-runtime being async unaware and async providers “lying” to it comes up frequently in SIG Upjet meetings and provider issues. If I understand correctly, @blakeromano is talking about the problem in general. I was determined to open a crossplane-runtime issue to track all such cases, but couldn't prioritize doing so 😒 I am sad with the fact we neglect Quadrant 2 activities in the [Eisenhower Matrix](https://en.wikipedia.org/wiki/Time_management#The_Eisenhower_Method).

**Comment by blakeromano** [comment]
I just want to be clear that due to this level of impact to managementPolicies for all async resources I still would emphasize I think we need a solution before we go GA with Management Policies.

**Comment by r-nasiri** [comment]
I ran into another issue with `external-name` annotation not being populated when `LateInitialize` managementPolicy is not set. Let's say you have an AWS security group that doesn't have `LateInitialize` management policy and then you want to reference it in a security group rule using `securityGroupIdSelector`. Since the extractor for SecurityGroup is set to external name, the resource will not be resolved as the value is empty and the security group rule resource stays in not Ready state forever.

**Comment by twobiers** [comment]
/fresh

Faced the same issue and it is breaking our assumptions about how we're writing compositions.

In our case we are creating Entra ID groups and allow modifications of the members in Entra. 
Therefore we're using an `initProvider` and remove the LateInitialize from management policies.

Now during cluster upgrades as part of the node draining, which shut down the provider, we ended up with multiple duplicates of groups and it required a lot of manual effort with updating the external-name, and so on.
What is even worse is that we now have to actively monitor groups as a crash of the provider might lead to the same issue again.

I would be very happy if we could find a solution or at least an intermediate measure for this issue.

**Comment by twobiers** [comment]
> Thanks for reporting [@blakeromano](https://github.com/blakeromano), managed to reproduce the issue.
> 
> Talked with [@ulucinar](https://github.com/ulucinar) [@mergenci](https://github.com/mergenci) about it and we found that the issue originates in [upjet](https://github.com/crossplane/upjet). Do to it being asynchronous, it handles updating the external name annotation on subsequent Observes after Create by forcing an update to the managed resource by setting the[ observation.ResourceLateInitialized to true](https://github.com/crossplane/upjet/blob/c606b4cbc0a7597fed7870cd941403a379ad8cf0/pkg/controller/external_tfpluginsdk.go#L557-L569). Which of course does not work with LateInitialize being disabled.
> 
> There is no other way to tell the crossplane-runtime reconciler to update the managed resource, so maybe we need a new way there that upjet could use. Or maybe there is a change possbile in upjet itself, TBD.

I've spend some time in understanding the Problem better and would like to extend on this for reference:
- The root cause of the behavior here is that upjet will not set the `crossplane.io/external-name` annotation after a successful creation when `LateInitialize` is removed from management policies 
  - This only affects non-deterministic external names as otherwise the external-name will be populated
- When an upjet provider creates a resource async, it will return immediately to the crossplane-runtime reconciler, making the update in a co-routine (https://github.com/crossplane/upjet/blob/0af42ca2591cf87341efcd9bec0812ab03e6bfa7/pkg/controller/external_async_tfpluginsdk.go#L139) 
- To propagate the state of the managed resource, upjet providers rely on the assumption that [`Observe()`](https://github.com/crossplane/upjet/blob/0af42ca2591cf87341efcd9bec0812ab03e6bfa7/pkg/controller/external_async_tfpluginsdk.go#L117) will be called eventually
  - `Observe()` will report the state back to the crossplane-runtime **AND** it also [updates the external name](https://github.com/crossplane/upjet/blob/0af42ca2591cf87341efcd9bec0812ab03e6bfa7/pkg/controller/external_tfpluginsdk.go#L570).
  - As the `external-name` effectively changes with every observation, it will report it has been late initialized (https://github.com/crossplane/upjet/blob/0af42ca2591cf87341efcd9bec0812ab03e6bfa7/pkg/controller/external_tfpluginsdk.go#L573)
  - The crossplane-runtime reconciler will only store the update if `LateInitialize` is part of the management policies (https://github.com/crossplane/crossplane-runtime/blob/0d81d3f7c2d872b656cd933e57601accfcd4cca5/pkg/reconciler/managed/reconciler.go#L1270-L1284)

While I agree that the best solution would be native support for async creations, I think this will be a long- to mid-term solution and I believe we can also come up with a short-term solution to that.
From my perspective crossplane should treat only changes to the `spec` as `LateInitialize` and updates to `metadata` should be stored anyway like updates to the `status`.
This would remidiate the issue here and is a reasonable enough behavior and is already the documented behavior:
> ResourceLateInitialized should be true if the managed resource's **spec was updated during its observation**. A Crossplane provider may update a managed resource's spec fields after it is created or updated, as long as the updates are limited to setting previously unset fields, and adding keys to maps.

https://github.com/crossplane/crossplane-runtime/blob/0d81d3f7c2d872b656cd933e57601accfcd4cca5/pkg/reconciler/managed/reconciler.go#L471-L472

**Possible Workaround with Composition Functions**
Set the `crossplane.io/external-name` annotation manually. For example using `function-go-templating`:
```yaml
apiVersion: groups.azuread.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    {{ setResourceNameAnnotation "test-group" }}
    {{- $existingId := (getComposedResource $ "test-group").status.atProvider.id }}
    {{- if $existingId }}
    crossplane.io/external-name: {{ $existingId }}
    {{- end }}
  name: "test-group"
spec:
  managementPolicies: ["Observe", "Create", "Update", "Delete"] 
  forProvider:
    displayName: "Test Group"
    description: "Test Group"
    securityEnabled: true
```
