### ISSUE TITLE
Support specifying package versions by digest

### ISSUE THREAD

**Issue by adamwg** [crossplane/crossplane#5920]
### What problem are you facing?

Crossplane packages are OCI images, which can be uniquely identified by a digest of their contents. While image tags are mutable (the manifest behind a particular tag can change), the digest is immutable since it is a hash of the contents of the image. Specifying an image by digest guarantees it won't change between pulls, and as such is often considered a security best practice.

Today, Crossplane only supports specifying package versions using semantic version constraints, relying on image tags in semantic version format. This is useful when the desired behavior is to get the latest version satisfied by the constraint, but prevents pinning a specific package version by digest.

### How could Crossplane help solve your problem?

Crossplane should support specifying a package version by digest. This change would need to be made in two places:

1. The `Provider`, `Configuration`, and `Function` package resources need to support a digest in `spec.package`:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-getting-started
spec:
  # Specify xpkg.upbound.io/upbound/configuration-getting-started:v0.3.0 by digest
  package: xpkg.upbound.io/upbound/configuration-getting-started@sha256:869bca254eb12f2d5d9681ac7186f13e67e2984e68f18e6195492d37e4fb42a2
```

2. The `Provider`, `Configuration`, and `Function` metadata types need to support digests in their `spec.dependsOn`:

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-getting-started
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-getting-started
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.15.2"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-nop
      version: "sha256:ecc25c121431dfc7058754427f97c034ecde26d4aafa0da16d258090e0443904"
    - function: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: "sha256:79a291ab951eb48f9324c6d15feb4a37a28e5cbb90268e23928e58c295a70a71"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: "sha256:ad9454a37aa78dcb13835ee60290f7bec1a25c2ba3514f3f03c6e17254733967"
```

Dependency resolution for packages specified by digest would work the same as when a package is specified by exact tag: if two packages specify dependencies on different digests, or one by digest and one by tag, the dependencies are unsatisfiable.
