### ISSUE TITLE
Endless provider revisions reconciliation when re-using DeploymentRuntimeConfig

### ISSUE THREAD

**Issue by Sijoma** [crossplane/crossplane#5961]
### What happened?

Reusing a DeplyomentRuntimeConfig between two providers causes endless reconciles of the provider revisions. The provider itself however works. 

We use the same config for the "Family-GCP & GCP KMS provider". This sets then securityContext, resources, affinity and tolerations equally.

The screenshot shows when I installed the second provider with the same runtime config. The reconciliations converge to 6 ops/s. Causing high CPU load of Crossplane. When I then modify the second provider to a unique runtimeConfig. The reconciliations go down. 
![image](https://github.com/user-attachments/assets/9f3b2005-0d94-4fd6-b027-87ccf53e2bac)

CPU graph:
![image](https://github.com/user-attachments/assets/8db311a7-71ff-413f-ada3-8f896fdda6c6)

### How can we reproduce it?

1. Create DeploymentRuntimeConfig:
```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-family
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: node-type
                        operator: In
                        values:
                          - critical-components
                  weight: 100
          tolerations:
            - effect: NoSchedule
              key: components.gke.io/gke-managed-components
              operator: Equal
              value: "true"
          containers:
            - name: package-runtime
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 500m
                  memory: 1Gi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 65532
                runAsNonRoot: true
                runAsUser: 65532
                seccompProfile:
                  type: RuntimeDefault
```
2. Create first provider (family gcp)
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-gcp
spec:
  package: upbound-provider-family-image
  runtimeConfigRef:
    name: provider-family-gcp
```
3. Create second provider
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: gcp-provider-kms
spec:
  skipDependencyResolution: true
  package: gcp-provider-kms-image
  runtimeConfigRef:
    name: provider-gcp-kms
```
### What environment did it happen in?
Crossplane version: v1.17.0 & v1.16.0

GKE Kubernetes Server Version: v1.30.3-gke.1969000
