### ISSUE TITLE
Usage relationship between two Composite resources gets stuck in deleting phase

### ISSUE THREAD

**Issue by ShamilMagamadov** [crossplane/crossplane#5962]
### What happened?
With Usages , I have defined a simple usage relationship between two Composite resources (the two composite resources are referenced in `By` and `Of`).
**Problem:** When deleting the Claim resource of the  `By`  Composite resource (MyCompositeA), the Claim and its referenced Composite (MyCompositeA) gets stuck in deleting status.
**Cause:** All the Managed Resources (MR) of the Composite resource gets deleted except for its Usage MR. The Usage resource says it is waiting for the Composite resource MyCompositeA to be deleted with the following warning:
```
  Normal  UsageConfigured      15m (x2 over 15m)  usage/usage.apiextensions.crossplane.io  Usage configured successfully.
  Normal  WaitingUsingDeleted  1s (x28 over 13m)  usage/usage.apiextensions.crossplane.io  Waiting for the using resource (which is a "MyCompositeA" named "my-composite-123") to be deleted.
```
**Manual Fix:** After deleting the Claim resource for MyCompositeA, i had to manually run the delete command (`kubectl delete MyCompositeA my-composite-123`) for the Composite resource so that its claim and the composite resources gets deleted as expected.
**Expected Behaviour:** When deleting the Claim resource, the Composite has the status Deleting. I expect the delete command for the Composite to have then been run by it self, and all its Managed Resources including the Usage resourse should be deleted. All the managed resources of the Composite gets deleted as expected but NOT the Usage resource. 

### How can we reproduce it?
Create two seperate Compositions (Composition A and Composition B) with their own CompositeResourceDefinitions (Claims) where Composition A has Foreground deletion policy and Composition B has Background.
Then in the resources for the Composition A, create a Usage managed resource where it is defined as follows:

```yaml
    - name: MyCompositeA-uses-CompositeB
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          replayDeletion: true
          of:
            apiVersion: someVersion/v1alpha1
            kind: CompositeB
            resourceSelector:
              matchLabels:
                crossplane.io/claim-namespace: patched
          by:
            apiVersion: someVersion/v1alpha1
            kind: MyCompositeA
            resourceSelector:
              matchLabels:
                crossplane.io/claim-namespace: patched
      patches:
        - fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: spec.of.resourceSelector.matchLabels['crossplane.io/claim-namespace']
        - fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: spec.by.resourceSelector.matchLabels['crossplane.io/claim-namespace'] 
```

### What environment did it happen in?
Crossplane version: v1.16.0

* Kubernetes version:
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7-eks-2f46c53
* OS: Linux Redshift
* Kernel: Linux x86_64 GNU/Linux
-->

**Suggestion for extra task:** It would be nice to update docs for usage relationship between Composite resources as it is lacking compared to usage relationship between managed resources.
