### ISSUE TITLE
Standardize Input APIs and metadata.annotations, meta APIs across crossplane functions for consistency

### ISSUE THREAD

**Issue by haarchri** [crossplane/crossplane#5966]
### What problem are you facing?

As the Crossplane ecosystem continues to grow with more and more functions, I wonder if the Crossplane project could establish a more consistent input API for all our functions. Currently, we have functions that support inline code, filesystem, or OCI, but the input APIs for these functions vary greatly. Here are a few examples:

`spec.source`
`source: Inline` in combination with `inline.template`
`resources[]`

#### inline 

```
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-kcl
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: KCLInput
      spec:
        source: |
            bucket = {
            apiVersion = "s3.aws.upbound.io/v1beta1"
            kind = "Bucket"
            metadata.annotations = {
                "krm.kcl.dev/composition-resource-name" = "bucket"
            }

            items = [
              bucket
            ]
    step: crossplane-contrib-function-kcl
```

```
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: bucket
    step: crossplane-contrib-function-go-templating
```

```
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: bucket
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
    step: crossplane-contrib-function-patch-and-transform
```

#### filesystem, one file, multiple files, OCI

```
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: FileSystem
      fileSystem:
        dirPath: /templates
    step: crossplane-contrib-function-go-templating
```

```
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-kcl
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: KCLInput
      spec:
        source: ./main.kcl
    step: crossplane-contrib-function-kcl 
```

#### resource-name annotation 
Another thing I've noticed is the variation in resource name annotations. For example:

```
resources[i].name
gotemplating.fn.crossplane.io/composition-resource-name
krm.kcl.dev/composition-resource-name
```
All of these lead to `crossplane.io/composition-resource-name`. So, why aren't we using `crossplane.io/composition-resource-name` directly?

#### meta apis 
The other observation is around the "meta APIs" used within the functions, like `ExtraResources` and `CompositeConnectionDetails`. Here, we also see a lot of differences in how these are implemented.

```
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
```

```
              apiVersion: meta.krm.kcl.dev/v1alpha1
              kind: CompositeConnectionDetails
```

### How could Crossplane help solve your problem?

To create a more consistent and unified input API for Crossplane functions, we can define a standardized API structure that accommodates various use cases (inline code, filesystem, OCI, etc.) while maintaining flexibility. Here’s a possible approach:

```
pipeline:
  - functionRef:
      name: crossplane-function
    input:
      apiVersion: xyz.crossplane.io/v1beta1
      kind: FunctionInput
      source:
        type: Inline
        inlineTemplate: |
          ---
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
          metadata:
            annotations:
              crossplane.io/composition-resource-name: bucket
    step: crossplane-function
```

```
pipeline:
  - functionRef:
      name: crossplane-function
    input:
      apiVersion: zgf.crossplane.io/v1beta1
      kind: FunctionInput
      source:
        type: Inline
        inlineTemplate: |
            bucket = {
            apiVersion = "s3.aws.upbound.io/v1beta1"
            kind = "Bucket"
            metadata.annotations = {
                "crossplane.io/composition-resource-name" = "bucket"
            }
            items = [
              bucket
            ]
    step: crossplane-function
```

```
pipeline:
  - functionRef:
      name: crossplane-function
    input:
      apiVersion: ert.crossplane.io/v1beta1
      kind: FunctionInput
      source:
        type: Inline
        resources: 
            - base:
                apiVersion: s3.aws.upbound.io/v1beta1
                kind: Bucket
                metadata:
                  annotations:
                    crossplane.io/composition-resource-name: bucket
    step: crossplane-function
```

```
pipeline:
  - functionRef:
      name: crossplane-function
    input:
      apiVersion: xyz.crossplane.io/v1alpha1
      kind: FunctionInput
      source:
        type: FileSystem
        fileSystem:
          dirPath: /templates
          filePath: main.kcl
    step: crossplane-function
```

```
pipeline:
  - functionRef:
      name: crossplane-function
    input:
      apiVersion: xyz.crossplane.io/v1alpha1
      kind: FunctionInput
      source:
        type: OCI
        oci:
          image: oci://example.com/repo/image:tag
    step: crossplane-function
```

**Consistency**: All functions follow a similar structure, making them easier to understand and use.
**Standardization**: Uses standardized metadata annotations like crossplane.io/composition-resource-name to reduce ambiguity.

We can still include additional fields for different inputs, but I wonder if we could enforce a more consistent input API for common field inputs, along with standardized annotations and metadata. This would make it much easier for newcomers to understand and adopt Crossplane, especially when working with various examples.
