### ISSUE TITLE
Can't install `Function` with `meta.pkg.crossplane.io/v1` package metadata

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5971]
### What happened?

If you write a function that uses the `meta.pkg.crossplane.io/v1` API version for its package metadata, you can't install it on Crossplane v1.17.x. You'll get the following error:

```
linting package contents failed: package meta type is not Function
```

You also can't use `crossplane xpkg build` to build the function, because it uses the same linting logic:

```
crossplane: error: failed to build package: failed to lint package: package meta type is not Function
```

Thanks @adamwg for reporting this.

### How can we reproduce it?

Try install the following function on Crossplane v1.17.1:

```yaml
---
apiVersion: meta.pkg.crossplane.io/v1
kind: Function
metadata:
  annotations:
    meta.crossplane.io/description: Function boop
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/function-boop
  name: function-boop
spec: {}
```

### What environment did it happen in?
Crossplane version: v1.17.1
