### ISSUE TITLE
Terraform provider fails

### ISSUE THREAD

**Issue by agardnerIT** [crossplane/crossplane#5978]
I create a new kind cluster, install Crossplane + the Terraform provider. I also configure the sync to `1m` for testing purposes.

I apply a remote configuration (which looks at a public GitHub repo). The initial resource creation works.

Then in the backend I delete the resource and I'm expecting Crossplane to recreate the resource after `~1m` but I see:

```
Error: Settings objectId 'vu9U3hXa3q0AAAABABlidWlsdGluOnRhZ3MuYXV0by10YWdnaW5nAAZ0ZW5hbnQABnRlbmFudAAkZTVjYzg1ZjEtODAxZC0zZDJhLWEzYjgtMGEwMWE5NDU3MzMzvu9U3hXa3q0' not found

  with dynatrace_autotag_rules.sampleagremote,
  on main.tf line 12, in resource "dynatrace_autotag_rules" "sampleagremote":
  12: resource "dynatrace_autotag_rules" "sampleagremote" {
```

# Installation
```
kind create cluster
helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update
helm install crossplane \
--namespace crossplane-system \
--create-namespace crossplane-stable/crossplane 

# Create terraform.yaml
# https://marketplace.upbound.io/providers/upbound/provider-terraform/v0.17.0
# Install terraform provider
kubectl apply -f terraform.yaml

kubectl -n crossplane-system create secret generic dt-details \
  --from-literal=DYNATRACE_ENV_URL=https://abc12345.live.dynatrace.com \
  --from-literal=DYNATRACE_API_TOKEN=dt0c01.sample.secret

kubectl apply -f provider_conf.yaml

kubectl apply -f workspace-remote.yaml
```

## provider_conf.yaml
```
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  configuration: |
    terraform {
        required_providers {
            dynatrace = {
                version = "~> 1.0"
                source = "dynatrace-oss/dynatrace"
            }
        }
    }

    provider "dynatrace" {
      dt_env_url   = "https://abc12345.live.dynatrace.com/"
      dt_api_token = "dt0c01.secret.sample"
    }

    // Modules _must_ use remote state. The provider does not persist state.
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-default"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }
```

## workspace-remote.yaml
```
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: example-remote
  annotations:
    # The terraform workspace will be named 'coolbucket'. If you omit this
    # annotation it would be derived from metadata.name - e.g. 'example-inline'.
    #crossplane.io/external-name: agardnerit/tf
spec:
  forProvider:
    # Use any module source supported by terraform init -from-module.
    source: Remote
    module: git::https://github.com/agardnerit/tf?ref=main
    # Environment variables can be passed through
    env:
      - name: DYNATRACE_ENV_URL
        secretKeyRef:
          namespace: crossplane-system
          name: dt-details
          key: DYNATRACE_ENV_URL
      - name: DYNATRACE_API_TOKEN
        secretKeyRef:
          namespace: crossplane-system
          name: dt-details
          key: DYNATRACE_API_TOKEN
  # All Terraform outputs are written to the connection secret.
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-example-remote
```

Reads this remote: `https://github.com/agardnerIT/tf`
