### ISSUE TITLE
feat: modify default printer columns

### ISSUE THREAD

**Issue by jan-mrm** [crossplane/crossplane#5984]
### What problem are you facing?

I'm using CompositeResourceDefinitions (XRDs) to create composite resources. The CRDs created from the XRDs always contain a default set of additional printer columns:

```yaml
      additionalPrinterColumns:
        - name: SYNCED
          type: string
          jsonPath: .status.conditions[?(@.type=='Synced')].status
        - name: READY
          type: string
          jsonPath: .status.conditions[?(@.type=='Ready')].status
        - name: CONNECTION-SECRET
          type: string
          jsonPath: .spec.writeConnectionSecretToRef.name
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
```

Since my compositions rarely have a connection-secret I'd like to remove it from the additionalPrinterColumns.
But as far as I found, those additionalPrinterColumns originate here https://github.com/crossplane/crossplane/blob/fa5f5850ef4ebe763def3c7a350a841a3d65b880/internal/xcrd/schemas.go#L400
and are just appended here https://github.com/crossplane/crossplane/blob/fa5f5850ef4ebe763def3c7a350a841a3d65b880/internal/xcrd/crd.go#L84
I do not see anyway to enable, disable or modify / overwrite the default yet.

### How could Crossplane help solve your problem?

By adding any way to configure the default printer columns.

**Comment by guillaumebernard84** [comment]
Hello, I have the same need, I'd like to add a few additionalPrinterColumns to the `kubectl get` output for my composite ressource

**Comment by jan-mrm** [comment]
> Hello, I have the same need, I'd like to add a few additionalPrinterColumns to the `kubectl get` output for my composite ressource

Hey @guillaumebernard84 adding of `additionalPrinterColumns` should just work by defining some in the definition of the `CompositeResourceDefinition`.
This issue is more about changing the set of default printer columns, mainly the `CONNECTION-SECRET` one.

**Comment by jan-mrm** [comment]
Hi @jbw976, since I just saw you updating this issue / feature request especially with 'good first issue': do you have a suggestion on how to implement this? Especially with being backwards compatible. So not changing the current default which everyone used but to be able to opt-in to overwriting it maybe? In general I'd be interested in implementing it if I can - I can give it a try.
But I'd need to know if this is something that is wanted to be implemented / okay to implement and an idea of the best way on how to implement it. Any feedback is appreciated. 🙂

**Comment by guillaumebernard84** [comment]
Hello @jan-mrm, you are right, I tried it and it didn't work, but looking at the code it should work. I must have missed something!

**Comment by jan-mrm** [comment]
> Hello [@jan-mrm](https://github.com/jan-mrm), you are right, I tried it and it didn't work, but looking at the code it should work. I must have missed something!

it should be pretty much just this, did you try something different?

<details>
<summary>manifest for additionalPrinterColumns</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsomeresources.exmaple.com
spec:
  group: exmaple.com
  names:
    kind: XSomeResource
    plural: xsomeresources
  claimNames:
    kind: SomeResource
    plural: someresources
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      additionalPrinterColumns:
        - jsonPath: .status.some.field
          name: someFieldName
          type: string
```
</details>
