### ISSUE TITLE
Implement anyOf in the XRD. 

### ISSUE THREAD

**Issue by peterbosalliandercom** [crossplane/crossplane#5992]
According to the kubernetes crd documentation it should be possible to use the anyOf in the structural schema of custom resource definitions. See here: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

I have tested it with oneOf and that works. 
```
openAPIV3Schema:
  type: object
  properties:
    x:
      type: boolean  # Assuming 'x' is a boolean
    y:
      type: boolean  # Assuming 'y' is a boolean
    z:
      type: string
  required:
    - z  # Assuming 'z' is always required
  oneOf:
    - required: ["x"]
    - required: ["y"]
```

I have tested it with anyOf and that does not seem to work, i have not found any code on the anyOf
```
openAPIV3Schema:
  type: object
  properties:
    x:
      type: boolean  # Assuming 'x' is a boolean
    y:
      type: boolean  # Assuming 'y' is a boolean
    z:
      type: string
  required:
    - z  # Assuming 'z' is always required
  anyOf:
    - required: ["x"]
    - required: ["y"]
```
    

Also it doent appear to be there in the actual crossplane code or am i missing something?

https://github.com/crossplane/crossplane/blob/ed4e659c5c217fb69958eeb75ce8daa65b63823c/internal/xcrd/crd.go#L193

It would be great if this would work.
