### ISSUE TITLE
CosmosDB Account access to use Azure portal for data exploring

### ISSUE THREAD

**Issue by malnor** [crossplane/crossplane#6011]
### What problem are you facing?
I want to be able to use my Crossplan composition to create a cosmosdb where the account can setup that azure portal is allowed to use the data explorer. This option isn't possible to setup today.

### How could Crossplane help solve your problem?
Implemenent away to do this. For example 
 ```yaml
publicNetworkAccessEnabled: false
  isVirtualNetworkFilterEnabled: true
  networkAclBypassForAzureServices: true <----- either this allows the azure portal to use the data explorer
  networkAcl:
    bypasses:
      - AzureServices <------- or the azure portal is specified in this 
```
