### ISSUE TITLE
compositionRevisionSelector not updating compositionRevisionRef

### ISSUE THREAD

**Issue by jtucci** [crossplane/crossplane#6030]
### What happened?
When updating a Composition with new logic and updated labels, the associated Composite Resource (XR) does not receive the intended updates. The compositionRevisionSelector on the XR reflects the new selector labels, but the compositionRevisionRef does not point to the latest CompositionRevision, causing the XR to miss the changes.

### How can we reproduce it?
1. Create a composition (in this case it will have a bug in it with the $id param)
```
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: github-repo
  labels:
    version: v0.1.0
    channel: dev
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: ops.example.org/v1alpha1
    kind: XGitHubRepo
  pipeline:
    - step: compose-resources
      functionRef:
        name: go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $xr := getCompositeResource . }}
            {{ $claimNamespace := get $xr.metadata.labels "crossplane.io/claim-namespace" }}

            {{ $params := get $xr.spec "parameters" | default dict }}
            {{ $ id := get $params "id" }}

            ---
            {{ $providerConfigShootKubernetesResourceName := "providerConfigKubernetes" }}

            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: ProviderConfig
            metadata:
              annotations:
                {{ setResourceNameAnnotation $providerConfigShootKubernetesResourceName }}
                gotemplating.fn.crossplane.io/ready: "True"
              name: {{ printf "%s-%s" $claimNamespace $id | toYaml }}
              labels:
                ops.example.org/resource-name: {{ $providerConfigShootKubernetesResourceName | toYaml }}
                ops.example.org/managed: "true"
            spec:
              credentials:
                secretRef:
                  key: kubeconfig
                  name: "super-secret"
                  namespace: {{ $claimNamespace | toYaml }}
                source: Secret
            ---

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: auto-ready
```
2.) Deploy composition + associated XRD, take note of the revision created 
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositionRevision
metadata:
  creationTimestamp: '2024-10-25T21:10:26Z'
  generation: 1
  labels:
    channel: dev
    crossplane.io/composition-hash: db3672f5a0cde2eae80f3c14c2120ebbec6ecc22934d86c7f36fdc4c95ce6a1
    crossplane.io/composition-name: github-repo
    version: v0.1.0
  name: github-repo-db3672f
```
3.) Deploy Claim 
```
apiVersion: ops.example.org/v1alpha1
kind: GitHubRepo
metadata:
  name: jmt-dev-us-infra-repo
  namespace: jmt-dev-us
spec:
  parameters:
    id: "account-1"
  compositionUpdatePolicy: "Manual"
  compositionRevisionSelector:
    matchLabels:
      version: "v0.1.0"
      channel: "dev"
```

View the currently selected revision in the newly created XR
```
...
  compositionRef:
    name: github-repo
  compositionRevisionRef:
    name: github-repo-db3672f
  compositionRevisionSelector:
    matchLabels:
      channel: dev
      version: v0.1.0
```
4. Modify composition / Fix the bug with the id variable, bump the version label, and redeploy. This will create a new composition revision. 
```
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: github-repo
  labels:
    version: v0.1.1
    channel: dev
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: ops.example.org/v1alpha1
    kind: XGitHubRepo
  pipeline:
    - step: compose-resources
      functionRef:
        name: go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $xr := getCompositeResource . }}
            {{ $claimNamespace := get $xr.metadata.labels "crossplane.io/claim-namespace" }}

            {{ $params := get $xr.spec "parameters" | default dict }}
            {{ $id := get $params "id" }}

            ---
            {{ $providerConfigShootKubernetesResourceName := "providerConfigKubernetes" }}

            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: ProviderConfig
            metadata:
              annotations:
                {{ setResourceNameAnnotation $providerConfigShootKubernetesResourceName }}
                gotemplating.fn.crossplane.io/ready: "True"
              name: {{ printf "%s-%s" $claimNamespace $id | toYaml }}
              labels:
                ops.example.org/resource-name: {{ $providerConfigShootKubernetesResourceName | toYaml }}
                ops.example.org/managed: "true"
            spec:
              credentials:
                secretRef:
                  key: kubeconfig
                  name: "super-secret"
                  namespace: {{ $claimNamespace | toYaml }}
                source: Secret
            ---

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: auto-ready
```
Observe the new revision 
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositionRevision
metadata:
  creationTimestamp: '2024-10-25T21:21:06Z'
  generation: 1
  labels:
    channel: dev
    crossplane.io/composition-hash: cd5fa25c479309f6119e9d0c4096bb3f51e40ab71c3e4fb070d3127a0abd494
    crossplane.io/composition-name: github-repo
    version: v0.1.1
  name: github-repo-cd5fa25
```
5. Re Deploy Claim to select for the new revision 
```
apiVersion: ops.example.org/v1alpha1
kind: GitHubRepo
metadata:
  name: jmt-dev-us-infra-repo
  namespace: jmt-dev-us
spec:
  parameters:
    id: "account-1"
  compositionUpdatePolicy: "Manual"
  compositionRevisionSelector:
    matchLabels:
      version: "v0.1.1"
      channel: "dev"
```
6. Observe that the XR is not updating the revision ref
```
...
  compositionRef:
    name: github-repo
  compositionRevisionRef:
    name: github-repo-db3672f
  compositionRevisionSelector:
    matchLabels:
      channel: dev
      version: v0.1.1
```
### What environment did it happen in?
Crossplane version: 
1.16.0
