### ISSUE TITLE
High memory usage while verifying attestations

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#6077]
### What happened?

Crossplane uses a large amount of memory (and OOMKilled with default values) if multiple attestation verifications are conducted simultaneously. This may also be related to the size of the attestations attached to the packages; Crossplane memory usage goes up significantly during attestation verification.

### How can we reproduce it?

1. Install Crossplane v1.18.0 with `--enable-signature-verification`.
2. Create an image config verifying attestations, e.g. 

```
...
  verification:
    provider: Cosign
    cosign:
      authorities:
        - name: verify keyless signing
          keyless:
          ...
          attestations:
            - name: verify attestations
              predicateType: spdxjson
```

3. Create multiple matching providers.

In my experiments, when I try with 11 providers with SBOMs around size of 50Mb, Crossplane used up to 4.5 Gb of memory.

### What environment did it happen in?
Crossplane version: v1.18.0
