### ISSUE TITLE
Cannot change field of a composite that has a claim

### ISSUE THREAD

**Issue by Mikel-Landa** [crossplane/crossplane#6095]
### What happened?

When I try to remove a field from the composite or claim, it gets added immediately back. Remove any tag and kubectl apply. The first time it detects changes but the tags remain the same. When I try to apply again, it doesn't even detect changes. Seem like #3421 again.

### How can we reproduce it?

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtests.prism.pepper-advantage.com
spec:
  group: prism.pepper-advantage.com
  names:
    kind: XTest
    plural: xtests
  claimNames:
    kind: Test
    plural: tests
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: The OpenAPIV3Schema of this Composite Resource Definition.
              properties:
                env:
                  x-kubernetes-preserve-unknown-fields: true
                parameters:
                  x-kubernetes-preserve-unknown-fields: true

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xtest.azure.prism.pepper-advantage.com
  labels:
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: prism.pepper-advantage.com/v1alpha1
    kind: XTest
  mode: Pipeline
  pipeline:
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
---
apiVersion: prism.pepper-advantage.com/v1alpha1
kind: Test
metadata:
  name: test
  namespace: test
spec:
  parameters:
    tags:
      client: test
      managed: 'true'
      operator: crossplane
```
### What environment did it happen in?
Crossplane version: 
1.18.0
