### ISSUE TITLE
`validate` does not download all missing schemas anymore

### ISSUE THREAD

**Issue by samuelstadler** [crossplane/crossplane#6096]
### What happened?
Running `crossplane beta validate schema render-output.yaml` should download all missing schemas. Since [this change](https://github.com/crossplane/crossplane/blob/e98f4f3cb7bd7731c5be484a5a8fb1afcf213ac8/cmd/crank/beta/validate/manager.go#L307) that is not the case anymore and only the first missing schema is downloaded and then it continues with validating. The validation then "fails" because of missing schemas.

### How can we reproduce it?

Run `crossplane beta validate schema render-output.yaml` with the latest version of crossplane (1.18.0) and multiple schemas in the `schema` folder like:
```
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-eks
spec:
  crossplane:
    version: ">=v1.16.0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.15.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.19.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: ">=v1.15.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      version: ">=v1.15.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: ">=v1.15.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-kms
      version: ">=v1.15.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-autoscaling
      version: ">=v1.15.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-dlm
      version: ">=v1.15.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.7.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: ">=v0.7.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.3.0"
```

### What environment did it happen in?
Crossplane version: 1.18.0
