### ISSUE TITLE
Merging two maps getting overwritten. Disparency between documentation and API Reference

### ISSUE THREAD

**Issue by glaberge** [crossplane/crossplane#6124]
### What happened?
Might be related to #3993 but I'm unsure.

I'm trying to merge tags maps from an `environmentConfig` with a field path

```
            - type: FromCompositeFieldPath
              fromFieldPath: spec.tags
              toFieldPath: spec.forProvider.tags
            - type: FromEnvironmentFieldPath
              fromFieldPath: defaultTags
              toFieldPath: spec.forProvider.tags
              policy:
                mergeOptions:
                  appendSlice: true
                  keepMapValues: true
```

`environmentConfig`

```
data:
  defaultTags:
    Automation: "Crossplane"
    Owner: "Me"
```

`xrd`
```
spec:
  tags:
    Domain: "Infra"
```

The managed resource ends up having only the `defaultTags` fields. Removing the `FromEnvironmentFieldPath` patch applies only the xrd tags.

Also, the documentation mentions to use `policy.toFieldPath` as mentioned [here](https://docs.crossplane.io/latest/guides/function-patch-and-transform/#tofieldpath-policy) but the API reference shows not such field and only [mergeOptions](https://docs.crossplane.io/v1.18/api/#Composition-spec-resources-patches-policy-mergeOptions)

### How can we reproduce it?
Define EnvironmentConfig
```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: environment-config
data:
  defaultTags:
    Automation: "Crossplane"
    Owner: "Me"
    Environment: "dev"
```
Define a Composition
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ecr
spec:
  mode: Pipeline
  pipeline:
  - step: environmentConfigs
    functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - type: Reference
          ref:
            name: environment-config
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: repository
          base:
            apiVersion: ecr.aws.upbound.io/v1beta1
            kind: Repository
            metadata:
              name: default
            spec:
              forProvider:
                region: "ca-central-1"
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: spec.tags
              toFieldPath: spec.forProvider.tags
            - type: FromEnvironmentFieldPath
              fromFieldPath: defaultTags
              toFieldPath: spec.forProvider.tags
              policy:
                mergeOptions:
                  appendSlice: true
                  keepMapValues: true
```
Define xrd
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: ecrs.infra.domain.com
spec:
  group: infra.domain.com
  names:
    kind: Ecr
    plural: ecrs
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
              tags:
                type: object
                additionalProperties:
                  type: string
                  properties:
                    Domain:
                      type: string
                required:
                  - Domain
            required:
              - tags
    served: true
    referenceable: true
  claimNames:
    kind: EcrClaim
    plural: ecrsclaim
```
Create resource
```
apiVersion: infra.domain.com/v1alpha1
kind: Ecr
metadata:
  name: my-demo
spec:
  tags:
    Domain: "Infra"
```

Created ECR (tested with s3 as well) only has tags from environment config

### What environment did it happen in?
Crossplane version: 1.18.0
Kubernetes: 1.30
AWS EKS

**Comment by phisco** [comment]
Merge options were changed in function-patch-and-transform, you have to set it as:
```
...
              policy:
                toFieldPath: ForceMergeObjectsAppendArrays
...
```

**Comment by glaberge** [comment]
Hi @phisco 
Tried the following with the same result (only env config tags are applied)
```
            - type: FromEnvironmentFieldPath
              fromFieldPath: defaultTags
              toFieldPath: spec.forProvider.tags
              policy:
                toFieldPath: ForceMergeObjectsAppendArrays
```

**Comment by glaberge** [comment]
Any news on this? Or maybe any possible workaround?

**Comment by glaberge** [comment]
Was able to get a workaround using go templates and the status field

Added this to the `Composite`
```
  - step: go-template-merge-tags
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          apiVersion: infra.mydomain.com/v1alpha1
          kind: Ecr
          status:
            mergedTags: {{ toYaml (merge .observed.composite.resource.spec.tags (index .context "apiextensions.crossplane.io/environment" "defaultTags")) | nindent 6 }}
```

Xrd
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: ecrs.infra.mydomain.com
spec:
  group: infra.mydomain.com
  names:
    kind: Ecr
    plural: ecrs
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tags:
                type: object
                additionalProperties:
                  type: string
                  properties:
                    Domain:
                      type: string
                required:
                  - Domain
            required:
              - tags
          status:
            description: Defines the observed state of repository
            properties:
              repoId:
                type: string
              mergedTags:
                type: object
                additionalProperties:
                  type: string
```
