### ISSUE TITLE
Passing values as object in a Claim would fail if in XRD the value is defined as Free form

### ISSUE THREAD

**Issue by spastorclovr** [crossplane/crossplane#6127]
### What happened?

I am trying to create an XRD which should allow any values for the field `values`

I tried :point_down: 
```
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
               values:
                    type: object
                    additionalProperties: true
                    maxProperties: 1000
```

but when trying to use a claim with 

```
    values:
      replica:
        replicaCount: 20
```

I receive : 
```
The request is invalid: patch: Invalid value: 
strict decoding error: unknown field "spec.image.values.replica.replicaCount"
```

Is there a specific way to specify that we do not expect any values for one of the field when this one is of type `object`
According to [swagger
](https://swagger.io/docs/specification/v3_0/data-models/data-types/) we should be able to specify  the object like so 
`type: object` to declare it as a `free form` but this does not work neither.

### What environment did it happen in?
Crossplane version: 

crossplane-1.18.0

**Comment by bobh66** [comment]
Use `x-kubernetes-preserve-unknown-fields: true` in your object definition:

```
 - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
               values:
                 type: object
                 x-kubernetes-preserve-unknown-fields: true
```
