### ISSUE TITLE
Usage API: consider setting `replayDeletion` default to true

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#6140]
#5394 introduced the ability to replay a previously blocked deletion attempt by explicitly setting `spec.replayDeletion: true`. See the documentation for more details: https://docs.crossplane.io/v1.18/concepts/usages/#replay-blocked-deletion-attempt

While promoting the API to beta, we should consider making this the default behavior, which could mean renaming the field `spec.skipReplayDeletion: false` and dropping the old `spec.replayDeletion`.  

Related discussion: https://github.com/crossplane/crossplane/pull/5394#discussion_r1518582368

**Comment by turkenh** [comment]
I was testing #6175 which makes replay deletion the default behavior, but, I am not happy with the following situation:

Using the manifests at `test/e2e/manifests/apiextensions/usage/standalone/with-reason/`, I created a protected resource and a usage with a reason.

```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Usage
metadata:
  name: protect-a-resource
spec:
  of:
    apiVersion: nop.crossplane.io/v1alpha1
    kind: NopResource
    resourceSelector:
        matchLabels:
          tier: critical
  reason: "This resource is protected!"
```

Note, we don't have `spec.doNotReplayDeletion` is set, so, we will replay deletion.

I attempted deleting the used resource and it is rejected as expected. Then I deleted the Usage and it resulted deletion of the used resource. Think about a real world scenario where somebody creates a database MR and then defines a usage protecting it with a reason like "this is prod database". During its lifecycle, let's assume it rejected a couple of deletion attempts. For some reason, the admins decided to delete that Usage resource; they will notice their database resource is being deleted because of deletion replay 😱

The situation is not much different if a `spec.by` was defined, and even more confusing since deleting the using resource causes deletion of the usage (since it owns usage) and eventually the used resource.
