### ISSUE TITLE
Import SQS

### ISSUE THREAD

**Issue by diegoavitorino** [crossplane/crossplane#6146]
### What problem are you facing?
 By trying import sqs queue I'm facing the error:
```
Warning  CannotObserveExternalResource  4s (x8 over 66s)  managed/sqs.aws.upbound.io/v1beta1, kind=queue  
failed to observe the resource: [{0 SQS Queue URL (mysqs-etc-test) is in the incorrect format  []}]
```

### How could Crossplane help solve your problem?
Follow my yaml

```
apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  annotations:
    crossplane.io/external-name: mysqs-etc-test
  labels:
    app: mysqs-etc-test
  name: mysqs-etc-test
spec:
  forProvider:
    region: us-east-1
```

**Comment by bobh66** [comment]
This is a provider issue and so should be raised in the https://github.com/crossplane-contrib/provider-upjet-aws repo

**Comment by diegoavitorino** [comment]
I didn't find a way to import the existing sqs queue, just to create a new one

**Comment by jbw976** [comment]
Are you following the steps outlined in https://docs.crossplane.io/latest/guides/import-existing-resources/#import-resources-automatically? if you start with `managementPolicies: ["Observe"]`, it may be easier for the provider to observe/read all the data, then more easily import all the correct settings fully.

i suspect without that, there are some required fields that aren't getting set and that's causing it to have problems 🤔

**Comment by jbw976** [comment]
I think the error message `SQS Queue URL (queue-example-sqs) is in the incorrect format` is hinting to you that the provided `external-name` is incorrect. This [AWS docs page](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-queue-message-identifiers.html) is relevant.

I was able to successfully import an existing SQS queue right now using a manifest like the following:
```
apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  annotations:
    crossplane.io/external-name: https://sqs.us-east-1.amazonaws.com/609897127049/jaredexamplequeue
  name: jared-example
spec:
  managementPolicies: ["Observe"]
  forProvider:
    name: jaredexamplequeue
    region: us-east-1
```


Note my `external-name` is using the queue URL format:
```
crossplane.io/external-name: https://sqs.us-east-1.amazonaws.com/609897127049/jaredexamplequeue
```
Try the same thing using the queue URL that's shown in your AWS console 🙏
