### ISSUE TITLE
crossplane manager cannot unpack xpkg from an insecure registry and there is no option to allow it

### ISSUE THREAD

**Issue by dionysius** [crossplane/crossplane#6159]
### What problem are you facing?
For development purposes I want to install a xpkg into my crossplane development k8s from a local container registry with self-signed certificate - as [offline installation](https://docs.crossplane.io/latest/concepts/packages/#install-offline) is supported but requires a container registry.

Since the crossplane manager wants to download the image itself it connects to the registry directly.

### How could Crossplane help solve your problem?
While it supports being passed docker pull secrets via the ProviderSpec it's missing an option to define allowed insecure registries similiar to what docker offers: https://distribution.github.io/distribution/about/insecure/.

Since the `package` "url" itself is part of the [PackageSpec](https://github.com/crossplane/crossplane/blob/main/apis/pkg/v1/package_types.go#L26) i propose to allow there the insecure flag to be set, which then is consumed and [used by the manager's Revision method].(https://github.com/crossplane/crossplane/blob/main/internal/controller/pkg/manager/reconciler.go#L347)

### Additional info

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-xyz
spec:
  package: docker-registry-xp.lxd/provider-xyz:v0.0.0-1.gad31f9f
```
```yaml
status:
  conditions:
  - lastTransitionTime: "2024-12-04T21:04:17Z"
    message: 'cannot unpack package: failed to fetch package digest from remote: failed
      to fetch package descriptor with a GET request after a previous HEAD request
      failure: Get "https://docker-registry-xp.lxd/v2/": tls: failed to verify certificate:
      x509: certificate signed by unknown authority: Get "https://docker-registry-xp.lxd/v2/":
      tls: failed to verify certificate: x509: certificate signed by unknown authority'
    reason: UnpackingPackage
    status: "False"
    type: Installed
```

The image in question can be perfectly pulled (and in theory run, but no entrypoint) by the hosts docker daemon after the appropriate [insecure registries have been configured](https://distribution.github.io/distribution/about/insecure/).
```
root@k3s-xp:~# docker run --rm --name test docker-registry-xp.lxd/provider-xyz:v0.0.0-1.gad31f9f foo
Unable to find image 'docker-registry-xp.lxd/provider-xyz:v0.0.0-1.gad31f9f' locally
v0.0.0-1.gad31f9f: Pulling from provider-xyz
83f4e511f011: Pull complete 
Digest: sha256:d0d145eb9a28a93303222df50fefcd44f5fcb49f9c15732c570f29bea35a0915
Status: Downloaded newer image for docker-registry-xp.lxd/provider-xyz:v0.0.0-1.gad31f9f
docker: Error response from daemon [... error not relevant to this issue]
```

The setup of the registry is described in this issue: https://github.com/crossplane/crossplane/issues/6156

_Additionally (separate issue but hinting it here fits) the other features like mirroring support similiar to the docker deamon config should also be considered. One should be able to mirror xpkg.upbound.io and possibly other marketplaces and use that mirror to drive it's crossplane system for various reasons._

**Comment by charlestjackson** [comment]
I'm also running into this issue. In my case, I have a cert with a newer CA that's not automatically trusted by most systems and I have to manually add it. I've done that for my kubernetes node, which I've confirmed is correct by both curling and pulling the image from the node. However, installing the crossplane provider fails with a similar error to above.

**Comment by dionysius** [comment]
I lately stumbled upon a [standard/format(?)](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md) about those registry settings. Maybe it makes sense to honor that and allow a the pod to be configured accordingly (e.g. by an attached configmap or whatever).

**Comment by TehilaTheStudent** [comment]
i mounted a cert into crossplane pod, and successfully pulled a package from self signed local registry

my values.yaml:
```
extraVolumeMountsCrossplane:
  - name: custom-certs
    mountPath: /etc/ssl/certs/cert.pem
    subPath: cert.pem
extraVolumesCrossplane:
  - name: custom-certs
    configMap:
      name: custom-certs-cm
```
