### ISSUE TITLE
The update of existing Azure AD app doesn't work

### ISSUE THREAD

**Issue by eriksML** [crossplane/crossplane#6190]
Hi crossplane team,

we need to update the existing azure AD application by adding redirect uris for SSO configuration.
However looks it's not working with the azuread provider the version 1.6.0.
Here is my manifest which I'm trying to apply 

```
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Application
metadata:
  name: my-app-test
  annotations:
    crossplane.io/external-name: "/applications/00000000-0000-0000-0000-000000000000"
spec:
  managementPolicies: ["Observe"]
  forProvider:
    displayName: my-app-test
    identifierUris:
    - "dummyurl.com"
  providerConfigRef:
    name: azuread-provider-config
```
    
and getting the error

_Warning  CannotObserveExternalResource  33s    managed/applications.azuread.upbound.io/v1beta1, kind=application  external resource does not exist_

I've tried to use identifierUris as an additional field but still not working. Changing the management policy and using "*" creates a new app instead of updating the existing one. My provider config has ReadWrite permissions for all apps.  
Could you check this issue please? Probably there is some bug in the provider.
