### ISSUE TITLE
Allow packages to depend on arbitrary package types

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#6197]
### What problem are you facing?

At Upbound we'd like to be able to extend our product with new Crossplane package types. These package types would be reconciled by proprietary controllers running alongside Crossplane. We'd like these proprietary package types to be able to depend on upstream Crossplane package types and vice versa.

Today this isn't possible for a few reasons:

1. The `Lock` type that tracks dependencies has a `type` enum field of only the built-in types
2. The `dependsOn` array in package metadata (i.e. `crossplane.yaml`) uses typed field names (e.g. `provider`) to specify a dependency
3. The `resolver` controller resolves and installs package dependencies. It uses strongly typed package objects (e.g. `&v1.Provider{}` to install them.

I could imagine others potentially finding it useful to extend the package manager with their own package types too.

### How could Crossplane help solve your problem?

I believe we could update the Lock and package metadata APIs to allow specifying a dependency on an arbitrary type of package. We could then update the `resolver` controller to use `*Unstructured` resources of the type specified in the lock to install new packages. The dependency resolution process doesn't actually care what type a package is. Only the dependency installation process cares.

**Comment by negz** [comment]
Here's what I propose:

Lock today:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Lock
metadata:
  name: lock
packages:
- name: upbound-configuration-caas-ea16d2b7eb7d
  source: xpkg.upbound.io/upbound/configuration-caas
  type: Configuration
  version: v0.4.0
  dependencies:
  - constraints: v0.11.0
    package: xpkg.upbound.io/upbound/configuration-aws-network
    type: Configuration
```

Proposed update:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Lock
metadata:
  name: lock
packages:
- apiVersion: pkg.crossplane.io/v1
  kind: Configuration
  name: upbound-configuration-caas-ea16d2b7eb7d
  source: xpkg.upbound.io/upbound/configuration-caas
  version: v0.4.0
  dependencies:
  - apiVersion: pkg.crossplane.io/v1
    kind: Configuration
    package: xpkg.upbound.io/upbound/configuration-aws-network
    constraints: v0.11.0
```

Package metadata today:

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-caas
spec:
  dependsOn:
  - configuration: xpkg.upbound.io/upbound/configuration-aws-network
    version: "v0.11.0"
```

Proposed update:

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-caas
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Configuration
    package: xpkg.upbound.io/upbound/configuration-aws-network
    version: "v0.11.0"
```

Crossplane will assume that dependencies "are packages" - i.e. they quack like a Crossplane package type. Specifically all the `resolver` controller cares about today is that the package has a `spec.package` field it can set.

One implication of this change is that the GVK used to install a dependency is now specified by the dependent packages, not internally by Crossplane.

Say for example packages start depending on some new `v1alpha1` package type. We later promote that type to `v1beta1` and drop the alpha type. Today packages don't specify an API version for their dependencies, so they wouldn't need any updates to handle this. After this change, any package that depends on the v1alpha1 type would need to be updated to depend on the v1beta1 type.

I'm hopeful this won't be a problem in practice. We don't add new package types very often, and it's reasonable to expect that folks who adopt alpha features are opting in to a bumpy ride.

**Comment by negz** [comment]
Forgot to mention - this needs to be a backward compatible change. So with that in mind I propose we:

* Introduce the new dependency `apiVersion` and `kind` fields
* Mark the contemporary Lock dependency `type` field and metadata `configuration`, `package, and `function` fields deprecated
* When a dependency doesn't have an `apiVersion` and `kind`, fall back to the deprecated types

**Comment by negz** [comment]
Another implication is that a package could now depend on a type of package that isn't supported by a particular Crossplane installation.

For example say someone creates a Configuration package that depends on a Widget package. The Widget package type is some special proprietary package that only exists inside their organization, but for whatever reason the Configuration is public.

If you try to install that Configuration Crossplane would get stuck trying to install the Widget it depends on, because no such type would exist in your API server.

For Upbound's use case, we're thinking we'd like public Crossplane packages to be able to depend on our proprietary packages but that those dependencies would be nice to have. A package that depends on our proprietary extensions should still work on a vanilla upstream Crossplane install - it'll just lack whatever functionality the proprietary package added.

To address this I propose we make it possible to mark a dependency as optional.

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-caas
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Configuration
    package: xpkg.upbound.io/upbound/configuration-aws-network
    version: "v0.11.0"
    policy: Optional  # Required or Optional - default is Required
```

I'd argue that dependencies should be required by default. Most of the time if your package says it depends on something, it means it needs it to function. Per Upbound's use case though, there is some value in an optional dependency.

**Comment by negz** [comment]
> I propose we make it possible to mark a dependency as optional

Actually, I think this needs more than just a package author marking a dependency as optional. I think the package consumer (i.e. the person who installs it) should be able to specify whether they want the optional dependencies.

Another way to frame this - I don't think optional really means "try to install this but fail gracefully if you can't". What if you really do want the functionality of the optional dependency? In that case I'd argue it's an error if Crossplane can't install it.

The closest example I can think of is Python project dependencies: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-optional-dependencies.

In Python a package author can mark some dependencies as optional. The package consumer then indicates which of those optional dependencies they want at install time.

I'm not sure what that'd look like in Crossplane. Perhaps like this?

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: my-app-model
spec:
  package: xpkg.upbound.io/acme/my-app-model:v1.0.0
  options:
  - apiVersion: pkg.upbound.io/v1
     kind: Widget
  - apiVersion: pkg.acme.io/v1
    kind: CustomExtension
    package: xpkg.upbound.io/acme/extension-apps
```

The first option recursively requires the dependency on all Widget packages the Configuration optionally depends on. It's a bit like enabling the Widget feature generally for this package.

The second option recursively requires one specific CustomExtension package the Configuration optionally depends on. I don't think we need this at first, but it's something we could add in future without a breaking change.

If we made this change we'd need to propagate which optional dependencies a package required/enabled down from the package to the revision to the lock.
