### ISSUE TITLE
TLS handshake error during AWS Provider installation

### ISSUE THREAD

**Issue by mcaruso85** [crossplane/crossplane#6203]
### What happened?
When I apply to my k8s:

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v1.18.1
```
  
I get in the crossplane pod:

TLS handshake error from x.x.x.x:23056: remote error: tls: bad certificate

And in the provider status crd:

Warning UnpackPackage 5m15s (x46 over 45m) packages/provider.pkg.crossplane.io cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request failure: Get "https://xpkg.upbound.io/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority: Get "https://xpkg.upbound.io/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority

And in the k8s node i can pull the image from [xpkg.upbound.io](http://xpkg.upbound.io/) as i have set insecure skip verify for containerd.

root@capi-bootstrap-control-plane:/# crictl pull xpkg.upbound.io/upbound/provider-aws-iam:v1.18.1
Image is up to date for sha256:237a94aa1ea8e224930a19fc3f6aacf7a77fd729c077846973772e2a9bf1995b

### How can we reproduce it?
- Create a kind cluster
- Install crossplane
- Install aws provider

### What environment did it happen in?
Crossplane version: v1.18.2
