### ISSUE TITLE
crossplane render - problems with EnvironmentConfig apiVersion and selection via Reference

### ISSUE THREAD

**Issue by mlubanski** [crossplane/crossplane#6206]
### What happened?

I am trying to run `crossplane render` with Composition which has defined `function-environment-configs` function and as a response I am getting below error:

```bash
crossplane: error: cannot render composite resource: pipeline step "" returned a fatal result: cannot get selected environment configs: expected exactly one extra resource "environment-config-0", got 0
```

`crossplane render` CLI command should instead return rendered Managed Resources

### How can we reproduce it?
Run `crossplane render -c -x --extra-resources environment.yaml --include-context xr.yaml composition.yaml functions.yaml` command with below files:

**environment.yaml**
```yaml
apiVersion: apiextensions.crossplane.io/v1beta1
data:
  mysqlinstance:
    envConfig:
      additionalSecurityGroups:
      - sg-06dcccaawe12
kind: EnvironmentConfig
metadata:
  name: mysqlinstance-v2
```
**functions.yaml**
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.3.0
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-environment-configs
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.2.0
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.8.0
```
**xr.yaml**
```yaml
apiVersion: rdsv2.aws.crossplane.sinch.com/v1alpha1
kind: XMySQLInstance
metadata:
  annotations:
    core.crossplane.sinch.com/awsClusterSecurityGroup: sg-04aedb2cbad797ab5
    core.crossplane.sinch.com/awsDbSubnetGroupName: private_net_vpc-09a920aea5efce3ce
    core.crossplane.sinch.com/awsMqSubnets: '["subnet-0a3e47xxx", "subnet-0f33432dyyy",
      "subnet-0a8783f9b1zzz"]'
    core.crossplane.sinch.com/awsRegion: eu-west-1
    core.crossplane.sinch.com/cluster: eu1lab-eks001
    core.crossplane.sinch.com/deletionPolicy: Delete
    core.crossplane.sinch.com/site: eu1lab
  labels:
    crossplane.io/claim-name: hello-crossplane
    crossplane.io/claim-namespace: crossplane-demo
    crossplane.io/composite: hello-crossplane-97w47
spec:
  claimRef:
    apiVersion: rdsv2.aws.crossplane.sinch.com/v1alpha1
    kind: MySQLInstance
    name: hello-crossplane
    namespace: crossplane-demo
  compositionRef:
    name: mysqlinstances.rdsv2.aws.crossplane.sinch.com-v1alpha1
  compositionRevisionRef:
    name: mysqlinstances.rdsv2.aws.crossplane.sinch.com-v1alpha1-1f2f000
  compositionUpdatePolicy: Automatic
  parameters:
    applyModificationsImmediately: false
    dbInstanceClass: db.t4g.small
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    majorEngineVersion: "8.0"
    maxStorageGB: 1000
    preferredBackupWindow: 14:00-16:00
    preferredMaintenanceWindow: Mon:11:00-Mon:14:00
    storageGB: 20
    storageType: gp3
  publishConnectionDetailsTo:
    configRef:
      name: default
    name: 46a6f629-886b-4a8f-9ba7-c86625d21d38
  resourceRefs:
  - apiVersion: database.aws.crossplane.io/v1beta1
    kind: RDSInstance
    name: hello-crossplane-97w47-x5pr8
...
```
**composition.yaml**
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/composition-hash: 1f2f000d7ab22237126ae46e4b993b22b37c2f484a05bb0c6c4ef6a09f51f61
    crossplane.io/composition-name: mysqlinstances.rdsv2.aws.crossplane.sinch.com-v1alpha1
    crossplane.io/xrd: xmysqlinstances.rdsv2.aws.crossplane.sinch.com
    semverFull: v1.3.5
  name: mysqlinstances.rdsv2.aws.crossplane.sinch.com-v1alpha1-1f2f000
spec:
  compositeTypeRef:
    apiVersion: rdsv2.aws.crossplane.sinch.com/v1alpha1
    kind: XMySQLInstance
  mode: Pipeline
  - functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - ref:
            name: mysqlinstance-v2
          type: Reference
    step: environmentConfigs
  - functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      inline:
        template: |
          ---
          apiVersion: database.aws.crossplane.io/v1beta1
          kind: RDSInstance
          metadata:
            annotations:
              {{ setResourceNameAnnotation "rds" }}
          spec:
            forProvider:
              backupRetentionPeriod: 0
              caCertificateIdentifier: rds-ca-rsa2048-g1
              copyTagsToSnapshot: true
              engine: mysql
              masterUsername: root
              publiclyAccessible: false
              skipFinalSnapshotBeforeDeletion: true
              storageEncrypted: true   
              vpcSecurityGroupIds: [] 
            managementPolicies:
            - '*'
            providerConfigRef:
              name: crossplane-provider-aws
            publishConnectionDetailsTo:
              configRef:
                name: default
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      environment: null
      kind: Resources
      patchSets: []
      resources:
      - name: rds
        patches:
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.maxStorageGB
          toFieldPath: spec.forProvider.maxAllocatedStorage
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.dbInstanceClass
          toFieldPath: spec.forProvider.dbInstanceClass
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.storageType
          toFieldPath: spec.forProvider.storageType
          type: FromCompositeFieldPath
        - fromFieldPath: mysqlinstance_sg
          toFieldPath: spec.forProvider.vpcSecurityGroupIds[0]
          type: FromEnvironmentFieldPath          
        - fromFieldPath: metadata.annotations[mysqlinstance.crossplane.sinch.com/namespaceSG]
          toFieldPath: spec.forProvider.vpcSecurityGroupIds[1]
          type: FromCompositeFieldPath
        - fromFieldPath: mysqlinstance.envConfig.additionalSecurityGroups
          toFieldPath: spec.forProvider.vpcSecurityGroupIds
          policy:
            toFieldPath: AppendArray
          type: FromEnvironmentFieldPath
         ...
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
```

### Detected Issues

**Issue1: EnvironmentVersion apiVersion**
It seems that `crossplane render` command does not recognize properly `apiVersion: apiextensions.crossplane.io/v1beta1` and I had to change it to `apiVersion: apiextensions.crossplane.io/v1alpha1`

**Issue2:  `function-environment-configs` function and `type: Reference` EnvironmentConfig config selector**
`crossplane render` can not find EnvironmentConfig when we are selecting it via Reference name. After switching to `type: Selector` like below it can find it properly

```yaml
  - functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - type: Selector
          selector:
            mode: Single
            matchLabels:
              - key: helm.toolkit.fluxcd.io/name
                type: Value
                value: crossplane-aws-rdsv2-mysqlinstance
```

**Summary:**
After fixing above issues CLI `crossplane render` commands returns rendered Managed Resources

```yaml
---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/composition-resource-name: rds
    crossplane.io/external-name: eu1lab-eks001-crossplane-demo-hello-crossplane
  generateName: hello-crossplane-97w47-
  labels:
    crossplane.io/claim-name: hello-crossplane
    crossplane.io/claim-namespace: crossplane-demo
    crossplane.io/composite: hello-crossplane-97w47
  ownerReferences:
  - apiVersion: rdsv2.aws.crossplane.sinch.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XMySQLInstance
    name: hello-crossplane-97w47
    uid: 46a6f629-886b-4a8f-9ba7-c86625d21d38
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 20
    applyModificationsImmediately: false
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-rsa2048-g1
    copyTagsToSnapshot: true
...
```

### What environment did it happen in?
* Crossplane CLI version: `v1.18.2`
* Kubernetes version `v1.31.2`
* Kubernetes distribution: `EKS`
* `xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.3.0`

**Comment by stefnans** [comment]
I can confirm that with `apiVersion: apiextensions.crossplane.io/v1beta1` of `EnvironmentConfig`, I encounter the same issue. I don't encounter this issue with `apiVersion: apiextensions.crossplane.io/v1alpha1`, but I didn't need to change the `type` to `Selector` as you did, I left it as `Reference`

I don't believe this is to be an issue with the render command, but more with `v1beta1` version of `EnvironmentConfig`

**Comment by chandrasekharkolla** [comment]
I’m experiencing the same issue, but only when running crossplane render. I can successfully apply the resource and retrieve data from the EnvironmentConfig, but rendering fails. Can't we render if we have environmentconfig in the compostion?

```
- step: environmentConfigs
    functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - type: Reference
          ref:
            name: example-environment
- step: vpc-resources
  functionRef:
    name: function-go-templating
  input:
    apiVersion: gotemplate.fn.crossplane.io/v1beta1
    kind: GoTemplate
    source: Inline
    inline: 
      template: |
        {{- if .observed.composite.resource.spec.createVPC }}
        ---
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        metadata:
          name: {{ .observed.composite.resource.metadata.name }}
          annotations:
            gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.metadata.name }}
            test: {{ index .context "apiextensions.crossplane.io/environment" "locations" "eu" }}
        spec:
            forProvider:
              region: us-east-1
              cidrBlock: 10.0.0.0/16
              enableDnsSupport: true
              enableDnsHostnames: true
```
