### ISSUE TITLE
Composition tries to create infinite managed resources when it patches the name field to be the empty string

### ISSUE THREAD

**Issue by jamesdobson** [crossplane/crossplane#6209]
### What happened?
When we patch the name field of a managed resource to be the empty string, we get:
* One managed resource created (if using the `patch-and-transform` function)
* An _ever-increasing number_ of managed resources (if using the legacy mechanism)

We shouldn't be able to end up with many managed resources being created, as in the worst case this could cause a lot of infrastructure to get created. We were using the AWS DynamoDB Table resource (and localstack) so it wasn't bad.

Also, we didn't expect a different behaviour between the new `patch-and-transform` function and the legacy mechanism (though we prefer what `patch-and-transform` does in this case)

We recognize that patching `name` may not be the best idea for us to do, and that we have options like `crossplane.io/external-name` available to us. That said, we don't think we should be able to convince Crossplane to create so many resources by giving it a bad input.

### How can we reproduce it?
In this reproduction, we assume the Kubernetes provider is installed. The resource we are creating is just `ConfigMap`, so you won't have any issues with infrastructure cost due to all the resources that get created.

Here's the XRD:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsimples.example.guidewire.net
spec:
  group: example.guidewire.net
  names:
    kind: xSimple
    plural: xsimples
  claimNames:
    kind: Simple
    plural: simples
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              foo:
                type: string
            required:
              - foo
```

Here's a Composition that doesn't have the problem because it uses the `patch-and-transform` function:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: simple-composition-fn
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: example.guidewire.net/v1alpha1
    kind: xSimple
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: themap
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          spec:
            forProvider:
              manifest:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  namespace: default
                data:
                  constant: first version
                  foo: replace me
        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.foo
            toFieldPath: metadata.name
```

And here's the Composition that does have the problem:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: simple-composition-legacy
spec:
  compositeTypeRef:
    apiVersion: example.guidewire.net/v1alpha1
    kind: xSimple
  resources:
    - name: themap
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                namespace: default
              data:
                constant: first version
                foo: replace me
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.foo
          toFieldPath: metadata.name
```

Create the following claim to see that there is no problem:

```yaml
apiVersion: example.guidewire.net/v1alpha1
kind: Simple
metadata:
  name: test-infinity-ok
  namespace: default
spec:
  foo: ""
  compositionRef:
    name: simple-composition-fn
```

The result should be:

```bash
$ kubectl get simple.example.guidewire.net
kubectl get configmap

NAME               SYNCED   READY   CONNECTION-SECRET   AGE
test-infinity-ok   True     True                        4s
NAME                           DATA   AGE
kube-root-ca.crt               1      2m5s
test-infinity-ok-bdcxh-zs2qq   2      3s
```

Now create a claim using the "legacy" composition:

```yaml
apiVersion: example.guidewire.net/v1alpha1
kind: Simple
metadata:
  name: test-infinity-bad
  namespace: default
spec:
  foo: ""
  compositionRef:
    name: simple-composition-legacy
```

Run:

```bash
$ kubectl get simple.example.guidewire.net
kubectl get configmap
sleep 1 ; date ; kubectl get configmap | wc -l
sleep 1 ; date ; kubectl get configmap | wc -l
sleep 1 ; date ; kubectl get configmap | wc -l
sleep 1 ; date ; kubectl get configmap | wc -l
sleep 1 ; date ; kubectl get configmap | wc -l

NAME                SYNCED   READY   CONNECTION-SECRET   AGE
test-infinity-bad   True     False                       6s
test-infinity-ok    True     True                        25s
NAME                            DATA   AGE
kube-root-ca.crt                1      2m27s
test-infinity-bad-5htwh-2lszp   2      2s
test-infinity-bad-5htwh-4fcsr   2      4s
test-infinity-bad-5htwh-64zd6   2      1s
test-infinity-bad-5htwh-6gd9k   2      2s
test-infinity-bad-5htwh-79ft4   2      1s
test-infinity-bad-5htwh-8dtkh   2      4s
test-infinity-bad-5htwh-8r4c8   2      4s
test-infinity-bad-5htwh-9n2hv   2      1s
test-infinity-bad-5htwh-bp6xg   2      5s
test-infinity-bad-5htwh-cvrgn   2      5s
test-infinity-bad-5htwh-d6dvp   2      2s
test-infinity-bad-5htwh-dnq9d   2      6s
test-infinity-bad-5htwh-dznj5   2      2s
test-infinity-bad-5htwh-flqnv   2      5s
test-infinity-bad-5htwh-fls6g   2      3s
test-infinity-bad-5htwh-gz9hs   2      3s
test-infinity-bad-5htwh-j66ll   2      5s
test-infinity-bad-5htwh-jsd2n   2      5s
test-infinity-bad-5htwh-knpnw   2      4s
test-infinity-bad-5htwh-lbfl8   2      3s
test-infinity-bad-5htwh-nhm92   2      4s
test-infinity-bad-5htwh-p7q8l   2      6s
test-infinity-bad-5htwh-qzpc2   2      2s
test-infinity-bad-5htwh-qzxx7   2      2s
test-infinity-bad-5htwh-s6wvt   2      1s
test-infinity-bad-5htwh-tt449   2      6s
test-infinity-bad-5htwh-vs4vd   2      5s
test-infinity-bad-5htwh-w59wf   2      3s
test-infinity-bad-5htwh-xhlsb   2      0s
test-infinity-bad-5htwh-xvbjl   2      2s
test-infinity-bad-5htwh-z5hl5   2      3s
test-infinity-bad-5htwh-z75tt   2      6s
test-infinity-ok-bdcxh-zs2qq    2      25s
Thu Jan  2 16:44:50 EST 2025
      43
Thu Jan  2 16:44:52 EST 2025
      51
Thu Jan  2 16:44:53 EST 2025
      59
Thu Jan  2 16:44:54 EST 2025
      66
Thu Jan  2 16:44:56 EST 2025
      73
```

You can see the number of `ConfigMap` resources is steadily increasing.

Deleting the Claim does clean up all the resources, eventually:

```bash
# kubectl delete simple.example.guidewire.net test-infinity-bad
sleep 1 ; date ; kubectl get configmap | wc -l
sleep 1 ; date ; kubectl get configmap | wc -l
sleep 1 ; date ; kubectl get configmap | wc -l
sleep 1 ; date ; kubectl get configmap | wc -l
sleep 1 ; date ; kubectl get configmap | wc -l

simple.example.guidewire.net "test-infinity-bad" deleted
Thu Jan  2 16:45:03 EST 2025
      88
Thu Jan  2 16:45:04 EST 2025
      57
Thu Jan  2 16:45:05 EST 2025
      31
Thu Jan  2 16:45:07 EST 2025
       3
Thu Jan  2 16:45:08 EST 2025
       3
```

### What environment did it happen in?
* Crossplane version: 1.18.2
  * xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.1.4
  * xpkg.upbound.io/upbound/provider-kubernetes:v0.16.0
* Kube Version: v1.30.6+k3s1

Thanks!
