### ISSUE TITLE
Support Restricted Pod Security Admission OOTB

### ISSUE THREAD

**Issue by ryanseipp** [crossplane/crossplane#6219]
In my cluster, I'm enforcing the Restricted Pod Security Admission profile on just about every namespace, including `crossplane-system`. To do this, I've configured a `DeploymentRuntimeConfig` on every provider and function that I install for Crossplane.

In doing so, I've realized that every DRC looks exactly the same:
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-auto-ready
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              securityContext:
                allowPrivilegeEscalation: false
                privileged: false
                runAsGroup: 2000
                runAsNonRoot: true
                runAsUser: 2000
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
```

This has made me wonder if Crossplane would be able to configure pods & containers this way out of the box? Doing so would allow me to remove all but one `DeploymentRuntimeConfig` in my cluster (used to give provider-kubernetes a ServiceAccount).

All pods are already configured with a `securityContext` that sets a non-root user and group. This just additionally prevents privilege escalation, sets the seccomp profile, and drops all capabilities, which is possible because all ports the containers listen on are non-privileged. Adding `readOnlyRootFilesystem` could be another option to add, but it isn't enforced by PSA, and I haven't explicitly tested it.
