### ISSUE TITLE
infinite reconciliation of custom claim status with server-side-apply enabled

### ISSUE THREAD

**Issue by stefnans** [crossplane/crossplane#6228]
### What happened?

Resolves #crossplane-contrib/function-status-transformer#45 (issue was originally opened there)

With server-side-apply for claims enabled, a claim's status conditions get updated infinitely when outputting custom status conditions, such as when using the [function-status-transformer](https://github.com/crossplane-contrib/function-status-transformer). This does not happen with SSA off. It looks like the Crossplane reconcile and the SSA are fighting over setting the status of the claim.

![1st_snap_of_claim_function_status_transformer](https://github.com/user-attachments/assets/d8d5ba11-9352-4aaf-b1c5-622685290eb8)

![2nd_snap_of_claim_function_status_transformer](https://github.com/user-attachments/assets/e7efec8a-b55e-406c-8fe4-8b9107d2ff59)

### How can we reproduce it?

I took the example from the AWS quickstart from the Crossplane docs and I added a step in the composition to add custom status conditions to CompositeAndClaim in case of success or error, using the [function-status-transformer](https://github.com/crossplane-contrib/function-status-transformer). 

The xrd, composition, functions and claim manifests can be found below. The issue will occur whether the custom status is about success or error.

**Note**: this is not specific to the function-status-transformer, it applies to any case where you set custom status conditions to the claim.

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.1.4
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.4.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-status-transformer
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-status-transformer:v0.4.0
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: nosqls.database.example.com
spec:
  group: database.example.com
  names:
    kind: NoSQL
    plural: nosqls
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              location:
                type: string
                oneOf:
                  - pattern: '^EU$'
                  - pattern: '^US$'
            required:
              - location
    served: true
    referenceable: true
  claimNames:
    kind: NoSQLClaim
    plural: nosqlclaim
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dynamo-with-bucket
spec:
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: s3Bucket
          base:
            apiVersion: s3.aws.upbound.io/v1beta1
            kind: Bucket
            metadata:
              name: crossplane-quickstart-bucket
            spec:
              forProvider:
                region: us-east-2
              providerConfigRef:
                name: default
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.region"
              transforms:
                - type: map
                  map: 
                    EU: "eu-north-1"
                    US: "us-east-2"
        - name: dynamoDB
          base:
            apiVersion: dynamodb.aws.upbound.io/v1beta1
            kind: Table
            metadata:
              name: crossplane-quickstart-database
            spec:
              forProvider:
                region: "us-east-2"
                writeCapacity: 1
                readCapacity: 1
                attribute:
                  - name: S3ID
                    type: S
                hashKey: S3ID
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.region"
              transforms:
                - type: map
                  map: 
                    EU: "eu-north-1"
                    US: "us-east-2"
                    
  - step: status-handler
    functionRef:
      name: function-status-transformer
    input:
      apiVersion: function-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      statusConditionHooks:
      - matchers:
        - resources:
          - name: "dynamoDB"
          conditions:
          - type: Synced
            status: "True"
        - resources:
          - name: "dynamoDB"
          conditions:
          - type: Ready
            status: "True"
        setConditions:
        - target: CompositeAndClaim
          condition:
            type: CustomCompositionReadiness
            status: "True"
            reason: Ready
            message: "So far so good"
      - matchers:
        - resources: 
          - name: "dynamoDB"
          conditions:
          - type: Synced
            status: "False"
            reason: ReconcileError
            message: "connect failed: (?P<Error>.+)"
        setConditions:
        - target: CompositeAndClaim
          condition:
            type: CustomCompositionReadiness
            status: "False"
            reason: ClaimError
            message: "failed to create table: {{ .Error }}"

  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready

  compositeTypeRef:
    apiVersion: database.example.com/v1alpha1
    kind: NoSQL
---
apiVersion: database.example.com/v1alpha1
kind: NoSQLClaim
metadata:
  name: my-nosql-database
  namespace: crossplane-test
spec: 
  location: "EU"
```

### What environment did it happen in?
Crossplane version: 1.17.3
