### ISSUE TITLE
`enforcedCompositionRef` conflicting with Claim/Composite sync

### ISSUE THREAD

**Issue by wotolom** [crossplane/crossplane#6230]
### What happened?

We are starting using the `enforcedCompositionRef` feature to migrate from a multiple-composition-per-API to a one-compoistion-per-API setup.

While testing we found to 2 major problems with the behaviour of that parameter:

1. after updating an XRD with added  `enforcedCompositionRef`, this only takes effect after a Crossplane Pod restart
2. the Claim/Composite sync (CSA, not tested with SSA alpha feature) is conflicting with `enforcedCompositionRef`  for the setting of `compositionRef`.
   * this results in Claims/Composites with this:
      ```
      spec:
        claimRef:
          apiVersion: cluster/v1alpha1
          kind: NodePool
          name: tenant-nodepool
          namespace: tenant
        compositionRef:
          name: node-pool-iat
        compositionRevisionRef:
          name: node-pool-34014e3
        compositionSelector:
          matchLabels:
            stage: iat
        compositionUpdatePolicy: Automatic
      ``` 
   * in the events of the XR we see the CompositionSelection-loop (increasing loop interval) :
      ```
      Events:
        Type    Reason                Age                From                                                             Message
        ----    ------                ----               ----                                                             -------
        Normal  CompositionSelection  17m (x2 over 53m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Enforced composition has been selected
        Normal  ComposeResources      9m18s              defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully composed resources
      ```
   * sometimes (e.g. in k9s) you can catch the flicker where shortly `compositionRef` has the desired Composition name
   * however the `compositionRevisionRef` seems to never change.
   * also it is possible to delete the old Composition (here "node-pool-iat"), because none of its CompositionRevision is in use
   * Note: in cases/APIs where there is only a Composite (no Claim, e.g. composed via other Composition), we do not see this behaviour 

### How can we reproduce it?

1. base setup: 
   * XRD (without `enforcedCompositionRef`)
   * 2 Compositions (A + B) for that API
   * 1 deployed test Claim that references composition A (directly `compositionRef` or via `compositionSelector`)
2. update the XRD with an enforcedCompositionRef for composition B
3. trigger manually (or wait) for Crossplane Pod restart
4. look at XRC/XR spec and XR Events (as seen in the examples above)

### What environment did it happen in?
Crossplane version: 1.17.1

**Comment by ezgidemirel** [comment]
Hello @wotolom, thanks for opening this issue. I was able to partially reproduce it by starting without enforcement, then adding `enforcedCompositionRef` to switch to a different composition. The reproductions steps are below: 


- Deploy XRD without enforcement and a composite with compositionSelector pointing to GCP.

- Confirm GCP composition is selected.

- Update XRD to add:

```yaml
enforcedCompositionRef:
  name: xbuckets.aws.example.org
```
- Observe the transition from GCP → AWS.


No conflicts observed between `compositionSelector` and `enforcedCompositionRef` on my end. But I needed to restart the Crossplane pod as you mentioned. 

<details> <summary>Initial XRD (no enforcement)</summary>

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.example.org
spec:
  group: example.org
  names:
    kind: XBucket
    plural: xbuckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bucketName:
                  type: string
                  description: "Bucket name"
              required:
                - bucketName
 ```
</details> <details> <summary>AWS Composition</summary>

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.aws.example.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XBucket
  patchSets: []
  resources:
    - name: aws-bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta2
        kind: Bucket
        metadata:
          labels:
            testing.upbound.io/example-name: s3
        spec:
          forProvider:
            region: us-west-1
      patches:
        - fromFieldPath: "spec.bucketName"
          toFieldPath: "metadata.name"
```
</details> <details> <summary>GCP Composition</summary>

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.gcp.example.org
  labels:
    provider: gcp
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XBucket
  resources:
    - name: gcp-bucket
      base:
        apiVersion: storage.gcp.upbound.io/v1beta1
        kind: Bucket
        metadata:
          name: example
          labels:
            example: "true"
        spec:
          forProvider:
            location: US
          deletionPolicy: Delete
      patches:
        - fromFieldPath: "spec.bucketName"
          toFieldPath: "metadata.name"
```
</details> <details> <summary>Initial Composite (GCP selector)</summary>

```
apiVersion: example.org/v1alpha1
kind: XBucket
metadata:
  name: ezgi-bucket
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
  bucketName: "ezgi-test-bucket"
```
</details>


Could you share any relevant controller logs when the sync loop occurs?
