### ISSUE TITLE
skipDependencyResolution has no impact

### ISSUE THREAD

**Issue by mattagohni** [crossplane/crossplane#6275]
### What happened?
We are new to crossplane and are still figuring stuff out. At the moment we experiment with ways how to build/deploy a platform using crossplane. During our experiments we stumbled upon some problems.

We have multiple `configurationPackages` configuring the dependencies they need. In order to have control over the versions of the active `providers` and `functions` we have set `skipDependencyResolution` to `true`. In the configurationPackage of our `platform` we reference the other configurations

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-configuration
  namespace: crossplane-system
spec:
  crossplane:
    version: ">=v1.18.0"
  skipDependencyResolution: true
  dependsOn:
    - configuration: docker-registry-path/configuration-1
      version: ">=v0.0.2"
    - configuration: docker-registry-path/configuration-2
      version: ">=v0.0.1"
```
```yaml
---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-1
spec:
  crossplane:
    version: ">=v1.18.0"
  skipDependencyResolution: true
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.14.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: "v0.8.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: "v0.2.1"
```

```yaml
---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-2
spec:
  crossplane:
    version: ">=v1.18.0"
  skipDependencyResolution: true
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.15.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: "v0.8.0"
```

Our expectation when installing crossplane with the following command

```bash
$ helm install crossplane \          
crossplane-stable/crossplane \
--namespace crossplane-system \
--set configuration.packages='{docker-registry-path/platform-configuration:v0.0.4}'
```
is, that it would not install any of the dependencies declared by the `ConfigurationPackages` we reference in the `platform-configuration`-Package.

### How can we reproduce it?
Applying the above setup on a clean cluster. Our expectation would be, that no providers or functions are installed. But all dependencies where installed automatically. Maybe we get the `skipDependencyResolution` wrong?

### What environment did it happen in?
Crossplane version: 
v1.18.0
k8s version:
v.1.29
OS:
macOs
