### ISSUE TITLE
Service Account Permission : Provider Azure

### ISSUE THREAD

**Issue by thiDucTran** [crossplane/crossplane#6324]
Error: `E0310 19:08:16.929804 1 reflector.go:147] k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: Failed to watch *v1beta1.ProviderConfig: failed to list *v1beta1.ProviderConfig: providerconfigs.azure.upbound.io is forbidden: User "system:serviceaccount:crossplane-system:provider-azure-network-8858ff163911" cannot list resource "providerconfigs" in API group "azure.upbound.io" at the cluster scope`

We are following https://docs.crossplane.io/latest/getting-started/provider-azure/ with these tweaks:
* We are using https://docs.upbound.io/providers/provider-azure/authentication/#user-assigned-managed-identity for authentication. So for our existing AKS cluster we ran: `az aks update --name aks-rd-occluster-mgmt  --resource-group rg-rd-akscluster-mgmt --assign-kubelet-identity /subscriptions/xxx --enable-managed-identity --assign-identity /subscriptions/xxx`

```
$ kubectl get pkgrev
NAME                                                                                       HEALTHY   REVISION   IMAGE                                                                  STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/crossplane-contrib-provider-family-azure-9eb311f0447f   True      1          ghcr.io/crossplane-contrib/provider-family-azure:v1.11.1               Active
           23m
providerrevision.pkg.crossplane.io/provider-azure-network-8858ff163911                     True      1          xpkg.crossplane.io/crossplane-contrib/provider-azure-network:v1.11.1   Active   1           1               23m
```

`$ kubectl get clusterrolebindings.rbac.authorization.k8s.io crossplane:provider:provider-azure-network-8858ff163911:system -o yaml|kubectl-neat`
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane:provider:provider-azure-network-8858ff163911:system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:provider:provider-azure-network-8858ff163911:system
subjects:
- kind: ServiceAccount
  name: provider-azure-network-8858ff163911
  namespace: crossplane-system
```

`$ kubectl get clusterrole crossplane:provider:provider-azure-network-8858ff163911:system -o yaml|kubectl-neat`
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.crossplane.io/system: provider-azure-network-8858ff163911
  name: crossplane:provider:provider-azure-network-8858ff163911:system
rules:
- apiGroups:
  - network.azure.upbound.io
  resources:
  - applicationgateways
  - applicationgateways/status
  - applicationsecuritygroups
  - applicationsecuritygroups/status
  - bastionhosts
  - bastionhosts/status
  - connectionmonitors
  - connectionmonitors/status
  - ddosprotectionplans
  - ddosprotectionplans/status
  - dnsaaaarecords
  - dnsaaaarecords/status
  - dnsarecords
  - dnsarecords/status
  - dnscaarecords
  - dnscaarecords/status
  - dnscnamerecords
  - dnscnamerecords/status
  - dnsmxrecords
  - dnsmxrecords/status
  - dnsnsrecords
  - dnsnsrecords/status
  - dnsptrrecords
  - dnsptrrecords/status
  - dnssrvrecords
  - dnssrvrecords/status
  - dnstxtrecords
  - dnstxtrecords/status
  - dnszones
  - dnszones/status
  - expressroutecircuitauthorizations
  - expressroutecircuitauthorizations/status
  - expressroutecircuitconnections
  - expressroutecircuitconnections/status
  - expressroutecircuitpeerings
  - expressroutecircuitpeerings/status
  - expressroutecircuits
  - expressroutecircuits/status
  - expressrouteconnections
  - expressrouteconnections/status
  - expressroutegateways
  - expressroutegateways/status
  - expressrouteports
  - expressrouteports/status
  - firewallapplicationrulecollections
  - firewallapplicationrulecollections/status
  - firewallnatrulecollections
  - firewallnatrulecollections/status
  - firewallnetworkrulecollections
  - firewallnetworkrulecollections/status
  - firewallpolicies
  - firewallpolicies/status
  - firewallpolicyrulecollectiongroups
  - firewallpolicyrulecollectiongroups/status
  - firewalls
  - firewalls/status
  - frontdoorcustomhttpsconfigurations
  - frontdoorcustomhttpsconfigurations/status
  - frontdoorfirewallpolicies
  - frontdoorfirewallpolicies/status
  - frontdoorrulesengines
  - frontdoorrulesengines/status
  - frontdoors
  - frontdoors/status
  - ipgroups
  - ipgroups/status
  - loadbalancerbackendaddresspooladdresses
  - loadbalancerbackendaddresspooladdresses/status
  - loadbalancerbackendaddresspools
  - loadbalancerbackendaddresspools/status
  - loadbalancernatpools
  - loadbalancernatpools/status
  - loadbalancernatrules
  - loadbalancernatrules/status
  - loadbalanceroutboundrules
  - loadbalanceroutboundrules/status
  - loadbalancerprobes
  - loadbalancerprobes/status
  - loadbalancerrules
  - loadbalancerrules/status
  - loadbalancers
  - loadbalancers/status
  - localnetworkgateways
  - localnetworkgateways/status
  - managermanagementgroupconnections
  - managermanagementgroupconnections/status
  - managernetworkgroups
  - managernetworkgroups/status
  - managers
  - managers/status
  - managerstaticmembers
  - managerstaticmembers/status
  - managersubscriptionconnections
  - managersubscriptionconnections/status
  - natgatewaypublicipassociations
  - natgatewaypublicipassociations/status
  - natgatewaypublicipprefixassociations
  - natgatewaypublicipprefixassociations/status
  - natgateways
  - natgateways/status
  - networkinterfaceapplicationsecuritygroupassociations
  - networkinterfaceapplicationsecuritygroupassociations/status
  - networkinterfacebackendaddresspoolassociations
  - networkinterfacebackendaddresspoolassociations/status
  - networkinterfacenatruleassociations
  - networkinterfacenatruleassociations/status
  - networkinterfacesecuritygroupassociations
  - networkinterfacesecuritygroupassociations/status
  - networkinterfaces
  - networkinterfaces/status
  - packetcaptures
  - packetcaptures/status
  - pointtositevpngateways
  - pointtositevpngateways/status
  - privatednsaaaarecords
  - privatednsaaaarecords/status
  - privatednsarecords
  - privatednsarecords/status
  - privatednscnamerecords
  - privatednscnamerecords/status
  - privatednsmxrecords
  - privatednsmxrecords/status
  - privatednsptrrecords
  - privatednsptrrecords/status
  - privatednsresolverinboundendpoints
  - privatednsresolverinboundendpoints/status
  - privatednsresolveroutboundendpoints
  - privatednsresolveroutboundendpoints/status
  - privatednsresolvers
  - privatednsresolvers/status
  - privatednssrvrecords
  - privatednssrvrecords/status
  - privatednstxtrecords
  - privatednstxtrecords/status
  - privatednszones
  - privatednszones/status
  - privatednszonevirtualnetworklinks
  - privatednszonevirtualnetworklinks/status
  - privateendpointapplicationsecuritygroupassociations
  - privateendpointapplicationsecuritygroupassociations/status
  - privateendpoints
  - privateendpoints/status
  - privatelinkservices
  - privatelinkservices/status
  - profiles
  - profiles/status
  - publicipprefixes
  - publicipprefixes/status
  - publicips
  - publicips/status
  - routefilters
  - routefilters/status
  - routemaps
  - routemaps/status
  - routeserverbgpconnections
  - routeserverbgpconnections/status
  - routeservers
  - routeservers/status
  - routes
  - routes/status
  - routetables
  - routetables/status
  - securitygroups
  - securitygroups/status
  - securityrules
  - securityrules/status
  - subnetnatgatewayassociations
  - subnetnatgatewayassociations/status
  - subnetnetworksecuritygroupassociations
  - subnetnetworksecuritygroupassociations/status
  - subnetroutetableassociations
  - subnetroutetableassociations/status
  - subnetserviceendpointstoragepolicies
  - subnetserviceendpointstoragepolicies/status
  - subnets
  - subnets/status
  - trafficmanagerazureendpoints
  - trafficmanagerazureendpoints/status
  - trafficmanagerexternalendpoints
  - trafficmanagerexternalendpoints/status
  - trafficmanagernestedendpoints
  - trafficmanagernestedendpoints/status
  - trafficmanagerprofiles
  - trafficmanagerprofiles/status
  - virtualhubconnections
  - virtualhubconnections/status
  - virtualhubips
  - virtualhubips/status
  - virtualhubroutetableroutes
  - virtualhubroutetableroutes/status
  - virtualhubroutetables
  - virtualhubroutetables/status
  - virtualhubsecuritypartnerproviders
  - virtualhubsecuritypartnerproviders/status
  - virtualhubs
  - virtualhubs/status
  - virtualnetworkgatewayconnections
  - virtualnetworkgatewayconnections/status
  - virtualnetworkgateways
  - virtualnetworkgateways/status
  - virtualnetworkpeerings
  - virtualnetworkpeerings/status
  - virtualnetworks
  - virtualnetworks/status
  - virtualwans
  - virtualwans/status
  - vpngatewayconnections
  - vpngatewayconnections/status
  - vpngateways
  - vpngateways/status
  - vpnserverconfigurationpolicygroups
  - vpnserverconfigurationpolicygroups/status
  - vpnserverconfigurations
  - vpnserverconfigurations/status
  - vpnsites
  - vpnsites/status
  - watcherflowlogs
  - watcherflowlogs/status
  - watchers
  - watchers/status
  - webapplicationfirewallpolicies
  - webapplicationfirewallpolicies/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
- apiGroups:
  - network.azure.upbound.io
  resources:
  - '*/finalizers'
  verbs:
  - update
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - secrets
  - configmaps
  - events
  - leases
  verbs:
  - '*'
```

AFAIK: from the clusterrole above..seems like a legit error? did I do something wrong?
