### ISSUE TITLE
Bad interaction between a pre-populated function cache and semver tagging

### ISSUE THREAD

**Issue by scoplin** [crossplane/crossplane#6338]
### What happened?
I was attempting to run the `xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1` composition function on my local Docker Desktop kubernetes cluster by pre-populating the package cache in the crossplane pod, which I had mounted as a local volume.  This was really to understand the local dev workflow better.  I downloaded the OCI image and used `up xpkg xp-extract` to extract the crossplane metadata layer (as observed in [this](https://github.com/crossplane-contrib/provider-aws/blob/master/cluster/local/integration_tests.sh#L69) aws-provider integration test).  I placed the output in `<cache>/xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1.gz` and then attempted to deploy the function with `function-dummy.yaml`:

```
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-dummy
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1
  packagePullPolicy: Never
```

However, this persistently produced the message "failed to get pre-cached package with pull policy Never".

It appears the problem may be in the `BuildCache` [function](https://github.com/crossplane/crossplane/blob/01782c157210836cde79e62521392fcc3899dc9e/internal/xpkg/name.go#L106):
```
// BuildPath builds a path with the provided extension.
func BuildPath(path, name, ext string) string {
	full := filepath.Join(path, name)
	existExt := filepath.Ext(full)
	return full[0:len(full)-len(existExt)] + ext
}
```

Given a package name of `xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1`, this function unexpectedly strips the "extension" of `.1`, so crossplane ends up looking for `xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.gz`.

We can work around this with using non-semver tags like `latest`, but this seems like a bit of a footgun for local dev.

To be honest, it's not clear from the code history what the value is in stripping an existing extension -- at least not for this particular use case.

### How can we reproduce it?

Set up a local crossplane install with an exposed package cache.  I used this `helmfile.yaml`:
```
repositories:
  - name: crossplane-stable
    url: https://charts.crossplane.io/stable

releases:
  - name: crossplane
    namespace: crossplane-system
    createNamespace: true
    chart: crossplane-stable/crossplane
    version: "1.19.0"
    values:
      - installCRDs: true
        packageCache:
          pvc: crossplane-package-cache
        extraObjects:
          - apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: crossplane-package-cache
            spec:
              storageClassName: manual
              capacity:
                storage: 1Gi
              accessModes:
                - ReadWriteOnce
              persistentVolumeReclaimPolicy: Retain
              hostPath:
                path: "{{ requiredEnv "PWD" }}/crossplane-cache"
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: crossplane-package-cache
            spec:
              storageClassName: manual
              volumeName: crossplane-package-cache
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
```

And the following function manifest `function-dummy.yaml`:
```
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-dummy
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1
  packagePullPolicy: Never
```

Execute the following commands:

```
# Get the dynamic directory context
export PWD=$(pwd)

# Make our cache directory
mkdir -p $PWD/crossplane-cache/xpkg.upbound.io/crossplane-contrib

# Bring up crossplane
helmfile sync --wait

# Pull the test function and extract its manifests into cache
docker pull xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1
up xpkg xp-extract \
  -o $PWD/crossplane-cache/xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1.gz \
  --from-daemon xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1

# Deploy the function and observe its status
kubectl apply -f function-dummy.yaml
sleep 5
kubectl -n crossplane-system describe function function-dummy
```

Observe the function status as as:
```
Status:
  Conditions:
    Last Transition Time:  2025-03-14T15:34:27Z
    Message:               failed to get pre-cached package with pull policy Never
    Reason:                UnhealthyPackageRevision
    Status:                False
    Type:                  Healthy
    Last Transition Time:  2025-03-14T15:34:27Z
    Reason:                ActivePackageRevision
    Status:                True
    Type:                  Installed
  Current Identifier:      xpkg.upbound.io/crossplane-contrib/function-dummy:v0.2.1
  Current Revision:        function-dummy-xpkg-upbound
```

### What environment did it happen in?
Crossplane version: v1.19.0
Up CLI version: v0.37.1
Docker Desktop Kubernetes (Docker version v4.39.0, kubeadm v1.32.2)
M1 MacBook Pro
Kernel (Mac): Darwin AM-Y2VFWPYFKQ 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:16 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6000 arm64
Kernel (in the Docker VM): Linux f15f5ea4ab56 6.10.14-linuxkit #1 SMP Mon Feb 24 16:35:16 UTC 2025 aarch64 GNU/Linux
