### ISSUE TITLE
provider unusable when installed with skipDependencyResolution: true

### ISSUE THREAD

**Issue by humoflife** [crossplane/crossplane#6360]
### What happened?

When installing a provider with `skipDependencyResolution: true` and separately installing or relying on an existing family provider, the newly installed provider does not receive permissions to list resources. This can result in error messages shown below as seen for multiple different providers installed in the described way.

```
provider-aws-route53:

provider: error: Cannot start controller manager: [failed to list managed resources: failed to get API group resources: unable to retrieve the complete list of server APIs: route53.aws.upbound.io/v1beta1: Get "[https://10.100.0.1:443/apis/route53.aws.upbound.io/v1beta1](https://10.100.0.1/apis/route53.aws.upbound.io/v1beta1)": Service Unavailable, failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]
```

```
provider-aws-sagemaker:

provider: error: Cannot start controller manager: [failed to wait for managed/sagemaker.aws.upbound.io/v1beta1, kind=device caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.Device, failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]
```

```
provider-aws-ec2:

E0325 22:03:50.378405       1 reflector.go:147] k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: Failed to watch *v1beta1.ProviderConfig: failed to list *v1beta1.ProviderConfig: providerconfigs.aws.upbound.io is forbidden: User "system:serviceaccount:crossplane-system:provider-aws-ec2-9372b0c31fc5" cannot list resource "providerconfigs" in API group "aws.upbound.io" at the cluster scope
```

### How can we reproduce it?

Install a provider as follows onto a control plane.

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v1.17.0
  skipDependencyResolution: true
```

Install a family provider.

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v1.17.0
```

Apply a provider config to authorize the provider to manage resources.

Create a resource, e.g. a `vpc`.

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta2/vpcpeeringconnectionaccepter
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: eu-west-1
```

Examine the provider logs `kubectl -n crossplane-system logs provider-aws-ec2-...`

Find entries per below.

```
E0325 22:25:01.900430       1 reflector.go:147] k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: Failed to watch *v1beta1.ProviderConfig: failed to list *v1beta1.ProviderConfig: providerconfigs.aws.upbound.io is forbidden: User "system:serviceaccount:crossplane-system:provider-aws-ec2-9372b0c31fc5" cannot list resource "providerconfigs" in API group "aws.upbound.io" at the cluster scope
```

Note: Installing providers from scratch in the above way worked as expected with the providers having the correct permissions in Crossplane v1.16.x.

Note: Installing a provider from scratch with `skipDependencyResolution: false` pulls in a family provider and RBAC is configured as expected.

Note: After installing a provider with `skipDependencyResolution: true`, and observing the above permissions issues, and then re-applying the provider manifest with `skipDependencyResolution: false` turns the health of the family provider to false and shows the following message in the family provider yaml, because owner reference uid's now do not match between family provider, provider revision and provider config crd. See attached diagram for the uid's that are expected to match but do not any longer. Examine the uid's with
```
kubectl get providerrevision upbound-provider-family-aws-... -o yaml
kubectl get provider.pkg upbound-provider-family-aws -o yaml
kubectl get crd providerconfigs.aws.upbound.io -o yaml 
```

![Image](https://github.com/user-attachments/assets/9e849d28-25ee-4bc0-b9c0-57311ccf78e1)

```
Message:               cannot establish control of object: providerconfigs.aws.upbound.io is already controlled by ProviderRevision upbound-provider-family-aws-20202ddbd61a (UID 7475c970-77ce-47d6-8c4e-b83a2d746c11)
```

```
kubectl get provider.pkg
NAME                          INSTALLED   HEALTHY   PACKAGE                                                AGE
provider-aws-ec2              True        True      xpkg.upbound.io/upbound/provider-aws-ec2:v1.17.0       78m
provider-aws-route53          True        True      xpkg.upbound.io/upbound/provider-aws-route53:v1.16.0   63m
provider-kubernetes           True        True      xpkg.upbound.io/upbound/provider-kubernetes:v0.17.1    3d17h
upbound-provider-family-aws   True        False     xpkg.upbound.io/upbound/provider-family-aws:v1.21.0    62m
```

### What environment did it happen in?
Crossplane version: v1.17.3-up.1 and v1.18.3-up.1

**Comment by turkenf** [comment]
Hi @humoflife,

I attempted to reproduce the issue with the information you provided. I followed your steps on a clean kind cluster, and the VPC resource was created successfully. The issue could not be reproduced with the provided information.

- kubectl get providers.pkg.crossplane.io -w
```
NAME                  INSTALLED   HEALTHY   PACKAGE                                               AGE
provider-aws-ec2      True        True      xpkg.upbound.io/upbound/provider-aws-ec2:v1.17.0      3m25s
provider-family-aws   True        True      xpkg.upbound.io/upbound/provider-family-aws:v1.17.0   114s
```
- kubectl get managed
```
NAME                          SYNCED   READY   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/main   True     True    vpc-0d9e9d9187a5e2b40   42s
```
- kubectl get vpc.ec2.aws.upbound.io/main -o yaml
```
apiVersion: ec2.aws.upbound.io/v1beta1
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ec2.aws.upbound.io/v1beta1","kind":"VPC","metadata":{"annotations":{"meta.upbound.io/example-id":"ec2/v1beta2/vpcpeeringconnectionaccepter"},"labels":{"testing.upbound.io/example-name":"main"},"name":"main"},"spec":{"forProvider":{"cidrBlock":"10.0.0.0/16","region":"eu-east-2"}}}
    meta.upbound.io/example-id: ec2/v1beta2/vpcpeeringconnectionaccepter
  creationTimestamp: "2025-03-27T20:27:38Z"
  generation: 2
  labels:
    testing.upbound.io/example-name: main
  name: main
  resourceVersion: "4618"
  uid: 6d1552b3-c93a-43a5-b06b-8d35d4a478eb
spec:
  deletionPolicy: Delete
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: eu-east-2
    tags:
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: main
      crossplane-providerconfig: default
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2025-03-27T20:27:38Z"
    message: 'connect failed: cannot initialize the Terraform plugin SDK async external
      client: cannot get terraform setup: could not configure the no-fork AWS client:
      cannot construct TF AWS Client from TF AWS Config, [{0 invalid AWS Region: eu-east-2  []}]'
    reason: ReconcileError
    status: "False"
    type: Synced
> kubectl delete managed --all
vpc.ec2.aws.upbound.io "main" deleted
> k applythis
vpc.ec2.aws.upbound.io/main created
> k get vpc.ec2.aws.upbound.io/main -o yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    crossplane.io/external-create-pending: "2025-03-27T20:29:51Z"
    crossplane.io/external-create-succeeded: "2025-03-27T20:29:51Z"
    crossplane.io/external-name: vpc-0d9e9d9187a5e2b40
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ec2.aws.upbound.io/v1beta1","kind":"VPC","metadata":{"annotations":{"meta.upbound.io/example-id":"ec2/v1beta2/vpcpeeringconnectionaccepter"},"labels":{"testing.upbound.io/example-name":"main"},"name":"main"},"spec":{"forProvider":{"cidrBlock":"10.0.0.0/16","region":"us-east-2"}}}
    meta.upbound.io/example-id: ec2/v1beta2/vpcpeeringconnectionaccepter
  creationTimestamp: "2025-03-27T20:29:51Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  labels:
    testing.upbound.io/example-name: main
  name: main
  resourceVersion: "4965"
  uid: bd1d4a56-f6d2-4586-ab44-92ae904c7910
spec:
  deletionPolicy: Delete
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    instanceTenancy: default
    region: us-east-2
    tags:
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: main
      crossplane-providerconfig: default
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-east-2:153891904029:vpc/vpc-0d9e9d9187a5e2b40
    assignGeneratedIpv6CidrBlock: false
    cidrBlock: 10.0.0.0/16
    defaultNetworkAclId: acl-0683c539f08ca90f7
    defaultRouteTableId: rtb-03a75b2aea8177f0d
    defaultSecurityGroupId: sg-09fea669f044c9b32
    dhcpOptionsId: dopt-045881b025a2fba4f
    enableDnsHostnames: false
    enableDnsSupport: true
    enableNetworkAddressUsageMetrics: false
    id: vpc-0d9e9d9187a5e2b40
    instanceTenancy: default
    ipv6AssociationId: ""
    ipv6CidrBlock: ""
    ipv6CidrBlockNetworkBorderGroup: ""
    ipv6IpamPoolId: ""
    ipv6NetmaskLength: 0
    mainRouteTableId: rtb-03a75b2aea8177f0d
    ownerId: "153891904029"
    tags:
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: main
      crossplane-providerconfig: default
    tagsAll:
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: main
      crossplane-providerconfig: default
  conditions:
  - lastTransitionTime: "2025-03-27T20:30:00Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-03-27T20:29:51Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-03-27T20:29:54Z"
    reason: Success
    status: "True"
    type: LastAsyncOperatio
```

When I look at the report, I see the log that I believe to be inconsistent:
```
kubectl get provider.pkg
NAME                          INSTALLED   HEALTHY   PACKAGE                                                AGE
provider-aws-ec2              True        True      xpkg.upbound.io/upbound/provider-aws-ec2:v1.17.0       78m
provider-aws-route53          True        True      xpkg.upbound.io/upbound/provider-aws-route53:v1.16.0   63m
provider-kubernetes           True        True      xpkg.upbound.io/upbound/provider-kubernetes:v0.17.1    3d17h
upbound-provider-family-aws   True        False     xpkg.upbound.io/upbound/provider-family-aws:v1.21.0    62m
```
Earlier, we installed version `v1.17.0` of the provider-family-aws, but the log output shows `v1.21.0`. This could be because they set `skipDependencyResolution: false` after receiving an error, but in any case, I could not reproduce the issue with clean steps from scratch. 
After seeing these logs, I realized that the `skipDependencyResolution: true` setting might not have been applied to every provider, or perhaps there was a family provider package automatically installed in the cluster previously. Based on the warning from the Upbound documentation ([Install Providers in an offline environment](https://docs.upbound.io/providers/provider-families/#installing-a-provider-family:~:text=services%20to%20install.-,Install%20Providers%20in%20an%20offline%20environment,-View%20the%20installed)), when we installing multiple providers, we should apply `skipDependencyResolution: true` to every Provider.
Could you please check and let us know?

Thanks in advance

**Comment by humoflife** [comment]
The above repro steps were performed on a newly created Upbound control plane. I will re-repro the behavior and follow-up.

**Comment by humoflife** [comment]
When reproducing the above behavior, the providers remain unhealthy because of another reason now.
```
NAME                  INSTALLED   HEALTHY   PACKAGE                                               AGE
provider-aws-ec2      True        False     xpkg.upbound.io/upbound/provider-aws-ec2:v1.17.0      11m
provider-family-aws   True        False     xpkg.upbound.io/upbound/provider-family-aws:v1.17.0   9m12s
```

```
    message: 'post establish runtime hook failed for package: provider package deployment
      is unavailable with message: Deployment does not have minimum availability.'
```

**Comment by jbw976** [comment]
Were you able to look at the deployments and pods for these providers in the `crossplane-system` namespace? e.g. `kubectl -n crossplane-system describe deployment <deploymentName>` etc.? Curious what could be preventing the deployments from rolling out and their pods starting up OK...

**Comment by devops-inthe-east** [comment]
I too have been plaque with the exact same issue when trying to install the provider in an offline mode. 

- Chart Name: universal-crossplane
- Chart version: v1.18.0-up.1.rc.0.tgz
- Image version: v1.17.1
- Provider version: 1.23

My values.file for crossplane chart : 

```
universal-crossplane:
  externalSecretStoresEnabled: false
  image:
    repository: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/crossplane
    tag: v1.17.1-up.1
    pullPolicy: IfNotPresent
  bootstrapper:
    image:
      repository: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/uxp-bootstrapper
      tag: v1.17.1-up.1
      pullPolicy: IfNotPresent
    config:
      debugMode: true  [Even after enabling this option, the logs level are only info level]
  provider:
    packages: 
      - ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-family-aws:v1
      - ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-iam:v1
      - ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-sns:v1
      - ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-sqs:v1
      - ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-cloudwatchevents:v1
```

The status of the provider are:

```
cloudification-upbound-provider-aws-cloudwatchevents   True        False     023951383515.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-cloudwatchevents:v1   14h
cloudification-upbound-provider-aws-iam                True        False     023951383515.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-iam:v1                14h
cloudification-upbound-provider-aws-sns                True        False     023951383515.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-sns:v1                14h
cloudification-upbound-provider-aws-sqs                True        True      023951383515.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-sqs:v1                14h
cloudification-upbound-provider-family-aws             True        False     023951383515.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-family-aws:v1             14h
```

Logs from one of the non-working providers [cloudwatchevents]:

```
k8s.io/client-go@v0.29.4/tools/cache/reflector.go:229: Failed to watch *v1beta1.Permission: failed to list *v1beta1.Permission: permissions.cloudwatchevents.aws.upbound.io is forbidden: User "system:serviceaccount:platform:cloudification-upbound-provider-aws-cloudwatcheven-cab8eab35d6b" cannot list resource "permissions" in API group "cloudwatchevents.aws.upbound.io" at the cluster scope
provider: error: Cannot start controller manager: failed to wait for managed/cloudwatchevents.aws.upbound.io/v1beta1, kind=connection caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.Connection
```

**Comment by devops-inthe-east** [comment]
@turkenf / @jbw976 , apologies for the direct tag, however I'd like to know if I am missing something important with regards to the installation

**Comment by devops-inthe-east** [comment]
There is one very peculiar thing occurs when installing the crossplane &  provider family . Crossplane install the provider family from using the **xgql** repo and not from the internal repo. 

Can this mean, the flag  **skipDependencyResolution: true** is suppose to be passed to the crossplane chart too, given that I am installing the provider in the offline mode. 

```
kubectl get Provider -A 

NAME                                                   INSTALLED   HEALTHY   PACKAGE                                                                                          AGE
cloudification-upbound-provider-aws-cloudwatchevents   True        Unknown   ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-cloudwatchevents:v1   6m5s
cloudification-upbound-provider-aws-iam                True        Unknown   ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-iam:v1                6m5s
cloudification-upbound-provider-aws-sns                True        Unknown   ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-sns:v1                6m5s
cloudification-upbound-provider-aws-sqs                True        True      ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-aws-sqs:v1                6m5s
cloudification-upbound-provider-family-aws             True        Unknown   ***.dkr.ecr.eu-central-1.amazonaws.com/cloudification/upbound/provider-family-aws:v1.23          6m5s
upbound-provider-family-aws                            True        True      xpkg.upbound.io/upbound/provider-family-aws:v1.23.                                               2m1s
```

**Comment by bobh66** [comment]
I think we probably need to put some comments in the documentation/values.yaml file to clarify that installing providers from the helm chart is a convenience feature that is only intended to work in the most basic environments, and if you need to do anything like pull from a private repository, set `skipDependencies`, specify a `DeploymentRuntimeConfig`, it _will not_ work for those scenarios.  Either that or enhance the values.yaml interface to support the full DRC/Provider/Function specification which seems like a lot of work for not a lot of benefit considering that I think "most" deployments (whatever that means) install the providers separately from manifests.

**Comment by bobh66** [comment]
Actually the existing `extraObjects` parameter in values.yaml will let you create anything you want at deploy time so you can put fully specified `DeploymentRuntimeConfigs` and `Providers` and `Functions` configured however you need them

**Comment by devops-inthe-east** [comment]
Hello @bobh66,  After following suggestion, I encounter a situation wherein the crossplane chart dont get installed, due to a deadlock b/w provider CRDs. 

Here the values.yaml and we use ArgoCD. 

```
universal-crossplane:
  externalSecretStoresEnabled: false
  image:
    repository: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/crossplane
    tag: v1.17.1-up.1
    pullPolicy: IfNotPresent
  bootstrapper:
    image:
      repository: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/uxp-bootstrapper
      tag: v1.17.1-up.1
      pullPolicy: IfNotPresent
    config:
    # -- Enable debug mode for bootstrapper.
    debugMode: true
  extraObjects:
  # AWS Provider Family
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-family-aws
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-family-aws:v1.23
      skipDependencyResolution: true

   # IAM Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-aws-iam
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-iam:v1
      skipDependencyResolution: true
      
  # CloudWatch Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-aws-cloudwatch
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-cloudwatchevents:v1
      skipDependencyResolution: true
      
  # SNS Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-aws-sns
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-sns:v1
      skipDependencyResolution: true
      
  # SQS Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: provider-aws-sqs
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-sqs:v1
      skipDependencyResolution: true  
  
  # ProviderConfig for AWS AuthN
  - apiVersion: aws.upbound.io/v1beta1
    kind: ProviderConfig
    metadata:
      name: default
    spec:
      credentials:
        source: IRSA
```

Error visible on ArgoCD 

```
The Kubernetes API could not find version "v1" of pkg.crossplane.io/Provider for requested resource platform/provider-family-aws. Version "v1beta1" of externaldata.gatekeeper.sh/Provider is installed on the destination cluster.

The Kubernetes API could not find aws.upbound.io/ProviderConfig for requested resource platform/default. Make sure the "ProviderConfig" CRD is installed on the destination cluster
```

I presume this occurs as CRDs not being available when Helm tries to install the Provider objects. 

As the **extraObjects** are applied during Helm installation, but the Provider CRDs need to be installed by Crossplane first.(Chicken & Egg Problem)

**Comment by bobh66** [comment]
Can you try adding a `"helm.sh/hook": post-install` annotation to each of the `extraObjects` - that might trigger helm to wait until after Crossplane is installed to render the `extraObjects`:
```
extraObjects:
  # AWS Provider Family
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      annotations:
        "helm.sh/hook": post-install
      name: provider-family-aws
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-family-aws:v1.23
      skipDependencyResolution: true

   # IAM Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      annotations:
        "helm.sh/hook": post-install
      name: provider-aws-iam
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-iam:v1
      skipDependencyResolution: true
      
  # CloudWatch Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      annotations:
        "helm.sh/hook": post-install
      name: provider-aws-cloudwatch
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-cloudwatchevents:v1
      skipDependencyResolution: true
      
  # SNS Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      annotations:
        "helm.sh/hook": post-install
      name: provider-aws-sns
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-sns:v1
      skipDependencyResolution: true
      
  # SQS Provider
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      annotations:
        "helm.sh/hook": post-install
      name: provider-aws-sqs
    spec:
      package: ***.dkr.ecr.eu-central-1.amazonaws.com/***/upbound/provider-aws-sqs:v1
      skipDependencyResolution: true  
  
  # ProviderConfig for AWS AuthN
  - apiVersion: aws.upbound.io/v1beta1
    kind: ProviderConfig
    metadata:
      annotations:
        "helm.sh/hook": post-install
      name: default
    spec:
      credentials:
        source: IRSA
```
