### ISSUE TITLE
Composite cannot create named configmap; field not declared in schema

### ISSUE THREAD

**Issue by zevisert-aaico** [crossplane/crossplane#6362]
### What happened?

I was working on a larger composition, and I needed to create a configmap with a specific `metadata.name` - I get an error saying: 
```
status:
  conditions:
  - lastTransitionTime: "2025-03-27T23:08:17Z"
    message: 'cannot compose resources: cannot update composite resource spec.resourceRefs:
      failed to create typed patch object (/minimal-reproducible-example; composites.ops.aaico.com/v1alpha1,
      Kind=ConfigMapNameBug): .spec.resourceRefs[0].namespace: field not declared
      in schema'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### How can we reproduce it?

<details><summary>Install Crossplane 1.19.0 with fluxcd.io via helm</summary>

```yaml
# run `flux install --namespace=flux-system` to install these CRDs
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane-stable
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane-core
  namespace: flux-system
spec:
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
      version: 1.19.0
  install:
    createNamespace: true
  interval: 5m0s
  targetNamespace: crossplane-system
  releaseName: crossplane-core
```

</details> 

<details><summary>Install the patch-and-transform function (0.8.2) </summary>

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.8.2
```

</details> 

<details><summary>Create this CompositeResourceDefinition</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: configmapnamebugs.example.com
spec:
  group: example.com
  names:
    kind: ConfigMapNameBug
    listKind: ConfigMapNameBugList
    plural: configmapnamebugs
    singular: configmapnamebug
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
```

</details> 

<details><summary>Create this Composition</summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: configmap-name-bug-composition
spec:
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: ConfigMapNameBug
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: target-cm
            base:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                # name: <patched>
                namespace: flux-system
              data: {}
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
```

</details> 

<details><summary>Apply this XR</summary>

```yaml
apiVersion: example.com/v1alpha1
kind: ConfigMapNameBug
metadata:
  name: minimal-reproducible-example
spec: {}
```

</details> 

### What environment did it happen in?
Crossplane version: 1.19.0
Kubernetes distribution: v1.32.2-eks-bc803b4
