### ISSUE TITLE
Empty array ([]) as shortNames causes error Invalid value: "object": Value is immutable

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#6369]
### What happened?
We had some compositions with `shortNames: []`, which used to work fine.

We now se that we cannot create new clusters with this CompositeResourceDefinition.

Probably related to https://github.com/crossplane/crossplane/pull/5682

### How can we reproduce it?
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xmydatabases.example.org
spec:
  group: example.org
  names:
    kind: XMyDatabase
    plural: xmydatabases
    shortNames: []
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
```

```
  Warning  EstablishComposite  3s (x2 over 4s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot add composite resource finalizer: cannot update object: CompositeResourceDefinition.apiextensions.crossplane.io "xmydatabases.example.org" is invalid: spec.names: Invalid value: "object": Value is immutable
```

### What environment did it happen in?
Crossplane version: 1.18.2
EKS 1.31.6
