### ISSUE TITLE
Wrap likely RBAC errors with a hint

### ISSUE THREAD

**Issue by jingliming** [crossplane/crossplane#6397]
Edit from @negz: See https://github.com/crossplane/crossplane/issues/6397#issuecomment-2877624018. 

```
Timeout: failed waiting for *unstructured.Unstructured Informer to sync
```

This error means the controller-runtime machinery can't start a cache informer for some type. This could be for a number of reasons but it's most often either:

* Crossplane doesn't have RBAC access to list/watch the type
* The type doesn't exist - e.g. typo in the apiVersion/kind or the CRD isn't installed

Ideally we'd wrap this obscure error with a hint to let folks know what's (probably) happening.

Original issue follows:

---

### What happened?
When I test crossplane xrd with document, the synced and ready fields of composite are empty, and the managed resource was not created.

![Image](https://github.com/user-attachments/assets/b9e14ec8-7d6b-45ad-8bfa-57e58669b87d)

```
kubectl describe composite vpc-crossplane
Name:         vpc-crossplane
Namespace:    
Labels:       crossplane.io/composite=vpc-crossplane
              testing.upbound.io/example-name=vpc-crossplane
Annotations:  meta.upbound.io/example-id: vpc/v1alpha1/vpc
API Version:  core.bizworks.dev/v1alpha1
Kind:         XVPC
Metadata:
  Creation Timestamp:  2025-04-23T02:22:18Z
  Finalizers:
    composite.apiextensions.crossplane.io
  Generation:        3
  Resource Version:  1680920
  UID:               0849ae65-1224-4e17-8003-550e1e109fdf
Spec:
  Cidr Block:  172.16.1.0/12
  Composition Ref:
    Name:  example-composition
  Composition Revision Ref:
    Name:                     example-composition-d23549f
  Composition Update Policy:  Automatic
  Name:                       vpc-crossplane
  Region:                     cn-hangzhou
Events:
  Type     Reason             Age    From                                                             Message
  ----     ------             ----   ----                                                             -------
  Normal   SelectComposition  2m31s  defined/compositeresourcedefinition.apiextensions.crossplane.io  Successfully selected composition: example-composition
  Normal   SelectComposition  2m31s  defined/compositeresourcedefinition.apiextensions.crossplane.io  Selected composition revision: example-composition-d23549f
  Warning  ComposeResources   31s    defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot compose resources: cannot generate a name for composed resource "aliyun-vpc": Timeout: failed waiting for *unstructured.Unstructured Informer to sync
```

### How can we reproduce it?
1. apply xrd
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcs.core.bizworks.dev
spec:
  group: core.bizworks.dev
  names:
    kind: XVPC
    plural: xvpcs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                cidrBlock:
                  type: string
                name:
                  type: string
              required:
                - region
                - cidrBlock
                - name
```
2. apply composition
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-composition
spec:
  compositeTypeRef:
    apiVersion: core.bizworks.dev/v1alpha1
    kind: XVPC
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: aliyun-vpc
            base:
              apiVersion: vpc.alicloud.crossplane.io/v1alpha1
              kind: VPC
              spec:
                forProvider:
                  cidrBlock: 172.16.2.0/12
                  vpcName: test
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.cidrBlock
                toFieldPath: spec.forProvider.cidrBlock
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: spec.forProvider.vpcName
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.annotations
                toFieldPath: metadata.annotations
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels
                toFieldPath: metadata.labels
```
5. apply xr
```
apiVersion: core.bizworks.dev/v1alpha1
kind: XVPC
metadata:
  name: vpc-crossplane
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: vpc-crossplane
spec:
  region: cn-hangzhou
  cidrBlock: 172.16.1.0/12
  name: vpc-crossplane

```
function was already installed.

![Image](https://github.com/user-attachments/assets/8bb22471-1af7-4599-812a-50d694184fb4)

### What environment did it happen in?
* Crossplane version:  1.19.0
* Cloud provider : aliyun provider generated from upjet
* Kubernetes version :v1.30.7
* Kernel : Darwin MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64
