### ISSUE TITLE
secret generated from writeConnectionSecretToRef on gcp cluster MR has empty user token in kubeconfig

### ISSUE THREAD

**Issue by rahulrayal** [crossplane/crossplane#6400]
### What happened?
While using the field `writeConnectionSecretToRef` in the `Cluster` (`v1beta2`) MR of `upbound/provider-gcp-container@v1.12.0`. We have observed that the kubeconfig added in the secret created by `writeConnectionSecretToRef` has empty user token

```
users:
- name: test-cluster-54-97hfp
  user: {}
```

### How can we reproduce it?

You can apply this MR manifest and after the creation of the cluster is successful you can check the kubeconfig in the `test-secret` of `test-namespace`

```
apiVersion: container.gcp.upbound.io/v1beta2
kind: Cluster
metadata:
  name: test-cluster
spec:
  providerConfigRef:
    name: test-provider-config
  forProvider:
    deletionProtection: false
    location: test-location
    removeDefaultNodePool: true
    enableAutopilot: false
    initialNodeCount: 1
  writeConnectionSecretToRef:
    name: test-secret
    namespace: test-namespace
```

### What environment did it happen in?
Crossplane version: `v1.19.0`
