### ISSUE TITLE
publishConnectionDetailsTo to kubernetes secret on gcp cluster MR does not create any secret

### ISSUE THREAD

**Issue by rahulrayal** [crossplane/crossplane#6402]
### What happened?
While using the field `publishConnectionDetailsTo` (with `default` configRef) in the Cluster (v1beta2) MR of upbound/provider-gcp-container@v1.12.0. We have observed that no secret is created and also there is no way to mention the namespace in which secret should be created/exist

### How can we reproduce it?
You can apply this MR manifest and after the creation of the cluster is successful you can see that no secret with name `test-secret` is created in any namespace

```
apiVersion: container.gcp.upbound.io/v1beta2
kind: Cluster
metadata:
  name: test-cluster
spec:
  providerConfigRef:
    name: test-provider-config
  forProvider:
    deletionProtection: false
    location: "us-east4"
    removeDefaultNodePool: true
    enableAutopilot: false
    initialNodeCount: 1
  publishConnectionDetailsTo:
    name: test-secret
    configRef:
      name: default
```

### What environment did it happen in?
Crossplane version: `v1.19.0`
