### ISSUE TITLE
ImageConfig and default registry interact in surprising ways

### ISSUE THREAD

**Issue by adamwg** [crossplane/crossplane#6428]
### What happened?

Suppose you set Crossplane's deafult registry to a private registry called `registry.example.com`. You then apply the following `ImageConfig` to authenticate to `registry.example.com` with a pull secret:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: ImageConfig
metadata:
  name: private-registry-auth
spec:
  matchImages:
    - prefix: registry.example.com
  registry:
    authentication:
      pullSecretRef:
        name: private-registry-pull-secret
```

Then you create the following package:

```yaml
# This configuration has a private dependency. See package/crossplane.yaml.
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: my-configuration
spec:
  package: my-team/my-configuration:v0.1.0
```

Crossplane will apply the default registry when pulling the package, resulting in a pull from `registry.example.com/my-team/my-configuration:v0.1.0`. However, because ImageConfigs are matched based on the `package` field in the spec, not the resolved reference, the pull secret will not be used, resulting in an authentication failure.

### How can we reproduce it?

See above.

### Possible solutions

1. (After #6421 is merged) Resolve refs using the default registry at the same as we apply ImageConfig rewrites, and store the resulting fully qualified path in `ResolvedImage`/`ResolvedPackage`. Then, always look up pull secret ImageConfigs based on those fields rather than resolving the ref again.
2. Eliminate the default registry and require fully-qualified references everywhere. This would be a breaking change, but would reinforce the best practice.
