### ISSUE TITLE
Allow XRDs to configure the `scale` subresource

### ISSUE THREAD

**Issue by LCaparelli** [crossplane/crossplane#6443]
### What problem are you facing?

Compositions may be used to create abstractions that naturally implement a resource that can be scaled. For example:

- a composition that manages, among other resources, a `Deployment`
- a composition that manages, among other resources, a load balancer with configurable capacity allocation (eg, [AWS ELB reserved capacity](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.12/guide/ingress/annotations/#capacity-unit-reservation))

Allowing users to define XRDs with the [`scale` subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource) would allow for integration with other machinery that relies on this subresource, such as [KEDA](https://github.com/kedacore/keda/issues/703).

### How could Crossplane help solve your problem?

By allowing users to define the `scale` subresource for XRDs.

**Comment by jbw976** [comment]
Thanks for sharing this idea @LCaparelli! Can you share some more details on how you think this should look, from a UX perspective but also how it could be implemented? I can see some value here for certain shapes of XRs (depending on what they compose), but it's also possible it could be a bit awkward for other cases because XRs are an aggregation of multiple heterogeneous resources that may not share the same scaling semantics, and surfacing a single scale subresource at the XR level could get awkward 🤔 

Some more details about your intended experience with examples could be useful! 🙇‍♂

**Comment by vrabbi** [comment]
@jbw976 can we reopen this? i think this would be extremely beneficial. all it would need is to enable the addition of the subresource section in the XRD from the schema of a CRD. this would enable XRD authors to implement subresources freely including scale subresources without much work needed on the side of crossplane. this is something we would really benefit from for creating abstractions for workloads, especially since 2.0 where applications are first class citizens and crossplane is much more app ready and not just infra ready. the actual logic of what the scale will do, is down to the composition itself and its handling of the fields mapped to the subresource for example of scale.

**Comment by jbw976** [comment]
sure, happy to re-open this issue! and it can make more sense in the v2 world where you can compose arbitrary resources.

IIUC, the request here is to be able to define `subresources` within an XRD, similar to how it's possible in CRDs:
```
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: apps.example.crossplane.io
spec:
  scope: Namespaced
  group: example.crossplane.io
  names:
    kind: App
    plural: apps
  versions:
  - name: v1
     schema:
       # same ol' schema as always
       <omitted>
     # new subresources config
     subresources:
       scale:
         specReplicasPath: .spec.replicas
         statusReplicasPath: .status.replicas
         labelSelectorPath: .status.selector
```

Crossplane would need to propagate this `subresources` configuration to the CRD it generates, then composition authors would have the responsibility to take these `scale` related values and map them to their composed resources appropriately. For example, using `function-patch-and-transform` and a `Deployment` resource:
```
    resources:
      - name: deployment
        base:
          apiVersion: apps/v1
          kind: Deployment
          spec:
            replicas: 1
        patches:
          # Map XR replicas -> Deployment replicas
          - type: FromCompositeFieldPath
            fromFieldPath: spec.replicas
            toFieldPath: spec.replicas
```  

Does that UX sketch sound correct to what you all are thinking? 🤓
