### ISSUE TITLE
Realtime composition rendering spinning with valid resources when not using `mode: Pipeline`

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#6461]
### What happened?
On a test cluster with 1.20.0-rc.1 I see a couple of compositions "spinning", reconciling a resource in a tight loop.

#### provider-aws tags

In one case there's an old community provider-aws version with arrray based tags:

```yaml
    tags:
    - key: kubernetes_namespace
      value: demoimage
```

the provider then instantly writes back:

```yaml
    - key: crossplane-name
      value: app-7x459-m86pn
    - key: crossplane-providerconfig
      value: default
    - key: crossplane-kind
      value: repository.ecr.aws.crossplane.io
```

This itself is not a new issue, but it didn't spin this quick before. I think there should be some kind of protection against this as the CloudTrail, GuardDuty and EKS audit log bills will be huge for anyone on AWS running into this and similar issues.

#### provider-kubernetes apiVersion / conversion

Another issue where I see a similar issue, but with unknown cause, is a provider-kubernetes resource where the composition uses `v1alpha1` instead of `v1alpha2`.

### How can we reproduce it?

```yaml
apiVersion: example.com/v1alpha1
kind: Spin
metadata:
  name: spinner
  namespace: crossplane-system
spec: {}
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositespins.example.com
spec:
  group: example.com
  names:
    kind: CompositeSpin
    plural: compositespins
  claimNames:
    kind: Spin
    plural: spins
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties: {}
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositespins.example.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: CompositeSpin
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                namespace: crossplane-system
```

### What environment did it happen in?
Crossplane version: 1.20.0-rc.1
