### ISSUE TITLE
Consider deprecation warning for Composition resources / `mode: Resources`

### ISSUE THREAD

**Issue by chlunde** [crossplane/crossplane#6466]
### What problem are you facing?
I was working on a composition and didn't notice it was not using `mode: Pipeline`.

It would be great with a warning when doing this.
Ideally it would be part of the CRD, which could be supported in editors and validators/linteres, but it doesn't look like there's a Warning or deprecation feature in kubernetes CRDs: https://github.com/kubernetes/kubernetes/issues/123161

### How could Crossplane help solve your problem?

This seems to work for humans, but there's no information here that this is a deprecation warning:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "resources-deprecated.crossplane.io"
spec:
  failurePolicy: Ignore
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apiextensions.crossplane.io"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["compositions"]
  validations:
    - expression: "!has(object.spec.resources)"
      message: "The Resources mode is deprecated, and you shouldn't use it. Crossplane supports Compositions that use the Resources mode for backward compatibility, but the feature is no longer maintained. Crossplane doesn't accept new Resources features, and only accepts security bug fixes."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "resources-deprecated.crossplane.io"
spec:
  policyName: "resources-deprecated.crossplane.io"
  validationActions: [Warn]
```

```console
$ k create -f composition.yaml 
Warning: Validation failed for ValidatingAdmissionPolicy 'resources-deprecated.crossplane.io' with binding 'resources-deprecated.crossplane.io': The Resources mode is deprecated, and you shouldn't use it. Crossplane supports Compositions that use the Resources mode for backward compatibility, but the feature is no longer maintained. Crossplane doesn't accept new Resources features, and only accepts security bug fixes.
```
