### ISSUE TITLE
Unready Claim with ready XR

### ISSUE THREAD

**Issue by duizabojul** [crossplane/crossplane#6482]
## Description
In Crossplane 1.20 with real-time compositions enabled, some claims incorrectly report a `Ready: False` condition with the message "Composite resource is not yet ready" even though the associated composite resource is actually ready. This condition becomes stale and does not update automatically, requiring a Crossplane pod restart to resolve.

## Reproduction Conditions
This issue is difficult to reproduce consistently and appears to occur under specific conditions:
- When "starting" a new cluster
- During simultaneous deployment of a Crossplane stack and multiple claims
- Under high concurrency/load conditions

## Example

```
apiVersion: storage.crossplane.airnity.io/v1alpha1
kind: GCPBucket
metadata:
  finalizers:
  - finalizer.apiextensions.crossplane.io
  generation: 3
  name: tempo
  namespace: tempo
  resourceVersion: "11369202"
  uid: 10a27ff1-083c-464a-bcec-0e248c083fab
spec:
  compositeDeletePolicy: Foreground
  compositionRef:
    name: storage-gcpbucket-v1alpha1
  compositionRevisionRef:
    name: storage-gcpbucket-v1alpha1-6c5c995
  params:
    deletionPolicy: Retain
    permissions:
    - member:
        gkeWorkloadIdentity:
          name: tempo
      roles:
      - OWNER
  resourceRef:
    apiVersion: storage.crossplane.airnity.io/v1alpha1
    kind: XGCPBucket
    name: tempo-hgvjf
status:
  conditions:
  - lastTransitionTime: "2025-05-22T12:22:45Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-05-22T12:33:38Z"
    reason: Available
    status: "True"
    type: Ready
---
apiVersion: storage.crossplane.airnity.io/v1alpha1
kind: XGCPBucket
metadata:
  creationTimestamp: "2025-05-22T12:22:45Z"
  finalizers:
  - composite.apiextensions.crossplane.io
  generation: 6
  labels:
    crossplane.io/claim-name: tempo
    crossplane.io/claim-namespace: tempo
    crossplane.io/composite: tempo-hgvjf
  name: tempo-hgvjf
  resourceVersion: "11369216"
  uid: 07a46475-852a-45e0-8650-4fc6a488774c
spec:
  claimRef:
    apiVersion: storage.crossplane.airnity.io/v1alpha1
    kind: GCPBucket
    name: tempo
    namespace: tempo
  compositionRef:
    name: storage-gcpbucket-v1alpha1
  compositionRevisionRef:
    name: storage-gcpbucket-v1alpha1-6c5c995
  compositionUpdatePolicy: Automatic
  params:
    deletionPolicy: Retain
    permissions:
    - member:
        gkeWorkloadIdentity:
          name: tempo
      roles:
      - OWNER
  resourceRefs:
  - apiVersion: iam.crossplane.airnity.io/v1alpha1
    kind: XGCPRolesBinding
    name: tempo-hgvjf-09c205
  - apiVersion: kubernetes.crossplane.io/v1alpha2
    kind: Object
    name: tempo-hgvjf-config-map
  - apiVersion: storage.gcp.upbound.io/v1beta2
    kind: Bucket
    name: rnt-sandbox-telco-par-1-tempo-tempo
  writeConnectionSecretToRef:
    name: 07a46475-852a-45e0-8650-4fc6a488774c
    namespace: crossplane-secrets
status:
  conditions:
  - lastTransitionTime: "2025-05-22T12:22:52Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-05-22T12:23:08Z"
    reason: Available
    status: "True"
    type: Ready
  connectionDetails:
    lastPublishedTime: "2025-05-22T12:22:52Z"
```

You can see with `lastTransitionTime` that claim got ready 10min after XR, after i rebooted crossplane pod

Here are logs of controller before reboot

[crossplane.log](https://github.com/user-attachments/files/20392428/crossplane.log)

**Comment by negz** [comment]
FWIW I can't immediately think of a reason that realtime composition would affect the claim -> XR relationship. I don't think the feature touched any of that code.

**Comment by ytsarev** [comment]
I hit the same with e2e testing of https://github.com/upbound/configuration-observability-oss/ 

Extremely long readiness status propagation time from XR to Claim 

```
crossplane beta trace oss uptest-observability
NAME                                                                                            SYNCED   READY   STATUS
Oss/uptest-observability (default)                                                              True     False   Waiting: Claim is waiting for composite resource to become Ready
└─ XOss/uptest-observability-786ks                                                              True     True    Available
   ├─ Usage/usageprometheusbypodmonitorcrossplane-uptest-observability-oss-cluster              -        True    Available
   ├─ Usage/usageprometheusbypodmonitorcrossplanerbacmanager-uptest-observability-oss-cluster   -        True    Available
   ├─ Usage/usageprometheusbypodmonitorproviders-uptest-observability-oss-cluster               -        True    Available
   ├─ Release/releaseprometheus-uptest-observability-oss-cluster                                True     True    Available
   ├─ Object/podmonitorcrossplane-uptest-observability-oss-cluster                              True     True    Available
   ├─ Object/podmonitorcrossplaneproviders-uptest-observability-oss-cluster                     True     True    Available
   └─ Object/podmonitorcrossplanerbacmanager-uptest-observability-oss-cluster                   True     True    Available
```

**Comment by haarchri** [comment]
same issue here 

```
NAME                                          RESOURCE   SYNCED   READY   STATUS
EC2Instance/uptest-basic-ec2 (default)                   True     False   Waiting: Claim is waiting for composite resource to become Ready
└─ XEC2Instance/uptest-basic-ec2-7rhj9                   True     True    Available
   └─ Instance/uptest-basic-ec2-7rhj9-7lvpr   instance   True     True    Available
NAME                                          RESOURCE   SYNCED   READY   STATUS
EC2Instance/uptest-basic-ec2 (default)                   True     False   Waiting: Claim is waiting for composite resource to become Ready
└─ XEC2Instance/uptest-basic-ec2-7rhj9                   True     True    Available
   └─ Instance/uptest-basic-ec2-7rhj9-7lvpr   instance   True     True    Available
NAME                                          RESOURCE   SYNCED   READY   STATUS
EC2Instance/uptest-basic-ec2 (default)                   True     False   Waiting: Claim is waiting for composite resource to become Ready
└─ XEC2Instance/uptest-basic-ec2-7rhj9                   True     True    Available
   └─ Instance/uptest-basic-ec2-7rhj9-7lvpr   instance   True     True    Available
NAME                                          RESOURCE   SYNCED   READY   STATUS
EC2Instance/uptest-basic-ec2 (default)                   True     False   Waiting: Claim is waiting for composite resource to become Ready
└─ XEC2Instance/uptest-basic-ec2-7rhj9                   True     True    Available
   └─ Instance/uptest-basic-ec2-7rhj9-7lvpr   instance   True     True    Available
```

**Comment by n3wscott** [comment]
I have not been able to reproduce this bug unless I have a function that is not ready in the composition. I have been trying for a while. I am doing the following based on https://github.com/crossplane/crossplane/issues/6482#issuecomment-2987947056:

```
while true; do kubectl apply -f ./all.yaml; sleep 1; kubectl apply -f ./all.yaml; sleep 30; kubectl delete -f ./all.yaml; sleep 5; done
```

watching everything with `watch kubectl describe oss` and `watch kubectl describe xoss`

`all.yaml` is 

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xosss.observe.platform.upbound.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: observe.platform.upbound.io
  names:
    kind: XOss
    plural: xosss
  claimNames:
    kind: Oss
    plural: osss
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Monitoring configuration parameters.
                  properties:
                    id:
                      type: string
                      description: ID of this Cluster to enable Monitoring with OSS Prometheus and Grafana
                    operators:
                      type: object
                      description: Operators parameters.
                      properties:
                        prometheus:
                          type: object
                          description: Prometheus operator parameters.
                          properties:
                            version:
                              type: string
                              description: Prometheus chart version.
                    deletionPolicy:
                      description: When the Composition is deleleted, delelete the AWS resources. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                  required:
                    - id
              required:
                - parameters
            status:
              type: object
              properties:
                backup:
                  description: Freeform field containing status information for uxp-datadog
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: foos.example.com
spec:
  defaultCompositeDeletePolicy: Foreground
  group: example.com
  names:
    kind: Foo
    plural: foos
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.10.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: crossplane-contrib-function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.4.0
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xosss.observe.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: observe.platform.upbound.io/v1alpha1
    kind: XOss
  mode: Pipeline
  pipeline:
    - step: create-a-bucket
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: example.com/v1alpha1
            kind: Foo
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: foo
            spec: {}
    - functionRef:
        name: crossplane-contrib-function-auto-ready
      step: auto-ready
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: foos.example.com
spec:
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: Foo
  mode: Pipeline
  pipeline:
    - functionRef:
        name: crossplane-contrib-function-auto-ready
      step: auto-ready
---
apiVersion: observe.platform.upbound.io/v1alpha1
kind: Oss
metadata:
  name: test-oss
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: configuration-observability-oss
    operators:
      prometheus:
        version: "52.1.0"
```

So if someone who gets into the situation again, please also dump the events and status of all of the involved resources.
