### ISSUE TITLE
[v2] Drop runtime `image` and `permissionRequests` configs from the provider/function meta

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#6487]
### What problem are you facing?

Currently, one can specify a different runtime image for a given provider or function from the image of the package itself. For example:

```yaml
apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-foo
spec:
  controller:
    image: acme.registry.io/orgfoo/my-foo-provider-container:v1.2.3
```

While this configuration offers some flexibility, we are not aware of any actual **Providers** or **Functions** utilizing it. However, it introduces significant complexity to the codebase and packaging tooling, as it effectively necessitates the use of two container images for a single package. Consequently, issues such as registry defaults, versioning, and the discovery and mirroring of required images must be addressed for this separate image. Furthermore, accessing metadata in the runtime implementations requires "parsing the package" (i.e., `--package-runtime=External`).

Another similar configuration with no real world usage is `spec.controller.permissionRequests` in the **Provider** meta (not available for **Functions**) 

### How could Crossplane help solve your problem?

I would suggest dropping those two configurations (i.e., `spec.controller.image` and `spec.controller.permissionRequests`) from the package metadata in v2. Although we believe they don't have real world usages, this could be considered as a breaking change since the package meta api is v1 and I think it is a good opportunity to clean them up with v2.
