### ISSUE TITLE
[v2] Simplify XR -> FunctionRevision selection

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#6545]
### What problem are you facing?

An XR is reconciled by a pipeline of composition functions. The XR specifies what Composition to use, and the Composition specifies what Functions to use.

Behind the scenes, there's really two layers of revisions:

* An XR _really_ uses a CompositionRevision - a snapshot a Composition at a particular spec generation
* The running function is _really_ determined by the active function revision - a specific OCI digest of the function package

At the time of writing only one function revision can be active (running and serving requests), but [the Controlled Rollout design](https://github.com/crossplane/crossplane/blob/ab50a06c3deef4338fc71d05c8eb0c2bb8dfe1aa/design/one-pager-controlled-rollout-of-composition-functions.md) proposes we change that.

When a user creates an XR, they might want the following behaviors:

* I don't have any opinion about what Composition Crossplane uses
* I only want Crossplane to use a specific (named) Composition
* I want Crossplane to use a Composition with certain properties (cloud, region, etc)
* I want Crossplane to use a particular channel of a Composition - stable, beta, etc
* When the Composition changes, I want to automatically pickup the latest changes
* When the Composition changes, I want to explicitly opt-in to pickup the latest changes

When a Composition author specifies a function to use, they might want the following behaviors:

* I only want Crossplane to use a named function (e.g. `function-python`) - use the latest revision
* I only want Crossplane to use a function with a specific OCI ref (e.g. `xpkg.crossplane.io/crossplane-contrib/function-python:v1.0.0`)
* I only want Crossplane to use a particular channel of a named function - stable, beta, blue, green, etc

There's a couple of things we could improve about the current implementation.

#### Selecting a CompositionRevision is verbose

Here's an example of a hypothetical XR that uses all the fields it can use today to select a composition revision:

```yaml
apiVersion: example.org
kind: XR
metadata:
  name: example
spec:
  compositionRef:
    name: my-composition
  compositionSelector:
    matchLabels:
      cloud: aws
  compositionRevisionRef:
    name: my-composition-somehash
  compositionRevisionSelector:
    matchLabels:
      channel: stable
  # Don't automatically update the revision ref
  compositionUpdatePolicy: Manual
```

It's unlikely you'd actually write this composition. You'd probably use only some of the refs and selectors. For example:

```yaml
apiVersion: example.org
kind: XR
metadata:
  name: example
spec:
  compositionRef:
    name: my-composition
  compositionRevisionSelector:
    matchLabels:
      channel: stable
  compositionUpdatePolicy: Manual
```

Crossplane would resolve the selector and pin the related ref though, so you'd probably need to _read_ the more verbose example above.

The Controlled Rollout design proposes replicating this pattern to Composition -> FunctionRevision selection. So a pipeline step in a Composition could look like this:

```yaml
spec:
  pipeline:
  - step: use-function-python
     functionRef:
       name: function-python
     functionRevisionSelector:
       matchLabels:
         channel: stable
```

#### A CompositionRevision's composition logic can change over time

A CompositionRevision _seems_ like a snapshot of composition logic, and before functions were introduced it was. Today though it's actually a snapshot of a pipeline of functions. Those functions could change to point to new function revisions, with potentially completely different logic. 

### How could Crossplane help solve your problem?

After a brainstorm session with @n3wscott and @adamwg I propose we do the following:

1. Collapse `<T>` and `<T>Revision` referencing and selection
1. Always resolve and pin specific FunctionRevisions in a CompositionRevision's pipeline

#### Collapse `Composition` and `CompositionRevision` referencing and selection

I propose we:

* Have our controllers automatically label revisions with things you might want to select on - e.g. composition name
* Drop `compositionRef`, `compositionSelector`, and `compositionRevisionRef` - only select revisions

The scenarios I laid out earlier would look like this:

##### I don't have any opinion about what Composition Crossplane uses

No change from today. Just omit `spec.crossplane` completely.

##### I only want Crossplane to use a specific (named) Composition

Select revisions of that composition by name:

```yaml
apiVersion: example.org
kind: XR
metadata:
  name: example
spec:
  crossplane:
    compositionRevisionSelector:
      matchLabels:
        crossplane.io/composition-name: my-composition
```

Crossplane adds the `crossplane.io/composition-name` label automatically. Crossplane always selects the latest matching revision.

#####  I want Crossplane to use a Composition with certain properties (cloud, region, etc)

```yaml
apiVersion: example.org
kind: XR
metadata:
  name: example
spec:
  crossplane:
    compositionRevisionSelector:
      matchLabels:
        example.org/cloud-provider: aws
```

Crossplane always selects the latest matching revision.

##### I want Crossplane to use a particular channel of a Composition - stable, beta, etc

```yaml
apiVersion: example.org
kind: XR
metadata:
  name: example
spec:
  crossplane:
    compositionRevisionSelector:
      matchLabels:
        crossplane.io/composition-name: my-composition
        example.org/release-channel: beta
```

##### When the Composition changes, I want to automatically pickup the latest changes

This is the default behavior in all of the preceding examples.

##### When the Composition changes, I want to explicitly opt-in to pickup the latest changes

I'm not sure what the best way to address this is under this proposal. You could explicitly pin a revision like this:

```yaml
apiVersion: example.org
kind: XR
metadata:
  name: example
spec:
  crossplane:
    compositionRevisionSelector:
      matchLabels:
        crossplane.io/composition-name: my-composition
        crossplane.io/composition-revision-hash: hashhash
```

The problem is you'd need to know what revision was the latest when you create the XR. Today you just set `compositionUpdatePolicy: Manual` and Crossplane figures it out for you.

I could imagine moving this revision-pinning functionality into a separate controller.

#### Collapse `Function` and `FunctionRevision` referencing and selection

I propose we:

* Have our controllers automatically label revisions with things you might want to select on - e.g. function name, function OCI ref, digest
* Drop `functionRef` - only select revisions

##### I only want Crossplane to use a named function

```
spec:
  pipeline:
  - step: function-negz-compose-a-bucket
    functionRevisionSelector:
      matchLabels:
        crossplane.io/function-name: function-negz-compose-bucket
```

##### I only want Crossplane to use a function with a specific OCI ref

```
spec:
  pipeline:
  - step: function-negz-compose-a-bucket
    functionRevisionSelector:
      matchLabels:
        crossplane.io/function-package: xpkg.crossplane.io/negz/function-compose-bucket:v1.0.0  # Or a SHA256 digest
```

I think this is the most interesting one - it allows you to specify a function revision by OCI ref in your Composition. No need to worry about function Kubernetes names, or specifically what revision is running the tag you want to use.

##### I only want Crossplane to use a particular channel of a named function

```
spec:
  pipeline:
  - step: function-negz-compose-a-bucket
    functionRevisionSelector:
      matchLabels:
        crossplane.io/function-name: function-negz-compose-bucket
        example.org/release-channel: stable
```

Always uses the latest matching revision.

#### Always resolve and pin specific FunctionRevisions in a CompositionRevision's pipeline

This one's pretty straightforward. The Composition controller would resolve function revision selectors _before_ creating a CompositionRevision, and create the revision with pinned revision references - not selectors. e.g.:

```
spec:
  pipeline:
  - step: function-negz-compose-a-bucket
    functionRevisionName: function-negz-compose-a-bucket-somehash
```

**Comment by negz** [comment]
We also discussed keeping refs, but using them as schemafied convenience aliases. So for example instead of:

```yaml
spec:
  pipeline:
  - step: function-negz-compose-a-bucket
    functionRevisionSelector:
      matchLabels:
        crossplane.io/function-name: function-negz-compose-bucket
```

You could write:

```yaml
spec:
  pipeline:
  - step: function-negz-compose-a-bucket
    functionRef:
      name: function-negz-compose-bucket
```

The two would be semantically equivalent - under the hood Crossplane would translate the second example to the first.

I like that:

* This is backward compatible for anyone using `fooRef.name` to set refs today
* It makes the most common revision labels more discoverable - the ref isn't a `map[string]string` but a schemafied object

However when writing up this issue I found that describing this felt like it complicated the proposal. I started to feel things'd be simpler to just have one way to do the thing - revision selector - even though this does rely on folks knowing what well-known selector labels Crossplane creates and how to use them.

**Comment by negz** [comment]
> I'm not sure what the best way to address [automatically pinning composition revisions] is under this proposal.

One approach that crossed my mind was to keep using `compositionUpdatePolicy`. So if you write this:

```yaml
apiVersion: example.org
kind: XR
metadata:
  name: example
spec:
  crossplane:
    compositionRevisionSelector:
      matchLabels:
        crossplane.io/composition-name: my-composition
    compositionUpdatePolicy: Manual
```

Crossplane will automatically add a label selector to pin the latest revision for you (if it's not already set):

```yaml
apiVersion: example.org
kind: XR
metadata:
  name: example
spec:
  crossplane:
    compositionRevisionSelector:
      matchLabels:
        crossplane.io/composition-name: my-composition
        crossplane.io/composition-revision-hash: hashhash
    compositionUpdatePolicy: Manual
```

This feels like the smallest change compared to the current API.
