### ISSUE TITLE
Extend xpkg spec for specifying additional data in `meta.pkg.crossplane.io`

### ISSUE THREAD

**Issue by jastang** [crossplane/crossplane#6550]
### What problem are you facing?

The [xpkg specification](https://github.com/crossplane/crossplane/blob/main/contributing/specifications/xpkg.md#object-annotations) allows third-party consumers of Crossplane packages to define arbitrary key-value pairs in `metadata.annotations` of a package metadata.

While this gives reasonable flexibility, annotations lack support for more complex and structured metadata. An example that may be interesting to consumers is a list of capabilities or feature flags a Provider has enabled.

### How could Crossplane help solve your problem?

Codify in the xpkg spec that third-party consumers may specify custom structured metadata in a package metadata YAML file (typically `crossplane.yaml`). This enables more expressiveness and organization over flattened string annotations.

Package metadata differs from live, reconciled objects like `Deployments` - Kubernetes does not care about or interpret it, and Crossplane is only concerned with specific fields in the [package meta spec ](https://github.com/crossplane/crossplane/blob/c98ccb3fdf79584a6f0708c13173848c42e1000c/apis/pkg/meta/v1/meta.go#L20)for dependency resolution or Crossplane version constraints.

Naming aside, I propose a convention of a `spec.metadataExtensions` block for this purpose. 

1. Using `spec` is not inherently "bad" in this context, though it may be semantically confusing to readers. `metadata` signals that this is meant to be non-reconciled metadata/information.
2. Consumers can independently add custom schema validation in their tooling or automation, for example, enforcing enums.

Flat metadata should still live in namespaced `metadata.annotations` where appropriate. Extending `ObjectMeta` would be interesting, but not as straightforward, given the types are defined upstream.

#### Example
```
apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-foo
  annotations:
    meta.crossplane.io/maintainer: john.doe@coolcompany.ai
spec:
    metadataExtensions:
        capabilities:
          - name: observability
            maturity: stable
            enabled: true
          - name: enhanced-changelogs
            maturity: beta
            enabled: true
          - name: quantum-ai-oracle
            maturity: alpha
            enabled: false
```
