### ISSUE TITLE
remove empty status blocks from CRDs

### ISSUE THREAD

**Issue by cppforlife** [crossplane/crossplane#690]
### What happened?

It seems that CRDs included in the helm chart all include:

```yaml
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

I don't believe cleared out `status` section is necessary and can be removed. I noticed it when using kapp (https://get-kapp.io) to install crossplane (`helm template ... | kapp deploy ...`).

Is there a reason it's present in CRDs?
