### ISSUE TITLE
Honoring inter-resource dependency when creating/deleting resources

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane#708]
### What problem are you facing?

When creating multiple managed resources simultaneously to implement a *resource configuration* (see #707), it is often the case that in order to provision resource  `B`, resource `A` needs to be already provisioned and ready. For example, in order to create a `Subnet` instance which consumes a `VPC` instance, the latter has to be already created. 

Similarly, deleting a managed resource might result in a few orphan resources which depend on the deleted resource and might affect the system operability. As an example deleting a resource which manages credentials for other resources, will most likely leave other resources in a faulty state.

In the case of creating resources, one argument could be that since Crossplane gradually reconciles the resource state, even if the initial attempts of creation fail because the depending resource does not yet exist, subsequent attempts will eventually succeed once all required resources are provisioned. While this is true for a lot of cases, it is worth noting that being dependent on another resource does not necessarily mean being blocked from provisioning by the cloud provider. In other words, the dependency might be logical rather than physical. For instance in AWS case, imagine an `eksCluster` resource is depending on an `iamRolePolicyAttachment` resource, where the latter assigns the required policies to the `eksCluster` resource so that it could operate as intended. This dependency is logical, and it will not block AWS provider from provisioning an `eksCluster` in the absence of `iamRolePolicyAttachment`. Now if the provisioning the `iamRolePolicyAttachment` keeps failing for whatever reason, the created eks cluster will not be operational even though its managed state in Crossplane is *Ready*.

### How could Crossplane help solve your problem?

To solve this, I propose the notion of *resource dependency* in consuming resource's spec:

  ```yaml
  ...
  metadata:
    - namespace: example
      name: sample
  ...
  spec:
    ...
    dependsOn:
      # a list of strings, each in name.namespace format
      - requiredResource1Name.requiredResourceNamespace
      - requiredResource2Name.requiredResourceNamespace
    ...
  ...
  ```

This indicates that provisioning `sample.example` instance needs to wait until all required resources are ready. Similarly, deleting `requiredResource1Name.requiredResourceNamespace` instance will be blocked as long as there are any consuming resource instance (like `sample.example`).

**Comment by negz** [comment]
If we do introduce a `dependsOn` stanza I believe we'll need to include type metadata for each dependency, as name and namespace are insufficient to uniquely identify an arbitrary kind of Kubernetes resource. The Kubernetes [API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#references-to-related-objects) recommend either label selectors or [object references](https://godoc.org/k8s.io/api/core/v1#ObjectReference) for this, for example:

```yaml
spec:
  dependsOnRefs:
  - apiVersion: cool.crossplane.io/v1alpha1
    kind: cool
    namespace: coolns
    name: coolname
  - apiVersion: cool.crossplane.io/v1alpha1
    kind: cooler
    namespace: coolns
    name: coolname
```

We may also need to revisit how we communicate that a managed resource is ready for its dependent managed resources to consume. Currently all managed resources [expose a conditioned status and a binding status](https://github.com/crossplaneio/crossplane-runtime/blob/e4d61e/apis/core/v1alpha1/resource.go#L53).

In practice all contemporary managed resources implement the `Ready` condition type, but doing so is not mandatory. Furthermore, conditioned status is designed for human rather than programmatic consumption, providing no straightforward API to query which conditions are true. In retrospect believe that design decision to be due to a misunderstanding of #275 

Binding status _is_ intended (and currently used) for programmatic consumption, but has a slightly misleading name and is only strictly required by managed resources that can be bound to resource claims.

We may also need to consider dependency cycle detection, what happens if a dependent resource becomes transitions from ready to unready, etc.

**Comment by negz** [comment]
I noticed while reading about the GCP Config Connector yesterday that [they use](https://cloud.google.com/config-connector/docs/how-to/creating-resource-references) what appear to be [a subset of `ObjectReference`](https://cloud.google.com/config-connector/docs/reference/resources#pubsubsubscription) (just kind, namespace, and name) to model dependencies. We could use a similar pattern if each managed resource controller knew in advance the kinds it depended on. This would make our API something like:

```yaml
spec:
  dependsOn:
    someResourceKindRef:
      name: coolresource
    anotherResourceKindRef:
      name: coolerresource
```

**Comment by bassam** [comment]
Can we use configMaps to capture dependencies between objects?

**Comment by negz** [comment]
> Can we use configMaps to capture dependencies between objects?

Could you elaborate on how this might look? it sounds a bit awkward to me.

Kubernetes typically seems to prefer handling dependencies via eventual consistency; you apply everything and if something is not ready its dependents wait until it is before proceeding. If we solve #707 and also standardise how managed resources communicate their readiness. We should be able to simply short circuit reconciles until all directly dependent resources are ready for consumption.

**Comment by soorena776** [comment]
@negz I think what @bassam is suggesting is to have a config map `dependency-cm` which stores all the dependency information in one place for better visibility (instead of spreading it across all resources). Then, each resource that is involved in a dependency graph will simply have a field like `dependency-graph: dependency-cm`, form which its dependency needs to be satisfied.

**Comment by suskin** [comment]
I was thinking about this recently, and related to the config map question, I believe it is worth asking exactly what the consumer resources are depending on in their dependencies. Is it names? Secrets?

If I am understanding @soorena776 's description correctly, I am thinking about a very similar idea. I am wondering whether it would make sense for dependencies to be modeled as follows:

**Dependency declaration**

* Let's say a resource R1 depends on a resource R2. The specific thing that R1 needs is the `id` from R2.
* R1 would express its dependency as a reference to some object holding `R2.id`. For the sake of argument, let's say the id is published to a Secret called `secrets.r2.id`, and that is what `R1` declares a dependency on.

**Dependency resolution**

* R1 would not be created until `secrets.r2.id` exists
* In general, R1 would not be created until all of its dependencies exist
* When R2 is created, its `id` would be published to `secrets.r2.id`
* Once `secrets.r2.id` is created, R1's dependencies are all resolved, and it will be created

I am thinking that what I am describing all sounds very similar to what is being discussed already, but I want to make sure we are making it clear that the point of dependencies is that consumers want to inject or use some value or object, not that consumers just want to wait for their dependencies to exist.

Maybe it would make sense to ask: what are the types of dependencies we want to model? Having the full picture seems helpful, and maybe we'll be able to address them separately. I believe so far we have described:

* A consumer can be created, but to become healthy and ready it needs a configuration value from a dependency
* A consumer needs a configuration value from a dependency, and can not be provisioned until that value is ready
* A consumer does not need any configuration values from its dependency, but needs its dependency to exist (I am having trouble coming up with a concrete example for this one, so I would appreciate help with this)

What do other people think?

**Comment by soorena776** [comment]
Thanks @suskin for the input! 

  > I want to make sure we are making it clear that the point of dependencies is that consumers want to inject or use some value or object, not that consumers just want to wait for their dependencies to exist.
1. If I am understanding you correctly, you want the dependency to be always to an API object. Given that the resources that say `R1` depends on, are themselves have a corresponding API object in K8S api (e.g. `R2.Status`), why do you think creating separate secret objects is necessary?

2. I think we should keep it simple, by just addressing dependency between resources 
I'm not convinced at least at this point there is a need to publish `R2.id` to a secret

3. My idea about a dependency config-map looks like the following:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-dependency-conf
  namespace: myns
data:
  resources-aliases:
    - r1
        name: mySubnet
        namespace: infra-ns
    - r2
        name: myVPC
        namespace: infra-ns 
    - r3
        name: myInternetGateway
        namespace: infra-ns
    dep-map:
    - r1:
       - alias: r2
          property: id
    - r3:
       - alias: r2
          property: id
       - alias: r1
          property: cidrBlock
```
The big advantage would be that one could look at the config map and see the inter resource relationships.

I also have to say I also think we could implement dependency between resources w/o using a configmap, as it's done in [Google Config Connector](https://cloud.google.com/config-connector/docs/how-to/creating-resource-references), by just adding an attribute directly in the object's spec.
