### ISSUE TITLE
Share resource class specTemplate config across multiple environments: dev, test, prod

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#757]
**What seems to be the problem?**
The upcoming [GitLab integration](https://gitlab.com/groups/gitlab-org/-/epics/1866) populates a set of default resource classes to get new users going more quickly. However for the [GCP example](https://gitlab.com/groups/gitlab-org/-/epics/1866#2-configure-crossplane-for-use-with-your-cloud-provider): region and allowedNetworks will need to be set in most of the resource classes, which must be repeated across each resource class. 

In particular, enabling managed service provisioning on a GitLab connected cluster requires:
- configure region in provider.yaml (AWS) or in all the resource classes (GCP)
- configure allowedNetworks in the resource classes
- duplicate resource classes in the GitLab project `crossplane/classes` folder per environment (dev, test, prod) if they have separate clusters, networks, etc.

**What can Crossplane do to help?**
It would be nice to have environmental attributes (region, allowedNetworks, etc.) captured in a single resource that could be configured once per [GitLab environment](https://docs.gitlab.com/ee/ci/environments.html#defining-environments) (dev, staging, prod - with [separate k8s clusters](https://docs.gitlab.com/ee/user/project/clusters/#multiple-kubernetes-clusters-premium), networks, subnets, etc.) and referenced from resource claims or provided as the default environment in a given namespace, so the GitLab user can configure these settings once per environment, instead of having to go through each of the resource classes and find the attributes to configure.

This would allow a resource claim similar to:

```yaml
apiVersion: database.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: cloudsqlinstancepostgresql
spec:
  environmentRef:
    kind: Environment
    apiVersion: core.crossplane.io/v1alpha2
    name: environment
    namespace: prod
  classRef:
    kind: CloudsqlInstanceClass
    apiVersion: database.gcp.crossplane.io/v1alpha2
    name: cloudsqlinstancepostgresql
    namespace: crossplane-system
  writeConnectionSecretToRef:
    name: cloudsqlinstancepostgres
  engineVersion: "9.6"
```

**Related:**
#340
