### ISSUE TITLE
Scoped verb access to CRDs a package depends on

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#758]
This issue started with discussion in https://github.com/crossplaneio/crossplane/pull/672#discussion_r319581410

### What problem are you facing?
As per the stacks security and isolation [design doc](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stacks-security-isolation.md#allowed-resource-access), a stack will be given access to all verbs on CRDs that the stack depends on:

> The allowed verbs for the CRDs the stack owns and depends on will be the same. Stacks will likely need full CRUD access, regardless of if the stack owns or depends on the CRD.

This is because most stacks will likely need to create instances of CRDs they depend on (e.g. WordPress stack will create instances of `MySqlInstance` and `KubernetesCluster`) and the stack will also need to update and delete those instances.  Essentially full CRUD access.

However, some stacks may want more scoped down access though, such as read only verbs (GET, LIST, WATCH).

This isn't blocking v0.3, as this isn't a critical part of the design and the user experience design isn't clear yet so it will take a bit of thinking through.

### How could Crossplane help solve your problem?

When a stack declares the CRDs that it depends on, perhaps it could also declare the type of access (verbs) that it wants for those CRDs as well.  Example:

```yaml
dependsOn:
- kind: Foo
  apiversion: mygroup.io/v1alpha1
  verbs: "get,create,update,delete"
- kind: Bar
  apiversion: yourgroup.io/v1alpha2
  verbs: "get,watch"
```

Another example that instead of explicitly specifying verbs, specifies usage intent instead:

```yaml
dependsOn:
- kind: Foo
  apiversion: mygroup.io/v1alpha1
  readOnly: true
```

Since the stack author has declared `readOnly: true`, the Stack Manager would grant read only verbs, such as GET, LIST, and WATCH.

These examples are not completely in agreement with how dependencies are being specified (the author should be able to express a stack package they depend on instead of just CRDs), but it is meant to convey the spirit of the experience that we may want to allow.
