### ISSUE TITLE
Create design doc for optional automatic reconciliation

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane#834]
### What problem are you facing?

Crossplane automatically updates external resources when it finds one has drifted from the specified configuration (i.e. the cloud-specific class `spec`). It is not clear that this is always desired by a user.

### How could Crossplane help solve your problem?

The first step would be creating a design document that the Crossplane community could discuss / converge on.

#### Rough Proposal

Crossplane could implement an `autoUpdate` boolean field on all resource claim types where, if set to to `true`, managed reconcilers would operate as they currently do. However, if `autoUpdate` was set to `false`, the managed reconciler would create a `ProposedDiff` object in the namespace of the claim with a reference to the managed resource. The `ProposedDiff` would have a boolean field `apply` that would initially be set to `false`. If a user wanted the diff to be applied to the resource, it would `kubectl edit` the diff, changing `apply` to `true`. The managed reconciler would check for outstanding `ProposedDiff` objects (or a reference to a proposed diff could be added to the managed resource) for the resource during reconciliation. If a diff exists for the managed resource with `apply: true`, the update would then be made to the external resource.

#### Open Questions

1. How would multiple proposed diffs for a single managed resource be handled? Could only one exist at a time?
1. Should `ProposedDiff` objects exist in the claim or managed resource namespace? If they existed in a claim namespace, they *could not* have an [owner reference](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents) to the managed resource.
1. Is there a better way to apply a diff besides editing the `apply` field of the `ProposedDiff`?

#### Required Updates

The rough proposal above could be implemented as follows:
1. Add a `ProjectDiff` CRD type to core `crossplane`
1. Update the shared managed reconciler in `crossplane-runtime` to achieve desired functionality.
1. Update the embedded `resource.Claim` type in `crossplane-runtime` to include the `autoUpdate` field.
1. Bump the `crossplane-runtime` dependency in core `crossplane`.
1. Bump the `crossplane-runtime` dependency in each provider stack (this could be done incrementally when each stack desired the functionality).

**Comment by muvaf** [comment]
I can see that where you change field `X`, the actual change in the provider could correspond to `Y, Z` config that you might want to be warned of.

A _dry-run_ functionality on the client side makes more sense to me to solve this. For a controller, blindly trying to reach to desired state makes implementation/maintenance easier. So, user can see the dry run and if they are still happy they can do the `kubectl apply` and controller would do its job. Pretty much like kubectl dry-run, maybe crossplane-cli can help on that in the future.

Related to https://github.com/crossplaneio/crossplane-runtime/issues/22

**Comment by negz** [comment]
Also related to https://github.com/crossplaneio/crossplane-runtime/issues/27. I've been socialising the following idea which I believe would support this case, as well as a few others:

```yaml
# The default policy. Returns an error if the named external resource already
# exists at creation time.
externalResourcePolicy:
  create: Create
  update: Update
  delete: Delete
```

```yaml
# A "read only" policy, similar to a Terraform data source. Exposes the state
# of an existing external resource via the managed resource status object.
externalResourcePolicy:
  create: Attach
  update: Observe
  delete: Detach
```

```yaml
# The ability to attach an existing external resource to Crossplane reconciliation.
externalResourcePolicy:
  create: Attach
  update: Update
  delete: Delete
```

```yaml
# The equivalent of Crossplane's current reclaim policy implementation
externalResourcePolicy:
  create: CreateOrAttach
  update: Update
  delete: Detach
```
