### ISSUE TITLE
Proposal: Weighted random composition selection

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#967]
### What problem are you facing?

The [simple resource class selection](https://github.com/crossplaneio/crossplane/blob/31ba7418/design/one-pager-simple-class-selection.md) design introduces the ability for resource claims to select the resource classes they use by labels. When multiple resource classes match a claim's label selector a random matching resource class is selected.

Weighting the resource classes would allow us to more intelligently select a resource class when multiple match the class selector. With weighted random resource class selection when multiple resource classes matched a resource claim's label selector the class with the heaviest weight would win. If multiple classes matching the label selector shared the highest weight they would be deemed equally desirable and one would be chosen at random.

A weighted resource class would look something like:

```yaml
apiVersion: cache.gcp.crossplane.io/v1alpha2
kind: CloudMemorystoreInstanceClass
metadata:
  name: gcp-dev
  labels:
    engineVersion: "3.2"
    region: us-west
    replicated: "true"
weight: 100  # Represents the weight of the class.
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  tier: STANDARD_HA
  region: us-west2
  memorySizeGb: 1
  redisVersion: REDIS_3_2
```

Weighted random resource class selection would provide the foundation for cost based scheduling - i.e. the cheapest resource classes get the heaviest weight. A standalone admission webhook or controller could watch for newly created or updated resource classes, price them, and allocate them a weight based on their price.

### How could Crossplane help solve your problem?

The challenge with implementing weighted random resource class selection is that as described in the [technical implementation](https://github.com/crossplaneio/crossplane/blob/31ba7418/design/one-pager-simple-class-selection.md#technical-implementation) there is not a single controller handling each newly found resource claim, but rather several racing controllers. Each controller assesses the available resource classes of a particular kind, then uses random jitter to ensure a random controller wins if multiple controllers find matching resource classes. These controllers would need to coordinate to support weighted random scheduling.

Claim scheduling controllers could coordinate via a new `ClassWeight` kind:

```yaml
apiVersion: scheduling.crossplane.io/v1alpha1
kind: ClassWeight
metadata:
  # The UID of the associated class. ClassWeights are cluster scoped, like classes.
  name: eb86ac7a-f5cb-11e9-b82c-5aa538984bd8
  labels:
    # This label is used to filter ClassWeights to those pertaining to classes that
    # could satisfy a particular kind of resource claim.
    claim.crossplane.io/kind: "postgresqlinstance.database.crossplaneio/v1alpha1"
    # These labels are copied verbatim from the associated resource class.
    stack: gitlab
    grade: production
classRef:
  apiVersion: database.gcp.crossplane.io/v1alpha2
  kind: CloudSQLInstanceClass
  name: gitlab-production
  uid: eb86ac7a-f5cb-11e9-b82c-5aa538984bd8
weight: 100 # Represents the weight of the class
```

The function of a `ClassWeight` is to be a single kind of resource that all claim scheduling controllers can use to assess whether they have the highest weighted class for a particular resource claim.

When a resource class was created or updated a webhook or controller would be responsible for creating or updating a `ClassWeight` for the class. The `ClassWeight` would be labelled with the group, version and kind of the claims it could satisfy and any labels applied to its matching resource class. Crossplane users would not be expected to author or otherwise be concerned with `ClassWeight` resources - they would be a "behind the scenes" implementation detail of Crossplane.

Keep in mind that each claim scheduler owns and operates on a unique (resource claim kind, resource class kind) tuple. When a resource claim with label selectors was created each claim scheduling controller would.:

1. List all `ClassWeight` resources, filtered by those that include a `claim.crossplane.io/kind` label matching the resource claim kind they want to schedule, plus all the label selectors specified by the resource claim.
1. If there are no matching `ClassWeight` there are deemed to be no matching resource classes and the reconcile is done.
1. If there are matching `ClassWeight` the claim scheduler sorts them by their weight. If none of the equally highest weighted `ClassWeight` resources have a `classRef` of the kind the claim scheduler operates on, the reconcile is done.
1. If one or more of the equally highest weighted `ClassWeight` resources has a `classRef` of the kind the claim scheduler operates on the reconcile proceeds similarly to the current logic. The scheduler picks one of the equally highest weighted classes at random, sleeps for a randomly jittered amount of time, then attempts to set it as the class reference of the claim it is scheduling.
